/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import TNLean.MPS.Defs

import Batteries.Data.Fin
import Mathlib.Logic.Equiv.Fin.Rotate


-- @@ L11-18 verbatim
/-!
# Non-translation-invariant MPS chains

This file introduces the fixed-length periodic-chain version of an MPS tensor:
site-dependent local tensors, their ordered matrix product coefficient, the
corresponding equality notion at fixed chain length, and the cyclic gauge
relation used by the algebraic fundamental-theorem route.
-/


-- @@ L20-20 verbatim
open scoped Matrix


-- @@ L22-24 verbatim
/-- A non-translation-invariant MPS chain with physical dimension `d`, bond
dimension `D`, and `n` sites. -/
abbrev MPSChainTensor (d D n : ℕ) := Fin n → MPSTensor d D


-- @@ L26-26 verbatim
namespace MPSChainTensor


-- @@ L28-28 verbatim
variable {d D n : ℕ}


-- @@ L30-33 verbatim
/-- Ordered matrix product along a periodic chain. -/
def eval (A : MPSChainTensor d D n) (σ : Fin n → Fin d) :
    Matrix (Fin D) (Fin D) ℂ :=
  Fin.prod fun k => A k (σ k)


-- @@ L35-38 verbatim
/-- The coefficient of the basis configuration `σ`, obtained by tracing the
ordered product of the selected local matrices. -/
def coeff (A : MPSChainTensor d D n) (σ : Fin n → Fin d) : ℂ :=
  Matrix.trace (eval A σ)


-- @@ L40-42 verbatim
/-- Two non-TI chains generate the same state at the fixed system size `n`. -/
def SameState (A B : MPSChainTensor d D n) : Prop :=
  ∀ σ : Fin n → Fin d, coeff A σ = coeff B σ


-- @@ L44-46 verbatim
/-- Every local tensor in the chain is injective. -/
def IsInjective (A : MPSChainTensor d D n) : Prop :=
  ∀ k : Fin n, Kraus.IsInjective (A k)


-- @@ L48-50 verbatim
/-- Cyclic successor on `Fin n`, sending the last site back to `0`. -/
def cyclicSucc : Fin n → Fin n :=
  finRotate n


-- @@ L52-54 verbatim
@[simp] lemma cyclicSucc_val (k : Fin (n + 1)) :
    (cyclicSucc k).val = (k.val + 1) % (n + 1) := by
  simp [cyclicSucc, Fin.val_add]


-- @@ L56-59 verbatim
/-- The cyclic successor is addition by one on `Fin n`. -/
@[simp] lemma cyclicSucc_eq_add_one [NeZero n] (k : Fin n) :
    cyclicSucc k = k + 1 := by
  simp [cyclicSucc, finRotate_apply]


-- @@ L61-61 verbatim
/-! ### Cyclic shift of a closed chain -/


-- @@ L63-65 verbatim
/-- The site-dependent closed chain shifted by one site. -/
def cyclicShift (A : MPSChainTensor d D n) : MPSChainTensor d D n :=
  fun k => A (cyclicSucc k)


-- @@ L67-70 verbatim
/-- The state generated by a site-dependent closed chain is invariant under
the cyclic shift of the local tensors. -/
def IsCyclicShiftInvariantState (A : MPSChainTensor d D n) : Prop :=
  SameState A (cyclicShift A)


-- @@ L72-76 verbatim
/-- Cyclic shifting preserves sitewise injectivity. -/
theorem IsInjective.cyclicShift {A : MPSChainTensor d D n} (hA : IsInjective A) :
    IsInjective (cyclicShift A) := by
  intro k
  exact hA (cyclicSucc k)


-- @@ L78-83 verbatim
/-- Cyclic gauge equivalence on a periodic chain:
`Bₖ^σ = Zₖ Aₖ^σ Zₖ₊₁⁻¹`, where the successor is taken modulo `n`. -/
def GaugeEquiv (A B : MPSChainTensor d D n) : Prop :=
  ∃ Z : Fin n → GL (Fin D) ℂ, ∀ k : Fin n, ∀ i : Fin d,
    B k i = (Z k : Matrix (Fin D) (Fin D) ℂ) * A k i *
      (((Z (cyclicSucc k))⁻¹ : GL (Fin D) ℂ) : Matrix (Fin D) (Fin D) ℂ)


-- @@ L85-87 verbatim
@[simp] lemma eval_zero (A : MPSChainTensor d D 0) (σ : Fin 0 → Fin d) :
    eval A σ = 1 := by
  simp [eval]


-- @@ L89-92 verbatim
@[simp] lemma eval_succ (A : MPSChainTensor d D (n + 1)) (σ : Fin (n + 1) → Fin d) :
    eval A σ = A 0 (σ 0) * eval (fun k => A k.succ) (fun k => σ k.succ) := by
  -- `Fin.prod_succ` splits off the first factor in the ordered product.
  simpa [eval] using Fin.prod_succ (fun k : Fin (n + 1) => A k (σ k))


-- @@ L94-95 verbatim
@[simp] lemma coeff_eq (A : MPSChainTensor d D n) (σ : Fin n → Fin d) :
    coeff A σ = Matrix.trace (eval A σ) := rfl


-- @@ L97-98 verbatim
theorem SameState.refl (A : MPSChainTensor d D n) : SameState A A :=
  fun _ => rfl


-- @@ L100-102 verbatim
theorem SameState.symm {A B : MPSChainTensor d D n} (h : SameState A B) :
    SameState B A :=
  fun σ => (h σ).symm


-- @@ L104-107 verbatim
theorem SameState.trans {A B C : MPSChainTensor d D n}
    (hAB : SameState A B) (hBC : SameState B C) :
    SameState A C :=
  fun σ => (hAB σ).trans (hBC σ)


-- @@ L109-113 verbatim
/-- `SameState` is an equivalence relation. -/
theorem instEquivalenceSameState : Equivalence (SameState (d := d) (D := D) (n := n)) where
  refl := SameState.refl
  symm := SameState.symm
  trans := SameState.trans


-- @@ L115-118 verbatim
theorem GaugeEquiv.refl (A : MPSChainTensor d D n) : GaugeEquiv A A := by
  refine ⟨fun _ => 1, ?_⟩
  intro k i
  simp


-- @@ L120-126 verbatim
theorem GaugeEquiv.symm {A B : MPSChainTensor d D n} (h : GaugeEquiv A B) :
    GaugeEquiv B A := by
  obtain ⟨Z, hZ⟩ := h
  refine ⟨fun k => (Z k)⁻¹, ?_⟩
  intro k i
  rw [hZ k i]
  simp [Matrix.mul_assoc]


-- @@ L128-136 verbatim
theorem GaugeEquiv.trans {A B C : MPSChainTensor d D n}
    (hAB : GaugeEquiv A B) (hBC : GaugeEquiv B C) :
    GaugeEquiv A C := by
  obtain ⟨Z, hZ⟩ := hAB
  obtain ⟨Y, hY⟩ := hBC
  refine ⟨fun k => Y k * Z k, ?_⟩
  intro k i
  rw [hY k i, hZ k i]
  simp [Matrix.mul_assoc, mul_inv_rev]


-- @@ L138-142 verbatim
/-- `GaugeEquiv` is an equivalence relation. -/
theorem instEquivalenceGaugeEquiv : Equivalence (GaugeEquiv (d := d) (D := D) (n := n)) where
  refl := GaugeEquiv.refl
  symm := GaugeEquiv.symm
  trans := GaugeEquiv.trans


-- @@ L144-144 verbatim
end MPSChainTensor
