/-
Copyright (c) 2026 TNLean contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: TNLean contributors
-/
import QICLean.Algebra.NilMatrixSubalgebra
import TNLean.MPS.Core.Reduction


-- @@ L9-20 verbatim
/-!
# Residual data for a rectangular MPS reduction

For a selected reduction from `B` to `A`, this file defines the residual
letters $N^i=B^i-WA^iV$, their generated nonunital algebra and nilpotency
length, and the sums that occur in the residual expansions of MGSC18.

**Local fix (arXiv:1706.07329v2, Lemma `B_expand`, lines 3993--4005):** the
printed weak-range expansion is false.  The strict-window definitions below
use a pure residual term and a nonempty central window, as documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`.
-/


-- @@ L22-22 verbatim
open scoped Matrix BigOperators


-- @@ L24-24 verbatim
namespace MPSTensor


-- @@ L26-26 verbatim
variable {d D_A D_B : ℕ}


-- @@ L28-35 verbatim
/-- The reduction-specific residual letter $N^i=B^i-WA^iV$.

Source: Molnár--Ge--Schuch--Cirac, arXiv:1706.07329v2, Proposition 21,
`cornerproblem.tex` lines 3142--3144. -/
noncomputable def reductionResidual (B : MPSTensor d D_B) (A : MPSTensor d D_A)
    (V : Matrix (Fin D_A) (Fin D_B) ℂ) (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    MPSTensor d D_B :=
  fun i ↦ B i - W * A i * V


-- @@ L37-41 verbatim
/-- The set of residual letters belonging to one selected reduction. -/
noncomputable def reductionResidualGeneratorSet (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) : Set (Matrix (Fin D_B) (Fin D_B) ℂ) :=
  Set.range (reductionResidual B A V W)


-- @@ L43-51 verbatim
/-- The nonunital algebra generated by the residual letters of one selected reduction.

Source: arXiv:1706.07329v2, Proposition 21 and its proof,
`cornerproblem.tex` lines 3972--3986. -/
noncomputable def reductionResidualAlgebra (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    NonUnitalSubalgebra ℂ (Matrix (Fin D_B) (Fin D_B) ℂ) :=
  NonUnitalAlgebra.adjoin ℂ (reductionResidualGeneratorSet B A V W)


-- @@ L53-64 verbatim
/-- An exact-length residual-word nilpotency bound for a selected reduction:
every word of exactly this length in the residual letters vanishes.  Definition 8
requires vanishing at every greater length; the two formulations are equivalent
by splitting a longer word after the bounded prefix.

Source: arXiv:1706.07329v2, Definition 8, `cornerproblem.tex` lines
3147--3152. -/
def IsReductionResidualNilpotencyBound (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) (N : ℕ) : Prop :=
  ∀ w : List (Fin d), w.length = N →
    Kraus.evalWord (reductionResidual B A V W) w = 0


-- @@ L66-74 verbatim
/-- The least exact-length residual-word bound.  Prefix factorization identifies
it with the nilpotency length of the selected reduction in MGSC18.

Source: arXiv:1706.07329v2, Definition 8, `cornerproblem.tex` lines
3147--3152. -/
noncomputable def reductionResidualNilpotencyLength (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) : ℕ :=
  sInf {N | IsReductionResidualNilpotencyBound B A V W N}


-- @@ L76-90 verbatim
/-- The strict-window terms whose central $A$-word starts at the first
letter of the input word.  The recursion enumerates every nonempty initial
central word exactly once.

Source: arXiv:1706.07329v2, corrected form of Lemma `lem:B_expand`,
`cornerproblem.tex` lines 3993--4005.  The correction is documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`. -/
noncomputable def reductionInitialWindowSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    List (Fin d) → Matrix (Fin D_B) (Fin D_B) ℂ
  | [] => 0
  | i :: w => W * A i * V *
      (Kraus.evalWord (reductionResidual B A V W) w +
        reductionInitialWindowSum B A V W w)


-- @@ L92-107 verbatim
/-- The recursive form of the sum over all strict windows
$0\leq r<s\leq |w|$.  Its summand is
$N^{w_{<r}} W A^{w_{[r,s)}} V N^{w_{\geq s}}$.  The first recursive term
collects windows with `r = 0`; the second shifts every window in the tail and
therefore collects `0 < r < s`.

Source: arXiv:1706.07329v2, corrected form of Lemma `lem:B_expand`,
`cornerproblem.tex` lines 3993--4005.  The correction is documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`. -/
noncomputable def reductionStrictWindowSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    List (Fin d) → Matrix (Fin D_B) (Fin D_B) ℂ
  | [] => 0
  | i :: w => reductionInitialWindowSum B A V W (i :: w) +
      reductionResidual B A V W i * reductionStrictWindowSum B A V W w


-- @@ L109-121 verbatim
/-- The explicit sum over the strict windows that start at the first letter.
The index `k : Fin w.length` gives the nonempty central length `k + 1`.

Source: arXiv:1706.07329v2, corrected form of Lemma `lem:B_expand`,
`cornerproblem.tex` lines 3993--4005.  The correction is documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`. -/
noncomputable def reductionInitialWindowRangeSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) (w : List (Fin d)) :
    Matrix (Fin D_B) (Fin D_B) ℂ :=
  ∑ k : Fin w.length,
    W * Kraus.evalWord A (w.take (k.1 + 1)) * V *
      Kraus.evalWord (reductionResidual B A V W) (w.drop (k.1 + 1))


-- @@ L123-140 verbatim
/-- The explicit corrected strict-window sum.  Its indices are a start
`r : Fin w.length` and a positive central length `k + 1` within `w.drop r`.
Thus `s = r + k + 1` runs bijectively over $0\leq r<s\leq |w|$, and the
summand is
$N^{w_{<r}} W A^{w_{[r,s)}} V N^{w_{\geq s}}$.

Source: arXiv:1706.07329v2, corrected form of Lemma `lem:B_expand`,
`cornerproblem.tex` lines 3993--4005.  The correction is documented in
`docs/paper-gaps/mgsc18_residual_expansion_empty_word_error.tex`. -/
noncomputable def reductionStrictWindowRangeSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) (w : List (Fin d)) :
    Matrix (Fin D_B) (Fin D_B) ℂ :=
  ∑ r : Fin w.length, ∑ k : Fin (w.drop r.1).length,
    Kraus.evalWord (reductionResidual B A V W) (w.take r.1) * W *
      Kraus.evalWord A ((w.drop r.1).take (k.1 + 1)) * V *
        Kraus.evalWord (reductionResidual B A V W)
          ((w.drop r.1).drop (k.1 + 1))


-- @@ L142-157 verbatim
/-- The all-cut left-contracted sum
$\sum_{s=0}^{|w|} A^{w_{<s}}V N^{w_{\geq s}}$.
When a nilpotency bound is available, terms with residual suffix at least that
long vanish, giving the truncated left contraction printed in MGSC18,
Lemma `B_expand`.

Source: derived all-cut precursor to the first contracted formula in
arXiv:1706.07329v2, `cornerproblem.tex` line 3997. -/
noncomputable def reductionLeftContractedSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    List (Fin d) → Matrix (Fin D_A) (Fin D_B) ℂ
  | [] => V
  | i :: w => V * reductionResidual B A V W i *
      Kraus.evalWord (reductionResidual B A V W) w +
      A i * reductionLeftContractedSum B A V W w


-- @@ L159-173 verbatim
/-- The all-cut right-contracted sum
$\sum_{r=0}^{|w|}N^{w_{<r}}W A^{w_{\geq r}}$.
When a nilpotency bound is available, terms with residual prefix at least that
long vanish, giving the truncated right contraction printed in MGSC18,
Lemma `B_expand`.

Source: derived all-cut precursor to the second contracted formula in
arXiv:1706.07329v2, `cornerproblem.tex` line 3998. -/
noncomputable def reductionRightContractedSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) :
    List (Fin d) → Matrix (Fin D_B) (Fin D_A) ℂ
  | [] => W
  | i :: w => W * A i * Kraus.evalWord A w +
      reductionResidual B A V W i * reductionRightContractedSum B A V W w


-- @@ L175-187 verbatim
/-- The printed left-contracted range
$|w|-N\leq s\leq |w|$.  The endpoint with residual suffix of length exactly
`N` is retained; it vanishes when `N` is a residual nilpotency bound.

Source: arXiv:1706.07329v2, Lemma `lem:B_expand`, the first contracted formula
in `cornerproblem.tex` line 3997. -/
noncomputable def reductionLeftContractedRangeSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) (N : ℕ) (w : List (Fin d)) :
    Matrix (Fin D_A) (Fin D_B) ℂ :=
  ∑ s ∈ Finset.Icc (w.length - N) w.length,
    Kraus.evalWord A (w.take s) * V *
      Kraus.evalWord (reductionResidual B A V W) (w.drop s)


-- @@ L189-201 verbatim
/-- The printed right-contracted range
$0\leq r\leq \min(N,|w|)$.  The endpoint with residual prefix of length
exactly `N` is retained; it vanishes when `N` is a residual nilpotency bound.

Source: arXiv:1706.07329v2, Lemma `lem:B_expand`, the second contracted formula
in `cornerproblem.tex` line 3998. -/
noncomputable def reductionRightContractedRangeSum (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) (N : ℕ) (w : List (Fin d)) :
    Matrix (Fin D_B) (Fin D_A) ℂ :=
  ∑ r ∈ Finset.Icc 0 (min N w.length),
    Kraus.evalWord (reductionResidual B A V W) (w.take r) * W *
      Kraus.evalWord A (w.drop r)


-- @@ L203-210 verbatim
/-- Every selected-reduction residual letter belongs to its generated algebra. -/
theorem reductionResidual_mem_reductionResidualAlgebra
    (B : MPSTensor d D_B) (A : MPSTensor d D_A)
    (V : Matrix (Fin D_A) (Fin D_B) ℂ) (W : Matrix (Fin D_B) (Fin D_A) ℂ)
    (i : Fin d) :
    reductionResidual B A V W i ∈ reductionResidualAlgebra B A V W := by
  apply NonUnitalAlgebra.subset_adjoin ℂ
  exact ⟨i, rfl⟩


-- @@ L212-223 verbatim
/-- The residual letters $N^i=B^i-WA^iV$ are unchanged by the reciprocal scalar
rescaling $W\mapsto\beta W$, $V\mapsto\beta^{-1}V$: the two scalars meet inside
the product $WA^iV$ and cancel.

Under the identification $F^<=V$, $F^>=W$ this is the scalar gauge freedom of
arXiv:2502.20257, `eq:scalar_fus_ten`, `main.tex` lines 1500--1504. -/
theorem reductionResidual_reciprocal_smul (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) {β : ℂ} (hβ : β ≠ 0) :
    reductionResidual B A (β⁻¹ • V) (β • W) = reductionResidual B A V W := by
  funext i
  simp (disch := exact hβ) only [reductionResidual, matrix_reciprocal_smul]


-- @@ L225-233 verbatim
/-- The reciprocal scalar rescaling preserves every exact-length residual-word
nilpotency bound, in both directions. -/
theorem isReductionResidualNilpotencyBound_reciprocal_smul (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) {β : ℂ} (hβ : β ≠ 0) (N : ℕ) :
    IsReductionResidualNilpotencyBound B A (β⁻¹ • V) (β • W) N ↔
      IsReductionResidualNilpotencyBound B A V W N := by
  unfold IsReductionResidualNilpotencyBound
  rw [reductionResidual_reciprocal_smul B A V W hβ]


-- @@ L235-247 verbatim
/-- The MGSC18 nilpotency length of a reduction is unchanged by the reciprocal
scalar rescaling. -/
theorem reductionResidualNilpotencyLength_reciprocal_smul (B : MPSTensor d D_B)
    (A : MPSTensor d D_A) (V : Matrix (Fin D_A) (Fin D_B) ℂ)
    (W : Matrix (Fin D_B) (Fin D_A) ℂ) {β : ℂ} (hβ : β ≠ 0) :
    reductionResidualNilpotencyLength B A (β⁻¹ • V) (β • W) =
      reductionResidualNilpotencyLength B A V W := by
  have hset : {N | IsReductionResidualNilpotencyBound B A (β⁻¹ • V) (β • W) N} =
      {N | IsReductionResidualNilpotencyBound B A V W N} := by
    ext N
    exact isReductionResidualNilpotencyBound_reciprocal_smul B A V W hβ N
  unfold reductionResidualNilpotencyLength
  rw [hset]


-- @@ L249-249 verbatim
end MPSTensor
