/-
Copyright (c) 2026 Quang Dao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module
public import Mathlib.Data.Real.ENatENNReal
public import VCVio.CryptoFoundations.FiatShamir.Sigma.Stateful.Bridge
public import VCVio.ProgramLogic.Relational.Quantitative
public import VCVio.StateSeparating.IdenticalUntilBad


-- @@ L13-18 verbatim
/-!
# Native stateful Fiat-Shamir CMA game hops

The theorems here are stated directly over `QueryImpl.Stateful` handlers and the
concrete `CmaState` product state.
-/


-- @@ L20-20 verbatim
@[expose] public section


-- @@ L22-22 verbatim
universe u


-- @@ L24-24 verbatim
open ENNReal OracleSpec OracleComp ProbComp

-- @@ L25-25 verbatim
open OracleComp.ProgramLogic.Relational


-- @@ L27-27 verbatim
namespace FiatShamir.Stateful


-- @@ L29-29 verbatim
variable (M : Type) [DecidableEq M]

-- @@ L30-30 verbatim
variable (Commit : Type) [DecidableEq Commit]

-- @@ L31-31 verbatim
variable (Chal : Type) [SampleableType Chal]

-- @@ L32-32 verbatim
variable {Stmt Wit : Type} {rel : Stmt → Wit → Bool}

-- @@ L33-33 verbatim
variable {Resp PrvState : Type}


-- @@ L35-35 verbatim
/-! ## H3 state invariants and per-query loss -/


-- @@ L37-40 verbatim
/-- Initial direct CMA data, without the trailing bad flag. -/
@[reducible] def cmaDataInit (M Commit Chal Stmt Wit : Type) :
    CmaData M Commit Chal Stmt Wit :=
  ([], ∅, none)


-- @@ L42-46 verbatim
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
/-- The direct CMA initial state is the initial data with bad unset. -/
@[simp]
lemma cmaInit_eq_cmaDataInit :
    cmaInit M Commit Chal Stmt Wit = (cmaDataInit M Commit Chal Stmt Wit, false) := rfl


-- @@ L48-58 verbatim
/-- Reachability invariant for the direct CMA data.

Cached keypairs, when present, must satisfy the relation generated by `hr.gen`.
The invariant is intentionally phrased on `CmaData`, not heap cells. -/
def CmaData.Valid
    {M : Type} {Commit : Type} {Chal Stmt Wit : Type}
    {rel : Stmt → Wit → Bool}
    (s : CmaData M Commit Chal Stmt Wit) : Prop :=
  match s.2.2 with
  | none => True
  | some (pk, sk) => rel pk sk = true


-- @@ L60-66 verbatim
instance
    {M : Type} {Commit : Type} {Chal Stmt Wit : Type}
    {rel : Stmt → Wit → Bool}
    (s : CmaData M Commit Chal Stmt Wit) :
    Decidable (CmaData.Valid (rel := rel) s) := by
  unfold CmaData.Valid
  rcases s.2.2 with _ | ⟨pk, sk⟩ <;> infer_instance


-- @@ L68-73 verbatim
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
/-- The initial direct CMA data has no cached keypair, hence satisfies the
valid-keypair invariant. -/
lemma cmaDataInit_valid :
    CmaData.Valid (rel := rel) (cmaDataInit M Commit Chal Stmt Wit) := by
  simp [CmaData.Valid]


-- @@ L75-78 verbatim
/-- Tight state-dependent per-signing-query loss for H3 on reachable states. -/
noncomputable def cmaSignEpsCore
    (ζ_zk β : ℝ≥0∞) (s : CmaData M Commit Chal Stmt Wit) : ℝ≥0∞ :=
  ζ_zk + QueryCache.enncard s.2.1 * β


-- @@ L80-90 verbatim
/-- State-dependent per-signing-query loss for H3.

On reachable states this is `ζ_zk + QueryCache.enncard · β`. Invalid keypair states
receive the conservative fallback cost `1`, which is useful for ungated
identical-until-bad statements. -/
noncomputable def cmaSignEps
    (ζ_zk β : ℝ≥0∞) (s : CmaData M Commit Chal Stmt Wit) : ℝ≥0∞ :=
  if CmaData.Valid (rel := rel) s then
    cmaSignEpsCore M Commit Chal ζ_zk β s
  else
    1


-- @@ L92-92 verbatim
/-! ## H3 proof obligations -/


-- @@ L94-98 verbatim
/-- Signing queries are the charged queries in the H3 hop. -/
abbrev cmaH3Costly :
    (cmaSpec M Commit Chal Resp Stmt).Domain → Prop :=
  IsCostlyQuery (M := M) (Commit := Commit) (Chal := Chal)
    (Resp := Resp) (Stmt := Stmt)


-- @@ L100-111 verbatim
/-- Boolean distinguishing advantage for the native H3 pair from the direct
initial CMA state. -/
noncomputable abbrev cmaH3Advantage
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool) : ℝ :=
  (cmaReal M Commit Chal σ hr).advantage
    (cmaInit M Commit Chal Stmt Wit)
    (cmaSim M Commit Chal hr simT)
    (cmaInit M Commit Chal Stmt Wit)
    A


-- @@ L113-125 verbatim
/-- Expected accumulated H3 signing loss in the real game. -/
noncomputable abbrev cmaH3ExpectedLoss
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α)
    (qS : ℕ) : ℝ≥0∞ :=
  expectedQuerySlack (cmaReal M Commit Chal σ hr)
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt))
    (cmaSignEpsCore M Commit Chal ζ_zk β) A qS
    (cmaInit M Commit Chal Stmt Wit)


-- @@ L127-160 verbatim
/-- Per-query facts for the native H3 hop. -/
structure CmaH3StepFacts
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞) : Prop where
  /-- The real game preserves keypair validity while bad is false. -/
  preservesValid :
    (cmaReal M Commit Chal σ hr).PreservesNoBadInvariant
      (CmaData.Valid (rel := rel))
  /-- Signing queries are close by the state-dependent H3 loss. -/
  stepTvCostly :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
      cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt) t →
      ∀ (s : CmaData M Commit Chal Stmt Wit),
        CmaData.Valid (rel := rel) s →
          ENNReal.ofReal (tvDist
            (((cmaReal M Commit Chal σ hr) t).run (s, false))
            (((cmaSim M Commit Chal hr simT) t).run (s, false)))
            ≤ cmaSignEpsCore M Commit Chal ζ_zk β s
  /-- Non-signing queries agree pointwise. -/
  stepEqFree :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain),
      ¬ cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t →
      ∀ (p : CmaState M Commit Chal Stmt Wit),
        ((cmaReal M Commit Chal σ hr) t).run p =
          ((cmaSim M Commit Chal hr simT) t).run p
  /-- Once the real bad flag is true, it stays true. -/
  badMono :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
      (p : CmaState M Commit Chal Stmt Wit), p.2 = true →
        ∀ z ∈ support (((cmaReal M Commit Chal σ hr) t).run p), z.2.2 = true


-- @@ L162-180 expanded
/-- Computation-specific facts for applying the native H3 hop. -/
structure CmaH3RunFacts (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool) (qS : ℕ) (εBound : ℝ≥0∞) : Prop where
  /-- The adversary issues at most `qS` signing queries. -/
  queryBound :
    OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal) (Resp := Resp) (Stmt := Stmt)) qS
  /-- The real game never reaches bad from the initial state. -/
  badZero :
    (probEvent ((simulateQ (cmaReal M Commit Chal σ hr) A).run (cmaInit M Commit Chal Stmt Wit))
        fun z : Bool × CmaState M Commit Chal Stmt Wit => z.2.2 = true) =
      0
  /-- The expected accumulated signing loss is at most the requested bound. -/
  expectedLossLe : cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤ εBound


-- @@ L182-182 verbatim
/-! ## Real-game bad flag facts -/


-- @@ L184-203 verbatim
/-- Stepwise preservation of a trailing Boolean flag lifts through
`simulateQ`. -/
theorem simulateQ_bad_preserved_of_step
    {ι ι' : Type} {spec : OracleSpec ι} {spec' : OracleSpec ι'}
    [IsUniformSpec spec']
    {σ : Type} {α : Type}
    (impl : QueryImpl spec (StateT (σ × Bool) (OracleComp spec')))
    (hstep : ∀ (t : spec.Domain) (p : σ × Bool) (z),
      z ∈ support ((impl t).run p) → z.2.2 = p.2)
    (oa : OracleComp spec α) (p : σ × Bool) {z : α × σ × Bool}
    (hz : z ∈ support ((simulateQ impl oa).run p)) :
    z.2.2 = p.2 := by
  induction oa using OracleComp.inductionOn generalizing p z with
  | pure x => simp_all
  | query_bind t k ih =>
      simp only [simulateQ_bind, simulateQ_query, OracleQuery.cont_query,
        OracleQuery.input_query, id_map, StateT.run_bind, support_bind,
        Set.mem_iUnion, exists_prop] at hz
      obtain ⟨up, hup, hz⟩ := hz
      exact (ih up.1 up.2 hz).trans (hstep t p up hup)


-- @@ L205-284 verbatim
/-- Unified per-step structure of `cmaReal`: at every query, the bad flag is
preserved, the `Valid` predicate is preserved on the data, and the random-oracle
cache count grows by at most one if and only if the query is `cmaH3Costly` or
`IsHashQuery`. The three callable corollaries below are projections of this
single case-blast. -/
private theorem cmaReal_step_normal_form
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    z.2.2 = p.2 ∧
    (CmaData.Valid (rel := rel) p.1 → CmaData.Valid (rel := rel) z.2.1) ∧
    QueryCache.enncard z.2.1.2.1 ≤ QueryCache.enncard p.1.2.1 +
      (if cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt) t ∨
          IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
            (Resp := Resp) (Stmt := Stmt) t then (1 : ℝ≥0∞) else 0) := by
  rcases p with ⟨⟨log, cache, keypair⟩, bad⟩
  rcases t with n | mc | m | ⟨⟩
  · simp only [fs_simp, cmaH3Costly, IsCostlyQuery, IsHashQuery, false_or, if_false,
      StateT.run_mk, support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
      exists_prop] at hz ⊢
    obtain ⟨r, _, rfl⟩ := hz
    exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, by simp⟩
  · simp only [fs_simp, cmaH3Costly, IsCostlyQuery, IsHashQuery, false_or, if_true,
      StateT.run_mk] at hz ⊢
    cases hcache : cache mc with
    | none =>
        simp only [hcache, support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
          exists_prop] at hz
        obtain ⟨r, _, rfl⟩ := hz
        exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h,
          QueryCache.enncard_cacheQuery_le cache mc r⟩
    | some r =>
        simp only [hcache, support_pure, Set.mem_singleton_iff] at hz
        subst z
        exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, le_self_add⟩
  · simp only [fs_simp, cmaH3Costly, IsCostlyQuery, IsHashQuery, true_or, if_true,
      StateT.run_mk] at hz ⊢
    rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [support_bind, Set.mem_iUnion, exists_prop] at hz
      obtain ⟨pk_sk, hgen, i, _, hrest⟩ := hz
      cases hcache : cache (m, i.1) with
      | none =>
          simp only [hcache, support_bind, Set.mem_iUnion, exists_prop, support_pure,
            Set.mem_singleton_iff] at hrest
          obtain ⟨ch, _, π, _, rfl⟩ := hrest
          exact ⟨rfl, fun _ => hr.gen_sound pk_sk.1 pk_sk.2 hgen,
            QueryCache.enncard_cacheQuery_le cache (m, i.1) ch⟩
      | some ch =>
          simp only [hcache, support_bind, Set.mem_iUnion, support_pure,
            Set.mem_singleton_iff, exists_prop] at hrest
          obtain ⟨π, _, rfl⟩ := hrest
          exact ⟨rfl, fun _ => hr.gen_sound pk_sk.1 pk_sk.2 hgen, le_self_add⟩
    · simp only [support_bind, Set.mem_iUnion, exists_prop] at hz
      obtain ⟨i, _, hrest⟩ := hz
      cases hcache : cache (m, i.1) with
      | none =>
          simp only [hcache, support_bind, Set.mem_iUnion, support_pure,
            Set.mem_singleton_iff, exists_prop] at hrest
          obtain ⟨ch, _, π, _, rfl⟩ := hrest
          exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h,
            QueryCache.enncard_cacheQuery_le cache (m, i.1) ch⟩
      | some ch =>
          simp only [hcache, support_bind, Set.mem_iUnion, support_pure,
            Set.mem_singleton_iff, exists_prop] at hrest
          obtain ⟨π, _, rfl⟩ := hrest
          exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, le_self_add⟩
  · simp only [fs_simp, cmaReal, cmaH3Costly, IsCostlyQuery, IsHashQuery, false_or,
      if_false, StateT.run_mk] at hz ⊢
    rcases keypair with keypair | ⟨pk, sk⟩
    · simp only [support_bind, Set.mem_iUnion, support_pure, Set.mem_singleton_iff,
        exists_prop] at hz
      obtain ⟨pk_sk, hgen, rfl⟩ := hz
      exact ⟨rfl, fun _ => hr.gen_sound pk_sk.1 pk_sk.2 hgen, by simp⟩
    · simp only [support_pure, Set.mem_singleton_iff] at hz
      subst z
      exact ⟨rfl, fun h => by simpa [CmaData.Valid] using h, by simp⟩


-- @@ L286-295 verbatim
/-- One step of the real CMA game preserves the bad flag exactly. -/
theorem cmaReal_bad_preserved
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    z.2.2 = p.2 :=
  (cmaReal_step_normal_form M Commit Chal σ hr t p z hz).1


-- @@ L297-305 verbatim
/-- Once the real CMA bad flag is true, one real step keeps it true. -/
theorem cmaReal_bad_mono
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) :
    ∀ (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
      (p : CmaState M Commit Chal Stmt Wit), p.2 = true →
        ∀ z ∈ support (((cmaReal M Commit Chal σ hr) t).run p), z.2.2 = true := by
  intro t p hp z hz
  exact (cmaReal_bad_preserved M Commit Chal σ hr t p z hz).trans hp


-- @@ L307-324 expanded
/-- The real CMA game never reaches bad from the initial state. -/
theorem cmaReal_probEvent_bad_eq_zero (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α) :
    (probEvent ((simulateQ (cmaReal M Commit Chal σ hr) A).run (cmaInit M Commit Chal Stmt Wit))
        fun z : α × CmaState M Commit Chal Stmt Wit => z.2.2 = true) =
      0 :=
  by
  rw [probEvent_eq_zero_iff]
  intro z hz hbad
  have hpres :=
    simulateQ_bad_preserved_of_step (impl := cmaReal M Commit Chal σ hr)
      (fun t p z hz => cmaReal_bad_preserved M Commit Chal σ hr t p z hz) A
      (cmaInit M Commit Chal Stmt Wit) hz
  change z.2.2 = false at hpres
  rw [hpres] at hbad
  contradiction


-- @@ L326-336 verbatim
/-- One real CMA step preserves keypair validity. -/
theorem cmaReal_valid_preserved
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (hpvalid : CmaData.Valid (rel := rel) p.1)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    CmaData.Valid (rel := rel) z.2.1 :=
  (cmaReal_step_normal_form M Commit Chal σ hr t p z hz).2.1 hpvalid


-- @@ L338-345 verbatim
/-- The real CMA handler preserves keypair validity while bad is false. -/
theorem cmaReal_preserves_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) :
    (cmaReal M Commit Chal σ hr).PreservesNoBadInvariant
      (CmaData.Valid (rel := rel)) := by
  intro t p _ hpvalid z hz
  exact cmaReal_valid_preserved M Commit Chal σ hr t p hpvalid z hz


-- @@ L347-361 verbatim
/-- One real CMA step grows the direct random-oracle cache by at most one on
signing or hash queries, and does not grow it on other queries. -/
theorem cmaReal_roCacheCount_step_le
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (p : CmaState M Commit Chal Stmt Wit)
    (z : (cmaSpec M Commit Chal Resp Stmt).Range t × CmaState M Commit Chal Stmt Wit)
    (hz : z ∈ support (((cmaReal M Commit Chal σ hr) t).run p)) :
    QueryCache.enncard z.2.1.2.1 ≤ QueryCache.enncard p.1.2.1 +
      if cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t ∨
        IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
          (Resp := Resp) (Stmt := Stmt) t then (1 : ℝ≥0∞) else 0 :=
  (cmaReal_step_normal_form M Commit Chal σ hr t p z hz).2.2


-- @@ L363-406 verbatim
/-- Expected H3 loss from direct signing and hash query bounds.

If the adversary makes at most `qS` signing queries and at most `qH` random
oracle queries, the accumulated state-dependent signing slack is bounded by the
standard `qS * ζ + qS * (qS + qH) * β` expression. -/
theorem cmaH3ExpectedLoss_le_queryBounds
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    {α : Type}
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) α)
    {qS qH : ℕ}
    (h_qS : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_qH : OracleComp.IsQueryBoundP A
      (IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qH) :
    cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤
      (qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β := by
  change expectedQuerySlack (cmaReal M Commit Chal σ hr)
    (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt))
    (fun s : CmaData M Commit Chal Stmt Wit ↦ ζ_zk + QueryCache.enncard s.2.1 * β)
    A qS (cmaDataInit M Commit Chal Stmt Wit, false) ≤ _
  simpa [cmaDataInit, add_assoc] using
    expectedQuerySlack_resource_le
      (impl := cmaReal M Commit Chal σ hr)
      (chargedQuery := cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt))
      (growthQuery := IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt))
      (R := fun s : CmaData M Commit Chal Stmt Wit => QueryCache.enncard s.2.1)
      (ζ := ζ_zk) (β := β)
      (h_growth := by
        intro t p _ htg z hz
        simpa [htg] using cmaReal_roCacheCount_step_le M Commit Chal σ hr t p z hz)
      (h_free := by
        intro t p _ hnotCostly hnotHash z hz
        simpa [hnotCostly, hnotHash] using
          cmaReal_roCacheCount_step_le M Commit Chal σ hr t p z hz)
      (oa := A) (qS := qS) (qH := qH)
      (h_qS := h_qS) (h_qH := h_qH)
      (s := cmaDataInit M Commit Chal Stmt Wit)


-- @@ L408-423 verbatim
/-- Build the native H3 run facts from the query bound and expected-loss bound. -/
theorem cmaH3RunFacts_of_queryBound_expectedLoss
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    (qS : ℕ) (εBound : ℝ≥0∞)
    (h_queryBound : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_expectedLoss :
      cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS ≤ εBound) :
    CmaH3RunFacts M Commit Chal σ hr ζ_zk β A qS εBound where
  queryBound := h_queryBound
  badZero := cmaReal_probEvent_bad_eq_zero M Commit Chal σ hr A
  expectedLossLe := h_expectedLoss


-- @@ L425-425 verbatim
/-! ## Non-signing step equality -/


-- @@ L427-448 verbatim
/-- The real and simulated CMA handlers agree on every non-signing query. -/
theorem cmaReal_eq_cmaSim_of_not_costly
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (ht : ¬ cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt) t)
    (p : CmaState M Commit Chal Stmt Wit) :
    ((cmaReal M Commit Chal σ hr) t).run p =
      ((cmaSim M Commit Chal hr simT) t).run p := by
  rcases p with ⟨⟨log, cache, keypair⟩, bad⟩
  rcases t with n | mc | m | ⟨⟩
  · simp [fs_simp, QueryImpl.Stateful.linkWith_apply_run,
      QueryImpl.Stateful.Frame.linkReshape]
  · cases hcache : cache mc <;>
      simp [fs_simp, QueryImpl.Stateful.linkWith_apply_run,
        QueryImpl.Stateful.Frame.linkReshape, hcache]
  · exact (ht True.intro).elim
  · rcases keypair with _ | ⟨pk, sk⟩ <;>
      simp [fs_simp, QueryImpl.Stateful.linkWith_apply_run,
        QueryImpl.Stateful.Frame.linkReshape]


-- @@ L450-450 verbatim
/-! ## Native signing-step TV ingredients -/


-- @@ L452-460 verbatim
private structure CmaRealSignGhost
    (Stmt Wit Commit PrvState Chal Resp : Type) where
  pk : Stmt
  sk : Wit
  commit : Commit
  privateState : PrvState
  challenge : Chal
  ghostResponse : Resp
  actualResponse : Resp


-- @@ L462-468 verbatim
private structure CmaSignPublic
    (Stmt Wit Commit Chal Resp : Type) where
  pk : Stmt
  sk : Wit
  commit : Commit
  challenge : Chal
  response : Resp


-- @@ L470-478 verbatim
private def cmaSignPublicOfTranscript
    {Stmt Wit Commit Chal Resp : Type}
    (pk : Stmt) (sk : Wit) (t : Commit × Chal × Resp) :
    CmaSignPublic Stmt Wit Commit Chal Resp where
  pk := pk
  sk := sk
  commit := t.1
  challenge := t.2.1
  response := t.2.2


-- @@ L480-488 verbatim
private def CmaRealSignGhost.public
    {Stmt Wit Commit PrvState Chal Resp : Type}
    (x : CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp) :
    CmaSignPublic Stmt Wit Commit Chal Resp where
  pk := x.pk
  sk := x.sk
  commit := x.commit
  challenge := x.challenge
  response := x.ghostResponse


-- @@ L490-496 verbatim
private def cmaSignKeySource
    (hr : GenerableRelation Stmt Wit rel)
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (Stmt × Wit) :=
  match s.2.2 with
  | some keypair => pure keypair
  | none => hr.gen


-- @@ L498-504 verbatim
private def cmaSignKeyedData
    (s : CmaData M Commit Chal Stmt Wit)
    (pk : Stmt) (sk : Wit) :
    CmaData M Commit Chal Stmt Wit :=
  match s.2.2 with
  | some _ => s
  | none => (s.1, s.2.1, some (pk, sk))


-- @@ L506-525 expanded
private def cmaRealSignGhostDist (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel) (m : M) (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp) := do
  let (pk, sk) ← cmaSignKeySource M Commit Chal hr s
  let (c, prv) ← σ.commit pk sk
  let ch ← uniformSample Chal
  let ghostResp ← σ.respond pk sk prv ch
  match s.2.1 (m, c) with
  | some cachedCh =>
    do
      let actualResp ← σ.respond pk sk prv cachedCh
      pure
          { pk := pk, sk := sk, commit := c, privateState := prv, challenge := ch,
            ghostResponse := ghostResp, actualResponse := actualResp }
  | none =>
    pure
        { pk := pk, sk := sk, commit := c, privateState := prv, challenge := ch,
          ghostResponse := ghostResp, actualResponse := ghostResp }


-- @@ L527-533 verbatim
private def cmaRealSignPublicDist
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (CmaSignPublic Stmt Wit Commit Chal Resp) := do
  let (pk, sk) ← cmaSignKeySource M Commit Chal hr s
  cmaSignPublicOfTranscript pk sk <$> σ.realTranscript pk sk


-- @@ L535-542 verbatim
private def cmaSimSignPublicDist
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (s : CmaData M Commit Chal Stmt Wit) :
    ProbComp (CmaSignPublic Stmt Wit Commit Chal Resp) := do
  let (pk, sk) ← cmaSignKeySource M Commit Chal hr s
  let (c, ch, π) ← simT pk
  pure (cmaSignPublicOfTranscript pk sk (c, ch, π))


-- @@ L544-551 verbatim
omit [DecidableEq M] [DecidableEq Commit] in
private lemma cmaRealSignPublicDist_some
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (log : OuterState M) (cache : RoCache M Commit Chal) (key : Stmt × Wit) :
    cmaRealSignPublicDist M Commit Chal σ hr (log, cache, some key) =
      cmaSignPublicOfTranscript key.1 key.2 <$> σ.realTranscript key.1 key.2 := by
  simp [cmaRealSignPublicDist, cmaSignKeySource]


-- @@ L553-560 verbatim
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
private lemma cmaSimSignPublicDist_some
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (log : OuterState M) (cache : RoCache M Commit Chal) (key : Stmt × Wit) :
    cmaSimSignPublicDist M Commit Chal hr simT (log, cache, some key) =
      cmaSignPublicOfTranscript key.1 key.2 <$> simT key.1 := by
  simp [cmaSimSignPublicDist, cmaSignKeySource, map_eq_bind_pure_comp]


-- @@ L562-570 verbatim
omit [DecidableEq M] [DecidableEq Commit] in
private lemma cmaRealSignPublicDist_none
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (log : OuterState M) (cache : RoCache M Commit Chal) :
    cmaRealSignPublicDist M Commit Chal σ hr (log, cache, none) =
      (hr.gen >>= fun key =>
        cmaSignPublicOfTranscript key.1 key.2 <$> σ.realTranscript key.1 key.2) := by
  simp [cmaRealSignPublicDist, cmaSignKeySource]


-- @@ L572-579 verbatim
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
private lemma cmaSimSignPublicDist_none
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (log : OuterState M) (cache : RoCache M Commit Chal) :
    cmaSimSignPublicDist M Commit Chal hr simT (log, cache, none) =
      (hr.gen >>= fun key => cmaSignPublicOfTranscript key.1 key.2 <$> simT key.1) := by
  simp [cmaSimSignPublicDist, cmaSignKeySource, map_eq_bind_pure_comp]


-- @@ L581-592 verbatim
private def cmaRealSignGhostOut
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp) :
    (Commit × Resp) × CmaState M Commit Chal Stmt Wit :=
  let s₁ := cmaSignKeyedData M Commit Chal s x.pk x.sk
  match s₁.2.1 (m, x.commit) with
  | some _ =>
      ((x.commit, x.actualResponse), ((s₁.1 ++ [m], s₁.2.1, s₁.2.2), false))
  | none =>
      let cache₂ := s₁.2.1.cacheQuery (m, x.commit) x.challenge
      ((x.commit, x.ghostResponse), ((s₁.1 ++ [m], cache₂, s₁.2.2), false))


-- @@ L594-605 verbatim
private def cmaSimSignPublicOut
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaSignPublic Stmt Wit Commit Chal Resp) :
    (Commit × Resp) × CmaState M Commit Chal Stmt Wit :=
  let s₁ := cmaSignKeyedData M Commit Chal s x.pk x.sk
  match s₁.2.1 (m, x.commit) with
  | some _ =>
      ((x.commit, x.response), ((s₁.1 ++ [m], s₁.2.1, s₁.2.2), true))
  | none =>
      let cache₂ := s₁.2.1.cacheQuery (m, x.commit) x.challenge
      ((x.commit, x.response), ((s₁.1 ++ [m], cache₂, s₁.2.2), false))


-- @@ L607-611 verbatim
private def cmaSimSignPublicBad
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaSignPublic Stmt Wit Commit Chal Resp) : Prop :=
  ∃ ch, s.2.1 (m, x.commit) = some ch


-- @@ L613-633 verbatim
omit [SampleableType Chal] in
private lemma cmaRealSignGhostOut_eq_cmaSimSignPublicOut_of_not_bad
    (m : M)
    (s : CmaData M Commit Chal Stmt Wit)
    (x : CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp)
    (y : CmaSignPublic Stmt Wit Commit Chal Resp)
    (hpub : x.public = y)
    (hbad : ¬ cmaSimSignPublicBad M Commit Chal m s y) :
    cmaRealSignGhostOut M Commit Chal m s x =
      cmaSimSignPublicOut M Commit Chal m s y := by
  rcases x with ⟨pk, sk, c, prv, ch, ghostResp, actualResp⟩
  rcases y with ⟨pk', sk', c', ch', resp'⟩
  simp only [CmaRealSignGhost.public, CmaSignPublic.mk.injEq] at hpub
  rcases hpub with ⟨rfl, rfl, rfl, rfl, rfl⟩
  have hmiss : s.2.1 (m, c) = none :=
    Option.eq_none_iff_forall_ne_some.2 fun ch0 h => hbad ⟨ch0, h⟩
  have hmiss_keyed :
      (cmaSignKeyedData M Commit Chal s pk sk).2.1 (m, c) = none := by
    rcases s with ⟨log, cache, keypair⟩
    cases keypair <;> simpa [cmaSignKeyedData] using hmiss
  simp [cmaRealSignGhostOut, cmaSimSignPublicOut, hmiss_keyed]


-- @@ L635-649 verbatim
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
private lemma cmaSignKeySource_sound
    (hr : GenerableRelation Stmt Wit rel)
    (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s)
    (key : Stmt × Wit)
    (hkey : key ∈ support (cmaSignKeySource M Commit Chal hr s)) :
    rel key.1 key.2 = true := by
  rcases s with ⟨log, cache, keypair⟩
  cases keypair with
  | none =>
      exact hr.gen_sound key.1 key.2 hkey
  | some keypair =>
      obtain rfl : key = keypair := by simpa [cmaSignKeySource] using hkey
      simpa [CmaData.Valid] using hvalid


-- @@ L651-675 expanded
omit [DecidableEq M] [DecidableEq Commit] in
private lemma cmaRealSignGhost_public_evalSPMF_eq_publicDist
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel) (hr : GenerableRelation Stmt Wit rel)
    (m : M) (s : CmaData M Commit Chal Stmt Wit) :
    evalSPMF (CmaRealSignGhost.public <$> cmaRealSignGhostDist M Commit Chal σ hr m s) =
      evalSPMF (cmaRealSignPublicDist M Commit Chal σ hr s) :=
  by
  rcases s with ⟨log, cache, keypair⟩
  simp only [cmaRealSignGhostDist, cmaRealSignPublicDist, ChallengeVerifyProtocol.realTranscript,
    cmaSignPublicOfTranscript, evalSPMF_bind, evalSPMF_map, map_bind, bind_pure_comp,
    Functor.map_map]
  refine bind_congr fun key => ?_
  refine bind_congr fun cp => ?_
  refine bind_congr fun ch => ?_
  refine bind_congr fun ghostResp => ?_
  cases hcache : cache (m, cp.1) with
  | none =>
    simp only [evalSPMF_pure, map_pure, Function.comp_apply, CmaRealSignGhost.public]
    rfl
  | some
    cachedCh =>
    simp only [evalSPMF_map, Functor.map_map, Function.comp_apply, CmaRealSignGhost.public]
    exact
      spmf_map_const_of_no_failure
        (probFailure_evalSPMF_eq_zero (σ.respond key.1 key.2 cp.2 cachedCh)) _


-- @@ L677-710 verbatim
omit [DecidableEq M] [DecidableEq Commit] in
private lemma cmaSignPublicDist_tv_le_hvzk
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk : ℝ≥0∞) (hζ_zk : ζ_zk < ∞)
    (hHVZK : σ.HVZK simT ζ_zk.toReal)
    (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s) :
    ENNReal.ofReal (tvDist
      (cmaRealSignPublicDist M Commit Chal σ hr s)
      (cmaSimSignPublicDist M Commit Chal hr simT s)) ≤ ζ_zk := by
  have htop : ζ_zk ≠ ⊤ := ne_top_of_lt hζ_zk
  rcases s with ⟨log, cache, keypair⟩
  cases keypair with
  | some key =>
      refine (ENNReal.ofReal_le_iff_le_toReal htop).mpr <| le_trans ?_
        (hHVZK key.1 key.2 (by simpa [CmaData.Valid] using hvalid))
      rw [cmaRealSignPublicDist_some, cmaSimSignPublicDist_some]
      exact tvDist_map_le (cmaSignPublicOfTranscript key.1 key.2)
        (σ.realTranscript key.1 key.2) (simT key.1)
  | none =>
      rw [cmaRealSignPublicDist_none, cmaSimSignPublicDist_none]
      refine ofReal_tvDist_bind_left_le_const
        (mx := hr.gen)
        (f := fun key : Stmt × Wit =>
          cmaSignPublicOfTranscript key.1 key.2 <$> σ.realTranscript key.1 key.2)
        (g := fun key : Stmt × Wit =>
          cmaSignPublicOfTranscript key.1 key.2 <$> simT key.1)
        (ε := ζ_zk) ?_
      intro key hkey
      exact (ENNReal.ofReal_le_iff_le_toReal htop).mpr <|
        (tvDist_map_le (cmaSignPublicOfTranscript key.1 key.2) (σ.realTranscript key.1 key.2)
          (simT key.1)).trans (hHVZK key.1 key.2 (hr.gen_sound key.1 key.2 hkey))


-- @@ L712-741 expanded
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
private lemma simTranscript_cacheHit_prob_le_roCacheCount_mul
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp)) (β : ℝ≥0∞)
    (hCommit : σ.simCommitPredictability simT β) (pk : Stmt) (m : M)
    (cache : RoCache M Commit Chal) :
    (probEvent (simT pk) fun t : Commit × Chal × Resp => ∃ ch, cache (m, t.1) = some ch) ≤
      QueryCache.enncard cache * β :=
  by
  classical
  let : DecidableEq M := Classical.decEq M
  let : DecidableEq Commit := Classical.decEq Commit
  let commitDist : ProbComp Commit := Prod.fst <$> simT pk
  let hit : Commit → Prop := fun c => ∃ ch, cache (m, c) = some ch
  let S : Finset Commit := (finSupport commitDist).filter hit
  have h_card_le : (S.card : ℝ≥0∞) ≤ QueryCache.enncard cache :=
    by
    let e : (S : Set Commit) ↪ cache.toSet :=
      ⟨fun c =>
        ⟨⟨(m, c.1), Classical.choose (Finset.mem_filter.mp c.2).2⟩,
          Classical.choose_spec (Finset.mem_filter.mp c.2).2⟩,
        fun c₁ c₂ h => Subtype.ext (congrArg (fun x : cache.toSet => x.1.1.2) h)⟩
    simpa only [QueryCache.enncard, Set.encard_coe_eq_coe_finsetCard, ENat.toENNReal_coe] using
      ENat.toENNReal_mono e.encard_le
  calc
    (probEvent (simT pk) fun t : Commit × Chal × Resp => ∃ ch, cache (m, t.1) = some ch) =
        probEvent commitDist hit :=
      by simp [commitDist, hit]
    _ = ∑ c ∈ S, probOutput commitDist c := by simp [S, probEvent_eq_sum_filter_finSupport]
    _ ≤ ∑ c ∈ S, β := (Finset.sum_le_sum fun c _ => hCommit pk c)
    _ = (S.card : ℝ≥0∞) * β := by simp [Finset.sum_const, nsmul_eq_mul]
    _ ≤ QueryCache.enncard cache * β := mul_le_mul' h_card_le le_rfl


-- @@ L743-782 expanded
omit [DecidableEq M] [DecidableEq Commit] [SampleableType Chal] in
private lemma cmaSimSignPublicBad_prob_le_roCacheCount_mul
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel) (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp)) (β : ℝ≥0∞)
    (hCommit : σ.simCommitPredictability simT β) (m : M) (s : CmaData M Commit Chal Stmt Wit) :
    probEvent (cmaSimSignPublicDist M Commit Chal hr simT s)
        (cmaSimSignPublicBad M Commit Chal m s) ≤
      QueryCache.enncard s.2.1 * β :=
  by
  classical
  rcases s with ⟨log, cache, keypair⟩
  cases keypair with
  | some key =>
    simpa [cmaSimSignPublicDist, cmaSignKeySource, cmaSimSignPublicBad, cmaSignPublicOfTranscript,
      CmaSignPublic.commit, Function.comp_def] using
      simTranscript_cacheHit_prob_le_roCacheCount_mul M Commit Chal σ simT β hCommit key.1 m cache
  | none =>
    rw [cmaSimSignPublicDist_none]
    rw [probEvent_bind_eq_tsum]
    calc
      (∑' key : Stmt × Wit,
            probOutput hr.gen key *
              probEvent
                ((fun t : Commit × Chal × Resp =>
                    ({ pk := key.1, sk := key.2, commit := t.1, challenge := t.2.1,
                        response := t.2.2 } :
                      CmaSignPublic Stmt Wit Commit Chal Resp)) <$>
                  simT key.1)
                (cmaSimSignPublicBad M Commit Chal m (log, cache, none))) ≤
          ∑' key : Stmt × Wit, probOutput hr.gen key * (QueryCache.enncard cache * β) :=
        by
        gcongr with key
        simpa [cmaSimSignPublicBad, Function.comp_def] using
          simTranscript_cacheHit_prob_le_roCacheCount_mul M Commit Chal σ simT β hCommit key.1 m
            cache
      _ = (∑' key : Stmt × Wit, probOutput hr.gen key) * (QueryCache.enncard cache * β) := by
        rw [ENNReal.tsum_mul_right]
      _ = QueryCache.enncard cache * β := by
        rw [tsum_probOutput_eq_one' probFailure_eq_zero, one_mul]


-- @@ L784-814 expanded
private lemma cmaRealSignStep_evalSPMF_eq_ghost
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel) (hr : GenerableRelation Stmt Wit rel)
    (m : M) (s : CmaData M Commit Chal Stmt Wit) :
    evalSPMF (((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false)) =
      evalSPMF
        (cmaRealSignGhostOut M Commit Chal m s <$> cmaRealSignGhostDist M Commit Chal σ hr m s) :=
  by
  rcases s with ⟨log, cache, keypair⟩
  obtain _ | key := keypair <;>
      (conv_lhs =>
          simp only [cmaReal, cmaRealSourceFull, bind_pure_comp, Prod.mk.eta, StateT.run_mk,
            liftM_bind]) <;>
    (conv_rhs => simp [cmaRealSignGhostDist, cmaSignKeySource])
  on_goal 1 => refine bind_congr fun key => ?_
  all_goals
    refine bind_congr fun cp => ?_
    cases hcache : cache (m, cp.1) with
    | none => simp [hcache, cmaRealSignGhostOut, cmaSignKeyedData]
    | some
      cachedCh =>
      conv_lhs => simp [hcache, cmaRealSignGhostOut, cmaSignKeyedData]
      conv_rhs => simp [hcache, cmaRealSignGhostOut, cmaSignKeyedData]
      rw [spmf_bind_bind_const_of_no_failure (p := evalSPMF ((uniformSample Chal) : ProbComp Chal))
          (q := fun ch => evalSPMF (σ.respond key.1 key.2 cp.2 ch)) (r :=
          (fun actualResp => ((cp.1, actualResp), ((log ++ [m], cache, some key), false))) <$>
            evalSPMF (σ.respond key.1 key.2 cp.2 cachedCh))]
      · exact probFailure_evalSPMF_eq_zero ((uniformSample Chal) : ProbComp Chal)
      · intro ch
        exact probFailure_evalSPMF_eq_zero (σ.respond key.1 key.2 cp.2 ch)


-- @@ L816-835 verbatim
private lemma nma_simulateQ_liftM_unif_run {α : Type}
    (hr : GenerableRelation Stmt Wit rel)
    (oa : ProbComp α)
    (s : NmaState M Commit Chal Stmt Wit) :
    (simulateQ (nma M Commit Chal hr)
      (liftM oa : OracleComp (nmaSpec M Commit Chal Stmt) α)).run s =
      (fun a => (a, s)) <$> oa := by
  simpa using
    QueryImpl.Stateful.simulateQ_liftComp_run_of_query
      (h := nma M Commit Chal hr)
      (fun t s => by
        change
          (fun p : unifSpec.Range t × NmaState M Commit Chal Stmt Wit =>
              (p.1, p.2)) <$>
              ((fun a : unifSpec.Range t => (a, s)) <$>
                (liftM (unifSpec.query t) : ProbComp (unifSpec.Range t))) =
            (fun a : unifSpec.Range t => (a, s)) <$>
              (liftM (unifSpec.query t) : ProbComp (unifSpec.Range t))
        simp [Functor.map_map])
      oa s


-- @@ L837-876 expanded
private lemma cmaSimSignStep_evalSPMF_eq_public (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp)) (m : M) (s : CmaData M Commit Chal Stmt Wit) :
    evalSPMF (((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false)) =
      evalSPMF
        (cmaSimSignPublicOut M Commit Chal m s <$> cmaSimSignPublicDist M Commit Chal hr simT s) :=
  by
  rcases s with ⟨log, cache, keypair⟩
  unfold cmaSim
  obtain _ | key := keypair <;>
      (conv_lhs =>
          simp only [cmaFrame, cmaOuterLens, Prod.mk.eta, cmaNmaLens,
            QueryImpl.Stateful.linkWith_apply_run, cmaToNma, cmaSignSim, liftComp_eq_liftM,
            bind_pure_comp, PFunctor.Lens.State.mk_get, StateT.run_mk, simulateQ_bind,
            simulateQ_query, OracleQuery.input_query, OracleQuery.cont_query, nma, nmaPublic,
            id_map, simulateQ_map, nmaProgram, StateT.run_bind, StateT.run_map, pure_bind,
            bind_map_left, map_bind, Functor.map_map, QueryImpl.Stateful.Frame.linkReshape,
            PFunctor.Lens.State.mk_put, liftM_bind, liftM_map]) <;>
    (conv_rhs => simp [cmaSimSignPublicDist, cmaSignKeySource])
  on_goal 1 => refine bind_congr fun key => ?_
  all_goals
    change
      (evalSPMF
            ((simulateQ (nma M Commit Chal hr)
                  (liftM (simT key.1) :
                    OracleComp (nmaSpec M Commit Chal Stmt) (Commit × Chal × Resp))).run
              (cache, some key, false)) >>=
          _) =
        _
    rw [nma_simulateQ_liftM_unif_run M Commit Chal hr (simT key.1) (cache, some key, false),
      show
        ((fun a : Commit × Chal × Resp => (a, cache, some key, false)) <$> simT key.1) =
          (simT key.1 >>= fun a => pure (a, cache, some key, false))
        by
        rw [map_eq_bind_pure_comp]
        rfl,
      evalSPMF_bind]
    simp only [evalSPMF_pure, bind_pure_comp]
    rw [bind_map_left, map_eq_bind_pure_comp]
    refine bind_congr fun t => ?_
    cases hcache : cache (m, t.1) with
    | none => simp [hcache, cmaSimSignPublicOut, cmaSignKeyedData, cmaSignPublicOfTranscript]
    | some cachedCh =>
      simp [hcache, cmaSimSignPublicOut, cmaSignKeyedData, cmaSignPublicOfTranscript]


-- @@ L878-945 expanded
/-- On a valid keypair state, the total-variation distance between the real and simulated
signing oracle on a single signing query is bounded by `cmaSignEpsCore`. -/
theorem cmaReal_cmaSim_tv_sign_le_cmaSignEpsCore_of_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel) (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp)) (ζ_zk β : ℝ≥0∞) (hζ_zk : ζ_zk < ∞)
    (hHVZK : σ.HVZK simT ζ_zk.toReal) (hCommit : σ.simCommitPredictability simT β) (m : M)
    (s : CmaData M Commit Chal Stmt Wit) (hvalid : CmaData.Valid (rel := rel) s) :
    ENNReal.ofReal
        (tvDist (((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false))
          (((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false))) ≤
      cmaSignEpsCore M Commit Chal ζ_zk β s :=
  by
  let realGhost := cmaRealSignGhostDist M Commit Chal σ hr m s
  let simPub := cmaSimSignPublicDist M Commit Chal hr simT s
  let realOut :
    CmaRealSignGhost Stmt Wit Commit PrvState Chal Resp →
      (Commit × Resp) × CmaState M Commit Chal Stmt Wit :=
    cmaRealSignGhostOut M Commit Chal m s
  let simOut :
    CmaSignPublic Stmt Wit Commit Chal Resp → (Commit × Resp) × CmaState M Commit Chal Stmt Wit :=
    cmaSimSignPublicOut M Commit Chal m s
  let bad : CmaSignPublic Stmt Wit Commit Chal Resp → Prop := cmaSimSignPublicBad M Commit Chal m s
  have hreal :
    evalSPMF (((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false)) =
      evalSPMF (realOut <$> realGhost) :=
    by simpa [realGhost, realOut] using cmaRealSignStep_evalSPMF_eq_ghost M Commit Chal σ hr m s
  have hsim :
    evalSPMF (((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false)) =
      evalSPMF (simOut <$> simPub) :=
    by simpa [simPub, simOut] using cmaSimSignStep_evalSPMF_eq_public M Commit Chal hr simT m s
  have hstep :
    ENNReal.ofReal
        (tvDist (((cmaReal M Commit Chal σ hr) (CmaQuery.sign m)).run (s, false))
          (((cmaSim M Commit Chal hr simT) (CmaQuery.sign m)).run (s, false))) =
      ENNReal.ofReal (tvDist (realOut <$> realGhost) (simOut <$> simPub)) :=
    by
    unfold tvDist
    rw [hreal, hsim]
  have hprivate :
    ENNReal.ofReal (tvDist (realOut <$> realGhost) (simOut <$> simPub)) ≤
      ENNReal.ofReal (tvDist (CmaRealSignGhost.public <$> realGhost) simPub) +
        probEvent simPub bad :=
    ofReal_tvDist_map_private_right_bad_le (oa := realGhost) (ob := simPub) (pub :=
      CmaRealSignGhost.public) (fa := realOut) (fb := simOut) (bad := bad) fun x y hpub hbad =>
      cmaRealSignGhostOut_eq_cmaSimSignPublicOut_of_not_bad M Commit Chal m s x y hpub hbad
  have hpublic : ENNReal.ofReal (tvDist (CmaRealSignGhost.public <$> realGhost) simPub) ≤ ζ_zk :=
    by
    have hpub_eval :
      evalSPMF (CmaRealSignGhost.public <$> realGhost) =
        evalSPMF (cmaRealSignPublicDist M Commit Chal σ hr s) :=
      by
      simpa [realGhost] using cmaRealSignGhost_public_evalSPMF_eq_publicDist M Commit Chal σ hr m s
    simpa [tvDist, simPub, hpub_eval] using
      cmaSignPublicDist_tv_le_hvzk M Commit Chal σ hr simT ζ_zk hζ_zk hHVZK s hvalid
  have hbad : probEvent simPub bad ≤ QueryCache.enncard s.2.1 * β := by
    simpa [bad, simPub] using
      cmaSimSignPublicBad_prob_le_roCacheCount_mul M Commit Chal σ hr simT β hCommit m s
  rw [hstep]
  exact (hprivate.trans (add_le_add hpublic hbad)).trans_eq rfl


-- @@ L947-968 verbatim
theorem cmaReal_cmaSim_tv_costly_le_cmaSignEpsCore_of_valid
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞) (hζ_zk : ζ_zk < ∞)
    (hHVZK : σ.HVZK simT ζ_zk.toReal)
    (hCommit : σ.simCommitPredictability simT β)
    (t : (cmaSpec M Commit Chal Resp Stmt).Domain)
    (ht : cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
      (Resp := Resp) (Stmt := Stmt) t)
    (s : CmaData M Commit Chal Stmt Wit)
    (hvalid : CmaData.Valid (rel := rel) s) :
    ENNReal.ofReal (tvDist
      (((cmaReal M Commit Chal σ hr) t).run (s, false))
      (((cmaSim M Commit Chal hr simT) t).run (s, false)))
      ≤ cmaSignEpsCore M Commit Chal ζ_zk β s := by
  rcases t with n | mc | m | ⟨⟩
  · exact ht.elim
  · exact ht.elim
  · exact cmaReal_cmaSim_tv_sign_le_cmaSignEpsCore_of_valid
      M Commit Chal σ hr simT ζ_zk β hζ_zk hHVZK hCommit m s hvalid
  · exact ht.elim


-- @@ L970-985 verbatim
/-- Build the native H3 step facts from HVZK and simulator commit
predictability. -/
theorem cmaH3StepFacts_of_hvzk_predictability
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞) (hζ_zk : ζ_zk < ∞)
    (hHVZK : σ.HVZK simT ζ_zk.toReal)
    (hCommit : σ.simCommitPredictability simT β) :
    CmaH3StepFacts M Commit Chal σ hr simT ζ_zk β where
  preservesValid := cmaReal_preserves_valid M Commit Chal σ hr
  stepTvCostly t ht s hvalid :=
    cmaReal_cmaSim_tv_costly_le_cmaSignEpsCore_of_valid
      M Commit Chal σ hr simT ζ_zk β hζ_zk hHVZK hCommit t ht s hvalid
  stepEqFree := cmaReal_eq_cmaSim_of_not_costly M Commit Chal σ hr simT
  badMono := cmaReal_bad_mono M Commit Chal σ hr


-- @@ L987-987 verbatim
/-! ## Native H3 factoring theorem -/


-- @@ L989-1029 expanded
/-- Native H3 bridge with caller-supplied expected-cost bound.

This is the direct `QueryImpl.Stateful` replacement for the old H3
identical-until-bad instantiation. The hypotheses are factored into per-query
step facts and computation-specific run facts; no heap package or state
projection appears in the statement. -/
theorem cmaReal_cmaSim_advantage_le_H3_bound_of_expectedQuerySlack
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel) (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp)) (ζ_zk β : ℝ≥0∞)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool) (qS : ℕ) (εBound : ℝ≥0∞)
    (stepFacts : CmaH3StepFacts M Commit Chal σ hr simT ζ_zk β)
    (runFacts : CmaH3RunFacts M Commit Chal σ hr ζ_zk β A qS εBound) :
    ENNReal.ofReal (cmaH3Advantage M Commit Chal σ hr simT A) ≤ εBound :=
  by
  have h_bridge :=
    QueryImpl.Stateful.advantage_le_expectedQuerySlack_plus_probEvent_bad_of_inv_preserved (h₀ :=
      cmaReal M Commit Chal σ hr) (h₁ := cmaSim M Commit Chal hr simT) (s_init :=
      cmaDataInit M Commit Chal Stmt Wit) (Inv := CmaData.Valid (rel := rel)) (chargedQuery :=
      cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal) (Resp := Resp) (Stmt := Stmt))
      (querySlack := cmaSignEpsCore M Commit Chal ζ_zk β) (h_init_inv :=
      cmaDataInit_valid M Commit Chal) stepFacts.preservesValid stepFacts.stepTvCostly
      stepFacts.stepEqFree stepFacts.badMono A runFacts.queryBound
  calc
    ENNReal.ofReal (cmaH3Advantage M Commit Chal σ hr simT A) ≤
        expectedQuerySlack (cmaReal M Commit Chal σ hr)
            (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal) (Resp := Resp) (Stmt := Stmt))
            (cmaSignEpsCore M Commit Chal ζ_zk β) A qS (cmaDataInit M Commit Chal Stmt Wit, false) +
          probEvent
            ((simulateQ (cmaReal M Commit Chal σ hr) A).run
              (cmaDataInit M Commit Chal Stmt Wit, false))
            fun z : Bool × CmaState M Commit Chal Stmt Wit => z.2.2 = true :=
      h_bridge
    _ = cmaH3ExpectedLoss M Commit Chal σ hr ζ_zk β A qS := by
      simp [runFacts.badZero, cmaH3ExpectedLoss]
    _ ≤ εBound := runFacts.expectedLossLe


-- @@ L1031-1058 verbatim
/-- Fully assembled native H3 bound from HVZK, simulator commit
predictability, and adversary signing/hash query budgets. -/
theorem cmaReal_cmaSim_advantage_le_H3_bound
    (σ : SigmaProtocol Stmt Wit Commit PrvState Chal Resp rel)
    (hr : GenerableRelation Stmt Wit rel)
    (simT : Stmt → ProbComp (Commit × Chal × Resp))
    (ζ_zk β : ℝ≥0∞) (hζ_zk : ζ_zk < ∞)
    (hHVZK : σ.HVZK simT ζ_zk.toReal)
    (hCommit : σ.simCommitPredictability simT β)
    (A : OracleComp (cmaSpec M Commit Chal Resp Stmt) Bool)
    {qS qH : ℕ}
    (h_qS : OracleComp.IsQueryBoundP A
      (cmaH3Costly (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qS)
    (h_qH : OracleComp.IsQueryBoundP A
      (IsHashQuery (M := M) (Commit := Commit) (Chal := Chal)
        (Resp := Resp) (Stmt := Stmt)) qH) :
    ENNReal.ofReal (cmaH3Advantage M Commit Chal σ hr simT A) ≤
      (qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β :=
  cmaReal_cmaSim_advantage_le_H3_bound_of_expectedQuerySlack
    M Commit Chal σ hr simT ζ_zk β A qS
    ((qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β)
    (cmaH3StepFacts_of_hvzk_predictability M Commit Chal σ hr simT
      ζ_zk β hζ_zk hHVZK hCommit)
    (cmaH3RunFacts_of_queryBound_expectedLoss M Commit Chal σ hr ζ_zk β A qS
      ((qS : ℝ≥0∞) * ζ_zk + (qS : ℝ≥0∞) * ((qS : ℝ≥0∞) + qH) * β)
      h_qS
      (cmaH3ExpectedLoss_le_queryBounds M Commit Chal σ hr ζ_zk β A h_qS h_qH))


-- @@ L1060-1060 verbatim
end FiatShamir.Stateful
