/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import PolyFun.PFunctor.PatternRunsOnMatter.Basic
public import PolyFun.PFunctor.Dynamical.CofreeMate
public import PolyFun.PFunctor.Dynamical.Simulation
public import PolyFun.PFunctor.Dynamical.Game


-- @@ L13-27 verbatim
/-!
# Finite patterns running on dynamical systems

A dynamical system supplies canonical matter through its terminal-coalgebra
behavior tree. Composing that behavior map with `FreeP.runOn` turns a finite
pattern and an initial state into a synchronized finite decision tree. Its
dependent backward map returns both the path through the original pattern and
the system state reached at the corresponding finite behavior vertex.

This is an operational bridge, not a new execution model: it identifies the
paper's cofree matter with the repository's established `DynSystem.behavior`
semantics. It also makes the exact observational claim available downstream:
simulation-related states produce equal synchronized output shapes. Their
backward state labels need not be equal when the two state types differ.
-/


-- @@ L29-29 verbatim
@[expose] public section


-- @@ L31-31 verbatim
universe pA pB qA qB uS uS₁ uS₂ uα


-- @@ L33-33 verbatim
namespace PFunctor

-- @@ L34-34 verbatim
namespace FreeP


-- @@ L36-37 verbatim
variable {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}}
  {S : Type uS} {S₁ : Type uS₁} {S₂ : Type uS₂}


-- @@ L39-46 verbatim
/-- Run a finite `P`-pattern on the behavior generated by a `Q`-dynamical
system. The state monomial's backward direction records the reached state. -/
def runOnSystem (P : PFunctor.{pA, pB})
    (system : DynSystem S Q) :
    Lens (FreeP P ⊗ selfMonomial S) (FreeP (P ⊗ Q)) :=
  runOn P Q ∘ₗ
    (Lens.id (FreeP P) ⊗ₗ
      CofreeP.unfoldLens (stateComonoid S) system)


-- @@ L48-53 verbatim
@[simp]
theorem runOnSystem_toFunA (P : PFunctor.{pA, pB})
    (system : DynSystem S Q) (pattern : (FreeP P).A) (state : S) :
    (runOnSystem P system).toFunA (pattern, state) =
      (runObj pattern (system.behavior state)).1 :=
  rfl


-- @@ L55-64 verbatim
/-- The complete backward result consists of the source pattern path and the
state reached at the matter vertex visited by that path. -/
theorem runOnSystem_toFunB (P : PFunctor.{pA, pB})
    (system : DynSystem S Q) (pattern : (FreeP P).A) (state : S)
    (path : FreeM.Path ((runOnSystem P system).toFunA (pattern, state))) :
    (runOnSystem P system).toFunB (pattern, state) path =
      let pulled := (runObj pattern (system.behavior state)).2 path
      (pulled.1,
        CofreeP.unfoldDirection (stateComonoid S) system state pulled.2) :=
  rfl


-- @@ L66-75 verbatim
/-- Package the synchronized output shape with its complete pattern-path and
reached-state labelling. -/
def runSystemObj (system : DynSystem S Q)
    (pattern : (FreeP P).A) (state : S) :
    (FreeP (P ⊗ Q)).Obj (FreeM.Path pattern × S) :=
  FreeP.relabel
    (fun pulled =>
      (pulled.1,
        CofreeP.unfoldDirection (stateComonoid S) system state pulled.2))
    (runObj pattern (system.behavior state))


-- @@ L77-86 verbatim
/-- `runSystemObj` is exactly the object map of the composite operational
lens, including its dependent backward labels. -/
theorem mapObj_runOnSystem (P : PFunctor.{pA, pB})
    (system : DynSystem S Q) (pattern : (FreeP P).A) (state : S) :
    Lens.mapObj (runOnSystem P system)
        (⟨(pattern, state), id⟩ :
          (FreeP P ⊗ selfMonomial S).Obj
            (FreeM.Path pattern × S)) =
      runSystemObj system pattern state :=
  rfl


-- @@ L88-98 verbatim
/-- Observationally equivalent states produce the same synchronized finite
output tree for every pattern. This intentionally compares output shapes, not
the reached-state labels in potentially different state types. -/
theorem runOnSystem_toFunA_eq_of_obsEq
    {system₁ : DynSystem S₁ Q} {system₂ : DynSystem S₂ Q}
    {state₁ : S₁} {state₂ : S₂}
    (h : DynSystem.ObsEq system₁ system₂ state₁ state₂)
    (pattern : (FreeP P).A) :
    (runOnSystem P system₁).toFunA (pattern, state₁) =
      (runOnSystem P system₂).toFunA (pattern, state₂) :=
  congrArg (fun matter => (runObj pattern matter).1) h


-- @@ L100-110 verbatim
/-- A synchronized dynamical-system simulation therefore preserves every
finite pattern's synchronized output shape. -/
theorem runOnSystem_toFunA_eq_of_isSimulation
    {system₁ : DynSystem S₁ Q} {system₂ : DynSystem S₂ Q}
    {R : S₁ → S₂ → Prop} (hsim : DynSystem.IsSimulation system₁ system₂ R)
    {state₁ : S₁} {state₂ : S₂} (hstate : R state₁ state₂)
    (pattern : (FreeP P).A) :
    (runOnSystem P system₁).toFunA (pattern, state₁) =
      (runOnSystem P system₂).toFunA (pattern, state₂) :=
  runOnSystem_toFunA_eq_of_obsEq
    (DynSystem.obsEq_of_isSimulation hsim hstate) pattern


-- @@ L112-112 verbatim
end FreeP


-- @@ L114-114 verbatim
namespace DynSystem


-- @@ L116-117 verbatim
variable {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}}
  {S : Type uS} {α : Type uα}


-- @@ L119-127 verbatim
/-- Direct recursive normal form for pattern execution. The public
`runPattern` below is defined through the object-level Xi construction. -/
private def runPatternTree (system : DynSystem S Q) : FreeM P α → S →
    FreeM (P ⊗ Q) (α × S)
  | .pure value, state => .pure (value, state)
  | .liftBind operation next, state =>
      .liftBind (operation, system.expose state) fun direction =>
        runPatternTree system (next direction.1)
          (system.update state direction.2)


-- @@ L129-135 verbatim
/-- Run an arbitrary result-labelled finite pattern on a dynamical system via
the object map of `runOn`. Every output leaf contains the pattern result and
the actual state reached at the corresponding matter vertex. -/
def runPattern (system : DynSystem S Q) (pattern : FreeM P α)
    (state : S) : FreeM (P ⊗ Q) (α × S) :=
  FreeP.decode
    (FreeP.runObjects (FreeP.encode pattern) (system.mateObj state id))


-- @@ L137-142 verbatim
private theorem mateObj_root_id (system : DynSystem S Q) (state : S) :
    (system.mateObj state id).2 (.root (system.mateObj state id).1) = state := by
  change CofreeP.unfoldDirection (stateComonoid S) system state
      (.root (CofreeP.unfoldShape (stateComonoid S) system state)) = state
  rw [CofreeP.unfoldDirection_root]
  rfl


-- @@ L144-163 verbatim
private theorem runObjectsTree_mateObj
    (system : DynSystem S Q) (pattern : FreeM P α) (state : S) :
    FreeP.runObjectsTree pattern (system.mateObj state id) =
      runPatternTree system pattern state := by
  induction pattern generalizing state with
  | pure value =>
      change FreeM.pure
          (value, (system.mateObj state id).2
            (.root (system.mateObj state id).1)) =
        FreeM.pure (value, state)
      rw [mateObj_root_id]
  | lift_bind operation next ih =>
      have hhead := CofreeP.head_unfoldShape
        (stateComonoid S) system state
      cases hhead
      change FreeM.liftBind _ _ = FreeM.liftBind _ _
      congr 1
      funext direction
      rw [DynSystem.mateObj_child]
      exact ih direction.1 (system.update state direction.2)


-- @@ L165-169 verbatim
private theorem runPattern_eq_runPatternTree
    (system : DynSystem S Q) (pattern : FreeM P α) (state : S) :
    system.runPattern pattern state = runPatternTree system pattern state := by
  rw [runPattern, FreeP.decode_runObjects_encode]
  exact runObjectsTree_mateObj system pattern state


-- @@ L171-175 verbatim
@[simp]
theorem runPattern_pure (system : DynSystem S Q) (value : α) (state : S) :
    system.runPattern (P := P) (pure value) state = pure (value, state) := by
  rw [runPattern_eq_runPatternTree]
  rfl


-- @@ L177-190 verbatim
/-- A nonempty pattern synchronizes its root with the system's exposed
position, then advances the two continuations along their respective
directions. -/
theorem runPattern_liftBind (system : DynSystem S Q) (operation : P.A)
    (next : P.B operation → FreeM P α) (state : S) :
    system.runPattern (.liftBind operation next) state =
      .liftBind (operation, system.expose state) fun direction =>
        system.runPattern (next direction.1)
          (system.update state direction.2) := by
  rw [runPattern_eq_runPatternTree]
  change FreeM.liftBind _ _ = FreeM.liftBind _ _
  congr 1
  funext direction
  rw [runPattern_eq_runPatternTree]


-- @@ L192-198 verbatim
/-- The full `n`-round branching pattern generated by a dynamical system,
with the reached state stored at every leaf. -/
def patternN (system : DynSystem S P) : ℕ → S → FreeM P S
  | 0, state => .pure state
  | n + 1, state =>
      .liftBind (system.expose state) fun direction =>
        system.patternN n (system.update state direction)


-- @@ L200-203 verbatim
@[simp]
theorem patternN_zero (system : DynSystem S P) (state : S) :
    system.patternN 0 state = .pure state :=
  rfl


-- @@ L205-209 verbatim
theorem patternN_succ (system : DynSystem S P) (n : ℕ) (state : S) :
    system.patternN (n + 1) state =
      .liftBind (system.expose state) fun direction =>
        system.patternN n (system.update state direction) :=
  rfl


-- @@ L211-242 verbatim
/-- Whole-finite-run compatibility with the existing game wiring: running the
challenger's finite branching pattern on the adversary and then evaluating is
exactly the finite branching pattern of `DynSystem.game`. -/
theorem runPattern_game
    {q r : PFunctor.{pA, pB}} {T : Type uS₁}
    (challenger : DynSystem S (q ⊸ r)) (adversary : DynSystem T q)
    (n : ℕ) (challengerState : S) (adversaryState : T) :
    (adversary.runPattern
        (challenger.patternN n challengerState) adversaryState).mapLens
          (Lens.eval q r) =
      (DynSystem.game challenger adversary).patternN n
        (challengerState, adversaryState) := by
  induction n generalizing challengerState adversaryState with
  | zero =>
      rw [patternN_zero, patternN_zero]
      change FreeM.mapLens (Lens.eval q r)
          (adversary.runPattern (pure challengerState) adversaryState) = _
      rw [runPattern_pure]
      rfl
  | succ n ih =>
      rw [patternN_succ, runPattern_liftBind, patternN_succ]
      unfold FreeM.mapLens
      apply congrArg (FreeM.liftBind
        ((challenger.expose challengerState).toFunA
          (adversary.expose adversaryState)))
      funext direction
      exact ih
        (challenger.update challengerState
          ⟨adversary.expose adversaryState, direction⟩)
        (adversary.update adversaryState
          ((challenger.expose challengerState).toFunB
            (adversary.expose adversaryState) direction))


-- @@ L244-244 verbatim
end DynSystem

-- @@ L245-245 verbatim
end PFunctor
