/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import PolyFun.PFunctor.PatternRunsOnMatter.Module
public import PolyFun.PFunctor.PatternRunsOnMatter.Dynamical
public import PolyFun.PFunctor.Dynamical.Bisimulation


-- @@ L12-28 verbatim
/-!
# Internal-hom answerers as matter

Section 4 of Libkind--Spivak uses matter of type `[P,R]`: at every node it
offers a lens answering every `P`-position with an `R`-position and pulling an
`R`-direction back to a `P`-direction. After a finite `P`-pattern runs on this
matter, tensor evaluation turns every synchronized node into an `R`-node.

`runThrough` is the paper's generic Section 4 interaction schema.
`evaluation` is exactly `Lens.eval`, preceded only by tensor symmetry to
match Equation (1)'s pattern-first order, and `runAgainst` is its
single-internal-hom specialization for interview/program-style examples.
`runAgainstSystem` additionally factors the cofree matter through a
`DynSystem`, matching the paper's state-system presentation of a person or
operating system. Voting tensor powers and the two-player duoidal composite
need additional aggregation structure and are intentionally not claimed here.
-/


-- @@ L30-30 verbatim
@[expose] public section


-- @@ L32-32 verbatim
universe pA pB qA qB rA rB t uS uS₁ uS₂


-- @@ L34-34 verbatim
namespace PFunctor

-- @@ L35-35 verbatim
namespace FreeP


-- @@ L37-37 verbatim
variable {S : Type uS} {S₁ : Type uS₁} {S₂ : Type uS₂}


-- @@ L39-44 verbatim
/-- Run a pattern on arbitrary matter, then interpret each synchronized node
through an interaction lens. This is the paper's generic Section 4 schema
`m p ⊗ c q → m (p ⊗ q) → m r`. -/
def runThrough {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}} {R : PFunctor.{rA, rB}}
    (interaction : Lens (P ⊗ Q) R) : Lens (FreeP P ⊗ CofreeP Q) (FreeP R) :=
  FreeP.map interaction ∘ₗ FreeP.runOn P Q


-- @@ L46-49 verbatim
/-- Evaluate a pattern node against an internal-hom answerer. Tensor symmetry
only changes the paper's pattern-first order to `Lens.eval`'s hom-first order. -/
def evaluation (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB}) : Lens (P ⊗ (P ⊸ R)) R :=
  Lens.eval P R ∘ₗ (Lens.Equiv.tensorComm P (P ⊸ R)).toLens


-- @@ L51-55 verbatim
@[simp]
theorem evaluation_toFunA (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB})
    (position : P.A × (P ⊸ R).A) :
    (evaluation P R).toFunA position = position.2.toFunA position.1 :=
  rfl


-- @@ L57-62 verbatim
@[simp]
theorem evaluation_toFunB (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB})
    (position : P.A × (P ⊸ R).A) (direction : R.B ((evaluation P R).toFunA position)) :
    (evaluation P R).toFunB position direction =
      (position.2.toFunB position.1 direction, ⟨position.1, direction⟩) :=
  rfl


-- @@ L64-68 verbatim
/-- Run a finite pattern on a cofree internal-hom answerer and evaluate every
synchronized node. This is the common Section 4 application composite. -/
def runAgainst (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB}) :
    Lens (FreeP P ⊗ CofreeP (P ⊸ R)) (FreeP R) :=
  runThrough (evaluation P R)


-- @@ L70-75 verbatim
/-- Equation (6): after an internal-hom answerer runs against the pattern,
fold the resulting free tree into any substitution monoid `T`. -/
def runAgainstMonoid (P : PFunctor.{pA, pB}) (T : SubstMonoid.{t, t}) :
    Lens (FreeP P ⊗ CofreeP (P ⊸ T.carrier)) T.carrier :=
  (FreeP.extend T (Lens.id T.carrier)).toLens ∘ₗ
    runAgainst P T.carrier


-- @@ L77-82 verbatim
/-- Factor the answerer matter through an existing dynamical system. The
backward map of this lens returns a pattern path together with the answerer
state reached after the selected sequence of questions/effects. -/
def runAgainstSystem (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB})
    (answerer : DynSystem S (P ⊸ R)) : Lens (FreeP P ⊗ selfMonomial S) (FreeP R) :=
  FreeP.map (evaluation P R) ∘ₗ runOnSystem P answerer


-- @@ L84-89 verbatim
/-- Evaluate a fixed pattern against the behavior generated by a system under
an arbitrary node interaction. -/
def runBehaviorThrough {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}} {R : PFunctor.{rA, rB}}
    (interaction : Lens (P ⊗ Q) R) (pattern : (FreeP P).A) (system : DynSystem S Q) (state : S) :
    (FreeP R).A :=
  (runThrough interaction).toFunA (pattern, system.behavior state)


-- @@ L91-97 verbatim
theorem runBehaviorThrough_eq_of_obsEq {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}}
    {R : PFunctor.{rA, rB}} (interaction : Lens (P ⊗ Q) R) (pattern : (FreeP P).A)
    {system₁ : DynSystem S₁ Q} {system₂ : DynSystem S₂ Q} {state₁ : S₁} {state₂ : S₂}
    (h : DynSystem.ObsEq system₁ system₂ state₁ state₂) :
    runBehaviorThrough interaction pattern system₁ state₁ =
      runBehaviorThrough interaction pattern system₂ state₂ :=
  congrArg (fun matter => (runThrough interaction).toFunA (pattern, matter)) h


-- @@ L99-107 verbatim
theorem runBehaviorThrough_eq_of_isSimulation {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}}
    {R : PFunctor.{rA, rB}} (interaction : Lens (P ⊗ Q) R) (pattern : (FreeP P).A)
    {system₁ : DynSystem S₁ Q} {system₂ : DynSystem S₂ Q} {Rel : S₁ → S₂ → Prop}
    (hsim : DynSystem.IsSimulation system₁ system₂ Rel) {state₁ : S₁} {state₂ : S₂}
    (hstate : Rel state₁ state₂) :
    runBehaviorThrough interaction pattern system₁ state₁ =
      runBehaviorThrough interaction pattern system₂ state₂ :=
  runBehaviorThrough_eq_of_obsEq interaction pattern
    (DynSystem.obsEq_of_isSimulation hsim hstate)


-- @@ L109-117 verbatim
theorem runBehaviorThrough_eq_of_isStrongSimulation {P : PFunctor.{pA, pB}} {Q : PFunctor.{qA, qB}}
    {R : PFunctor.{rA, rB}} (interaction : Lens (P ⊗ Q) R) (pattern : (FreeP P).A)
    {system₁ : DynSystem S₁ Q} {system₂ : DynSystem S₂ Q} {Rel : S₁ → S₂ → Prop}
    (hsim : Control.IsStrongSimulation system₁.toLTS system₂.toLTS Rel) {state₁ : S₁} {state₂ : S₂}
    (hstate : Rel state₁ state₂) :
    runBehaviorThrough interaction pattern system₁ state₁ =
      runBehaviorThrough interaction pattern system₂ state₂ :=
  runBehaviorThrough_eq_of_obsEq interaction pattern
    (DynSystem.obsEq_of_isStrongSimulation hsim hstate)


-- @@ L119-127 verbatim
/-- Observationally equivalent answerer states give the same evaluated finite
output tree. -/
theorem runAgainstSystem_toFunA_eq_of_obsEq (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB})
    {answerer₁ : DynSystem S₁ (P ⊸ R)} {answerer₂ : DynSystem S₂ (P ⊸ R)}
    {state₁ : S₁} {state₂ : S₂} (h : DynSystem.ObsEq answerer₁ answerer₂ state₁ state₂)
    (pattern : (FreeP P).A) :
    (runAgainstSystem P R answerer₁).toFunA (pattern, state₁) =
      (runAgainstSystem P R answerer₂).toFunA (pattern, state₂) :=
  congrArg (FreeP.map (evaluation P R)).toFunA (runOnSystem_toFunA_eq_of_obsEq h pattern)


-- @@ L129-138 verbatim
/-- Simulation-related answerer states therefore give the same evaluated
finite output tree. -/
theorem runAgainstSystem_toFunA_eq_of_isSimulation (P : PFunctor.{pA, pB}) (R : PFunctor.{rA, rB})
    {answerer₁ : DynSystem S₁ (P ⊸ R)} {answerer₂ : DynSystem S₂ (P ⊸ R)} {Rel : S₁ → S₂ → Prop}
    (hsim : DynSystem.IsSimulation answerer₁ answerer₂ Rel) {state₁ : S₁} {state₂ : S₂}
    (hstate : Rel state₁ state₂) (pattern : (FreeP P).A) :
    (runAgainstSystem P R answerer₁).toFunA (pattern, state₁) =
      (runAgainstSystem P R answerer₂).toFunA (pattern, state₂) :=
  runAgainstSystem_toFunA_eq_of_obsEq P R
    (DynSystem.obsEq_of_isSimulation hsim hstate) pattern


-- @@ L140-140 verbatim
end FreeP

-- @@ L141-141 verbatim
end PFunctor
