/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import PolyFun.ITree.Bisim.Defs


-- @@ L10-49 verbatim
/-! # Equivalence laws for ITree (weak) bisimulation

Reflexivity, symmetry, and transitivity of `ITree.WeakBisim`, plus the
`Setoid (ITree F α)` instance generated by it.

## Strategy

The proofs use the Tarski greatest fixed point characterization
`WeakBisim t s = ∃ R, (closure under WeakBisimF) ∧ R t s`.

* **Reflexivity**: take `R := Eq`. The closure is immediate from the
  three head cases of `Match`.

* **Symmetry**: take `R := swap WeakBisim`. The closure follows from
  `Match.swap`.

* **Transitivity**: this is the deep one. Following the Coq
  `InteractionTrees` proof of `eutt_trans` (Xia et al., POPL 2020), the
  argument must reconcile the interaction between τ-stripping and head
  alignment when the intermediate term has a divergent step. We discharge
  it here without the paco "up-to" machinery by combining two workhorse
  devices:

  - the τ-absorption lemmas (`absorb_tauSteps_left`, `step_absorb_right`,
    `absorb_tauSteps_right`, `tauSteps_weakBisim_left`,
    `weakBisim_of_tauSteps_right`), which let us slide finite τ-strips
    through a `WeakBisim`, and
  - `Match.advance_left` / `Match.advance_right`, which advance a
    `Match WeakBisim` witness across a τ-strip on either endpoint.

  Together with `TauSteps.linear` they reduce the transitivity witness
  to a head-aligned `Match.trans_aligned`.

## Helpers

The τ-absorption lemmas are independently useful and are exported for
downstream proofs. They correspond to the "tau-eutt" lemmas in the
Coq library and are the workhorses of weak-bisim reasoning in the
absence of full transitivity.
-/


-- @@ L51-51 verbatim
@[expose] public section


-- @@ L53-53 verbatim
universe uFA uFB uα uβ uγ


-- @@ L55-55 verbatim
namespace ITree


-- @@ L57-57 verbatim
variable {F : PFunctor.{uFA, uFB}} {α : Type uα} {β : Type uβ}


-- @@ L59-59 verbatim
/-! ### `Bisim` is an equivalence -/


-- @@ L61-62 verbatim
theorem Bisim.equivalence : Equivalence (Bisim (F := F) (α := α)) :=
  ⟨Bisim.refl', Bisim.symm', Bisim.trans'⟩


-- @@ L64-64 verbatim
/-! ### Helper lemmas on `TauSteps` -/


-- @@ L66-66 verbatim
namespace TauSteps


-- @@ L68-74 verbatim
/-- If `t` has a pure head, then `TauSteps t t'` forces `t' = t`. -/
theorem rigid_of_pure {t t' : ITree F α} (r : α)
    (ht : shape' t = ⟨.pure r, PEmpty.elim⟩)
    (h : TauSteps t t') : t' = t := by
  cases h with
  | refl _ => rfl
  | step c hstep _ => rw [ht] at hstep; cases hstep


-- @@ L76-82 verbatim
/-- If `t` has a query head, then `TauSteps t t'` forces `t' = t`. -/
theorem rigid_of_query {t t' : ITree F α} (a : F.A) (c : F.B a → ITree F α)
    (ht : shape' t = ⟨.query a, c⟩)
    (h : TauSteps t t') : t' = t := by
  cases h with
  | refl _ => rfl
  | step c' hstep _ => rw [ht] at hstep; cases hstep


-- @@ L84-95 verbatim
/-- Determinism of τ-stripping on a step-headed tree: a stripping from
a step-headed tree either does nothing or proceeds through the unique
step continuation. -/
theorem step_cases {t t' : ITree F α} (c : PUnit.{uFB + 1} → ITree F α)
    (ht : shape' t = ⟨.step, c⟩) (h : TauSteps t t') :
    t' = t ∨ TauSteps (c PUnit.unit) t' := by
  cases h with
  | refl _ => exact Or.inl rfl
  | @step _ t'' c' ht' hr =>
      have hcc : c = c' := TauSteps.cont_eq ht ht'
      subst hcc
      exact Or.inr hr


-- @@ L97-110 verbatim
private theorem diverge_target_eq_aux {source t : ITree F α}
    (hsource : source = diverge) (h : TauSteps source t) :
    t = diverge :=
  TauSteps.rec
    (motive := fun initial target _ =>
      initial = diverge → target = diverge)
    (fun _ hs => hs)
    (fun {t t'} c hstep (_ : TauSteps (c PUnit.unit) t') ih hs => by
      subst t
      have hc : c = fun _ => diverge :=
        TauSteps.cont_eq hstep shape'_diverge
      subst c
      exact ih rfl)
    h hsource


-- @@ L112-116 verbatim
/-- Every finite silent stripping of `diverge` still ends at `diverge`. -/
theorem diverge_target_eq {t : ITree F α}
    (h : TauSteps (diverge (F := F) (α := α)) t) :
    t = diverge :=
  diverge_target_eq_aux rfl h


-- @@ L118-118 verbatim
end TauSteps


-- @@ L120-120 verbatim
/-! ### Basic relational laws -/


-- @@ L122-122 verbatim
namespace WeakBisimRel


-- @@ L124-129 verbatim
/-- Pure trees are relationally weakly bisimilar exactly when their return
values are related. -/
theorem pure {RR : α → β → Prop} {r : α} {s : β} (h : RR r s) :
    WeakBisimRel RR (pure (F := F) r) (pure (F := F) s) := by
  refine fold ⟨ITree.pure r, ITree.pure s, .refl _, .refl _, ?_⟩
  exact MatchRel.pure r s h (shape'_pure r) (shape'_pure s)


-- @@ L131-144 verbatim
/-- Relational reflexivity, assuming the return relation is reflexive. -/
theorem refl {RR : α → α → Prop} (hRR : ∀ r, RR r r) (t : ITree F α) :
    WeakBisimRel RR t t := by
  refine coinduct RR Eq ?_ rfl
  rintro a b rfl
  rcases hsh : shape' a with ⟨sh, c⟩
  refine ⟨a, a, .refl _, .refl _, ?_⟩
  cases sh with
  | pure r =>
      refine MatchRel.pure r r (hRR r) ?_ ?_
      · rw [hsh]; congr 1; funext z; exact z.elim
      · rw [hsh]; congr 1; funext z; exact z.elim
  | step => exact MatchRel.tau c c hsh hsh rfl
  | query a => exact MatchRel.query a c c hsh hsh (fun _ => rfl)


-- @@ L146-154 verbatim
/-- Swap a relational weak bisimulation and reverse its return relation. -/
theorem symm {RR : α → β → Prop} {t : ITree F α} {s : ITree F β}
    (h : WeakBisimRel RR t s) :
    WeakBisimRel (fun b a => RR a b) s t := by
  obtain ⟨R, hcl, hR⟩ := h
  refine coinduct (fun b a => RR a b) (fun a b => R b a) ?_ hR
  intro a b hab
  obtain ⟨b', a', hb, ha, hm⟩ := hcl _ _ hab
  exact ⟨a', b', ha, hb, MatchRel.swap hm⟩


-- @@ L156-167 verbatim
/-- Prepending finitely many silent steps on the left preserves relational
weak bisimulation. -/
theorem absorb_tauSteps_left {RR : α → β → Prop}
    {t t' : ITree F α} {s : ITree F β}
    (h : TauSteps t t') (hw : WeakBisimRel RR t' s) : WeakBisimRel RR t s := by
  refine coinduct RR
    (fun x y => ∃ x', TauSteps x x' ∧ WeakBisimRel RR x' y) ?_ ⟨t', h, hw⟩
  rintro a b ⟨a', haa', hab⟩
  obtain ⟨a'', b', ha'a'', hbb', M⟩ := hab.dest
  refine ⟨a'', b', haa'.trans ha'a'', hbb', M.mono ?_⟩
  intro x y hxy
  exact ⟨x, .refl _, hxy⟩


-- @@ L169-180 verbatim
/-- Appending finitely many silent steps before the right endpoint preserves
relational weak bisimulation. -/
theorem of_tauSteps_right {RR : α → β → Prop}
    {t : ITree F α} {s s' : ITree F β}
    (h : WeakBisimRel RR t s') (hstrip : TauSteps s s') :
    WeakBisimRel RR t s := by
  refine coinduct RR
    (fun x y => ∃ y', TauSteps y y' ∧ WeakBisimRel RR x y') ?_ ⟨s', hstrip, h⟩
  rintro a b ⟨b', hbb', hab'⟩
  obtain ⟨a', b'', ha, hb, M⟩ := hab'.dest
  exact ⟨a', b'', ha, hbb'.trans hb,
    M.mono (fun _ y hxy => ⟨y, .refl _, hxy⟩)⟩


-- @@ L182-185 verbatim
/-- A leading silent step on the left is observationally irrelevant. -/
theorem step_left {RR : α → β → Prop} {t : ITree F α} {s : ITree F β}
    (h : WeakBisimRel RR t s) : WeakBisimRel RR (step t) s :=
  absorb_tauSteps_left (TauSteps.one (fun _ => t) (shape'_step t)) h


-- @@ L187-190 verbatim
/-- A leading silent step on the right is observationally irrelevant. -/
theorem step_right {RR : α → β → Prop} {t : ITree F α} {s : ITree F β}
    (h : WeakBisimRel RR t s) : WeakBisimRel RR t (step s) :=
  of_tauSteps_right h (TauSteps.one (fun _ => s) (shape'_step s))


-- @@ L192-195 verbatim
/-- Paired leading silent steps preserve relational weak bisimulation. -/
theorem step {RR : α → β → Prop} {t : ITree F α} {s : ITree F β}
    (h : WeakBisimRel RR t s) : WeakBisimRel RR (ITree.step t) (ITree.step s) :=
  (step_left h).step_right


-- @@ L197-277 verbatim
/-- Strip one silent step from the right endpoint of a relational weak
bisimulation. This is the direction not supplied directly by the post-fixed
point constructors and is the key to relational composition. -/
theorem step_absorb_right {RR : α → β → Prop}
    {t : ITree F α} {s : ITree F β}
    (c : PUnit.{uFB + 1} → ITree F β) (h : WeakBisimRel RR t s)
    (hstep : shape' s = ⟨.step, c⟩) :
    WeakBisimRel RR t (c PUnit.unit) := by
  refine coinduct RR
    (fun x z => WeakBisimRel RR x z ∨
      ∃ (s' : ITree F β) (c' : PUnit.{uFB + 1} → ITree F β),
        WeakBisimRel RR x s' ∧ shape' s' = ⟨.step, c'⟩ ∧ z = c' PUnit.unit)
    ?_ (Or.inr ⟨s, c, h, hstep, rfl⟩)
  intro a b hab
  rcases hab with hab | ⟨s', c', hab, hstep', rfl⟩
  · obtain ⟨a', b', ha, hb, M⟩ := hab.dest
    exact ⟨a', b', ha, hb, M.mono (fun _ _ hxy => Or.inl hxy)⟩
  · obtain ⟨a', s₁, ha, hs, M⟩ := hab.dest
    rcases TauSteps.step_cases c' hstep' hs with hs_eq | hs_strict
    · subst hs_eq
      cases M with
      | pure _ _ _ _ hs_bad => rw [hstep'] at hs_bad; cases hs_bad
      | query _ _ _ _ hs_bad _ => rw [hstep'] at hs_bad; cases hs_bad
      | tau ct cs ht_a hs_a hr =>
          have hcc : cs = c' := TauSteps.cont_eq hs_a hstep'
          subst hcc
          rcases hsh : shape' (cs PUnit.unit) with ⟨sh, cc⟩
          cases sh with
          | pure r =>
              have hsh' : shape' (cs PUnit.unit) =
                  ⟨Shape.pure r, PEmpty.elim⟩ := by
                rw [hsh]
                congr 1
                funext z
                exact z.elim
              obtain ⟨X, Y, hX, hY, MXY⟩ := hr.dest
              have hYeq : Y = cs PUnit.unit :=
                TauSteps.rigid_of_pure r hsh' hY
              subst hYeq
              cases MXY with
              | pure x y hxy hX' hY' =>
                  have heq : (⟨Shape.pure y, PEmpty.elim⟩ :
                      (ViewPoly F β).Obj (ITree F β)) =
                      ⟨Shape.pure r, PEmpty.elim⟩ := hY'.symm.trans hsh'
                  have hyr : y = r := Shape.pure.inj (Sigma.mk.inj heq).1
                  subst y
                  refine ⟨X, cs PUnit.unit,
                    ha.trans ((TauSteps.one ct ht_a).trans hX), .refl _, ?_⟩
                  exact MatchRel.pure x r hxy hX' hsh'
              | query _ _ _ _ hY' _ =>
                  rw [hY'] at hsh'; cases hsh'
              | tau _ _ _ hY' _ =>
                  rw [hY'] at hsh'; cases hsh'
          | step =>
              refine ⟨a', cs PUnit.unit, ha, .refl _, ?_⟩
              refine MatchRel.tau ct cc ht_a hsh ?_
              exact Or.inr ⟨cs PUnit.unit, cc, hr, hsh, rfl⟩
          | query q =>
              obtain ⟨X, Y, hX, hY, MXY⟩ := hr.dest
              have hYeq : Y = cs PUnit.unit :=
                TauSteps.rigid_of_query q cc hsh hY
              subst hYeq
              cases MXY with
              | pure _ _ _ _ hY' =>
                  rw [hY'] at hsh; cases hsh
              | query q' cX cY hX' hY' hcont =>
                  have heq : (⟨Shape.query q', cY⟩ :
                      (ViewPoly F β).Obj (ITree F β)) =
                      ⟨Shape.query q, cc⟩ := hY'.symm.trans hsh
                  have hqq : q' = q := Shape.query.inj (Sigma.mk.inj heq).1
                  subst hqq
                  have hcc : cY = cc := eq_of_heq (Sigma.mk.inj heq).2
                  subst hcc
                  refine ⟨X, cs PUnit.unit,
                    ha.trans ((TauSteps.one ct ht_a).trans hX), .refl _, ?_⟩
                  exact MatchRel.query q' cX cY hX' hsh
                    (fun reply => Or.inl (hcont reply))
              | tau _ _ _ hY' _ =>
                  rw [hY'] at hsh; cases hsh
    · exact ⟨a', s₁, ha, hs_strict,
        M.mono (fun _ _ hxy => Or.inl hxy)⟩


-- @@ L279-286 verbatim
/-- Strip finitely many silent steps from the right endpoint. -/
theorem absorb_tauSteps_right {RR : α → β → Prop}
    {t : ITree F α} {s s' : ITree F β}
    (h : WeakBisimRel RR t s) (hstrip : TauSteps s s') :
    WeakBisimRel RR t s' := by
  induction hstrip generalizing t with
  | refl _ => exact h
  | @step _ _ c ht hr ih => exact ih (step_absorb_right c h ht)


-- @@ L288-294 verbatim
/-- Strip finitely many silent steps from the left endpoint. -/
theorem tauSteps_left {RR : α → β → Prop}
    {t t' : ITree F α} {s : ITree F β}
    (h : WeakBisimRel RR t s) (hstrip : TauSteps t t') :
    WeakBisimRel RR t' s := by
  have hs := absorb_tauSteps_right (RR := fun y x => RR x y) h.symm hstrip
  exact hs.symm


-- @@ L296-296 verbatim
end WeakBisimRel


-- @@ L298-298 verbatim
/-! ### Relational head alignment -/


-- @@ L300-300 verbatim
namespace MatchRel


-- @@ L302-323 verbatim
/-- Advance the right endpoint of a relational head match through silent
steps, absorbing those steps into its continuation relation. -/
theorem advance_right {RR : α → β → Prop}
    {x : ITree F α} {z₁ z₂ : ITree F β}
    (headMatch : MatchRel RR (WeakBisimRel RR) x z₁)
    (steps : TauSteps z₁ z₂) :
    ∃ x' z', TauSteps x x' ∧ TauSteps z₂ z' ∧
      MatchRel RR (WeakBisimRel RR) x' z' := by
  induction steps generalizing x with
  | refl z => exact ⟨x, z, .refl _, .refl _, headMatch⟩
  | @step _ z₂' c hz hr _ =>
      cases headMatch with
      | pure _ _ _ _ hp => rw [hp] at hz; cases hz
      | query _ _ _ _ hq _ => rw [hq] at hz; cases hz
      | tau ct cs hx hz' hrel =>
          have hcc : cs = c := TauSteps.cont_eq hz' hz
          subst hcc
          have hrel' : WeakBisimRel RR (ct PUnit.unit) z₂' :=
            WeakBisimRel.absorb_tauSteps_right hrel hr
          obtain ⟨X, Z, hX, hZ, matched⟩ := hrel'.dest
          refine ⟨X, Z, ?_, hZ, matched⟩
          exact (TauSteps.one ct hx).trans hX


-- @@ L325-346 verbatim
/-- Advance the left endpoint of a relational head match through silent
steps, absorbing those steps into its continuation relation. -/
theorem advance_left {RR : α → β → Prop}
    {x₁ x₂ : ITree F α} {z : ITree F β}
    (headMatch : MatchRel RR (WeakBisimRel RR) x₁ z)
    (steps : TauSteps x₁ x₂) :
    ∃ x' z', TauSteps x₂ x' ∧ TauSteps z z' ∧
      MatchRel RR (WeakBisimRel RR) x' z' := by
  induction steps generalizing z with
  | refl x => exact ⟨x, z, .refl _, .refl _, headMatch⟩
  | @step _ x₂' c hx hr _ =>
      cases headMatch with
      | pure _ _ _ hp _ => rw [hp] at hx; cases hx
      | query _ _ _ hp _ _ => rw [hp] at hx; cases hx
      | tau ct cs hx' hz hrel =>
          have hcc : c = ct := TauSteps.cont_eq hx hx'
          subst hcc
          have hrel' : WeakBisimRel RR x₂' (cs PUnit.unit) :=
            WeakBisimRel.tauSteps_left hrel hr
          obtain ⟨X, Z, hX, hZ, matched⟩ := hrel'.dest
          refine ⟨X, Z, hX, ?_, matched⟩
          exact (TauSteps.one cs hz).trans hZ


-- @@ L348-390 verbatim
/-- Compose two head matches aligned at the same middle tree. The intermediate
return value remains explicit in `Relation.Comp`. -/
theorem comp_aligned {γ : Type uγ} {RR : α → β → Prop} {SS : β → γ → Prop}
    {left : ITree F α} {middle : ITree F β} {right : ITree F γ}
    (first : MatchRel RR (WeakBisimRel RR) left middle)
    (second : MatchRel SS (WeakBisimRel SS) middle right) :
    MatchRel (Relation.Comp RR SS)
      (fun x z => ∃ y, WeakBisimRel RR x y ∧ WeakBisimRel SS y z)
      left right := by
  cases first with
  | pure x y hxy hleft hmiddle =>
      cases second with
      | pure y' z hyz hmiddle' hright =>
          have heq : (⟨Shape.pure y, PEmpty.elim⟩ :
              (ViewPoly F β).Obj (ITree F β)) =
              ⟨Shape.pure y', PEmpty.elim⟩ := hmiddle.symm.trans hmiddle'
          have hyy : y = y' := Shape.pure.inj (Sigma.mk.inj heq).1
          subst y'
          exact .pure x z ⟨y, hxy, hyz⟩ hleft hright
      | query _ _ _ hbad _ _ => rw [hmiddle] at hbad; cases hbad
      | tau _ _ hbad _ _ => rw [hmiddle] at hbad; cases hbad
  | query event cLeft cMiddle hleft hmiddle hcont =>
      cases second with
      | pure _ _ _ hbad _ => rw [hmiddle] at hbad; cases hbad
      | query event' cMiddle' cRight hmiddle' hright hcont' =>
          have heq : (⟨Shape.query event, cMiddle⟩ :
              (ViewPoly F β).Obj (ITree F β)) =
              ⟨Shape.query event', cMiddle'⟩ := hmiddle.symm.trans hmiddle'
          have hevent : event = event' := Shape.query.inj (Sigma.mk.inj heq).1
          subst event'
          have hc : cMiddle = cMiddle' := eq_of_heq (Sigma.mk.inj heq).2
          subst cMiddle'
          exact .query event cLeft cRight hleft hright
            (fun reply => ⟨cMiddle reply, hcont reply, hcont' reply⟩)
      | tau _ _ hbad _ _ => rw [hmiddle] at hbad; cases hbad
  | tau cLeft cMiddle hleft hmiddle hcont =>
      cases second with
      | pure _ _ _ hbad _ => rw [hmiddle] at hbad; cases hbad
      | query _ _ _ hbad _ _ => rw [hmiddle] at hbad; cases hbad
      | tau cMiddle' cRight hmiddle' hright hcont' =>
          have hc : cMiddle' = cMiddle := TauSteps.cont_eq hmiddle' hmiddle
          exact .tau cLeft cRight hleft hright
            ⟨cMiddle PUnit.unit, hcont, hc ▸ hcont'⟩


-- @@ L392-392 verbatim
end MatchRel


-- @@ L394-394 verbatim
namespace WeakBisimRel


-- @@ L396-546 verbatim
/-- Relational weak bisimulations compose through an explicit intermediate
return value. This is the heterogeneous form of `WeakBisim.trans`. -/
protected theorem comp {γ : Type uγ} {RR : α → β → Prop}
    {SS : β → γ → Prop}
    {left : ITree F α} {middle : ITree F β} {right : ITree F γ}
    (first : WeakBisimRel RR left middle)
    (second : WeakBisimRel SS middle right) :
    WeakBisimRel (Relation.Comp RR SS) left right := by
  let R : ITree F α → ITree F γ → Prop := fun x z =>
    ∃ y, WeakBisimRel RR x y ∧ WeakBisimRel SS y z
  refine coinduct (Relation.Comp RR SS) R ?_ ⟨middle, first, second⟩
  rintro a d ⟨b, hab, hbd⟩
  obtain ⟨a', b₁, ha, hb₁, Ma⟩ := hab.dest
  obtain ⟨b₂, d', hb₂, hd, Mb⟩ := hbd.dest
  cases TauSteps.linear hb₁ hb₂ with
  | inl hlin =>
      obtain ⟨a'', b', ha', hb', Ma'⟩ := MatchRel.advance_right Ma hlin
      obtain ⟨b'', d'', hb'', hd', Mb'⟩ := MatchRel.advance_left Mb hb'
      cases Ma' with
      | pure x y hxy Ha Hb =>
          have hEq : b'' = b' := TauSteps.rigid_of_pure y Hb hb''
          subst hEq
          exact ⟨a'', d'', ha.trans ha', hd.trans hd',
            (MatchRel.pure x y hxy Ha Hb).comp_aligned Mb'⟩
      | query event ca cb Ha Hb hcont =>
          have hEq : b'' = b' := TauSteps.rigid_of_query event cb Hb hb''
          subst hEq
          exact ⟨a'', d'', ha.trans ha', hd.trans hd',
            (MatchRel.query event ca cb Ha Hb hcont).comp_aligned Mb'⟩
      | tau ca cb Ha Hb hAB =>
          rcases TauSteps.step_cases cb Hb hb'' with hEq | hrest
          · subst hEq
            exact ⟨a'', d'', ha.trans ha', hd.trans hd',
              (MatchRel.tau ca cb Ha Hb hAB).comp_aligned Mb'⟩
          · cases Mb' with
            | pure y z hyz Hb'' Hd'' =>
                have hAC : WeakBisimRel RR (ca PUnit.unit) b'' :=
                  absorb_tauSteps_right hAB hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hAC.dest
                have hYeq : Y = b'' := TauSteps.rigid_of_pure y Hb'' hY
                subst hYeq
                cases MXY with
                | pure x y' hxy HX HY =>
                    have heq : (⟨Shape.pure y', PEmpty.elim⟩ :
                        (ViewPoly F β).Obj (ITree F β)) =
                        ⟨Shape.pure y, PEmpty.elim⟩ := HY.symm.trans Hb''
                    have hyy : y' = y := Shape.pure.inj (Sigma.mk.inj heq).1
                    subst y'
                    refine ⟨X, d'',
                      ha.trans (ha'.trans ((TauSteps.one ca Ha).trans hX)),
                      hd.trans hd', ?_⟩
                    exact MatchRel.pure x z ⟨y, hxy, hyz⟩ HX Hd''
                | query _ _ _ _ HY _ => rw [HY] at Hb''; cases Hb''
                | tau _ _ _ HY _ => rw [HY] at Hb''; cases Hb''
            | query event cMiddle cRight Hb'' Hd'' hBD =>
                have hAC : WeakBisimRel RR (ca PUnit.unit) b'' :=
                  absorb_tauSteps_right hAB hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hAC.dest
                have hYeq : Y = b'' :=
                  TauSteps.rigid_of_query event cMiddle Hb'' hY
                subst hYeq
                cases MXY with
                | pure _ _ _ _ HY => rw [HY] at Hb''; cases Hb''
                | query event' cLeft cMiddle' HX HY hAC' =>
                    have heq : (⟨Shape.query event', cMiddle'⟩ :
                        (ViewPoly F β).Obj (ITree F β)) =
                        ⟨Shape.query event, cMiddle⟩ := HY.symm.trans Hb''
                    have hevent : event' = event :=
                      Shape.query.inj (Sigma.mk.inj heq).1
                    subst event'
                    have hc : cMiddle' = cMiddle := eq_of_heq (Sigma.mk.inj heq).2
                    subst cMiddle'
                    refine ⟨X, d'',
                      ha.trans (ha'.trans ((TauSteps.one ca Ha).trans hX)),
                      hd.trans hd', ?_⟩
                    exact MatchRel.query event cLeft cRight HX Hd''
                      (fun reply => ⟨cMiddle reply, hAC' reply, hBD reply⟩)
                | tau _ _ _ HY _ => rw [HY] at Hb''; cases Hb''
            | tau cMiddle cRight Hb'' Hd'' hBD =>
                refine ⟨a'', d'', ha.trans ha', hd.trans hd', ?_⟩
                refine MatchRel.tau ca cRight Ha Hd'' ?_
                refine ⟨cMiddle PUnit.unit, ?_, hBD⟩
                exact absorb_tauSteps_right hAB
                  (hrest.trans (TauSteps.one cMiddle Hb''))
  | inr hlin =>
      obtain ⟨b', d'', hb', hd', Mb'⟩ := MatchRel.advance_left Mb hlin
      obtain ⟨a'', b'', ha', hb'', Ma'⟩ := MatchRel.advance_right Ma hb'
      cases Mb' with
      | pure y z hyz Hb Hd =>
          have hEq : b'' = b' := TauSteps.rigid_of_pure y Hb hb''
          subst hEq
          exact ⟨a'', d'', ha.trans ha', hd.trans hd',
            Ma'.comp_aligned (MatchRel.pure y z hyz Hb Hd)⟩
      | query event cb cd Hb Hd hcont =>
          have hEq : b'' = b' := TauSteps.rigid_of_query event cb Hb hb''
          subst hEq
          exact ⟨a'', d'', ha.trans ha', hd.trans hd',
            Ma'.comp_aligned (MatchRel.query event cb cd Hb Hd hcont)⟩
      | tau cb cd Hb Hd hBD =>
          rcases TauSteps.step_cases cb Hb hb'' with hEq | hrest
          · subst hEq
            exact ⟨a'', d'', ha.trans ha', hd.trans hd',
              Ma'.comp_aligned (MatchRel.tau cb cd Hb Hd hBD)⟩
          · cases Ma' with
            | pure x y hxy Ha Hb'' =>
                have hBD' : WeakBisimRel SS b'' (cd PUnit.unit) :=
                  tauSteps_left hBD hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hBD'.dest
                have hXeq : X = b'' := TauSteps.rigid_of_pure y Hb'' hX
                subst hXeq
                cases MXY with
                | pure y' z hyz HX HY =>
                    have heq : (⟨Shape.pure y', PEmpty.elim⟩ :
                        (ViewPoly F β).Obj (ITree F β)) =
                        ⟨Shape.pure y, PEmpty.elim⟩ := HX.symm.trans Hb''
                    have hyy : y' = y := Shape.pure.inj (Sigma.mk.inj heq).1
                    subst y'
                    refine ⟨a'', Y, ha.trans ha',
                      hd.trans (hd'.trans ((TauSteps.one cd Hd).trans hY)), ?_⟩
                    exact MatchRel.pure x z ⟨y, hxy, hyz⟩ Ha HY
                | query _ _ _ HX _ _ => rw [HX] at Hb''; cases Hb''
                | tau _ _ HX _ _ => rw [HX] at Hb''; cases Hb''
            | query event cLeft cMiddle Ha Hb'' hAB =>
                have hBD' : WeakBisimRel SS b'' (cd PUnit.unit) :=
                  tauSteps_left hBD hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hBD'.dest
                have hXeq : X = b'' :=
                  TauSteps.rigid_of_query event cMiddle Hb'' hX
                subst hXeq
                cases MXY with
                | pure _ _ _ HX _ => rw [HX] at Hb''; cases Hb''
                | query event' cMiddle' cRight HX HY hBD' =>
                    have heq : (⟨Shape.query event', cMiddle'⟩ :
                        (ViewPoly F β).Obj (ITree F β)) =
                        ⟨Shape.query event, cMiddle⟩ := HX.symm.trans Hb''
                    have hevent : event' = event :=
                      Shape.query.inj (Sigma.mk.inj heq).1
                    subst event'
                    have hc : cMiddle' = cMiddle := eq_of_heq (Sigma.mk.inj heq).2
                    subst cMiddle'
                    refine ⟨a'', Y, ha.trans ha',
                      hd.trans (hd'.trans ((TauSteps.one cd Hd).trans hY)), ?_⟩
                    exact MatchRel.query event cLeft cRight Ha HY
                      (fun reply => ⟨cMiddle reply, hAB reply, hBD' reply⟩)
                | tau _ _ HX _ _ => rw [HX] at Hb''; cases Hb''
            | tau cLeft cMiddle Ha Hb'' hAB =>
                refine ⟨a'', d'', ha.trans ha', hd.trans hd', ?_⟩
                refine MatchRel.tau cLeft cd Ha Hd ?_
                refine ⟨cMiddle PUnit.unit, hAB, ?_⟩
                exact tauSteps_left hBD
                  (hrest.trans (TauSteps.one cMiddle Hb''))


-- @@ L548-548 verbatim
end WeakBisimRel


-- @@ L550-550 verbatim
/-! ### `WeakBisim` is an equivalence -/


-- @@ L552-552 verbatim
namespace WeakBisim


-- @@ L554-574 verbatim
/-- A terminating return is not weakly bisimilar to silent divergence.
This is the central finite-τ safety property of the definition. -/
theorem pure_not_diverge (r : α) :
    ¬ WeakBisim (pure (F := F) r) (diverge (F := F) (α := α)) := by
  intro h
  obtain ⟨left, right, hleft, hright, matched⟩ := h.dest
  have hleft_eq : left = pure (F := F) r :=
    TauSteps.rigid_of_pure r (shape'_pure r) hleft
  have hright_eq : right = diverge := TauSteps.diverge_target_eq hright
  subst left
  subst right
  cases matched with
  | pure _ _ hdiverge =>
      rw [shape'_diverge] at hdiverge
      cases hdiverge
  | query _ _ _ hpure _ _ =>
      rw [shape'_pure] at hpure
      cases hpure
  | tau _ _ hpure _ _ =>
      rw [shape'_pure] at hpure
      cases hpure


-- @@ L576-588 verbatim
/-- Reflexivity: every tree is weakly bisimilar to itself. -/
@[refl] theorem refl (t : ITree F α) : t ≈ t := by
  refine coinduct Eq ?_ rfl
  rintro a b rfl
  rcases hsh : shape' a with ⟨sh, c⟩
  refine ⟨a, a, .refl _, .refl _, ?_⟩
  cases sh with
  | pure r =>
      refine Match.pure r ?_ ?_
      · rw [hsh]; congr 1; funext z; exact z.elim
      · rw [hsh]; congr 1; funext z; exact z.elim
  | step => exact Match.tau c c hsh hsh rfl
  | query a => exact Match.query a c c hsh hsh (fun _ => rfl)


-- @@ L590-592 verbatim
/-- Symmetry: weak bisimilarity is symmetric. -/
@[symm] theorem symm {t s : ITree F α} (h : t ≈ s) : s ≈ t :=
  (WeakBisimRel.symm h).mono_result (fun _ _ hEq => hEq.symm)


-- @@ L594-599 verbatim
/-! ### τ-absorption lemmas

These are the "tau-eutt" lemmas: τ-stripping on either side of a weak
bisimulation produces another weak bisimulation. They are independently
useful and form the building blocks for transitivity.
-/


-- @@ L601-609 verbatim
/-- Absorbing a LHS τ-strip into a weak bisimulation. -/
theorem absorb_tauSteps_left {t t' s : ITree F α}
    (h : TauSteps t t') (hw : t' ≈ s) : t ≈ s := by
  refine coinduct (fun x y => ∃ x', TauSteps x x' ∧ x' ≈ y) ?_ ⟨t', h, hw⟩
  rintro a b ⟨a', haa', hab⟩
  obtain ⟨a'', b', ha'a'', hbb', M⟩ := hab.dest
  refine ⟨a'', b', haa'.trans ha'a'', hbb', M.mono ?_⟩
  intro x y hxy
  exact ⟨x, .refl _, hxy⟩


-- @@ L611-693 verbatim
/-- Absorbing a single step τ-strip on the RHS of a weak bisimulation:
given `t ≈ s` and `s` step-headed with continuation `c`, conclude
`t ≈ (c .unit)`. The proof unfolds the bisim once and case-analyzes on
the head of `(c .unit)`, in the worst case unfolding the inner
`WeakBisim (ct .unit) (cs .unit)` one more level to reach a head match. -/
theorem step_absorb_right {t s : ITree F α} (c : PUnit.{uFB + 1} → ITree F α)
    (h : t ≈ s) (hstep : shape' s = ⟨.step, c⟩) :
    t ≈ (c PUnit.unit) := by
  refine coinduct
    (fun x z => x ≈ z ∨
      ∃ (s' : ITree F α) (c' : PUnit.{uFB + 1} → ITree F α),
        x ≈ s' ∧ shape' s' = ⟨.step, c'⟩ ∧ z = (c' PUnit.unit))
    ?_ (Or.inr ⟨s, c, h, hstep, rfl⟩)
  intro a b hab
  rcases hab with hab | ⟨s', c', hab, hstep', hz⟩
  · obtain ⟨a', b', ha, hb, M⟩ := hab.dest
    exact ⟨a', b', ha, hb, M.mono (fun _ _ hxy => Or.inl hxy)⟩
  subst hz
  obtain ⟨a', s₁, ha, hs, M⟩ := hab.dest
  rcases TauSteps.step_cases c' hstep' hs with hs_eq | hs_strict
  · subst hs_eq
    cases M with
    | pure _ _ hs_bad => rw [hstep'] at hs_bad; cases hs_bad
    | query _ _ _ _ hs_bad _ => rw [hstep'] at hs_bad; cases hs_bad
    | tau ct cs ht_a hs_a hr_weak =>
        have hcc : cs = c' := TauSteps.cont_eq hs_a hstep'
        subst hcc
        rcases hshc : shape' (cs PUnit.unit) with ⟨sh_c, c_cc⟩
        cases sh_c with
        | pure r =>
            have hshc_rw : shape' (cs PUnit.unit) =
                ⟨Shape.pure r, PEmpty.elim⟩ := by
              rw [hshc]; congr 1; funext z; exact z.elim
            obtain ⟨X, Y, hX, hY, MxY⟩ := hr_weak.dest
            have hY_eq : Y = (cs PUnit.unit) :=
              TauSteps.rigid_of_pure r hshc_rw hY
            subst hY_eq
            cases MxY with
            | pure r' ht_X hs_Y =>
                have hEq1 : (⟨Shape.pure r', PEmpty.elim⟩ :
                    (ViewPoly F α).Obj (ITree F α)) =
                  ⟨Shape.pure r, PEmpty.elim⟩ := hs_Y.symm.trans hshc_rw
                have hrr : r' = r := Shape.pure.inj (Sigma.mk.inj hEq1).1
                subst hrr
                refine ⟨X, cs PUnit.unit,
                    ha.trans ((TauSteps.one ct ht_a).trans hX), .refl _, ?_⟩
                exact Match.pure r' ht_X hshc_rw
            | query _ _ _ _ hs_Y _ =>
                rw [hs_Y] at hshc_rw; cases hshc_rw
            | tau _ _ _ hs_Y _ =>
                rw [hs_Y] at hshc_rw; cases hshc_rw
        | step =>
            have hshc_rw : shape' (cs PUnit.unit) = ⟨Shape.step, c_cc⟩ := hshc
            refine ⟨a', cs PUnit.unit, ha, .refl _, ?_⟩
            refine Match.tau ct c_cc ht_a hshc_rw ?_
            exact Or.inr ⟨cs PUnit.unit, c_cc, hr_weak, hshc_rw, rfl⟩
        | query qa =>
            have hshc_rw : shape' (cs PUnit.unit) =
                ⟨Shape.query qa, c_cc⟩ := hshc
            obtain ⟨X, Y, hX, hY, MxY⟩ := hr_weak.dest
            have hY_eq : Y = (cs PUnit.unit) :=
              TauSteps.rigid_of_query qa c_cc hshc_rw hY
            subst hY_eq
            cases MxY with
            | pure _ _ hs_Y =>
                rw [hs_Y] at hshc_rw; cases hshc_rw
            | query qa' c_X c_Y ht_X hs_Y hcc_XY =>
                have hEq : (⟨Shape.query qa', c_Y⟩ :
                    (ViewPoly F α).Obj (ITree F α)) =
                  ⟨Shape.query qa, c_cc⟩ := hs_Y.symm.trans hshc_rw
                have hqq : qa' = qa := Shape.query.inj (Sigma.mk.inj hEq).1
                subst hqq
                have hcc : c_Y = c_cc := eq_of_heq (Sigma.mk.inj hEq).2
                subst hcc
                refine ⟨X, cs PUnit.unit,
                    ha.trans ((TauSteps.one ct ht_a).trans hX), .refl _, ?_⟩
                refine Match.query qa' c_X c_Y ht_X hshc_rw ?_
                intro b
                exact Or.inl (hcc_XY b)
            | tau _ _ _ hs_Y _ =>
                rw [hs_Y] at hshc_rw; cases hshc_rw
  · refine ⟨a', s₁, ha, hs_strict, ?_⟩
    exact M.mono (fun _ _ hxy => Or.inl hxy)


-- @@ L695-700 verbatim
/-- Absorbing a sequence of τ-strips on the RHS of a weak bisimulation. -/
theorem absorb_tauSteps_right {t s s' : ITree F α}
    (h : t ≈ s) (hstrip : TauSteps s s') : t ≈ s' := by
  induction hstrip generalizing t with
  | refl _ => exact h
  | @step _ _ c ht hr ih => exact ih (step_absorb_right c h ht)


-- @@ L702-706 verbatim
/-- A τ-strip on the LHS of a weak bisimulation yields a weak bisimulation
between the stripped tree and the RHS. Dual to `absorb_tauSteps_right`. -/
theorem tauSteps_weakBisim_left {t t' s : ITree F α}
    (h : t ≈ s) (hstrip : TauSteps t t') : t' ≈ s :=
  (absorb_tauSteps_right h.symm hstrip).symm


-- @@ L708-716 verbatim
/-- "Un-stripping" on the RHS: if `t ≈ s'` and `s` reaches `s'` by
τ-stripping, then `t ≈ s`. Built directly via coinduction carrying a
residual strip obligation on the RHS. -/
theorem weakBisim_of_tauSteps_right {t s s' : ITree F α}
    (h : t ≈ s') (hstrip : TauSteps s s') : t ≈ s := by
  refine coinduct (fun x y => ∃ y', TauSteps y y' ∧ x ≈ y') ?_ ⟨s', hstrip, h⟩
  rintro a b ⟨b', hbb', hab'⟩
  obtain ⟨a', b'', ha, hb, M⟩ := hab'.dest
  exact ⟨a', b'', ha, hbb'.trans hb, M.mono (fun _ y hxy => ⟨y, .refl _, hxy⟩)⟩


-- @@ L718-722 verbatim
/-- Every τ-strip witnesses a weak bisimulation between its endpoints. -/
theorem weakBisim_of_tauSteps {t t' : ITree F α} (h : TauSteps t t') : t ≈ t' := by
  induction h with
  | refl _ => exact WeakBisim.refl _
  | step c ht _ ih => exact absorb_tauSteps_left (TauSteps.one c ht) ih


-- @@ L724-724 verbatim
end WeakBisim


-- @@ L726-734 verbatim
/-! ### `Match` advance lemmas

Advance a `Match WeakBisim` witness through a τ-strip on one of its
endpoints, producing a new `Match WeakBisim` at advanced endpoints.
These are the core tools for closing the misaligned case of
`WeakBisim.trans` — a τ-strip on the inner middle endpoint is absorbed
into the weak-bisim witness by `absorb_tauSteps_right` /
`tauSteps_weakBisim_left`, then the weak-bisim is unfolded once to
produce a new `Match` witness. -/


-- @@ L736-756 verbatim
/-- Advance a `Match WeakBisim` witness on its RIGHT endpoint through a
τ-strip. Given `Match W x z1` and `TauSteps z1 z2`, produce
`x'`, `z'` with `TauSteps x x'`, `TauSteps z2 z'`, and
`Match W x' z'`. -/
theorem Match.advance_right {x z1 z2 : ITree F α}
    (Ma : Match WeakBisim x z1) (hlin : TauSteps z1 z2) :
    ∃ x' z', TauSteps x x' ∧ TauSteps z2 z' ∧ Match WeakBisim x' z' := by
  induction hlin generalizing x with
  | refl t => exact ⟨x, t, .refl _, .refl _, Ma⟩
  | @step _ z2' c Hz1 hr _ =>
      cases Ma with
      | pure _ _ Hp => rw [Hp] at Hz1; cases Hz1
      | query _ _ _ _ Hq _ => rw [Hq] at Hz1; cases Hz1
      | tau ct cs Hx_a Hz1_s hBisim =>
          have hcc : cs = c := TauSteps.cont_eq Hz1_s Hz1
          subst hcc
          have hB2 : WeakBisim (ct PUnit.unit) z2' :=
            WeakBisim.absorb_tauSteps_right hBisim hr
          obtain ⟨X, Y, hX, hY, MXY⟩ := hB2.dest
          refine ⟨X, Y, ?_, hY, MXY⟩
          exact (TauSteps.one ct Hx_a).trans hX


-- @@ L758-778 verbatim
/-- Advance a `Match WeakBisim` witness on its LEFT endpoint through a
τ-strip. Given `Match W c1 y` and `TauSteps c1 c2`, produce
`c'`, `y'` with `TauSteps c2 c'`, `TauSteps y y'`, and
`Match W c' y'`. -/
theorem Match.advance_left {c1 c2 y : ITree F α}
    (Mb : Match WeakBisim c1 y) (hlin : TauSteps c1 c2) :
    ∃ c' y', TauSteps c2 c' ∧ TauSteps y y' ∧ Match WeakBisim c' y' := by
  induction hlin generalizing y with
  | refl t => exact ⟨t, y, .refl _, .refl _, Mb⟩
  | @step _ c2' c Hc1 hr _ =>
      cases Mb with
      | pure _ Hp _ => rw [Hp] at Hc1; cases Hc1
      | query _ _ _ Hq _ _ => rw [Hq] at Hc1; cases Hc1
      | tau ct cs Hc1_s Hy_s hBisim =>
          have hcc : c = ct := TauSteps.cont_eq Hc1 Hc1_s
          subst hcc
          have hB2 : WeakBisim c2' (cs PUnit.unit) :=
            WeakBisim.tauSteps_weakBisim_left hBisim hr
          obtain ⟨X, Y, hX, hY, MXY⟩ := hB2.dest
          refine ⟨X, Y, hX, ?_, MXY⟩
          exact (TauSteps.one cs Hy_s).trans hY


-- @@ L780-815 verbatim
/-- Aligned-case transitivity at the `Match` level. Given two `Match`
witnesses that share a common middle tree `c`, produce a `Match` witness
for the composite relation `fun x y => ∃ z, x ≈ z ∧ z ≈ y`. Direct case
analysis on both matches, using shape determinism. -/
theorem Match.trans_aligned {c a_1 b_1 : ITree F α}
    (Ma : Match WeakBisim a_1 c) (Mb : Match WeakBisim c b_1) :
    Match (fun x y : ITree F α => ∃ z, x ≈ z ∧ z ≈ y) a_1 b_1 := by
  cases Ma with
  | pure r Ha Hc =>
      cases Mb with
      | pure r' Hc' Hb =>
          have heq : (⟨.pure r, PEmpty.elim⟩ : (ViewPoly F α).Obj _) =
              ⟨.pure r', PEmpty.elim⟩ := Hc.symm.trans Hc'
          have hrr : r = r' := Shape.pure.inj (Sigma.mk.inj heq).1
          subst hrr
          exact .pure r Ha Hb
      | query _ _ _ Hc' _ _ => rw [Hc] at Hc'; cases Hc'
      | tau _ _ Hc' _ _ => rw [Hc] at Hc'; cases Hc'
  | query q ca ca' Ha Hc h =>
      cases Mb with
      | pure _ Hc' _ => rw [Hc] at Hc'; cases Hc'
      | query q' cc cb Hc' Hb h' =>
          have heq : (⟨.query q, ca'⟩ : (ViewPoly F α).Obj _) =
              ⟨.query q', cc⟩ := Hc.symm.trans Hc'
          have hqq : q = q' := Shape.query.inj (Sigma.mk.inj heq).1
          subst hqq
          have hcc : ca' = cc := eq_of_heq (Sigma.mk.inj heq).2
          exact .query q ca cb Ha Hb (fun b => ⟨ca' b, h b, hcc.symm ▸ h' b⟩)
      | tau _ _ Hc' _ _ => rw [Hc] at Hc'; cases Hc'
  | tau ct cs Ha Hc h =>
      cases Mb with
      | pure _ Hc' _ => rw [Hc] at Hc'; cases Hc'
      | query _ _ _ Hc' _ _ => rw [Hc] at Hc'; cases Hc'
      | tau cs' cb Hc' Hb h' =>
          have hss : cs' = cs := TauSteps.cont_eq Hc' Hc
          exact .tau ct cb Ha Hb ⟨cs PUnit.unit, h, hss ▸ h'⟩


-- @@ L817-817 verbatim
namespace WeakBisim


-- @@ L819-992 verbatim
/-- Transitivity of weak bisimilarity.

**Proof.** By coinduction with relation `R x y := ∃ z, x ≈ z ∧ z ≈ y`.
The closure step unfolds both weak bisims once to obtain
`Ma : Match W a' c₁` with `TauSteps c c₁` and `Mb : Match W c₂ b'` with
`TauSteps c c₂`. Linearity of τ-stripping (`TauSteps.linear`) gives
either `TauSteps c₁ c₂` or `TauSteps c₂ c₁`; WLOG we take the former.

`Match.advance_right` on `Ma` through `TauSteps c₁ c₂` produces
`Ma' : Match W a'' c'` with `TauSteps c₂ c'`. `Match.advance_left` on
`Mb` through `TauSteps c₂ c'` produces `Mb' : Match W c'' b''` with
`TauSteps c' c''`.

Case analysis on the head of `c'` via `Ma'`:
* `pure` / `query`: rigidity of `TauSteps c' c''` forces `c'' = c'`, so
  `Match.trans_aligned` glues `Ma'` and `Mb'`.
* `.tau ct cs`: case split on `TauSteps c' c''`. When refl, aligned,
  glue. Otherwise `hrest : TauSteps (cs .unit) c''`. Case on the head
  of `c''` via `Mb'`:
  * `pure r'`: `absorb_tauSteps_right h_a hrest` gives
    `(ct .unit) ≈ c''`. Unfolding pins `a''` to some pure-`r'` tree
    reachable by τ-strips, producing `Match.pure`.
  * `query q'`: symmetric to pure via a query-aligned unfold.
  * `.tau ct'' cs''`: both sides step-headed. Produce `Match.tau` at
    `(a'', b'')` with continuations `(ct .unit)` and `(cs'' .unit)`.
    The residual coinductive relation is witnessed by choosing the
    intermediate term `z := ct'' .unit`:
    - `(ct .unit) ≈ (ct'' .unit)` via
      `absorb_tauSteps_right h_a (hrest.trans (TauSteps.one ct'' Hc''))`;
    - `(ct'' .unit) ≈ (cs'' .unit)` directly from `h_b`. -/
@[trans] theorem trans {t s u : ITree F α}
    (h₁ : t ≈ s) (h₂ : s ≈ u) : t ≈ u := by
  refine coinduct (fun x y => ∃ z, x ≈ z ∧ z ≈ y) ?_ ⟨s, h₁, h₂⟩
  rintro a b ⟨c, hac, hcb⟩
  obtain ⟨a', c₁, ha, hc₁, Ma⟩ := hac.dest
  obtain ⟨c₂, b', hc₂, hb, Mb⟩ := hcb.dest
  cases TauSteps.linear hc₁ hc₂ with
  | inl hlin =>
      obtain ⟨a'', c', ha', hc', Ma'⟩ := Match.advance_right Ma hlin
      obtain ⟨c'', b'', hc'', hb'', Mb'⟩ := Match.advance_left Mb hc'
      cases Ma' with
      | pure r Ha'' Hc' =>
          have : c'' = c' := TauSteps.rigid_of_pure r Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha', hb.trans hb'',
            (Match.pure r Ha'' Hc').trans_aligned Mb'⟩
      | query q ca ca' Ha'' Hc' hq =>
          have : c'' = c' := TauSteps.rigid_of_query q ca' Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha', hb.trans hb'',
            (Match.query q ca ca' Ha'' Hc' hq).trans_aligned Mb'⟩
      | tau ct cs Ha'' Hc' h_a =>
          rcases TauSteps.step_cases cs Hc' hc'' with hc_eq | hrest
          · subst hc_eq
            exact ⟨a'', b'', ha.trans ha', hb.trans hb'',
              (Match.tau ct cs Ha'' Hc' h_a).trans_aligned Mb'⟩
          · cases Mb' with
            | pure r' Hc'' Hb'' =>
                have hRB : WeakBisim (ct PUnit.unit) c'' :=
                  absorb_tauSteps_right h_a hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hYc : Y = c'' := TauSteps.rigid_of_pure r' Hc'' hY
                subst hYc
                cases MXY with
                | pure r'' HX HY =>
                    have heq : (⟨Shape.pure r'', PEmpty.elim⟩ :
                        (ViewPoly F α).Obj (ITree F α)) =
                        ⟨Shape.pure r', PEmpty.elim⟩ := HY.symm.trans Hc''
                    have hrr : r' = r'' := (Shape.pure.inj (Sigma.mk.inj heq).1).symm
                    refine ⟨X, b'',
                      ha.trans (ha'.trans ((TauSteps.one ct Ha'').trans hX)),
                      hb.trans hb'', ?_⟩
                    exact Match.pure r'' HX (hrr ▸ Hb'')
                | query _ _ _ _ HY _ => rw [HY] at Hc''; cases Hc''
                | tau _ _ _ HY _ => rw [HY] at Hc''; cases Hc''
            | query q_outer cq_outer cq'_outer Hc'' Hb'' hq =>
                have hRB : WeakBisim (ct PUnit.unit) c'' :=
                  absorb_tauSteps_right h_a hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hYc : Y = c'' := TauSteps.rigid_of_query q_outer cq_outer Hc'' hY
                subst hYc
                cases MXY with
                | pure _ _ HY => rw [HY] at Hc''; cases Hc''
                | query q'' cq_a cq_b HX HY h_q =>
                    have heq : (⟨Shape.query q'', cq_b⟩ :
                        (ViewPoly F α).Obj (ITree F α)) =
                        ⟨Shape.query q_outer, cq_outer⟩ := HY.symm.trans Hc''
                    have hqq : q'' = q_outer :=
                      Shape.query.inj (Sigma.mk.inj heq).1
                    subst hqq
                    have hcc : cq_b = cq_outer := eq_of_heq (Sigma.mk.inj heq).2
                    subst hcc
                    refine ⟨X, b'',
                      ha.trans (ha'.trans ((TauSteps.one ct Ha'').trans hX)),
                      hb.trans hb'', ?_⟩
                    refine Match.query q'' cq_a cq'_outer HX Hb'' ?_
                    intro b
                    exact ⟨cq_b b, h_q b, hq b⟩
                | tau _ _ _ HY _ => rw [HY] at Hc''; cases Hc''
            | tau ct'' cs'' Hc'' Hb'' h_b =>
                refine ⟨a'', b'', ha.trans ha', hb.trans hb'', ?_⟩
                refine Match.tau ct cs'' Ha'' Hb'' ?_
                refine ⟨ct'' PUnit.unit, ?_, h_b⟩
                have hTau : TauSteps (cs PUnit.unit) (ct'' PUnit.unit) :=
                  hrest.trans (TauSteps.one ct'' Hc'')
                exact absorb_tauSteps_right h_a hTau
  | inr hlin =>
      obtain ⟨c', b'', hc', hb', Mb'⟩ := Match.advance_left Mb hlin
      obtain ⟨a'', c'', ha'', hc'', Ma'⟩ := Match.advance_right Ma hc'
      cases Mb' with
      | pure r Hc' Hb'' =>
          have : c'' = c' := TauSteps.rigid_of_pure r Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha'', hb.trans hb',
            Ma'.trans_aligned (Match.pure r Hc' Hb'')⟩
      | query q ca ca' Hc' Hb'' hq =>
          have : c'' = c' := TauSteps.rigid_of_query q ca Hc' hc''
          subst this
          exact ⟨a'', b'', ha.trans ha'', hb.trans hb',
            Ma'.trans_aligned (Match.query q ca ca' Hc' Hb'' hq)⟩
      | tau ct cs Hc' Hb'' h_b =>
          rcases TauSteps.step_cases ct Hc' hc'' with hc_eq | hrest
          · subst hc_eq
            exact ⟨a'', b'', ha.trans ha'', hb.trans hb',
              Ma'.trans_aligned (Match.tau ct cs Hc' Hb'' h_b)⟩
          · cases Ma' with
            | pure r' Ha'' Hc'' =>
                have hRB : WeakBisim c'' (cs PUnit.unit) :=
                  tauSteps_weakBisim_left h_b hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hXc : X = c'' := TauSteps.rigid_of_pure r' Hc'' hX
                subst hXc
                cases MXY with
                | pure r'' HX HY =>
                    have heq : (⟨Shape.pure r'', PEmpty.elim⟩ :
                        (ViewPoly F α).Obj (ITree F α)) =
                        ⟨Shape.pure r', PEmpty.elim⟩ := HX.symm.trans Hc''
                    have hrr : r' = r'' := (Shape.pure.inj (Sigma.mk.inj heq).1).symm
                    refine ⟨a'', Y, ha.trans ha'',
                      hb.trans (hb'.trans ((TauSteps.one cs Hb'').trans hY)),
                      ?_⟩
                    exact Match.pure r'' (hrr ▸ Ha'') HY
                | query _ _ _ HX _ _ => rw [HX] at Hc''; cases Hc''
                | tau _ _ HX _ _ => rw [HX] at Hc''; cases Hc''
            | query q_a cq_outer cq'_outer Ha'' Hc'' hq =>
                have hRB : WeakBisim c'' (cs PUnit.unit) :=
                  tauSteps_weakBisim_left h_b hrest
                obtain ⟨X, Y, hX, hY, MXY⟩ := hRB.dest
                have hXc : X = c'' := TauSteps.rigid_of_query q_a cq'_outer Hc'' hX
                subst hXc
                cases MXY with
                | pure _ HX _ => rw [HX] at Hc''; cases Hc''
                | query q'' cq_a cq_b HX HY h_q =>
                    have heq : (⟨Shape.query q'', cq_a⟩ :
                        (ViewPoly F α).Obj (ITree F α)) =
                        ⟨Shape.query q_a, cq'_outer⟩ := HX.symm.trans Hc''
                    have hqq : q'' = q_a := Shape.query.inj (Sigma.mk.inj heq).1
                    subst hqq
                    have hcc : cq_a = cq'_outer := eq_of_heq (Sigma.mk.inj heq).2
                    subst hcc
                    refine ⟨a'', Y, ha.trans ha'',
                      hb.trans (hb'.trans ((TauSteps.one cs Hb'').trans hY)),
                      ?_⟩
                    refine Match.query q'' cq_outer cq_b Ha'' HY ?_
                    intro b
                    exact ⟨cq_a b, hq b, h_q b⟩
                | tau _ _ HX _ _ => rw [HX] at Hc''; cases Hc''
            | tau ct'' cs'' Ha'' Hc'' h_a =>
                refine ⟨a'', b'', ha.trans ha'', hb.trans hb', ?_⟩
                refine Match.tau ct'' cs Ha'' Hb'' ?_
                refine ⟨cs'' PUnit.unit, h_a, ?_⟩
                have hTau : TauSteps (ct PUnit.unit) (cs'' PUnit.unit) :=
                  hrest.trans (TauSteps.one cs'' Hc'')
                exact tauSteps_weakBisim_left h_b hTau


-- @@ L994-995 verbatim
theorem equivalence : Equivalence (WeakBisim (F := F) (α := α)) :=
  ⟨WeakBisim.refl, fun {_ _} => WeakBisim.symm, fun {_ _ _} => WeakBisim.trans⟩


-- @@ L997-997 verbatim
end WeakBisim


-- @@ L999-999 verbatim
/-! ### Setoid instance generated by `WeakBisim` -/


-- @@ L1001-1003 verbatim
instance instSetoid : Setoid (ITree F α) where
  r := WeakBisim
  iseqv := WeakBisim.equivalence


-- @@ L1005-1005 verbatim
/-! ### `Bisim` implies `WeakBisim` -/


-- @@ L1007-1008 verbatim
theorem Bisim.toWeakBisim {t s : ITree F α} (h : t ≅ s) : WeakBisim t s := by
  cases h; exact WeakBisim.refl _


-- @@ L1010-1010 verbatim
end ITree
