/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# General (continuous-covariate) overlap-weighted ATE

Abstract-conditioning version of the saturated-control OLS identity for an
*arbitrary*
covariate σ-algebra `m` (think: `m` generated by a covariate `X`). This uses
Mathlib's σ-algebra conditional expectation `μ[f | m]` rather than the
finite-event `normalizedRestrictedIntegral` used elsewhere in this repo, so it covers the
continuous-`X` case directly.

## Setup

`D : Ω → ℝ` is binary treatment (`D = 0 ∨ D = 1` a.e.), `Y0 Y1` are the
square-integrable potential outcomes, `Y` the observed outcome. Write
`p := μ[D | m]` (propensity score) and `D̃ := D − p` (the saturated residual
of `D` on the controls). The saturated-control OLS estimand is the
Frisch–Waugh–Lovell ratio

    β_sat = E[D̃·Y] / E[D̃²].

The algebraic lemma `saturated_ols_overlap_ratio_identity` proves the
totalized ratio identity

    β_sat = E[p(1−p)·(μ[Y1 | m] − μ[Y0 | m])] / E[p(1−p)].

The theorem `saturated_ols_overlap_weighted_ate` adds strictly
positive integrated overlap, so the right-hand ratio is genuinely a normalized
overlap-weighted average.

## Conditional-mean-independence faithfulness note

The hypotheses `hCMI1`, `hCMI0` are stated in the **mean-independence
factoring form**

    μ[D·Y1 | m] =ᵐ μ[D | m]·μ[Y1 | m],   μ[(1−D)·Y0 | m] =ᵐ μ[1−D | m]·μ[Y0 | m].

This is a *consequence* of full conditional mean independence
`E[Y(d) | D, X] = E[Y(d) | X]` (derive it by the tower property: condition
on the joint σ-algebra `m ⊔ comap D`, factor out the `m ⊔ comap D`-measurable
`D` / `1−D`, then apply CMI to replace `μ[Y(d)|m ⊔ comap D]` by `μ[Y(d)|m]`).
Taking the factored form as a hypothesis therefore uses only the weaker
property needed for this identity.
-/

module

public import Causalean.Mathlib.Probability.FiniteCellConditionalMomentBridge
public import Causalean.Tactic.CondexpLinearity
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
public import Mathlib.MeasureTheory.Function.ConditionalExpectation.PullOut


-- @@ L56-66 verbatim
/-! # General Conditional-Expectation OLS Identity

This file proves the continuous-covariate saturated ordinary least squares
ratio identity using conditional expectation with respect to an arbitrary
covariate σ-algebra. The helper lemmas `denom_identity` and `numer_identity`
identify the Frisch-Waugh-Lovell denominator and numerator after residualizing
treatment on `m`. The headline theorem `saturated_ols_overlap_weighted_ate`
then shows that, under binary treatment, consistency, integrability, factored
conditional-mean-independence, and strictly positive integrated overlap, the
residualized treatment ratio equals the corresponding overlap-weighted
conditional-treatment-effect ratio. -/


-- @@ L68-68 verbatim
public section


-- @@ L70-70 verbatim
open Causalean.Mathlib.Probability


-- @@ L72-72 verbatim
namespace Causalean.Panel.EstimandCharacterization.OLSWeightDecomposition


-- @@ L74-74 verbatim
open MeasureTheory ProbabilityTheory


-- @@ L76-76 verbatim
section General


-- @@ L78-78 verbatim
variable {Ω : Type*} {m mΩ : MeasurableSpace Ω} (μ : Measure Ω) [IsFiniteMeasure μ]


-- @@ L80-84 verbatim
/-- The conditional expectation of one minus an integrable real-valued variable, given a
sub-σ-algebra, equals one minus that variable's conditional expectation almost surely. -/
lemma condExp_one_sub (hm : m ≤ mΩ) {D : Ω → ℝ} (hD_int : Integrable D μ) :
    μ[(fun ω => 1 - D ω) | m] =ᵐ[μ] fun ω => 1 - (μ[D | m]) ω := by
  condexp_linearity


-- @@ L86-99 verbatim
/-- A real-valued variable that is zero or one almost surely has conditional expectation,
given a sub-σ-algebra, between zero and one almost surely. -/
lemma condExp_D_bounds (hm : m ≤ mΩ) {D : Ω → ℝ} (hD_int : Integrable D μ)
    (hDbin : ∀ᵐ ω ∂μ, D ω = 0 ∨ D ω = 1) :
    (∀ᵐ ω ∂μ, 0 ≤ (μ[D | m]) ω) ∧ (∀ᵐ ω ∂μ, (μ[D | m]) ω ≤ 1) := by
  have h0 : (0 : Ω → ℝ) ≤ᵐ[μ] D := by
    filter_upwards [hDbin] with ω hω; rcases hω with h | h <;> simp [h]
  have h1 : D ≤ᵐ[μ] fun _ => (1 : ℝ) := by
    filter_upwards [hDbin] with ω hω; rcases hω with h | h <;> simp [h]
  refine ⟨condExp_nonneg h0, ?_⟩
  have hmono := condExp_mono (m := m) hD_int (integrable_const (1 : ℝ)) h1
  have hc : μ[(fun _ : Ω => (1 : ℝ)) | m] = fun _ => (1 : ℝ) := condExp_const hm (1 : ℝ)
  filter_upwards [hmono] with ω hω
  rwa [hc] at hω


-- @@ L101-108 verbatim
/-- The conditional expectation of a real-valued variable that is zero or one almost surely
has absolute value at most one almost surely. -/
lemma condExp_D_norm_le (hm : m ≤ mΩ) {D : Ω → ℝ} (hD_int : Integrable D μ)
    (hDbin : ∀ᵐ ω ∂μ, D ω = 0 ∨ D ω = 1) :
    ∀ᵐ ω ∂μ, ‖(μ[D | m]) ω‖ ≤ 1 := by
  obtain ⟨hlo, hhi⟩ := condExp_D_bounds μ hm hD_int hDbin
  filter_upwards [hlo, hhi] with ω h0 h1
  rw [Real.norm_eq_abs, abs_le]; exact ⟨by linarith, h1⟩


-- @@ L110-165 verbatim
/-- **Denominator identity (A).** For binary `D`,
`∫ (D − μ[D | m])² ∂μ = ∫ μ[D | m]·(1 − μ[D | m]) ∂μ`.

Proof sketch: conditioning the expansion `(D − p)² = D − 2·p·D + p²`
(using `D² =ᵐ D`) on `m` and pulling out the `m`-measurable factors gives
`μ[(D−p)² | m] =ᵐ p − 2p² + p² = p(1−p)`; integrate via `integral_condExp`. -/
lemma denom_identity (hm : m ≤ mΩ)
    (D : Ω → ℝ) (hDbin : ∀ᵐ ω ∂μ, D ω = 0 ∨ D ω = 1)
    (hD_int : Integrable D μ) :
    (∫ ω, (D ω - (μ[D | m]) ω) ^ 2 ∂μ)
      = ∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) ∂μ := by
  haveI : IsFiniteMeasure (μ.trim hm) := isFiniteMeasure_trim hm
  set p : Ω → ℝ := μ[D | m] with hp
  have hp_sm : StronglyMeasurable[m] p := stronglyMeasurable_condExp
  have hp_int : Integrable p μ := integrable_condExp
  have hp_bound : ∀ᵐ ω ∂μ, ‖p ω‖ ≤ 1 := condExp_D_norm_le μ hm hD_int hDbin
  have hp_aesm : AEStronglyMeasurable p μ := (hp_sm.mono hm).aestronglyMeasurable
  -- Integrabilities of the products (`p` is a.e. bounded by 1).
  have hpD_int : Integrable (fun ω => p ω * D ω) μ :=
    hD_int.bdd_mul hp_aesm hp_bound
  have hp2_int : Integrable (fun ω => p ω * p ω) μ := hp_int.bdd_mul hp_aesm hp_bound
  -- Expand `(D-p)² =ᵐ D - 2*(p*D) + p*p`  (using `D² =ᵐ D`).
  have hexp : (fun ω => (D ω - p ω) ^ 2)
      =ᵐ[μ] fun ω => D ω - 2 * (p ω * D ω) + p ω * p ω := by
    filter_upwards [hDbin] with ω hω
    rcases hω with h | h <;> rw [h] <;> ring
  -- `∫ p*D = ∫ p*p`, via pull-out of the m-measurable `p` and `integral_condExp`.
  have hpullout : μ[(fun ω => p ω * D ω) | m] =ᵐ[μ] fun ω => p ω * (μ[D | m]) ω :=
    condExp_mul_of_stronglyMeasurable_left hp_sm hpD_int hD_int
  have hpD_eq_pp : (∫ ω, p ω * D ω ∂μ) = ∫ ω, p ω * p ω ∂μ := by
    rw [← integral_condExp hm (f := fun ω => p ω * D ω)]
    refine integral_congr_ae ?_
    filter_upwards [hpullout] with ω hω; rw [hω]
  -- `∫ D = ∫ p`.
  have hD_eq_p : (∫ ω, D ω ∂μ) = ∫ ω, p ω ∂μ := by
    rw [hp]; exact (integral_condExp hm).symm
  -- Integral of the expansion via linearity (`∫ (f + g) = ∫ f + ∫ g` etc.).
  have h2pD_int : Integrable (fun ω => 2 * (p ω * D ω)) μ := hpD_int.const_mul 2
  have hint_exp : (∫ ω, (D ω - 2 * (p ω * D ω) + p ω * p ω) ∂μ)
      = (∫ ω, D ω ∂μ) - 2 * (∫ ω, p ω * D ω ∂μ) + ∫ ω, p ω * p ω ∂μ := by
    rw [integral_add (μ := μ) (f := fun ω => D ω - 2 * (p ω * D ω)) (g := fun ω => p ω * p ω)
        (hD_int.sub h2pD_int) hp2_int,
      integral_sub (μ := μ) (f := D) (g := fun ω => 2 * (p ω * D ω)) hD_int h2pD_int,
      integral_const_mul]
  -- Compute both sides via integral linearity.
  calc
    (∫ ω, (D ω - p ω) ^ 2 ∂μ)
        = ∫ ω, (D ω - 2 * (p ω * D ω) + p ω * p ω) ∂μ := integral_congr_ae hexp
    _ = (∫ ω, D ω ∂μ) - 2 * (∫ ω, p ω * D ω ∂μ) + ∫ ω, p ω * p ω ∂μ := hint_exp
    _ = (∫ ω, p ω ∂μ) - 2 * (∫ ω, p ω * p ω ∂μ) + ∫ ω, p ω * p ω ∂μ := by
        rw [hD_eq_p, hpD_eq_pp]
    _ = (∫ ω, p ω ∂μ) - ∫ ω, p ω * p ω ∂μ := by ring
    _ = ∫ ω, p ω * (1 - p ω) ∂μ := by
        rw [← integral_sub hp_int hp2_int]
        refine integral_congr_ae ?_
        filter_upwards [] with ω; ring


-- @@ L167-263 verbatim
/-- **Numerator identity (B).** Under consistency and the factored
conditional-mean-independence hypotheses,
`∫ (D − μ[D | m])·Y ∂μ = ∫ μ[D | m]·(1 − μ[D | m])·(μ[Y1 | m] − μ[Y0 | m]) ∂μ`.

Proof sketch: by consistency and binary `D`,
`(D − p)·Y =ᵐ (1−p)·(D·Y1) − p·((1−D)·Y0)`. Pulling the `m`-measurable
`1−p` and `p` out of the conditional expectation and applying the CMI
factoring `μ[D·Y1 | m] =ᵐ p·μ[Y1 | m]`, `μ[(1−D)·Y0 | m] =ᵐ (1−p)·μ[Y0 | m]`
gives the integrand `p·(1−p)·(μ[Y1 | m] − μ[Y0 | m])`. -/
lemma numer_identity (hm : m ≤ mΩ)
    (D Y Y0 Y1 : Ω → ℝ) (hDbin : ∀ᵐ ω ∂μ, D ω = 0 ∨ D ω = 1)
    (hD_int : Integrable D μ)
    (hDY1_int : Integrable (fun ω => D ω * Y1 ω) μ)
    (h1DY0_int : Integrable (fun ω => (1 - D ω) * Y0 ω) μ)
    (hcons : Y =ᵐ[μ] fun ω => D ω * Y1 ω + (1 - D ω) * Y0 ω)
    (hCMI1 : μ[(fun ω => D ω * Y1 ω) | m] =ᵐ[μ] fun ω => (μ[D | m]) ω * (μ[Y1 | m]) ω)
    (hCMI0 : μ[(fun ω => (1 - D ω) * Y0 ω) | m]
        =ᵐ[μ] fun ω => (μ[(fun ω => 1 - D ω) | m]) ω * (μ[Y0 | m]) ω) :
    (∫ ω, (D ω - (μ[D | m]) ω) * Y ω ∂μ)
      = ∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) * ((μ[Y1 | m]) ω - (μ[Y0 | m]) ω) ∂μ := by
  haveI : IsFiniteMeasure (μ.trim hm) := isFiniteMeasure_trim hm
  set p : Ω → ℝ := μ[D | m] with hp
  set M1 : Ω → ℝ := μ[Y1 | m] with hM1
  set M0 : Ω → ℝ := μ[Y0 | m] with hM0
  have hp_sm : StronglyMeasurable[m] p := stronglyMeasurable_condExp
  have hp_bound : ∀ᵐ ω ∂μ, ‖p ω‖ ≤ 1 := condExp_D_norm_le μ hm hD_int hDbin
  have hp_aesm : AEStronglyMeasurable p μ := (hp_sm.mono hm).aestronglyMeasurable
  -- `1 - p` is `m`-strongly measurable and a.e. bounded by `2`.
  have h1p_sm : StronglyMeasurable[m] (fun ω => 1 - p ω) :=
    stronglyMeasurable_const.sub hp_sm
  have h1p_aesm : AEStronglyMeasurable (fun ω => 1 - p ω) μ :=
    (h1p_sm.mono hm).aestronglyMeasurable
  have h1p_bound : ∀ᵐ ω ∂μ, ‖1 - p ω‖ ≤ 2 := by
    filter_upwards [hp_bound] with ω hω
    calc ‖1 - p ω‖ ≤ ‖(1 : ℝ)‖ + ‖p ω‖ := norm_sub_le _ _
      _ ≤ 1 + 1 := by rw [norm_one]; linarith [hω]
      _ = 2 := by norm_num
  -- Integrabilities.
  have ha_int : Integrable (fun ω => (1 - p ω) * (D ω * Y1 ω)) μ :=
    hDY1_int.bdd_mul h1p_aesm h1p_bound
  have hb_int : Integrable (fun ω => p ω * ((1 - D ω) * Y0 ω)) μ :=
    h1DY0_int.bdd_mul hp_aesm hp_bound
  -- Consistency + binary `D`: `(D-p)·Y =ᵐ (1-p)·(D·Y1) - p·((1-D)·Y0)`.
  have hsplit : (fun ω => (D ω - p ω) * Y ω)
      =ᵐ[μ] fun ω => (1 - p ω) * (D ω * Y1 ω) - p ω * ((1 - D ω) * Y0 ω) := by
    filter_upwards [hcons, hDbin] with ω hY hD
    rw [hY]; rcases hD with h | h <;> rw [h] <;> ring
  -- `μ[1-D | m] =ᵐ 1 - p`.
  have h1D : μ[(fun ω => 1 - D ω) | m] =ᵐ[μ] fun ω => 1 - p ω := condExp_one_sub μ hm hD_int
  -- Term A: `∫ (1-p)(D·Y1) = ∫ (1-p)·p·M1`.
  have hpullA : μ[(fun ω => (1 - p ω) * (D ω * Y1 ω)) | m]
      =ᵐ[μ] fun ω => (1 - p ω) * (μ[(fun ω => D ω * Y1 ω) | m]) ω :=
    condExp_mul_of_stronglyMeasurable_left h1p_sm ha_int hDY1_int
  have hA : (∫ ω, (1 - p ω) * (D ω * Y1 ω) ∂μ) = ∫ ω, (1 - p ω) * (p ω * M1 ω) ∂μ := by
    rw [← integral_condExp hm (f := fun ω => (1 - p ω) * (D ω * Y1 ω))]
    refine integral_congr_ae ?_
    filter_upwards [hpullA, hCMI1] with ω h1 h2; rw [h1, h2]
  -- Term B: `∫ p((1-D)Y0) = ∫ p·(1-p)·M0`.
  have hpullB : μ[(fun ω => p ω * ((1 - D ω) * Y0 ω)) | m]
      =ᵐ[μ] fun ω => p ω * (μ[(fun ω => (1 - D ω) * Y0 ω) | m]) ω :=
    condExp_mul_of_stronglyMeasurable_left hp_sm hb_int h1DY0_int
  have hB : (∫ ω, p ω * ((1 - D ω) * Y0 ω) ∂μ) = ∫ ω, p ω * ((1 - p ω) * M0 ω) ∂μ := by
    rw [← integral_condExp hm (f := fun ω => p ω * ((1 - D ω) * Y0 ω))]
    refine integral_congr_ae ?_
    filter_upwards [hpullB, hCMI0, h1D] with ω h1 h2 h3
    rw [h1, h2, h3]
  -- Assemble.
  calc
    (∫ ω, (D ω - p ω) * Y ω ∂μ)
        = ∫ ω, ((1 - p ω) * (D ω * Y1 ω) - p ω * ((1 - D ω) * Y0 ω)) ∂μ :=
          integral_congr_ae hsplit
    _ = (∫ ω, (1 - p ω) * (D ω * Y1 ω) ∂μ) - ∫ ω, p ω * ((1 - D ω) * Y0 ω) ∂μ := by
        simp only [integral_sub ha_int hb_int]
    _ = (∫ ω, (1 - p ω) * (p ω * M1 ω) ∂μ) - ∫ ω, p ω * ((1 - p ω) * M0 ω) ∂μ := by
        rw [hA, hB]
    _ = ∫ ω, p ω * (1 - p ω) * (M1 ω - M0 ω) ∂μ := by
        -- `1-p` bounded by 2, `p` bounded by 1, so the coefficients are bounded by 2.
        have hM1_int : Integrable M1 μ := integrable_condExp
        have hM0_int : Integrable M0 μ := integrable_condExp
        have hcoeff_bound : ∀ᵐ ω ∂μ, ‖(1 - p ω) * p ω‖ ≤ 2 := by
          filter_upwards [hp_bound, h1p_bound] with ω hp1 h1p
          calc ‖(1 - p ω) * p ω‖ = ‖1 - p ω‖ * ‖p ω‖ := by rw [norm_mul]
            _ ≤ 2 * 1 := mul_le_mul h1p hp1 (norm_nonneg _) (by norm_num)
            _ = 2 := by norm_num
        have hA_int : Integrable (fun ω => (1 - p ω) * (p ω * M1 ω)) μ := by
          have : (fun ω => (1 - p ω) * (p ω * M1 ω))
              = (fun ω => ((1 - p ω) * p ω) * M1 ω) := by funext ω; ring
          rw [this]
          exact hM1_int.bdd_mul ((h1p_aesm.mul hp_aesm)) hcoeff_bound
        have hB_int : Integrable (fun ω => p ω * ((1 - p ω) * M0 ω)) μ := by
          have : (fun ω => p ω * ((1 - p ω) * M0 ω))
              = (fun ω => ((1 - p ω) * p ω) * M0 ω) := by funext ω; ring
          rw [this]
          exact hM0_int.bdd_mul ((h1p_aesm.mul hp_aesm)) hcoeff_bound
        rw [← integral_sub hA_int hB_int]
        refine integral_congr_ae ?_
        filter_upwards [] with ω; ring


-- @@ L265-287 verbatim
/-- If [the conditioning σ-algebra is below the ambient one](hyp:hm), [treatment is binary
almost everywhere](hyp:hDbin), [the required treatment and potential-outcome products are
integrable](hyp:hD_int,hDY1_int,h1DY0_int), [consistency holds](hyp:hcons), and [the two
factored conditional-mean identities hold](hyp:hCMI1,hCMI0), then [the two totalized
saturated-control OLS overlap ratios are equal, including when their common denominator is
zero](goal). -/
theorem saturated_ols_overlap_ratio_identity (hm : m ≤ mΩ)
    (D Y Y0 Y1 : Ω → ℝ) (hDbin : ∀ᵐ ω ∂μ, D ω = 0 ∨ D ω = 1)
    (hD_int : Integrable D μ)
    (hDY1_int : Integrable (fun ω => D ω * Y1 ω) μ)
    (h1DY0_int : Integrable (fun ω => (1 - D ω) * Y0 ω) μ)
    (hcons : Y =ᵐ[μ] fun ω => D ω * Y1 ω + (1 - D ω) * Y0 ω)
    (hCMI1 : μ[(fun ω => D ω * Y1 ω) | m] =ᵐ[μ]
      fun ω => (μ[D | m]) ω * (μ[Y1 | m]) ω)
    (hCMI0 : μ[(fun ω => (1 - D ω) * Y0 ω) | m] =ᵐ[μ]
      fun ω => (μ[(fun ω => 1 - D ω) | m]) ω * (μ[Y0 | m]) ω) :
    (∫ ω, (D ω - (μ[D | m]) ω) * Y ω ∂μ) /
        (∫ ω, (D ω - (μ[D | m]) ω) ^ 2 ∂μ)
      = (∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) *
          ((μ[Y1 | m]) ω - (μ[Y0 | m]) ω) ∂μ) /
        (∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) ∂μ) := by
  rw [denom_identity μ hm D hDbin hD_int,
    numer_identity μ hm D Y Y0 Y1 hDbin hD_int hDY1_int h1DY0_int hcons hCMI1 hCMI0]


-- @@ L289-319 verbatim
/-- **Saturated-control OLS overlap-weighted ATE identity.** Fix [a covariate
σ-algebra `m` at most as fine as the ambient one](hyp:hm), and outcome,
treatment, and potential-outcome functions `D`, `Y`, `Y0`, `Y1`. Suppose
[treatment is binary almost everywhere](hyp:hDbin), [`D` is
integrable](hyp:hD_int), [`D·Y1` is integrable](hyp:hDY1_int), and [`(1−D)·Y0`
is integrable](hyp:h1DY0_int). Suppose also [consistency: the observed outcome
equals `D·Y1 + (1−D)·Y0` almost everywhere](hyp:hcons), and the factored
conditional-mean-independence conditions [`μ[D·Y1 ∣ m]` equals
`μ[D∣m]·μ[Y1∣m]` almost everywhere](hyp:hCMI1) and [`μ[(1−D)·Y0 ∣ m]` equals
`μ[1−D∣m]·μ[Y0∣m]` almost everywhere](hyp:hCMI0). Then [the saturated-control
OLS residualized treatment-outcome ratio `E[(D−μ[D∣m])·Y] / E[(D−μ[D∣m])²]`
equals the overlap-weighted average of conditional treatment effects
`E[μ[D∣m]·(1−μ[D∣m])·(μ[Y1∣m]−μ[Y0∣m])] / E[μ[D∣m]·(1−μ[D∣m])]`, using Lean's
totalized division convention](goal), provided [integrated overlap is strictly
positive](hyp:hOverlapPos). This proves an overlap-weighted conditional-effect
identity, not a treated-versus-untreated ATT/ATU representation. -/
theorem saturated_ols_overlap_weighted_ate (hm : m ≤ mΩ)
    (D Y Y0 Y1 : Ω → ℝ) (hDbin : ∀ᵐ ω ∂μ, D ω = 0 ∨ D ω = 1)
    (hD_int : Integrable D μ)
    (hDY1_int : Integrable (fun ω => D ω * Y1 ω) μ)
    (h1DY0_int : Integrable (fun ω => (1 - D ω) * Y0 ω) μ)
    (hcons : Y =ᵐ[μ] fun ω => D ω * Y1 ω + (1 - D ω) * Y0 ω)
    (hCMI1 : μ[(fun ω => D ω * Y1 ω) | m] =ᵐ[μ] fun ω => (μ[D | m]) ω * (μ[Y1 | m]) ω)
    (hCMI0 : μ[(fun ω => (1 - D ω) * Y0 ω) | m]
        =ᵐ[μ] fun ω => (μ[(fun ω => 1 - D ω) | m]) ω * (μ[Y0 | m]) ω)
    (hOverlapPos : 0 < ∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) ∂μ) :
    (∫ ω, (D ω - (μ[D | m]) ω) * Y ω ∂μ) / (∫ ω, (D ω - (μ[D | m]) ω) ^ 2 ∂μ)
      = (∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) * ((μ[Y1 | m]) ω - (μ[Y0 | m]) ω) ∂μ)
        / (∫ ω, (μ[D | m]) ω * (1 - (μ[D | m]) ω) ∂μ) := by
  exact saturated_ols_overlap_ratio_identity μ hm D Y Y0 Y1 hDbin hD_int
    hDY1_int h1DY0_int hcons hCMI1 hCMI0


-- @@ L321-321 verbatim
end General


-- @@ L323-323 verbatim
end Causalean.Panel.EstimandCharacterization.OLSWeightDecomposition
