/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Backdoor ATE identification in the Potential Outcome Framework

Implements the standard backdoor adjustment identity for the average treatment
effect (ATE) under the PO framework, with continuous covariate `X`, binary
treatment `D`, and real outcome `Y`.

Core identification (σ-algebra level):
    μ[Y(d) | σ(X)]  =ᵐ  μ[Y · 1_{D=d} | σ(X)] / P[D=d | σ(X)].

Integrated corollary:
    ATE = E[μ[Y(1)|σ(X)] − μ[Y(0)|σ(X)]].
-/

module
public import Causalean.PO.Assumptions.ConsistencyLemmas
public import Causalean.PO.Assumptions.IndepCF
public import Causalean.PO.Conditioning.CondExpTooling
public import Causalean.Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Integral.Bochner.Basic
public import Mathlib.Probability.ConditionalExpectation
public import Mathlib.Probability.Independence.Conditional
public import Mathlib.MeasureTheory.Function.FactorsThrough
public import Causalean.Mathlib.MeasureTheory.CondExpIndicatorTower
public import Causalean.Tactic.Attr
public import Causalean.Tactic.CondexpLinearity


-- @@ L32-48 verbatim
/-! # Backdoor Average Treatment Effect

This file proves backdoor identification for the average treatment effect in
the potential-outcome framework. It connects conditional independence,
consistency, and overlap assumptions to the standard adjustment formula for
binary treatment and real-valued outcomes.

The adjustment covariate has an arbitrary measurable value space, so the same
setup covers discrete, continuous, and vector-valued covariates. The proof uses
conditional expectations with respect to the sigma-algebra generated by the
covariate.

The main public results are `conditionalMeanOutcome_backdoor_of_propScore_ne`,
which isolates the per-arm assumptions, `conditionalMeanOutcome_backdoor`,
which discharges nonvanishing from two-sided overlap, `ate_backdoor`, and
`regression_adjustment`, which shows the adjusted conditional functional is
the observable regression `E[Y | D=d, X]`. -/


-- @@ L50-50 verbatim
@[expose] public section


-- @@ L52-52 verbatim
open Causalean.Mathlib.Probability.Independence.Conditional


-- @@ L54-54 verbatim
namespace Causalean

-- @@ L55-55 verbatim
namespace PO


-- @@ L57-57 verbatim
open MeasureTheory ProbabilityTheory


-- @@ L59-73 verbatim
/-- A backdoor system consists of [a binary treatment variable](hyp:D,hDbool), [a real-valued
outcome variable](hyp:Y,hYreal), and [an adjustment covariate](hyp:Xvar) with an arbitrary
measurable value space, where [the three variables are pairwise distinct](hyp:hDY,hDX,hYX).

The covariate may be discrete, continuous, or vector-valued through its arbitrary
measurable value space. -/
structure POBackdoorSystem (P : POSystem) (γ : Type*) [MeasurableSpace γ] where
  D : P.V
  Y : P.V
  Xvar : POVar P γ
  hDbool : P.X D ≃ᵐ Bool
  hYreal : P.X Y ≃ᵐ ℝ
  hDY : D ≠ Y
  hDX : D ≠ Xvar.v
  hYX : Y ≠ Xvar.v


-- @@ L75-75 verbatim
namespace POBackdoorSystem


-- @@ L77-77 verbatim
variable {P : POSystem} {γ : Type*} [MeasurableSpace γ]

-- @@ L78-78 verbatim
variable (S : POBackdoorSystem P γ)


-- @@ L80-82 verbatim
/-- The [treatment variable used in backdoor adjustment](goal) represents the treatment in
[a binary-treatment system](hyp:S) [on the two possible arms](step:1). -/
def dVar : POVar P Bool := ⟨S.D, S.hDbool⟩

-- @@ L83-85 verbatim
/-- The [outcome variable used in backdoor adjustment](goal) represents the outcome in
[a binary-treatment system](hyp:S) [on the real line](step:1). -/
def yVar : POVar P ℝ := ⟨S.Y, S.hYreal⟩

-- @@ L86-88 verbatim
/-- The [covariate variable used for adjustment](goal) is [the covariate specified by the
backdoor system](hyp:S) [with its original measurable value space](step:1). -/
def xVar : POVar P γ := S.Xvar


-- @@ L90-93 verbatim
/-- The [arm-specific potential outcome](goal) in [a backdoor system](hyp:S) [records each
unit's outcome if treatment were set to the selected arm](step:1), [rather than merely
conditioning on units observed in that arm](hyp:d). -/
noncomputable def YofD (d : Bool) : P.Ω → ℝ := S.yVar.cfUnder S.dVar d

-- @@ L94-96 verbatim
/-- The [factual treatment](goal) in [a backdoor system](hyp:S) [records each unit's realized
treatment arm](step:1). -/
noncomputable def factualD : P.Ω → Bool := S.dVar.factual

-- @@ L97-99 verbatim
/-- The [factual outcome](goal) in [a backdoor system](hyp:S) [records each unit's observed
real-valued response](step:1). -/
noncomputable def factualY : P.Ω → ℝ := S.yVar.factual

-- @@ L100-102 verbatim
/-- The [factual covariate](goal) in [a backdoor system](hyp:S) [records the observed
adjustment value for each unit](step:1). -/
noncomputable def factualX : P.Ω → γ := S.xVar.factual


-- @@ L104-108 verbatim
/-- In [a backdoor system](hyp:S), [the potential outcome under a fixed arm](hyp:d) is
[measurable, so its conditional mean and population mean are well-defined](goal). -/
@[fun_prop]
lemma measurable_YofD (d : Bool) : Measurable (S.YofD d) :=
  S.yVar.measurable_cfUnder S.dVar d

-- @@ L109-112 verbatim
/-- [Observed treatment in a backdoor system](hyp:S) is [measurable, so treatment-arm
events can be used for conditioning and adjustment](goal). -/
@[fun_prop]
lemma measurable_factualD : Measurable S.factualD := S.dVar.measurable_factual

-- @@ L113-116 verbatim
/-- [Observed outcome in a backdoor system](hyp:S) is [measurable, so its conditional
regressions are valid random variables](goal). -/
@[fun_prop]
lemma measurable_factualY : Measurable S.factualY := S.yVar.measurable_factual

-- @@ L117-120 verbatim
/-- [The adjustment covariate in a backdoor system](hyp:S) is [measurable, so it generates
the information set used for adjustment](goal). -/
@[fun_prop]
lemma measurable_factualX : Measurable S.factualX := S.xVar.measurable_factual


-- @@ L122-125 verbatim
/-- The [information set used for backdoor adjustment](goal) in [a binary-treatment
system](hyp:S) is [exactly the σ-algebra generated by the observed covariate](step:1). -/
noncomputable def sigmaX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualX inferInstance


-- @@ L127-131 verbatim
/-- [The covariate information set in a backdoor system](hyp:S) is [contained in the
full observable σ-algebra](goal), so covariate-measurable nuisance functions are valid
random variables. -/
lemma sigmaX_le : S.sigmaX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_factualX.comap_le


-- @@ L133-137 verbatim
/-- [The observed covariate in a backdoor system](hyp:S) is [measurable using only the
information it generates](goal), which licenses conditioning on that covariate. -/
@[fun_prop]
lemma measurable_factualX_sigmaX : Measurable[S.sigmaX] S.factualX :=
  comap_measurable S.factualX


-- @@ L139-143 verbatim
/-- The [regimed outcome variable](goal) in [a backdoor system](hyp:S) [pairs the outcome
with an intervention that fixes treatment to the selected arm](step:1), [making that arm
available to counterfactual-independence statements](hyp:d). -/
def yUnderD (d : Bool) : RegimedVar P ℝ :=
  ⟨S.yVar, Regime.single S.D (S.hDbool.symm d)⟩


-- @@ L145-151 verbatim
/-- The [counterfactual bundle used in the unconfoundedness assumption](goal) for
[a backdoor system](hyp:S) [collects both treated and untreated potential outcomes](step:1),
so joint exchangeability covers both ATE arms. -/
noncomputable def cfBundle : POCFBundle P :=
  POCFBundle.cons (S.yUnderD true) <|
  POCFBundle.cons (S.yUnderD false) <|
  POCFBundle.nil P


-- @@ L153-157 verbatim
/-- The [arm-specific propensity score](goal) in [a backdoor system](hyp:S) [is the
conditional treatment-arm probability given the adjustment covariates](step:1); the
[selected arm](hyp:d) determines which overlap condition is relevant. -/
noncomputable def propScore (d : Bool) : P.Ω → ℝ :=
  P.μ[S.dVar.indicator d | S.sigmaX]


-- @@ L159-166 verbatim
/-- The [arm-specific conditional mean potential outcome](goal) in [a backdoor
system](hyp:S) [averages the potential outcome given the adjustment covariates](step:1) for
[the selected treatment arm](hyp:d).

This is the arm-specific conditional mean `μ_d(X) = E[Y(d) | X]`, not the
treated-minus-control conditional effect. -/
noncomputable def conditionalMeanOutcome (d : Bool) : P.Ω → ℝ :=
  P.μ[S.YofD d | S.sigmaX]


-- @@ L168-173 verbatim
/-- The propensity score at a treatment arm is the conditional expectation of that arm's
treatment indicator given the covariate σ-algebra. -/
@[causal_defs_simps]
lemma propScore_eq (d : Bool) :
    S.propScore d = P.μ[S.dVar.indicator d | S.sigmaX] :=
  rfl


-- @@ L175-181 verbatim
/-- For [an arm in a backdoor system](hyp:S,d), [the arm-specific conditional mean
potential outcome equals the conditional expectation of that arm's potential outcome given
the covariate σ-algebra](goal). -/
@[causal_defs_simps]
lemma conditionalMeanOutcome_eq (d : Bool) :
    S.conditionalMeanOutcome d = P.μ[S.YofD d | S.sigmaX] :=
  rfl


-- @@ L183-188 verbatim
/-- The propensity score is strongly measurable for the covariate sigma-algebra:
it is a conditional expectation given that sigma-algebra. -/
@[fun_prop]
lemma stronglyMeasurable_propScore_sigmaX (d : Bool) :
    StronglyMeasurable[S.sigmaX] (S.propScore d) :=
  MeasureTheory.stronglyMeasurable_condExp


-- @@ L190-194 verbatim
/-- [The propensity score for a treatment arm](hyp:d) [uses only covariate
information](goal) in [the backdoor system](hyp:S), as required for adjustment. -/
@[fun_prop]
lemma measurable_propScore_sigmaX (d : Bool) : Measurable[S.sigmaX] (S.propScore d) :=
  (MeasureTheory.stronglyMeasurable_condExp).measurable


-- @@ L196-200 verbatim
/-- [The propensity score for a treatment arm](hyp:d) in [a backdoor system](hyp:S) is
[a measurable random variable on the full sample space](goal). -/
@[fun_prop]
lemma measurable_propScore (d : Bool) : Measurable (S.propScore d) :=
  (S.measurable_propScore_sigmaX d).mono S.sigmaX_le le_rfl


-- @@ L202-206 verbatim
/-- [The propensity score for a treatment arm](hyp:d) in [a backdoor system](hyp:S) has
[a finite population mean](goal), because it is a conditional probability. -/
@[fun_prop]
lemma integrable_propScore (d : Bool) : Integrable (S.propScore d) P.μ :=
  MeasureTheory.integrable_condExp


-- @@ L208-213 verbatim
/-- In [a backdoor system](hyp:S), [the conditional mean potential outcome for an
arm](hyp:d) [is strongly measurable for the covariate σ-algebra](goal). -/
@[fun_prop]
lemma stronglyMeasurable_conditionalMeanOutcome_sigmaX (d : Bool) :
    StronglyMeasurable[S.sigmaX] (S.conditionalMeanOutcome d) :=
  MeasureTheory.stronglyMeasurable_condExp


-- @@ L215-221 verbatim
/-- In [a backdoor system](hyp:S), [the conditional mean potential outcome for an
arm](hyp:d) is [a measurable random variable on the sample space](goal). -/
@[fun_prop]
lemma measurable_conditionalMeanOutcome (d : Bool) :
    Measurable (S.conditionalMeanOutcome d) :=
  ((MeasureTheory.stronglyMeasurable_condExp
    (μ := P.μ) (m := S.sigmaX) (f := S.YofD d)).measurable).mono S.sigmaX_le le_rfl


-- @@ L223-229 verbatim
/-- In [a backdoor system](hyp:S), [the conditional mean potential outcome for an
arm](hyp:d) has [a finite population mean whenever represented as a conditional
expectation](goal). -/
@[fun_prop]
lemma integrable_conditionalMeanOutcome (d : Bool) :
    Integrable (S.conditionalMeanOutcome d) P.μ :=
  MeasureTheory.integrable_condExp


-- @@ L231-233 verbatim
/-- The [average treatment effect](goal) in [a binary-treatment backdoor system](hyp:S)
[averages each unit's treated-minus-untreated potential-outcome contrast](step:1). -/
noncomputable def ATE : ℝ := ∫ ω, S.YofD true ω - S.YofD false ω ∂P.μ


-- @@ L235-242 verbatim
/-- The [observable arm-specific adjustment functional](goal) in [a backdoor
system](hyp:S) [divides the covariate-conditional outcome contribution of an arm by its
propensity](step:1), with [the selected arm](hyp:d) determining both quantities.

It is the observable outcome-indicator
regression divided by the propensity score. -/
noncomputable def adjustedCE (d : Bool) : P.Ω → ℝ :=
  fun ω => P.μ[fun ω' => S.factualY ω' * S.dVar.indicator d ω' | S.sigmaX] ω / S.propScore d ω


-- @@ L244-253 verbatim
/-- The adjusted conditional functional at a treatment arm sends a unit to the conditional
expectation, given the covariate σ-algebra, of the factual outcome times that arm's treatment
indicator, divided by the propensity score of that arm. -/
@[causal_defs_simps]
lemma adjustedCE_def (d : Bool) :
    S.adjustedCE d =
      fun ω =>
        P.μ[fun ω' => S.factualY ω' * S.dVar.indicator d ω' | S.sigmaX] ω /
          S.propScore d ω :=
  rfl


-- @@ L255-261 verbatim
/-- The [observable adjusted ATE functional](goal) in [a backdoor system](hyp:S)
[averages the treated-minus-control contrast of the two adjusted conditional means](step:1).

It integrates the difference of the two adjusted conditional
outcome functionals. -/
noncomputable def adjustedATE : ℝ :=
  ∫ ω, S.adjustedCE true ω - S.adjustedCE false ω ∂P.μ


-- @@ L263-295 verbatim
/-- The backdoor (Rosenbaum–Rubin / Firpo) identifying assumptions for the ATE, at the
potential-outcome level, for binary treatment `D` and real outcome `Y` adjusted for covariates
`X`: [the observed outcome equals the potential outcome of the realized treatment
arm](hyp:consistency), [treatment is conditionally independent of the treated and untreated
potential outcomes given the covariates](hyp:unconfoundedness), [every covariate stratum has
a positive chance of either treatment arm](hyp:overlap), and [the treated and untreated
potential outcomes are integrable](hyp:integrable_Y1,integrable_Y0). -/
structure Assumptions (S : POBackdoorSystem P γ)
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ] : Prop where
  /-- Consistency (SUTVA): the observed outcome equals the potential outcome of
  the realized arm — on `{D = d}`, `Y = Y(d)`. Links observed data to the
  potential outcomes. -/
  consistency : P.Consistency
  /-- Unconfoundedness (conditional ignorability): treatment is independent of the
  potential outcomes given the covariates, `D ⟂ (Y(1), Y(0)) | X`. Stated as
  conditional independence of the realized `D` and the counterfactual bundle
  `(Y(1), Y(0))` given `σ(X)`. -/
  unconfoundedness :
    P.CondIndepCF (RegimedVar.ofFactual S.dVar) S.cfBundle
      (RegimedVar.ofFactual S.xVar) P.μ
  /-- Overlap (common support): every covariate stratum has a positive chance of
  EITHER arm — `0 < P[D=1 | σ(X)] < 1` a.s. Two-sided here because the ATE needs
  both arms identified at every `x`. Bare positivity (not a uniform `c ≤ e ≤ 1−c`
  strong-overlap bound, which is only needed for efficient-estimator asymptotics),
  mirroring DTR. -/
  overlap :
    ∀ᵐ ω ∂P.μ, 0 < S.propScore true ω ∧ S.propScore true ω < 1
  /-- Regularity: the treated potential outcome `Y(1)` is integrable (so `E[Y(1)]`
  is well-defined). -/
  integrable_Y1 : Integrable (S.YofD true) P.μ
  /-- Regularity: the control potential outcome `Y(0)` is integrable (so `E[Y(0)]`
  is well-defined). -/
  integrable_Y0 : Integrable (S.YofD false) P.μ


-- @@ L297-297 verbatim
attribute [fun_prop] Assumptions.integrable_Y1 Assumptions.integrable_Y0


-- @@ L299-306 verbatim
/-- Under the backdoor assumption bundle the potential outcome of either treatment
arm is integrable. -/
@[fun_prop]
lemma Assumptions.integrable_YofD [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) (d : Bool) : Integrable (S.YofD d) P.μ := by
  cases d
  · exact hA.integrable_Y0
  · exact hA.integrable_Y1


-- @@ L308-348 verbatim
/-- Factual `Y` is integrable whenever both treatment-arm potential outcomes are
integrable and consistency links the observed outcome to the realized arm. -/
lemma integrable_factualY_of_consistency
    (hcons : P.Consistency)
    (hY1 : Integrable (S.YofD true) P.μ)
    (hY0 : Integrable (S.YofD false) P.μ) :
    Integrable S.factualY P.μ := by
  have hY1_ind :
      Integrable (fun ω => S.YofD true ω * S.dVar.indicator true ω) P.μ := by fun_prop
  have hY0_ind :
      Integrable (fun ω => S.YofD false ω * S.dVar.indicator false ω) P.μ := by fun_prop
  have hsum_int :
      Integrable
        (fun ω => S.YofD true ω * S.dVar.indicator true ω
          + S.YofD false ω * S.dVar.indicator false ω) P.μ := by fun_prop
  refine hsum_int.congr ?_
  filter_upwards with ω
  have htrue := congr_fun
    (POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar true (Ne.symm S.hDY)) ω
  have hfalse := congr_fun
    (POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
      hcons S.yVar S.dVar false (Ne.symm S.hDY)) ω
  have htrue' : S.YofD true ω * S.dVar.indicator true ω =
      S.factualY ω * S.dVar.indicator true ω := by
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY] using htrue.symm
  have hfalse' : S.YofD false ω * S.dVar.indicator false ω =
      S.factualY ω * S.dVar.indicator false ω := by
    simpa [POBackdoorSystem.YofD, POBackdoorSystem.factualY] using hfalse.symm
  have hsum := S.dVar.indicator_add_indicator_not ω
  calc
    S.YofD true ω * S.dVar.indicator true ω
        + S.YofD false ω * S.dVar.indicator false ω
        = S.factualY ω * S.dVar.indicator true ω
          + S.factualY ω * S.dVar.indicator false ω := by
          rw [htrue', hfalse']
    _ = S.factualY ω *
            (S.dVar.indicator true ω + S.dVar.indicator false ω) := by
          ring
    _ = S.factualY ω := by
          rw [hsum, mul_one]


-- @@ L350-358 verbatim
/-- [The backdoor assumptions](hyp:hA) guarantee that [the observed outcome in the
system](hyp:S) [has a finite population mean](goal), by consistency and armwise
integrability. -/
@[fun_prop]
lemma Assumptions.integrable_factualY
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ] (hA : S.Assumptions) :
    Integrable S.factualY P.μ :=
  S.integrable_factualY_of_consistency
    hA.consistency hA.integrable_Y1 hA.integrable_Y0


-- @@ L360-398 verbatim
/-- From two-sided overlap, the per-arm propensity score `P[D=d | σ(X)]` is a.s.
nonzero: for `d = true` directly from `0 < e(X)`, for `d = false` from
`e(X) < 1` via `propScore false = 1 - e(X)`. -/
lemma propScore_ne_of_overlap [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hov : ∀ᵐ ω ∂P.μ, 0 < S.propScore true ω ∧ S.propScore true ω < 1) (d : Bool) :
    ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0 := by
  cases d
  · -- false: propScore false = 1 - propScore true, and propScore true < 1.
    have hindD_integrable : ∀ e : Bool, Integrable (S.dVar.indicator e) P.μ :=
      fun e => S.dVar.integrable_indicator e (measurableSet_singleton e)
    have hsum_ptwise :
        (fun ω => S.dVar.indicator true ω + S.dVar.indicator false ω)
          = (fun _ : P.Ω => (1 : ℝ)) := by
      funext ω
      exact S.dVar.indicator_add_indicator_not ω
    have hsum :
        P.μ[fun ω => S.dVar.indicator true ω + S.dVar.indicator false ω | S.sigmaX]
          =ᵐ[P.μ] (fun _ => (1 : ℝ)) := by
      rw [hsum_ptwise]
      condexp_linearity
    have hadd :
        P.μ[fun ω => S.dVar.indicator true ω + S.dVar.indicator false ω | S.sigmaX]
          =ᵐ[P.μ]
            P.μ[S.dVar.indicator true | S.sigmaX]
              + P.μ[S.dVar.indicator false | S.sigmaX] :=
      by condexp_linearity [hindD_integrable true, hindD_integrable false]
    filter_upwards [hsum, hadd, hov] with ω h1 h2 hT
    have heq : S.propScore true ω + S.propScore false ω = 1 := by
      have : P.μ[S.dVar.indicator true | S.sigmaX] ω
            + P.μ[S.dVar.indicator false | S.sigmaX] ω = 1 := by
        rw [← Pi.add_apply, ← h2, h1]
      unfold POBackdoorSystem.propScore
      exact this
    have hps_false : S.propScore false ω = 1 - S.propScore true ω := by linarith
    rw [hps_false]
    intro h
    linarith [hT.2]
  · filter_upwards [hov] with ω hω
    exact ne_of_gt hω.1


-- @@ L400-525 verbatim
/-- **Per-arm backdoor identification.** In [a binary-treatment backdoor
system](hyp:S), [the arm-specific conditional mean potential outcome equals the
adjusted-outcome functional](goal) when [factual consistency](hyp:hcons), [conditional
independence of that arm's potential outcome from treatment given covariates](hyp:hunconf),
[integrability of both potential outcomes](hyp:hY1,hY0), and [nonzero propensity for the
selected arm](hyp:h_ne) hold for [that treatment arm](hyp:d):

    μ[Y(d) | σ(X)] =ᵐ[μ] μ[Y · 1_{D=d} | σ(X)] / P[D=d | σ(X)].

This per-arm form isolates both the exchangeability and positivity actually
needed for one arm. -/
theorem conditionalMeanOutcome_backdoor_of_propScore_ne
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hcons : P.Consistency)
    (d : Bool)
    (hunconf : CondIndepFun S.sigmaX S.sigmaX_le
      S.factualD (S.YofD d) P.μ)
    (hY1 : Integrable (S.YofD true) P.μ) (hY0 : Integrable (S.YofD false) P.μ)
    (h_ne : ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0) :
    S.conditionalMeanOutcome d =ᵐ[P.μ] S.adjustedCE d := by
  -- Rewrite `adjustedCE d = condExpRatio S.xVar (factualY * indD d) (indD d) P.μ`.
  have hratio_def :
      S.adjustedCE d
        = S.xVar.condExpRatio
          (fun ω => S.factualY ω * S.dVar.indicator d ω)
          (S.dVar.indicator d) P.μ := by
    funext ω
    unfold POBackdoorSystem.adjustedCE POBackdoorSystem.propScore
      POBackdoorSystem.sigmaX POBackdoorSystem.factualX POVar.condExpRatio
      POVar.condExpGiven
    rfl
  rw [hratio_def]
  -- Apply `condExpRatio_eq_of_mul` to reduce to (hprod) and (hne).
  refine (S.xVar.condExpRatio_eq_of_mul (g := fun ω => S.factualY ω * S.dVar.indicator d ω)
      (h := S.dVar.indicator d) (target := S.conditionalMeanOutcome d) ?_ ?_).symm
  · -- (hprod): μ[Y·1_{D=d}|σX] =ᵐ μ[1_{D=d}|σX] · conditionalMeanOutcome d.
    -- Integrability prerequisites.
    have hindD_integrable : Integrable (S.dVar.indicator d) P.μ := by fun_prop
    have hYofD_integrable : Integrable (S.YofD d) P.μ := by
      cases d
      · exact hY0
      · exact hY1
    have hYofD_bdd_integrable_aux :
        Integrable (fun ω => S.YofD d ω * S.dVar.indicator d ω) P.μ := by fun_prop
    have hYtimesInd_integrable :
        Integrable (fun ω => S.factualY ω * S.dVar.indicator d ω) P.μ := by
      exact S.dVar.integrable_mul_indicator d (measurableSet_singleton d)
        (S.integrable_factualY_of_consistency hcons hY1 hY0)
    -- Step 1: μ[Y·1_{D=d}|σX] =ᵐ μ[Y(d)·1_{D=d}|σX].
    have hstep1 :
        S.xVar.condExpGiven (fun ω => S.factualY ω * S.dVar.indicator d ω) P.μ
          =ᵐ[P.μ] S.xVar.condExpGiven
            (fun ω => S.YofD d ω * S.dVar.indicator d ω) P.μ := by
      have hvw : S.yVar.v ≠ S.dVar.v := Ne.symm S.hDY
      have hfm :=
        POVar.factual_mul_indicator_eq_cfUnder_mul_indicator_fn
          hcons S.yVar S.dVar d hvw
      -- `S.factualY = S.yVar.factual` and `S.YofD d = S.yVar.cfUnder S.dVar d` by def.
      change S.xVar.condExpGiven
          (fun ω => S.yVar.factual ω * S.dVar.indicator d ω) P.μ
          =ᵐ[P.μ] S.xVar.condExpGiven
            (fun ω => S.yVar.cfUnder S.dVar d ω * S.dVar.indicator d ω) P.μ
      rw [hfm]
    refine hstep1.trans ?_
    -- Apply factorization with u := indD d (as a function of factualD) and v := YofD d.
    -- Use the plain pointwise product: indD d ω * YofD d ω.
    have hindMul_swap :
        (fun ω => S.YofD d ω * S.dVar.indicator d ω)
          = (fun ω => S.dVar.indicator d ω * S.YofD d ω) := by
      funext ω; exact mul_comm _ _
    rw [hindMul_swap]
    -- Apply via an auxiliary lemma that takes the (u, v) shapes matching our data.
    -- Use `condExp_mul_of_condIndep` with:
    --   f = factualD, g = YofD d, u = (fun b => if b = d then 1 else 0), v = id.
    -- `u (factualD ω) = indD d ω` and `id (YofD d ω) = YofD d ω` by rfl.
    -- Set-indicator packaging: `u b := ({d} : Set Bool).indicator 1 b`, which
    -- satisfies `u (S.factualD ω) = S.dVar.indicator d ω`.
    let u : Bool → ℝ := ({d} : Set Bool).indicator (fun _ => (1 : ℝ))
    have hu_meas : Measurable u := by fun_prop
    have hu_eq : (fun ω => u (S.factualD ω)) = S.dVar.indicator d := by
      funext ω
      unfold POVar.indicator
      by_cases h : S.factualD ω = d
      · have h1 : S.factualD ω ∈ ({d} : Set Bool) := h
        have h2 : ω ∈ S.dVar.event d := h
        rw [show u (S.factualD ω) = (1 : ℝ) from Set.indicator_of_mem h1 _,
            Set.indicator_of_mem h2]
      · have h1 : S.factualD ω ∉ ({d} : Set Bool) := h
        have h2 : ω ∉ S.dVar.event d := h
        rw [show u (S.factualD ω) = (0 : ℝ) from Set.indicator_of_notMem h1 _,
            Set.indicator_of_notMem h2]
    have huMul_int :
        MeasureTheory.Integrable
          (fun ω => u (S.factualD ω) * S.YofD d ω) P.μ := by fun_prop
    have hfact :
        P.μ[fun ω => u (S.factualD ω) * S.YofD d ω | S.sigmaX]
          =ᵐ[P.μ]
            P.μ[fun ω => u (S.factualD ω) | S.sigmaX]
              * P.μ[fun ω => S.YofD d ω | S.sigmaX] := by
      have := condExp_mul_of_condIndep (μ := P.μ) (m := S.sigmaX) S.sigmaX_le
          (f := S.factualD) (g := S.YofD d)
          S.measurable_factualD (S.measurable_YofD d) hunconf
          (u := u) (v := id) hu_meas measurable_id
          (by rw [hu_eq]; exact hindD_integrable)
          hYofD_integrable huMul_int
      exact this
    -- Goal (after hindMul_swap):
    --   S.xVar.condExpGiven (indD d * YofD d) =ᵐ
    --     S.xVar.condExpGiven (indD d) * conditionalMeanOutcome d.
    -- Unfold the definitions to land on μ[·|σX] with matching argument shapes.
    unfold POVar.condExpGiven POBackdoorSystem.conditionalMeanOutcome
      POBackdoorSystem.sigmaX POBackdoorSystem.factualX
    have hfact_rw : (fun ω => u (S.factualD ω)) = S.dVar.indicator d := hu_eq
    have hprod_rw : (fun ω => u (S.factualD ω) * S.YofD d ω)
        = (fun ω => S.dVar.indicator d ω * S.YofD d ω) := by
      funext ω; rw [congr_fun hu_eq ω]
    rw [hprod_rw, hfact_rw] at hfact
    exact hfact
  · -- (hne): μ[1_{D=d}|σX] ≠ 0 a.s. — supplied directly as `h_ne`.
    -- `S.xVar.condExpGiven (S.dVar.indicator d) P.μ = S.propScore d` definitionally.
    have hEq : S.xVar.condExpGiven (S.dVar.indicator d) P.μ = S.propScore d := by
      unfold POVar.condExpGiven POBackdoorSystem.propScore
        POBackdoorSystem.sigmaX POBackdoorSystem.factualX
      rfl
    rw [hEq]
    exact h_ne


-- @@ L527-549 verbatim
/-- **Backdoor identification from the traditional two-arm exchangeability
bundle.** Under [factual consistency](hyp:hcons), [joint conditional
independence of treatment from both potential outcomes](hyp:hunconf),
[integrability of both arms](hyp:hY1,hY0), for [a treatment arm](hyp:d) with
[nonzero propensity](hyp:h_ne), [the arm-specific conditional mean equals the
adjusted-outcome functional](goal).

This compatibility wrapper projects the requested arm from the two-arm bundle
and applies `conditionalMeanOutcome_backdoor_of_propScore_ne`. -/
theorem conditionalMeanOutcome_backdoor_of_condIndepCF_of_propScore_ne
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hcons : P.Consistency)
    (hunconf : P.CondIndepCF (RegimedVar.ofFactual S.dVar) S.cfBundle
      (RegimedVar.ofFactual S.xVar) P.μ)
    (hY1 : Integrable (S.YofD true) P.μ) (hY0 : Integrable (S.YofD false) P.μ)
    (d : Bool) (h_ne : ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0) :
    S.conditionalMeanOutcome d =ᵐ[P.μ] S.adjustedCE d := by
  have hCI : CondIndepFun S.sigmaX S.sigmaX_le
      S.factualD (S.YofD d) P.μ := by
    cases d
    · exact hunconf.component (1 : Fin 2)
    · exact hunconf.component (0 : Fin 2)
  exact S.conditionalMeanOutcome_backdoor_of_propScore_ne hcons d hCI hY1 hY0 h_ne


-- @@ L551-570 verbatim
/-- **Conditional-mean backdoor identification.** In [a binary-treatment backdoor
system](hyp:S), under [the backdoor identification
assumptions — consistency, unconfoundedness, and two-sided overlap of the
propensity score, together with integrability of the potential
outcomes](hyp:hA), for [a treatment arm](hyp:d), [the arm-specific conditional
mean potential outcome equals the adjusted-outcome functional](goal):

    μ[Y(d) | σ(X)] =ᵐ[μ] μ[Y · 1_{D=d} | σ(X)] / P[D=d | σ(X)].

Two-sided wrapper around
`conditionalMeanOutcome_backdoor_of_condIndepCF_of_propScore_ne`: it discharges
the per-arm nonvanishing hypothesis from `Assumptions.overlap` via
`propScore_ne_of_overlap`. -/
theorem conditionalMeanOutcome_backdoor
    [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) (d : Bool) :
    S.conditionalMeanOutcome d =ᵐ[P.μ] S.adjustedCE d :=
  S.conditionalMeanOutcome_backdoor_of_condIndepCF_of_propScore_ne
    hA.consistency hA.unconfoundedness hA.integrable_Y1 hA.integrable_Y0 d
    (S.propScore_ne_of_overlap hA.overlap d)


-- @@ L572-588 verbatim
/-- **Integrated backdoor ATE identification.** In [a binary-treatment backdoor
system](hyp:S), under [the backdoor
identification assumptions — consistency, unconfoundedness, two-sided
overlap, and integrable potential outcomes](hyp:hA), [the average treatment
effect equals the adjusted-outcome functional obtained by averaging the
two arm-specific conditional-mean backdoor identities over the covariate
distribution](goal). -/
theorem ate_backdoor [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) : S.ATE = S.adjustedATE := by
  unfold POBackdoorSystem.ATE POBackdoorSystem.adjustedATE
  -- `conditionalMeanOutcome d = xVar.condExpGiven (YofD d) P.μ` definitionally.
  have hf' : S.xVar.condExpGiven (S.YofD true) P.μ =ᵐ[P.μ] S.adjustedCE true :=
    S.conditionalMeanOutcome_backdoor hA true
  have hg' : S.xVar.condExpGiven (S.YofD false) P.μ =ᵐ[P.μ] S.adjustedCE false :=
    S.conditionalMeanOutcome_backdoor hA false
  exact S.xVar.integral_sub_eq_integral_sub_of_condExpGiven_ae_eq
    hA.integrable_Y1 hA.integrable_Y0 hf' hg'


-- @@ L590-598 verbatim
/-! ## Regression-adjustment identification: the adjustment functional is a regression

`conditionalMeanOutcome_backdoor` identifies the *counterfactual* conditional mean `μ[Y(d)|σX]` with
the adjustment functional `adjustedCE d` (needs unconfoundedness). The results below
supply the missing, purely *observable* fact that `adjustedCE d` is the **outcome
regression of the observed `Y` on the observed `(D, X)`** — a statement about the
law of `(X, D, Y)` only — certifying that estimating `μ` is a standard regression
problem (the one `ML/CausalApplication/RegressionBridge.lean` solves). Together they give the
chain `E[Y(d)|X] =ᵐ adjustedCE d =ᵐ E[Y|D=d,X]`. -/


-- @@ L600-606 verbatim
/-- The [observable treatment–covariate state](goal) in [a backdoor system](hyp:S)
[pairs each unit's realized arm with its adjustment covariate](step:1).

The
covariate–treatment cell each unit lands in. -/
noncomputable def factualDX : P.Ω → Bool × γ :=
  fun ω => (S.factualD ω, S.factualX ω)


-- @@ L608-612 verbatim
/-- [The observed treatment–covariate state in a backdoor system](hyp:S) is [measurable,
so it can generate the information set for outcome regression](goal). -/
@[fun_prop]
lemma measurable_factualDX : Measurable S.factualDX :=
  S.measurable_factualD.prodMk S.measurable_factualX


-- @@ L614-620 verbatim
/-- The [information set for observed outcome regression](goal) in [a backdoor
system](hyp:S) is [generated jointly by realized treatment and covariates](step:1).

It contains the covariate σ-algebra and is the information available to a regression of
the outcome on treatment and covariates. -/
noncomputable def sigmaDX : MeasurableSpace P.Ω :=
  MeasurableSpace.comap S.factualDX inferInstance


-- @@ L622-626 verbatim
/-- [The joint treatment–covariate information set in a backdoor system](hyp:S) is
[contained in the full observable σ-algebra](goal), so observed outcome regression is
well-defined. -/
lemma sigmaDX_le : S.sigmaDX ≤ (inferInstance : MeasurableSpace P.Ω) :=
  S.measurable_factualDX.comap_le


-- @@ L628-632 verbatim
/-- [The observed treatment–covariate state in a backdoor system](hyp:S) is
[measurable using only its jointly generated information](goal). -/
@[fun_prop]
lemma measurable_factualDX_sigmaDX : Measurable[S.sigmaDX] S.factualDX :=
  comap_measurable S.factualDX


-- @@ L634-638 verbatim
/-- [Observed treatment in a backdoor system](hyp:S) is [available in the joint
treatment–covariate information set](goal). -/
@[fun_prop]
lemma measurable_factualD_sigmaDX : Measurable[S.sigmaDX] S.factualD :=
  measurable_fst.comp (comap_measurable S.factualDX)


-- @@ L640-644 verbatim
/-- [The observed covariate in a backdoor system](hyp:S) is [available in the joint
treatment–covariate information set](goal). -/
@[fun_prop]
lemma measurable_factualX_sigmaDX : Measurable[S.sigmaDX] S.factualX :=
  measurable_snd.comp (comap_measurable S.factualDX)


-- @@ L646-654 verbatim
/-- [The covariate information set in a backdoor system](hyp:S) is [coarser than the
joint treatment–covariate information set](goal), enabling conditional-expectation tower
arguments between adjustment and outcome regression. -/
lemma sigmaX_le_sigmaDX : S.sigmaX ≤ S.sigmaDX := by
  -- `factualX = Prod.snd ∘ factualDX`, so `comap factualX ≤ comap factualDX`.
  have hfx : S.factualX = Prod.snd ∘ S.factualDX := rfl
  rw [POBackdoorSystem.sigmaX, POBackdoorSystem.sigmaDX, hfx,
    ← MeasurableSpace.comap_comp]
  exact MeasurableSpace.comap_mono measurable_snd.comap_le


-- @@ L656-663 verbatim
/-- The [observable outcome regression](goal) in [a backdoor system](hyp:S) [is the
conditional mean of observed outcomes given realized treatment and covariates](step:1).

It is the conditional
mean of the *observed* outcome given the *observed* treatment and covariate. A
functional of the observed data law, learnable by regressing `Y` on `(D, X)`. -/
noncomputable def outcomeReg : P.Ω → ℝ :=
  P.μ[S.factualY | S.sigmaDX]


-- @@ L665-670 verbatim
/-- [The observed outcome regression in a backdoor system](hyp:S) [depends measurably
only on realized treatment and covariates](goal), so it is a genuine regression nuisance. -/
@[fun_prop]
lemma stronglyMeasurable_outcomeReg :
    StronglyMeasurable[S.sigmaDX] S.outcomeReg :=
  MeasureTheory.stronglyMeasurable_condExp


-- @@ L672-676 verbatim
/-- [The observed outcome regression in a backdoor system](hyp:S) is [a measurable
random variable on the full sample space](goal). -/
@[fun_prop]
lemma measurable_outcomeReg : Measurable S.outcomeReg :=
  (S.stronglyMeasurable_outcomeReg.measurable).mono S.sigmaDX_le le_rfl


-- @@ L678-690 verbatim
/-- The `σ(D, X)`-measurable `outcomeReg` factors through `(D, X)`: there is a
measurable value-space regression function `r : Bool × γ → ℝ` with
`outcomeReg = r ∘ factualDX`. This is Doob–Dynkin (`exists_eq_measurable_comp`);
`r` is the function an ML regressor of `Y` on `(D, X)` targets. -/
lemma exists_regFn :
    ∃ r : Bool × γ → ℝ, Measurable r ∧
      S.outcomeReg = fun ω => r (S.factualDX ω) := by
  -- `sigmaDX = comap factualDX`, so `outcomeReg` is `comap factualDX`-measurable;
  -- Doob–Dynkin (`exists_eq_measurable_comp`) produces the value-space factorisation.
  have hmeas : Measurable[S.sigmaDX] S.outcomeReg := by fun_prop
  obtain ⟨r, hr_meas, hr_eq⟩ :=
    Measurable.exists_eq_measurable_comp (f := S.factualDX) (g := S.outcomeReg) hmeas
  exact ⟨r, hr_meas, by funext ω; exact congrFun hr_eq ω⟩


-- @@ L692-695 verbatim
/-- The [value-space outcome regression](goal) for [a backdoor system](hyp:S) [maps each
treatment–covariate cell to its observable conditional mean outcome](step:1), which is the
object a regression learner estimates. -/
noncomputable def regFn : Bool × γ → ℝ := S.exists_regFn.choose


-- @@ L697-700 verbatim
/-- [The selected value-space outcome regression for a backdoor system](hyp:S) is
[measurable, so evaluating it at observed or counterfactual arms remains valid](goal). -/
@[fun_prop]
lemma measurable_regFn : Measurable S.regFn := S.exists_regFn.choose_spec.1


-- @@ L702-706 verbatim
/-- The observed outcome regression equals the value-space regression evaluated
at each unit's observed treatment and covariate. -/
lemma outcomeReg_eq_regFn :
    S.outcomeReg = fun ω => S.regFn (S.factualDX ω) :=
  S.exists_regFn.choose_spec.2


-- @@ L708-716 verbatim
/-- The `σ(X)`-measurable propensity `propScore true` factors through `factualX`:
a measurable value-space propensity `e : γ → ℝ` with `propScore true = e ∘ factualX`
(Doob–Dynkin). This is the value-space propensity an estimator learns. -/
lemma exists_propScoreLift :
    ∃ e : γ → ℝ, Measurable e ∧ S.propScore true = fun ω => e (S.factualX ω) := by
  have hmeas : Measurable[S.sigmaX] (S.propScore true) := by fun_prop
  obtain ⟨e, he_meas, he_eq⟩ :=
    Measurable.exists_eq_measurable_comp (f := S.factualX) (g := S.propScore true) hmeas
  exact ⟨e, he_meas, by funext ω; exact congrFun he_eq ω⟩


-- @@ L718-721 verbatim
/-- The [value-space propensity function](goal) for [a backdoor system](hyp:S) [maps each
covariate value to its treated-arm probability](step:1), matching the nuisance function
estimated from observed data. -/
noncomputable def eLift : γ → ℝ := S.exists_propScoreLift.choose


-- @@ L723-726 verbatim
/-- [The selected value-space propensity for a backdoor system](hyp:S) is [measurable,
so it can be evaluated at the observed covariate](goal). -/
@[fun_prop]
lemma measurable_eLift : Measurable S.eLift := S.exists_propScoreLift.choose_spec.1


-- @@ L728-732 verbatim
/-- The treated-arm propensity score equals the value-space propensity evaluated
at each unit's observed covariate. -/
lemma propScore_true_eq_eLift :
    S.propScore true = fun ω => S.eLift (S.factualX ω) :=
  S.exists_propScoreLift.choose_spec.2


-- @@ L734-845 verbatim
/-- **Regression-adjustment identification (observable).** In [a binary-treatment
backdoor system](hyp:S), [the adjustment functional for an arm equals the value-space
outcome regression evaluated at that arm](goal) for [the selected treatment arm](hyp:d)
when [the observed outcome is integrable](hyp:hY) and [the arm has almost-surely
nonzero conditional probability given covariates](hyp:h_ne):

    adjustedCE d  =ᵐ  fun ω => regFn (d, factualX ω)  = E[Y | D=d, X].

This is a fact about the observed law of `(X, D, Y)` alone — it needs overlap
(`P[D=d | σ(X)] ≠ 0`) but NOT unconfoundedness. Combined with `conditionalMeanOutcome_backdoor` it
completes the chain `E[Y(d)|X] =ᵐ adjustedCE d =ᵐ E[Y|D=d,X]`, certifying the
back-door nuisance `μ` as a genuine regression problem. -/
theorem regression_adjustment [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (d : Bool) (hY : Integrable S.factualY P.μ)
    (h_ne : ∀ᵐ ω ∂P.μ, S.propScore d ω ≠ 0) :
    S.adjustedCE d =ᵐ[P.μ] (fun ω => S.regFn (d, S.factualX ω)) := by
  have hratio_def :
      S.adjustedCE d
        = S.xVar.condExpRatio
          (fun ω => S.factualY ω * S.dVar.indicator d ω)
          (S.dVar.indicator d) P.μ := by
    funext ω
    unfold POBackdoorSystem.adjustedCE POBackdoorSystem.propScore
      POBackdoorSystem.sigmaX POBackdoorSystem.factualX POVar.condExpRatio
      POVar.condExpGiven
    rfl
  rw [hratio_def]
  refine S.xVar.condExpRatio_eq_of_mul
    (g := fun ω => S.factualY ω * S.dVar.indicator d ω)
    (h := S.dVar.indicator d)
    (target := fun ω => S.regFn (d, S.factualX ω)) ?_ ?_
  · have hYint : Integrable S.factualY P.μ := hY
    · let s : Set P.Ω := S.dVar.event d
      let target : P.Ω → ℝ := fun ω => S.regFn (d, S.factualX ω)
      have hsDX : MeasurableSet[S.sigmaDX] s := by
        change MeasurableSet[MeasurableSpace.comap S.factualDX inferInstance]
          (S.factualD ⁻¹' {d})
        exact ⟨Prod.fst ⁻¹' {d}, measurableSet_singleton d |>.preimage measurable_fst, rfl⟩
      have hs : MeasurableSet s :=
        S.dVar.measurableSet_event d (measurableSet_singleton d)
      have hmul_indicator :
          (fun ω => S.factualY ω * S.dVar.indicator d ω) = s.indicator S.factualY := by
        funext ω
        by_cases hω : ω ∈ s
        · have hind : S.dVar.indicator d ω = 1 := S.dVar.indicator_apply_eq_one hω
          rw [hind, mul_one, Set.indicator_of_mem hω]
        · have hD : S.factualD ω ≠ d := hω
          have hind : S.dVar.indicator d ω = 0 := S.dVar.indicator_apply_eq_zero hD
          rw [hind, mul_zero, Set.indicator_of_notMem hω]
      have htarget_meas : Measurable[S.sigmaX] target := by fun_prop
      have htarget_sm : StronglyMeasurable[S.sigmaX] target := by fun_prop
      have houtcome_target :
          s.indicator S.outcomeReg = s.indicator target := by
        funext ω
        by_cases hω : ω ∈ s
        · have hD : S.factualD ω = d := hω
          rw [Set.indicator_of_mem hω, Set.indicator_of_mem hω]
          rw [congrFun S.outcomeReg_eq_regFn ω]
          simp [target, POBackdoorSystem.factualDX, hD]
        · rw [Set.indicator_of_notMem hω, Set.indicator_of_notMem hω]
      have htower :
          P.μ[s.indicator S.factualY | S.sigmaX]
            =ᵐ[P.μ] P.μ[s.indicator S.outcomeReg | S.sigmaX] := by
        simpa [s, POBackdoorSystem.outcomeReg] using
          MeasureTheory.condExp_setIndicator_condExp_of_le
            (μ := P.μ) (m := S.sigmaX) (m' := S.sigmaDX)
            S.sigmaX_le_sigmaDX S.sigmaDX_le hsDX hYint
      have hleft :
          P.μ[fun ω => S.factualY ω * S.dVar.indicator d ω | S.sigmaX]
            =ᵐ[P.μ] P.μ[s.indicator target | S.sigmaX] :=
        (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ)
          (Filter.EventuallyEq.of_eq hmul_indicator)).trans
          (htower.trans
            (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ)
              (Filter.EventuallyEq.of_eq houtcome_target)))
      have hind_int : Integrable (S.dVar.indicator d) P.μ := by fun_prop
      have htarget_mul_indicator :
          target * S.dVar.indicator d = s.indicator target := by
        funext ω
        by_cases hω : ω ∈ s
        · have hind : S.dVar.indicator d ω = 1 := S.dVar.indicator_apply_eq_one hω
          rw [Pi.mul_apply, hind, mul_one, Set.indicator_of_mem hω]
        · have hD : S.factualD ω ≠ d := hω
          have hind : S.dVar.indicator d ω = 0 := S.dVar.indicator_apply_eq_zero hD
          rw [Pi.mul_apply, hind, mul_zero, Set.indicator_of_notMem hω]
      have htarget_mul_int : Integrable (target * S.dVar.indicator d) P.μ := by
        rw [htarget_mul_indicator]
        have houtcome_target' :
            s.indicator (P.μ[S.factualY | S.sigmaDX]) = s.indicator target := by
          simpa [POBackdoorSystem.outcomeReg] using houtcome_target
        exact MeasureTheory.Integrable.indicator
          (MeasureTheory.integrable_condExp (μ := P.μ) (m := S.sigmaDX) (f := S.factualY)) hs
            |>.congr (Filter.EventuallyEq.of_eq houtcome_target')
      have hpull :
          P.μ[target * S.dVar.indicator d | S.sigmaX]
            =ᵐ[P.μ] target * P.μ[S.dVar.indicator d | S.sigmaX] :=
        MeasureTheory.condExp_mul_of_stronglyMeasurable_left
          (m := S.sigmaX) (μ := P.μ) htarget_sm htarget_mul_int hind_int
      change P.μ[fun ω => S.factualY ω * S.dVar.indicator d ω | S.sigmaX]
          =ᵐ[P.μ] P.μ[S.dVar.indicator d | S.sigmaX] * target
      refine hleft.trans ?_
      refine (MeasureTheory.condExp_congr_ae (m := S.sigmaX) (μ := P.μ)
        (Filter.EventuallyEq.of_eq htarget_mul_indicator.symm)).trans ?_
      exact hpull.trans (Filter.EventuallyEq.of_eq (by
        funext ω
        exact mul_comm _ _))
  · have hEq : S.xVar.condExpGiven (S.dVar.indicator d) P.μ = S.propScore d := by
      unfold POVar.condExpGiven POBackdoorSystem.propScore
        POBackdoorSystem.sigmaX POBackdoorSystem.factualX
      rfl
    rw [hEq]
    exact h_ne


-- @@ L847-856 verbatim
/-- **Regression-adjustment, packaged for identified systems.** The same observable
identity `adjustedCE d =ᵐ E[Y|D=d,X]`, with the two regularity hypotheses of
`regression_adjustment` discharged from the back-door `Assumptions`: integrability of
the observed outcome from `Assumptions.integrable_factualY`, and overlap from
`propScore_ne_of_overlap`. Lets callers in an identified context apply it with just
`hA`. -/
theorem regression_adjustment_of_assumptions [StandardBorelSpace P.Ω] [IsFiniteMeasure P.μ]
    (hA : S.Assumptions) (d : Bool) :
    S.adjustedCE d =ᵐ[P.μ] (fun ω => S.regFn (d, S.factualX ω)) :=
  S.regression_adjustment d hA.integrable_factualY (S.propScore_ne_of_overlap hA.overlap d)


-- @@ L858-858 verbatim
end POBackdoorSystem


-- @@ L860-860 verbatim
end PO

-- @@ L861-861 verbatim
end Causalean
