/-
Copyright (c) 2025 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Mathematics.OneParameterSubgroups.Unitary
public import Physlib.Meta.TODO.Basic
public import Physlib.QuantumMechanics.PlanckConstant

-- @@ L11-22 verbatim
/-!

# Finite-dimensional quantum systems

A `FiniteTarget` consists of a finite-dimensional Hilbert space together with a self-adjoint
Hamiltonian. Its Hamiltonian determines a unitary time evolution through Stone's correspondence.

Physical examples of such systems include:
- Spin systems.
- Tight binding chains.

-/


-- @@ L24-24 verbatim
@[expose] public section


-- @@ L26-26 verbatim
open Constants Module


-- @@ L28-28 verbatim
namespace QuantumMechanics


-- @@ L30-38 verbatim
/-- A finite-dimensional quantum system with a self-adjoint Hamiltonian. -/
structure FiniteTarget (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [FiniteDimensional ℂ H] (n : ℕ) where
  /-- The Hilbert space has dimension `n`. -/
  hdim: Module.finrank ℂ H = n
  /-- The Hamiltonian. -/
  Ham : H →L[ℂ] H
  /-- The Hamiltonian is self-adjoint. -/
  Ham_selfAdjoint: IsSelfAdjoint Ham


-- @@ L40-40 verbatim
namespace FiniteTarget

-- @@ L41-42 verbatim
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [FiniteDimensional ℂ H] -- a Hilbert Space with finite dimension

-- @@ L43-43 verbatim
variable {n : ℕ} (A : FiniteTarget H n)


-- @@ L45-50 verbatim
/-- The unitary time evolution generated by the Hamiltonian of `A`. -/
noncomputable def unitaryTimeEvolution : UnitaryOneParameterGroup H :=
  UnitaryOneParameterGroup.ofSelfAdjoint (A := ((ℏ : ℂ)⁻¹) • A.Ham) (by
    have hℏself : IsSelfAdjoint (ℏ : ℂ) := by
      rw [isSelfAdjoint_iff, Complex.star_def, Complex.conj_ofReal]
    exact hℏself.inv₀.smul A.Ham_selfAdjoint)


-- @@ L52-59 verbatim
/-- The generator of time evolution is the Hamiltonian divided by `ℏ`. -/
@[simp]
lemma unitaryTimeEvolution_generator :
    A.unitaryTimeEvolution.generator = ((ℏ : ℂ)⁻¹) • A.Ham := by
  apply Eq.symm
  apply UnitaryOneParameterGroup.generator_unique
  intro t
  rw [unitaryTimeEvolution, UnitaryOneParameterGroup.ofSelfAdjoint_apply]


-- @@ L61-62 verbatim
/-- The operator implementing the time evolution of `A` at time `t`. -/
noncomputable def timeEvolution (t : ℝ) : H →L[ℂ] H := A.unitaryTimeEvolution t


-- @@ L64-68 verbatim
@[simp] lemma timeEvolution_eq_exp (t : ℝ) :
    A.timeEvolution t = NormedSpace.exp ((-(t : ℂ) * Complex.I / ℏ) • A.Ham) := by
  rw [timeEvolution, UnitaryOneParameterGroup.apply_eq_exp_generator,
    unitaryTimeEvolution_generator, smul_smul]
  congr 1


-- @@ L70-73 verbatim
/-- The matrix of the time-evolution operator at time `t` in the basis `b`. -/
noncomputable def timeEvolutionMatrix (t : ℝ) (b : Basis (Fin n) ℂ H) :
  Matrix (Fin n) (Fin n) ℂ :=
  LinearMap.toMatrix b b (A.timeEvolution t).toLinearMap


-- @@ L75-79 verbatim
/-- The matrix of the time-evolution operator in a chosen basis indexed by `Fin n`. -/
noncomputable def timeEvolutionMatrixStandard (t : ℝ) :
  Matrix (Fin n) (Fin n) ℂ :=
  let b : Basis (Fin n) ℂ H := Module.finBasisOfFinrankEq ℂ H A.hdim
  timeEvolutionMatrix A t b


-- @@ L81-81 verbatim
TODO "Define a smooth structure on `FiniteTarget`."


-- @@ L83-83 verbatim
end FiniteTarget


-- @@ L85-85 verbatim
end QuantumMechanics
