/-
Copyright (c) 2024 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Mathlib.Analysis.Complex.Basic
public import Mathlib.Data.Matrix.Reflection
public import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
public import Physlib.Meta.TODO.Basic

-- @@ L12-35 verbatim
/-!
# The Clifford Algebra

This file defines the Gamma matrices and their relationship to the Clifford algebra.

## Main Definitions

- `γ0, γ1, γ2, γ3`: The four gamma matrices in the Dirac representation (4×4 complex matrices)
- `γSet`: The set of gamma matrices
- `diracForm`: The quadratic form with Minkowski signature (+,-,-,-)
  corresponding to the gamma matrices
- `diracAlgebra`: The algebra generated by the gamma matrices over ℝ
- `ofCliffordAlgebra`: The algebra homomorphism from the Clifford algebra to `diracAlgebra`

## Main Results

- `ofCliffordAlgebra_surjective`: The homomorphism `ofCliffordAlgebra` is surjective

## TODO

- Complete the isomorphism by proving injectivity of `ofCliffordAlgebra` (requires dimension theory)
- Construct the `AlgEquiv` between `CliffordAlgebra diracForm` and `diracAlgebra`

-/


-- @@ L37-37 verbatim
@[expose] public section

-- @@ L38-38 verbatim
TODO "Prove injectivity of ofCliffordAlgebra and construct the full isomorphism."

-- @@ L39-39 verbatim
namespace spaceTime

-- @@ L40-40 verbatim
open Complex


-- @@ L42-42 verbatim
noncomputable section diracRepresentation


-- @@ L44-46 verbatim
/-- The γ⁰ gamma matrix in the Dirac representation. -/
def γ0 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, -1, 0; 0, 0, 0, -1]


-- @@ L48-50 verbatim
/-- The γ¹ gamma matrix in the Dirac representation. -/
def γ1 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 0, 1; 0, 0, 1, 0; 0, -1, 0, 0; -1, 0, 0, 0]


-- @@ L52-54 verbatim
/-- The γ² gamma matrix in the Dirac representation. -/
def γ2 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 0, - I; 0, 0, I, 0; 0, I, 0, 0; -I, 0, 0, 0]


-- @@ L56-58 verbatim
/-- The γ³ gamma matrix in the Dirac representation. -/
def γ3 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 1, 0; 0, 0, 0, -1; -1, 0, 0, 0; 0, 1, 0, 0]


-- @@ L60-62 verbatim
theorem _root_.Matrix.one_fin_four {α} [Zero α] [One α] :
    (1 : Matrix (Fin 4) (Fin 4) α) = !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1] :=
  Matrix.etaExpand_eq _ |>.symm


-- @@ L64-64 verbatim
@[simp] lemma γ0_mul_γ0 : γ0 * γ0 = 1 := by simp [γ0, Matrix.one_fin_four]

-- @@ L65-65 verbatim
@[simp] lemma γ1_mul_γ1 : γ1 * γ1 = -1 := by simp [γ1, Matrix.one_fin_four]

-- @@ L66-66 verbatim
@[simp] lemma γ2_mul_γ2 : γ2 * γ2 = -1 := by simp [γ2, Matrix.one_fin_four]

-- @@ L67-67 verbatim
@[simp] lemma γ3_mul_γ3 : γ3 * γ3 = -1 := by simp [γ3, Matrix.one_fin_four]


-- @@ L69-69 verbatim
@[simp] lemma γ1_mul_γ0 : γ1 * γ0 = -(γ0 * γ1) := by simp [γ0, γ1]

-- @@ L70-70 verbatim
@[simp] lemma γ2_mul_γ0 : γ2 * γ0 = -(γ0 * γ2) := by simp [γ0, γ2]

-- @@ L71-71 verbatim
@[simp] lemma γ3_mul_γ0 : γ3 * γ0 = -(γ0 * γ3) := by simp [γ0, γ3]

-- @@ L72-72 verbatim
@[simp] lemma γ2_mul_γ1 : γ2 * γ1 = -(γ1 * γ2) := by simp [γ1, γ2]

-- @@ L73-73 verbatim
@[simp] lemma γ3_mul_γ1 : γ3 * γ1 = -(γ1 * γ3) := by simp [γ1, γ3]

-- @@ L74-74 verbatim
@[simp] lemma γ3_mul_γ2 : γ3 * γ2 = -(γ2 * γ3) := by simp [γ2, γ3]


-- @@ L76-77 verbatim
/-- The γ⁵ gamma matrix in the Dirac representation. -/
def γ5 : Matrix (Fin 4) (Fin 4) ℂ := I • (γ0 * γ1 * γ2 * γ3)


-- @@ L79-81 verbatim
/-- The γ gamma matrices in the Dirac representation. -/
@[simp]
def γ : Fin 4 → Matrix (Fin 4) (Fin 4) ℂ := ![γ0, γ1, γ2, γ3]


-- @@ L83-83 verbatim
namespace γ


-- @@ L85-85 verbatim
open spaceTime


-- @@ L87-87 verbatim
variable (μ ν : Fin 4)


-- @@ L89-92 verbatim
/-- The subset of `Matrix (Fin 4) (Fin 4) ℂ` formed by the gamma matrices in the Dirac
representation. -/
@[simp]
def γSet : Set (Matrix (Fin 4) (Fin 4) ℂ) := {γ i | i : Fin 4}


-- @@ L94-95 verbatim
lemma γ_in_γSet (μ : Fin 4) : γ μ ∈ γSet := by
  simp [γSet]


-- @@ L97-99 verbatim
/-- The algebra generated by the gamma matrices in the Dirac representation. -/
def diracAlgebra : Subalgebra ℝ (Matrix (Fin 4) (Fin 4) ℂ) :=
  Algebra.adjoin ℝ γSet


-- @@ L101-102 verbatim
lemma γSet_subset_diracAlgebra : γSet ⊆ diracAlgebra :=
  Algebra.subset_adjoin


-- @@ L104-105 verbatim
lemma γ_in_diracAlgebra (μ : Fin 4) : γ μ ∈ diracAlgebra :=
  γSet_subset_diracAlgebra (γ_in_γSet μ)


-- @@ L107-113 verbatim
/-- The quadratic form of the clifford algebra corresponding to the `γ` matrices. -/
@[simps!]
def diracForm : QuadraticForm ℝ (Fin 4 → ℝ) :=
  QuadraticMap.sq.comp (LinearMap.proj 0)
    - QuadraticMap.sq.comp (LinearMap.proj 1)
    - QuadraticMap.sq.comp (LinearMap.proj 2)
    - QuadraticMap.sq.comp (LinearMap.proj 3)


-- @@ L115-128 verbatim
/-- The injection from the clifford algebra over `diracForm` into the algebra generated by the
`γ` matrices. -/
def ofCliffordAlgebra : CliffordAlgebra diracForm →ₐ[ℝ] diracAlgebra :=
  CliffordAlgebra.lift _
    ⟨∑ i, (LinearMap.proj i).smulRight ⟨γ i, γ_in_diracAlgebra _⟩, fun v => by
      ext : 1
      simp only [γ, Fin.sum_univ_four, Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one,
        Matrix.cons_val, LinearMap.add_apply, LinearMap.coe_smulRight, LinearMap.coe_proj,
        Function.eval, SetLike.mk_smul_mk, AddMemClass.mk_add_mk, MulMemClass.mk_mul_mk, mul_add,
        Algebra.mul_smul_comm, add_mul, Algebra.smul_mul_assoc, γ0_mul_γ0, γ1_mul_γ0, smul_neg,
        γ2_mul_γ0, γ3_mul_γ0, smul_add, γ1_mul_γ1, γ2_mul_γ1, γ3_mul_γ1, γ2_mul_γ2, γ3_mul_γ2,
        γ3_mul_γ3, diracForm_apply, Algebra.algebraMap_eq_smul_one, SetLike.val_smul,
        OneMemClass.coe_one]
      module⟩


-- @@ L130-141 verbatim
/-- The generators of the clifford algebra correspond to the elements `γ`. -/
@[simp]
lemma ofCliffordAlgebra_ι_single (i : Fin 4) (r : ℝ) :
    ofCliffordAlgebra (CliffordAlgebra.ι _ (Pi.single i r)) = r • ⟨γ i, γ_in_diracAlgebra _⟩ :=
  CliffordAlgebra.lift_ι_apply _ _ _ |>.trans <| Subtype.ext <| by
    simp only [γ, LinearMap.coe_sum, LinearMap.coe_smulRight, LinearMap.coe_proj, Function.eval,
      SetLike.mk_smul_mk, Finset.sum_apply, AddSubmonoidClass.coe_finsetSum]
    rw [Finset.sum_eq_single i]
    · simp
    · intro b _ hb
      simp [Pi.single_eq_of_ne hb]
    · simp


-- @@ L143-143 verbatim
/-! ### Surjectivity of ofCliffordAlgebra -/


-- @@ L145-149 verbatim
/-- Each gamma matrix (as an element of diracAlgebra) is in the range of ofCliffordAlgebra. -/
lemma γ_subtype_in_range (i : Fin 4) :
    ⟨γ i, γ_in_diracAlgebra i⟩ ∈ ofCliffordAlgebra.range := by
  use CliffordAlgebra.ι diracForm (Pi.single i 1)
  simp [ofCliffordAlgebra_ι_single]


-- @@ L151-181 verbatim
/-- Helper lemma: If a matrix is in Algebra.adjoin ℝ γSet, then its subtype is in the range. -/
private lemma mem_adjoin_imp_subtype_in_range (m : Matrix (Fin 4) (Fin 4) ℂ)
    (hm : m ∈ Algebra.adjoin ℝ γSet) : ⟨m, hm⟩ ∈ ofCliffordAlgebra.range := by
  induction hm using Algebra.adjoin_induction with
  | mem y hy =>
    -- y ∈ γSet, so y = γ i for some i
    obtain ⟨i, rfl⟩ := hy
    exact γ_subtype_in_range i
  | algebraMap r =>
    -- r from ℝ
    use algebraMap ℝ _ r
    ext
    simp [Algebra.algebraMap_eq_smul_one]
  | add y z _ _ hy hz =>
    -- If y and z are in range, so is y + z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' + z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']
  | mul y z _ _ hy hz =>
    -- If y and z are in range, so is y * z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' * z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']


-- @@ L183-187 verbatim
/-- The range of ofCliffordAlgebra equals the top subalgebra (i.e., all of diracAlgebra). -/
lemma ofCliffordAlgebra_range_eq_top : ofCliffordAlgebra.range = ⊤ := by
  rw [eq_top_iff]
  intro x _
  exact mem_adjoin_imp_subtype_in_range x.val x.property


-- @@ L189-192 verbatim
/-- The homomorphism `ofCliffordAlgebra` is surjective. -/
theorem ofCliffordAlgebra_surjective : Function.Surjective ofCliffordAlgebra := by
  rw [← AlgHom.range_eq_top]
  exact ofCliffordAlgebra_range_eq_top


-- @@ L194-194 verbatim
end γ


-- @@ L196-196 verbatim
end diracRepresentation

-- @@ L197-197 verbatim
end spaceTime
