/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.E7.Minuscule.Carrier
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Coroot


-- @@ L11-35 verbatim
/-!
# Generation of the E₇ minuscule weight torus by root subgroups

The type-`E₇` minuscule carrier is defined using both its fourteen numbered simple root
subgroups and its rank-seven weight torus. This file proves that, on the underlying
base-changed lattice over any commutative ring, the torus is already contained in the elementary
group generated by the root subgroups.

The represented simple generators at each node form an `sl₂` triple by
`TauCeti.E7Minuscule.isSl2Triple_rep_serreRootGenerator`. The remaining concrete input is
supplied here: every row of the type-`E₇` Cartan matrix contains `-1`, so its entries have an
explicit integral linear combination equal to one. The generic coroot-generation theorem then
puts every coordinate cocharacter, and hence the whole weight torus, in the elementary group.

The conclusion concerns subgroups of the automorphism group of the base-changed admissible
lattice. Identifying those generated points with all points of the toral-closure group scheme is
a separate scheme-theoretic comparison.

## Main results

* `TauCeti.E7Minuscule.weightTorusSubgroup_le_elementarySubgroup`: the weight torus lies in the
  elementary subgroup over every commutative ring.
* `TauCeti.E7Minuscule.weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup`: adjoining the
  weight torus to all numbered root subgroups gives exactly the elementary subgroup.
-/


-- @@ L37-37 verbatim
public section


-- @@ L39-39 verbatim
open scoped Matrix TensorProduct


-- @@ L41-41 verbatim
universe v


-- @@ L43-43 verbatim
namespace TauCeti.E7Minuscule


-- @@ L45-45 verbatim
open TauCeti.DynkinType TauCeti.UniversalEnvelopingAlgebra


-- @@ L47-47 verbatim
attribute [local instance 100] LieRing.ofAssociativeRing

-- @@ L48-48 verbatim
attribute [local instance high] Algebra.toModule


-- @@ L50-50 verbatim
local notation "CM" => CartanMatrix.E 7

-- @@ L51-51 verbatim
local notation "rootGen" => TauCeti.serreRootGenerator CM

-- @@ L52-52 verbatim
local notation "cartanGen" => TauCeti.serreH ℚ CM

-- @@ L53-53 verbatim
local notation "rootWeight" => DynkinType.E7.rootGeneratorWeight DynkinType.valid_E7


-- @@ L55-56 verbatim
private def cartanNeighbor : Fin 7 → Fin 7 :=
  ![2, 3, 0, 1, 3, 4, 5]


-- @@ L58-59 verbatim
private def cartanBezout (i j : Fin 7) : ℤ :=
  if j = cartanNeighbor i then -1 else 0


-- @@ L61-63 verbatim
private theorem cartan_sum_mul_bezout (i : Fin 7) :
    ∑ j, CM i j * cartanBezout i j = 1 := by
  fin_cases i <;> decide


-- @@ L65-77 verbatim
private theorem rootWeight_sum_mul_bezout (i : Fin 7) :
    ∑ j, rootWeight (.inl i) j * cartanBezout i j = 1 := by
  have hweight (j : Fin 7) : rootWeight (.inl i) j = CM i j := by
    simpa only [DynkinType.rank_E7, DynkinType.cartanMatrix_E7] using
      (DynkinType.rootGeneratorWeight_inl (t := DynkinType.E7)
        (ht := DynkinType.valid_E7) i j)
  calc
    ∑ j, rootWeight (.inl i) j * cartanBezout i j =
        ∑ j, CM i j * cartanBezout i j := by
      apply Finset.sum_congr rfl
      intro j _
      rw [hweight j]
    _ = 1 := cartan_sum_mul_bezout i


-- @@ L79-85 verbatim
private theorem rootWeight_inr_eq_neg_inl (i : Fin 7) :
    rootWeight (.inr i) = -rootWeight (.inl i) := by
  simpa only [DynkinType.rank_E7] using
    (DynkinType.rootGeneratorWeight_inr_eq_neg_root_simpleIndex
      (t := DynkinType.E7) (ht := DynkinType.valid_E7) i).trans
    (congrArg Neg.neg (DynkinType.rootGeneratorWeight_inl_eq_root_simpleIndex
      (t := DynkinType.E7) (ht := DynkinType.valid_E7) i).symm)


-- @@ L87-101 verbatim
/-- Over every commutative ring, the type-`E₇` minuscule weight torus on the base-changed
admissible lattice is contained in the elementary group generated by the fourteen positive and
negative numbered simple root subgroups. -/
theorem weightTorusSubgroup_le_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubgroup lattice.toAddSubgroup
        latticeBasis e7MinusculeWeight A ≤
      kostantElementarySubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator A := by
  exact kostantTorusSubgroup_le_kostantElementarySubgroup
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
    isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
    Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl cartanBezout
    rootWeight_sum_mul_bezout A


-- @@ L103-118 verbatim
/-- Over every commutative ring, adjoining the type-`E₇` minuscule weight torus to all fourteen
numbered simple root subgroups does not enlarge their elementary subgroup. -/
theorem weightTorusSubsystemSubgroup_univ_eq_elementarySubgroup (A : CommAlgCat.{v} ℤ) :
    kostantTorusSubsystemSubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight Set.univ A =
      kostantElementarySubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator A := by
  exact
    kostantTorusSubsystemSubgroup_univ_eq_kostantElementarySubgroup
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis e7MinusculeWeight
      isCartanWeightVector_latticeBasis rootWeight lie_cartanGenerator_rootGenerator
      Sum.inl Sum.inr isSl2Triple_rep_serreRootGenerator rootWeight_inr_eq_neg_inl cartanBezout
      rootWeight_sum_mul_bezout A


-- @@ L120-120 verbatim
end TauCeti.E7Minuscule
