/-
Copyright (c) 2026 Yunzhou Xie and contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yunzhou Xie, Yichen Feng, Jujian Zhang, Yael Dillies
-/
module

public import Mathlib.RingTheory.SimpleRing.Defs
public import Mathlib.RingTheory.TwoSidedIdeal.Operations
public import Mathlib.RingTheory.TwoSidedIdeal.Kernel
import LeanPool.BrauerGroupNew.Mathlib.RingTheory.TwoSidedIdeal.Kernel
import Mathlib.Data.Fintype.BigOperators
import Mathlib.RingTheory.TwoSidedIdeal.BigOperators


-- @@ L15-19 verbatim
/-!
# LeanPool.BrauerGroupNew.TwoSidedIdeal

Imported Lean Pool material for `LeanPool.BrauerGroupNew.TwoSidedIdeal`.
-/


-- @@ L21-21 verbatim
@[expose] public section


-- @@ L23-23 verbatim
variable {M : Type*} [AddCommMonoid M] (r : AddCon M) {ι : Type*} (s : Finset ι)

-- @@ L24-24 verbatim
variable {R : Type*} [Ring R] (t : TwoSidedIdeal R)


-- @@ L26-26 verbatim
open MulOpposite


-- @@ L28-28 verbatim
namespace TwoSidedIdeal


-- @@ L30-30 verbatim
variable {s}


-- @@ L32-32 verbatim
variable (I : TwoSidedIdeal R)


-- @@ L34-34 verbatim
variable {R' : Type*} [Ring R']


-- @@ L36-54 verbatim
/-- The two-sided ideal generated by finite sums `xL * y * xR` with `y ∈ s`. -/
def span' (s : Set R) : TwoSidedIdeal R := .mk'
  {x | ∃ (ι : Type) (fin : Fintype ι) (xL : ι → R) (xR : ι → R) (y : ι → s),
    x = ∑ i : ι, xL i * y i * xR i}
  ⟨Empty, Fintype.instEmpty, Empty.elim, Empty.elim, Empty.elim, by simp⟩
  (by
    rintro _ _ ⟨na, fina, xLa, xRa, ya, rfl⟩ ⟨nb, finb, xLb, xRb, yb, rfl⟩
    refine ⟨na ⊕ nb, inferInstance, Sum.elim xLa xLb, Sum.elim xRa xRb, Sum.elim ya yb, by
      simp⟩)
  (by
    rintro _ ⟨n, finn, xL, xR, y, rfl⟩
    exact ⟨n, finn, -xL, xR, y, by simp⟩)
  (by
    rintro a _ ⟨n, finn, xL, xR, y, rfl⟩
    exact ⟨n, finn, a • xL, xR, y, by
      rw [Finset.mul_sum]; simp only [mul_assoc, Pi.smul_apply, smul_eq_mul]⟩)
  (by
    rintro _ b ⟨n, finn, xL, xR, y, rfl⟩
    exact ⟨n, finn, xL, fun x ↦ xR x * b, y, by simp [Finset.sum_mul, mul_assoc]⟩)


-- @@ L56-60 verbatim
lemma mem_span'_iff_exists_fin (s : Set R) (x : R) :
    x ∈ span' s ↔
    ∃ (ι : Type) (_ : Fintype ι) (xL : ι → R) (xR : ι → R) (y : ι → s),
    x = ∑ i : ι, xL i * (y i : R) * xR i := by
  simp only [span', mem_mk', Set.mem_ofPred_eq]


-- @@ L62-85 verbatim
lemma mem_span_iff_exists_fin (s : Set R) (x : R) :
    x ∈ span s ↔
    ∃ (ι : Type) (_ : Fintype ι) (xL : ι → R) (xR : ι → R) (y : ι → s),
    x = ∑ i : ι, xL i * (y i : R) * xR i := by
  suffices eq1 : span s = span' s by
    rw [eq1]
    simp only [span']
    simp_all
  rw [span, RingCon.ringConGen_eq]
  apply ringCon_injective
  refine sInf_eq_of_forall_ge_of_forall_gt_exists_lt ?_ ?_
  · rintro I (hI : ∀ a b, _ → _)
    suffices span' s ≤ .ofRingCon I by
      rw [ringCon_le_iff] at this
      exact this
    intro x h
    rw [mem_span'_iff_exists_fin] at h
    obtain ⟨n, finn, xL, xR, y, rfl⟩ := h
    rw [mem_iff]
    refine TwoSidedIdeal.finsetSum_mem _ _ _ fun i _ ↦ TwoSidedIdeal.mul_mem_right _ _ _
      (TwoSidedIdeal.mul_mem_left _ _ _ <| hI (y i) 0 (by simp))
  · rintro I hI
    exact ⟨(span' s).ringCon, fun a b H ↦ ⟨PUnit, inferInstance, fun _ ↦ 1, fun _ ↦ 1,
      fun _ ↦ ⟨a - b, by simp [H]⟩, by simp⟩, hI⟩


-- @@ L87-96 verbatim
lemma mem_span_ideal_iff_exists_fin (s : Ideal R) (x : R) :
    x ∈ span s ↔
    ∃ (ι : Type) (_ : Fintype ι) (xR : ι → R) (y : ι → s),
    x = ∑ i : ι, (y i : R) * xR i := by
  rw [mem_span_iff_exists_fin]
  fconstructor
  · rintro ⟨n, fin, xL, xR, y, rfl⟩
    exact ⟨n, fin, xR, fun i ↦ ⟨xL i * y i, s.mul_mem_left _ (y i).2⟩, by simp⟩
  · rintro ⟨n, fin, xR, y, rfl⟩
    exact ⟨n, fin, 1, xR, y, by simp⟩


-- @@ L98-99 verbatim
lemma coe_bot_set : ((⊥ : TwoSidedIdeal R) : Set R) = {0} := by
  simp_all


-- @@ L101-102 verbatim
lemma coe_top_set : ((⊤ : TwoSidedIdeal R) : Set R) = Set.univ := by
  simp_all


-- @@ L104-104 verbatim
section IsSimpleOrder


-- @@ L106-106 verbatim
universe u


-- @@ L108-108 verbatim
variable (A : Type u) [Ring A]


-- @@ L110-112 verbatim
instance [Nontrivial A] : Nontrivial (TwoSidedIdeal A) :=
⟨⊥, ⊤, by
      simp_all⟩


-- @@ L114-166 verbatim
lemma _root_.IsSimpleRing.iff_eq_zero_or_injective'
    (k : Type*) [CommRing k] [Algebra k A] [Nontrivial A] :
    IsSimpleRing A ↔
    ∀ ⦃B : Type u⦄ [Ring B] [Algebra k B] (f : A →ₐ[k] B),
      TwoSidedIdeal.ker f = ⊤ ∨ Function.Injective f := by
  classical
  constructor
  · intro so B _ _ f
    if hker : TwoSidedIdeal.ker f.toRingHom = ⊤
    then exact Or.inl hker
    else
      replace hker := so.1.2 (TwoSidedIdeal.ker f) |>.resolve_right hker
      rw [injective_iff_ker_eq_bot]
      exact Or.inr hker
  · intro h
    refine ⟨⟨fun I => ?_⟩⟩
    let : Algebra k I.ringCon.Quotient :=
    { algebraMap := I.ringCon.mk'.comp (algebraMap k A)
      smul a := Quotient.map' (fun b => a • b) fun x y (h : I.ringCon x y) =>
        show I.ringCon _ _ by
        rw [Algebra.smul_def, Algebra.smul_def]
        exact I.ringCon.mul (I.ringCon.refl (algebraMap k A a)) h
      commutes' := by
        simp only [RingHom.coe_comp, Function.comp_apply]
        intro a b
        induction b using Quotient.inductionOn' with
        | h b =>
          change _ * I.ringCon.mk' b = I.ringCon.mk' b * _
          simp only [← map_mul, Algebra.commutes a b]

      smul_def' := fun a b => by
        simp only [RingHom.coe_comp, Function.comp_apply]
        change Quotient.map' _ _ _ = _
        induction b using Quotient.inductionOn' with
        | h b =>
          change _ = _ * I.ringCon.mk' _
          simp only [Quotient.map'_mk'', ← map_mul, Algebra.smul_def]
          rfl }
    rcases @h I.ringCon.Quotient _ _ {I.ringCon.mk' with commutes' a := rfl } with h|h
    · right
      rw [eq_top_iff, le_iff]
      rintro x -
      simp only at h
      have mem : x ∈ TwoSidedIdeal.ker I.ringCon.mk' := by erw [h]; trivial
      simp_all
    · left
      rw [injective_iff_ker_eq_bot] at h
      rw [eq_bot_iff, le_iff]
      intro x hx
      have mem : x ∈ TwoSidedIdeal.ker I.ringCon.mk' := by
        simp_all
      erw [h] at mem
      exact mem


-- @@ L168-168 verbatim
end IsSimpleOrder


-- @@ L170-170 verbatim
end TwoSidedIdeal
