/-
Copyright (c) 2026 Chris Birkbeck. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import LeanPool.LeanModularForms.HeckeRIngs.AbstractHeckeRing.Ring
public import LeanPool.LeanModularForms.HeckeRIngs.GLn.DiagonalCosets
import LeanPool.LeanModularForms.HeckeRIngs.GLn.CoprimeMul
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.Data.EReal.Operations
import Mathlib.Tactic.Positivity.Finset
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded


-- @@ L17-40 verbatim
/-!
# Prime Decomposition of Hecke Ring Elements

p-adic decomposition of diagonal Hecke operators and the p-local Hecke subring RP.
Every `T(a₁,...,aₙ)` factors into a product of p-power `T`-elements via coprime splitting.

## Main definitions

* `ppowDiag` — p-power diagonal: entries are `p^(e i)`
* `pComponent` — extract the p-adic valuation of each diagonal entry
* `removePrime` — remove the p-component from a diagonal (p-free part)
* `RP` — the p-local Hecke subring generated by p-power T-elements

## Main results

* `divChain_ppow` — monotone exponents give a divisibility chain for p-power diagonals
* `T_elem_split_prime` — binary prime splitting: `T(a) = T(p-part) · T(p-free part)`
* `T_elem_ppow_mem_R_p` — p-power T-elements lie in RP
* `T_elem_mem_closure_ppow` — every T-element is in the subring generated by all p-local pieces

## References

* Shimura, *Introduction to the Arithmetic Theory of Automorphic Functions*, §3.2
-/


-- @@ L42-42 verbatim
@[expose] public section


-- @@ L44-44 verbatim
open Matrix Subgroup.Commensurable Pointwise HeckeRing DoubleCoset


-- @@ L46-46 verbatim
open scoped Pointwise


-- @@ L48-48 verbatim
namespace HeckeRing.GLn


-- @@ L50-50 verbatim
variable (n : ℕ)


-- @@ L52-52 verbatim
/-! ### p-power diagonals -/


-- @@ L54-54 verbatim
section PPow


-- @@ L56-58 verbatim
/-- p-power diagonal: entries are `p^(e i)`. -/
def ppowDiag (p : ℕ) (e : Fin n → ℕ) : Fin n → ℕ :=
  fun i => p ^ e i


-- @@ L60-62 verbatim
lemma ppowDiag_pos (p : ℕ) (hp : p.Prime) (e : Fin n → ℕ) :
    ∀ i, 0 < ppowDiag n p e i :=
  fun _ => pow_pos hp.pos _


-- @@ L64-67 verbatim
/-- DivChain for p-power diagonals when exponents are monotone. -/
lemma divChain_ppow (p : ℕ) (e : Fin n → ℕ) (hmono : Monotone e) :
    DivChain n (ppowDiag n p e) := fun i hi => by
  simpa only [ppowDiag] using Nat.pow_dvd_pow p (hmono (Fin.mk_le_mk.mpr (by omega)))


-- @@ L69-71 verbatim
/-- Extract the p-component of each entry in a positive diagonal. -/
def pComponent (p : ℕ) (a : Fin n → ℕ) : Fin n → ℕ :=
  fun i => (a i).factorization p


-- @@ L73-79 verbatim
/-- The p-component of a divisibility chain is monotone. -/
lemma pComponent_monotone (a : Fin n → ℕ)
    (ha_pos : ∀ i, 0 < a i) (ha : DivChain n a) (p : ℕ) :
    Monotone (pComponent n p a) := fun i j hij => by
  simp only [pComponent]
  exact (Nat.factorization_le_iff_dvd (ha_pos i).ne' (ha_pos j).ne').mpr
    (divChain_dvd (n := n) ha hij) p


-- @@ L81-81 verbatim
end PPow


-- @@ L83-83 verbatim
/-! ### Prime removal: extracting the p-free part -/


-- @@ L85-85 verbatim
section RemovePrime


-- @@ L87-90 verbatim
/-- Remove the p-component from each entry: `a_i ↦ a_i / p^{v_p(a_i)}`.
    This is the p-free part (ordCompl) of each diagonal entry. -/
noncomputable def removePrime (p : ℕ) (a : Fin n → ℕ) : Fin n → ℕ :=
  fun i => (a i) / p ^ ((a i).factorization p)


-- @@ L92-94 verbatim
lemma removePrime_pos (p : ℕ) (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) :
    ∀ i, 0 < removePrime n p a i :=
  fun i => Nat.ordCompl_pos p (ha_pos i).ne'


-- @@ L96-102 verbatim
/-- The p-free part preserves divisibility chains. -/
lemma removePrime_divChain (p : ℕ) (a : Fin n → ℕ) (ha : DivChain n a) :
    DivChain n (removePrime n p a) := fun i hi => by
  simp only [removePrime]
  obtain ⟨k, hk⟩ := ha i hi
  conv_rhs => rw [show a ⟨i + 1, hi⟩ = a ⟨i, by omega⟩ * k from hk]
  rw [Nat.ordCompl_mul]; exact dvd_mul_right _ _


-- @@ L104-109 verbatim
/-- Recovery: the pointwise product of p-part and p-free part equals the original. -/
lemma mul_ppow_remove_eq (p : ℕ) (a : Fin n → ℕ) :
    ppowDiag n p (pComponent n p a) * removePrime n p a = a := by
  funext i
  simp only [Pi.mul_apply, ppowDiag, removePrime, pComponent]
  exact Nat.ordProj_mul_ordCompl_eq_self (a i) p


-- @@ L111-111 verbatim
end RemovePrime


-- @@ L113-113 verbatim
/-! ### Coprimality of p-part and p-free part determinants -/


-- @@ L115-115 verbatim
section Coprimality


-- @@ L117-119 verbatim
/-- The determinant of a p-power diagonal is a power of `p`. -/
lemma prod_ppow (p : ℕ) (e : Fin n → ℕ) :
    ∏ i, (ppowDiag n p e) i = p ^ (∑ i, e i) := by simp only [ppowDiag, Finset.prod_pow_eq_pow_sum]


-- @@ L121-127 verbatim
/-- The p-part and p-free part determinants are coprime. -/
lemma prod_ppow_remove_coprime (p : ℕ) (hp : p.Prime)
    (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) :
    Nat.Coprime (∏ i, (ppowDiag n p (pComponent n p a) i))
               (∏ i, (removePrime n p a) i) := by
  rw [prod_ppow]; apply Nat.Coprime.pow_left
  exact Nat.Coprime.prod_right fun i _ => Nat.coprime_ordCompl hp (ha_pos i).ne'


-- @@ L129-129 verbatim
end Coprimality


-- @@ L131-131 verbatim
/-! ### Binary prime splitting theorem -/


-- @@ L133-133 verbatim
variable [NeZero n]


-- @@ L135-135 verbatim
section Splitting


-- @@ L137-139 verbatim
/-- TElem is determined by its diagonal, independent of the positivity/DivChain proofs. -/
lemma T_elem_congr_diag {a b : Fin n → ℕ} (h : a = b) :
    TElem a = TElem b := by subst h; rfl


-- @@ L141-158 verbatim
/-- Binary prime splitting: `T(a) = T(p-part) · T(p-free part)`.
    Every diagonal Hecke element factors into its p-power component
    and its p-free component, for any prime `p`. -/
theorem T_elem_split_prime (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i)
    (ha : DivChain n a) (p : ℕ) (hp : p.Prime) :
    TElem a =
    TElem (ppowDiag n p (pComponent n p a)) *
    TElem (removePrime n p a) := by
  have h_mul := T_diag_mul_coprime n
    (ppowDiag n p (pComponent n p a))
    (removePrime n p a)
    (ppowDiag_pos n p hp _)
    (removePrime_pos n p a ha_pos)
    (divChain_ppow n p _ (pComponent_monotone n a ha_pos ha p))
    (removePrime_divChain n p a ha)
    (prod_ppow_remove_coprime n p hp a ha_pos)
  rw [T_elem_congr_diag n (mul_ppow_remove_eq n p a).symm]
  exact h_mul.symm


-- @@ L160-160 verbatim
end Splitting


-- @@ L162-162 verbatim
/-! ### p-local Hecke subring -/


-- @@ L164-164 verbatim
section RpSubring


-- @@ L166-173 verbatim
/-- The p-local Hecke ring: subring generated by `TElem` with p-power entries.
    This is Shimura's `RP^{(n)}`. -/
noncomputable def RP (p : ℕ) (hp : p.Prime) : Subring (HeckeAlgebra n) :=
  -- `hp` records that `p` is prime; it is consumed here so the definition carries
  -- this provenance even though the subring closure does not use primality directly.
  let _ := hp
  Subring.closure { f | ∃ (e : Fin n → ℕ) (_hmono : Monotone e),
    f = TElem (ppowDiag n p e) }


-- @@ L175-178 verbatim
/-- A TElem with p-power entries lies in RP. -/
lemma T_elem_ppow_mem_R_p (p : ℕ) (hp : p.Prime) (e : Fin n → ℕ) (hmono : Monotone e) :
    TElem (ppowDiag n p e) ∈ RP n p hp :=
  Subring.subset_closure ⟨e, hmono, rfl⟩


-- @@ L180-184 verbatim
/-- The identity `T(1,...,1)` is in every RP (as the zero-exponent element). -/
lemma one_mem_R_p (p : ℕ) (hp : p.Prime) :
    TElem (fun _ : Fin n => 1) ∈ RP n p hp := by
  have h : TElem (fun _ : Fin n => 1) = TElem (ppowDiag n p (fun _ => 0)) := by congr
  rw [h]; exact T_elem_ppow_mem_R_p n p hp (fun _ => 0) monotone_const


-- @@ L186-186 verbatim
end RpSubring


-- @@ L188-188 verbatim
/-! ### Full prime factorization -/


-- @@ L190-190 verbatim
section FullFactorization


-- @@ L192-195 verbatim
/-- The Hecke elements represented by monotone prime-power diagonal matrices. -/
def ppowClosureSet (n : ℕ) [NeZero n] : Set (HeckeAlgebra n) :=
  { f | ∃ (p : ℕ) (_hp : p.Prime) (e : Fin n → ℕ) (_hmono : Monotone e),
    f = TElem (ppowDiag n p e) }


-- @@ L197-200 verbatim
omit [NeZero n] in
private lemma prod_pos_of_pos (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) :
    0 < ∏ i, a i :=
  Finset.prod_pos (fun i _ => ha_pos i)


-- @@ L202-264 verbatim
/-- Every `TElem` is in the subring generated by all p-local T-elements. -/
theorem T_elem_mem_closure_ppow (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) (ha : DivChain n a) :
    TElem a ∈ Subring.closure (ppowClosureSet n) := by
  suffices ∀ (m : ℕ) (a : Fin n → ℕ) (ha_pos : ∀ i, 0 < a i) (ha : DivChain n a),
      (∏ i, a i).factorization.support.card ≤ m →
      TElem a ∈ Subring.closure (ppowClosureSet n) from
    this _ a ha_pos ha le_rfl
  intro m
  induction m with
  | zero =>
    intro a ha_pos ha hcard
    have h_all_one : ∀ i, a i = 1 := by
      intro i
      have h_dvd : a i ∣ ∏ i, a i := Finset.dvd_prod_of_mem _ (Finset.mem_univ i)
      have h_det : ∏ i, a i = 1 := by
        have h_supp : (∏ i, a i).factorization.support = ∅ :=
          Finset.card_eq_zero.mp (Nat.le_zero.mp hcard)
        have := Nat.prod_factorization_pow_eq_self (prod_pos_of_pos n a ha_pos).ne'
        rw [Finsupp.prod, h_supp, Finset.prod_empty] at this
        exact this.symm
      exact Nat.eq_one_of_dvd_one (h_det ▸ h_dvd)
    have h_eq : a = fun _ => 1 := funext h_all_one
    subst h_eq
    have h_ppow : TElem (fun _ : Fin n => 1) = TElem (ppowDiag n 2 (fun _ => 0)) := by congr
    rw [h_ppow]; exact Subring.subset_closure ⟨2, Nat.prime_two, _, monotone_const, rfl⟩
  | succ m ih =>
    intro a ha_pos ha hcard
    by_cases h_empty : (∏ i, a i).factorization.support = ∅
    · exact ih a ha_pos ha (by rw [Finset.card_eq_zero.mpr h_empty]; exact Nat.zero_le _)
    obtain ⟨p, hp_mem⟩ := Finset.nonempty_of_ne_empty h_empty
    have hp : p.Prime := by
      rw [Nat.support_factorization] at hp_mem; exact Nat.prime_of_mem_primeFactors hp_mem
    rw [T_elem_split_prime n a ha_pos ha p hp]
    apply Subring.mul_mem
    · exact Subring.subset_closure
        ⟨p, hp, pComponent n p a, pComponent_monotone n a ha_pos ha p, rfl⟩
    · have h_ssubset : (∏ i, (removePrime n p a) i).factorization.support ⊂
          (∏ i, a i).factorization.support := by
        constructor
        · intro q hq
          rw [Finsupp.mem_support_iff] at hq ⊢
          intro h_zero
          apply hq
          have h_dvd : ∏ i, (removePrime n p a) i ∣ ∏ i, a i :=
            Finset.prod_dvd_prod_of_dvd _ _ fun i _ => Nat.ordCompl_dvd (a i) p
          have h_le := (Nat.factorization_le_iff_dvd
            (prod_pos_of_pos n _ (removePrime_pos n p a ha_pos)).ne'
            (prod_pos_of_pos n a ha_pos).ne').mpr h_dvd q
          omega
        · intro h_sup
          have hp_in : p ∈ (∏ i, (removePrime n p a) i).factorization.support :=
            h_sup hp_mem
          rw [Finsupp.mem_support_iff] at hp_in
          apply hp_in
          rw [Nat.factorization_prod (fun i _ => (removePrime_pos n p a ha_pos i).ne'),
            Finset.sum_apply']
          apply Finset.sum_eq_zero
          intro i _
          simp only [removePrime]
          rw [Nat.factorization_ordCompl]
          exact Finsupp.erase_same
      apply ih _ (removePrime_pos n p a ha_pos) (removePrime_divChain n p a ha)
      have h_lt := Finset.card_lt_card h_ssubset; omega


-- @@ L266-266 verbatim
end FullFactorization


-- @@ L268-268 verbatim
/-! ### Generation by R_p's -/


-- @@ L270-270 verbatim
section Generation


-- @@ L272-277 verbatim
/-- Every element of the Hecke algebra is in the subring generated by all p-local pieces. -/
theorem HeckeAlgebra_generated_by_R_p :
    (⊤ : Subring (HeckeAlgebra n)) ≤ Subring.closure (ppowClosureSet n) := by
  intro f _; obtain ⟨S, c, hf⟩ := T_diag_span n f; rw [hf]
  exact Subring.sum_mem _ fun s _ =>
    Subring.zsmul_mem _ (T_elem_mem_closure_ppow n s.1.1 s.1.2.1 s.1.2.2) _


-- @@ L279-279 verbatim
end Generation


-- @@ L281-281 verbatim
end HeckeRing.GLn
