/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.Lomega1omega.Entailment
public import LeanPool.InfinitaryLogic.Methods.GeneratedSublanguage
import LeanPool.InfinitaryLogic.Methods.Interpolation.CraigSublanguage
import LeanPool.InfinitaryLogic.Methods.Interpolation.MalitzRelational
import LeanPool.InfinitaryLogic.Methods.SymbSublangExpansion

-- @@ L13-24 verbatim
/-!
# Malitz interpolation over an arbitrary relational language (issue #15)

Removes the countability hypothesis from `malitz_interpolation_relational_countable` by passing to
the sublanguage generated by the two roots' own symbols — which is countable because a single
`Lω₁ω` sentence mentions only countably many — applying the core there, and mapping the interpolant
back along the inclusion.

The quantifier class survives both moves: `universalSigned_restrictSymbols` carries `IsUniversal`
into the sublanguage, and `universalSigned_mapLanguage` carries it back out.  This is the payoff of
proving those as *exact* equivalences rather than one-way implications.
-/


-- @@ L26-26 verbatim
@[expose] public section


-- @@ L28-28 verbatim
namespace FirstOrder.Language


-- @@ L30-30 verbatim
open FirstOrder BoundedFormulaω


-- @@ L32-32 verbatim
variable {L : Language.{0, 0}}


-- @@ L34-75 verbatim
/-- **Malitz interpolation for `L_ω₁ω`** (relational languages, arbitrary cardinality).

An entailment with **universal** consequent has a **universal** interpolant, whose function and
relation symbols occur in both sides.

This is López–Escobar / Malitz's Theorem 4.5 in the function-free case: the interpolant may be taken
in the same quantifier class as the consequent. -/
theorem malitz_interpolation [L.IsRelational] (φ ψ : L.Sentenceω) (hψ : IsUniversal ψ)
    (h : Sentenceω.Entails φ ψ) :
    ∃ θ : L.Sentenceω,
      IsUniversal θ ∧
      θ.functionsIn ⊆ φ.functionsIn ∩ ψ.functionsIn ∧
      θ.relationsIn ⊆ φ.relationsIn ∩ ψ.relationsIn ∧
      Sentenceω.Entails φ θ ∧ Sentenceω.Entails θ ψ := by
  set F : Set (Σ n, L.Functions n) := φ.functionsIn ∪ ψ.functionsIn with hF
  set R : Set (Σ n, L.Relations n) := φ.relationsIn ∪ ψ.relationsIn with hR
  have hRc : R.Countable := (φ.relationsIn_countable).union (ψ.relationsIn_countable)
  have h₁F : φ.functionsIn ⊆ F := Set.subset_union_left
  have h₁R : φ.relationsIn ⊆ R := Set.subset_union_left
  have h₂F : ψ.functionsIn ⊆ F := Set.subset_union_right
  have h₂R : ψ.relationsIn ⊆ R := Set.subset_union_right
  have hE' : Sentenceω.Entails (φ.restrictSymbols h₁F h₁R) (ψ.restrictSymbols h₂F h₂R) :=
    entails_restrictSymbols_singleton F R φ ψ h₁F h₁R h₂F h₂R h
  have : Countable (Σ n, (symbSublang (L := L) F R).Relations n) :=
    symbSublang_rel_countable F hRc
  -- the consequent stays universal inside the sublanguage
  have hψ' : IsUniversal (ψ.restrictSymbols h₂F h₂R) :=
    (BoundedFormulaω.universalSigned_restrictSymbols true ψ h₂F h₂R).mpr hψ
  obtain ⟨θ', hθ'U, hθ'F, hθ'R, hE1', hE2'⟩ :=
    malitz_interpolation_relational_countable (φ.restrictSymbols h₁F h₁R)
      (ψ.restrictSymbols h₂F h₂R) hψ' hE'
  refine ⟨θ'.mapLanguage (symbSublangIncl F R), ?_, ?_, ?_, ?_, ?_⟩
  · -- and it stays universal on the way back out
    exact (universalSigned_mapLanguage (symbSublangIncl F R) true θ').mpr hθ'U
  · exact Set.subset_inter
      (functionsIn_mapLanguage_incl_subset F R φ h₁F h₁R θ' (hθ'F.trans Set.inter_subset_left))
      (functionsIn_mapLanguage_incl_subset F R ψ h₂F h₂R θ' (hθ'F.trans Set.inter_subset_right))
  · exact Set.subset_inter
      (relationsIn_mapLanguage_incl_subset F R φ h₁F h₁R θ' (hθ'R.trans Set.inter_subset_left))
      (relationsIn_mapLanguage_incl_subset F R ψ h₂F h₂R θ' (hθ'R.trans Set.inter_subset_right))
  · exact entails_mapLanguage_restrictSymbols_left F R φ h₁F h₁R θ' hE1'
  · exact entails_mapLanguage_restrictSymbols_right F R ψ h₂F h₂R θ' hE2'


-- @@ L77-77 verbatim
end FirstOrder.Language
