/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle
(https://aristotle.harmonic.fun).
-/
module

public import LeanPool.KrafftSieve.SelbergWeights
public import LeanPool.KrafftSieve.Basic
public import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt



-- @@ L22-28 verbatim
/-!
# Sieve Variance

This module defines the mean density $\mu$ and the physical variance $\sigma^2$
of the survivor distribution in the Krafft Sieve, and proves Parseval's identity
to relate the variance to the Fourier coefficients.
-/


-- @@ L30-30 verbatim
@[expose] public section


-- @@ L32-32 verbatim
namespace KrafftSieve


-- @@ L34-34 verbatim
open scoped BigOperators

-- @@ L35-35 verbatim
open scoped Real

-- @@ L36-36 verbatim
open scoped Nat

-- @@ L37-37 verbatim
open scoped Pointwise


-- @@ L39-39 verbatim
noncomputable section


-- @@ L41-46 verbatim
/--
Definition of N as the cardinality of A.
Let $N = |A| = \prod_{i=1}^w (p_i - 2)$ be the total number
of surviving residues.
-/
def N (n : ℕ) (r : Fin (w n) → ℕ) : ℕ := (A n r).card


-- @@ L48-53 verbatim
/--
Definition of the global mean density μ.
Define the global mean density $\mu = \frac{N}{q}$.
-/
noncomputable def μ (n : ℕ) (r : Fin (w n) → ℕ) : ℝ :=
  (N n r : ℝ) / (q n : ℝ)


-- @@ L55-67 verbatim
/--
Definition of the Discrete Fourier Transform fHat.
Define the Discrete Fourier Transform of $f$ at frequency
$h \in \mathbb{Z}/q\mathbb{Z}$ as:
  $$ \hat{f}(h) = \frac{1}{q} \sum_{x=0}^{q-1}
       f(x) e^{-2\pi i h x / q} $$
-/
noncomputable def fHat (n : ℕ) (r : Fin (w n) → ℕ)
    (h : ZMod (q n)) : ℂ :=
  haveI : NeZero (q n) := ⟨Finset.prod_ne_zero_iff.mpr fun _ hp =>
    Nat.Prime.ne_zero <| Finset.mem_filter.mp hp |>.2.2⟩
  (1 / (q n : ℂ)) * ∑ x : ZMod (q n),
    (f n r x) * Complex.exp (-2 * Real.pi * Complex.I * (h.val * x.val : ℕ) / (q n : ℂ))


-- @@ L69-78 verbatim
/--
Definition of the physical variance sigmaSq.
Define the physical variance of the survivor distribution as:
  $$ \sigma^2 = \frac{1}{q}
       \sum_{x=0}^{q-1} (f(x) - \mu)^2 $$
-/
noncomputable def sigmaSq (n : ℕ) (r : Fin (w n) → ℕ) : ℝ :=
  haveI : NeZero (q n) := ⟨Finset.prod_ne_zero_iff.mpr fun _ hp =>
    Nat.Prime.ne_zero <| Finset.mem_filter.mp hp |>.2.2⟩
  (1 / (q n : ℝ)) * ∑ x : ZMod (q n), (f n r x - μ n r) ^ 2


-- @@ L80-93 verbatim
/--
The Fourier coefficient at 0 is equal to the mean density μ.
-/
theorem f_hat_zero_eq_mu (n : ℕ) (r : Fin (w n) → ℕ) :
    fHat n r 0 = μ n r := by
  simp only [fHat, one_div, neg_mul, ZMod.val_zero, zero_mul, CharP.cast_eq_zero, mul_zero,
    zero_div, Complex.exp_zero, mul_one, μ, Complex.ofReal_div, Complex.ofReal_natCast]
  rw [ inv_mul_eq_div, div_eq_div_iff ] <;>
    norm_cast <;> norm_num [ q_ne_zero ]
  · unfold f N; aesop
  · exact Finset.prod_ne_zero_iff.mpr fun p hp =>
      Nat.Prime.ne_zero <| Finset.mem_filter.mp hp |>.2.2
  · exact Finset.prod_ne_zero_iff.mpr fun p hp =>
      Nat.Prime.ne_zero <| Finset.mem_filter.mp hp |>.2.2


-- @@ L95-141 verbatim
/--
Orthogonality of the exponential sum.
-/
lemma sum_exp_orthogonality (n : ℕ) (k : ZMod (q n)) :
    ∑ h : ZMod (q n), Complex.exp (2 * Real.pi * Complex.I * h.val * k.val / (q n : ℂ)) =
      if k = 0 then (q n : ℂ) else 0 := by
  rw [ ← Finset.sum_subset
    ( Finset.subset_univ ( Finset.image ( fun x : ℕ => ↑x : ℕ → ZMod ( q n ) )
        ( Finset.range ( q n ) ) ) ) ]
  · rw [ Finset.sum_image ] <;> norm_num
    · split_ifs
      · simp_all
      · -- Let $z = e^{2 \pi i k / q}$.
        -- Since $k \neq 0$,
        -- $z$ is a primitive $q$-th root of unity.
        set z : ℂ := Complex.exp (2 * Real.pi * Complex.I * k.val / (q n : ℂ))
        have hz : z ≠ 1 := by
          rw [ Ne.eq_def, Complex.exp_eq_one_iff ]; field_simp
          rintro ⟨ m, hm ⟩
          rw [ div_eq_iff ] at hm <;> norm_cast at * <;> simp_all only [ZMod.natCast_val]
          · replace hm := congr_arg ( fun x : ℤ => x : ℤ → ZMod ( q n ) ) hm
            simp_all
          · exact Nat.ne_of_gt <| Finset.prod_pos fun p hp =>
              Nat.Prime.pos <| Finset.mem_filter.mp hp |>.2.2
        -- The sum of a geometric series with
        -- ratio $z$ is zero when $z \neq 1$.
        have h_geo_series : ∑ x ∈ Finset.range (q n), z ^ x = 0 := by
          rw [ geom_sum_eq ] <;> norm_num [ hz ]
          exact Or.inl ( by
            rw [ ← Complex.exp_nat_mul, mul_comm, Complex.exp_eq_one_iff.mpr ⟨ k.val, by
              push_cast; ring_nf
              norm_num [ show q n ≠ 0 from Finset.prod_ne_zero_iff.mpr
                fun p hp => Nat.Prime.ne_zero <| Finset.mem_filter.mp hp |>.2.2 ] ⟩ ]
            ring )
        convert h_geo_series using 2; ring_nf
        rw [ ← Complex.exp_nat_mul ]
        rw [ Nat.mod_eq_of_lt ( Finset.mem_range.mp ‹_› ) ]; ring_nf
        simp +decide [ mul_assoc, mul_comm, mul_left_comm ]
    · exact fun x hx y hy hxy =>
        Nat.mod_eq_of_lt hx.out ▸ Nat.mod_eq_of_lt hy.out ▸ by
          rw [ ZMod.natCast_eq_natCast_iff ] at hxy
          exact hxy
  · simp +zetaDelta only [Finset.mem_univ, Finset.mem_image, Finset.mem_range, not_exists,
    not_and, ZMod.natCast_val, Complex.exp_ne_zero, imp_false, not_forall,
    Decidable.not_not, forall_const] at *
    intro x
    exact ⟨ x.val, by exact x.val_lt, by exact ZMod.natCast_zmod_val x ⟩


-- @@ L143-150 verbatim
/--
Orthogonality of the exponential sum over $x$.
-/
lemma orthogonality_x (n : ℕ) (k : ZMod (q n)) :
    ∑ x : ZMod (q n), Complex.exp (2 * Real.pi * Complex.I * k.val * x.val / (q n : ℂ)) =
      if k = 0 then (q n : ℂ) else 0 := by
  convert sum_exp_orthogonality n k using 1
  exact Finset.sum_congr rfl fun x _ => by ring_nf


-- @@ L152-170 verbatim
/--
Application of orthogonality to simplify the double
sum of function values.
-/
lemma sum_orthogonality_application (n : ℕ) (r : Fin (w n) → ℕ) :
    ∑ x : ZMod (q n), ∑ y : ZMod (q n), (f n r x : ℂ) * (f n r y : ℂ) *
      ∑ h : ZMod (q n), Complex.exp (2 * Real.pi * Complex.I * h.val * (y - x).val / (q n : ℂ)) =
    (q n : ℂ) * ∑ x : ZMod (q n), (f n r x : ℂ)^2 := by
  -- Apply the orthogonality result to simplify
  -- the inner sum over $h$.
  have h_inner : ∀ x y : ZMod (q n),
      ∑ h : ZMod (q n), Complex.exp (2 * Real.pi * Complex.I * h.val * (y - x).val / (q n : ℂ)) =
        if y = x then (q n : ℂ) else 0 := by
    intro x y
    split_ifs with h
    · simp_all
    have := sum_exp_orthogonality n ( y - x )
    simp_all +decide [ sub_eq_iff_eq_add ]
  simp_all +decide [ sq, mul_assoc, mul_comm, Finset.mul_sum _ _ _ ]


-- @@ L172-232 verbatim
/--
Expansion of the squared magnitude of a single Fourier coefficient.
-/
lemma f_hat_normSq_expansion (n : ℕ) (r : Fin (w n) → ℕ) (h : ZMod (q n)) :
    Complex.normSq (fHat n r h) =
    (1 / (q n : ℂ)^2) * ∑ x : ZMod (q n), ∑ y : ZMod (q n), (f n r x : ℂ) * (f n r y : ℂ) *
      Complex.exp (2 * Real.pi * Complex.I * h.val * (y - x).val / (q n : ℂ)) := by
  -- By definition of $fHat$, we have:
  have h_def : fHat n r h =
      (1 / (q n : ℂ)) * ∑ x : ZMod (q n), (f n r x : ℂ) *
        Complex.exp (-2 * Real.pi * Complex.I * (h.val * x.val : ℕ) / (q n : ℂ)) := by
    exact rfl
  -- By definition of $fHat$, we have
  -- $\overline{\hat{f}(h)} =
  --   \frac{1}{q} \sum_y f(y) e^{2\pi i h y / q}$.
  have h_conj : starRingEnd ℂ (fHat n r h) =
      (1 / (q n : ℂ)) * ∑ y : ZMod (q n), (f n r y : ℂ) *
        Complex.exp (2 * Real.pi * Complex.I * (h.val * y.val : ℕ) / (q n : ℂ)) := by
    simp_all +decide only [one_div, neg_mul, Nat.cast_mul, ZMod.natCast_val, Complex.ext_iff,
      Complex.mul_re, Complex.inv_re, Complex.natCast_re, Complex.normSq_natCast,
      div_self_mul_self', Complex.re_sum, Complex.ofReal_re, Complex.exp_re,
      Complex.div_natCast_re, Complex.neg_re, Complex.re_ofNat, Complex.im_ofNat,
      Complex.ofReal_im, mul_zero, sub_zero, Complex.I_re, Complex.mul_im, zero_mul, add_zero,
      Complex.I_im, mul_one, sub_self, zero_sub, neg_neg, Complex.div_natCast_im, Complex.neg_im,
      zero_add, Complex.exp_im, Complex.inv_im, Complex.natCast_im, neg_zero, zero_div,
      Complex.im_sum, Complex.conj_re, mul_eq_mul_left_iff, inv_eq_zero, Nat.cast_eq_zero,
      Complex.conj_im]
    norm_num [ neg_div, mul_div_assoc, Real.cos_neg, Real.sin_neg ]
    have h_exp : ∀ x : ZMod (q n),
        Complex.re (h.val * x.val) = h.val * x.val ∧ Complex.im (h.val * x.val) = 0 := by
      norm_cast; aesop
    aesop
  convert congr_arg₂ ( · * · ) h_def h_conj using 1 <;> ring_nf
  · norm_num [ Complex.mul_conj, Complex.normSq_eq_norm_sq ]
  · -- By combining the exponents, we can see that the LHS and RHS are equal.
    have h_exp : ∀ x y : ZMod (q n),
        Complex.exp ((q n : ℂ)⁻¹ * Real.pi * Complex.I * h.val * (y - x).val * 2) =
        Complex.exp ((q n : ℂ)⁻¹ * Real.pi * Complex.I * h.val * y.val * 2) *
        Complex.exp (-(q n : ℂ)⁻¹ * Real.pi * Complex.I * h.val * x.val * 2) := by
      intro x y; rw [ ← Complex.exp_add ]
      ring_nf
      rw [ Complex.exp_eq_exp_iff_exists_int ]
      -- Since $y$ and $x$ are elements of $ZMod (q n)$, their values are integers
      -- modulo $q n$. Therefore, $(y - x).val$ is equal to $y.val - x.val$ plus
      -- some multiple of $q n$.
      obtain ⟨k, hk⟩ : ∃ k : ℤ, (y - x).val = y.val - x.val + k * q n := by
        have h_mod : (y - x).val ≡ y.val - x.val [ZMOD q n] := by
          simp +decide only [ZMod.natCast_val, ← ZMod.intCast_eq_intCast_iff, ZMod.intCast_cast,
            dvd_refl, ZMod.cast_sub, ZMod.cast_id', id_eq, Int.cast_sub]
        exact h_mod.symm.dvd.imp fun k hk => by linarith
      use k * h.val
      push_cast [ ← @Int.cast_inj ℂ ] at *
      rw [ hk ]; ring_nf
      rw [ mul_inv_cancel₀ ( Nat.cast_ne_zero.mpr <| ne_of_gt <|
        Finset.prod_pos fun p hp => Nat.Prime.pos <| Finset.mem_filter.mp hp |>.2.2 ) ]
      ring
    simp +decide only [mul_assoc, Finset.mul_sum _ _ _, Finset.sum_mul]
    exact Finset.sum_comm.trans
      ( Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by
        push_cast [ ← mul_assoc, ← Complex.exp_add ]
        rw [ h_exp ]; ring_nf )


-- @@ L234-267 verbatim
/--
Standard Parseval's Identity: The sum of the squared magnitudes of the Fourier coefficients equals
the average of the squared function values.
-/
lemma parseval_standard (n : ℕ) (r : Fin (w n) → ℕ) :
    ∑ h : ZMod (q n), Complex.normSq (fHat n r h) = (1 / (q n : ℝ)) *
      ∑ x : ZMod (q n), (f n r x)^2 := by
  -- Applying the expansion for each term:
  have h_sum :
      ∑ h : ZMod (q n), Complex.normSq (fHat n r h) =
      (1 / (q n : ℂ)^2) * ∑ x : ZMod (q n), ∑ y : ZMod (q n),
      (f n r x : ℂ) * (f n r y : ℂ) * ∑ h : ZMod (q n),
        Complex.exp (2 * Real.pi * Complex.I * h.val * (y - x).val / (q n : ℂ)) := by
    -- Apply the norm squared expansion to each
    -- term in the sum.
    have h_expand : ∀ h : ZMod (q n),
        Complex.normSq (fHat n r h) = (1 / (q n : ℂ)^2) * ∑ x : ZMod (q n), ∑ y : ZMod (q n),
          (f n r x : ℂ) * (f n r y : ℂ) * Complex.exp
            (2 * Real.pi * Complex.I * h.val * (y - x).val / (q n : ℂ)) :=
      fun h ↦ f_hat_normSq_expansion n r h
    simp +zetaDelta at *
    simp +decide only [h_expand, Finset.mul_sum]
    ring_nf
    exact Finset.sum_comm.trans ( Finset.sum_congr rfl fun _ _ => Finset.sum_comm.trans
      ( Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => by ring ) )
  -- Substitute the result from h_double_sum
  -- into h_sum.
  have h_final : ∑ h : ZMod (q n), Complex.normSq (fHat n r h) =
      (1 / (q n : ℂ)^2) * (q n : ℂ) * ∑ x : ZMod (q n), (f n r x : ℂ)^2 := by
    rw [ h_sum, sum_orthogonality_application ]
    ring
  convert h_final using 1
  norm_num [ sq, mul_assoc ]; ring_nf
  norm_num [ ← Complex.ofReal_inj ]


-- @@ L269-281 verbatim
/--
Expansion of the variance formula.
-/
lemma variance_expansion (n : ℕ) (r : Fin (w n) → ℕ) :
    sigmaSq n r = (1 / (q n : ℝ)) * ∑ x : ZMod (q n), (f n r x)^2 - (μ n r)^2 := by
  unfold sigmaSq μ
  rw [ show f n r = fun x => if x ∈ A n r then 1 else 0 from funext fun x => rfl ]
  norm_num [ Finset.sum_ite, Finset.filter_mem_eq_inter, Finset.filter_not ]
  ring_nf
  norm_num [ Finset.sum_add_distrib, Finset.mul_sum _ _ _, Finset.sum_mul ]
  ring_nf!
  by_cases h : q n = 0 <;> simp_all +decide [ pow_three, sq, mul_assoc ]
  ring


-- @@ L283-296 verbatim
/--
Parseval's Identity for the Sieve: The variance of the
indicator function f is strictly equal to the sum of the
squared magnitudes of its non-zero Fourier coefficients.
-/
theorem parseval_identity (n : ℕ) (r : Fin (w n) → ℕ) :
    sigmaSq n r = ∑ h : ZMod (q n), if h = 0 then 0 else Complex.normSq (fHat n r h) := by
  rw [ Finset.sum_ite, Finset.filter_ne' ]
  have := parseval_standard n r
  have := variance_expansion n r
  simp_all +decide only [one_div, sub_eq_add_neg, Finset.sum_const_zero, Finset.mem_univ,
    Finset.sum_erase_eq_sub, zero_add, add_right_inj, neg_inj]
  rw [ f_hat_zero_eq_mu ]
  norm_num [ Complex.normSq ]; ring


-- @@ L298-309 verbatim
/--
The primorial $q$ is odd.
-/
lemma q_odd (n : ℕ) : Odd (q n) := by
  -- Each prime $p$ in $\mathcal{P}_n$ is odd, and
  -- the product of odd numbers is odd.
  have h_odd_primes : ∀ p ∈ primeWindow n, Odd p :=
    fun p hp => Nat.Prime.odd_of_ne_two ( Finset.mem_filter.mp hp |>.2.2 )
      ( by linarith [ Finset.mem_filter.mp hp |>.2.1 ] )
  exact Nat.odd_iff.mpr ( Finset.prod_nat_mod _ _ _ ▸ by
    rw [ Finset.prod_eq_one fun x hx => Nat.odd_iff.mp ( h_odd_primes x hx ) ]
    norm_num )


-- @@ L311-347 verbatim
/--
Conjugate symmetry of the Fourier transform for
real-valued functions.
-/
lemma f_hat_conj_symm (n : ℕ) (r : Fin (w n) → ℕ) (h : ZMod (q n)) :
    fHat n r (-h) = starRingEnd ℂ (fHat n r h) := by
  unfold fHat
  -- Since $(-h).val \equiv -h.val \pmod{q}$,
  -- we can replace $(-h).val$ with $-h.val$
  -- in the exponent.
  have h_exp : ∀ x : ZMod (q n),
      Complex.exp (-2 * Real.pi * Complex.I * ((-h).val * x.val) / (q n : ℂ)) =
      Complex.exp (2 * Real.pi * Complex.I * (h.val * x.val) / (q n : ℂ)) := by
    have h_exp : (-h).val ≡ -h.val [ZMOD q n] := by
      simp +decide [ ← ZMod.intCast_eq_intCast_iff ]
    obtain ⟨ k, hk ⟩ := h_exp.symm.dvd
    intro x
    rw [ Complex.exp_eq_exp_iff_exists_int ]
    use -k * x.val
    push_cast [ ← @Int.cast_inj ℂ ] at *
    simp_all +decide only [ZMod.natCast_val, sub_neg_eq_add, mul_comm, mul_neg, neg_mul,
      mul_assoc, div_eq_mul_inv, mul_left_comm]
    ring_nf
    field_simp
    rw [ div_sub', mul_div_assoc' ]
    · grind
    · exact Nat.cast_ne_zero.mpr <| Nat.ne_of_gt <| Finset.prod_pos fun p hp =>
        Nat.Prime.pos <| Finset.mem_filter.mp hp |>.2.2
  simp +zetaDelta only [neg_mul, ZMod.natCast_val, one_div, Nat.cast_mul, map_mul, map_inv₀,
    map_natCast, map_sum, Complex.conj_ofReal, mul_eq_mul_left_iff, inv_eq_zero,
    Nat.cast_eq_zero] at *
  left; congr; ext x; rw [ h_exp ]
  rw [ Complex.ext_iff ]
  norm_num [ Complex.exp_re, Complex.exp_im, neg_div ]
  ring_nf
  rw [ ZMod.cast_eq_val, ZMod.cast_eq_val ]
  norm_cast; aesop


-- @@ L349-367 verbatim
/--
Harmonic Variance Lower Bound: For any non-zero
frequency $h$, the variance is at least twice the squared
magnitude of the Fourier coefficient at $h$.
-/
lemma harmonic_variance_lower_bound (n : ℕ) (r : Fin (w n) → ℕ) (h : ZMod (q n))
    (h_ne_zero : h ≠ 0) : sigmaSq n r ≥ 2 * Complex.normSq (fHat n r h) := by
  have := f_hat_conj_symm n r h
  rw [ parseval_identity ]
  rw [ ← Finset.add_sum_erase _ _ ( Finset.mem_univ h ) ]
  rw [ ← Finset.add_sum_erase _ _
    ( Finset.mem_erase.mpr ⟨ ?_, Finset.mem_univ ( -h ) ⟩ ) ] <;>
    norm_num [ h_ne_zero, this ]
  · linarith [ show 0 ≤ ∑ x ∈ (Finset.univ.erase h).erase (-h),
        if x = 0 then 0 else Complex.normSq ( fHat n r x ) from
      Finset.sum_nonneg fun x hx => by
        split_ifs <;> norm_num [ Complex.normSq_nonneg ] ]
  · intro h_eq; have := q_odd n
    simp_all +decide [ neg_eq_iff_add_eq_zero ]


-- @@ L369-369 verbatim
end


-- @@ L371-371 verbatim
end KrafftSieve
