/-
Copyright (c) 2026 Judith Ludwig, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Judith Ludwig, Christian Merten
-/
module

public import LeanPool.BruhatTits.Lattice.Basic
public import Mathlib.RingTheory.DiscreteValuationRing.Basic
import LeanPool.BruhatTits.Utils.Misc
import LeanPool.BruhatTits.Utils.ValuationRings
import Mathlib.RingTheory.Localization.Module


-- @@ L14-39 verbatim
/-!
# Basic constructions and operations on lattices

In this file we provide the infrastructure for going back and forth between
`K`-bases of `Fin 2 → K` and `R`-lattices. Also we provide operations
on bases, such as twisting by units of `K` and permutations of the basis.

The main definition is `Basis.toLattice` which, given a basis `b` of `Fin 2 → K` constructs
the lattice spanned by the entries of `b`. The API is built around this definition in the following
sense: Every operation on lattices comes with API lemmas showing the interaction
with `Basis.toLattice`, reducing it to an operation on bases. In a general situation,
try to use the induction principle of equality (i.e. the `subst` tactic) to replace
arbitrary lattices with `b.toLattice` for a suitable basis.

Most constructions work for an arbitrary subring `R` of a field `K`.

## Main definitions

- `Basis.toSubmodule`: Given a `K`-basis `b` of `ι → K`, this is the `R`-submodule of `ι → K`
  spanned by `K`. This is a lattice (`toSubmodule_isLattice`).
- `Basis.toLattice`: `Basis.toSubmodule` as a lattice. See the docstring for more details.
- `Basis.twist`: Let `f` be a tuple of integers and let `ϖ` be a uniformizer. The twist of a basis
  `b` by `f` is defined as `b i ↦ ϖ.val ^ f i • b i`. We provide variants for `ι = Fin 2` and
  for natural exponents. Generally, try to bring all lattices in the context in the form
  of `b.twist hϖ f` for fixed `b` and varying `f`, in order to simplify calculations.
-/


-- @@ L41-41 verbatim
@[expose] public section


-- @@ L43-43 verbatim
open Module



-- @@ L46-46 verbatim
suppress_compilation


-- @@ L48-48 verbatim
variable {K : Type*} [Field K]

-- @@ L49-49 verbatim
variable {R : Subring K}


-- @@ L51-51 verbatim
open BruhatTits


-- @@ L53-53 verbatim
namespace Module.Basis


-- @@ L55-55 verbatim
variable {ι : Type*}


-- @@ L57-60 verbatim
/-- From a `ι`-indexed basis `b` of `ι → K`, we obtain an `R` submodule of `ι → K` generated by
the entries of `b`. -/
def toSubmodule (b : Basis ι K (ι → K)) : Submodule R (ι → K) :=
  Submodule.span R (Set.range b)


-- @@ L62-65 verbatim
lemma self_mem_toSubmodule (b : Basis ι K (ι → K)) (i : ι) : b i ∈ b.toSubmodule (R := R) := by
  rw [toSubmodule]
  apply Submodule.subset_span
  use i


-- @@ L67-79 verbatim
open Classical in
lemma toSubmodule_isLattice [Finite ι] (b : Basis ι K (ι → K)) :
    IsLattice (R := R) b.toSubmodule where
  isFG := by
    let : Fintype ι := Fintype.ofFinite ι
    exact ⟨Finset.image b Finset.univ, by simp [toSubmodule]⟩
  spans := by
    let : Fintype ι := Fintype.ofFinite ι
    rw [_root_.eq_top_iff]
    rw [← b.span_eq]
    apply Submodule.span_mono
    simp only [toSubmodule]
    simp_all


-- @@ L81-92 verbatim
/--
Given a `K`-basis of `K^2`, this is the `R`-lattice generated by the entries of `b`.

This is the normal form of a lattice in our API and for every operation on lattices
suitable `simp` lemmas should be provided for lattices given by `Basis.toLattice`.

If possible, in proofs use the induction principle of equality (i.e. the `subst` tactic) to
replace all occurring lattices by invocations of `Basis.toLattice`.
-/
def toLattice (b : Basis (Fin 2) K (Fin 2 → K)) : BruhatTits.Lattice R where
  M := b.toSubmodule
  isLattice := b.toSubmodule_isLattice


-- @@ L94-97 verbatim
@[simp]
lemma toLattice_module (b : Basis (Fin 2) K (Fin 2 → K)) :
    (b.toLattice (R := R)).M = b.toSubmodule :=
  rfl


-- @@ L99-113 verbatim
/-- If `b` is a `K`-basis of `ι → K` and `f : ι → Kˣ` a family of invertible elements of `K`,
this is the basis of `ι → K` obtained by multiplying `i`-th entry of `b` by `f i`. -/
def twist' [Fintype ι] (b : Basis ι K (ι → K)) (f : ι → Kˣ) : Basis ι K (ι → K) :=
  let v (i : ι) : (ι → K) := (f i).val • b i
  have hli : LinearIndependent K v := by
    rw [linearIndependent_iff']
    intro s g hg
    simp only [v, smul_smul] at hg
    intro i hi
    have := linearIndependent_iff'.mp b.linearIndependent s _ hg i hi
    simp_all
  have hsp : ⊤ ≤ Submodule.span K (Set.range v) := by
    rw [← hli.span_eq_top_of_card_eq_finrank']
    exact (Module.finrank_fintype_fun_eq_card K).symm
  Basis.mk hli hsp


-- @@ L115-118 verbatim
@[simp]
lemma twist'_apply [Fintype ι] (b : Basis ι K (ι → K)) (f : ι → Kˣ) (i : ι) :
    b.twist' f i = f i • b i := by
  simp [twist', Units.smul_def]


-- @@ L120-126 verbatim
/-- Given integer exponents `f` and a uniformizer `ϖ`, we may twist a basis `b` by
`b i ↦ ϖ.val ^ f i • b i`. -/
def twist [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f : ι → ℤ) :
    Basis ι K (ι → K) :=
  have hϖ' : ϖ.val ≠ 0 := by simpa using hϖ.ne_zero
  b.twist' (fun i ↦ Units.mk0 ϖ.val hϖ' ^ f i)


-- @@ L128-132 verbatim
@[simp]
lemma twist_apply [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f : ι → ℤ) (i : ι) :
    b.twist hϖ f i = ϖ.val ^ f i • b i := by
  simp [twist, Units.smul_def]


-- @@ L134-138 verbatim
/-- `twist` but for natural exponents. -/
def ntwist [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f : ι → ℕ) :
    Basis ι K (ι → K) :=
  b.twist hϖ (fun i ↦ f i)


-- @@ L140-144 verbatim
@[simp]
lemma ntwist_apply [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f : ι → ℕ) (i : ι) :
    b.ntwist hϖ f i = ϖ ^ f i • b i := by
  simp [ntwist, Subring.smul_def]


-- @@ L146-151 verbatim
/-- `twist` specialized to dimension two. -/
def twist₂ (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ) (n m : ℤ) :
    Basis (Fin 2) K (Fin 2 → K) :=
  b.twist hϖ (fun i ↦ match i with
    | 0 => n
    | 1 => m)


-- @@ L153-157 verbatim
@[simp]
lemma twist₂_apply₀ (b : Basis (Fin 2) K ((Fin 2) → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (n m : ℤ) :
    b.twist₂ hϖ n m 0 = ϖ.val ^ n • b 0 := by
  simp [twist₂]


-- @@ L159-163 verbatim
@[simp]
lemma twist₂_apply₁ (b : Basis (Fin 2) K ((Fin 2) → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (n m : ℤ) :
    b.twist₂ hϖ n m 1 = ϖ.val ^ m • b 1 := by
  simp [twist₂]


-- @@ L165-168 verbatim
/-- `twist₂` for natural exponents. -/
def ntwist₂ (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ) (n m : ℕ) :
    Basis (Fin 2) K (Fin 2 → K) :=
  b.twist₂ hϖ n m


-- @@ L170-174 verbatim
@[simp]
lemma ntwist₂_apply₀ (b : Basis (Fin 2) K ((Fin 2) → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (n m : ℕ) :
    b.ntwist₂ hϖ n m 0 = ϖ ^ n • b 0 := by
  simp [ntwist₂, Subring.smul_def]


-- @@ L176-180 verbatim
@[simp]
lemma ntwist₂_apply₁ (b : Basis (Fin 2) K ((Fin 2) → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (n m : ℕ) :
    b.ntwist₂ hϖ n m 1 = ϖ ^ m • b 1 := by
  simp [ntwist₂, Subring.smul_def]


-- @@ L182-182 verbatim
section «LE»


-- @@ L184-184 verbatim
open BigOperators


-- @@ L186-242 verbatim
lemma twist_le_twist_iff [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f g : ι → ℤ) :
    (b.twist hϖ f).toSubmodule (R := R) ≤ (b.twist hϖ g).toSubmodule (R := R) ↔ g ≤ f := by
  classical
  constructor
  · intro h i
    have : ϖ.val ^ f i • b i ∈ (b.twist hϖ g).toSubmodule (R := R) := by
      apply h
      apply Submodule.subset_span
      simp_all
    simp only [toSubmodule] at this
    rw [Submodule.mem_span_range_iff_exists_fun] at this
    obtain ⟨c, hc⟩ := this
    have heq : ∑ j : ι, c j • (b.twist hϖ g) j - ϖ.val ^ f i • b i = 0 := by
      simp_all
    simp only [twist_apply] at heq
    have : ϖ.val ^ f i • b i = ∑ j : ι, (if i = j then ϖ.val ^ f i else 0) • b j := by
      simp
    rw [this] at heq
    rw [← Finset.sum_sub_distrib] at heq
    simp_rw [Subring.smul_def, smul_smul, ← sub_smul] at heq
    have hzero := Fintype.linearIndependent_iff.mp b.linearIndependent _ heq i
    rw [ite_eq_left rfl] at hzero
    rw [sub_eq_zero] at hzero
    have : ϖ.val ≠ 0 := by simpa using hϖ.ne_zero
    have : ϖ.val ^ g i ≠ 0 := zpow_ne_zero (g i) this
    have : (c i).val = ϖ.val ^ f i * ϖ.val ^ (- g i) := by
      rw [← hzero]
      simp
      field_simp
    rw [← zpow_add₀ (by simpa using hϖ.ne_zero)] at this
    have : f i - g i ≥ 0 := by
      rw [← irreducible_zpow_mem_subring_iff (R := R) (hϖ := hϖ)]
      rw [sub_eq_add_neg, ← this]
      exact (c i).property
    simpa using this
  · intro hgf
    simp only [toSubmodule]
    rw [Submodule.span_le]
    rintro - ⟨i, hi, rfl⟩
    simp only [twist_apply, SetLike.mem_coe]
    have hϖ' : ϖ.val ≠ 0 := by simpa using hϖ.ne_zero
    have : ϖ.val ^ g i ≠ 0 := zpow_ne_zero (g i) hϖ'
    have : ϖ.val ^ f i • b i = ϖ.val ^ (f i - g i) • ϖ.val ^ g i • b i := by
      rw [zpow_sub₀ hϖ', smul_smul]
      field_simp
    rw [this]
    have : ϖ.val ^ (f i - g i) ∈ R := by
      rw [irreducible_zpow_mem_subring_iff (hϖ := hϖ)]
      simpa using hgf i
    let r : R := ⟨ϖ.val ^ (f i - g i), this⟩
    have : ϖ.val ^ (f i - g i) • ϖ.val ^ g i • b i = r • ϖ.val ^ g i • b i := by
      simp [Subring.smul_def, r]
    rw [this]
    apply Submodule.smul_mem
    apply Submodule.subset_span
    simp_all


-- @@ L244-252 verbatim
lemma twist_eq_twist_iff [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f g : ι → ℤ) :
    (b.twist hϖ f).toSubmodule (R := R) = (b.twist hϖ g).toSubmodule (R := R) ↔ g = f := by
  constructor
  · intro h
    apply le_antisymm
    · rw [← b.twist_le_twist_iff hϖ, h]
    · rw [← b.twist_le_twist_iff hϖ, h]
  · simp_all


-- @@ L254-273 verbatim
lemma twist_lt_twist_iff [Fintype ι] (b : Basis ι K (ι → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (f g : ι → ℤ) :
    (b.twist hϖ f).toSubmodule (R := R) < (b.twist hϖ g).toSubmodule (R := R) ↔
      g ≤ f ∧ ∃ i, g i < f i := by
  constructor
  · intro h
    have hgf : g ≤ f := by
      rw [← b.twist_le_twist_iff hϖ]
      exact le_of_lt h
    by_contra hnotlt
    simp only [not_and, not_exists, not_lt] at hnotlt
    have hfg : f ≤ g := hnotlt hgf
    have : f = g := le_antisymm hfg hgf
    simp_all
  · intro h
    rw [← b.twist_le_twist_iff hϖ] at h
    apply lt_of_le_of_ne h.left
    by_contra heq
    rw [b.twist_eq_twist_iff] at heq
    simp [heq] at h


-- @@ L275-284 verbatim
lemma twist₂_le_twist₂_iff (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ)
    (n₁ m₁ n₂ m₂ : ℤ) :
    (b.twist₂ hϖ n₁ m₁).toSubmodule (R := R) ≤ (b.twist₂ hϖ n₂ m₂).toSubmodule ↔
      n₂ ≤ n₁ ∧ m₂ ≤ m₁ := by
  rw [twist₂, twist₂, twist_le_twist_iff]
  constructor
  · intro h
    exact ⟨by simpa using h 0, by simpa using h 1⟩
  · intro h i
    fin_cases i <;> [exact h.left; exact h.right]


-- @@ L286-292 verbatim
lemma twist₂_eq_twist₂_iff (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ)
    (n₁ m₁ n₂ m₂ : ℤ) :
    (b.twist₂ hϖ n₁ m₁).toSubmodule (R := R) = (b.twist₂ hϖ n₂ m₂).toSubmodule ↔
      n₂ = n₁ ∧ m₂ = m₁ := by
  rw [twist₂, twist₂, twist_eq_twist_iff]
  refine ⟨fun h ↦ ⟨by simpa using congrFun h 0, by simpa using congrFun h 1⟩, fun h ↦ ?_⟩
  simp_all


-- @@ L294-300 verbatim
lemma ntwist₂_le_ntwist₂_iff (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ)
    (n₁ m₁ n₂ m₂ : ℕ) :
    (b.ntwist₂ hϖ n₁ m₁).toSubmodule (R := R) ≤ (b.ntwist₂ hϖ n₂ m₂).toSubmodule ↔
      n₂ ≤ n₁ ∧ m₂ ≤ m₁ := by
  simp only [ntwist₂]
  rw [twist₂_le_twist₂_iff]
  omega


-- @@ L302-302 verbatim
end «LE»


-- @@ L304-304 verbatim
section «fromLattice»


-- @@ L306-306 verbatim
variable [IsFractionRing R K] [Fintype ι]


-- @@ L308-315 verbatim
/-- If `M` is a lattice, every `R`-basis of `M` is also a `K`-basis of `ι → K`. -/
def fromSubmoduleOfIsLattice {M : Submodule R (ι → K)} [IsLattice M] (b : Basis ι R M) :
    Basis ι K (ι → K) :=
  have hli : LinearIndependent K (fun i ↦ (b i).val) :=
    b.linearIndependent_of_submodule
  have hsp : ⊤ ≤ Submodule.span K (Set.range <| fun i ↦ (b i).val) :=
    b.top_le_submodule_span_of_isLattice
  Basis.mk hli hsp


-- @@ L317-320 verbatim
@[simp]
lemma fromSubmoduleOfIsLattice_apply {M : Submodule R (ι → K)} [IsLattice M] (b : Basis ι R M)
    (i : ι) : b.fromSubmoduleOfIsLattice i = b i := by
  simp [fromSubmoduleOfIsLattice]


-- @@ L322-325 verbatim
/-- If `M` is an `R`-lattice, every `R`-basis of `M` is also a `K`-basis of `Fin 2 → K`. -/
def fromLattice {M : BruhatTits.Lattice R} (b : Basis (Fin 2) R M.M) :
    Basis (Fin 2) K (Fin 2 → K) :=
  fromSubmoduleOfIsLattice b


-- @@ L327-330 verbatim
@[simp]
lemma fromLattice_apply {M : BruhatTits.Lattice R} (b : Basis (Fin 2) R M.M) (i : Fin 2) :
    b.fromLattice i = b i := by
  simp [fromLattice]


-- @@ L332-344 verbatim
@[simp]
lemma toSubmodule_fromLattice {M : Submodule R (ι → K)} [IsLattice M] (b : Basis ι R M) :
    b.fromSubmoduleOfIsLattice.toSubmodule = M := by
  simp only [toSubmodule]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro - ⟨i, rfl⟩
    simp
  · simp_rw [← Submodule.map_subtype_top M, ← b.span_eq]
    rw [Submodule.map_span]
    apply Submodule.span_mono
    rintro - ⟨i, ⟨a, rfl⟩, rfl⟩
    simp


-- @@ L346-350 verbatim
@[simp]
lemma toLattice_fromLattice {M : BruhatTits.Lattice R} (b : Basis (Fin 2) R M.M) :
    b.fromLattice.toLattice = M := by
  apply BruhatTits.Lattice.ext
  simp [fromLattice]


-- @@ L352-352 verbatim
end «fromLattice»


-- @@ L354-354 verbatim
section «Restrict»


-- @@ L356-356 verbatim
variable [IsFractionRing R K] [Fintype ι]


-- @@ L358-375 verbatim
/-- If `b` is a `K`-basis of `ι → K`, it is naturally an `R`-basis of the
`R`-submodule generated by the entries of `b`. -/
def restrict (b : Basis ι K (ι → K)) : Basis ι R (b.toSubmodule (R := R)) :=
  let v (i : ι) : (b.toSubmodule (R := R)) := ⟨b i, b.self_mem_toSubmodule i⟩
  have hli : LinearIndependent R v := by
    apply LinearIndependent.of_comp (b.toSubmodule (R := R)).subtype
    rw [LinearIndependent.iff_fractionRing (R := R) (K := K)]
    exact b.linearIndependent
  have hsp : ⊤ ≤ Submodule.span R (Set.range v) := by
    rintro ⟨x, hx⟩ -
    simp only [toSubmodule] at hx
    simp only [v]
    rw [Submodule.mem_span_range_iff_exists_fun] at hx ⊢
    obtain ⟨c, hc⟩ := hx
    use c
    apply Subtype.ext
    simpa
  Basis.mk hli hsp


-- @@ L377-380 verbatim
@[simp]
lemma restrict_apply (b : Basis ι K (ι → K)) (i : ι) :
    b.restrict (R := R) i = b i := by
  simp [restrict]


-- @@ L382-386 verbatim
/-- If `b` is a `K`-basis of `Fin 2 → K`, it is naturally an `R`-basis of the
`R`-lattice generated by the entries of `b`. -/
def restrictToLattice (b : Basis (Fin 2) K (Fin 2 → K)) :
    Basis (Fin 2) R (b.toLattice (R := R)).M :=
  b.restrict (R := R)


-- @@ L388-392 verbatim
lemma restrictToLattice_apply (b : Basis (Fin 2) K (Fin 2 → K)) (i : Fin 2) :
    @DFunLike.coe no_index _ _ _ _ (b.restrictToLattice (R := R)) i = b i := by
  simp only [restrictToLattice]
  rw [← b.restrict_apply (R := R) i]
  rfl


-- @@ L394-394 verbatim
end «Restrict»


-- @@ L396-396 verbatim
section «GLSMul»


-- @@ L398-398 verbatim
variable [DecidableEq ι] [Fintype ι]


-- @@ L400-402 verbatim
/-- Scalar multiplication by `GL ι K` on `ι`-indexed bases of `ι → K`. -/
def smulGL (g : GL ι K) (b : Basis ι K (ι → K)) : Basis ι K (ι → K) :=
  b.map (g.toLin.toLinearEquiv)


-- @@ L404-405 verbatim
instance instSMulGeneralLinearGroupForallLeanPool : SMul (GL ι K) (Basis ι K (ι → K)) where
  smul g b := smulGL g b


-- @@ L407-409 verbatim
lemma smulGL_def (g : GL ι K) (b : Basis ι K (ι → K)) :
    g • b = b.map (g.toLin.toLinearEquiv) :=
  rfl


-- @@ L411-415 verbatim
@[simp]
lemma smulGL_apply (g : GL ι K) (b : Basis ι K (ι → K)) (i : ι) :
    (g • b) i = g.val.mulVec (b i) := by
  rw [smulGL_def]
  simp [LinearMap.GeneralLinearGroup.toLinearEquiv, Matrix.mulVecLin]


-- @@ L417-441 verbatim
lemma smulGL_toSubmodule (g : GL ι K) (b : Basis ι K (ι → K)) :
    (g • b).toSubmodule (R := R) = g • b.toSubmodule := by
  classical
  simp only [toSubmodule, smulGL_def]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro - ⟨i, hi, rfl⟩
    simp only [map_apply, SetLike.mem_coe]
    rw [Matrix.GeneralLinearGroup.mem_smul]
    refine ⟨b i, ?_, rfl⟩
    apply Submodule.subset_span
    exact Set.mem_range_self i
  · intro x hx
    rw [Matrix.GeneralLinearGroup.mem_smul] at hx
    obtain ⟨y, hy, rfl⟩ := hx
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hy
    · intro x hx
      obtain ⟨i, rfl⟩ := hx
      apply Submodule.subset_span
      simp_all
    · simp
    · intro x y _ _ hx hy
      simpa only [Matrix.mulVec_add] using Submodule.add_mem _ hx hy
    · intro a x _ hx
      simpa only [Matrix.mulVec_smul] using Submodule.smul_mem _ a hx


-- @@ L443-448 verbatim
lemma smulGL_toLattice (g : GL (Fin 2) K) (b : Basis (Fin 2) K (Fin 2 → K)) :
    (g • b).toLattice (R := R) = g • b.toLattice (R := R) := by
  classical
  apply BruhatTits.Lattice.ext
  rw [Lattice.smul_M]
  simp [smulGL_toSubmodule]


-- @@ L450-453 verbatim
lemma smulGL_twist (g : GL ι K) (b : Basis ι K (ι → K)) {ϖ : R} (hϖ : Irreducible ϖ) (f : ι → ℤ) :
    g • b.twist hϖ f = (g • b).twist hϖ f := by
  ext i : 1
  simp [Matrix.mulVec_smul]


-- @@ L455-458 verbatim
lemma smulGL_toGeneralLinearGroup (g : GL ι K) (b : Basis ι K (ι → K)) :
    (g • b).toGeneralLinearGroup = g * b.toGeneralLinearGroup := by
  ext i j
  simp [Matrix.mul_apply, Matrix.mulVec, dotProduct]


-- @@ L460-460 verbatim
end «GLSMul»


-- @@ L462-462 verbatim
section «SMul»


-- @@ L464-464 verbatim
variable [Fintype ι]


-- @@ L466-467 verbatim
/-- Scalar multiplication of units of `K` on bases of `ι → K` by twisting. -/
def smul' (a : Kˣ) (b : Basis ι K (ι → K)) : Basis ι K (ι → K) := b.twist' (fun _ ↦ a)


-- @@ L469-470 verbatim
instance instSMulUnitsForallLeanPool : SMul Kˣ (Basis ι K (ι → K)) where
  smul := smul'


-- @@ L472-472 verbatim
lemma smul'_def (a : Kˣ) (b : Basis ι K (ι → K)) : a • b = b.twist' (fun _ ↦ a) := rfl


-- @@ L474-476 verbatim
@[simp]
lemma smul'_apply (a : Kˣ) (b : Basis ι K (ι → K)) (i : ι) : (a • b) i = a • b i := by
  simp [smul'_def]


-- @@ L478-478 verbatim
open Pointwise


-- @@ L480-494 verbatim
lemma smul_toSubmodule (a : Kˣ) (b : Basis ι K (ι → K)) :
    a • b.toSubmodule (R := R) = (a • b).toSubmodule := by
  calc
    a • b.toSubmodule (R := R) = a • Submodule.span R (Set.range b) := rfl
    _ = Submodule.span R (a • Set.range b) :=
      Submodule.smul_span a (Set.range b)
    _ = Submodule.span R (Set.range (a • b)) := by
      apply congrArg (Submodule.span R)
      ext x
      constructor
      · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
        exact ⟨i, by simp [Units.smul_def]⟩
      · rintro ⟨i, rfl⟩
        exact ⟨b i, ⟨i, rfl⟩, by simp [Units.smul_def]⟩
    _ = (a • b).toSubmodule := rfl


-- @@ L496-512 verbatim
lemma smul_twist (b : Basis ι K (ι → K)) {ϖ : R} (hϖ : Irreducible ϖ) (f : ι → ℤ) :
    ϖ • (b.twist hϖ f).toSubmodule (R := R) = (b.twist hϖ (f + 1)).toSubmodule := by
  simp only [toSubmodule, Submodule.smul_span]
  congr
  ext x
  constructor
  · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
    simp only [twist_apply, Set.mem_range, Pi.add_apply, Pi.one_apply]
    use i
    rw [zpow_add₀ (by simpa using hϖ.ne_zero)]
    simp [Subring.smul_def, smul_smul, mul_comm]
  · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
    simp only [twist_apply, Pi.add_apply, Pi.one_apply]
    refine ⟨b.twist hϖ f y, ?_, ?_⟩
    · exact Set.mem_range_self y
    · rw [zpow_add₀ (by simpa using hϖ.ne_zero)]
      simp [Subring.smul_def, smul_smul, mul_comm]


-- @@ L514-520 verbatim
lemma smul_ntwist₂ (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ) (n m : ℕ) :
    ϖ • (b.ntwist₂ hϖ n m).toSubmodule (R := R) = (b.ntwist₂ hϖ (n + 1) (m + 1)).toSubmodule := by
  simp only [ntwist₂, twist₂, Nat.cast_add, Nat.cast_one]
  rw [smul_twist]
  congr
  ext i : 1
  fin_cases i <;> simp


-- @@ L522-538 verbatim
lemma smul_pow_twist (b : Basis ι K (ι → K)) {ϖ : R} (hϖ : Irreducible ϖ) (f : ι → ℤ) (k : ℤ) :
    ϖ.val ^ k • (b.twist hϖ f).toSubmodule (R := R) = (b.twist hϖ (f + k)).toSubmodule := by
  simp only [toSubmodule, Submodule.smul_span]
  congr
  ext x
  constructor
  · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
    simp only [Pi.intCast_def, Int.cast_id, twist_apply, Set.mem_range, Pi.add_apply]
    use i
    rw [zpow_add₀ (by simpa using hϖ.ne_zero)]
    simp only [mul_comm, smul_smul]
  · rintro ⟨y, ⟨i, rfl⟩, rfl⟩
    simp only [Pi.intCast_def, Int.cast_id, twist_apply, Pi.add_apply]
    refine ⟨b.twist hϖ f y, ?_, ?_⟩
    · exact Set.mem_range_self y
    · rw [zpow_add₀ (by simpa using hϖ.ne_zero)]
      simp [smul_smul, mul_comm]


-- @@ L540-547 verbatim
lemma smul_pow_twist₂ (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ) (n m k : ℤ) :
    ϖ.val ^ k • (b.twist₂ hϖ n m).toSubmodule (R := R) =
      (b.twist₂ hϖ (n + k) (m + k)).toSubmodule := by
  simp only [twist₂]
  rw [smul_pow_twist]
  congr
  ext i : 1
  fin_cases i <;> simp


-- @@ L549-552 verbatim
lemma twist_zero (b : Basis ι K (ι → K)) {ϖ : R} (hϖ : Irreducible ϖ) :
    b.twist hϖ 0 = b := by
  ext i : 1
  simp


-- @@ L554-557 verbatim
lemma ntwist₂_zero_zero (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ) :
    b.ntwist₂ hϖ 0 0 = b := by
  ext i : 1
  fin_cases i <;> simp


-- @@ L559-563 verbatim
lemma ntwist₂_toSubmodule_le_ntwist₂_toSubmodule (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) {n₁ m₁ n₂ m₂ : ℕ} (hn : n₂ ≤ n₁) (hm : m₂ ≤ m₁) :
    (b.ntwist₂ hϖ n₁ m₁).toSubmodule (R := R) ≤ (b.ntwist₂ hϖ n₂ m₂).toSubmodule (R := R) := by
  rw [ntwist₂_le_ntwist₂_iff]
  exact ⟨hn, hm⟩


-- @@ L565-571 verbatim
lemma ntwist₂_toSubmodule_le (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R}
    (hϖ : Irreducible ϖ) (n m : ℕ) :
    (b.ntwist₂ hϖ n m).toSubmodule ≤ b.toSubmodule (R := R) := by
  conv_rhs => rw [← b.ntwist₂_zero_zero hϖ]
  apply b.ntwist₂_toSubmodule_le_ntwist₂_toSubmodule
  · simp
  · simp


-- @@ L573-577 verbatim
lemma ntwist₂_ntwist₂ (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ)
    (n₁ m₁ n₂ m₂ : ℕ) :
    (b.ntwist₂ hϖ n₁ m₁).ntwist₂ hϖ n₂ m₂ = b.ntwist₂ hϖ (n₁ + n₂) (m₁ + m₂) := by
  ext i : 1
  fin_cases i <;> simp [pow_add, smul_smul, mul_comm]


-- @@ L579-579 verbatim
end «SMul»


-- @@ L581-581 verbatim
section «Swap»


-- @@ L583-583 verbatim
variable [Fintype ι] [DecidableEq ι]


-- @@ L585-588 verbatim
/-- Given a basis `b` of `ι → K` and a permutation of the basis vectors,
this is the matrix representing the `K`-automorphisms induced by the permutation. -/
def permMatrix (b : Basis ι K (ι → K)) (e : ι ≃ ι) : GL ι K :=
  Matrix.GeneralLinearGroup.toLin.symm <| .ofLinearEquiv <| b.equiv (b.reindex e) (Equiv.refl _)


-- @@ L590-600 verbatim
lemma toLinear_symm_ofLinearEquiv_mulVec (e : (ι → K) ≃ₗ[K] (ι → K)) (x : ι → K) :
    (Matrix.GeneralLinearGroup.toLin.symm <| .ofLinearEquiv e).val.mulVec x = e x := by
  have : (Matrix.GeneralLinearGroup.toLin.symm <| .ofLinearEquiv e).val.mulVecLin = e := by
    apply (Pi.basisFun K ι).ext
    intro i
    simp only [Pi.basisFun_apply, Matrix.mulVecBilin_apply, Matrix.mulVec_single,
      MulOpposite.op_one, one_smul, LinearEquiv.coe_coe]
    ext j
    simp
  change Matrix.mulVecLin _ x = e x
  simp_all


-- @@ L602-607 verbatim
lemma permMatrix_smul_toSubmodule (b : Basis ι K (ι → K)) (e : ι ≃ ι) :
    b.permMatrix e • b.toSubmodule = (b.reindex e).toSubmodule (R := R) := by
  rw [← smulGL_toSubmodule]
  congr
  ext i : 1
  simp [permMatrix, toLinear_symm_ofLinearEquiv_mulVec]


-- @@ L609-618 verbatim
/-- The permutation exchanging the two indices of a rank-two basis. -/
def swap₂ : Fin 2 ≃ Fin 2 where
  toFun
    | 0 => 1
    | 1 => 2
  invFun
    | 0 => 1
    | 1 => 2
  left_inv := by decide
  right_inv := by decide


-- @@ L620-620 verbatim
@[simp] lemma swap₂_apply₀ : swap₂ 0 = 1 := rfl

-- @@ L621-621 verbatim
@[simp] lemma swap₂_apply₁ : swap₂ 1 = 0 := rfl

-- @@ L622-622 verbatim
@[simp] lemma swap₂_symm : swap₂.symm = swap₂ := rfl


-- @@ L624-626 verbatim
/-- Swap the entries of a basis of `Fin 2 → K`. -/
def swap (b : Basis (Fin 2) K (Fin 2 → K)) : Basis (Fin 2) K (Fin 2 → K) :=
  b.reindex swap₂


-- @@ L628-629 verbatim
@[simp] lemma swap_apply₀ (b : Basis (Fin 2) K (Fin 2 → K)) : b.swap 0 = b 1 := by
  simp [swap]


-- @@ L631-632 verbatim
@[simp] lemma swap_apply₁ (b : Basis (Fin 2) K (Fin 2 → K)) : b.swap 1 = b 0 := by
  simp [swap]


-- @@ L634-643 verbatim
lemma swap_toSubmodule (b : Basis (Fin 2) K (Fin 2 → K)) :
    b.swap.toSubmodule (R := R) = b.toSubmodule := by
  rw [toSubmodule, toSubmodule]
  apply congrArg (Submodule.span R)
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i <;> simp [swap_apply₀, swap_apply₁]
  · rintro ⟨i, rfl⟩
    fin_cases i <;> [exact ⟨1, by simp⟩; exact ⟨0, by simp⟩]


-- @@ L645-648 verbatim
/-- The swap matrix associated to a basis `b`: the invertible matrix acting on `Fin 2 → K` by
swapping the entries of `b`. -/
def swapMatrix (b : Basis (Fin 2) K (Fin 2 → K)) : GL (Fin 2) K :=
  b.permMatrix swap₂


-- @@ L650-652 verbatim
lemma swapMatrix_smul_toSubmodule (b : Basis (Fin 2) K (Fin 2 → K)) :
    b.swapMatrix • b.toSubmodule = b.swap.toSubmodule (R := R) := by
  simp [swapMatrix, permMatrix_smul_toSubmodule, swap]


-- @@ L654-670 verbatim
lemma swapMatrix_smul_ntwist₂ (b : Basis (Fin 2) K (Fin 2 → K)) {ϖ : R} (hϖ : Irreducible ϖ)
    (n m : ℕ) :
    b.swapMatrix • (b.ntwist₂ hϖ n m).toSubmodule = (b.ntwist₂ hϖ m n).toSubmodule (R := R) := by
  simp only [swapMatrix]
  rw [← smulGL_toSubmodule]
  conv_rhs => rw [← swap_toSubmodule]
  congr
  ext i : 1
  match i with
  | 0 =>
    simp only [permMatrix, Fin.isValue, smulGL_apply, ntwist₂_apply₀, Subring.smul_def,
      SubmonoidClass.coe_pow, toLinear_symm_ofLinearEquiv_mulVec, map_smul, equiv_apply,
      Equiv.refl_apply, reindex_apply, swap₂_symm, swap₂_apply₀, swap_apply₀, ntwist₂_apply₁]
  | 1 =>
    simp only [permMatrix, Fin.isValue, smulGL_apply, ntwist₂_apply₁, Subring.smul_def,
      SubmonoidClass.coe_pow, toLinear_symm_ofLinearEquiv_mulVec, map_smul, equiv_apply,
      Equiv.refl_apply, reindex_apply, swap₂_symm, swap₂_apply₁, swap_apply₁, ntwist₂_apply₀]


-- @@ L672-672 verbatim
end «Swap»


-- @@ L674-676 verbatim
variable [IsFractionRing R K]

-- Auxiliary instance to speed up instance search

-- @@ L677-679 verbatim
instance (b : Basis (Fin 2) K (Fin 2 → K)) :
    SMul R (b.toSubmodule (R := R)) :=
  b.toSubmodule.smul


-- @@ L681-692 verbatim
lemma is_linear_comb_of_mem_ntwist (b : Basis (Fin 2) K (Fin 2 → K))
    {ϖ : R} (hϖ : Irreducible ϖ) (y : b.toSubmodule (R := R)) {n m : ℕ}
    (hy : y.val ∈ (b.ntwist₂ hϖ n m).toSubmodule (R := R)) :
    ∃ (α β : R),
      y = (α • (ϖ ^ n • b.restrict (R := R) 0 : b.toSubmodule (R := R))) +
        β • ϖ ^ m • b.restrict (R := R) 1 := by
  rw [toSubmodule] at hy
  rw [Submodule.mem_span_range_iff_exists_fun] at hy
  obtain ⟨c, hc⟩ := hy
  use c 0, c 1
  apply Subtype.ext
  simp_all


-- @@ L694-694 verbatim
end Module.Basis


-- @@ L696-699 verbatim
variable (R) in
/-- The standard `R`-lattice `R ⊕ R`. -/
def Lattice.standard : BruhatTits.Lattice R :=
  (Pi.basisFun K (Fin 2)).toLattice


-- @@ L701-717 verbatim
lemma Lattice.standard_M :
    (Lattice.standard R).M = LinearMap.range ((Algebra.linearMap R K).compLeft _) := by
  have : Submodule.span R (Set.range <| Pi.basisFun R (Fin 2)) = ⊤ :=
    (Pi.basisFun (↥R) (Fin 2)).span_eq
  simp only [Lattice.standard, Basis.toLattice_module, Basis.toSubmodule]
  rw [← Submodule.map_top, ← this, Submodule.map_span]
  apply congrArg (Submodule.span R)
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    refine ⟨Pi.basisFun R (Fin 2) i, ⟨i, rfl⟩, ?_⟩
    ext j
    simp [Pi.single_apply]
  · rintro ⟨v, ⟨i, rfl⟩, rfl⟩
    refine ⟨i, ?_⟩
    ext j
    simp [Pi.single_apply]


-- @@ L719-745 verbatim
@[simp]
lemma map_subtype_smul_standard_eq_standard (g : GL (Fin 2) R) :
    Matrix.GeneralLinearGroup.map R.subtype g • Lattice.standard R = Lattice.standard R := by
  ext : 1
  rw [Lattice.smul_M, Lattice.standard_M, Matrix.GeneralLinearGroup.smul_submodule_def]
  simp only [Matrix.GeneralLinearGroup.val_map_apply, Subring.coe_subtype]
  have (x : Fin 2 → R) :
      (g.val.map Subtype.val).mulVec (((Algebra.linearMap (↥R) K).compLeft (Fin 2)) x) =
        (Algebra.linearMap (↥R) K).compLeft (Fin 2) (g.val.mulVec x) := by
    induction x using Pi.single_induction with
    | zero => simp
    | add a b ha hb => simp [ha, hb, Matrix.mulVec_add]
    | single i r =>
      have : ((Algebra.linearMap (↥R) K).compLeft (Fin 2)) (Pi.single i r) = Pi.single i r.val := by
        ext
        simp [Algebra.algebraMap_ofSubsemiring_apply, Pi.single_apply]
      simp only [this, Matrix.mulVec_single, op_smul_eq_smul, map_smul]
      rfl
  apply le_antisymm
  · rw [Submodule.map_le_iff_le_comap]
    rintro - ⟨x, rfl⟩
    simp_all
  · rintro - ⟨x, rfl⟩
    simp only [Submodule.mem_map, LinearMap.mem_range, LinearMap.coe_restrictScalars,
      Matrix.mulVecLin_apply, exists_exists_eq_and]
    use g.inv.mulVec x
    simp [this]


-- @@ L747-747 verbatim
section


-- @@ L749-758 verbatim
open Pointwise in
lemma IsLattice.of_le_of_isLattice_right [IsDiscreteValuationRing R] (L : Submodule R (Fin 2 → K))
      [IsLattice L] (M : Submodule R (Fin 2 → K))
    (h₁ : M ≤ L) (h₂ : IsLocalRing.maximalIdeal R • L ≤ M) :
    IsLattice M := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible R
  rw [maximalIdeal_smul_eq_uniformizer_smul _ hϖ] at h₂
  have hϖ' : ϖ.val ≠ 0 := by simpa using hϖ.ne_zero
  replace h₂ : Units.mk0 ϖ.val hϖ' • L ≤ M := h₂
  apply IsLattice.of_le_of_isLattice h₂ h₁


-- @@ L760-760 verbatim
end
