/-
Copyright (c) 2026 Axiom Math. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ken Ono
-/
module

public import LeanPool.GranvilleMoore.Defs.TheIteratedFermatQuotients
public import LeanPool.GranvilleMoore.TheFermatQuotient
public import Mathlib.Algebra.Polynomial.Roots
public import Mathlib.Data.Nat.Prime.Factorial
public import Mathlib.Algebra.CharZero.Infinite
public import Mathlib.NumberTheory.Padics.PadicVal.Basic
public import Mathlib.Tactic.FieldSimp

-- Adapted for Lean Pool: relocated imports and simplified supporting infrastructure.


-- @@ L18-63 verbatim
/-!
# The binomial polynomial at powers of `p`

The rescaled binomial polynomial `B_m(z) = (1/m!) ∏_{s<m} ((z-1)/(p-1) - s)` of Granville's
paper is engineered so that its values at the powers of `p` are binomial coefficients: the
substitution `z = p^i` turns `(z-1)/(p-1)` into the Frobenius exponent `e_i = ∑_{r<i} p^r`,
and the product becomes the length-`m` falling factorial of `e_i`.

This file proves that evaluation, reads it backwards as an expansion of `C(e_i, m)` in the
powers `(p^n)^i`, and bounds the denominators of the coefficients `β_{m,n}`.

## Main results

* `GranvilleMoore.eval_binomPoly_pow_eq_choose`: `B_m(p^i) = C(e_i, m)`.
* `GranvilleMoore.natCast_choose_frobeniusExponent_eq_sum`:
  `C(e_i, m) = ∑_{n ≤ m} β_{m,n} (p^n)^i`.
* `GranvilleMoore.exists_intCast_eq_factorial_mul_pow_mul_binomPolyCoeff`: the integrality
  statement `m! (p-1)^m β_{m,n} ∈ ℤ`.
* `GranvilleMoore.neg_padicValRat_factorial_le_padicValRat_binomPolyCoeff` and
  `GranvilleMoore.padicValRat_binomPolyCoeff_nonneg`: `v_p(β_{m,n}) ≥ -v_p(m!)`, and
  `v_p(β_{m,n}) ≥ 0` when `m < p`.

## Implementation notes

The hypothesis for the evaluation lemmas is `2 ≤ p`, not `p.Prime`: nothing in them is about
primality, and both `p = 0` and `p = 1` have to be excluded because `(p : ℚ) - 1` is the
denominator being cleared and `p ^ k - 1` the numerator. Primality enters only with the
`p`-adic valuation.

The `p`-integrality of the coefficients is usually stated as the valuation inequality
`v_p(β_{m,n}) ≥ -v_p(m!)`, and that is what is proved here, in Mathlib's `padicValRat`. It is
however derived from a sharper and purely algebraic form,
`exists_intCast_eq_factorial_mul_pow_mul_binomPolyCoeff`, which says that

  `m! · (p-1)^m · β_{m,n}`

is an integer. That is the honest content of the assertion that the coefficients lie in the subring
generated by `ℤ` and `1/(p-1)` — it exhibits the denominator explicitly as a power of `p - 1` — it
needs only `p ≠ 1`, and it is the form a consumer should reach for when a concrete denominator is
more useful than a valuation bound. The valuation statement follows because `p ∤ p - 1`.

The algebraic form is proved by clearing all denominators at the level of polynomials:
`C (m! (p-1)^m) * B_m = ∏_{s<m} (X - 1 - s(p-1))`, an identity between polynomials over `ℚ`
verified pointwise with `Polynomial.funext`, whose right-hand side is visibly the image of a
polynomial over `ℤ`.
-/


-- @@ L65-65 verbatim
@[expose] public section


-- @@ L67-67 verbatim
open Finset Polynomial


-- @@ L69-69 verbatim
namespace GranvilleMoore


-- @@ L71-71 verbatim
/-! ### The value at a power of `p` -/


-- @@ L73-86 verbatim
/-- The length-`m` falling factorial of a natural number, written as a product in `ℚ`:
`∏_{s<m} (e - s) = e.descFactorial m`. Both sides vanish once `m` exceeds `e`. -/
private theorem prod_range_natCast_sub (e m : ℕ) :
    ∏ s ∈ range m, ((e : ℚ) - s) = (e.descFactorial m : ℚ) := by
  induction m with
  | zero => simp
  | succ m ih =>
    by_cases h : m ≤ e
    · rw [Finset.prod_range_succ, ih, Nat.descFactorial_succ]
      push_cast [Nat.cast_sub h]
      ring
    · rw [Nat.descFactorial_of_lt (by omega),
        Finset.prod_eq_zero (i := e) (mem_range.mpr (by omega)) (by ring)]
      simp


-- @@ L88-103 verbatim
/-- The closed form of the Frobenius exponent as a rational number:
`(p^i - 1)/(p - 1) = e_i`.

This is `GranvilleMoore.sub_one_mul_frobeniusExponent_add_one` divided by `p - 1`, and it is
the substitution that makes `B_m` a binomial coefficient at `z = p^i`. -/
theorem div_sub_one_eq_natCast_frobeniusExponent {p : ℕ} (hp : 2 ≤ p) (i : ℕ) :
    ((p : ℚ) ^ i - 1) / ((p : ℚ) - 1) = (frobeniusExponent p i : ℚ) := by
  have hp2 : (2 : ℚ) ≤ (p : ℚ) := by exact_mod_cast hp
  have hp1 : ((p : ℚ) - 1) ≠ 0 := sub_ne_zero_of_ne (ne_of_gt (by linarith))
  have hq : ((p : ℚ) - 1) * (frobeniusExponent p i : ℚ) + 1 = (p : ℚ) ^ i := by
    have h := congrArg (fun n : ℕ => (n : ℚ))
      (sub_one_mul_frobeniusExponent_add_one (p := p) (by omega) i)
    push_cast [Nat.cast_sub (show 1 ≤ p by omega)] at h
    linarith
  field_simp
  linarith


-- @@ L105-117 verbatim
/-- **The binomial polynomial evaluates the binomial coefficient**: `B_m(p^i) = C(e_i, m)`,
where `e_i` is the Frobenius exponent `∑_{r<i} p^r`.

Substituting `z = p^i` sends `(z-1)/(p-1)` to `e_i`, so the defining product of `B_m`
becomes the length-`m` falling factorial of `e_i`, and dividing it by `m!` is exactly
`C(e_i, m)`. -/
theorem eval_binomPoly_pow_eq_choose {p : ℕ} (hp : 2 ≤ p) (m i : ℕ) :
    (binomPoly p m).eval ((p : ℚ) ^ i) = ((frobeniusExponent p i).choose m : ℚ) := by
  have hfac : (m.factorial : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr m.factorial_ne_zero
  rw [eval_binomPoly, div_sub_one_eq_natCast_frobeniusExponent hp, prod_range_natCast_sub,
    Nat.descFactorial_eq_factorial_mul_choose]
  push_cast
  field_simp


-- @@ L119-119 verbatim
/-! ### The expansion of the binomial coefficient -/


-- @@ L121-133 verbatim
/-- **The binomial coefficient as a polynomial in `p^i`**:
`C(e_i, m) = ∑_{n ≤ m} β_{m,n} (p^n)^i`.

`B_m` has degree at most `m`, so it is `∑_{n ≤ m} β_{m,n} z^n`; evaluating at `z = p^i` and
using `GranvilleMoore.eval_binomPoly_pow_eq_choose` gives the claim, after rewriting
`(p^i)^n = (p^n)^i`. The point of this shape is that the right-hand side is a fixed linear
combination of the geometric progressions `i ↦ (p^n)^i`. -/
theorem natCast_choose_frobeniusExponent_eq_sum {p : ℕ} (hp : 2 ≤ p) (m i : ℕ) :
    ((frobeniusExponent p i).choose m : ℚ)
      = ∑ n ∈ range (m + 1), binomPolyCoeff p m n * ((p : ℚ) ^ n) ^ i := by
  rw [← eval_binomPoly_pow_eq_choose hp, binomPoly_eq_sum, eval_finsetSum]
  refine Finset.sum_congr rfl fun n _ => ?_
  rw [eval_mul, eval_C, eval_pow, eval_X, ← pow_mul, ← pow_mul, mul_comm i n]


-- @@ L135-135 verbatim
/-! ### The denominators of the coefficients -/


-- @@ L137-158 verbatim
/-- The binomial polynomial with all denominators cleared:
`m! (p-1)^m B_m = ∏_{s<m} (X - 1 - s(p-1))`.

Multiplying the defining product by `(p-1)^m` distributes one factor `p - 1` into each of
its `m` terms, turning `(z-1)/(p-1) - s` into `z - 1 - s(p-1)`. The right-hand side has
integer coefficients, which is the content of
`GranvilleMoore.exists_intCast_eq_factorial_mul_pow_mul_binomPolyCoeff`. -/
theorem C_mul_binomPoly_eq_prod {p : ℕ} (hp : p ≠ 1) (m : ℕ) :
    C ((m.factorial : ℚ) * ((p : ℚ) - 1) ^ m) * binomPoly p m
      = ∏ s ∈ range m, (X - 1 - C ((s : ℚ) * ((p : ℚ) - 1))) := by
  have hp1 : ((p : ℚ) - 1) ≠ 0 :=
    sub_ne_zero_of_ne fun h => hp (by exact_mod_cast h)
  have hfac : (m.factorial : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr m.factorial_ne_zero
  refine Polynomial.funext fun z => ?_
  rw [eval_mul, eval_C, eval_binomPoly, eval_prod,
    show ((p : ℚ) - 1) ^ m = ∏ _s ∈ range m, ((p : ℚ) - 1) by
      rw [Finset.prod_const, card_range],
    mul_comm (m.factorial : ℚ), mul_assoc, ← mul_assoc _ ((m.factorial : ℚ)⁻¹),
    mul_inv_cancel₀ hfac, one_mul, ← Finset.prod_mul_distrib]
  refine Finset.prod_congr rfl fun s _ => ?_
  simp only [eval_sub, eval_X, eval_one, eval_C]
  field_simp


-- @@ L160-171 verbatim
/-- The coefficients of `∏_{s<m} (X - 1 - s(p-1))` are integers: the polynomial is the
image of the corresponding product over `ℤ`. -/
private theorem exists_intCast_eq_coeff_prod (p m n : ℕ) :
    ∃ a : ℤ, (∏ s ∈ range m, (X - 1 - C ((s : ℚ) * ((p : ℚ) - 1)))).coeff n = (a : ℚ) := by
  refine ⟨(∏ s ∈ range m, (X - 1 - C ((s : ℤ) * ((p : ℤ) - 1)))).coeff n, ?_⟩
  have h : Polynomial.map (Int.castRingHom ℚ)
        (∏ s ∈ range m, (X - 1 - C ((s : ℤ) * ((p : ℤ) - 1))))
      = ∏ s ∈ range m, (X - 1 - C ((s : ℚ) * ((p : ℚ) - 1))) := by
    rw [Polynomial.map_prod]
    exact Finset.prod_congr rfl fun s _ => by simp
  rw [← h, Polynomial.coeff_map]
  rfl


-- @@ L173-185 verbatim
/-- **The denominator of `β_{m,n}` is a power of `p - 1`**: the rational number
`m! (p-1)^m β_{m,n}` is an integer.

This is the algebraic form of the `p`-integrality of the coefficients: `β_{m,n}` lies in the
subring of `ℚ` generated by `ℤ`, `1/m!` and `1/(p-1)`, with the two denominators exhibited
explicitly. Since `p ∤ p - 1`, it implies the valuation bound
`GranvilleMoore.neg_padicValRat_factorial_le_padicValRat_binomPolyCoeff`. -/
theorem exists_intCast_eq_factorial_mul_pow_mul_binomPolyCoeff {p : ℕ} (hp : p ≠ 1)
    (m n : ℕ) :
    ∃ a : ℤ, (m.factorial : ℚ) * ((p : ℚ) - 1) ^ m * binomPolyCoeff p m n = (a : ℚ) := by
  obtain ⟨a, ha⟩ := exists_intCast_eq_coeff_prod p m n
  refine ⟨a, ?_⟩
  rw [← ha, ← C_mul_binomPoly_eq_prod hp m, coeff_C_mul, binomPolyCoeff]


-- @@ L187-197 verbatim
/-- `p - 1` is a `p`-adic unit: `v_p(p - 1) = 0`. -/
theorem padicValRat_natCast_sub_one {p : ℕ} (hp : p.Prime) :
    padicValRat p ((p : ℚ) - 1) = 0 := by
  have : Fact p.Prime := ⟨hp⟩
  rw [show ((p : ℚ) - 1) = (((p : ℤ) - 1 : ℤ) : ℚ) by push_cast; ring, padicValRat.of_int,
    padicValInt.eq_zero_of_not_dvd, Nat.cast_zero]
  intro hd
  have h1 : (p : ℤ) ∣ 1 := by simpa using dvd_sub (dvd_refl (p : ℤ)) hd
  have h2 : (p : ℤ) ≤ 1 := Int.le_of_dvd zero_lt_one h1
  have h3 : (2 : ℤ) ≤ (p : ℤ) := by exact_mod_cast hp.two_le
  omega


-- @@ L199-225 verbatim
/-- **`p`-integrality of the coefficients**: `v_p(β_{m,n}) ≥ -v_p(m!)`.

The rational number `m! (p-1)^m β_{m,n}` is an integer, so has nonnegative valuation, and
`v_p((p-1)^m) = 0` because `p ∤ p - 1`; hence `v_p(β_{m,n}) ≥ -v_p(m!)`. No bound relating
`n` and `m` is needed: for `n > m` the coefficient vanishes and the inequality is trivial. -/
theorem neg_padicValRat_factorial_le_padicValRat_binomPolyCoeff {p : ℕ} (hp : p.Prime)
    (m n : ℕ) :
    -padicValRat p (m.factorial : ℚ) ≤ padicValRat p (binomPolyCoeff p m n) := by
  have : Fact p.Prime := ⟨hp⟩
  have hfac : (m.factorial : ℚ) ≠ 0 := Nat.cast_ne_zero.mpr m.factorial_ne_zero
  have hfac0 : 0 ≤ padicValRat p (m.factorial : ℚ) := by
    rw [padicValRat.of_nat]; positivity
  by_cases hb : binomPolyCoeff p m n = 0
  · rw [hb, padicValRat.zero]
    linarith
  have hp1 : ((p : ℚ) - 1) ≠ 0 :=
    sub_ne_zero_of_ne fun h => hp.ne_one (by exact_mod_cast h)
  have hpm : ((p : ℚ) - 1) ^ m ≠ 0 := pow_ne_zero _ hp1
  obtain ⟨a, ha⟩ := exists_intCast_eq_factorial_mul_pow_mul_binomPolyCoeff hp.ne_one m n
  have ha0 : (a : ℚ) ≠ 0 := ha ▸ mul_ne_zero (mul_ne_zero hfac hpm) hb
  have hint : 0 ≤ padicValRat p (a : ℚ) := by
    rw [padicValRat.of_int]; positivity
  have hval := congrArg (padicValRat p) ha
  rw [padicValRat.mul (mul_ne_zero hfac hpm) hb, padicValRat.mul hfac hpm,
    padicValRat.pow, padicValRat_natCast_sub_one hp, mul_zero, add_zero] at hval
  rw [← hval] at hint
  linarith


-- @@ L227-242 verbatim
/-- **`p`-integrality of the coefficients, small `m`**: `v_p(β_{m,n}) ≥ 0` when `m < p`.

For `m < p` no factor of `m!` is divisible by `p`, so `v_p(m!) = 0` and the bound of
`GranvilleMoore.neg_padicValRat_factorial_le_padicValRat_binomPolyCoeff` becomes
nonnegativity. -/
theorem padicValRat_binomPolyCoeff_nonneg {p : ℕ} (hp : p.Prime) {m : ℕ} (hm : m < p)
    (n : ℕ) :
    0 ≤ padicValRat p (binomPolyCoeff p m n) := by
  have : Fact p.Prime := ⟨hp⟩
  have hfac : padicValRat p (m.factorial : ℚ) = 0 := by
    rw [padicValRat.of_nat, padicValNat.eq_zero_of_not_dvd, Nat.cast_zero]
    rw [hp.dvd_factorial]
    omega
  have := neg_padicValRat_factorial_le_padicValRat_binomPolyCoeff hp m n
  rw [hfac, neg_zero] at this
  exact this


-- @@ L244-244 verbatim
end GranvilleMoore
