/-
Copyright (c) 2026 Aurélien Eveil. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Eveil, Anthropic, OpenAI
-/

/-
Generated canonical models and Singleton Variables (source Definitions 74--76
and Lemmas 77--78).

The development is one-sorted, so the source's root family is a single
witnessed MCS.  Reachability follows canonical-model outputs backwards to
their symbol arguments.  Generating paths retain the source's explicit list of
symbol/position pairs, and their contexts fill every sibling position with
`top`, exactly as in Definition 76.
-/
module

public import LeanPool.MatchingLogic.EntryIII.CanonicalCore
import LeanPool.MatchingLogic.EntryIII.MCSAlpha


-- @@ L22-24 verbatim
/-!
# MatchingLogic.EntryIII.Generated
-/


-- @@ L26-26 verbatim
@[expose] public section


-- @@ L28-28 verbatim
namespace MatchingLogic


-- @@ L30-30 verbatim
open Set


-- @@ L32-32 verbatim
variable {S : Signature}


-- @@ L34-34 verbatim
noncomputable section


-- @@ L36-38 verbatim
/-- Local decidable equality used by the generated-submodel construction. -/
local instance instDecidableEqPatternNatGenerated : DecidableEq (Pattern S Nat) :=
  Classical.decEq _


-- @@ L40-40 verbatim
/-! ### Application-context composition -/


-- @@ L42-42 verbatim
namespace AppCtx


-- @@ L44-48 verbatim
/-- Context composition: `outer.comp inner` plugs `inner` into `outer`. -/
def comp {Var : Type} (outer inner : AppCtx S Var) : AppCtx S Var :=
  match outer with
  | .hole => inner
  | .node sigma i args tail => .node sigma i args (comp tail inner)


-- @@ L50-56 verbatim
@[simp] theorem plug_comp {Var : Type}
    (outer inner : AppCtx S Var) (p : Pattern S Var) :
    (outer.comp inner).plug p = outer.plug (inner.plug p) := by
  induction outer with
  | hole => rfl
  | node sigma i args tail ih =>
      simp [comp, AppCtx.plug, ih]


-- @@ L58-58 verbatim
end AppCtx


-- @@ L60-60 verbatim
/-! ### Definition 74: generated canonical model -/


-- @@ L62-68 verbatim
/-- One backwards canonical step, from an output world to one component world
of a tuple producing it. -/
def canonicalStep (parent child : CanonicalCarrier S) : Prop :=
  ∃ (sigma : S.Sym)
    (components : Fin (S.arity sigma) → CanonicalCarrier S)
    (i : Fin (S.arity sigma)),
    parent ∈ canonicalInterp sigma components ∧ child = components i


-- @@ L70-76 verbatim
@[simp] theorem canonicalStep_iff (parent child : CanonicalCarrier S) :
    canonicalStep parent child ↔
      ∃ (sigma : S.Sym)
        (components : Fin (S.arity sigma) → CanonicalCarrier S)
        (i : Fin (S.arity sigma)),
        parent ∈ canonicalInterp sigma components ∧ child = components i :=
  Iff.rfl


-- @@ L78-81 verbatim
/-- The smallest set of canonical worlds containing `root` and closed under
backwards canonical symbol steps. -/
def Generated (root world : CanonicalCarrier S) : Prop :=
  Relation.ReflTransGen canonicalStep root world


-- @@ L83-85 verbatim
/-- The carrier of the submodel generated by `root`. -/
abbrev GeneratedCarrier (root : CanonicalCarrier S) :=
  {world : CanonicalCarrier S // Generated root world}


-- @@ L87-87 verbatim
namespace GeneratedCarrier


-- @@ L89-92 verbatim
/-- A generated point still carries its canonical MCS proof. -/
theorem isMCS {root : CanonicalCarrier S} (world : GeneratedCarrier root) :
    IsMCS world.val.val :=
  CanonicalCarrier.isMCS world.val


-- @@ L94-97 verbatim
/-- A generated point still carries its canonical witnessedness proof. -/
theorem witnessed {root : CanonicalCarrier S} (world : GeneratedCarrier root) :
    Witnessed world.val.val :=
  CanonicalCarrier.witnessed world.val


-- @@ L99-99 verbatim
end GeneratedCarrier


-- @@ L101-103 verbatim
/-- The root as a point of its generated carrier. -/
def generatedRoot (root : CanonicalCarrier S) : GeneratedCarrier root :=
  ⟨root, Relation.ReflTransGen.refl⟩


-- @@ L105-109 verbatim
/-- The canonical interpretation restricted to generated inputs and outputs. -/
def generatedInterp (root : CanonicalCarrier S) (sigma : S.Sym)
    (components : Fin (S.arity sigma) → GeneratedCarrier root) :
    Set (GeneratedCarrier root) :=
  {world | world.val ∈ canonicalInterp sigma (fun i => (components i).val)}


-- @@ L111-115 verbatim
/-- The submodel generated backwards from `root`. -/
abbrev generatedModel (root : CanonicalCarrier S) : Model S where
  carrier := GeneratedCarrier root
  nonempty := ⟨generatedRoot root⟩
  interp := generatedInterp root


-- @@ L117-122 verbatim
@[simp] theorem mem_generatedInterp {root : CanonicalCarrier S} {sigma : S.Sym}
    {components : Fin (S.arity sigma) → GeneratedCarrier root}
    {world : GeneratedCarrier root} :
    world ∈ generatedInterp root sigma components ↔
      world.val ∈ canonicalInterp sigma (fun i => (components i).val) :=
  Iff.rfl


-- @@ L124-129 verbatim
@[simp] theorem generatedModel_interp (root : CanonicalCarrier S)
    (sigma : S.Sym)
    (components : Fin (S.arity sigma) → GeneratedCarrier root) :
    (generatedModel root).interp sigma components =
      generatedInterp root sigma components :=
  rfl


-- @@ L131-136 verbatim
theorem mem_generatedModel_interp {root : CanonicalCarrier S}
    {sigma : S.Sym} {components : Fin (S.arity sigma) → GeneratedCarrier root}
    {world : GeneratedCarrier root} :
    world ∈ (generatedModel root).interp sigma components ↔
      world.val ∈ canonicalInterp sigma (fun i => (components i).val) :=
  Iff.rfl


-- @@ L138-138 verbatim
/-! ### Definitions 75--76: generating paths and their contexts -/


-- @@ L140-151 verbatim
/-- The source's explicit generating-path relation.  A new coordinate is
appended when an output world is followed to one of its argument worlds. -/
inductive GeneratingPath (root : CanonicalCarrier S) :
    CanonicalCarrier S → List (Coord S) → Prop
  | root : GeneratingPath root root []
  | tail {parent : CanonicalCarrier S} {path : List (Coord S)}
      {sigma : S.Sym}
      {components : Fin (S.arity sigma) → CanonicalCarrier S}
      {i : Fin (S.arity sigma)} :
      GeneratingPath root parent path →
      parent ∈ canonicalInterp sigma components →
      GeneratingPath root (components i) (path ++ [⟨sigma, i⟩])


-- @@ L153-156 verbatim
/-- The one-step context for a generating coordinate, with `top` in all
sibling positions as required by source Definition 76. -/
def generatingStepContext (e : Coord S) : AppCtx S Nat :=
  .node e.1 e.2 (fun _ => Pattern.tp) .hole


-- @@ L158-161 verbatim
@[simp] theorem generatingStepContext_plug (e : Coord S) (p : Pattern S Nat) :
    (generatingStepContext e).plug p =
      .app e.1 (Function.update (fun _ => Pattern.tp) e.2 p) :=
  rfl


-- @@ L163-166 verbatim
/-- The symbol context `C_path`, obtained by nesting one-step contexts in path
order. -/
def generatingContext (path : List (Coord S)) : AppCtx S Nat :=
  path.foldl (fun C e => C.comp (generatingStepContext e)) .hole


-- @@ L168-170 verbatim
@[simp] theorem generatingContext_nil :
    generatingContext ([] : List (Coord S)) = (.hole : AppCtx S Nat) :=
  rfl


-- @@ L172-175 verbatim
theorem generatingContext_append (path : List (Coord S)) (e : Coord S) :
    generatingContext (path ++ [e]) =
      (generatingContext path).comp (generatingStepContext e) := by
  simp [generatingContext, List.foldl_append]


-- @@ L177-181 verbatim
/-- Every canonical MCS contains `top`. -/
theorem CanonicalCarrier.top_mem (world : CanonicalCarrier S) :
    (Pattern.tp : Pattern S Nat) ∈ (world : Set (Pattern S Nat)) :=
  (CanonicalCarrier.isMCS world).mem_of_provable_empty
    (provable_top (∅ : Set (Pattern S Nat)))


-- @@ L183-191 verbatim
/-- A source generating path witnesses membership in the reachability closure. -/
theorem GeneratingPath.generated {root world : CanonicalCarrier S}
    {path : List (Coord S)} (hpath : GeneratingPath root world path) :
    Generated root world := by
  induction hpath with
  | root => exact Relation.ReflTransGen.refl
  | @tail parent path sigma components i hpath hinterp ih =>
      exact ih.tail (canonicalStep_iff parent (components i) |>.mpr
        ⟨sigma, components, i, hinterp, rfl⟩)


-- @@ L193-203 verbatim
/-- Reachability and the paper's explicit generating-path relation agree. -/
theorem Generated.exists_generatingPath {root world : CanonicalCarrier S}
    (hgen : Generated root world) :
    ∃ path : List (Coord S), GeneratingPath root world path := by
  induction hgen with
  | refl => exact ⟨[], .root⟩
  | @tail parent child hreach hstep ih =>
      obtain ⟨path, hpath⟩ := ih
      rw [canonicalStep_iff] at hstep
      obtain ⟨sigma, components, i, hinterp, rfl⟩ := hstep
      exact ⟨path ++ [⟨sigma, i⟩], .tail hpath hinterp⟩


-- @@ L205-229 verbatim
/-- Source Lemma 77: a generating context transports every member of its end
world back into the root MCS. -/
theorem GeneratingPath.plug_mem_root {root world : CanonicalCarrier S}
    {path : List (Coord S)} (hpath : GeneratingPath root world path)
    {p : Pattern S Nat} (hp : p ∈ (world : Set (Pattern S Nat))) :
    (generatingContext path).plug p ∈ (root : Set (Pattern S Nat)) := by
  induction hpath generalizing p with
  | root => simpa [generatingContext, AppCtx.plug] using hp
  | @tail parent path sigma components i hpath hinterp ih =>
      let args : Fin (S.arity sigma) → Pattern S Nat :=
        Function.update (fun _ => Pattern.tp) i p
      have hargs : ∀ j, args j ∈ (components j : Set (Pattern S Nat)) := by
        intro j
        by_cases hji : j = i
        · subst j
          simpa [args] using hp
        · rw [show args j = Pattern.tp by simp [args, hji]]
          exact CanonicalCarrier.top_mem (components j)
      have happ : Pattern.app sigma args ∈
          (parent : Set (Pattern S Nat)) :=
        (mem_canonicalInterp.mp hinterp) args hargs
      have hout := ih happ
      rw [generatingContext_append, AppCtx.plug_comp,
        generatingStepContext_plug]
      exact hout


-- @@ L231-239 verbatim
/-- Every reachable world has a context transporting all of its members into
the root. -/
theorem Generated.exists_generatingContext {root world : CanonicalCarrier S}
    (hgen : Generated root world) :
    ∃ C : AppCtx S Nat,
      ∀ p ∈ (world : Set (Pattern S Nat)),
        C.plug p ∈ (root : Set (Pattern S Nat)) := by
  obtain ⟨path, hpath⟩ := hgen.exists_generatingPath
  exact ⟨generatingContext path, fun _ hp => hpath.plug_mem_root hp⟩


-- @@ L241-241 verbatim
/-! ### Lemma 78: Singleton Variables -/


-- @@ L243-274 verbatim
private theorem subset_of_shared_var_and_paths
    (root left right : CanonicalCarrier S)
    {leftPath rightPath : List (Coord S)}
    (hleftPath : GeneratingPath root left leftPath)
    (hrightPath : GeneratingPath root right rightPath)
    {x : Nat} (hxleft : Pattern.var x ∈ (left : Set (Pattern S Nat)))
    (hxright : Pattern.var x ∈ (right : Set (Pattern S Nat))) :
    (left : Set (Pattern S Nat)) ⊆ (right : Set (Pattern S Nat)) := by
  intro p hp
  by_contra hnright
  have hntp : Pattern.nt p ∈ (right : Set (Pattern S Nat)) :=
    (CanonicalCarrier.isMCS right).neg_mem_iff_not_mem.mpr hnright
  have hleftAnd : Pattern.and (.var x) p ∈
      (left : Set (Pattern S Nat)) :=
    (CanonicalCarrier.isMCS left).and_mem_iff.mpr ⟨hxleft, hp⟩
  have hrightAnd : Pattern.and (.var x) (Pattern.nt p) ∈
      (right : Set (Pattern S Nat)) :=
    (CanonicalCarrier.isMCS right).and_mem_iff.mpr ⟨hxright, hntp⟩
  have hleftRoot := hleftPath.plug_mem_root hleftAnd
  have hrightRoot := hrightPath.plug_mem_root hrightAnd
  have hsingle : Provable (∅ : Set (Pattern S Nat))
      (.imp ((generatingContext leftPath).plug (Pattern.and (.var x) p))
        (Pattern.nt
          ((generatingContext rightPath).plug
            (Pattern.and (.var x) (Pattern.nt p))))) :=
    Provable.singleton (generatingContext leftPath) (generatingContext rightPath)
  have hsingleRoot :=
    (CanonicalCarrier.isMCS root).mem_of_provable_empty hsingle
  have hnotRight :=
    (CanonicalCarrier.isMCS root).mp_mem hleftRoot hsingleRoot
  exact (CanonicalCarrier.isMCS root).1
    ((LocProvable.of_mem hrightRoot).mp (LocProvable.of_mem hnotRight))


-- @@ L276-289 verbatim
/-- Source Lemma 78: a variable pattern belongs to at most one reachable
canonical world. -/
theorem generated_singleton_variables (root : CanonicalCarrier S)
    {left right : CanonicalCarrier S}
    (hleft : Generated root left) (hright : Generated root right)
    {x : Nat} (hxleft : Pattern.var x ∈ (left : Set (Pattern S Nat)))
    (hxright : Pattern.var x ∈ (right : Set (Pattern S Nat))) :
    left = right := by
  obtain ⟨leftPath, hleftPath⟩ := hleft.exists_generatingPath
  obtain ⟨rightPath, hrightPath⟩ := hright.exists_generatingPath
  apply Subtype.ext
  exact Set.Subset.antisymm
    (subset_of_shared_var_and_paths root left right hleftPath hrightPath hxleft hxright)
    (subset_of_shared_var_and_paths root right left hrightPath hleftPath hxright hxleft)


-- @@ L291-299 verbatim
/-- Carrier form of Singleton Variables, used by the later completed
valuation. -/
theorem GeneratedCarrier.eq_of_var_mem {root : CanonicalCarrier S}
    (left right : GeneratedCarrier root) {x : Nat}
    (hxleft : Pattern.var x ∈ left.val.val)
    (hxright : Pattern.var x ∈ right.val.val) :
    left = right := by
  apply Subtype.ext
  exact generated_singleton_variables root left.property right.property hxleft hxright


-- @@ L301-301 verbatim
end


-- @@ L303-303 verbatim
end MatchingLogic
