/-
Copyright (c) 2026 Hyeon Seung-Hyeon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hyeon Seung-Hyeon
-/

-- Adapted for Lean Pool from 0stellensatz/MassFormula at 7fa41a621f724f110183904d3fd19c6730a932ad.
module

public import LeanPool.MassFormula.Defs
import LeanPool.MassFormula.Discriminant
import LeanPool.MassFormula.EisensteinMonogenic
import Mathlib.NumberTheory.ArithmeticFunction.Misc
import Mathlib.RingTheory.Henselian


-- @@ L16-44 verbatim
/-!
# Auxiliary file: `ncard_isomorphic_mul_w`—the orbit count of Remark 3°

Every `L` in `sigma K n` is isomorphic to `n` / `w L` elements of `sigma K n`. We express this
by multiplying the cardinality of the isomorphism class by `w L`
([Serre 1978, Remark 3°, p.1031][Serre1978]). The count is the classical embedding argument:

- `L` / `K` is separable of degree `n` and `SeparableClosure K` is separably closed, so `L` has
  exactly `n` embeddings into `SeparableClosure K` (`natCard_algHom`, via
  `Field.embEquivOfAdjoinSplits` and `Field.finSepDegree_eq_finrank_of_isSeparable`).
- The image of an embedding stays in `sigma K n` (`fieldRange_mem_sigma`): by
  `exists_eisenstein_generator` `L` is generated by a root `x` of an Eisenstein polynomial, an
  embedding transports the generator with the *same* minimal polynomial over `𝒪[K]`, and
  `isTotallyRamified_adjoin` applies to the image—which is `IntermediateField.adjoin K {σ x}`—as it
  stands. No transport of `integers` or of the ramification data along the isomorphism is needed.
- The embeddings with a given image `M` are a torsor under the `K`-automorphisms of `L`: after
  choosing one isomorphism `e M` onto each member of the class, the map sending `(M, g)` to the
  composite of `g`, then `e M`, then the inclusion of `M` is a bijection from (class) ×
  (automorphisms) onto the embeddings.

Taking `Nat.card` of the bijection gives that the number of `M` isomorphic to `L`, times `w L`, is
`n`, with no finiteness bookkeeping: `Nat.card` is junk-`0`-safe on both sides, and the finiteness
of the class is itself a corollary of the count.

## References

* [Serre1978] J-P. Serre, *Une «formule de masse» pour les extensions totalement ramifiées de
  degré donné d'un corps local*, C. R. Acad. Sci. Paris **286** (1978), Série A, 1031–1036.
-/


-- @@ L46-46 verbatim
@[expose] public section


-- @@ L48-48 verbatim
open ValuativeRel


-- @@ L50-50 verbatim
namespace MassFormula


-- @@ L52-53 verbatim
variable (K : Type*) [Field K] [ValuativeRel K] [UniformSpace K] [IsUniformAddGroup K]
  [IsNonarchimedeanLocalField K]


-- @@ L55-103 verbatim
omit [IsUniformAddGroup K] in
/-- The invariance of `sigma K n` under `K`-isomorphism: the image of a member of `sigma K n` under
a `K`-embedding into `SeparableClosure K` is again a member. The embedding transports an Eisenstein
generator (`exists_eisenstein_generator`) onto a generator of the image with the same minimal
polynomial over `𝒪[K]` (`minpoly.algHom_eq`), so `isTotallyRamified_adjoin` makes the image totally
ramified with no transport of `integers` or of the ramification data. -/
private theorem fieldRange_mem_sigma (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ sigma K n)
    (σ : ↥L →ₐ[K] SeparableClosure K) : σ.fieldRange ∈ sigma K n := by
  obtain ⟨x, π, hπ, hint, hei, hadj, -⟩ := exists_eisenstein_generator K n hn L hL
  have hxL : x ∈ L := hadj ▸ IntermediateField.mem_adjoin_simple_self K x
  -- the generator inside `L`, and its image under the embedding
  set ξ : ↥L := ⟨x, hxL⟩ with hξ
  set x' : SeparableClosure K := σ ξ with hx'
  -- the minimal polynomial over `𝒪[K]` is transported unchanged
  have hminx : minpoly ↥𝒪[K] x = minpoly ↥𝒪[K] ξ :=
    minpoly.algHom_eq (L.val.restrictScalars ↥𝒪[K])
      (L.val.restrictScalars ↥𝒪[K]).toRingHom.injective ξ
  have hminx' : minpoly ↥𝒪[K] x' = minpoly ↥𝒪[K] ξ :=
    minpoly.algHom_eq (σ.restrictScalars ↥𝒪[K])
      (σ.restrictScalars ↥𝒪[K]).toRingHom.injective ξ
  have hintξ : IsIntegral ↥𝒪[K] ξ :=
    (isIntegral_algHom_iff (L.val.restrictScalars ↥𝒪[K])
      (L.val.restrictScalars ↥𝒪[K]).toRingHom.injective).mp hint
  have hint' : IsIntegral ↥𝒪[K] x' := hintξ.map (σ.restrictScalars ↥𝒪[K])
  have hei' : (minpoly ↥𝒪[K] x').IsEisensteinAt (Submodule.span ↥𝒪[K] {π}) := by
    rw [hminx', ← hminx]
    exact hei
  -- the range of the embedding is generated by the image of the generator
  have halgx : IsAlgebraic K x := hint.tower_top.isAlgebraic
  have halgx' : IsAlgebraic K x' := hint'.tower_top.isAlgebraic
  have htop : (⊤ : Subalgebra K ↥L) = Algebra.adjoin K {ξ} := by
    apply Subalgebra.map_injective (f := L.val) L.val.toRingHom.injective
    rw [Algebra.map_top, IntermediateField.range_val, AlgHom.map_adjoin, Set.image_singleton,
      show L.val ξ = x from rfl, ← hadj,
      IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic halgx]
  have hrange : σ.fieldRange = IntermediateField.adjoin K {x'} := by
    apply IntermediateField.toSubalgebra_injective
    rw [AlgHom.fieldRange_toSubalgebra,
      IntermediateField.adjoin_simple_toSubalgebra_of_isAlgebraic halgx',
      ← Algebra.map_top, htop, AlgHom.map_adjoin, Set.image_singleton, hx']
  -- degree along the isomorphism onto the range, total ramifiedness from the Eisenstein root
  have e0 : ↥L ≃ₐ[K] ↥σ.fieldRange := AlgEquiv.ofInjectiveField σ
  have hfr : Module.finrank K ↥σ.fieldRange = n := by
    rw [← e0.toLinearEquiv.finrank_eq]
    exact hL.1
  refine mem_sigma.mpr ⟨hfr, ?_⟩
  rw [hrange]
  exact isTotallyRamified_adjoin hπ hint' hei'


-- @@ L105-121 verbatim
omit [IsUniformAddGroup K] in
/-- `L` has exactly `n` `K`-embeddings into `SeparableClosure K`: the separable degree of the
separable extension `L` / `K` equals its degree `n`, and every separable minimal polynomial splits
in the separably closed `SeparableClosure K`. -/
private theorem natCard_algHom (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ sigma K n) :
    Nat.card (↥L →ₐ[K] SeparableClosure K) = n := by
  have : FiniteDimensional K ↥L := FiniteDimensional.of_finrank_pos (by rw [hL.1]; exact hn)
  have hequiv : Field.Emb K ↥L ≃ (↥L →ₐ[K] SeparableClosure K) :=
    Field.embEquivOfAdjoinSplits (F := K) (E := ↥L) (K := SeparableClosure K) (S := Set.univ)
      (IntermediateField.adjoin_univ K ↥L)
      (fun s _ => ⟨IsIntegral.of_finite K s,
        IsSepClosed.splits_codomain _ (Algebra.IsSeparable.isSeparable K s)⟩)
  rw [← Nat.card_congr hequiv,
    show Nat.card (Field.Emb K ↥L) = Field.finSepDegree K ↥L from rfl,
    Field.finSepDegree_eq_finrank_of_isSeparable]
  exact hL.1


-- @@ L123-185 verbatim
omit [IsUniformAddGroup K] in
/-- The number of members of `sigma K n` that are `K`-isomorphic to `L`, times `w L`, is `n`
([Serre 1978, Remark 3°, p.1031][Serre1978]). The bijection behind the count sends a member `M` of
the class and a `K`-automorphism `g` of `L` to the embedding of `L` into `SeparableClosure K`
composing `g`, a chosen isomorphism `e M` onto `M`, and the inclusion of `M`; the embeddings number
`n` (`natCard_algHom`), and their images all lie in the class (`fieldRange_mem_sigma`). -/
theorem ncard_isomorphic_mul_w (n : ℕ) (hn : 0 < n)
    (L : IntermediateField K (SeparableClosure K)) (hL : L ∈ sigma K n) :
    ({M ∈ sigma K n | Nonempty (↥L ≃ₐ[K] ↥M)}).ncard * w L = n := by
  classical
  set S : Set (IntermediateField K (SeparableClosure K)) :=
    {M ∈ sigma K n | Nonempty (↥L ≃ₐ[K] ↥M)} with hSdef
  -- a chosen isomorphism onto each member of the class
  have e : ∀ M : ↥S, ↥L ≃ₐ[K] ↥M.1 := fun M => Classical.choice (Set.mem_sep_iff.mp M.2).2
  -- the bijection: (member of the class, automorphism) ↦ embedding
  set F : ↥S × (↥L ≃ₐ[K] ↥L) → (↥L →ₐ[K] SeparableClosure K) :=
    fun p => (p.1.1.val.comp (e p.1).toAlgHom).comp p.2.toAlgHom with hFdef
  have hFapply : ∀ (M : ↥S) (g : ↥L ≃ₐ[K] ↥L) (y : ↥L),
      F (M, g) y = ((e M) (g y) : SeparableClosure K) := fun M g y => rfl
  -- the range of `F (M, g)` recovers `M`
  have hFrange : ∀ (M : ↥S) (g : ↥L ≃ₐ[K] ↥L), (F (M, g)).fieldRange = M.1 := by
    intro M g
    apply le_antisymm
    · rintro z ⟨y, rfl⟩
      exact ((e M) (g y)).2
    · intro z hz
      refine ⟨g.symm ((e M).symm ⟨z, hz⟩), ?_⟩
      change F (M, g) (g.symm ((e M).symm ⟨z, hz⟩)) = z
      rw [hFapply, AlgEquiv.apply_symm_apply, AlgEquiv.apply_symm_apply]
  have hFbij : Function.Bijective F := by
    constructor
    · -- the range recovers the member, and the two injections cancel
      rintro ⟨M, g⟩ ⟨M', g'⟩ hFeq
      have hMM' : M = M' := Subtype.ext (by rw [← hFrange M g, ← hFrange M' g', hFeq])
      subst hMM'
      have hg : g = g' := by
        refine AlgEquiv.ext fun y => ?_
        have h1 : F (M, g) y = F (M, g') y := by rw [hFeq]
        rw [hFapply, hFapply] at h1
        exact (e M).injective (Subtype.coe_injective h1)
      rw [hg]
    · -- every embedding arises: its range is in the class, and the choice mismatch is an
      -- automorphism
      intro σ
      have hmem : σ.fieldRange ∈ S :=
        Set.mem_sep_iff.mpr ⟨fieldRange_mem_sigma K n hn L hL σ,
          ⟨AlgEquiv.ofInjectiveField σ⟩⟩
      set M₀ : ↥S := ⟨σ.fieldRange, hmem⟩ with hM₀
      set g₀ : ↥L ≃ₐ[K] ↥L :=
        (AlgEquiv.ofInjectiveField σ : ↥L ≃ₐ[K] ↥σ.fieldRange).trans (e M₀).symm with hg₀
      refine ⟨(M₀, g₀), ?_⟩
      refine AlgHom.ext fun y => ?_
      rw [hFapply]
      have h2 : (e M₀) (g₀ y) =
          (AlgEquiv.ofInjectiveField σ : ↥L ≃ₐ[K] ↥σ.fieldRange) y :=
        AlgEquiv.apply_symm_apply (e M₀) _
      rw [h2]
      rfl
  -- take `Nat.card` of the bijection
  have hcard : Nat.card (↥S × (↥L ≃ₐ[K] ↥L)) = Nat.card (↥L →ₐ[K] SeparableClosure K) :=
    Nat.card_eq_of_bijective F hFbij
  rw [Nat.card_prod, natCard_algHom K n hn L hL, Nat.card_coe_set_eq] at hcard
  exact hcard


-- @@ L187-187 verbatim
end MassFormula
