/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/
module

public import LeanPool.Wallace.NontrivialSequences
public import Mathlib.Analysis.Normed.Group.Quotient
import Mathlib.Analysis.Normed.Group.AddCircle


-- @@ L12-23 verbatim
/-!
# Full topological consequences of the character construction

This file isolates the exact output needed to obtain the group theorem, rather than only its
nonnegative-cone consequence.  A `FullCharacterPackage` codes every injective sequence, assigns
it a genuine subsequence and a free ultrafilter, and supplies a point-separating family of
circle-valued characters for which that subsequence has a prescribed nonzero limit.

The initial topology of such a package is Hausdorff, is a group topology, is countably compact,
and has no non-eventually-constant convergent sequences.  Its canonical induced uniformity is
totally bounded, which is the uniform formulation of precompactness used here.
-/


-- @@ L25-25 verbatim
@[expose] public section


-- @@ L27-27 verbatim
open Filter Set Topology


-- @@ L29-29 verbatim
universe u v


-- @@ L31-31 verbatim
namespace Wallace


-- @@ L33-33 verbatim
noncomputable section


-- @@ L35-35 verbatim
/-! ## Countable compactness from the nonzero-limit property -/


-- @@ L37-53 verbatim
/-- The nonzero ultrafilter-limit property gives an accumulation point for every infinite set. -/
theorem infiniteSet_accumulation_of_nonzero_ultrafilter_limits
    {X : Type u} [TopologicalSpace X] [Zero X]
    (hlimits : HasNonzeroLimitProperty X) :
    HasInfiniteSetAccumulationProperty X := by
  intro B hBinf
  let e : ℕ ↪ B := hBinf.natEmbedding
  let s : ℕ → X := fun n ↦ e n
  have sinj : Function.Injective s := Subtype.val_injective.comp e.injective
  obtain ⟨φ, x, p, hφ, _hx, hfree, htendsto⟩ := hlimits s sinj
  have uinj : Function.Injective (s ∘ φ) := sinj.comp hφ.injective
  have hacc : AccPt x (Filter.principal (Set.range (s ∘ φ))) :=
    accPt_range_of_free_ultrafilter_limit uinj hfree htendsto
  refine ⟨x, hacc.mono <| Filter.principal_mono.2 ?_⟩
  intro y hy
  obtain ⟨n, rfl⟩ := hy
  exact (e (φ n)).property


-- @@ L55-61 verbatim
/-- In a `T₁` space, the package's ultrafilter limits imply countable compactness. -/
theorem countablyCompact_of_nonzero_ultrafilter_limits
    {X : Type u} [TopologicalSpace X] [Zero X] [T1Space X]
    (hlimits : HasNonzeroLimitProperty X) :
    CountablyCompactSpace X :=
  countablyCompact_of_infiniteSet_accumulation
    (infiniteSet_accumulation_of_nonzero_ultrafilter_limits hlimits)


-- @@ L63-63 verbatim
/-! ## A group-independent character package -/


-- @@ L65-91 verbatim
/-- The exact character data from which all conclusions of the group theorem follow.  This
interface applies without change to free Abelian groups and rational vector groups. -/
structure FullCharacterPackage (G : Type u) [AddCommGroup G] where
  /-- Codes for injective sequences in `G`. -/
  Code : Type v
  /-- The identification of codes with injective sequences. -/
  codeEquiv : Code ≃ InjectiveSequence' G
  /-- The selected subsequence of the sequence represented by each code. -/
  subsequence : Code → ℕ → ℕ
  subsequence_strictMono : ∀ c, StrictMono (subsequence c)
  /-- The free ultrafilter along which the selected subsequence converges. -/
  ultrafilter : Code → Ultrafilter ℕ
  ultrafilter_free : ∀ c, (ultrafilter c : Filter ℕ) ≤ cofinite
  /-- The prescribed nonzero limit of the selected subsequence. -/
  limitPoint : Code → G
  limitPoint_ne_zero : ∀ c, limitPoint c ≠ 0
  /-- Indices for the separating family of circle-valued characters. -/
  CharacterIndex : Type v
  /-- The separating family of circle-valued additive characters. -/
  character : CharacterIndex → G →+ UnitAddCircle
  character_detects : ∀ x : G, x ≠ 0 → ∃ j, character j x ≠ 0
  character_limit :
    ∀ (c : Code) (j : CharacterIndex),
      Tendsto
        (fun n ↦ character j ((codeEquiv c).1 (subsequence c n)))
        (ultrafilter c)
        (𝓝 (character j (limitPoint c)))


-- @@ L93-93 verbatim
namespace FullCharacterPackage


-- @@ L95-95 verbatim
variable {G : Type u} [AddCommGroup G]


-- @@ L97-102 verbatim
/-- Simultaneous evaluation by all characters in the package. -/
def evaluation (C : FullCharacterPackage G) :
    G →+ (C.CharacterIndex → UnitAddCircle) where
  toFun x j := C.character j x
  map_zero' := by ext j; simp
  map_add' x y := by ext j; simp


-- @@ L104-106 verbatim
/-- The initial topology generated by the package's characters. -/
@[reducible] def initialTopology (C : FullCharacterPackage G) : TopologicalSpace G :=
  TopologicalSpace.induced C.evaluation inferInstance


-- @@ L108-110 verbatim
/-- The uniformity pulled back from the compact power of the circle. -/
@[reducible] def initialUniformSpace (C : FullCharacterPackage G) : UniformSpace G :=
  UniformSpace.comap C.evaluation inferInstance


-- @@ L112-113 verbatim
theorem initialUniformSpace_toTopology (C : FullCharacterPackage G) :
    C.initialUniformSpace.toTopologicalSpace = C.initialTopology := rfl


-- @@ L115-119 verbatim
/-- The pulled-back uniformity is the canonical uniform group structure induced by the diagonal
homomorphism. -/
theorem initial_isUniformAddGroup (C : FullCharacterPackage G) :
    @IsUniformAddGroup G C.initialUniformSpace _ :=
  IsUniformAddGroup.comap C.evaluation


-- @@ L121-130 verbatim
theorem evaluation_injective (C : FullCharacterPackage G) :
    Function.Injective C.evaluation := by
  intro x y hxy
  apply sub_eq_zero.mp
  by_contra hsub
  obtain ⟨j, hj⟩ := C.character_detects (x - y) hsub
  apply hj
  rw [map_sub]
  have hcoord : C.character j x = C.character j y := congrFun hxy j
  rw [hcoord, sub_self]


-- @@ L132-134 verbatim
theorem initial_isTopologicalAddGroup (C : FullCharacterPackage G) :
    @IsTopologicalAddGroup G C.initialTopology _ :=
  isTopologicalAddGroup_induced C.evaluation


-- @@ L136-139 verbatim
theorem initial_t2Space (C : FullCharacterPackage G) :
    @T2Space G C.initialTopology := by
  let : TopologicalSpace G := C.initialTopology
  exact C.evaluation_injective.isEmbedding_induced.t2Space


-- @@ L141-151 verbatim
/-- The selected subsequence converges to its prescribed point in the initial topology. -/
theorem prepared_tendsto_limitPoint (C : FullCharacterPackage G) (c : C.Code) :
    Tendsto
      (fun n ↦ (C.codeEquiv c).1 (C.subsequence c n))
      (C.ultrafilter c)
      (@nhds G C.initialTopology (C.limitPoint c)) := by
  let : TopologicalSpace G := C.initialTopology
  have hinducing : IsInducing C.evaluation := ⟨rfl⟩
  refine hinducing.tendsto_nhds_iff.mpr ?_
  refine tendsto_pi_nhds.2 fun j ↦ ?_
  simpa [evaluation, Function.comp_def] using C.character_limit c j


-- @@ L153-165 verbatim
theorem hasNonzeroLimitProperty (C : FullCharacterPackage G) :
    @HasNonzeroLimitProperty G C.initialTopology _ := by
  intro s hs
  let encoded : InjectiveSequence' G := ⟨s, hs⟩
  let c : C.Code := C.codeEquiv.symm encoded
  have hcoded : (C.codeEquiv c).1 = s :=
    congrArg Subtype.val (C.codeEquiv.apply_symm_apply encoded)
  refine ⟨C.subsequence c, C.limitPoint c, C.ultrafilter c,
    C.subsequence_strictMono c, C.limitPoint_ne_zero c,
    C.ultrafilter_free c, ?_⟩
  change Tendsto (fun n ↦ s (C.subsequence c n)) (C.ultrafilter c) _
  rw [← hcoded]
  exact C.prepared_tendsto_limitPoint c


-- @@ L167-172 verbatim
theorem initial_countablyCompactSpace (C : FullCharacterPackage G) :
    @CountablyCompactSpace G C.initialTopology := by
  let : TopologicalSpace G := C.initialTopology
  let : T2Space G := C.initial_t2Space
  exact countablyCompact_of_nonzero_ultrafilter_limits
    C.hasNonzeroLimitProperty


-- @@ L174-181 verbatim
theorem initial_noInjectiveConvergentSequences (C : FullCharacterPackage G) :
    ∀ s : ℕ → G, Function.Injective s →
      ¬ ∃ x : G, Tendsto s atTop (@nhds G C.initialTopology x) := by
  let : TopologicalSpace G := C.initialTopology
  let : IsTopologicalAddGroup G := C.initial_isTopologicalAddGroup
  let : T2Space G := C.initial_t2Space
  exact no_injective_sequence_converges_of_nonzeroLimitProperty
    C.hasNonzeroLimitProperty


-- @@ L183-192 verbatim
theorem initial_onlyEventuallyConstantConvergentSequences
    (C : FullCharacterPackage G) :
    ∀ (s : ℕ → G) (x : G),
      Tendsto s atTop (@nhds G C.initialTopology x) →
        ∀ᶠ n in atTop, s n = x := by
  let : TopologicalSpace G := C.initialTopology
  let : T2Space G := C.initial_t2Space
  intro s x hs
  exact eventually_eq_limit_of_no_injective_sequence_converges
    C.initial_noInjectiveConvergentSequences hs


-- @@ L194-203 verbatim
/-- The induced uniformity is totally bounded because the target is a compact power of the
circle. -/
theorem initial_totallyBounded (C : FullCharacterPackage G) :
    @TotallyBounded G C.initialUniformSpace Set.univ := by
  let : UniformSpace G := C.initialUniformSpace
  have hinducing : IsUniformInducing C.evaluation := ⟨rfl⟩
  have htarget : TotallyBounded
      (Set.univ : Set (C.CharacterIndex → UnitAddCircle)) :=
    isCompact_univ.totallyBounded
  simpa using totallyBounded_preimage hinducing htarget


-- @@ L205-205 verbatim
end FullCharacterPackage


-- @@ L207-207 verbatim
/-! ## The package already constructed for the free Abelian group -/


-- @@ L209-209 verbatim
namespace SeparationPackage


-- @@ L211-211 verbatim
variable {I : Type u}


-- @@ L213-227 verbatim
/-- Regard the existing free-Abelian separation package as a full character package. -/
def toFullCharacterPackage (C : SeparationPackage I) :
    FullCharacterPackage (I →₀ ℤ) where
  Code := C.Code
  codeEquiv := C.codeEquiv
  subsequence := C.subsequence
  subsequence_strictMono := C.subsequence_strictMono
  ultrafilter := C.ultrafilter
  ultrafilter_free := C.ultrafilter_free
  limitPoint c := Finsupp.single (C.codeIndex c) 1
  limitPoint_ne_zero _ := Finsupp.single_ne_zero.mpr one_ne_zero
  CharacterIndex := {x : I →₀ ℤ // x ≠ 0}
  character := C.character
  character_detects x hx := ⟨⟨x, hx⟩, C.character_self_ne_zero ⟨x, hx⟩⟩
  character_limit := C.character_limit


-- @@ L229-230 verbatim
theorem full_initialTopology_eq (C : SeparationPackage I) :
    C.toFullCharacterPackage.initialTopology = C.initialTopology := rfl


-- @@ L232-235 verbatim
theorem initial_countablyCompactSpace (C : SeparationPackage I) :
    @CountablyCompactSpace (I →₀ ℤ) C.initialTopology := by
  rw [← C.full_initialTopology_eq]
  exact C.toFullCharacterPackage.initial_countablyCompactSpace


-- @@ L237-242 verbatim
theorem initial_noInjectiveConvergentSequences (C : SeparationPackage I) :
    ∀ s : ℕ → (I →₀ ℤ), Function.Injective s →
      ¬ ∃ x : I →₀ ℤ,
        Tendsto s atTop (@nhds (I →₀ ℤ) C.initialTopology x) := by
  rw [← C.full_initialTopology_eq]
  exact C.toFullCharacterPackage.initial_noInjectiveConvergentSequences


-- @@ L244-250 verbatim
theorem initial_onlyEventuallyConstantConvergentSequences
    (C : SeparationPackage I) :
    ∀ (s : ℕ → (I →₀ ℤ)) (x : I →₀ ℤ),
      Tendsto s atTop (@nhds (I →₀ ℤ) C.initialTopology x) →
        ∀ᶠ n in atTop, s n = x := by
  rw [← C.full_initialTopology_eq]
  exact C.toFullCharacterPackage.initial_onlyEventuallyConstantConvergentSequences


-- @@ L252-255 verbatim
/-- The uniform structure induced by all characters in the separation package. -/
@[reducible] def initialUniformSpace (C : SeparationPackage I) :
    UniformSpace (I →₀ ℤ) :=
  C.toFullCharacterPackage.initialUniformSpace


-- @@ L257-259 verbatim
theorem initialUniformSpace_toTopology (C : SeparationPackage I) :
    C.initialUniformSpace.toTopologicalSpace = C.initialTopology := by
  exact C.toFullCharacterPackage.initialUniformSpace_toTopology


-- @@ L261-263 verbatim
theorem initial_isUniformAddGroup (C : SeparationPackage I) :
    @IsUniformAddGroup (I →₀ ℤ) C.initialUniformSpace _ :=
  C.toFullCharacterPackage.initial_isUniformAddGroup


-- @@ L265-267 verbatim
theorem initial_totallyBounded (C : SeparationPackage I) :
    @TotallyBounded (I →₀ ℤ) C.initialUniformSpace Set.univ :=
  C.toFullCharacterPackage.initial_totallyBounded


-- @@ L269-269 verbatim
end SeparationPackage


-- @@ L271-271 verbatim
/-! ## Publication-level theorem interfaces -/


-- @@ L273-285 verbatim
/-- The exact topological conclusion shared by the free-Abelian and rational-vector-group
results.  Total boundedness is stated for a compatible uniformity inducing the displayed
topology. -/
def HasMainGroupTopology (G : Type u) [AddCommGroup G] : Prop :=
  ∃ (topology : TopologicalSpace G) (uniformity : UniformSpace G),
    uniformity.toTopologicalSpace = topology ∧
    @IsUniformAddGroup G uniformity _ ∧
    @IsTopologicalAddGroup G topology _ ∧
    @T2Space G topology ∧
    @CountablyCompactSpace G topology ∧
    @TotallyBounded G uniformity Set.univ ∧
    (∀ (s : ℕ → G) (x : G),
      Tendsto s atTop (@nhds G topology x) → ∀ᶠ n in atTop, s n = x)


-- @@ L287-296 verbatim
/-- A full character package proves the complete group-topology conclusion. -/
theorem FullCharacterPackage.hasMainGroupTopology
    {G : Type u} [AddCommGroup G] (C : FullCharacterPackage G) :
    HasMainGroupTopology G := by
  refine ⟨C.initialTopology, C.initialUniformSpace,
    C.initialUniformSpace_toTopology, C.initial_isUniformAddGroup,
    C.initial_isTopologicalAddGroup,
    C.initial_t2Space, C.initial_countablyCompactSpace,
    C.initial_totallyBounded,
    C.initial_onlyEventuallyConstantConvergentSequences⟩


-- @@ L298-300 verbatim
/-- Exact statement of the rational-vector-group proposition for an arbitrary index type. -/
abbrev RationalVectorGroupConclusion (I : Type u) : Prop :=
  HasMainGroupTopology (I →₀ ℚ)


-- @@ L302-307 verbatim
/-- Once the construction is instantiated on the rational direct sum, the rational proposition
follows through exactly the same topology argument. -/
theorem FullCharacterPackage.rationalVectorGroupConclusion
    {I : Type u} (C : FullCharacterPackage (I →₀ ℚ)) :
    RationalVectorGroupConclusion I :=
  C.hasMainGroupTopology


-- @@ L309-309 verbatim
end


-- @@ L311-311 verbatim
end Wallace
