/-
Copyright (c) 2026 Ho Boon Suan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ho Boon Suan
-/

/-
# Key lemmas from the Kalton–Roberts paper

This file formalizes the mathematical lemmas from Sections 1–4 of
the companion paper.
-/
module

public import Mathlib.Data.Fintype.Order
public import LeanPool.KaltonRoberts.Defs
public import Mathlib.Order.BooleanSubalgebra
import LeanPool.KaltonRoberts.DualCert
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Data.Sym.Sym2.Init
import Mathlib.Tactic.NormNum.GCD
import Mathlib.Tactic.Positivity.Finset


-- @@ L24-28 verbatim
/-!
# Key lemmas from the Kalton-Roberts paper

Mathematical lemmas from Sections 1-4 of the companion paper.
-/


-- @@ L30-30 verbatim
@[expose] public section


-- @@ L32-32 verbatim
namespace KaltonRoberts


-- @@ L34-34 verbatim
open Finset BigOperators


-- @@ L36-36 verbatim
universe u


-- @@ L38-38 verbatim
/-! ## Lemma 1.2: Finite reduction (Kalton–Roberts compact reduction) -/


-- @@ L40-49 verbatim
/-- A finite Boolean algebra is order-isomorphic to the powerset of its atoms,
represented as `Finset {a // IsAtom a}`. -/
noncomputable def finiteBoolOrderIso (α : Type*) [BooleanAlgebra α] [Fintype α] :
    Finset {a : α // IsAtom a} ≃o α := by
  classical
  letI := Fintype.toCompleteAtomicBooleanAlgebra α
  exact
    (Fintype.finsetOrderIsoSet :
      Finset {a : α // IsAtom a} ≃o Set {a : α // IsAtom a}).trans
      (CompleteAtomicBooleanAlgebra.toSetOfIsAtom (α := α)).symm


-- @@ L51-103 verbatim
/-- Transfer the finite powerset theorem to an arbitrary finite Boolean algebra. -/
theorem finite_boolean_algebra_bound_of_powerset
    (C : ℝ)
    (hfin : ∀ (U : Type (max 0 u)) [Fintype U] [DecidableEq U]
      (f : Finset U → ℝ), IsApproxAdditive f 1 →
        ∃ a : U → ℝ, ∀ S : Finset U, |f S - additiveFunction a S| ≤ C)
    (α : Type u) [BooleanAlgebra α] [Finite α]
    (f : α → ℝ) (hf : IsApproxAdditiveBA f 1) :
    ∃ μ : α → ℝ, IsFinitelyAdditiveBA μ ∧ ∀ A : α, |f A - μ A| ≤ C := by
  classical
  let := Fintype.ofFinite α
  let Atom := {a : α // IsAtom a}
  let e : Finset Atom ≃o α := finiteBoolOrderIso α
  let f' : Finset Atom → ℝ := fun S => f (e S)
  have hf' : IsApproxAdditive f' 1 := by
    constructor
    · dsimp [f']
      have he_bot : e ∅ = (⊥ : α) := e.map_bot
      rw [he_bot]
      exact hf.1
    · intro S T hST
      dsimp [f']
      have hdisj : Disjoint (e S) (e T) := by
        rw [disjoint_iff_inf_le]
        rw [← e.map_inf]
        simp [hST.eq_bot]
      have hsup : e (S ∪ T) = e S ⊔ e T := e.map_sup S T
      simpa [hsup] using hf.2 (e S) (e T) hdisj
  obtain ⟨a, ha⟩ := hfin Atom f' hf'
  let μ : α → ℝ := fun A => additiveFunction a (e.symm A)
  refine ⟨μ, ?_, ?_⟩
  · constructor
    · dsimp [μ]
      have : e.symm (⊥ : α) = (⊥ : Finset Atom) := by
        simp_all
      simp [this, additiveFunction]
    · intro A B hAB
      dsimp [μ]
      have hdisj : Disjoint (e.symm A) (e.symm B) := by
        rw [disjoint_iff_inf_le] at hAB ⊢
        rw [← (e.symm).map_inf A B]
        exact le_trans ((e.symm).monotone hAB) (by simp)
      have hsup : e.symm (A ⊔ B) = e.symm A ∪ e.symm B := by
        apply e.injective
        rw [e.apply_symm_apply]
        change A ⊔ B = e (e.symm A ⊔ e.symm B)
        rw [e.map_sup]
        simp
      rw [hsup]
      simp [additiveFunction, Finset.sum_union hdisj]
  · intro A
    have := ha (e.symm A)
    simpa [f', μ] using this


-- @@ L105-143 verbatim
/-- The Boolean subalgebra generated by a finite set is finite. -/
lemma booleanSubalgebra_closure_finite_of_finite {α : Type*} [BooleanAlgebra α]
    {s : Set α} (hs : s.Finite) :
    (BooleanSubalgebra.closure s : Set α).Finite := by
  classical
  let s0 : Set α := s ∪ ({⊥, ⊤} : Set α)
  have hs0 : s0.Finite := hs.union (Set.toFinite _)
  let L0 : Set α := latticeClosure s0
  have hL0fin : L0.Finite := hs0.latticeClosure
  have hbot : (⊥ : α) ∈ L0 := by
    exact subset_latticeClosure (by simp [s0])
  have htop : (⊤ : α) ∈ L0 := by
    exact subset_latticeClosure (by simp [s0])
  have hL0_sub_closure_s : L0 ⊆ BooleanSubalgebra.closure s := by
    apply latticeClosure_min
    · intro x hx
      rcases hx with hx | hx
      · exact BooleanSubalgebra.mem_closure_of_mem hx
      · simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
        rcases hx with rfl | rfl
        · exact (BooleanSubalgebra.closure s).bot_mem
        · exact (BooleanSubalgebra.closure s).top_mem
    · exact (BooleanSubalgebra.closure s).isSublattice
  have hclosure_eq : BooleanSubalgebra.closure s = BooleanSubalgebra.closure L0 := by
    apply le_antisymm
    · exact BooleanSubalgebra.closure_mono (by
        intro x hx
        exact subset_latticeClosure (Or.inl hx))
    · exact BooleanSubalgebra.closure_le.mpr hL0_sub_closure_s
  rw [hclosure_eq]
  let β := L0
  have : Fintype β := hL0fin.fintype
  have : DecidableEq β := Classical.decEq β
  let rep : Finset (β × β) → α := fun t => t.sup fun x => (x.1.1 \ x.2.1)
  refine Set.Finite.subset (Set.finite_range rep) ?_
  intro x hx
  obtain ⟨t, rfl⟩ := (BooleanSubalgebra.mem_closure_iff_sup_sdiff
    (s := L0) isSublattice_latticeClosure hbot htop).mp hx
  exact ⟨t, rfl⟩


-- @@ L145-147 verbatim
/-- Coordinate interval used in the compactness reduction. -/
def ApproxCoord {α : Type*} (f : α → ℝ) (C : ℝ) (A : α) :=
  Set.Icc (f A - C) (f A + C)


-- @@ L149-151 verbatim
/-- Product of all coordinate intervals `[f(A)-C, f(A)+C]`. -/
abbrev ApproxProduct {α : Type*} (f : α → ℝ) (C : ℝ) :=
  ∀ A : α, ApproxCoord f C A


-- @@ L153-155 verbatim
/-- Index type for finite-additivity equations. -/
def AddIdx (α : Type*) [BooleanAlgebra α] :=
  {p : α × α // Disjoint p.1 p.2}


-- @@ L157-161 verbatim
/-- Closed additivity condition `ν(A ⊔ B) = ν(A) + ν(B)` inside the interval product. -/
def addCondition {α : Type*} [BooleanAlgebra α] (f : α → ℝ) (C : ℝ)
    (i : AddIdx α) : Set (ApproxProduct f C) :=
  {x | ((x (i.1.1 ⊔ i.1.2) : ApproxCoord f C (i.1.1 ⊔ i.1.2)) : ℝ) =
      (x i.1.1 : ℝ) + (x i.1.2 : ℝ)}


-- @@ L163-230 verbatim
/-- Compactness/FIP step in the Kalton--Roberts finite reduction.

If every finite set of coordinates admits values in the intervals satisfying
all additivity equations involving those coordinates, then a global finitely
additive measure exists. -/
theorem compact_reduction_from_local {α : Type*} [BooleanAlgebra α]
    (C : ℝ) (hC : 0 ≤ C) (f : α → ℝ)
    (hlocal : ∀ T : Finset α, ∃ ν : α → ℝ,
      (∀ A ∈ T, |f A - ν A| ≤ C) ∧
      (∀ A ∈ T, ∀ B ∈ T, Disjoint A B → A ⊔ B ∈ T →
        ν (A ⊔ B) = ν A + ν B)) :
    ∃ μ : α → ℝ, IsFinitelyAdditiveBA μ ∧ ∀ A : α, |f A - μ A| ≤ C := by
  classical
  have hclosed : ∀ i : AddIdx α, IsClosed (addCondition f C i) := by
    intro i
    unfold addCondition
    exact isClosed_eq
      ((continuous_apply (i.1.1 ⊔ i.1.2)).subtype_val)
      (((continuous_apply i.1.1).subtype_val).add
        ((continuous_apply i.1.2).subtype_val))
  have hfip : ∀ s : Finset (AddIdx α), (⋂ i ∈ s, addCondition f C i).Nonempty := by
    intro s
    let T : Finset α :=
      (s.image fun i => i.1.1) ∪ (s.image fun i => i.1.2) ∪
        (s.image fun i => i.1.1 ⊔ i.1.2)
    obtain ⟨ν, hνclose, hνadd⟩ := hlocal T
    let x : ApproxProduct f C := fun A =>
      if hA : A ∈ T then
        ⟨ν A, by
          have h := hνclose A hA
          constructor <;> linarith [abs_le.mp h]⟩
      else
        ⟨f A, by constructor <;> linarith⟩
    refine ⟨x, ?_⟩
    simp only [Set.mem_iInter]
    intro i hi
    have hA : i.1.1 ∈ T := by
      simp only [T, Finset.mem_union, Finset.mem_image]
      exact Or.inl (Or.inl ⟨i, hi, rfl⟩)
    have hB : i.1.2 ∈ T := by
      simp only [T, Finset.mem_union, Finset.mem_image]
      exact Or.inl (Or.inr ⟨i, hi, rfl⟩)
    have hU : i.1.1 ⊔ i.1.2 ∈ T := by
      simp only [T, Finset.mem_union, Finset.mem_image]
      exact Or.inr ⟨i, hi, rfl⟩
    have hadd := hνadd (i.1.1) hA (i.1.2) hB i.2 hU
    simp [addCondition, x, hA, hB, hU, hadd]
  have : ∀ A : α, CompactSpace (ApproxCoord f C A) := fun A => by
    exact isCompact_iff_compactSpace.mp isCompact_Icc
  obtain ⟨x, hx⟩ := CompactSpace.iInter_nonempty (t := addCondition f C) hclosed hfip
  let μ : α → ℝ := fun A => (x A : ℝ)
  refine ⟨μ, ?_, ?_⟩
  · constructor
    · have h0 := Set.mem_iInter.mp hx ⟨(⊥, ⊥), by simp⟩
      have h0' : (x ⊥ : ℝ) = (x ⊥ : ℝ) + (x ⊥ : ℝ) := by
        change (x (⊥ ⊔ ⊥) : ℝ) = (x ⊥ : ℝ) + (x ⊥ : ℝ) at h0
        rw [show (⊥ : α) ⊔ ⊥ = ⊥ by simp] at h0
        exact h0
      change (x ⊥ : ℝ) = 0
      linarith
    · intro A B hAB
      have h := Set.mem_iInter.mp hx ⟨(A, B), hAB⟩
      simpa [addCondition, μ, add_comm] using h
  · intro A
    have hxA := (x A).2
    dsimp [ApproxCoord] at hxA
    rw [abs_sub_comm]
    exact abs_le.mpr ⟨by linarith [hxA.1], by linarith [hxA.2]⟩


-- @@ L232-280 verbatim
/-- Finite satisfiability for the compactness reduction, obtained from the
finite Boolean algebra theorem on the subalgebra generated by the requested
coordinates. -/
theorem local_approximation_of_finite_boolean_algebras {α : Type u} [BooleanAlgebra α]
    (C : ℝ)
    (hfiniteBA : ∀ (β : Type u) [BooleanAlgebra β] [Fintype β]
      (g : β → ℝ), IsApproxAdditiveBA g 1 →
        ∃ μ : β → ℝ, IsFinitelyAdditiveBA μ ∧ ∀ B : β, |g B - μ B| ≤ C)
    (f : α → ℝ) (hf : IsApproxAdditiveBA f 1) :
    ∀ T : Finset α, ∃ ν : α → ℝ,
      (∀ A ∈ T, |f A - ν A| ≤ C) ∧
      (∀ A ∈ T, ∀ B ∈ T, Disjoint A B → A ⊔ B ∈ T →
        ν (A ⊔ B) = ν A + ν B) := by
  classical
  intro T
  let L : BooleanSubalgebra α := BooleanSubalgebra.closure (T : Set α)
  have hLfin_set : (L : Set α).Finite := by
    exact booleanSubalgebra_closure_finite_of_finite (s := (T : Set α)) T.finite_toSet
  have : Fintype L := hLfin_set.fintype
  let fL : L → ℝ := fun A => f A
  have hfL : IsApproxAdditiveBA fL 1 := by
    constructor
    · dsimp [fL]
      simpa using hf.1
    · intro A B hAB
      dsimp [fL]
      have hABα : Disjoint (A : α) (B : α) := by
        rw [disjoint_iff_inf_le]
        rw [disjoint_iff_inf_le] at hAB
        exact hAB
      have hsup : ((A ⊔ B : L) : α) = (A : α) ⊔ (B : α) := rfl
      simpa [hsup] using hf.2 (A : α) (B : α) hABα
  obtain ⟨μL, hμLadd, hμLclose⟩ := hfiniteBA L fL hfL
  let ν : α → ℝ := fun A => if hA : A ∈ L then μL ⟨A, hA⟩ else f A
  refine ⟨ν, ?_, ?_⟩
  · intro A hAT
    have hA : A ∈ L := BooleanSubalgebra.mem_closure_of_mem hAT
    have h := hμLclose ⟨A, hA⟩
    simpa [ν, hA, fL] using h
  · intro A hAT B hBT hAB hUT
    have hA : A ∈ L := BooleanSubalgebra.mem_closure_of_mem hAT
    have hB : B ∈ L := BooleanSubalgebra.mem_closure_of_mem hBT
    have hU : A ⊔ B ∈ L := BooleanSubalgebra.mem_closure_of_mem hUT
    have hAB_L : Disjoint (⟨A, hA⟩ : L) (⟨B, hB⟩ : L) := by
      rw [disjoint_iff_inf_le] at hAB ⊢
      exact hAB
    have hadd := hμLadd.2 (⟨A, hA⟩ : L) (⟨B, hB⟩ : L) hAB_L
    change μL ⟨A ⊔ B, hU⟩ = μL ⟨A, hA⟩ + μL ⟨B, hB⟩ at hadd
    simpa [ν, hA, hB, hU] using hadd


-- @@ L282-304 verbatim
/-- **Lemma 1.2** (Kalton--Roberts compact reduction).
If the main theorem holds for every finite power-set algebra `2^U` with
constant `C`, then it holds with the same constant for every Boolean algebra,
hence for every set algebra.

The proof formalizes the compact product/FIP argument from the paper and the
standard reduction from finite Boolean algebras to powersets of atoms.

**Reference**: Lemma 1.2 in Section 1 of the companion paper. -/
theorem finite_reduction
    (C : ℝ) (hC : 0 ≤ C)
    (hfin : ∀ (U : Type (max 0 u)) [Fintype U] [DecidableEq U]
      (f : Finset U → ℝ), IsApproxAdditive f 1 →
        ∃ a : U → ℝ, ∀ S : Finset U, |f S - additiveFunction a S| ≤ C)
    : ∀ (α : Type u) [BooleanAlgebra α]
        (f : α → ℝ), IsApproxAdditiveBA f 1 →
          ∃ μ : α → ℝ, IsFinitelyAdditiveBA μ ∧ ∀ A : α, |f A - μ A| ≤ C := by
  intro α _ f hf
  exact compact_reduction_from_local C hC f
    (local_approximation_of_finite_boolean_algebras C
      (by
        intro β _ _ g hg
        exact finite_boolean_algebra_bound_of_powerset C hfin β g hg) f hf)


-- @@ L306-306 verbatim
/-! ## Lemma 2.1: Dual certificate -/


-- @@ L308-323 verbatim
/-- **Lemma 2.1** (Dual certificate). Let `f : 2^U → ℝ` be `1`-additive.
After subtracting a closest additive signed measure, there exists a rational
dual certificate `λ` satisfying conditions (i)–(iii).

The proof uses the finite-dimensional Hahn–Banach criterion for best
`ℓ∞`-approximation. The rationality follows from the polytope vertex argument.

**Reference**: Lemma 2.1 in Section 2 of the companion paper. -/
theorem dual_certificate_exists {U : Type*} [DecidableEq U] [Fintype U]
    (f : Finset U → ℝ)
    (_hf : IsApproxAdditive f 1)
    (_hM : ∀ S : Finset U, |f S| ≤ distToAdditive f)
    (_hbest : ∀ a : U → ℝ, ∃ S : Finset U,
      |f S - additiveFunction a S| ≥ distToAdditive f) :
    Nonempty (DualCertificate f (distToAdditive f)) :=
  dual_certificate_exists_proof f _hf _hM _hbest


-- @@ L325-333 verbatim
/-! ## Lemma 2.4: Approximate modularity -/

/-
**Lemma 2.4** (Approximate modularity). For a `1`-additive function on a
finite power set, `|f(A) + f(B) − f(A ∪ B) − f(A ∩ B)| ≤ 2` for all `A, B`.

**Reference**: Lemma 2.4 (Equation (4)) in Section 2 of
the companion paper.
-/

-- @@ L334-378 verbatim
theorem approx_modularity {U : Type*} [DecidableEq U]
    (f : Finset U → ℝ) (hf : IsApproxAdditive f 1)
    (A B : Finset U) :
    |f A + f B - f (A ∪ B) - f (A ∩ B)| ≤ 2 := by
  -- Set I = A ∩ B, X = A \ B, Y = B \ A.
  set I := A ∩ B
  set X := A \ B
  set Y := B \ A;
  -- Then A = I ∪ X (disjoint), B = I ∪ Y (disjoint), A ∪ B = I ∪ X ∪ Y.
  have hA : A = I ∪ X := by
    simp only [I, X]; ext x; simp [Finset.mem_union, Finset.mem_inter, Finset.mem_sdiff]; tauto
  have hB : B = I ∪ Y := by
    grind
  have hAB : A ∪ B = I ∪ X ∪ Y := by
    grind
  have h_disjoint_XY : Disjoint X Y := by
    exact Finset.disjoint_left.mpr fun x hxX hxY => Finset.mem_sdiff.mp hxX |>.2 (
      Finset.mem_sdiff.mp hxY |>.1 )
  have h_disjoint_IY : Disjoint I Y := by
    exact Finset.disjoint_left.mpr fun x hxI hxY => Finset.mem_sdiff.mp hxY |>.2 (
      Finset.mem_inter.mp hxI |>.1 )
  have h_disjoint_IX : Disjoint I X := by
    exact Finset.disjoint_left.mpr fun x hxI hxX => Finset.mem_sdiff.mp hxX |>.2 (
      Finset.mem_inter.mp hxI |>.2 );
  -- Apply 1-additivity to the disjoint pairs `(I, X)` and `(I ∪ Y, X)`.
  -- and |f(A ∪ B) - f(B) - f(X)| ≤ 1.
  have h1 : |f A - f I - f X| ≤ 1 := by
    rw [hA, show f (I ∪ X) - f I - f X = -(f I + f X - f (I ∪ X)) from by ring, abs_neg]
    exact hf.2 I X h_disjoint_IX
  have h2 : |f (A ∪ B) - f B - f X| ≤ 1 := by
    have := hf.2 ( I ∪ Y ) X ?_ <;> norm_num at *;
    · grind +splitImp;
    · exact ⟨ h_disjoint_IX, h_disjoint_XY.symm ⟩;
  exact abs_le.mpr
    ⟨by linarith [abs_le.mp h1, abs_le.mp h2],
      by linarith [abs_le.mp h1, abs_le.mp h2]⟩

/-
**Lemma 2.4, deficit corollary**. If `f(A) = M − a` and `f(B) = M − b`,
then `f(A ∩ B) ≥ M − a − b − 2`, i.e., `A ∩ B` has deficit at most
`a + b + 2`.

**Reference**: second paragraph of Lemma 2.4 in Section 2 of
the companion paper.
-/

-- @@ L379-388 verbatim
theorem deficit_intersection {U : Type*} [DecidableEq U]
    (f : Finset U → ℝ) (hf : IsApproxAdditive f 1) (M : ℝ)
    (hM : ∀ S : Finset U, |f S| ≤ M)
    (A B : Finset U) (a b : ℝ)
    (hA : f A = M - a) (hB : f B = M - b) :
    f (A ∩ B) ≥ M - a - b - 2 := by
  -- Use approx_modularity to get |f(A) + f(B) - f(A ∪ B) - f(A ∩ B)| ≤ 2.
  have h_approx : |f A + f B - f (A ∪ B) - f (A ∩ B)| ≤ 2 := by
    exact approx_modularity f hf A B
  linarith [ abs_le.mp h_approx, abs_le.mp ( hM ( A ∪ B ) ) ]


-- @@ L390-402 verbatim
/-! ## Corollary 3.1: Mixed neighbouring intersections -/

/-
**Corollary 3.1** (Mixed neighbouring intersections), frequency bound.
If every item appears in at most a `t`-fraction of `C`, then the mixed
intersection `C^{(ℓ,τ)}` has item frequencies at most
`(1 − τ) t^ℓ + τ t^{ℓ+1}`.

The frequency bound is monotone in `t`.

**Reference**: Corollary 3.1 in Section 3 of
the companion paper.
-/

-- @@ L403-408 verbatim
theorem mixed_intersection_frequency_mono
    (t₁ t₂ : ℝ) (_ht : 0 ≤ t₁) (_ht12 : t₁ ≤ t₂) (_ht2 : t₂ ≤ 1)
    (ℓ : ℕ) (τ : ℝ) (_hτ : 0 ≤ τ) (_hτ1 : τ ≤ 1) :
    (1 - τ) * t₁ ^ ℓ + τ * t₁ ^ (ℓ + 1) ≤
      (1 - τ) * t₂ ^ ℓ + τ * t₂ ^ (ℓ + 1) := by
  gcongr


-- @@ L410-426 verbatim
/-- **Corollary 3.1**, deficit bound (nonnegativity only).

**NOTE**: This only proves that the expression `ℓ E + 2(ℓ − 1) + τ(E + 2) ≥ 0`.
This is NOT the actual Corollary 3.1 mixed-intersection theorem, which asserts
that the *average deficit of the constructed mixed intersection collection*
is at most this expression.

The honest construction-based version is `mixed_intersection_weighted`
in `Pipeline.lean`.

**Reference**: Corollary 3.1 in Section 3 of
the companion paper. -/
theorem mixed_intersection_deficit_bound
    (E : ℝ) (hE : 0 ≤ E) (ℓ : ℕ) (hℓ : 1 ≤ ℓ) (τ : ℝ) (hτ : 0 ≤ τ) :
    ℓ * E + 2 * ((ℓ : ℝ) - 1) + τ * (E + 2) ≥ 0 := by
  have : (ℓ : ℝ) ≥ 1 := Nat.one_le_cast.mpr hℓ
  nlinarith


-- @@ L428-428 verbatim
/-! ## Lemma 3.2: One-sided recombination -/


-- @@ L430-444 verbatim
/-- **Lemma 3.2** (One-sided recombination, algebraic consequence).

**NOTE**: This is only the algebraic manipulation from the recombination
inequality `hrec`, not the full combinatorial Lemma 3.2. The construction
used by the final theorem is `one_sided_recombination_core_eps` in
`EpsilonRecombination.lean`.

**Reference**: Lemma 3.2 in Section 3 of the companion paper. -/
theorem one_sided_recombination_ineq
    (θ M D D' r : ℝ) (_hθ : 0 < θ) (hθ1 : θ < 1)
    (hrec : (1 - θ) * M ≤ D - θ * D' + 2 * r - 1 - θ) :
    M ≤ (D + 2 * r - 1 - θ) / (1 - θ) - θ / (1 - θ) * D' := by
  have h1θ : (0 : ℝ) < 1 - θ := by linarith
  rw [show θ / (1 - θ) * D' = θ * D' / (1 - θ) from by ring, ← sub_div, le_div_iff₀ h1θ]
  nlinarith


-- @@ L446-456 verbatim
/-- **Equation (5)** in Lemma 3.2: discarding the target deficit gives
`M ≤ (D + 2r − 1 − θ)/(1 − θ)`.

**Reference**: Equation (5) in Lemma 3.2 of
the companion paper. -/
theorem one_sided_recombination_discard
    (θ M D D' r : ℝ) (_hθ : 0 < θ) (hθ1 : θ < 1) (hD' : 0 ≤ D')
    (hrec : (1 - θ) * M ≤ D - θ * D' + 2 * r - 1 - θ) :
    M ≤ (D + 2 * r - 1 - θ) / (1 - θ) := by
  rw [le_div_iff₀ (by linarith : (0 : ℝ) < 1 - θ)]
  nlinarith


-- @@ L458-458 verbatim
/-! ## Lemma 3.3: Two-sided recombination -/


-- @@ L460-474 verbatim
/-- **Lemma 3.3** (Two-sided recombination, algebraic consequence).

**NOTE**: This is only the algebraic averaging of two one-sided inequalities,
not the full combinatorial Lemma 3.3. The construction used by the final
theorem is `two_sided_recombination_core_eps` in `EpsilonRecombination.lean`.

**Reference**: Lemma 3.3 (Equation (6)) in Section 3 of
the companion paper. -/
theorem two_sided_recombination
    (_α r θ M D S D' S' : ℝ)
    (_hθ : 0 < θ) (_hθ1 : θ < 1)
    (h_pos : (1 - θ) * M ≤ D - θ * D' + 2 * r - 1 - θ)
    (h_neg : (1 - θ) * M ≤ S - θ * S' + 2 * r - 1 - θ) :
    (1 - θ) * M ≤ (D + S) / 2 - θ * (D' + S') / 2 + 2 * r - 1 - θ := by
  linarith


-- @@ L476-476 verbatim
end KaltonRoberts
