/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/
module

public import Mathlib.Logic.Encodable.Pi
public import Mathlib.Order.Filter.Cofinite
public import Mathlib.Order.Filter.Ultrafilter.Defs
public import Mathlib.SetTheory.Cardinal.Cofinality.Ordinal
public import Mathlib.SetTheory.Cardinal.Continuum
import Mathlib.Order.Interval.Finset.Nat


-- @@ L15-23 verbatim
/-!
# ZFC foundations used by the Wallace construction

This file records the parts of the set-theoretic and topological construction that can be
checked directly against mathlib.  In particular, it proves the ultrafilter extension step and
the basic facts about the initial topology generated by a family of circle-valued characters.

No declaration in this file is an axiom and no proof is omitted.
-/


-- @@ L25-25 verbatim
@[expose] public section


-- @@ L27-27 verbatim
open Filter Set

-- @@ L28-28 verbatim
open scoped Cardinal


-- @@ L30-30 verbatim
universe u v w


-- @@ L32-32 verbatim
namespace Wallace


-- @@ L34-34 verbatim
noncomputable section


-- @@ L36-36 verbatim
/-! ## Families with the finite-intersection property -/


-- @@ L38-44 verbatim
/-- Any proper filter extending the cofinite filter admits a free ultrafilter refinement. -/
theorem exists_free_ultrafilter_le_filter {α : Type u} (l : Filter α) [l.NeBot]
    (hl : l ≤ cofinite) :
    ∃ p : Ultrafilter α,
      (p : Filter α) ≤ l ∧ (p : Filter α) ≤ cofinite := by
  refine ⟨Ultrafilter.of l, Ultrafilter.of_le l, ?_⟩
  exact (Ultrafilter.of_le l).trans hl


-- @@ L46-46 verbatim
/-! ## Cardinal bookkeeping for the continuum-indexed free group -/


-- @@ L48-52 verbatim
/-- König's theorem gives the strict uncountable cofinality of the continuum.  This is the
precise fact used to bound a countable union of supports below the initial ordinal of `𝔠`. -/
theorem aleph0_lt_cof_continuum : ℵ₀ < (𝔠 : Cardinal).ord.cof := by
  rw [← Cardinal.two_power_aleph0]
  exact Cardinal.lt_cof_ord_power le_rfl (by simp)


-- @@ L54-54 verbatim
/-! ## A continuum-sized almost-disjoint family -/


-- @@ L56-57 verbatim
/-- A concrete node on the binary tree: a level and the values below that level. -/
abbrev BinaryTreeNode := Σ n : ℕ, Fin n → Bool


-- @@ L59-61 verbatim
/-- The length-`n` initial segment of a binary stream. -/
def binaryPrefix (x : ℕ → Bool) (n : ℕ) : BinaryTreeNode :=
  ⟨n, fun i => x i⟩


-- @@ L63-65 verbatim
/-- The branch through the binary tree associated to a stream. -/
def binaryBranch (x : ℕ → Bool) : Set BinaryTreeNode :=
  Set.range (binaryPrefix x)


-- @@ L67-70 verbatim
theorem binaryPrefix_injective (x : ℕ → Bool) :
    Function.Injective (binaryPrefix x) := by
  intro m n h
  exact congrArg Sigma.fst h


-- @@ L72-74 verbatim
/-- Every branch is infinite. -/
theorem binaryBranch_infinite (x : ℕ → Bool) : (binaryBranch x).Infinite := by
  exact Set.infinite_range_of_injective (binaryPrefix_injective x)


-- @@ L76-86 verbatim
/-- If two branches share a node at level `n`, then their streams agree below `n`. -/
theorem eq_on_Iio_of_binaryPrefix_eq {x y : ℕ → Bool} {m n : ℕ}
    (h : binaryPrefix x m = binaryPrefix y n) :
    m = n ∧ ∀ k < m, x k = y k := by
  have hmn : m = n := congrArg Sigma.fst h
  subst n
  refine ⟨rfl, ?_⟩
  have hfun : (fun i : Fin m => x i) = fun i : Fin m => y i :=
    eq_of_heq (Sigma.mk.inj_iff.mp h).2
  intro k hk
  exact congrFun hfun ⟨k, hk⟩


-- @@ L88-102 verbatim
/-- Distinct binary streams define branches with finite intersection. -/
theorem binaryBranch_inter_finite {x y : ℕ → Bool} (hxy : x ≠ y) :
    (binaryBranch x ∩ binaryBranch y).Finite := by
  obtain ⟨k, hk⟩ : ∃ k, x k ≠ y k := by
    simpa only [Function.ne_iff] using hxy
  refine (Set.finite_Iic k).image (binaryPrefix x) |>.subset ?_
  intro z hz
  rcases hz.1 with ⟨m, rfl⟩
  rcases hz.2 with ⟨n, hmn⟩
  have hmn' := (eq_on_Iio_of_binaryPrefix_eq hmn).1
  subst n
  refine ⟨m, ?_, rfl⟩
  by_contra hmk
  have hkm : k < m := Nat.lt_of_not_ge hmk
  exact hk ((eq_on_Iio_of_binaryPrefix_eq hmn).2 k hkm).symm


-- @@ L104-107 verbatim
/-- The binary-tree node type is infinite. -/
theorem binaryTreeNode_infinite : Infinite BinaryTreeNode :=
  Infinite.of_injective (binaryPrefix fun _ => false)
    (binaryPrefix_injective fun _ => false)


-- @@ L109-114 verbatim
/-- A fixed identification of the countably infinite binary tree with `ℕ`. -/
def binaryTreeNodeEquivNat : BinaryTreeNode ≃ ℕ := by
  letI : Infinite BinaryTreeNode := binaryTreeNode_infinite
  letI : Denumerable BinaryTreeNode :=
    Denumerable.ofEncodableOfInfinite BinaryTreeNode
  exact Denumerable.eqv BinaryTreeNode


-- @@ L116-118 verbatim
/-- The same branch family, transported to an almost-disjoint family literally on `ℕ`. -/
def binaryBranchOnNat (x : ℕ → Bool) : Set ℕ :=
  binaryTreeNodeEquivNat '' binaryBranch x


-- @@ L120-122 verbatim
theorem binaryBranchOnNat_infinite (x : ℕ → Bool) :
    (binaryBranchOnNat x).Infinite := by
  exact (binaryBranch_infinite x).image binaryTreeNodeEquivNat.injective.injOn


-- @@ L124-129 verbatim
theorem binaryBranchOnNat_inter_finite {x y : ℕ → Bool} (hxy : x ≠ y) :
    (binaryBranchOnNat x ∩ binaryBranchOnNat y).Finite := by
  change (binaryTreeNodeEquivNat '' binaryBranch x ∩
    binaryTreeNodeEquivNat '' binaryBranch y).Finite
  rw [← Set.image_inter binaryTreeNodeEquivNat.injective]
  exact (binaryBranch_inter_finite hxy).image binaryTreeNodeEquivNat


-- @@ L131-131 verbatim
/-! ## A reusable transfinite-iteration fact -/


-- @@ L133-133 verbatim
end


-- @@ L135-135 verbatim
end Wallace
