/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import Mathlib.Order.Directed
public import LeanPool.DomainTheory.Neighborhood.Basic
public import Mathlib.Basic.Finite.Defs
public import Mathlib.Order.SetNotation
public import Mathlib.Tactic.ToAdditive
import Mathlib.Data.Set.BooleanAlgebra
public import Mathlib.Data.Set.Finite.Basic


-- @@ L16-54 verbatim
/-!
# Exercise 2.22 (Scott 1981, PRG-19) — the abstract representation theorem

(*For set theorists.*) Exercises 1.18 and 2.11 noted that any domain `|𝒟|`, viewed
as a family of
sets, is closed under (i) the intersection of an arbitrary **non-empty** subfamily
and (ii) the union
of any **directed** subfamily. This exercise proves the converse: *any* family `C`
of sets with these
two closure properties is inclusion-isomorphic to a domain.

We follow Scott's hint. Fix `C : Set (Set τ)` (non-empty) closed under non-empty
intersections
(`hInter`) and directed unions (`hDir`).

* `Δ` = the **finite** sets `F` included in some member of `C` (here the subtype
`Tok C`).
* The **closure** of `F` is `Fbar = ⋂ {X ∈ C ∣ F ⊆ X}` (`Cl C F`); since `F` lies in
some member of
  `C`, this intersection is over a non-empty family, so `Fbar ∈ C` (`Cl_mem`). The
  `Fbar` are the "finite"
  elements.
* The neighbourhood system `reprSystem` over `Δ` has neighbourhoods `C(F) = {G ∈ Δ
∣ F ⊆ Gbar}`
  (`nbhd C F`).

The representation isomorphism `reprIso : reprSystem.Element ≃o C` (under `⊆`)
sends an ideal element
`x` to `⋃ {Fbar ∣ C(F) ∈ x}` and a set `X ∈ C` to the element generated by `{C(F) ∣
F ⊆ X}`. The key
identity (Scott) is `X = ⋃ {Fbar ∣ F ⊆ X, F ∈ Δ}`, realized by
`toC_ofC`/`mem_nbhd_iff`.

**Axioms.** This is the genuinely set-theoretic exercise: it uses
`Classical.choice` (picking witnesses
of `C.Nonempty`, finite-set induction). This is documented and expected per the
exercise's framing
("for set theorists").
-/


-- @@ L56-56 verbatim
@[expose] public section


-- @@ L58-58 verbatim
namespace Domain.Neighborhood.Exercise222


-- @@ L60-60 verbatim
open Domain.Neighborhood NeighborhoodSystem Set


-- @@ L62-62 verbatim
variable {τ : Type*} (C : Set (Set τ))


-- @@ L64-64 verbatim
/-! ### Closure and tokens. -/


-- @@ L66-68 verbatim
/-- The **closure** `Fbar = ⋂ {X ∈ C ∣ F ⊆ X}` of a set `F` relative to the family
`C`. -/
def Cl (F : Set τ) : Set τ := ⋂₀ {X | X ∈ C ∧ F ⊆ X}


-- @@ L70-75 verbatim
/-- `F ⊆ Fbar`: a set is contained in its closure. -/
theorem subset_Cl (F : Set τ) : F ⊆ Cl C F := by
  intro t ht
  rw [Cl, Set.mem_sInter]
  intro X hX
  exact hX.2 ht


-- @@ L77-81 verbatim
/-- `Fbar ⊆ X` whenever `X ∈ C` contains `F`: the closure is the *smallest* member
of `C` over `F`. -/
theorem Cl_subset {F X : Set τ} (hX : X ∈ C) (hFX : F ⊆ X) : Cl C F ⊆ X := by
  intro t ht
  exact (Set.mem_sInter.mp ht) X ⟨hX, hFX⟩


-- @@ L83-84 verbatim
/-- A token: a finite set included in some member of `C`. -/
def IsTok (F : Set τ) : Prop := F.Finite ∧ ∃ X ∈ C, F ⊆ X


-- @@ L86-87 verbatim
/-- Scott's `Δ`: the type of tokens (finite sets included in members of `C`). -/
abbrev Tok := {F : Set τ // IsTok C F}


-- @@ L89-89 verbatim
variable (hInter : ∀ 𝒮 : Set (Set τ), 𝒮.Nonempty → 𝒮 ⊆ C → ⋂₀ 𝒮 ∈ C)


-- @@ L91-99 verbatim
include hInter in
/-- Every closure `Fbar` of a token lies in `C` (closure under non-empty
intersection). -/
theorem Cl_mem {F : Set τ} (h : ∃ X ∈ C, F ⊆ X) : Cl C F ∈ C := by
  change ⋂₀ {X | X ∈ C ∧ F ⊆ X} ∈ C
  apply hInter
  · obtain ⟨X, hX, hFX⟩ := h
    exact ⟨X, hX, hFX⟩
  · simp_all


-- @@ L101-101 verbatim
/-! ### The neighbourhood system `reprSystem`. -/


-- @@ L103-104 verbatim
/-- Scott's neighbourhood `C(F) = {G ∈ Δ ∣ F ⊆ Gbar}`. -/
def nbhd (F : Set τ) : Set (Tok C) := {G | F ⊆ Cl C G.1}


-- @@ L106-106 verbatim
@[simp] theorem mem_nbhd {F : Set τ} {G : Tok C} : G ∈ nbhd C F ↔ F ⊆ Cl C G.1 := Iff.rfl


-- @@ L108-118 verbatim
include hInter in
/-- `C(F) ⊆ C(G) ↔ G ⊆ Fbar`: comparison of neighbourhoods reduces to inclusion
against closures. -/
theorem nbhd_subset_iff {F G : Set τ} (hF : IsTok C F) :
    nbhd C F ⊆ nbhd C G ↔ G ⊆ Cl C F := by
  constructor
  · intro h
    have hmem : (⟨F, hF⟩ : Tok C) ∈ nbhd C F := subset_Cl C F
    exact h hmem
  · intro hG H hH
    exact hG.trans (Cl_subset C (Cl_mem C hInter H.2.2) hH)


-- @@ L120-123 verbatim
/-- `C(∅) = Δ`: the empty token's neighbourhood is everything (the master). -/
theorem nbhd_empty : nbhd C (∅ : Set τ) = Set.univ := by
  ext G
  simp [nbhd]


-- @@ L125-125 verbatim
variable (hne : C.Nonempty)


-- @@ L127-129 verbatim
include hne in
/-- The empty token `∅ ∈ Δ` (needs `C` non-empty for `∅` to lie in some member). -/
def botTok : Tok C := ⟨∅, Set.finite_empty, hne.choose, hne.choose_spec, Set.empty_subset _⟩


-- @@ L131-148 verbatim
include hInter hne in
/-- **The representation neighbourhood system** `reprSystem` over `Δ = Tok C`:
neighbourhoods are
exactly the `C(F)` for tokens `F`, the master is all of `Δ = C(∅)`. -/
def reprSystem : NeighborhoodSystem (Tok C) where
  mem N := ∃ F : Tok C, N = nbhd C F.1
  master := Set.univ
  master_mem := ⟨botTok C hne, (nbhd_empty C).symm⟩
  inter_mem := by
    rintro X Y Z ⟨F, rfl⟩ ⟨F', rfl⟩ ⟨F'', rfl⟩ hZsub
    have hF''mem : (F'' : Tok C) ∈ nbhd C F''.1 := subset_Cl C F''.1
    have h := hZsub hF''mem
    have hClF'' : Cl C F''.1 ∈ C := Cl_mem C hInter F''.2.2
    have hunionsub : F.1 ∪ F'.1 ⊆ Cl C F''.1 := Set.union_subset h.1 h.2
    refine ⟨⟨F.1 ∪ F'.1, F.2.1.union F'.2.1, Cl C F''.1, hClF'', hunionsub⟩, ?_⟩
    ext G
    simp only [mem_nbhd, Set.mem_inter_iff, Set.union_subset_iff]
  sub_master := fun _ => Set.subset_univ _


-- @@ L150-151 verbatim
@[simp] theorem mem_reprSystem {N : Set (Tok C)} :
    (reprSystem C hInter hne).mem N ↔ ∃ F : Tok C, N = nbhd C F.1 := Iff.rfl


-- @@ L153-153 verbatim
@[simp] theorem reprSystem_master : (reprSystem C hInter hne).master = Set.univ := rfl


-- @@ L155-155 verbatim
/-! ### From an element to a set of `C`: `x ↦ ⋃ {Fbar ∣ C(F) ∈ x}`. -/


-- @@ L157-160 verbatim
/-- The family `{Fbar ∣ C(F) ∈ x}` of finite-element closures present in the ideal
element `x`. -/
def famC (x : (reprSystem C hInter hne).Element) : Set (Set τ) :=
  {Y | ∃ F : Tok C, x.mem (nbhd C F.1) ∧ Y = Cl C F.1}


-- @@ L162-164 verbatim
/-- Scott's `⋃ {Fbar ∣ C(F) ∈ x}`: the set of `C` represented by the ideal element
`x`. -/
def toC (x : (reprSystem C hInter hne).Element) : Set τ := ⋃₀ famC C hInter hne x


-- @@ L166-169 verbatim
theorem mem_toC (x : (reprSystem C hInter hne).Element) {t : τ} :
    t ∈ toC C hInter hne x ↔ ∃ F : Tok C, x.mem (nbhd C F.1) ∧ t ∈ Cl C F.1 := by
  simp only [toC, famC, Set.mem_sUnion, Set.mem_ofPred_eq]
  simp_all


-- @@ L171-187 verbatim
/-- **Directedness step.** If `C(F), C(F') ∈ x` then there is a token `F₃` with
`C(F₃) ∈ x` whose
closure dominates both `Fbar` and `Fbar'`. (From the filter intersection `C(F) ∩ C(F')
∈ x`, which is
some `C(F₃)`.) -/
theorem directed_step (x : (reprSystem C hInter hne).Element) {F F' : Tok C}
    (hF : x.mem (nbhd C F.1)) (hF' : x.mem (nbhd C F'.1)) :
    ∃ F₃ : Tok C, x.mem (nbhd C F₃.1) ∧ Cl C F.1 ⊆ Cl C F₃.1 ∧ Cl C F'.1 ⊆ Cl C F₃.1 := by
  have hinter : x.mem (nbhd C F.1 ∩ nbhd C F'.1) := x.inter_mem hF hF'
  have hmemD : (reprSystem C hInter hne).mem (nbhd C F.1 ∩ nbhd C F'.1) := x.sub hinter
  obtain ⟨F₃, hF₃eq⟩ := hmemD
  rw [hF₃eq] at hinter
  have hF₃self : (F₃ : Tok C) ∈ nbhd C F₃.1 := subset_Cl C F₃.1
  rw [← hF₃eq] at hF₃self
  refine ⟨F₃, hinter, ?_, ?_⟩
  · exact Cl_subset C (Cl_mem C hInter F₃.2.2) hF₃self.1
  · exact Cl_subset C (Cl_mem C hInter F₃.2.2) hF₃self.2


-- @@ L189-195 verbatim
/-- The empty token's neighbourhood `C(∅) = Δ` is in every element (it is the
master). -/
theorem mem_nbhd_bot (x : (reprSystem C hInter hne).Element) :
    x.mem (nbhd C (botTok C hne).1) := by
  have h : (botTok C hne).1 = (∅ : Set τ) := rfl
  rw [h, nbhd_empty C]
  exact x.master_mem


-- @@ L197-217 verbatim
/-- **Finite sets are captured by a single token.** A finite `s ⊆ toC x` is
contained in some `Fbar`
with `C(F) ∈ x` — the finite-subcover property of the directed union `toC x`. -/
theorem exists_tok_of_finite_subset (x : (reprSystem C hInter hne).Element) {s : Set τ}
    (hs : s.Finite) (hsub : s ⊆ toC C hInter hne x) :
    ∃ F : Tok C, x.mem (nbhd C F.1) ∧ s ⊆ Cl C F.1 := by
  revert hsub
  induction s, hs using Set.Finite.induction_on with
  | empty =>
    intro _
    exact ⟨botTok C hne, mem_nbhd_bot C hInter hne x, Set.empty_subset _⟩
  | @insert a s _ha _hsfin ih =>
    intro hsub
    have ha' : a ∈ toC C hInter hne x := hsub (Set.mem_insert a s)
    rw [mem_toC] at ha'
    obtain ⟨Fa, hFa, haCl⟩ := ha'
    obtain ⟨Fs, hFs, hsCl⟩ := ih (fun y hy => hsub (Set.mem_insert_of_mem a hy))
    obtain ⟨F₃, hF₃, hFaF₃, hFsF₃⟩ := directed_step C hInter hne x hFa hFs
    refine ⟨F₃, hF₃, ?_⟩
    rw [Set.insert_subset_iff]
    exact ⟨hFaF₃ haCl, hsCl.trans hFsF₃⟩


-- @@ L219-233 verbatim
/-- **Key membership identity.** `C(G) ∈ x ↔ G ⊆ toC x`. Forward: `G ⊆ Gbar ⊆ toC x`.
Reverse: `G` is
finite, so the finite-subcover lemma gives `F` with `C(F) ∈ x` and `G ⊆ Fbar`,
whence `C(F) ⊆ C(G)`
and upward closure gives `C(G) ∈ x`. -/
theorem mem_nbhd_iff (x : (reprSystem C hInter hne).Element) (G : Tok C) :
    x.mem (nbhd C G.1) ↔ G.1 ⊆ toC C hInter hne x := by
  constructor
  · intro hx t ht
    rw [mem_toC]
    exact ⟨G, hx, subset_Cl C G.1 ht⟩
  · intro hsub
    obtain ⟨F, hF, hGF⟩ := exists_tok_of_finite_subset C hInter hne x G.2.1 hsub
    have hnsub : nbhd C F.1 ⊆ nbhd C G.1 := (nbhd_subset_iff C hInter F.2).mpr hGF
    exact x.up_mem hF ⟨G, rfl⟩ hnsub


-- @@ L235-235 verbatim
/-! ### From a set of `C` to an element: `X ↦ {C(F) ∣ F ⊆ X}`. -/


-- @@ L237-256 verbatim
/-- The ideal element generated by `X ∈ C`: it contains the neighbourhoods above
some `C(F)` with
`F ⊆ X`. -/
def ofC (X : Set τ) (hX : X ∈ C) : (reprSystem C hInter hne).Element where
  mem N := (reprSystem C hInter hne).mem N ∧ ∃ F : Tok C, F.1 ⊆ X ∧ nbhd C F.1 ⊆ N
  sub h := h.1
  master_mem :=
    ⟨(reprSystem C hInter hne).master_mem, botTok C hne, Set.empty_subset X, Set.subset_univ _⟩
  inter_mem := by
    rintro N M ⟨hN, F, hFX, hFN⟩ ⟨hM, F', hF'X, hF'M⟩
    have htok : IsTok C (F.1 ∪ F'.1) := ⟨F.2.1.union F'.2.1, X, hX, Set.union_subset hFX hF'X⟩
    have hsub : nbhd C (F.1 ∪ F'.1) ⊆ N ∩ M := by
      intro G hG
      rw [mem_nbhd, Set.union_subset_iff] at hG
      exact ⟨hFN hG.1, hF'M hG.2⟩
    exact ⟨(reprSystem C hInter hne).inter_mem hN hM ⟨⟨_, htok⟩, rfl⟩ hsub,
      ⟨F.1 ∪ F'.1, htok⟩, Set.union_subset hFX hF'X, hsub⟩
  up_mem := by
    rintro N M ⟨_, F, hFX, hFN⟩ hM hNM
    exact ⟨hM, F, hFX, hFN.trans hNM⟩


-- @@ L258-273 verbatim
/-- **Scott's identity** `X = ⋃ {Fbar ∣ F ⊆ X, F ∈ Δ}` in round-trip form: `toC (ofC
X) = X`. -/
theorem toC_ofC (X : Set τ) (hX : X ∈ C) : toC C hInter hne (ofC C hInter hne X hX) = X := by
  apply Set.Subset.antisymm
  · intro t ht
    rw [mem_toC] at ht
    obtain ⟨F, hF, htCl⟩ := ht
    obtain ⟨_, F', hF'X, hF'F⟩ := hF
    have h1 : F.1 ⊆ Cl C F'.1 := (nbhd_subset_iff C hInter F'.2).mp hF'F
    have hFX : F.1 ⊆ X := h1.trans (Cl_subset C hX hF'X)
    exact Cl_subset C hX hFX htCl
  · intro t ht
    have hst : IsTok C {t} := ⟨Set.finite_singleton t, X, hX, Set.singleton_subset_iff.mpr ht⟩
    rw [mem_toC]
    refine ⟨⟨{t}, hst⟩, ?_, subset_Cl C {t} rfl⟩
    exact ⟨⟨⟨{t}, hst⟩, rfl⟩, ⟨{t}, hst⟩, Set.singleton_subset_iff.mpr ht, subset_rfl⟩


-- @@ L275-275 verbatim
variable (hDir : ∀ 𝒮 : Set (Set τ), 𝒮.Nonempty → 𝒮 ⊆ C → DirectedOn (· ⊆ ·) 𝒮 → ⋃₀ 𝒮 ∈ C)


-- @@ L277-288 verbatim
include hDir in
/-- `toC x ∈ C`: the represented set lies in the family (closure under directed
unions). -/
theorem toC_mem (x : (reprSystem C hInter hne).Element) : toC C hInter hne x ∈ C := by
  change ⋃₀ famC C hInter hne x ∈ C
  apply hDir (famC C hInter hne x)
  · exact ⟨Cl C (botTok C hne).1, botTok C hne, mem_nbhd_bot C hInter hne x, rfl⟩
  · rintro Y ⟨F, _, rfl⟩
    exact Cl_mem C hInter F.2.2
  · rintro Y ⟨F, hF, rfl⟩ Y' ⟨F', hF', rfl⟩
    obtain ⟨F₃, hF₃, hFF₃, hF'F₃⟩ := directed_step C hInter hne x hF hF'
    exact ⟨Cl C F₃.1, ⟨F₃, hF₃, rfl⟩, hFF₃, hF'F₃⟩


-- @@ L290-303 verbatim
/-- The other round-trip `ofC (toC x) = x`. -/
theorem ofC_toC (x : (reprSystem C hInter hne).Element) :
    ofC C hInter hne (toC C hInter hne x) (toC_mem C hInter hne hDir x) = x := by
  apply Element.ext
  intro N
  constructor
  · rintro ⟨hN, F, hFtoC, hFN⟩
    have hxF : x.mem (nbhd C F.1) := (mem_nbhd_iff C hInter hne x F).mpr hFtoC
    exact x.up_mem hxF hN hFN
  · intro hxN
    have hN : (reprSystem C hInter hne).mem N := x.sub hxN
    obtain ⟨G, rfl⟩ := hN
    have hGtoC : G.1 ⊆ toC C hInter hne x := (mem_nbhd_iff C hInter hne x G).mp hxN
    exact ⟨⟨G, rfl⟩, G, hGtoC, subset_rfl⟩


-- @@ L305-305 verbatim
/-! ### The representation isomorphism. -/


-- @@ L307-330 verbatim
include hDir in
/-- **Exercise 2.22 — the representation theorem.** `C`, ordered by inclusion, is
order-isomorphic
to the domain `|reprSystem|`. The isomorphism sends `x ↦ ⋃ {Fbar ∣ C(F) ∈ x}`
(`toC`) and
`X ↦ {C(F) ∣ F ⊆ X}` (`ofC`). -/
def reprIso : (reprSystem C hInter hne).Element ≃o {X : Set τ // X ∈ C} where
  toFun x := ⟨toC C hInter hne x, toC_mem C hInter hne hDir x⟩
  invFun X := ofC C hInter hne X.1 X.2
  left_inv x := ofC_toC C hInter hne hDir x
  right_inv X := Subtype.ext (toC_ofC C hInter hne X.1 X.2)
  map_rel_iff' := by
    intro a b
    change toC C hInter hne a ⊆ toC C hInter hne b ↔ a ≤ b
    constructor
    · intro hsub N hN
      have hmemD : (reprSystem C hInter hne).mem N := a.sub hN
      obtain ⟨G, rfl⟩ := hmemD
      have hGa : G.1 ⊆ toC C hInter hne a := (mem_nbhd_iff C hInter hne a G).mp hN
      exact (mem_nbhd_iff C hInter hne b G).mpr (hGa.trans hsub)
    · intro hab t ht
      rw [mem_toC] at ht ⊢
      obtain ⟨F, hF, htCl⟩ := ht
      exact ⟨F, hab _ hF, htCl⟩


-- @@ L332-332 verbatim
end Domain.Neighborhood.Exercise222
