/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.Lomega1omega.Entailment
public import LeanPool.InfinitaryLogic.Methods.GeneratedSublanguage
import LeanPool.InfinitaryLogic.Methods.Interpolation.CraigRelational
import LeanPool.InfinitaryLogic.Methods.LanguageMapOccurrence
import LeanPool.InfinitaryLogic.Methods.SymbSublangExpansion

-- @@ L13-31 verbatim
/-!
# Craig interpolation for `L_ω₁ω`, relational core without global countability (Layer 2)

Layer 1 (`craig_interpolation_relational_countable`) needs the whole language to have countably
many relation symbols.  This layer removes that hypothesis: an individual `L_ω₁ω` sentence mentions
only countably many symbols (`relationsIn_countable`), so the two roots `r₁, r₂` live inside the
sublanguage `symbSublang F R` generated by their (countable) combined symbol sets, which *is*
countable-relational.  We restrict both roots into that sublanguage, transport the entailment
(`entails_restrictSymbols_singleton`), apply Layer 1 there, and map the interpolant back along
`symbSublangIncl` — the reduct transport keeps the two entailments and the occurrence bounds intact.

```
craig_interpolation_relational [L.IsRelational] :
  Sentenceω.Entails r₁ r₂ →
    ∃ θ, θ.functionsIn ⊆ r₁.functionsIn ∩ r₂.functionsIn ∧
         θ.relationsIn ⊆ r₁.relationsIn ∩ r₂.relationsIn ∧
         Sentenceω.Entails r₁ θ ∧ Sentenceω.Entails θ r₂
```
-/


-- @@ L33-33 verbatim
@[expose] public section


-- @@ L35-35 verbatim
namespace FirstOrder.Language


-- @@ L37-37 verbatim
open FirstOrder Structure


-- @@ L39-39 verbatim
variable {L : Language.{0, 0}}


-- @@ L41-45 verbatim
/-! ## Mapping a sublanguage interpolant back to `L`: entailment and occurrence transport

These four transports are generic in the sublanguage inclusion — nothing about them is specific to
Craig — so they are exported for the Lyndon refinement (issue #14, Unit 5), which needs the same
entailment and function-occurrence transports alongside its own *signed* relation transport. -/


-- @@ L47-66 verbatim
/-- Left entailment transport: a sublanguage entailment `r₁.restrictSymbols ⊨ θ'` lifts, along the
inclusion, to `r₁ ⊨ θ'.mapLanguage incl` in `L` (via the sublanguage reduct of an `L`-model). -/
theorem entails_mapLanguage_restrictSymbols_left (F : Set (Σ n, L.Functions n))
    (R : Set (Σ n, L.Relations n)) (r : L.Sentenceω) (hF : r.functionsIn ⊆ F)
    (hR : r.relationsIn ⊆ R) (θ' : (symbSublang (L := L) F R).Sentenceω)
    (hE : Sentenceω.Entails (r.restrictSymbols hF hR) θ') :
    Sentenceω.Entails r (θ'.mapLanguage (symbSublangIncl F R)) := by
  rw [Sentenceω.entails_iff]
  intro M instM neM hr
  let instM' : (symbSublang (L := L) F R).Structure M := (symbSublangIncl F R).reduct M
  have : (symbSublangIncl F R).IsExpansionOn M := LHom.isExpansionOn_reduct (symbSublangIncl F R) M
  have hr' : @Sentenceω.Realize (symbSublang (L := L) F R) (r.restrictSymbols hF hR) M instM' := by
    have hiff :=
      BoundedFormulaω.realize_mapLanguage (symbSublangIncl F R) (r.restrictSymbols hF hR)
        (Empty.elim : Empty → M) Fin.elim0
    rw [BoundedFormulaω.mapLanguage_restrictSymbols] at hiff
    exact hiff.mp hr
  exact
    (BoundedFormulaω.realize_mapLanguage (symbSublangIncl F R) θ'
      (Empty.elim : Empty → M) Fin.elim0).mpr ((Sentenceω.entails_iff.mp hE) M hr')


-- @@ L68-85 verbatim
/-- Right entailment transport: a sublanguage entailment `θ' ⊨ r₂.restrictSymbols` lifts to
`θ'.mapLanguage incl ⊨ r₂` in `L`. -/
theorem entails_mapLanguage_restrictSymbols_right (F : Set (Σ n, L.Functions n))
    (R : Set (Σ n, L.Relations n)) (r : L.Sentenceω) (hF : r.functionsIn ⊆ F)
    (hR : r.relationsIn ⊆ R) (θ' : (symbSublang (L := L) F R).Sentenceω)
    (hE : Sentenceω.Entails θ' (r.restrictSymbols hF hR)) :
    Sentenceω.Entails (θ'.mapLanguage (symbSublangIncl F R)) r := by
  rw [Sentenceω.entails_iff]
  intro M instM neM hθ
  let instM' : (symbSublang (L := L) F R).Structure M := (symbSublangIncl F R).reduct M
  have : (symbSublangIncl F R).IsExpansionOn M := LHom.isExpansionOn_reduct (symbSublangIncl F R) M
  have hθ' : @Sentenceω.Realize (symbSublang (L := L) F R) θ' M instM' :=
    (BoundedFormulaω.realize_mapLanguage (symbSublangIncl F R) θ'
      (Empty.elim : Empty → M) Fin.elim0).mp hθ
  have hr :=
    (BoundedFormulaω.realize_mapLanguage (symbSublangIncl F R) (r.restrictSymbols hF hR)
      (Empty.elim : Empty → M) Fin.elim0).mpr ((Sentenceω.entails_iff.mp hE) M hθ')
  rwa [BoundedFormulaω.mapLanguage_restrictSymbols] at hr


-- @@ L87-96 verbatim
/-- Function-occurrence transport: the mapped interpolant's functions stay within `r`'s functions,
given the sublanguage bound against the restriction. -/
theorem functionsIn_mapLanguage_incl_subset (F : Set (Σ n, L.Functions n))
    (R : Set (Σ n, L.Relations n)) (r : L.Sentenceω) (hF : r.functionsIn ⊆ F)
    (hR : r.relationsIn ⊆ R) (θ' : (symbSublang (L := L) F R).Sentenceω)
    (hsub : θ'.functionsIn ⊆ (r.restrictSymbols hF hR).functionsIn) :
    (θ'.mapLanguage (symbSublangIncl F R)).functionsIn ⊆ r.functionsIn := by
  rw [BoundedFormulaω.functionsIn_mapLanguage,
    ← BoundedFormulaω.mapLanguage_restrictSymbols r hF hR, BoundedFormulaω.functionsIn_mapLanguage]
  exact Set.image_mono hsub


-- @@ L98-106 verbatim
/-- Relation-occurrence transport (companion of the above for relation symbols). -/
theorem relationsIn_mapLanguage_incl_subset (F : Set (Σ n, L.Functions n))
    (R : Set (Σ n, L.Relations n)) (r : L.Sentenceω) (hF : r.functionsIn ⊆ F)
    (hR : r.relationsIn ⊆ R) (θ' : (symbSublang (L := L) F R).Sentenceω)
    (hsub : θ'.relationsIn ⊆ (r.restrictSymbols hF hR).relationsIn) :
    (θ'.mapLanguage (symbSublangIncl F R)).relationsIn ⊆ r.relationsIn := by
  rw [BoundedFormulaω.relationsIn_mapLanguage,
    ← BoundedFormulaω.mapLanguage_restrictSymbols r hF hR, BoundedFormulaω.relationsIn_mapLanguage]
  exact Set.image_mono hsub


-- @@ L108-108 verbatim
/-! ## The relational Craig theorem (no global countability hypothesis) -/


-- @@ L110-145 verbatim
/-- **Craig interpolation for `L_ω₁ω` — relational, no global countability hypothesis.** Over a
purely relational language (of arbitrarily many symbols), an `L_ω₁ω`-entailment `r₁ ⊨ r₂` has a
base-`L` interpolant whose symbols lie in the intersection of the roots' occurrence sets. -/
theorem craig_interpolation_relational [L.IsRelational] (r₁ r₂ : L.Sentenceω)
    (h : Sentenceω.Entails r₁ r₂) :
    ∃ θ : L.Sentenceω,
      θ.functionsIn ⊆ r₁.functionsIn ∩ r₂.functionsIn ∧
      θ.relationsIn ⊆ r₁.relationsIn ∩ r₂.relationsIn ∧
      Sentenceω.Entails r₁ θ ∧ Sentenceω.Entails θ r₂ := by
  -- The sublanguage generated by the two roots' (countable) combined symbol sets.
  set F : Set (Σ n, L.Functions n) := r₁.functionsIn ∪ r₂.functionsIn with hF
  set R : Set (Σ n, L.Relations n) := r₁.relationsIn ∪ r₂.relationsIn with hR
  have hRc : R.Countable := (r₁.relationsIn_countable).union (r₂.relationsIn_countable)
  have hr₁F : r₁.functionsIn ⊆ F := Set.subset_union_left
  have hr₁R : r₁.relationsIn ⊆ R := Set.subset_union_left
  have hr₂F : r₂.functionsIn ⊆ F := Set.subset_union_right
  have hr₂R : r₂.relationsIn ⊆ R := Set.subset_union_right
  -- Restrict both roots and transport the entailment into the sublanguage.
  have hE' : Sentenceω.Entails (r₁.restrictSymbols hr₁F hr₁R) (r₂.restrictSymbols hr₂F hr₂R) :=
    entails_restrictSymbols_singleton F R r₁ r₂ hr₁F hr₁R hr₂F hr₂R h
  -- Apply Layer 1 in the sublanguage (relational + countably many relations).
  have : Countable (Σ n, (symbSublang (L := L) F R).Relations n) :=
    symbSublang_rel_countable F hRc
  obtain ⟨θ', hθ'F, hθ'R, hE1', hE2'⟩ :=
    craig_interpolation_relational_countable (r₁.restrictSymbols hr₁F hr₁R)
      (r₂.restrictSymbols hr₂F hr₂R) hE'
  -- Map the interpolant back to `L`; transport the four conclusions.
  refine ⟨θ'.mapLanguage (symbSublangIncl F R), ?_, ?_, ?_, ?_⟩
  · exact Set.subset_inter
      (functionsIn_mapLanguage_incl_subset F R r₁ hr₁F hr₁R θ' (hθ'F.trans Set.inter_subset_left))
      (functionsIn_mapLanguage_incl_subset F R r₂ hr₂F hr₂R θ' (hθ'F.trans Set.inter_subset_right))
  · exact Set.subset_inter
      (relationsIn_mapLanguage_incl_subset F R r₁ hr₁F hr₁R θ' (hθ'R.trans Set.inter_subset_left))
      (relationsIn_mapLanguage_incl_subset F R r₂ hr₂F hr₂R θ' (hθ'R.trans Set.inter_subset_right))
  · exact entails_mapLanguage_restrictSymbols_left F R r₁ hr₁F hr₁R θ' hE1'
  · exact entails_mapLanguage_restrictSymbols_right F R r₂ hr₂F hr₂R θ' hE2'


-- @@ L147-147 verbatim
end FirstOrder.Language
