/-
Copyright (c) 2026 Alfie Davies, Tomasz Maciosowski. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alfie Davies, Tomasz Maciosowski
-/
module

public import LeanPool.MisereGames.OfSets
public import Mathlib.Algebra.Group.Pointwise.Set.Small
public import Mathlib.Algebra.CharZero.Defs
import LeanPool.MisereGames.Mathlib.Small


-- @@ L13-15 verbatim
/-!
Misere combinatorial games.
-/


-- @@ L17-17 verbatim
namespace MisereGames


-- @@ L19-19 verbatim
universe u v


-- @@ L21-21 verbatim
public section


-- @@ L23-26 verbatim
/-- The immediate-option relation determined by a raw move function. -/
@[expose]
def Moves.IsOption' {G : Type v} (moves : Player → G → Set G) (x y : G) : Prop :=
  x ∈ ⋃ p, moves p y


-- @@ L28-33 verbatim
/-- A type with Left and Right moves and a well-founded option relation. -/
class Moves (G : Type v) where
  /-- The positions reachable by a move for a player. -/
  moves (p : Player) (x : G) : Set G
  /-- The option relation generated by `moves` is well-founded. -/
  isOption'_wf : WellFounded (Moves.IsOption' moves)


-- @@ L35-64 expanded
/-- A type of combinatorial game forms with negation, addition, and set construction. -/
class Form (G : Type (v + 1)) extends Moves G, OfSets G fun _ ↦ True, InvolutiveNeg G,
    AddCommSemigroup G where
  moves_neg' (p : Player) (x : G) : moves p (-x) = Set.neg.neg (moves (-p) x)
  moves_add' (p : Player) (x y : G) : moves p (x + y) = (· + y) '' moves p x ∪ (x + ·) '' moves p y
  moves_small' (p : Player) (x : G) : Small.{v} (moves p x)
  moves_ofSets' (p : Player) (st : Player → Set G) [Small.{v} (st .left)] [Small.{v} (st .right)] :
    moves p
        (OfSets.ofSets st
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) =
      st p
  add_zero' (x : G) :
    x +
        OfSets.ofSets (fun _ => ∅)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      x
  add_eq_zero_iff' (x y : G) :
    x + y =
        OfSets.ofSets (fun _ => ∅)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") ↔
      x =
          OfSets.ofSets (fun _ => ∅)
            (by
              first
              | done
              | trivial
              | assumption
              | aesop
              |
                fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                  where `h` is a proof that sets are valid") ∧
        y =
          OfSets.ofSets (fun _ => ∅)
            (by
              first
              | done
              | trivial
              | assumption
              | aesop
              |
                fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                  where `h` is a proof that sets are valid")
  ofSets_inj'' {st₁ st₂ : Player → Set G} [Small (st₁ .left)] [Small (st₁ .right)]
    [Small (st₂ .left)] [Small (st₂ .right)] :
    OfSets.ofSets st₁
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
        OfSets.ofSets st₂
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") ↔
      st₁ = st₂
  neg_ofSets'' (s t : Set G) [Small s] [Small t] :
    -OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      OfSets.ofSets (Player.cases (-t) (-s))
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid")
  neg_add' (x y : G) : -(x + y) = -x + -y
  smallElemMoves' (p : Player) (x : G) : Small.{v} (moves p x)
  /-- Positions that behave like ends for a player in the ambient form type. -/
  IsEndLike (p : Player) (x : G) : Prop
  ofSets_isEndLike_iff' (p : Player) (s t : Set G) [Small s] [Small t] :
    IsEndLike p
        (OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) ↔
      moves p
          (OfSets.ofSets (Player.cases s t)
            (by
              first
              | done
              | trivial
              | assumption
              | aesop
              |
                fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                  where `h` is a proof that sets are valid")) =
        ∅
  ofSets_add_ofSets'' (s₁ t₁ s₂ t₂ : Set G) [Small s₁] [Small t₁] [Small s₂] [Small t₂] :
    OfSets.ofSets (Player.cases s₁ t₁)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") +
        OfSets.ofSets (Player.cases s₂ t₂)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      OfSets.ofSets
        (Player.cases
          ((· +
                OfSets.ofSets (Player.cases s₂ t₂)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid")) ''
              s₁ ∪
            (OfSets.ofSets (Player.cases s₁ t₁)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid") +
                ·) ''
              s₂)
          ((· +
                OfSets.ofSets (Player.cases s₂ t₂)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid")) ''
              t₁ ∪
            (OfSets.ofSets (Player.cases s₁ t₁)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid") +
                ·) ''
              t₂))
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid")
  isEndLike_ofEnd' (p : Player) (x : G) (h1 : moves p x = ∅) : IsEndLike p x
  isEndLike_add_iff' (p : Player) (x y : G) : IsEndLike p (x + y) ↔ IsEndLike p x ∧ IsEndLike p y
  isEndLike_neg_iff_neg' (p : Player) (g : G) : IsEndLike p (-g) ↔ IsEndLike (-p) g
  ofSets_moves_of_not_isEndLike' (g : G) [Small.{v} (moves .left g)] [Small.{v} (moves .right g)]
    (h : ∀ p, ¬IsEndLike p g) :
    OfSets.ofSets (fun p => moves p g)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") =
      g


-- @@ L66-66 verbatim
namespace Moves


-- @@ L68-68 verbatim
variable {G : Type (u + 1)} [g_moves : Moves G]


-- @@ L70-82 verbatim
/--
`IsOption x y` means that `x` is either a Left or a Right option for `y`.
-/
@[expose]
def IsOption (x y : G) : Prop := IsOption' g_moves.moves x y

-- TODO: remove this or keep?

-- /-- The set of left moves of the game. -/
-- scoped notation:max g:max "ᴸ" => Form.moves Player.left g

-- /-- The set of right moves of the game. -/
-- scoped notation:max g:max "ᴿ" => Form.moves Player.right g


-- @@ L84-87 verbatim
@[aesop simp]
lemma IsOption.iff_mem_union {x y : G} :
    IsOption x y ↔ x ∈ moves .left y ∪ moves .right y := by
  simp [IsOption, IsOption', Player.exists]


-- @@ L89-90 verbatim
theorem IsOption.of_mem_moves {x y : G} {p : Player} (h : x ∈ moves p y) :
    IsOption x y := ⟨_, ⟨p, rfl⟩, h⟩


-- @@ L92-93 verbatim
instance (x : G) : Small.{u + 1} {y // IsOption y x} :=
  inferInstanceAs (Small (⋃ p, moves p x))


-- @@ L95-95 verbatim
theorem isOption_wf : WellFounded (@IsOption G _) := g_moves.isOption'_wf


-- @@ L97-97 verbatim
instance : WellFounded (@IsOption G _) := isOption_wf


-- @@ L99-99 verbatim
theorem IsOption.irrefl (x : G) : ¬ IsOption x x := fun h ↦ WellFounded.asymmetric x x h h


-- @@ L101-102 verbatim
theorem self_notMem_moves (p : Player) (x : G) : x ∉ moves p x :=
  fun hx ↦ IsOption.irrefl x (.of_mem_moves hx)


-- @@ L104-112 verbatim
/--
A *proper subposition* is an element of the transitive closure of `IsOption`.
Note that this is not the reflexive-transitive closure! While it is common to
say that $G$ is a subposition of $G$ in the literature, here `Subposition`
refers to a proper subposition.
-/
@[expose]
def Subposition : G → G → Prop :=
  Relation.TransGen IsOption


-- @@ L114-115 verbatim
theorem Subposition.of_isOption {x y : G} (h : IsOption x y) : Subposition x y :=
  Relation.TransGen.single h


-- @@ L117-119 verbatim
@[aesop apply 50%]
theorem Subposition.of_mem_moves {p} {x y : G} (h : x ∈ moves p y) : Subposition x y :=
  Subposition.of_isOption (.of_mem_moves h)


-- @@ L121-123 verbatim
theorem Subposition.trans {x y z : G} (h₁ : Subposition x y) (h₂ : Subposition y z) :
    Subposition x z :=
  Relation.TransGen.trans h₁ h₂


-- @@ L125-126 verbatim
instance (x : G) : Small.{u + 1} {y // Subposition y x} :=
  small_transGen' _ x


-- @@ L128-128 verbatim
instance : IsTrans _ (@Subposition G _) := inferInstanceAs (IsTrans _ (Relation.TransGen _))

-- @@ L129-130 verbatim
instance :
    WellFounded (@Subposition G _) := inferInstanceAs (WellFounded (Relation.TransGen _))

-- @@ L131-131 verbatim
instance : WellFoundedRelation G := ⟨Subposition, inferInstance⟩


-- @@ L133-137 verbatim
/-- Solve routine well-foundedness goals generated by recursive form definitions. -/
macro (name := formWf) "form_wf" : tactic =>
  `(tactic| all_goals solve_by_elim (maxDepth := 8)
    [Prod.Lex.left, Prod.Lex.right, PSigma.Lex.left, PSigma.Lex.right,
    Subposition.of_mem_moves, Subposition.trans, Subtype.prop] )


-- @@ L139-139 verbatim
end Moves


-- @@ L141-141 verbatim
namespace Form


-- @@ L143-143 verbatim
export Moves (IsOption IsOption.iff_mem_union IsOption.of_mem_moves Subposition moves)


-- @@ L145-146 verbatim
/-- A position is an end for `p` when `p` has no legal move. -/
def IsEnd {G : Type (u + 1)} [Moves G] (p : Player) (g : G) := moves p g = ∅


-- @@ L148-149 verbatim
theorem isEnd_def {G : Type (u + 1)} [Moves G] (p : Player) (g : G) :
    IsEnd p g = (moves p g = ∅) := by rfl


-- @@ L151-153 verbatim
theorem not_isEnd_def {G : Type (u + 1)} [Moves G] (p : Player) (g : G) :
    ¬(IsEnd p g) ↔ (moves p g ≠ ∅) := by
  simp [isEnd_def]


-- @@ L155-155 verbatim
variable {G : Type (u + 1)} [g_form : Form G]


-- @@ L157-158 verbatim
theorem isEndLike_of_isEnd {p : Player} {x : G} (h1 : IsEnd p x) : IsEndLike p x :=
  isEndLike_ofEnd' p x h1


-- @@ L160-162 verbatim
@[simp]
protected theorem IsEndLike.add_iff {p : Player} {x y : G}
    : IsEndLike p (x + y) ↔ IsEndLike p x ∧ IsEndLike p y := isEndLike_add_iff' p x y


-- @@ L164-167 verbatim
@[simp]
protected theorem IsEndLike.neg_iff_neg {g : G} {p : Player} :
    IsEndLike p (-g) ↔ IsEndLike (-p) g :=
  isEndLike_neg_iff_neg' p g


-- @@ L169-171 verbatim
@[simp]
theorem moves_neg (p : Player) (x : G) : moves p (-x) = Set.neg.neg (moves (-p) x) :=
  moves_neg' p x


-- @@ L173-176 verbatim
@[simp 900]
theorem moves_add (p : Player) (x y : G) :
    moves p (x + y) = (· + y) '' moves p x ∪ (x + ·) '' moves p y :=
  moves_add' p x y


-- @@ L178-178 verbatim
instance instSmallElemMoves (p : Player) (x : G) : Small.{u} (moves p x) := smallElemMoves' p x


-- @@ L180-183 expanded
@[simp]
theorem moves_ofSets (p : Player) (st : Player → Set G) [Small.{u} (st .left)]
    [Small.{u} (st .right)] :
    moves p
        (OfSets.ofSets st
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) =
      st p :=
  moves_ofSets' p st


-- @@ L185-188 expanded
/-- Away from end-like positions, a form is determined by its sets of moves. -/
theorem ofSets_moves_of_not_isEndLike {g : G} (h : ∀ p, ¬IsEndLike p g) :
    OfSets.ofSets (fun p => moves p g)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") =
      g :=
  ofSets_moves_of_not_isEndLike' g h


-- @@ L190-192 expanded
@[simp high]
theorem leftMoves_ofSets (s t : Set G) [Small.{u} s] [Small.{u} t] :
    moves .left
        (OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) =
      s :=
  moves_ofSets ..


-- @@ L194-196 expanded
@[simp high]
theorem rightMoves_ofSets (s t : Set G) [Small.{u} s] [Small.{u} t] :
    moves .right
        (OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) =
      t :=
  moves_ofSets ..


-- @@ L198-201 expanded
@[simp]
theorem ofSets_inj' {st₁ st₂ : Player → Set G} [Small (st₁ .left)] [Small (st₁ .right)]
    [Small (st₂ .left)] [Small (st₂ .right)] :
    OfSets.ofSets st₁
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
        OfSets.ofSets st₂
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") ↔
      st₁ = st₂ :=
  ofSets_inj''


-- @@ L203-205 expanded
theorem ofSets_inj {s₁ s₂ t₁ t₂ : Set G} [Small s₁] [Small s₂] [Small t₁] [Small t₂] :
    OfSets.ofSets (Player.cases s₁ t₁)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
        OfSets.ofSets (Player.cases s₂ t₂)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") ↔
      s₁ = s₂ ∧ t₁ = t₂ :=
  by simp


-- @@ L207-207 expanded
instance : Zero G :=
  ⟨OfSets.ofSets (fun _ ↦ ∅)
      (by
        first
        | done
        | trivial
        | assumption
        | aesop
        |
          fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
            where `h` is a proof that sets are valid")⟩


-- @@ L209-209 expanded
theorem zero_def :
    (0 : G) =
      OfSets.ofSets (fun _ ↦ ∅)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  rfl


-- @@ L211-213 verbatim
@[simp]
theorem moves_zero (p : Player) : moves p (0 : G) = ∅ := by
  simp [zero_def]


-- @@ L215-216 verbatim
@[simp]
theorem isEnd_zero {p : Player} : IsEnd p (0 : G) := moves_zero p


-- @@ L218-222 verbatim
/--
A form is *zero-like* if it is both a Left and a Right end, just like `0`.
-/
@[expose]
def IsZeroLike (g : G) : Prop := ∀ p, IsEnd p g


-- @@ L224-225 verbatim
@[simp]
theorem isZeroLike_zero : IsZeroLike (0 : G) := fun _ => isEnd_zero


-- @@ L227-228 expanded
@[simp]
theorem neg_ofSets (s t : Set G) [Small s] [Small t] :
    -OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      OfSets.ofSets (Player.cases (-t) (-s))
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  neg_ofSets'' s t


-- @@ L230-236 expanded
@[simp]
theorem neg_ofSets_const (s : Set G) [Small s] :
    -OfSets.ofSets (fun _ ↦ s)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      OfSets.ofSets (fun _ ↦ -s)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  by
  rw [ofSets_eq_ofSets_cases, ofSets_eq_ofSets_cases]
  simp only [Player.cases, neg_ofSets, ofSets_inj']
  funext p
  cases p <;> rfl


-- @@ L238-239 verbatim
instance : NegZeroClass G where
  neg_zero := by simp only [zero_def, neg_ofSets_const, Set.neg_empty]


-- @@ L241-241 verbatim
instance : Inhabited G := ⟨0⟩


-- @@ L243-243 expanded
instance : One G :=
  ⟨OfSets.ofSets (Player.cases {0} ∅)
      (by
        first
        | done
        | trivial
        | assumption
        | aesop
        |
          fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
            where `h` is a proof that sets are valid")⟩


-- @@ L245-245 expanded
theorem one_def :
    (1 : G) =
      OfSets.ofSets (Player.cases {0} ∅)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  rfl


-- @@ L247-247 verbatim
@[simp] theorem leftMoves_one : moves .left (1 : G) = {0} := leftMoves_ofSets ..

-- @@ L248-248 verbatim
@[simp] theorem rightMoves_one : moves .right (1 : G) = ∅ := rightMoves_ofSets ..


-- @@ L250-252 verbatim
@[simp]
theorem moves_small (p : Player) (x : G) : Small.{u} (moves p x) :=
  moves_small' p x


-- @@ L254-256 verbatim
theorem exists_moves_neg {P : G → Prop} {p : Player} {x : G} :
    (∃ y ∈ Moves.moves p (-x), P y) ↔ (∃ y ∈ Moves.moves (-p) x, P (-y)) := by
  simp only [moves_neg, Set.mem_neg, Set.exists_neg_mem]


-- @@ L258-266 verbatim
@[simp]
theorem IsEnd.add_iff {g h : G} {p : Player} :
    IsEnd p (g + h) ↔ (IsEnd p g ∧ IsEnd p h) := by
  constructor <;> intro h1
  · unfold IsEnd at *
    simp_all
  · unfold IsEnd at h1
    simp only [IsEnd, moves_add, Set.union_empty_iff, Set.image_eq_empty]
    exact h1


-- @@ L268-273 verbatim
theorem IsEnd.neg_iff_neg {g : G} {p : Player} : IsEnd p (-g) ↔ IsEnd (-p) g := by
  constructor <;> cases p
  all_goals
  · intro h1
    simp only [IsEnd, moves_neg, Set.neg_eq_empty] at *
    exact h1


-- @@ L275-277 verbatim
theorem mem_moves_ne_zero {g gl : G} {p : Player} (h1 : gl ∈ moves p g) : g ≠ 0 := by
  intro h2
  simp only [h2, moves_zero, Set.mem_empty_iff_false] at h1


-- @@ L279-281 verbatim
theorem not_isEnd_ne_zero {g : G} {p : Player} (h1 : ¬(IsEnd p g)) : g ≠ 0 := by
  intro h2
  simp_all


-- @@ L283-290 verbatim
theorem not_isEnd_exists_move {g : G} {p : Player}
    (h1 : ¬IsEnd p g) :
    ∃ gp, gp ∈ moves p g := by
  unfold IsEnd at h1
  by_contra h4
  simp only [not_exists] at h4
  absurd h1
  exact Set.subset_eq_empty h4 rfl


-- @@ L292-295 verbatim
@[simp]
theorem not_mem_moves_of_isEnd {p : Player} {g gp : G} (h1 : IsEnd p g) : gp ∉ moves p g := by
  rw [isEnd_def] at h1
  simp [h1]


-- @@ L297-299 verbatim
theorem not_isEnd_of_mem_moves {p : Player} {g g' : G} (h1 : g' ∈ moves p g) : ¬IsEnd p g := by
  rw [isEnd_def]
  exact ne_of_mem_of_not_mem' h1 id


-- @@ L301-303 verbatim
@[aesop apply 50%]
theorem not_isEnd_add_left {p : Player} {g h : G} (h_not_isEnd : ¬IsEnd p g) :
    ¬IsEnd p (g + h) := by simp [h_not_isEnd]


-- @@ L305-307 verbatim
@[aesop apply 50%]
theorem not_isEnd_add_right {p : Player} {g h : G} (h_not_isEnd : ¬IsEnd p h) :
    ¬IsEnd p (g + h) := by simp [h_not_isEnd]



-- @@ L310-312 verbatim
theorem add_left_mem_moves_add {p : Player} {x y : G} (h : x ∈ moves p y) (z : G) :
    z + x ∈ moves p (z + y) := by
  rw [moves_add]; right; use x


-- @@ L314-316 verbatim
theorem add_right_mem_moves_add {p : Player} {x y : G} (h : x ∈ moves p y) (z : G) :
    x + z ∈ moves p (y + z) := by
  rw [moves_add]; left; use x


-- @@ L318-323 verbatim
instance : AddCommMonoid G where
  add_zero := add_zero'
  zero_add _ := add_comm (G := G) .. ▸ add_zero' _
  add_comm := add_comm
  add_assoc := add_assoc
  nsmul := nsmulRec


-- @@ L325-326 verbatim
instance : SubNegMonoid G where
  zsmul := zsmulRec


-- @@ L328-328 verbatim
instance : AddCommMonoidWithOne G where


-- @@ L330-334 verbatim
theorem sub_left_mem_moves_sub {p : Player} {x y : G} (h : x ∈ moves p y) (z : G) :
    z - x ∈ moves (-p) (z - y) := by
  rw [sub_eq_add_neg, sub_eq_add_neg]
  apply add_left_mem_moves_add;
  simpa [moves_neg]


-- @@ L336-340 verbatim
theorem sub_left_mem_moves_sub_neg {p : Player} {x y : G} (h : x ∈ moves (-p) y) (z : G) :
    z - x ∈ moves p (z - y) := by
  rw [sub_eq_add_neg, sub_eq_add_neg]
  apply add_left_mem_moves_add;
  simpa [moves_neg]


-- @@ L342-345 verbatim
theorem sub_right_mem_moves_sub {p : Player} {x y : G} (h : x ∈ moves p y) (z : G) :
    x - z ∈ moves p (y - z) := by
  rw [sub_eq_add_neg, sub_eq_add_neg]
  exact add_right_mem_moves_add h _


-- @@ L347-350 verbatim
theorem exists_moves_add {p : Player} {P : G → Prop} {x y : G} :
    (∃ a ∈ moves p (x + y), P a) ↔
      (∃ a ∈ moves p x, P (a + y)) ∨ (∃ b ∈ moves p y, P (x + b)) := by
  aesop


-- @@ L352-354 verbatim
@[aesop simp]
lemma isOption_iff_mem_union {x y : G} : IsOption x y ↔ x ∈ moves .left y ∪ moves .right y := by
  simp [IsOption, Moves.IsOption', Player.exists]


-- @@ L356-357 verbatim
lemma isOption_iff_mem_moves {x y : G} : IsOption x y ↔ ∃ p, x ∈ moves p y := by
  simp [IsOption, Moves.IsOption', Player.exists]


-- @@ L359-359 verbatim
@[simp] theorem not_isOption_zero (g : G) : ¬IsOption g 0 := by simp [IsOption, Moves.IsOption']


-- @@ L361-367 verbatim
private theorem isOption_zero_neg.aux {g : G} (h_isOption : IsOption 0 (-g)) : IsOption 0 g := by
  simp only [isOption_iff_mem_union, Player.le_left, moves_neg, Player.neg_left, Player.right_le,
             Player.le_right_eq, Player.neg_right, Player.le_left_eq, Set.mem_union, Set.mem_neg,
             neg_zero] at h_isOption
  apply Or.elim h_isOption
  · exact IsOption.of_mem_moves
  · exact IsOption.of_mem_moves


-- @@ L369-375 verbatim
@[simp]
theorem isOption_zero_neg_iff {g : G} : IsOption 0 (-g) ↔ IsOption 0 g := by
  constructor
  · exact isOption_zero_neg.aux
  · intro h_isOption
    rw [<-neg_neg g] at h_isOption
    exact isOption_zero_neg.aux h_isOption


-- @@ L377-384 verbatim
theorem isOption_not_mem {p : Player} {g g' : G}
    (h_isOption : IsOption g' g) (h_mem : g' ∉ moves p g) :
    g' ∈ moves (-p) g := by
  simp only [isOption_iff_mem_moves] at h_isOption
  obtain ⟨q, h_q⟩ := h_isOption
  by_cases h_pq : p = q
  · simp_all
  · simp_all


-- @@ L386-392 verbatim
theorem isOption_not_mem_neg {p : Player} {g g' : G}
    (h_isOption : IsOption g' g) (h_mem : g' ∉ moves (-p) g) :
    g' ∈ moves p g := by
  have := isOption_not_mem h_isOption h_mem
  rwa [neg_neg] at this

-- Casts


-- @@ L394-398 verbatim
theorem leftMoves_natCast_succ' : ∀ n : ℕ, moves .left (n.succ : G) = {(n : G)}
  | 0 => by simp
  | n + 1 => by
    rw [Nat.cast_succ, moves_add, leftMoves_natCast_succ']
    simp


-- @@ L400-403 verbatim
@[simp 1100]
theorem leftMoves_natCast_succ (n : ℕ) : moves .left ((n + 1) : G) = {(n : G)} := by
  norm_cast
  exact leftMoves_natCast_succ' n


-- @@ L405-410 verbatim
@[simp 1100]
theorem rightMoves_natCast : ∀ n : ℕ, moves .right (n : G) = ∅
  | 0 => by simp [moves_zero]
  | n + 1 => by
    rw [Nat.cast_succ, moves_add, rightMoves_natCast]
    simp


-- @@ L412-417 verbatim
@[simp 1100]
theorem leftMoves_ofNat (n : ℕ) [n.AtLeastTwo] : moves .left (ofNat(n) : G) = {((n - 1 : ℕ) :
    G)} := by
  change moves .left (n : G) = _
  rw [← Nat.succ_pred (NeZero.out (n := n)), leftMoves_natCast_succ']
  simp


-- @@ L419-421 verbatim
@[simp 1100]
theorem rightMoves_ofNat (n : ℕ) [n.AtLeastTwo] : moves .right (ofNat(n) : G) = ∅ :=
  rightMoves_natCast n


-- @@ L423-426 verbatim
instance : IntCast G where
  intCast
  | .ofNat n => n
  | .negSucc n => -(n + 1)


-- @@ L428-429 verbatim
@[simp, norm_cast]
protected theorem intCast_nat (n : ℕ) : ((n : ℤ) : G) = n := rfl


-- @@ L431-432 verbatim
@[simp]
protected theorem intCast_ofNat (n : ℕ) : ((ofNat(n) : ℤ) : G) = n := rfl


-- @@ L434-435 verbatim
@[simp]
protected theorem intCast_negSucc (n : ℕ) : (Int.negSucc n : G) = -(n + 1) := rfl


-- @@ L437-438 verbatim
@[norm_cast]
protected theorem intCast_zero : ((0 : ℤ) : G) = 0 := by simp


-- @@ L440-441 verbatim
@[norm_cast]
protected theorem intCast_one : ((1 : ℤ) : G) = 1 := by simp


-- @@ L443-444 verbatim
@[norm_cast]
protected theorem natCast_zero : ((0 : ℕ) : G) = 0 := by simp


-- @@ L446-447 verbatim
@[norm_cast]
protected theorem natCast_one : ((1 : ℕ) : G) = 1 := by simp


-- @@ L449-458 verbatim
@[simp, norm_cast]
protected theorem intCast_neg (n : ℤ) : ((-n : ℤ) : G) = -(n : G) := by
  cases n with
  | ofNat n =>
    induction n with
    | zero => simp
    | succ k ih => rfl
  | negSucc n =>
    simp only [Form.intCast_negSucc, neg_neg, Int.neg_negSucc]
    norm_cast


-- @@ L460-465 verbatim
@[simp]
theorem leftMoves_eq_natCast_zero_lt {a : ℕ} (h1 : 0 < a)
    : moves .left (a : G) = {((a - 1 : ℕ) : G)} := by
  obtain ⟨x, h2⟩ := Nat.exists_add_one_eq.mpr h1
  rw [<-h2, Nat.cast_add, Nat.cast_one, leftMoves_natCast_succ]
  rfl


-- @@ L467-469 verbatim
theorem leftMoves_natCast_zero_lt {a : ℕ} (h1 : 0 < a)
    : ((a - 1 : ℕ) : G) ∈ moves .left (a : G) := by
  simp [h1]


-- @@ L471-475 verbatim
@[simp 1100] -- This should trigger before `leftMoves_add`.
theorem leftMoves_intCast_succ {n : ℤ} (h1 : 0 ≤ n) : moves .left ((n + 1) : G) = {(n : G)} := by
  match n with
  | Int.ofNat n => simp
  | Int.negSucc k => simp


-- @@ L477-486 verbatim
@[simp]
theorem leftMoves_intCast {a : ℤ} (h1 : 0 < a)
    : moves .left (a : G) = {((a - 1 : ℤ) : G)} := by
  obtain ⟨a', h_a'⟩ := (CanLift.prf a h1.le : ∃ (a' : ℕ), a' = a)
  rw [<-h_a']
  have : ∃ x, x + 1 = a' := by use a' - 1; omega
  obtain ⟨x, h2⟩ := this
  rw [<-h2]
  norm_cast
  simp


-- @@ L488-490 verbatim
theorem leftMoves_intCast_zero_lt {a : ℤ} (h1 : 0 < a)
    : ((a - 1 : ℤ) : G) ∈ moves .left (a : G) := by
  simp [h1]


-- @@ L492-495 verbatim
theorem leftMoves_intCast_zero_le_succ {a : ℤ} (h1 : 0 ≤ a)
    : ((a : ℤ) : G) ∈ moves .left (((a + 1) : ℤ) : G) := by
  have := leftMoves_intCast_zero_lt (G := G) (Int.le_iff_lt_add_one.mp h1)
  simp_all


-- @@ L497-501 verbatim
theorem leftMoves_intCast_le_zero_of_empty {k : ℤ} (h1 : 0 ≤ k) (h2 : moves .left (k : G) = ∅)
    : k = 0 := by
  obtain h_lt | h_eq := lt_or_eq_of_le h1
  · simp_all
  · exact h_eq.symm


-- @@ L503-507 verbatim
theorem leftMoves_intCast_le_one_eq {a : ℤ} (h1 : 1 ≤ a)
    : moves .left ((a : ℤ) : G) = {((a - 1 : ℤ) : G)} := by
  obtain ⟨x, h2⟩ := Int.le.dest h1
  rw [<-h2, Int.add_comm 1 _]
  simp


-- @@ L509-512 verbatim
@[simp]
theorem leftMoves_intCast_le_one_ne_empty {a : ℤ} (h1 : 1 ≤ a)
    : moves .left ((a : ℤ) : G) ≠ ∅ := by
  simp [leftMoves_intCast_le_one_eq h1]


-- @@ L514-519 verbatim
@[simp]
theorem rightMoves_intCast {a : ℤ} (h1 : 0 ≤ a) : moves .right (a : G) = ∅ := by
  have h2 : 0 < a + 1 := by omega
  obtain ⟨x', h_x'⟩ := (CanLift.prf a h1 : ∃ (x' : ℕ), x' = a)
  rw [<-h_x', Form.intCast_nat]
  simp only [rightMoves_natCast]


-- @@ L521-530 verbatim
private protected theorem natCast_eq_zero_iff {n : ℕ} : (n : G) = 0 ↔ n = 0 := by
  constructor
  · cases n with
    | zero => simp only [Nat.cast_zero, imp_self]
    | succ n =>
      intro h
      exfalso
      have := moves_zero (G := G) .left
      simp [<-h] at this
  · simp_all


-- @@ L532-539 verbatim
theorem mem_moves_add_one_iff_mem_moves {g : G} {p : Player} {n : ℕ}
    : (g + 1 ∈ moves p (n + 1 : G)) ↔ (g ∈ moves p (n : G)) := by
  cases p
  · apply Iff.intro <;> intro h1
    · simp only [leftMoves_natCast_succ, Set.mem_singleton_iff] at h1
      simp [<-h1]
    · exact add_right_mem_moves_add h1 1
  · simp


-- @@ L541-543 verbatim
@[simp]
theorem one_isEnd_right : IsEnd .right (1 : G) := by
  simp only [isEnd_def, rightMoves_one]


-- @@ L545-547 verbatim
@[simp]
theorem not_isEnd_left_one : ¬IsEnd Player.left (1 : G) := by
  simp only [isEnd_def, leftMoves_one, Set.singleton_ne_empty, not_false_eq_true]


-- @@ L549-552 verbatim
theorem natCast_isEnd_right (n : ℕ) : IsEnd .right (n : G) := by
  induction n with
  | zero => simp only [Nat.cast_zero, isEnd_zero]
  | succ k ih => simp_all


-- @@ L554-556 expanded
@[simp]
theorem ofSets_isEndLike_iff {p : Player} {s t : Set G} [Small s] [Small t] :
    IsEndLike p
        (OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) ↔
      IsEnd p
        (OfSets.ofSets (Player.cases s t)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid")) :=
  ofSets_isEndLike_iff' p s t


-- @@ L558-562 expanded
theorem ofSets_add_ofSets (s₁ t₁ s₂ t₂ : Set G) [Small s₁] [Small t₁] [Small s₂] [Small t₂] :
    OfSets.ofSets (Player.cases s₁ t₁)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") +
        OfSets.ofSets (Player.cases s₂ t₂)
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      OfSets.ofSets
        (Player.cases
          ((· +
                OfSets.ofSets (Player.cases s₂ t₂)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid")) ''
              s₁ ∪
            (OfSets.ofSets (Player.cases s₁ t₁)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid") +
                ·) ''
              s₂)
          ((· +
                OfSets.ofSets (Player.cases s₂ t₂)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid")) ''
              t₁ ∪
            (OfSets.ofSets (Player.cases s₁ t₁)
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid") +
                ·) ''
              t₂))
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  ofSets_add_ofSets'' s₁ t₁ s₂ t₂


-- @@ L564-569 expanded
theorem ofSets_add_ofSets' (st₁ st₂ : Player → Set G) [Small (st₁ .left)] [Small (st₂ .left)]
    [Small (st₁ .right)] [Small (st₂ .right)] :
    OfSets.ofSets st₁
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") +
        OfSets.ofSets st₂
          (by
            first
            | done
            | trivial
            | assumption
            | aesop
            |
              fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                where `h` is a proof that sets are valid") =
      OfSets.ofSets
        (fun p ↦
          (· +
                OfSets.ofSets st₂
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid")) ''
              st₁ p ∪
            (OfSets.ofSets st₁
                  (by
                    first
                    | done
                    | trivial
                    | assumption
                    | aesop
                    |
                      fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                        where `h` is a proof that sets are valid") +
                ·) ''
              st₂ p)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  by
  rw [ofSets_eq_ofSets_cases, ofSets_eq_ofSets_cases st₂, ofSets_eq_ofSets_cases (fun _ ↦ _ ∪ _),
    ofSets_add_ofSets]


-- @@ L571-579 expanded
theorem natCast_add_one_ofSets {n : ℕ} :
    ((n + 1 : ℕ) : G) =
      OfSets.ofSets (Player.cases {(n : G)} ∅)
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") :=
  by
  induction n with
  | zero => simp [one_def]
  | succ k ih =>
    rw [Nat.cast_add, ih, Nat.cast_one, one_def, ofSets_add_ofSets]
    simp only [Set.image_singleton, add_zero, Set.union_singleton, Set.image_empty, Set.union_self,
      ofSets_inj', Player.cases_inj, and_true]
    rw [← one_def, ← Nat.cast_one, ← Nat.cast_add, ih]
    simp only [Set.mem_singleton_iff, Set.insert_eq_of_mem]


-- @@ L581-594 verbatim
@[simp]
theorem natCast_isEndLike_iff {p : Player} {n : ℕ}
    : IsEndLike p (n : G) ↔ IsEnd p (n : G) := by
  match n with
  | 0 =>
    rw [Nat.cast_zero]
    nth_rw 1 [zero_def]
    simp only [isEnd_zero, iff_true]
    refine isEndLike_of_isEnd ?_
    rw [<-zero_def]
    exact isEnd_zero
  | m + 1 =>
    rw [natCast_add_one_ofSets]
    simp


-- @@ L596-599 verbatim
@[simp]
theorem one_isEndLike_right : IsEndLike .right (1 : G) := by
  rw [<-Nat.cast_one, natCast_isEndLike_iff, Nat.cast_one]
  exact one_isEnd_right


-- @@ L601-604 verbatim
@[simp]
theorem not_isEndLike_left_one : ¬IsEndLike .left (1 : G) := by
  rw [<-Nat.cast_one, natCast_isEndLike_iff, Nat.cast_one, one_def, isEnd_def]
  simp only [moves_ofSets, Player.cases, Set.singleton_ne_empty, not_false_eq_true]


-- @@ L606-619 verbatim
theorem natCast_ext {k m : ℕ}
    (h_moves : ∀ p, ∀ gp, gp ∈ moves p (k : G) ↔ gp ∈ moves p (m : G)) : (k : G) = (m : G) := by
  match k with
  | 0 =>
    match m with
    | 0 => rfl
    | y + 1 =>
      simp [natCast_add_one_ofSets, zero_def] at h_moves
  | x + 1 =>
    match m with
    | 0 => simp [natCast_add_one_ofSets, zero_def] at h_moves
    | y + 1 =>
      simp [natCast_add_one_ofSets] at h_moves
      simpa [natCast_add_one_ofSets]


-- @@ L621-627 verbatim
@[simp]
theorem isEnd_left_natCast_iff {n : ℕ} : IsEnd .left (n : G) ↔ n = 0 := by
  apply Iff.intro <;> intro h1
  · rw [<-Form.natCast_eq_zero_iff (G := G), <-Nat.cast_zero]
    apply natCast_ext
    simp_all
  · simp [h1, isEnd_def]


-- @@ L629-637 verbatim
@[simp]
theorem isEnd_left_intCast_iff {n : ℤ} : IsEnd Player.left (n : G) ↔ n ≤ 0 := by
  constructor <;> intro h1
  · match n with
    | .ofNat n => simpa using h1
    | .negSucc n => exact Int.negSucc_le_zero n
  · match n with
    | .ofNat n => simpa using h1
    | .negSucc n => simp [Form.intCast_negSucc, one_def, isEnd_def]


-- @@ L639-642 verbatim
@[simp]
theorem isEnd_right_intCast_iff {n : ℤ} : IsEnd Player.right (n : G) ↔ 0 ≤ n := by
  rw [<-Player.neg_left, <-IsEnd.neg_iff_neg, <-Form.intCast_neg, isEnd_left_intCast_iff]
  exact Int.neg_le_zero_iff


-- @@ L644-647 verbatim
@[simp]
theorem isEnd_right_natCast {n : ℕ} : IsEnd Player.right (n : G) := by
  rw [<-Form.intCast_nat, isEnd_right_intCast_iff]
  exact Int.natCast_nonneg n


-- @@ L649-651 verbatim
theorem isEnd_of_not_mem {p : Player} {g : G} (h1 : ∀ (gr : G), gr ∉ moves p g) : IsEnd p g := by
  rw [isEnd_def]
  exact Set.eq_empty_of_subset_empty h1


-- @@ L653-672 verbatim
protected theorem natCast_injective : Function.Injective (@Nat.cast G _) := by
  intro a b h1
  induction a generalizing b with
  | zero =>
    norm_cast at h1
    exact (Form.natCast_eq_zero_iff.mp h1.symm).symm
  | succ k ih =>
    match b with
    | 0 =>
      norm_cast at h1
      exact Form.natCast_eq_zero_iff.mp h1
    | m + 1 =>
      simp only [Nat.cast_succ] at h1
      apply congr_arg Nat.succ
      apply ih
      apply natCast_ext
      intro p gp
      apply Iff.intro <;> intro h2
      · rwa [<-mem_moves_add_one_iff_mem_moves, <-h1, mem_moves_add_one_iff_mem_moves]
      · rwa [<-mem_moves_add_one_iff_mem_moves, h1, mem_moves_add_one_iff_mem_moves]


-- @@ L674-675 verbatim
instance : CharZero G where
  cast_injective := Form.natCast_injective


-- @@ L677-683 verbatim
theorem eq_sub_one_of_mem_leftMoves_intCast {n : ℤ} {x : G} (hx : x ∈ moves .left (n : G)) :
    x = (n - 1 : ℤ) := by
  obtain ⟨n, rfl | rfl⟩ := n.eq_nat_or_neg
  · cases n
    · simp [moves_zero] at hx
    · simp_all
  · simp_all


-- @@ L685-694 verbatim
theorem eq_add_one_of_mem_rightMoves_intCast {n : ℤ} {x : G} (hx : x ∈ moves .right (n : G)) :
    x = (n + 1 : ℤ) := by
  have : -x ∈ moves .left ((-n : ℤ) : G) := by simpa [moves_neg]
  rw [← neg_inj]
  calc
    -x = ((-n - 1 : ℤ) : G) := eq_sub_one_of_mem_leftMoves_intCast this
    _ = ((-(n + 1) : ℤ) : G) := by
      congr
      omega
    _ = -((n + 1 : ℤ) : G) := by rw [Form.intCast_neg]


-- @@ L696-703 verbatim
/--
Every Left option of an integer is equal to a smaller integer.
-/
theorem eq_intCast_of_mem_leftMoves_intCast {n : ℤ} {x : G} (hx : x ∈ moves .left (n : G)) :
    ∃ m : ℤ, m < n ∧ m = x := by
  use n - 1
  simp [eq_sub_one_of_mem_leftMoves_intCast hx]
  omega -- really?


-- @@ L705-709 verbatim
theorem eq_intCast_of_mem_rightMoves_intCast {n : ℤ} {x : G} (hx : x ∈ moves .right (n : G)) :
    ∃ m : ℤ, n < m ∧ m = x := by
  use n + 1
  simp [eq_add_one_of_mem_rightMoves_intCast hx]
  omega


-- @@ L711-712 verbatim
theorem succ_nat_end_right {p : Player} {n : ℕ} : IsEnd p (n.succ : G) ↔ p = .right := by
  cases p <;> simp [isEnd_def]


-- @@ L714-722 verbatim
/--
If `P` holds at `n`, then `P` holds at every option of `n+1` (since `n` is the
only such option).
-/
theorem nat_forall_moves {n : ℕ} {P : G → Prop} (h1 : P n)
    : ∀ (p : Player), ∀ gp ∈ moves p (n.succ : G), P gp := by
  intro p; cases p
  · simp_all
  · simp_all


-- @@ L724-726 verbatim
@[simp]
theorem add_eq_zero_iff {x y : G} : x + y = 0 ↔ x = 0 ∧ y = 0 := by
  exact add_eq_zero_iff' x y


-- @@ L728-730 verbatim
instance : SubtractionCommMonoid G where
  neg_add_rev x y := by rw [neg_add', add_comm]
  neg_eq_of_add x y h1 := by simp_all only [add_eq_zero_iff, neg_zero]


-- @@ L732-735 verbatim
@[simp]
theorem IsEnd.sub_iff {g h : G} {p : Player} :
    IsEnd p (g - h) ↔ (IsEnd p g ∧ IsEnd (-p) h) := by
  rw [sub_eq_add_neg, IsEnd.add_iff, IsEnd.neg_iff_neg]


-- @@ L737-741 verbatim
theorem mem_leftMoves_natSub_add_isEnd {a b : ℕ} {y g' : G}
    (hye : IsEnd .left y) :
    g' ∈ moves .left (((a : G) - (b : G)) + y) ↔
    ∃ a', a = a' + 1 ∧ g' = ((a' : G) - (b : G)) + y := by
  cases a <;> simp_all +decide [ sub_eq_add_neg, moves_add, moves_neg ]


-- @@ L743-756 verbatim
theorem mem_rightMoves_natSub_add {a b : ℕ} {y g' : G} :
    g' ∈ moves .right (((a : G) - (b : G)) + y) ↔
    (∃ b', b = b' + 1 ∧ g' = ((a : G) - (b' : G)) + y) ∨
    (∃ yr ∈ moves .right y, g' = ((a : G) - (b : G)) + yr) := by
  constructor <;>
    simp only [sub_eq_add_neg, moves_add, rightMoves_natCast, Set.image_empty, moves_neg,
      Player.neg_right, Set.empty_union, Set.mem_union, Set.mem_image, Set.mem_neg,
      Set.exists_neg_mem, exists_exists_and_eq_and]
  · rintro (⟨x, hx, rfl⟩ | ⟨x, hx, rfl⟩)
    · cases b <;> simp_all [leftMoves_natCast_succ]
    · exact Or.inr ⟨x, hx, rfl⟩
  · rintro (⟨b', rfl, rfl⟩ | ⟨yr, hyr, rfl⟩)
    · simp
    · exact Or.inr ⟨yr, hyr, rfl⟩


-- @@ L758-758 verbatim
end Form


-- @@ L760-760 verbatim
end


-- @@ L762-762 verbatim
end MisereGames
