/-
Copyright (c) 2026 Matevz Miščič, Maša Žaucer, Job Petrovčič. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matevz Miščič, Maša Žaucer, Job Petrovčič
-/
module

public import Mathlib.RingTheory.TwoSidedIdeal.Operations
public import Mathlib.RingTheory.Ideal.Span
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.NormNum.Abs
import Mathlib.Tactic.NormNum.DivMod
import Mathlib.Tactic.NormNum.OfScientific


-- @@ L16-22 verbatim
/-!
# Products of ideals and the auxiliary set `bothMul`

Sets up `bothMul a b = aRb`, the algebra `IdealProd.ringSubsetProdIdeal`, and
the monoid structure on `TwoSidedIdeal R` used throughout the
Artin–Wedderburn development.
-/


-- @@ L24-24 verbatim
@[expose] public section


-- @@ L26-28 verbatim
namespace LeanPool.ArtinWedderburn

-- bothMul a b is the set aRb

-- @@ L29-30 verbatim
/-- The set `aRb = {a * r * b | r : R}` of two-sided products through `R`. -/
def bothMul {R : Type*} [Ring R] (a b : R) : Set R := {x | ∃ r : R, x = a * r * b}


-- @@ L32-33 verbatim
/-- Notation `(a ⬝ R ⬝ b)` for `bothMul R a b`. -/
notation:55 "(" a:55 "⬝" R:55 "⬝" b:55 ")" => bothMul R a b


-- @@ L35-35 verbatim
variable {R : Type*} [Ring R]


-- @@ L37-37 verbatim
variable (I J : Ideal R)


-- @@ L39-39 verbatim
variable (A B C : Set R)


-- @@ L41-41 verbatim
open Pointwise Set


-- @@ L43-45 verbatim
namespace IdealProd

-- the ideal generated by the set of all pairwise products of elements of A and B

-- @@ L46-49 verbatim
/-- The (left) ideal generated by all pairwise products `a * b` with `a ∈ A`, `b ∈ B`. -/
abbrev ringSubsetProdIdeal : Ideal R := Ideal.span (A * B)

-- there is a multiplicative structure on the set of ideals of a ring

-- @@ L50-50 verbatim
instance instMulIdealLeanPool : Mul (Ideal R) := {mul := fun I J => Ideal.span (↑I * ↑J)}


-- @@ L52-52 verbatim
end IdealProd


-- @@ L54-54 verbatim
namespace TwoSidedIdealProd


-- @@ L56-57 verbatim
/-- The two-sided ideal generated by all pairwise products `a * b` with `a ∈ A`, `b ∈ B`. -/
abbrev ringSubsetProdTwoSidedIdeal : TwoSidedIdeal R := TwoSidedIdeal.span (A * B)


-- @@ L59-62 verbatim
instance instMulTwoSidedIdealLeanPool : Mul (TwoSidedIdeal R) :=
  {mul := fun I J => ringSubsetProdTwoSidedIdeal ↑I ↑J}

-- RI = I

-- @@ L63-75 verbatim
theorem univ_mul_ideal_eq_ideal (I : TwoSidedIdeal R) : (univ : Set R) * I = I := by
  apply Set.ext_iff.mpr
  intro x
  constructor
  · rintro ⟨y, _yu, a, ha, rfl⟩
    refine SetLike.mem_coe.mpr ?_
    exact TwoSidedIdeal.mul_mem_left I y a ha
  · intro hx
    refine ⟨1, ?_, x, hx, ?_⟩
    · trivial
    · exact one_mul x

-- IR = I

-- @@ L76-86 verbatim
theorem mul_univ_ideal_eq_ideal (I : TwoSidedIdeal R) : I * (univ : Set R) = I := by
  apply Set.ext_iff.mpr
  intro x
  constructor
  · rintro ⟨y, yu, a, _ha, rfl⟩
    refine SetLike.mem_coe.mpr ?_
    exact TwoSidedIdeal.mul_mem_right I y a yu
  · intro hx
    refine ⟨x, hx, 1, ?_, ?_⟩
    · trivial
    · exact mul_one x


-- @@ L88-90 verbatim
@[simp]
theorem mul_two_sided_ideal_eq_span (I J : TwoSidedIdeal R) :
    I * J = ringSubsetProdTwoSidedIdeal ↑I ↑J := rfl


-- @@ L92-102 verbatim
theorem ideal_get_pair_wise_prod (I J : TwoSidedIdeal R) :
    (TwoSidedIdeal.setLike.coe (I * J)) = AddSubgroup.closure { i * j | (i ∈ I) (j ∈ J)} := by
  ext x
  change x ∈ TwoSidedIdeal.span ((I : Set R) * (J : Set R)) ↔
      x ∈ AddSubgroup.closure {x | ∃ i ∈ I, ∃ j ∈ J, i * j = x}
  rw [TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure]
  nth_rewrite 1 [Eq.symm (mul_assoc _ _ _)]
  rw [univ_mul_ideal_eq_ideal]
  nth_rewrite 1 [← Eq.symm (mul_assoc _ _ _)]
  rw [mul_univ_ideal_eq_ideal]
  exact Eq.to_iff rfl


-- @@ L104-107 verbatim
theorem ideal_eq_set_eq (I J : TwoSidedIdeal R) (h : (↑I : Set R) = ↑J) : I = J := by
  simp_all

-- ideal generated by I is I

-- @@ L108-115 verbatim
theorem ideal_eq_span (I : TwoSidedIdeal R) : I = TwoSidedIdeal.span I := by
  apply le_antisymm
  · exact @TwoSidedIdeal.subset_span R _ ↑I
  · intro x hx
    apply (@TwoSidedIdeal.mem_span_iff R _ I x).1 hx I
    trivial

-- IJ is a subset of I

-- @@ L116-122 verbatim
theorem prod_le_ideal (I J : TwoSidedIdeal R) : I * J ≤ I := by
  nth_rewrite 2 [ideal_eq_span I]
  apply TwoSidedIdeal.span_mono
  apply TwoSidedIdeal.subset_mul_set
  trivial

-- IJ is a subset of J

-- @@ L123-129 verbatim
theorem prod_le_ideal' (I J : TwoSidedIdeal R) : I * J ≤ J := by
  nth_rewrite 2 [ideal_eq_span J]
  apply TwoSidedIdeal.span_mono
  apply TwoSidedIdeal.set_mul_subset
  trivial

-- IR = I

-- @@ L130-141 verbatim
theorem mul_top (I : TwoSidedIdeal R) : I * ⊤ = I := by
  apply le_antisymm
  · apply prod_le_ideal
  · nth_rewrite 1 [ideal_eq_span I]
    apply TwoSidedIdeal.span_mono
    intro x hx
    refine mem_mul.mpr ?_
    refine ⟨x, hx, 1, ?_, ?_⟩
    · exact Set.mem_univ _
    · exact mul_one x

-- RI = I

-- @@ L142-153 verbatim
theorem top_mul (I : TwoSidedIdeal R) : ⊤ * I = I := by
  apply le_antisymm
  · apply prod_le_ideal'
  · nth_rewrite 1 [ideal_eq_span I]
    apply TwoSidedIdeal.span_mono
    intro x hx
    refine mem_mul.mpr ?_
    refine ⟨1, Set.mem_univ _, x, hx, ?_⟩
    exact one_mul x

-- the product of two ideals is an additive subgroup generated by the the pairwise products
-- of elements of the ideals

-- @@ L154-172 verbatim
theorem ideal_prod_subgroup_pair_products (I J : TwoSidedIdeal R) :
    (((I * J) : TwoSidedIdeal R) : Set R) =
      AddSubgroup.closure ((I : Set R) * (J : Set R)) := by
  ext x
  apply TwoSidedIdeal.mem_span_iff_mem_addSubgroup_closure_absorbing
  · rintro y z ⟨i, hi, j, hj, k⟩
    simp only at k
    rw [← k, ← mul_assoc]
    refine mul_mem_mul ?_ hj
    simp only [SetLike.mem_coe]
    exact TwoSidedIdeal.mul_mem_left I y i hi
  · intro y z ⟨i, hi, j, hj, k⟩
    simp only at k
    rw [← k, mul_assoc]
    refine mul_mem_mul hi ?_
    simp only [SetLike.mem_coe]
    exact TwoSidedIdeal.mul_mem_right J j z hj

-- cl(cl(A*B)*C) = cl(A*B*C)

-- @@ L173-202 verbatim
theorem subgroup_product_eq (A B C : AddSubgroup R) :
    AddSubgroup.closure
        ((((AddSubgroup.closure ((A : Set R) * (B : Set R)))) : Set R) * (C : Set R)) =
      AddSubgroup.closure ((A : Set R) * (B : Set R) * (C : Set R)) := by
  apply le_antisymm
  · rw [AddSubgroup.closure_le]
    rintro x ⟨y, hy, c, hc, h⟩
    simp only at h
    rw [← h]
    clear h
    induction hy using AddSubgroup.closure_induction with
    | mem z hz =>
      obtain ⟨a, ha, b, hb, hz⟩ := hz
      simp only at hz
      rw [← hz]
      have habc : a * b * c ∈ (A : Set R) * (B : Set R) * (C : Set R) :=
        ⟨a * b, ⟨a, ⟨ha, ⟨b, ⟨hb, rfl⟩⟩⟩⟩, c, hc, rfl⟩
      exact AddSubgroup.subset_closure habc
    | zero => simp only [zero_mul, SetLike.mem_coe]; apply AddSubgroup.zero_mem _
    | add t u ht hu hh k =>
      rw [right_distrib]
      apply AddSubgroup.add_mem
      · exact hh
      · exact k
    | neg t ht hh => rw [neg_mul]; apply AddSubgroup.neg_mem; exact hh
  · apply AddSubgroup.closure_mono
    apply mul_subset_mul_right
    exact AddSubgroup.subset_closure

-- cl(A*cl(B*C)) = cl(A*B*C)

-- @@ L203-232 verbatim
theorem product_subgroup_eq (A B C : AddSubgroup R) :
    AddSubgroup.closure ((A : Set R) *
        (AddSubgroup.closure ((B : Set R) * (C : Set R)) : Set R)) =
      AddSubgroup.closure ((A : Set R) * (B : Set R) * (C : Set R)) := by
  apply le_antisymm
  · rw [AddSubgroup.closure_le]
    rintro x ⟨a, ha, y, hy, h⟩
    simp only at h
    rw [← h]
    clear h
    induction hy using AddSubgroup.closure_induction with
    | mem z hz =>
      obtain ⟨b, hb, c, hc, hz⟩ := hz
      simp only at hz
      rw [← hz]
      have habc : a * b * c ∈ (A : Set R) * (B : Set R) * (C : Set R) :=
        ⟨a * b, ⟨a, ⟨ha, ⟨b, ⟨hb, rfl⟩⟩⟩⟩, c, hc, rfl⟩
      rw [← mul_assoc]
      exact AddSubgroup.subset_closure habc
    | zero => simp only [mul_zero, SetLike.mem_coe]; apply AddSubgroup.zero_mem _
    | add t u ht hu hh k =>
      rw [left_distrib]
      apply AddSubgroup.add_mem
      · exact hh
      · exact k
    | neg t ht hh => simp only [mul_neg, SetLike.mem_coe, neg_mem_iff]; exact hh
  · apply AddSubgroup.closure_mono
    rw [mul_assoc]
    apply mul_subset_mul_left
    exact AddSubgroup.subset_closure


-- @@ L234-240 verbatim
/-- Forget the multiplicative structure of a two-sided ideal, viewing it as an
additive subgroup. -/
def twoSidedIdealToSubgroup (I : TwoSidedIdeal R) : AddSubgroup R :=
  { carrier := I,
    zero_mem' := I.zero_mem,
    add_mem' := I.add_mem,
    neg_mem' := I.neg_mem }


-- @@ L242-245 verbatim
theorem subgroup_of_ideal_carrier_eq_carrier (I : TwoSidedIdeal R) :
    ((twoSidedIdealToSubgroup I) : Set R) = I := rfl

-- cl(cl(A*B)*C) = cl(A*B*C)

-- @@ L246-256 verbatim
theorem ideal_product_subgroup_eq (A B C : TwoSidedIdeal R) :
    AddSubgroup.closure
        ((((AddSubgroup.closure ((A : Set R) * (B : Set R)))) : Set R) * (C : Set R)) =
      AddSubgroup.closure ((A : Set R) * (B : Set R) * (C : Set R)) := by
  have k := subgroup_product_eq (twoSidedIdealToSubgroup A)
    (twoSidedIdealToSubgroup B) (twoSidedIdealToSubgroup C)
  rw [subgroup_of_ideal_carrier_eq_carrier, subgroup_of_ideal_carrier_eq_carrier,
    subgroup_of_ideal_carrier_eq_carrier] at k
  exact k

-- cl(A*cl(B*C)) = cl(A*B*C)

-- @@ L257-267 verbatim
theorem product_ideal_subgroup_eq (A B C : TwoSidedIdeal R) :
    AddSubgroup.closure ((A : Set R) *
        (AddSubgroup.closure ((B : Set R) * (C : Set R)) : Set R)) =
      AddSubgroup.closure ((A : Set R) * (B : Set R) * (C : Set R)) := by
  have k := product_subgroup_eq (twoSidedIdealToSubgroup A)
    (twoSidedIdealToSubgroup B) (twoSidedIdealToSubgroup C)
  rw [subgroup_of_ideal_carrier_eq_carrier, subgroup_of_ideal_carrier_eq_carrier,
    subgroup_of_ideal_carrier_eq_carrier] at k
  exact k

-- (IJ)K = I(JK)

-- @@ L268-272 verbatim
theorem ideal_mul_assoc (I J K : TwoSidedIdeal R) : (I * J) * K = I * (J * K) := by
  refine ideal_eq_set_eq (I * J * K) (I * (J * K)) ?h
  rw [ideal_prod_subgroup_pair_products, ideal_prod_subgroup_pair_products,
    ideal_product_subgroup_eq, ← product_ideal_subgroup_eq,
    ← ideal_prod_subgroup_pair_products, ← ideal_prod_subgroup_pair_products]


-- @@ L274-275 verbatim
instance instSemigroupTwoSidedIdealLeanPool : Semigroup (TwoSidedIdeal R) :=
  {mul_assoc := ideal_mul_assoc}


-- @@ L277-281 verbatim
@[simp]
instance MulTwoSidedisMonoid : Monoid (TwoSidedIdeal R) :=
  { one := ⊤,
    one_mul := top_mul
    mul_one := mul_top }


-- @@ L283-283 verbatim
end TwoSidedIdealProd


-- @@ L285-285 verbatim
end LeanPool.ArtinWedderburn
