/-
Copyright (c) 2026 Jue Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jue Xu
-/

module

public import LeanPool.LowWeightPauliDynamics.Pauli.Weight


-- @@ L11-83 verbatim
/-!
# The layer light cone of a Trotter step

This file formalizes the weight part of the light-cone lemma `apd:thm:lightcone`. A layer of
`k_h`-local Pauli rotations with pairwise disjoint supports multiplies the weight of a Pauli
string by at most `k_h` (`layer_weight_le`), so a sequence of `L` such layers multiplies it by at
most `k_h ^ L` (`reachable_weight_le`). One step of the `p`th-order product formula
`apd:eq:suzuki` consists of `ΥΓ` layers, where `Γ` is the number of disjoint-support groups `H_γ`
of the Hamiltonian and `Υ = 2·5^{p/2−1}` is the depth overhead of the formula, and the input of a
step has weight at most `w*` after the preceding truncation. This is the count behind the weight
bound `w* k_h^{ΥΓ}` on the Pauli strings of the discarded component `Õ^{(d)}_{≥w*+1}` of
`apd:eq:step_component`. An explicit 8-qubit brickwork with `k_h = 2` shows that the bound is
attained after two layers, and that in a second-order step a string is reachable whose weight
exceeds `w* k_h^Γ`: the exponent has to count the `ΥΓ` layers of a step and not the `Γ` groups.

## Main definitions

* `PauliString.branch G p`: the Pauli strings that can appear when `p` is conjugated by a rotation
  generated by `G`, namely `p` and, when `G` and `p` anticommute, the partner `i G p`.
* `PauliString.oneLayer L p`, `PauliString.reachable Ls p`: the same for a layer `L` of generators
  and for a list `Ls` of layers.
* `PauliString.IsLayer kh L`: the generators in `L` have pairwise disjoint supports and weight at
  most `kh`. This is also the layer hypothesis of `Pauli/LayerFlow.lean` and the files built on it.
* `PauliString.hitting L S`, `PauliString.cover L S`: the generators of `L` whose support meets a
  set `S` of qubits, and the one-layer light cone of `S`.
* `LayerWitness.L₁`, `LayerWitness.L₂`: the two layers of an 8-qubit brickwork with `k_h = 2`;
  `LayerWitness.P₄`, `LayerWitness.P₆`: Hermitian Pauli strings of weight `4` and `6`.

## Main results

* `PauliString.sympForm_eq_zero_of_disjoint_support`: Pauli strings with disjoint supports
  commute.
* `PauliString.support_subset_cover`, `PauliString.card_cover_le`: everything one layer reaches
  from `p` is supported in `cover L (support p)`, and `(cover L S).card ≤ kh * S.card`.
* `PauliString.layer_weight_le`: `q ∈ oneLayer L p → weight q ≤ kh * weight p`.
* `PauliString.reachable_weight_le`:
  `q ∈ reachable Ls p → weight q ≤ kh ^ Ls.length * weight p`.
* `LayerWitness.gamma_layers_weight_le`, `LayerWitness.gamma_layers_weight_four`: from the
  weight-one input `Z₃`, the largest weight reachable in the two layers `[L₁, L₂]` is exactly
  `4 = w* k_h^2`, so the bound of `reachable_weight_le` is attained there.
* `LayerWitness.gamma_weight_bound_false`, `LayerWitness.gamma_weight_bound_false_unmerged`: in the
  layer sequence of a second-order step, `[L₁, L₂, L₁]` or `[L₁, L₂, L₂, L₁]` with `Γ = 2`, the
  string `P₆` of weight `6 > 4 = w* k_h^Γ` is reachable. `Pauli/LayerCounterexample.lean` upgrades
  this from reachability to a nonzero coefficient of the discarded operator, which shows that the
  exponent `ΥΓ` cannot be replaced by `Γ`.

## Layers and reachable sets

A **layer** is a list of Pauli generators with pairwise disjoint supports, each of weight at most
`k_h` (`IsLayer`), as in the hypothesis of `apd:thm:lightcone`. A `k_h`-local Pauli rotation
generated by `G`, acting on a Pauli string `p`, either leaves it alone or splits it in two,
according to whether `G` and `p` commute (`commute_or_anticommute` in `Pauli/Basic.lean`);
`branch` is that two-way split, `oneLayer` composes it across a layer, and `reachable` across a
list of layers.

`reachable` is defined combinatorially: it records which strings can appear under the branching
rule `apd:eq:pauli_rotation_branch` and ignores the rotation angles. It therefore
over-approximates the support of the conjugated operator and is not a certificate that any
coefficient is nonzero. A containing set is exactly what an upper bound on the weight needs. In
the other direction, a heavy element of `reachable` does not by itself show that the conjugated
operator has a heavy Pauli component, because particular angles or cancellations between
branches can make a coefficient vanish. `Pauli/LayerCounterexample.lean` supplies that step for
the second-order word: it computes the coefficient of `P₆` in closed form, shows that it is
nonzero at every small angle, and shows that it survives in the discarded operator.

## Why the per-layer factor is `k_h`

`layer_weight_le` and its iterate `reachable_weight_le` are stated for a general layer. The proof
is a light-cone count: at most `|p|` generators of the layer can branch, because a generator that
anticommutes with `p` must overlap its support (`sympForm_eq_zero_of_disjoint_support`) and the
layer's supports are disjoint; each contributes at most `k_h` sites, and each of them consumes at
least one site of `p`. That is where the sharp factor `k_h` comes from rather than `k_h + 1`.
-/


-- @@ L85-85 verbatim
@[expose] public section


-- @@ L87-87 verbatim
namespace Lean4LPD


-- @@ L89-89 verbatim
namespace PauliString


-- @@ L91-91 verbatim
variable {n kh : ℕ} {G H p q : PauliString n} {L : List (PauliString n)} {S T : Finset (Fin n)}


-- @@ L93-96 verbatim
/-! ### Support arithmetic

Small facts about `support` that `Pauli/Weight.lean` does not need but the light-cone count
does. -/


-- @@ L98-107 verbatim
/-- The support of a product is contained in the union of the supports. -/
theorem support_mul_subset (s t : PauliString n) :
    support (s * t) ⊆ support s ∪ support t := by
  intro i hi
  rw [mem_support, site_mul] at hi
  rw [Finset.mem_union, mem_support, mem_support]
  by_contra hc
  have h1 : site s i = 0 := by by_contra h; exact hc (Or.inl h)
  have h2 : site t i = 0 := by by_contra h; exact hc (Or.inr h)
  exact hi (by rw [h1, h2, add_zero])


-- @@ L109-111 verbatim
/-- The support does not see the phase — the `Finset` refinement of `weight_phaseMul`. -/
@[simp] theorem support_phaseMul (k : ZMod 4) (s : PauliString n) :
    support (phaseMul k s) = support s := rfl


-- @@ L113-118 verbatim
/-- A locally anticommuting site lies in both supports. -/
theorem antiSites_subset_inter (G s : PauliString n) :
    antiSites G s ⊆ support G ∩ support s := by
  intro i hi
  rw [mem_antiSites] at hi
  exact Finset.mem_inter.2 ⟨mem_support.2 hi.1, mem_support.2 hi.2.1⟩


-- @@ L120-131 verbatim
/-- **Pauli strings with disjoint supports commute.** This is what makes a layer a layer: the
generators of one disjoint-support layer of `apd:thm:lightcone` commute with each other, so the
layer is a product of commuting Pauli rotations. -/
theorem sympForm_eq_zero_of_disjoint_support (h : Disjoint (support G) (support p)) :
    sympForm G p = 0 := by
  have hempty : antiSites G p = ∅ := by
    rw [Finset.eq_empty_iff_forall_notMem]
    intro i hi
    have := antiSites_subset_inter G p hi
    rw [Finset.mem_inter] at this
    exact (Finset.disjoint_left.1 h this.1) this.2
  rw [sympForm_eq_card_antiSites, hempty, Finset.card_empty, Nat.cast_zero]


-- @@ L133-138 verbatim
/-- Contrapositive of the previous theorem, in the form the light-cone count consumes: a generator
that anticommutes with `p` must touch `p`. -/
theorem inter_support_nonempty_of_sympForm (h : sympForm G p = 1) :
    (support G ∩ support p).Nonempty := by
  obtain ⟨i, hi⟩ := Finset.card_pos.1 (one_le_card_antiSites h)
  exact ⟨i, antiSites_subset_inter G p hi⟩


-- @@ L140-143 verbatim
/-! ### The branching process

One Pauli rotation, one layer, a list of layers. Every set here is a `Finset`, so the witness at
the end of the file is a finite computation. -/


-- @@ L145-155 verbatim
/-- **The two branches of one `k_h`-local Pauli rotation.** Conjugating `p` by the rotation
generated by `G`, with conjugation angle `θ`, leaves `p` alone when `G` and `p` commute and
produces `cos θ · p + sin θ · (i G p)` when they anticommute (`apd:eq:pauli_rotation_branch`,
formalized as `pauli_rotation_branch`), so the Pauli strings that can appear are `p` and, in the
anticommuting case, the partner `i G p`.

This is a statement about *which strings can appear*, not about their coefficients: `branch`
ignores the angle, so it over-approximates the support of the conjugated operator at any particular
`θ`. That is the right side to err on for an upper bound on the weight. -/
def branch (G p : PauliString n) : Finset (PauliString n) :=
  if sympForm G p = 1 then {p, phaseMul 1 (G * p)} else {p}


-- @@ L157-158 verbatim
@[simp] theorem self_mem_branch (G p : PauliString n) : p ∈ branch G p := by
  unfold branch; split <;> simp


-- @@ L160-162 verbatim
/-- The anticommuting branch: the partner `i G p` is reachable. -/
theorem partner_mem_branch (h : sympForm G p = 1) : phaseMul 1 (G * p) ∈ branch G p := by
  simp [branch, h]


-- @@ L164-175 verbatim
theorem support_subset_of_mem_branch (hq : q ∈ branch G p) :
    support q ⊆ support p ∪ support G := by
  rw [branch] at hq
  split at hq
  · simp only [Finset.mem_insert, Finset.mem_singleton] at hq
    rcases hq with rfl | rfl
    · exact Finset.subset_union_left
    · rw [support_phaseMul]
      exact (support_mul_subset G p).trans (by rw [Finset.union_comm])
  · rw [Finset.mem_singleton] at hq
    subst hq
    exact Finset.subset_union_left


-- @@ L177-182 verbatim
/-- **One layer**, applied generator by generator. The generators of a layer have disjoint
supports and so commute, which is why the order in the list is immaterial to the result and why
`branch`'s test can be read off the string entering the layer. -/
def oneLayer : (L : List (PauliString n)) → (p : PauliString n) → Finset (PauliString n)
  | [], p => {p}
  | G :: Gs, p => (branch G p).biUnion (oneLayer Gs)


-- @@ L184-184 verbatim
@[simp] theorem oneLayer_nil (p : PauliString n) : oneLayer [] p = {p} := rfl


-- @@ L186-188 verbatim
@[simp] theorem oneLayer_cons (G : PauliString n) (Gs : List (PauliString n))
    (p : PauliString n) :
    oneLayer (G :: Gs) p = (branch G p).biUnion (oneLayer Gs) := rfl


-- @@ L190-195 verbatim
/-- **A sequence of layers**, applied one after another, the head of the list first. One Trotter
step of the `p`th-order product formula `apd:eq:suzuki` is a sequence of `ΥΓ` layers. -/
def reachable : (layers : List (List (PauliString n))) → (p : PauliString n) →
    Finset (PauliString n)
  | [], p => {p}
  | L :: Ls, p => (oneLayer L p).biUnion (reachable Ls)


-- @@ L197-197 verbatim
@[simp] theorem reachable_nil (p : PauliString n) : reachable [] p = {p} := rfl


-- @@ L199-201 verbatim
@[simp] theorem reachable_cons (L : List (PauliString n)) (Ls : List (List (PauliString n)))
    (p : PauliString n) :
    reachable (L :: Ls) p = (oneLayer L p).biUnion (reachable Ls) := rfl


-- @@ L203-209 verbatim
/-- **A layer of `k_h`-local rotations with disjoint supports**: the hypothesis that
`apd:thm:lightcone` places on each layer of a Trotter step. -/
structure IsLayer (kh : ℕ) (L : List (PauliString n)) : Prop where
  /-- Distinct generators of the layer act on disjoint sets of qubits. -/
  disjoint : L.Pairwise fun G H => Disjoint (support G) (support H)
  /-- Every generator is `k_h`-local. -/
  weight_le : ∀ G ∈ L, weight G ≤ kh


-- @@ L211-226 verbatim
private theorem pairwise_disjoint_of_mem : ∀ {M : List (PauliString n)},
    (M.Pairwise fun G H => Disjoint (support G) (support H)) →
    ∀ {G H : PauliString n}, G ∈ M → H ∈ M → G ≠ H → Disjoint (support G) (support H) := by
  intro M
  induction M with
  | nil => intro _ _ _ hG _ _; exact absurd hG (by simp)
  | cons a t ih =>
    intro hpw G H hG hH hne
    rw [List.pairwise_cons] at hpw
    rcases List.mem_cons.1 hG with rfl | hG'
    · rcases List.mem_cons.1 hH with rfl | hH'
      · exact absurd rfl hne
      · exact hpw.1 _ hH'
    · rcases List.mem_cons.1 hH with rfl | hH'
      · exact (hpw.1 _ hG').symm
      · exact ih hpw.2 hG' hH' hne


-- @@ L228-232 verbatim
/-- Disjointness in the pointwise form the count needs. Stated separately because `List.Pairwise`
orders its pairs and `Disjoint` does not care. -/
theorem IsLayer.disjoint_of_mem (hL : IsLayer kh L) (hG : G ∈ L) (hH : H ∈ L) (hne : G ≠ H) :
    Disjoint (support G) (support H) :=
  pairwise_disjoint_of_mem hL.disjoint hG hH hne


-- @@ L234-238 verbatim
/-! ### The light cone of one layer

`cover L S` is the set of qubits a string supported in `S` can reach through one layer: `S`
itself, together with the full support of every generator that touches `S`. The two lemmas below
are the two halves of the per-layer weight bound: containment, then the count. -/


-- @@ L240-242 verbatim
/-- The generators of `L` whose support meets `S`. Only these can branch. -/
def hitting (L : List (PauliString n)) (S : Finset (Fin n)) : Finset (PauliString n) :=
  L.toFinset.filter fun G => (support G ∩ S).Nonempty


-- @@ L244-245 verbatim
theorem mem_hitting : G ∈ hitting L S ↔ G ∈ L ∧ (support G ∩ S).Nonempty := by
  simp [hitting, List.mem_toFinset]


-- @@ L247-249 verbatim
/-- **The one-layer light cone** of a set of qubits. -/
def cover (L : List (PauliString n)) (S : Finset (Fin n)) : Finset (Fin n) :=
  S ∪ (hitting L S).biUnion support


-- @@ L251-252 verbatim
@[simp] theorem cover_nil (S : Finset (Fin n)) : cover [] S = S := by
  simp [cover, hitting]


-- @@ L254-255 verbatim
theorem subset_cover (L : List (PauliString n)) (S : Finset (Fin n)) : S ⊆ cover L S :=
  Finset.subset_union_left


-- @@ L257-259 verbatim
theorem support_subset_cover_of_mem_hitting (h : G ∈ hitting L S) :
    support G ⊆ cover L S :=
  (Finset.subset_biUnion_of_mem support h).trans Finset.subset_union_right


-- @@ L261-265 verbatim
theorem hitting_subset_cons (G : PauliString n) (Gs : List (PauliString n))
    (S : Finset (Fin n)) : hitting Gs S ⊆ hitting (G :: Gs) S := by
  intro H hH
  rw [mem_hitting] at hH ⊢
  exact ⟨List.mem_cons_of_mem _ hH.1, hH.2⟩


-- @@ L267-270 verbatim
theorem cover_subset_cons (G : PauliString n) (Gs : List (PauliString n))
    (S : Finset (Fin n)) : cover Gs S ⊆ cover (G :: Gs) S :=
  Finset.union_subset_union_right
    (Finset.biUnion_subset_biUnion_of_subset_left _ (hitting_subset_cons G Gs S))


-- @@ L272-293 verbatim
/-- The step of the containment induction: once the head generator `G` has fired, the strings it
produces are supported in `S ∪ supp G`, and — because the rest of the layer is disjoint from
`G` — the *remaining* generators that can still fire are exactly those that could already fire
from `S`. So the light cone does not compound within a layer. -/
theorem cover_subset_cover_cons {G : PauliString n} {Gs : List (PauliString n)}
    (hG : ∀ H ∈ Gs, Disjoint (support G) (support H))
    (hGS : (support G ∩ S).Nonempty) (hT : T ⊆ S ∪ support G) :
    cover Gs T ⊆ cover (G :: Gs) S := by
  have hGmem : G ∈ hitting (G :: Gs) S :=
    mem_hitting.2 ⟨List.mem_cons_self, hGS⟩
  have hGcover : support G ⊆ cover (G :: Gs) S := support_subset_cover_of_mem_hitting hGmem
  have hhit : hitting Gs T ⊆ hitting (G :: Gs) S := by
    intro H hH
    rw [mem_hitting] at hH ⊢
    obtain ⟨i, hi⟩ := hH.2
    rw [Finset.mem_inter] at hi
    refine ⟨List.mem_cons_of_mem _ hH.1, ⟨i, Finset.mem_inter.2 ⟨hi.1, ?_⟩⟩⟩
    rcases Finset.mem_union.1 (hT hi.2) with hiS | hiG
    · exact hiS
    · exact absurd hi.1 (Finset.disjoint_left.1 (hG H hH.1) hiG)
  refine Finset.union_subset (hT.trans (Finset.union_subset (subset_cover _ _) hGcover)) ?_
  exact (Finset.biUnion_subset_biUnion_of_subset_left _ hhit).trans Finset.subset_union_right


-- @@ L295-327 verbatim
/-- **Containment.** Everything one layer can reach from `p` is supported in the light cone of
`supp p`. -/
theorem support_subset_cover : ∀ {L : List (PauliString n)},
    (L.Pairwise fun G H => Disjoint (support G) (support H)) →
    ∀ {p q : PauliString n}, q ∈ oneLayer L p → support q ⊆ cover L (support p) := by
  intro L
  induction L with
  | nil =>
    intro _ p q hq
    rw [oneLayer_nil, Finset.mem_singleton] at hq
    subst hq
    simp
  | cons G Gs ih =>
    intro hpw p q hq
    rw [List.pairwise_cons] at hpw
    rw [oneLayer_cons, Finset.mem_biUnion] at hq
    obtain ⟨p', hp', hq'⟩ := hq
    have hsub := ih hpw.2 hq'
    have hcase : p' = p ∨ (sympForm G p = 1 ∧ p' = phaseMul 1 (G * p)) := by
      rw [branch] at hp'
      split at hp'
      · simp only [Finset.mem_insert, Finset.mem_singleton] at hp'
        rcases hp' with rfl | rfl
        · exact Or.inl rfl
        · exact Or.inr ⟨by assumption, rfl⟩
      · rw [Finset.mem_singleton] at hp'
        exact Or.inl hp'
    rcases hcase with rfl | ⟨hanti, rfl⟩
    · exact hsub.trans (cover_subset_cons G Gs _)
    · refine hsub.trans (cover_subset_cover_cons hpw.1 ?_ ?_)
      · exact inter_support_nonempty_of_sympForm hanti
      · rw [support_phaseMul]
        exact (support_mul_subset G p).trans (by rw [Finset.union_comm])


-- @@ L329-373 verbatim
/-- **The count.** A layer of `k_h`-local generators with disjoint supports has a light cone at
most `k_h` times as large as the set it starts from.

The factor is `k_h` and not `k_h + 1` because each firing generator *pays* for itself out of `S`:
its support meets `S`, the supports are disjoint, so the firing generators inject into `S ∩ U`,
and the part of `S` no generator touches is carried along unchanged. -/
theorem card_cover_le (hL : IsLayer kh L) (hkh : 1 ≤ kh) (S : Finset (Fin n)) :
    (cover L S).card ≤ kh * S.card := by
  set U := (hitting L S).biUnion support with hUdef
  have hdisj : ∀ x ∈ hitting L S, ∀ y ∈ hitting L S, x ≠ y →
      Disjoint (support x ∩ S) (support y ∩ S) := by
    intro x hx y hy hxy
    exact Finset.disjoint_of_subset_left Finset.inter_subset_left
      (Finset.disjoint_of_subset_right Finset.inter_subset_left
        (hL.disjoint_of_mem (mem_hitting.1 hx).1 (mem_hitting.1 hy).1 hxy))
  -- each firing generator consumes at least one site of `S ∩ U`
  have hcount : (hitting L S).card ≤ (S ∩ U).card := by
    have hcard : ((hitting L S).biUnion fun G => support G ∩ S).card
        = ∑ G ∈ hitting L S, (support G ∩ S).card :=
      Finset.card_biUnion hdisj
    have hsub : ((hitting L S).biUnion fun G => support G ∩ S) ⊆ S ∩ U := by
      intro i hi
      rw [Finset.mem_biUnion] at hi
      obtain ⟨G, hG, hiG⟩ := hi
      rw [Finset.mem_inter] at hiG
      exact Finset.mem_inter.2 ⟨hiG.2, Finset.subset_biUnion_of_mem support hG hiG.1⟩
    calc (hitting L S).card
        = ∑ _G ∈ hitting L S, 1 := by simp
      _ ≤ ∑ G ∈ hitting L S, (support G ∩ S).card :=
          Finset.sum_le_sum fun G hG => Finset.card_pos.2 (mem_hitting.1 hG).2
      _ = ((hitting L S).biUnion fun G => support G ∩ S).card := hcard.symm
      _ ≤ (S ∩ U).card := Finset.card_le_card hsub
  have hUcard : U.card ≤ (hitting L S).card * kh :=
    Finset.card_biUnion_le_card_mul _ _ _ fun G hG => hL.weight_le G (mem_hitting.1 hG).1
  have hsplit : (S \ U).card + (S ∩ U).card = S.card := Finset.card_sdiff_add_card_inter S U
  calc (cover L S).card
      = ((S \ U) ∪ U).card := by rw [cover, ← hUdef, Finset.sdiff_union_self_eq_union]
    _ ≤ (S \ U).card + U.card := Finset.card_union_le _ _
    _ ≤ (S \ U).card + (hitting L S).card * kh := by omega
    _ ≤ (S \ U).card + (S ∩ U).card * kh := by
        exact Nat.add_le_add_left (Nat.mul_le_mul_right kh hcount) _
    _ ≤ (S \ U).card * kh + (S ∩ U).card * kh :=
        Nat.add_le_add_right (Nat.le_mul_of_pos_right _ hkh) _
    _ = ((S \ U).card + (S ∩ U).card) * kh := by ring
    _ = kh * S.card := by rw [hsplit]; ring


-- @@ L375-380 verbatim
/-- **One layer multiplies the Pauli weight by at most `k_h`.** This is the per-layer step in the
proof of `apd:thm:lightcone`, obtained by combining the containment `support_subset_cover` with
the count `card_cover_le`. -/
theorem layer_weight_le (hL : IsLayer kh L) (hkh : 1 ≤ kh) (hq : q ∈ oneLayer L p) :
    weight q ≤ kh * weight p :=
  le_trans (Finset.card_le_card (support_subset_cover hL.disjoint hq)) (card_cover_le hL hkh _)


-- @@ L382-410 verbatim
/-- **The `L`-fold iterate**, `|q| ≤ k_h^L |p|` after `L` layers.

With `|p| ≤ w*` and `L = ΥΓ`, the number of layers of one Trotter step of the `p`th-order formula
`apd:eq:suzuki`, the right-hand side is at most `w* k_h^{ΥΓ}`, the weight bound of
`apd:thm:lightcone` for the Pauli strings of the discarded component `apd:eq:step_component`.
Nothing is assumed about how the layers are related: they may repeat, as they do in a
second-order step. -/
theorem reachable_weight_le : ∀ {Ls : List (List (PauliString n))},
    (∀ L ∈ Ls, IsLayer kh L) → 1 ≤ kh →
    ∀ {p q : PauliString n}, q ∈ reachable Ls p → weight q ≤ kh ^ Ls.length * weight p := by
  intro Ls
  induction Ls with
  | nil =>
    intro _ _ p q hq
    rw [reachable_nil, Finset.mem_singleton] at hq
    subst hq
    simp
  | cons L Ls ih =>
    intro hLs hkh p q hq
    rw [reachable_cons, Finset.mem_biUnion] at hq
    obtain ⟨p', hp', hq'⟩ := hq
    have hstep : weight p' ≤ kh * weight p :=
      layer_weight_le (hLs L List.mem_cons_self) hkh hp'
    have hrest : weight q ≤ kh ^ Ls.length * weight p' :=
      ih (fun M hM => hLs M (List.mem_cons_of_mem _ hM)) hkh hq'
    calc weight q ≤ kh ^ Ls.length * weight p' := hrest
      _ ≤ kh ^ Ls.length * (kh * weight p) := Nat.mul_le_mul_left _ hstep
      _ = kh ^ (L :: Ls).length * weight p := by
          rw [List.length_cons, pow_succ]; ring


-- @@ L412-415 verbatim
/-! ### Single-site Pauli strings

Enough notation to write a concrete brickwork down. Both carry phase `0`, which is the Hermitian
choice for a string with no `Y` site (`isSelfAdjoint_iff_phase`). -/


-- @@ L417-418 verbatim
/-- The single-site `X_i`. -/
def X (i : Fin n) : PauliString n := ⟨fun j => if j = i then 1 else 0, 0, 0⟩


-- @@ L420-421 verbatim
/-- The single-site `Z_i`. -/
def Z (i : Fin n) : PauliString n := ⟨0, fun j => if j = i then 1 else 0, 0⟩


-- @@ L423-423 verbatim
end PauliString


-- @@ L425-427 verbatim
/-! ## The witness

`n = 8`, `k_h = 2`, `w* = 1`, and a brickwork of two-qubit generators. -/


-- @@ L429-429 verbatim
namespace LayerWitness


-- @@ L431-431 verbatim
open PauliString


-- @@ L433-434 verbatim
/-- The **even** brickwork layer: generators on qubit pairs `(0,1)`, `(2,3)`, `(4,5)`, `(6,7)`. -/
def L₁ : List (PauliString 8) := [X 0 * Z 1, X 2 * X 3, Z 4 * X 5, X 6 * X 7]


-- @@ L436-437 verbatim
/-- The **odd** brickwork layer: generators on `(1,2)`, `(3,4)`, `(5,6)`. -/
def L₂ : List (PauliString 8) := [X 1 * Z 2, X 3 * X 4, X 5 * X 6]


-- @@ L439-440 verbatim
/-- Both layers are layers of `2`-local generators with disjoint supports: `k_h = 2`. -/
theorem isLayer_L₁ : IsLayer 2 L₁ := ⟨by decide, by decide⟩


-- @@ L442-442 verbatim
theorem isLayer_L₂ : IsLayer 2 L₂ := ⟨by decide, by decide⟩


-- @@ L444-449 verbatim
/-- Every generator used is a Hermitian Pauli string, so each layer really is a product of Pauli
rotations `e^{-iθG}` with `G† = G` and `G² = 1` (`isSelfAdjoint_iff_mul_self_eq_one`). None of them
has a `Y` site, so phase `0` is the Hermitian representative. -/
theorem isSelfAdjoint_L₁ : ∀ G ∈ L₁, IsSelfAdjoint G := by
  have h : ∀ G ∈ L₁, signPhase (G.z ⬝ᵥ G.x) = 2 * G.phase := by decide
  exact fun G hG => isSelfAdjoint_iff_phase.2 (h G hG)


-- @@ L451-453 verbatim
theorem isSelfAdjoint_L₂ : ∀ G ∈ L₂, IsSelfAdjoint G := by
  have h : ∀ G ∈ L₂, signPhase (G.z ⬝ᵥ G.x) = 2 * G.phase := by decide
  exact fun G hG => isSelfAdjoint_iff_phase.2 (h G hG)


-- @@ L455-457 verbatim
/-- The input is `Z₃`, a single-qubit `Z`, so its weight is `1`. The input of a Trotter step has
weight at most `w*` after the preceding truncation; here that means `w* = 1`. -/
theorem weight_Z_three : weight (Z (3 : Fin 8)) = 1 := by decide


-- @@ L459-460 verbatim
theorem isSelfAdjoint_Z_three : IsSelfAdjoint (Z (3 : Fin 8)) :=
  isSelfAdjoint_iff_phase.2 (by decide)


-- @@ L462-478 verbatim
/-- **After `Γ` layers the weight is at most `w* k_h^Γ`.** With `w* = 1`, `k_h = 2` and the
`Γ = 2` brickwork layers `[L₁, L₂]`, nothing of weight more than `w* k_h^Γ = 4` is reachable from
`Z₃`. By `gamma_layers_weight_four` the value `4` is attained, so the bound `k_h ^ L` has no slack
in its constant: the weight-`6` string of `gamma_weight_bound_false` exceeds `4` only because a
second-order step has more than `Γ` layers.

Nothing about the brickwork is used: this is `reachable_weight_le` at `k_h = 2` and two layers. -/
theorem gamma_layers_weight_le :
    ∀ q ∈ reachable (layers := [L₁, L₂]) (Z 3), q.weight ≤ 4 := by
  intro q hq
  have h := reachable_weight_le (kh := 2)
    (fun L hL => by
      rcases List.mem_cons.1 hL with rfl | hL
      · exact isLayer_L₁
      · rw [List.mem_singleton.1 hL]; exact isLayer_L₂)
    (by norm_num) hq
  simpa [weight_Z_three] using h


-- @@ L480-487 verbatim
/-! ### The two named witnesses

Both are written with the phase `#{Y-sites} mod 4` — the canonical signless representative in
`Pauli/Basic.lean`'s convention, which pins the sign that `isSelfAdjoint_iff_phase` alone leaves
open. Hermiticity itself is checked below, so these are genuine observables, of the kind the
discarded component `Õ^{(d)}_{≥w*+1}` of `apd:eq:step_component` is a combination of, and not
phase-decorated
artefacts of the branching. -/


-- @@ L489-491 verbatim
/-- The weight-`4` witness: site types `X Y Z X` on qubits `1,2,3,4`. Reachable from `Z₃` in the
`Γ = 2` layers `[L₁, L₂]`, where it attains the bound `w* k_h^Γ = 4` exactly. -/
def P₄ : PauliString 8 := ⟨![0, 1, 1, 0, 1, 0, 0, 0], ![0, 0, 1, 1, 0, 0, 0, 0], 1⟩


-- @@ L493-495 verbatim
/-- The weight-`6` witness: site types `X Y Y Z Y X` on qubits `0,…,5`. Reachable from `Z₃` in
`[L₁, L₂, L₁]`; its weight exceeds `w* k_h^Γ = 4`. -/
def P₆ : PauliString 8 := ⟨![1, 1, 1, 0, 1, 1, 0, 0], ![0, 1, 1, 1, 1, 0, 0, 0], 3⟩


-- @@ L497-497 verbatim
theorem isSelfAdjoint_P₄ : IsSelfAdjoint P₄ := isSelfAdjoint_iff_phase.2 (by decide)


-- @@ L499-499 verbatim
theorem isSelfAdjoint_P₆ : IsSelfAdjoint P₆ := isSelfAdjoint_iff_phase.2 (by decide)


-- @@ L501-501 verbatim
theorem support_P₄ : P₄.support = {1, 2, 3, 4} := by decide


-- @@ L503-503 verbatim
theorem support_P₆ : P₆.support = {0, 1, 2, 3, 4, 5} := by decide


-- @@ L505-505 verbatim
theorem weight_P₄ : P₄.weight = 4 := by decide


-- @@ L507-507 verbatim
theorem weight_P₆ : P₆.weight = 6 := by decide


-- @@ L509-509 verbatim
theorem P₄_mem_reachable : P₄ ∈ reachable (layers := [L₁, L₂]) (Z 3) := by decide


-- @@ L511-511 verbatim
theorem P₆_mem_reachable : P₆ ∈ reachable (layers := [L₁, L₂, L₁]) (Z 3) := by decide


-- @@ L513-513 verbatim
theorem P₆_mem_reachable_unmerged : P₆ ∈ reachable (layers := [L₁, L₂, L₂, L₁]) (Z 3) := by decide


-- @@ L515-520 verbatim
/-- …and the bound is attained: `P₄` has weight exactly `4` and is reachable in the two brickwork
layers. Together with `gamma_layers_weight_le`, the maximum reachable weight after `Γ` layers is
exactly `w* k_h^Γ`. -/
theorem gamma_layers_weight_four :
    ∃ q ∈ reachable (layers := [L₁, L₂]) (Z 3), q.weight = 4 :=
  ⟨P₄, P₄_mem_reachable, weight_P₄⟩


-- @@ L522-543 verbatim
/-- **A reachable string of weight `6 > w* k_h^Γ = 4` in a second-order step**: the exponent of
the light-cone bound has to count layers, not the `Γ` groups of the Hamiltonian.

With `n = 8`, `k_h = 2`, the two brickwork layers `L₁`, `L₂` (so `Γ = 2`) and `w* = 1`, the value
of `w* k_h^Γ` is `4`. It is exactly the largest reachable weight after `Γ` layers
(`gamma_layers_weight_le` and `gamma_layers_weight_four`), and it is exceeded after the layer
sequence of the second-order product formula of `apd:eq:suzuki`, where the reachable Pauli `P₆`,
supported on qubits `0,…,5` (`support_P₆`), has weight `6`. This is consistent with
`reachable_weight_le`, which allows weight up to `k_h^3 = 8` for the three layers used here.

The layer sequence used here is `[L₁, L₂, L₁]`, which is the second-order step `L₁ L₂ · L₂ L₁`
after the two adjacent `H_Γ` half-steps are merged: the *shortest* reading of a second-order
step, and already one layer more than `Γ`. `gamma_weight_bound_false_unmerged` repeats it for the
literal `2Γ = 4` layers.

This theorem is purely combinatorial: it contains no angle and no coefficient, and it does not
quantify over the product-formula order `p`. That `P₆` has a nonzero coefficient in the operator
discarded after the second-order step is `LayerCounterexample.actual_discard_exceeds_gamma_bound`
in `Pauli/LayerCounterexample.lean`. -/
theorem gamma_weight_bound_false :
    ∃ q ∈ reachable (layers := [L₁, L₂, L₁]) (Z 3), 4 < q.weight :=
  ⟨P₆, P₆_mem_reachable, by rw [weight_P₆]; norm_num⟩


-- @@ L545-550 verbatim
/-- The same combinatorial witness for the literal `2Γ = 4` layers `[L₁, L₂, L₂, L₁]` of the
second-order product formula (`apd:eq:suzuki`), with no merging of the two adjacent `H_Γ`
half-steps. -/
theorem gamma_weight_bound_false_unmerged :
    ∃ q ∈ reachable (layers := [L₁, L₂, L₂, L₁]) (Z 3), 4 < q.weight :=
  ⟨P₆, P₆_mem_reachable_unmerged, by rw [weight_P₆]; norm_num⟩


-- @@ L552-552 verbatim
end LayerWitness


-- @@ L554-554 verbatim
end Lean4LPD
