/-
Copyright (c) 2026 Kalle Kytölä. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kalle Kytölä
-/
module

public import LeanPool.VirasoroProject.IndexTri
public import LeanPool.VirasoroProject.LieVerma
public import LeanPool.VirasoroProject.VirasoroAlgebra
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.Data.EReal.Operations
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded


-- @@ L17-56 verbatim
/-!
# Verma modules for the Virasoro algebra

This file defines Verma modules used in Lie algebra representation theory.

## Main definitions

* `HasCentralCharge`: A typeclass for Vierasoro modules where the central element acts by
  multiplication by a particular scalar (the scalar is called the *central charge*).
* `virasoroTri`: The triangular decomposition of the Virasoro algebra whose positive (resp.
  negative) part is spanned by `Lₙ` with `n` positive (resp. negative) and the Cartan subalgebra
  is spanned by `L₀` and the central element `C`.
* `VirasoroAlgebra.hw c h`: The (highest) weight of the Virasoro algebra specified by the value `c`
  of the central charge (`C`-eigenvalue) and the value `h` of the conformal weight
  (`L₀`-eigenvalue).
* `VirasoroVerma c h`: The Virasoro Verma module of highest weight `h` and central charge `c`.
* `VirasoroVerma.hwVec`: The highest weight vector of the Virasoro Verma module.
* `VirasoroVerma.universalMap`: The universal property of the Virasoro Verma module:
  Given another module `M` over `𝓤 𝕜 (VirasoroAlgebra 𝕜)` and a "target" vector `hwv ∈ M` satisfying
  `Lₙ • hwv = 0` for all `n > 0`, `L₀ • hwv = h • hwv`, and `C • hwv = c • hwv`,
  one obtains an `A`-module map from the Verma module to `M` uniquely specified by the requirement
  `hwVec c h ↦ hwv`.

## Main statements

* `VirasoroVerma.hwVec_cyclic`: The Virasoro Verma module is generated by its highest weight vector.
* `TriangularDecomposition.VermaHW.cartan_smul_hwVec`: The highest weight vector of a Verma module
  is an eigenvector of the Cartan subalgebra with the eigenvalues specified by the highest weight.
* `VirasoroVerma.lgen_zero_hwVec`: The highest weight vector of a Virasoro Verma module
  has `L₀`-eigenvalue `h`.
* `VirasoroVerma.lgen_pos_hwVec`: The highest weight vector of a Virasoro Verma module
  is annihilated `Lₙ` for `n > 0`.
* `VirasoroVerma.cgen_smul`: The central element `C` acts as scalar `c` in the Virasoro Verma
  module.

## Tags

Virasoro algebra, Verma module

-/


-- @@ L58-58 verbatim
@[expose] public section



-- @@ L61-61 verbatim
namespace VirasoroProject


-- @@ L63-63 verbatim
open Module


-- @@ L65-65 verbatim
section HasCentralCharge


-- @@ L67-67 verbatim
variable (𝕜 : Type*) [Field 𝕜] [CharZero 𝕜]

-- @@ L68-68 verbatim
variable (M : Type*) [AddCommGroup M] [Module 𝕜 M] [Module (𝓤 𝕜 (VirasoroAlgebra 𝕜)) M]


-- @@ L70-71 verbatim
/-- A Virasoro module where the central generator `C` acts by the scalar `c`. -/
abbrev HasCentralCharge (c : 𝕜) := HasCentralValue 𝕜 (VirasoroAlgebra 𝕜) M (.cgen _) c


-- @@ L73-75 verbatim
lemma _root_.VirasoroProject.HasCentralCharge.cgen_smul {c : 𝕜} [HasCentralCharge 𝕜 M c] (v : M) :
    ιUEA 𝕜 (VirasoroAlgebra.cgen 𝕜) • v = c • v :=
  HasCentralValue.central_smul ..


-- @@ L77-77 verbatim
end HasCentralCharge


-- @@ L79-79 verbatim
section VirasoroVerma


-- @@ L81-81 verbatim
variable (𝕜 : Type*) [Field 𝕜] [CharZero 𝕜]


-- @@ L83-89 verbatim
open VirasoroAlgebra in
/-- The triangular decomposition of the Virasoro algebra with upper and lower (essentially
nilpotent) parts spanned by the `Lₙ` with positive and negative `n`, respectively, and the
Cartan subalgebra spanned by `L₀` and the central element `C`. -/
noncomputable def _root_.VirasoroProject.virasoroTri :
    TriangularDecomposition 𝕜 (VirasoroAlgebra 𝕜) :=
  TriangularDecomposition.ofBasis (basisLC 𝕜) indexTri pairwise_disjoint_indexTri iUnion_indexTri


-- @@ L91-96 verbatim
open VirasoroAlgebra in
lemma _root_.VirasoroProject.virasoroTri_cartan :
    (virasoroTri 𝕜).cartan = Submodule.span 𝕜 {.cgen 𝕜, .lgen 𝕜 0} := by
  simp only [virasoroTri, indexTri, TriangularDecomposition.ofBasis, TriangularDecomposition.cartan]
  congr 1
  aesop


-- @@ L98-103 verbatim
open VirasoroAlgebra in
lemma _root_.VirasoroProject.virasoroTri_upper :
    (virasoroTri 𝕜).upper = Submodule.span 𝕜 ((fun n ↦ lgen 𝕜 n) '' {n | 0 < n}) := by
  simp only [virasoroTri, indexTri, TriangularDecomposition.upper, TriangularDecomposition.ofBasis]
  congr 1
  aesop


-- @@ L105-110 verbatim
open VirasoroAlgebra in
lemma _root_.VirasoroProject.virasoroTri_lower :
    (virasoroTri 𝕜).lower = Submodule.span 𝕜 ((fun n ↦ lgen 𝕜 n) '' {n | n < 0}) := by
  simp only [virasoroTri, indexTri, TriangularDecomposition.ofBasis, TriangularDecomposition.lower]
  congr 1
  aesop


-- @@ L112-117 verbatim
open VirasoroAlgebra in
/-- The basis of the Cartan part of the Virasoro triangular decomposition. -/
noncomputable def _root_.VirasoroProject.virasoroTriCartanBasis :
    Basis ({none, some 0} : Set (Option ℤ)) 𝕜 (virasoroTri 𝕜).cartan :=
  TriangularDecomposition.ofBasis.basisPart (VirasoroAlgebra.basisLC 𝕜) indexTri
    pairwise_disjoint_indexTri iUnion_indexTri 0


-- @@ L119-123 verbatim
/-- The highest weight of Virasoro algebra determined by the central charge `c` (`C`-eigenvalue)
and conformal weight `h` (`L₀`-eigenvalue). -/
noncomputable def _root_.VirasoroProject.VirasoroAlgebra.hw (c h : 𝕜) :
    (virasoroTri 𝕜).cartan →ₗ[𝕜] 𝕜 :=
  (virasoroTriCartanBasis 𝕜).constr (M' := 𝕜) 𝕜 (fun i ↦ if i.val = none then c else h)


-- @@ L125-127 verbatim
/-- The Virasoro generator `C` as an element of the Cartan subalgebra. -/
noncomputable def _root_.VirasoroProject.virasoroTriCgen : (virasoroTri 𝕜).part 0 :=
  ⟨.cgen 𝕜, Submodule.mem_span_of_mem (by simp [indexTri])⟩


-- @@ L129-131 verbatim
/-- The Virasoro generator `L₀` as an element of the Cartan subalgebra. -/
noncomputable def _root_.VirasoroProject.virasoroTriLzero : (virasoroTri 𝕜).part 0 :=
  ⟨.lgen 𝕜 0, Submodule.mem_span_of_mem (by simp [indexTri])⟩


-- @@ L133-135 verbatim
@[simp] lemma _root_.VirasoroProject.virasoroTri_cgen_val :
    (virasoroTriCgen 𝕜).val = .cgen 𝕜 :=
  rfl


-- @@ L137-139 verbatim
@[simp] lemma _root_.VirasoroProject.virasoroTri_lzero_val :
    (virasoroTriLzero 𝕜).val = .lgen 𝕜 0 :=
  rfl


-- @@ L141-151 verbatim
open VirasoroAlgebra in
lemma _root_.VirasoroProject.virasoroTri_cartan_basis_none_eq_cgen :
    (virasoroTriCartanBasis 𝕜) ⟨none, Set.mem_insert none {some 0}⟩ = virasoroTriCgen 𝕜 := by
  ext
  simp only [virasoroTriCartanBasis, TriangularDecomposition.ofBasis.basisPart, indexTri,
             virasoroTri_cgen_val]
  convert (basisLC 𝕜).basis_submodule_span_apply {none, some 0} ⟨none, Set.mem_insert none {some 0}⟩
  all_goals
    first
      | rfl
      | rw [VirasoroAlgebra.basisLC_none]


-- @@ L153-165 verbatim
open VirasoroAlgebra in
lemma _root_.VirasoroProject.virasoroTri_cartan_basis_some_eq_lzero :
    (virasoroTriCartanBasis 𝕜) ⟨some 0, by exact Set.mem_insert_of_mem none rfl⟩
      = virasoroTriLzero 𝕜 := by
  ext
  simp only [virasoroTriCartanBasis, TriangularDecomposition.ofBasis.basisPart, indexTri,
             virasoroTri_lzero_val]
  convert (basisLC 𝕜).basis_submodule_span_apply {none, some 0}
          ⟨some 0, Set.mem_insert_of_mem none rfl⟩
  all_goals
    first
      | rfl
      | rw [VirasoroAlgebra.basisLC_some]


-- @@ L167-169 verbatim
lemma _root_.VirasoroProject.virasoroTri_cgen_mem_cartan :
    .cgen 𝕜 ∈ (virasoroTri 𝕜).cartan := by
  simpa only [virasoroTri_cartan] using Submodule.mem_span_of_mem (by simp)


-- @@ L171-173 verbatim
lemma _root_.VirasoroProject.virasoroTri_lgen_zero_mem_cartan :
    .lgen 𝕜 0 ∈ (virasoroTri 𝕜).cartan := by
  simpa only [virasoroTri_cartan] using Submodule.mem_span_of_mem (by simp)


-- @@ L175-179 verbatim
lemma _root_.VirasoroProject.virasoroTri_lgen_pos_mem_upper {n : ℤ} (n_pos : 0 < n) :
    .lgen 𝕜 n ∈ (virasoroTri 𝕜).upper := by
  simp only [virasoroTri_upper]
  apply Submodule.mem_span_of_mem
  exact (Set.mem_image ..).mpr ⟨n, ⟨n_pos, rfl⟩⟩


-- @@ L181-184 verbatim
lemma _root_.VirasoroProject.VirasoroAlgebra.hw_apply_cgen (c h : 𝕜) :
    VirasoroAlgebra.hw 𝕜 c h (virasoroTriCgen 𝕜) = c := by
  rw [← virasoroTri_cartan_basis_none_eq_cgen, VirasoroAlgebra.hw, Basis.constr_basis]
  simp


-- @@ L186-189 verbatim
lemma _root_.VirasoroProject.VirasoroAlgebra.hw_apply_lzero (c h : 𝕜) :
    VirasoroAlgebra.hw 𝕜 c h (virasoroTriLzero 𝕜) = h := by
  rw [← virasoroTri_cartan_basis_some_eq_lzero, VirasoroAlgebra.hw, Basis.constr_basis]
  simp


-- @@ L191-193 verbatim
/-- The Verma module for the Virasoso algebra with central charge `c` and conformal weight `h`. -/
abbrev _root_.VirasoroProject.VirasoroVerma
    (c h : 𝕜) := (virasoroTri 𝕜).VermaHW (VirasoroAlgebra.hw 𝕜 c h)


-- @@ L195-198 verbatim
/-- The highest weight vector in the Verma module for the Virasoso algebra with central charge `c`
and conformal weight `h`. -/
noncomputable abbrev _root_.VirasoroProject.VirasoroVerma.hwVec (c h : 𝕜) :=
   TriangularDecomposition.VermaHW.hwVec (VirasoroAlgebra.hw 𝕜 c h)


-- @@ L200-202 verbatim
lemma _root_.VirasoroProject.VirasoroVerma.hwVec_cyclic (c h : 𝕜) :
    Submodule.span (𝓤 𝕜 (VirasoroAlgebra 𝕜)) {VirasoroVerma.hwVec 𝕜 c h} = ⊤ :=
  VermaModule.hwVec_cyclic ..


-- @@ L204-207 verbatim
lemma _root_.VirasoroProject.VirasoroVerma.lgen_pos_hwVec (c h : 𝕜) {n : ℤ} (n_pos : 0 < n) :
    ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 n) • VirasoroVerma.hwVec 𝕜 c h = 0 :=
  TriangularDecomposition.VermaHW.upper_smul_hwVec
    (VirasoroAlgebra.hw 𝕜 c h) (E := .lgen 𝕜 n) (virasoroTri_lgen_pos_mem_upper 𝕜 n_pos)


-- @@ L209-214 verbatim
lemma _root_.VirasoroProject.VirasoroVerma.lgen_zero_hwVec (c h : 𝕜) :
    ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 0) • VirasoroVerma.hwVec 𝕜 c h =
      h • VirasoroVerma.hwVec 𝕜 c h := by
  convert TriangularDecomposition.VermaHW.cartan_smul_hwVec
          (VirasoroAlgebra.hw 𝕜 c h) (H := .lgen 𝕜 0) (virasoroTri_lgen_zero_mem_cartan 𝕜)
  exact (VirasoroAlgebra.hw_apply_lzero 𝕜 c h).symm


-- @@ L216-221 verbatim
lemma _root_.VirasoroProject.VirasoroVerma.cgen_hwVec (c h : 𝕜) :
    ιUEA 𝕜 (VirasoroAlgebra.cgen 𝕜) • VirasoroVerma.hwVec 𝕜 c h =
      c • VirasoroVerma.hwVec 𝕜 c h := by
  convert TriangularDecomposition.VermaHW.cartan_smul_hwVec
          (VirasoroAlgebra.hw 𝕜 c h) (H := .cgen 𝕜) (virasoroTri_cgen_mem_cartan 𝕜)
  exact (VirasoroAlgebra.hw_apply_cgen 𝕜 c h).symm


-- @@ L223-226 verbatim
lemma _root_.VirasoroProject.VirasoroVerma.cgen_smul (c h : 𝕜) (v : VirasoroVerma 𝕜 c h) :
    ιUEA 𝕜 (VirasoroAlgebra.cgen 𝕜) • v = c • v :=
  UniversalEnvelopingAlgebra.smul_eq_of_cyclic_of_forall_lie_eq_zero
    _ _ (fun _ ↦ rfl) (VirasoroVerma.hwVec_cyclic 𝕜 c h) (VirasoroVerma.cgen_hwVec 𝕜 c h) v


-- @@ L228-231 verbatim
/-- The Virasoro Verma module with central charge `c` and conformal weight `h` has central
charge `c`. -/
instance (c h : 𝕜) : HasCentralCharge 𝕜 (VirasoroVerma 𝕜 c h) c :=
  ⟨fun v ↦ VirasoroVerma.cgen_smul 𝕜 c h v⟩


-- @@ L233-247 verbatim
private lemma _root_.VirasoroProject.upper_smul_eq_zero_of_forall_pos_lgen_smul_eq_zero
    {M : Type*} [AddCommGroup M] [Module (𝓤 𝕜 (VirasoroAlgebra 𝕜)) M] {v : M}
    (hwv_lpos : ∀ n > 0, ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 n) • v = 0) :
    ∀ {E} (_ : E ∈ (virasoroTri 𝕜).upper), (ιUEA 𝕜) E • v = 0 := by
  simp only [virasoroTri_upper]
  apply Submodule.span_induction
  · simp_all
  · simp
  · intro E₁ E₂ _ _ hE₁ hE₂
    simp only [map_add, add_smul, hE₁, hE₂, add_zero]
  · intro r E _ hE
    have hE' : algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) r • (ιUEA 𝕜 E • v) = 0 := by
      simp only [hE, smul_zero]
    simp only [map_smul, ← hE', ← smul_assoc]
    rfl


-- @@ L249-288 verbatim
private lemma _root_.VirasoroProject.cartan_smul_eq_of_cgen_smul_eq_of_lzero_smul_eq {c h : 𝕜}
    {M : Type*} [AddCommGroup M] [Module (𝓤 𝕜 (VirasoroAlgebra 𝕜)) M] {v : M}
    (hwv_c : ιUEA 𝕜 (VirasoroAlgebra.cgen 𝕜) • v
              = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) c • v))
    (hwv_lzero : ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 0) • v
              = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) h • v)) :
    ∀ {H} (hH : H ∈ (virasoroTri 𝕜).cartan) ,
      (ιUEA 𝕜) H • v
        = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜))) ((VirasoroAlgebra.hw 𝕜 c h) ⟨H, hH⟩) • v := by
  simp only [virasoroTri_cartan]
  apply Submodule.span_induction
  · intro X hX
    cases hX with
    | inl X_eq_C =>
      simp only [X_eq_C, hwv_c]
      congr 2
      exact (VirasoroAlgebra.hw_apply_cgen 𝕜 c h).symm
    | inr X_eq_L0 =>
      simp only [Set.mem_singleton_iff] at X_eq_L0
      simp only [X_eq_L0, hwv_lzero]
      congr 2
      exact (VirasoroAlgebra.hw_apply_lzero 𝕜 c h).symm
  · simp only [map_zero, zero_smul]
    convert (zero_smul ..).symm
    convert algebraMap.coe_zero
    exact LinearMap.map_zero (VirasoroAlgebra.hw 𝕜 c h)
  · intro H₁ H₂ _ _ hH₁ hH₂
    simp only [map_add, add_smul, hH₁, hH₂]
    rw [← add_smul, ← map_add, ← map_add]
    rfl
  · intro r H H_mem hH
    have aux : (r • (ιUEA 𝕜) H) • v
                = algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) r • ((ιUEA 𝕜) H • v) := by
      simp only [← smul_assoc, smul_eq_mul, Algebra.smul_def r ((ιUEA 𝕜) H)]
    simp only [map_smul, aux, hH, ← smul_assoc]
    congr 1
    rw [smul_eq_mul, ← map_mul]
    congr 1
    rw [← smul_eq_mul, ← map_smul]
    rfl


-- @@ L290-303 verbatim
/-- The universal map from a Virasoro Verma module to any module with a vector of the
given central charge, conformal weight, and positive-mode annihilation. -/
noncomputable def _root_.VirasoroProject.VirasoroVerma.universalMap {c h : 𝕜}
    (M : Type*) [AddCommGroup M] [Module (𝓤 𝕜 (VirasoroAlgebra 𝕜)) M] {hwv : M}
    (hwv_c : ιUEA 𝕜 (VirasoroAlgebra.cgen 𝕜) • hwv
              = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) c • hwv))
    (hwv_lzero : ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 0) • hwv
              = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) h • hwv))
    (hwv_lpos : ∀ n > 0, ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 n) • hwv = 0) :
    VirasoroVerma 𝕜 c h →ₗ[𝓤 𝕜 (VirasoroAlgebra 𝕜)] M := by
  apply @TriangularDecomposition.VermaHW.universalMap 𝕜 _ (VirasoroAlgebra 𝕜) _ _ (virasoroTri 𝕜)
        (VirasoroAlgebra.hw _ c h) M _ _ hwv ?_ ?_
  · exact private_decl% (cartan_smul_eq_of_cgen_smul_eq_of_lzero_smul_eq 𝕜 hwv_c hwv_lzero)
  · exact private_decl% (upper_smul_eq_zero_of_forall_pos_lgen_smul_eq_zero 𝕜 hwv_lpos)


-- @@ L305-314 verbatim
lemma _root_.VirasoroProject.VirasoroVerma.universalMap_hwVec (c h : 𝕜)
    (M : Type*) [AddCommGroup M] [Module (𝓤 𝕜 (VirasoroAlgebra 𝕜)) M] {hwv : M}
    (hwv_c : ιUEA 𝕜 (VirasoroAlgebra.cgen 𝕜) • hwv
              = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) c • hwv))
    (hwv_lzero : ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 0) • hwv
              = (algebraMap 𝕜 (𝓤 𝕜 (VirasoroAlgebra 𝕜)) h • hwv))
    (hwv_lpos : ∀ n > 0, ιUEA 𝕜 (VirasoroAlgebra.lgen 𝕜 n) • hwv = 0) :
    VirasoroVerma.universalMap 𝕜 M hwv_c hwv_lzero hwv_lpos (VirasoroVerma.hwVec 𝕜 c h) =
      hwv :=
  TriangularDecomposition.VermaHW.universalMap_hwVec ..


-- @@ L316-316 verbatim
end VirasoroVerma


-- @@ L318-318 verbatim
end VirasoroProject
