/-
Copyright (c) 2026 BochaoKong. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BochaoKong
-/
module

public import LeanPool.LocalComplexGeometry.WPTBridge.GermDivision
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal


-- @@ L11-18 verbatim
/-!
# The finite-free quotient by a prepared polynomial

The exact kernel and surjectivity of analytic Weierstrass remainder identify
the quotient by a prepared polynomial with its vector of `d` coefficients.
Transporting the standard function-space basis gives the classes of
`1, w, ..., w^(d-1)`.
-/


-- @@ L20-20 verbatim
@[expose] public section


-- @@ L22-22 verbatim
open scoped BigOperators


-- @@ L24-24 verbatim
namespace LocalComplexGeometry.WPTBridge


-- @@ L26-26 verbatim
open ClassicalComplexWPT


-- @@ L28-28 verbatim
noncomputable section



-- @@ L31-35 verbatim
/-- The principal ideal generated by a fixed prepared polynomial germ. -/
def preparedPolynomialIdeal {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0) :
    Ideal (HolomorphicGerm (n + 1)) :=
  Ideal.span ({preparedPolynomialGerm a ha} : Set (HolomorphicGerm (n + 1)))


-- @@ L37-44 verbatim
/-- Assemble a degree-`< d` polynomial from its coefficient vector, as a
base-linear map. -/
def remainderPolynomialGermLinearMap (n d : ℕ) :
    (Fin d → HolomorphicGerm n) →ₗ[HolomorphicGerm n]
      HolomorphicGerm (n + 1) where
  toFun := remainderPolynomialGerm
  map_add' := remainderPolynomialGerm_add
  map_smul' := remainderPolynomialGerm_smul


-- @@ L46-59 verbatim
/-- Remainder descends to the quotient by the prepared polynomial. -/
def preparedQuotientRemainderLinearMap {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) →ₗ[HolomorphicGerm n]
      (Fin d → HolomorphicGerm n) := by
  let rem := preparedGermDivisionRemainderLinearMap a ha ha0
  let I := preparedPolynomialIdeal a ha
  have hle : I.restrictScalars (HolomorphicGerm n) ≤ LinearMap.ker rem := by
    rw [preparedGermDivisionRemainderLinearMap_ker a ha ha0]
    rfl
  exact (I.restrictScalars (HolomorphicGerm n)).liftQ rem hle |>.comp
    (Submodule.Quotient.restrictScalarsEquiv
      (HolomorphicGerm n) I).symm.toLinearMap


-- @@ L61-68 verbatim
@[simp]
theorem preparedQuotientRemainderLinearMap_mk {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (h : HolomorphicGerm (n + 1)) :
    preparedQuotientRemainderLinearMap a ha ha0
        (Ideal.Quotient.mk (preparedPolynomialIdeal a ha) h) =
      preparedGermDivisionRemainder a ha ha0 h := by
  rfl


-- @@ L70-78 verbatim
/-- The inverse map sends a coefficient vector to the class of its remainder
polynomial. -/
def preparedQuotientRemainderSection {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0) :
    (Fin d → HolomorphicGerm n) →ₗ[HolomorphicGerm n]
      (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) :=
  (Ideal.Quotient.mkₐ (HolomorphicGerm n)
      (preparedPolynomialIdeal a ha)).toLinearMap.comp
    (remainderPolynomialGermLinearMap n d)


-- @@ L80-87 verbatim
@[simp]
theorem preparedQuotientRemainderSection_apply {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (r : Fin d → HolomorphicGerm n) :
    preparedQuotientRemainderSection a ha r =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (remainderPolynomialGerm r) :=
  rfl


-- @@ L89-97 verbatim
@[simp]
theorem preparedGermDivisionRemainder_remainderPolynomialGerm {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (r : Fin d → HolomorphicGerm n) :
    preparedGermDivisionRemainder a ha ha0 (remainderPolynomialGerm r) = r := by
  have hdivision : IsPreparedGermDivision a ha (remainderPolynomialGerm r) 0 r := by
    simp [IsPreparedGermDivision]
  exact (preparedGermDivision_eq_of_isDivision a ha ha0
    (remainderPolynomialGerm r) 0 r hdivision).2


-- @@ L99-105 verbatim
theorem preparedQuotientRemainder_rightInverse {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (preparedQuotientRemainderLinearMap a ha ha0).comp
        (preparedQuotientRemainderSection a ha) = LinearMap.id := by
  ext r
  simp


-- @@ L107-133 verbatim
theorem preparedQuotientRemainder_leftInverse {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (preparedQuotientRemainderSection a ha).comp
        (preparedQuotientRemainderLinearMap a ha ha0) = LinearMap.id := by
  apply LinearMap.ext
  intro x
  obtain ⟨h, rfl⟩ := Ideal.Quotient.mk_surjective x
  have hspec := preparedGermDivision_spec a ha ha0 h
  unfold IsPreparedGermDivision at hspec
  simp only [LinearMap.comp_apply, preparedQuotientRemainderLinearMap_mk,
    preparedQuotientRemainderSection_apply, LinearMap.id_apply]
  have hpzero : Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
      (preparedPolynomialGerm a ha) = 0 := by
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    exact Ideal.mem_span_singleton_self _
  calc
    Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (remainderPolynomialGerm
          (preparedGermDivisionRemainder a ha ha0 h)) =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (preparedGermDivisionQuotient a ha ha0 h * preparedPolynomialGerm a ha +
          remainderPolynomialGerm
            (preparedGermDivisionRemainder a ha ha0 h)) := by
        simp only [map_add, map_mul, hpzero, mul_zero, zero_add]
    _ = Ideal.Quotient.mk (preparedPolynomialIdeal a ha) h :=
      congrArg (Ideal.Quotient.mk (preparedPolynomialIdeal a ha)) hspec.symm


-- @@ L135-146 verbatim
/-- The quotient by a prepared polynomial, as a base-linear copy of its
degree-`< d` coefficient vectors. -/
def preparedQuotientRemainderEquiv {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) ≃ₗ[HolomorphicGerm n]
      (Fin d → HolomorphicGerm n) :=
  LinearEquiv.ofLinearMap
    (preparedQuotientRemainderLinearMap a ha ha0)
    (preparedQuotientRemainderSection a ha)
    (preparedQuotientRemainder_rightInverse a ha ha0)
    (preparedQuotientRemainder_leftInverse a ha ha0)


-- @@ L148-155 verbatim
@[simp]
theorem preparedQuotientRemainderEquiv_mk {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (h : HolomorphicGerm (n + 1)) :
    preparedQuotientRemainderEquiv a ha ha0
        (Ideal.Quotient.mk (preparedPolynomialIdeal a ha) h) =
      preparedGermDivisionRemainder a ha ha0 h :=
  rfl


-- @@ L157-164 verbatim
@[simp]
theorem preparedQuotientRemainderEquiv_symm_apply {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (r : Fin d → HolomorphicGerm n) :
    (preparedQuotientRemainderEquiv a ha ha0).symm r =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (remainderPolynomialGerm r) := by
  rfl


-- @@ L166-176 verbatim
theorem remainderPolynomialGerm_basisFun {n d : ℕ} (i : Fin d) :
    remainderPolynomialGerm
        (Pi.basisFun (HolomorphicGerm n) (Fin d) i) =
      lastCoordinateGerm n ^ (i : ℕ) := by
  classical
  unfold remainderPolynomialGerm
  rw [Pi.basisFun_apply, Finset.sum_eq_single i]
  · simp
  · intro j _ hji
    simp [hji]
  · simp


-- @@ L178-192 verbatim
@[simp]
theorem preparedGermDivisionRemainder_lastCoordinate_pow {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (i : Fin d) :
    preparedGermDivisionRemainder a ha ha0
        (lastCoordinateGerm n ^ (i : ℕ)) =
      Pi.basisFun (HolomorphicGerm n) (Fin d) i := by
  let e := Pi.basisFun (HolomorphicGerm n) (Fin d) i
  have hdivision : IsPreparedGermDivision a ha
      (lastCoordinateGerm n ^ (i : ℕ)) 0 e := by
    unfold IsPreparedGermDivision
    simp only [zero_mul, zero_add]
    exact (remainderPolynomialGerm_basisFun i).symm
  exact (preparedGermDivision_eq_of_isDivision a ha ha0
    (lastCoordinateGerm n ^ (i : ℕ)) 0 e hdivision).2


-- @@ L194-201 verbatim
/-- The explicit power basis of the prepared quotient. -/
def preparedQuotientBasis {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    Module.Basis (Fin d) (HolomorphicGerm n)
      (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) :=
  (Pi.basisFun (HolomorphicGerm n) (Fin d)).map
    (preparedQuotientRemainderEquiv a ha ha0).symm


-- @@ L203-214 verbatim
@[simp]
theorem preparedQuotientBasis_apply {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) (i : Fin d) :
    preparedQuotientBasis a ha ha0 i =
      Ideal.Quotient.mk (preparedPolynomialIdeal a ha)
        (lastCoordinateGerm n ^ (i : ℕ)) := by
  apply (preparedQuotientRemainderEquiv a ha ha0).injective
  rw [preparedQuotientBasis, Module.Basis.map_apply,
    LinearEquiv.apply_symm_apply,
    preparedQuotientRemainderEquiv_mk,
    preparedGermDivisionRemainder_lastCoordinate_pow]


-- @@ L216-223 verbatim
/-- The prepared quotient is free over the lower-dimensional holomorphic
germ ring. -/
theorem preparedQuotient_moduleFree {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    Module.Free (HolomorphicGerm n)
      (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) :=
  Module.Free.of_basis (preparedQuotientBasis a ha ha0)


-- @@ L225-232 verbatim
/-- The prepared quotient is finite over the lower-dimensional holomorphic
germ ring. -/
theorem preparedQuotient_moduleFinite {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    Module.Finite (HolomorphicGerm n)
      (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) :=
  Module.Finite.of_basis (preparedQuotientBasis a ha ha0)


-- @@ L234-245 verbatim
/-- Combined finite-free conclusion for the quotient by a prepared
polynomial.  The preceding `preparedQuotientBasis` specifies its rank-`d`
power basis. -/
theorem preparedQuotient_finiteFree {n d : ℕ}
    (a : Fin d → Base n → ℂ) (ha : ∀ i, AnalyticAt ℂ (a i) 0)
    (ha0 : ∀ i, a i 0 = 0) :
    Module.Free (HolomorphicGerm n)
        (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) ∧
      Module.Finite (HolomorphicGerm n)
        (HolomorphicGerm (n + 1) ⧸ preparedPolynomialIdeal a ha) :=
  ⟨preparedQuotient_moduleFree a ha ha0,
    preparedQuotient_moduleFinite a ha ha0⟩


-- @@ L247-247 verbatim
end


-- @@ L249-249 verbatim
end LocalComplexGeometry.WPTBridge
