/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import LeanPool.DomainTheory.Neighborhood.Exercise414
public import Mathlib.Algebra.Group.Submonoid.Basic
public import Mathlib.Algebra.Group.Pointwise.Set.Basic
public import Mathlib.Algebra.Group.Nat.Defs


-- @@ L13-50 verbatim
/-!
# Exercise 4.17 (Scott 1981, PRG-19, Lecture IV) — least solution in a monoid
power-set

(For algebraists.) Let `⟨S, 1, ·⟩` be a monoid (a semi-group with unit). Then `P
S` is a domain — in
fact a **complete lattice** (Exercise 4.14). For `a, b ∈ S`, what is the *least*
`x ∈ P S` with

  `x = {1} ∪ {a, b} ∪ x · x`,    where   `x · y = {t · u ∣ t ∈ x, u ∈ y}`?

**Answer.** The least solution is the **submonoid generated by `{a, b}`** — i.e.
the set of all
finite products of `a`s and `b`s (including the empty product `1`):

  `lfpSet (F a b) = ⟨{a, b}⟩  (= Submonoid.closure {a, b})`.

The operator `F a b x = {1} ∪ {a, b} ∪ x · x` is monotone (pointwise `·` is
monotone), so by
Exercise 4.14 (the dual Knaster–Tarski over the complete lattice `P S`) its least
fixed point
`lfpSet (F a b)` exists; we identify it with the submonoid closure
(`lfpSet_eq_closure`): a fixed
point of `F` is exactly a submonoid containing `{a, b}`, and the least such is the
closure.

**Need the fixed point be unique?** **No.** In *any* monoid the whole set
`Set.univ` is also a fixed
point (`F a b univ = univ`, since `s = 1 · s ∈ univ · univ`). So whenever the
monoid is not
generated by `{a, b}` there are at least two fixed points: taking `S = ℕ` (under
`·`) and `a = b = 1`,
the least solution is `{1}` while `Set.univ` is another (`fixedPoint_not_unique`).

The constructions are **choice-free** (`#print axioms ⊆ {propext, Quot.sound}`),
inheriting
`lfpSet` from Exercise 4.14.
-/


-- @@ L52-52 verbatim
@[expose] public section


-- @@ L54-54 verbatim
namespace Domain.Neighborhood.Exercise417


-- @@ L56-56 verbatim
open Pointwise

-- @@ L57-57 verbatim
open Domain.Neighborhood.Exercise414


-- @@ L59-59 verbatim
variable {S : Type*} [Monoid S]


-- @@ L61-62 verbatim
/-- Scott's operator `F(x) = {1} ∪ {a, b} ∪ x · x` on `P S`. -/
def F (a b : S) (x : Set S) : Set S := {1} ∪ {a, b} ∪ x * x


-- @@ L64-66 verbatim
theorem F_monotone (a b : S) : Monotone (F a b) := by
  intro x y hxy
  exact Set.union_subset_union (le_refl _) (Set.mul_subset_mul hxy hxy)


-- @@ L68-70 verbatim
/-- `{1} ∪ {a, b} ⊆ F a b x`. -/
theorem base_subset_F (a b : S) (x : Set S) : {1} ∪ {a, b} ⊆ F a b x :=
  Set.subset_union_left


-- @@ L72-73 verbatim
theorem self_mul_subset_F (a b : S) (x : Set S) : x * x ⊆ F a b x :=
  Set.subset_union_right


-- @@ L75-76 verbatim
theorem one_mem_F (a b : S) (x : Set S) : (1 : S) ∈ F a b x :=
  base_subset_F a b x (Set.mem_union_left _ rfl)


-- @@ L78-79 verbatim
theorem a_mem_F (a b : S) (x : Set S) : a ∈ F a b x :=
  base_subset_F a b x (Set.mem_union_right _ (Set.mem_insert _ _))


-- @@ L81-82 verbatim
theorem b_mem_F (a b : S) (x : Set S) : b ∈ F a b x :=
  base_subset_F a b x (Set.mem_union_right _ (Set.mem_insert_of_mem _ rfl))


-- @@ L84-84 verbatim
/-! ### The least solution. -/


-- @@ L86-91 verbatim
/-- The least solution `lfpSet (F a b)` indeed solves Scott's equation `x = {1} ∪
{a, b} ∪ x ·
x`. -/
theorem leastSolution_eq (a b : S) :
    F a b (lfpSet (F a b)) = lfpSet (F a b) :=
  lfpSet_isFixed (F a b) (F_monotone a b)


-- @@ L93-101 verbatim
/-- A pre-fixed point of `F` is a submonoid containing `{a, b}`: it contains `1`
and is closed under
multiplication and contains `a, b`. Packaged as the submonoid with that carrier. -/
def preFixSubmonoid (a b : S) {x : Set S} (hx : F a b x ⊆ x) : Submonoid S where
  carrier := x
  one_mem' := hx (one_mem_F a b x)
  mul_mem' := by
    intro s t hs ht
    exact hx (self_mul_subset_F a b x (Set.mul_mem_mul hs ht))


-- @@ L103-130 verbatim
/-- **Exercise 4.17 (Scott 1981, PRG-19).** The least solution of `x = {1} ∪ {a,
b} ∪ x · x` is the
submonoid generated by `{a, b}` (all finite products of `a`s and `b`s, including
`1`). -/
theorem lfpSet_eq_closure (a b : S) :
    lfpSet (F a b) = (Submonoid.closure ({a, b} : Set S) : Set S) := by
  apply Set.Subset.antisymm
  · -- `lfpSet ⊆ closure`: the closure is a (pre-)fixed point of `F`.
    have hclosed : F a b (Submonoid.closure ({a, b} : Set S)) ⊆
        (Submonoid.closure ({a, b} : Set S) : Set S) := by
      apply Set.union_subset
      · apply Set.union_subset
        · rintro s rfl; exact (Submonoid.closure ({a, b} : Set S)).one_mem
        · simp_all
      · rintro s ⟨t, ht, u, hu, rfl⟩
        exact (Submonoid.closure ({a, b} : Set S)).mul_mem ht hu
    exact lfpSet_subset (F a b) hclosed
  · -- `closure ⊆ lfpSet`: `lfpSet` is a submonoid containing `{a, b}`.
    have hfix : F a b (lfpSet (F a b)) ⊆ lfpSet (F a b) :=
      le_of_eq (leastSolution_eq a b)
    have ha : a ∈ lfpSet (F a b) := hfix (a_mem_F a b _)
    have hb : b ∈ lfpSet (F a b) := hfix (b_mem_F a b _)
    have hmem : ({a, b} : Set S) ⊆ lfpSet (F a b) := by
      intro s hs
      rcases Set.mem_insert_iff.mp hs with h | h
      · rw [h]; exact ha
      · rw [Set.mem_singleton_iff.mp h]; exact hb
    exact (Submonoid.closure_le (S := preFixSubmonoid a b hfix)).mpr hmem


-- @@ L132-132 verbatim
/-! ### Non-uniqueness. -/


-- @@ L134-139 verbatim
/-- In any monoid, `Set.univ` is a fixed point of `F a b`: `s = 1 · s ∈ univ ·
univ`. -/
theorem F_univ (a b : S) : F a b (Set.univ : Set S) = Set.univ := by
  apply Set.Subset.antisymm (Set.subset_univ _)
  intro s _
  exact self_mul_subset_F a b _ (Set.mem_mul.mpr ⟨1, trivial, s, trivial, one_mul s⟩)


-- @@ L141-144 verbatim
/-- `{1}` is a fixed point of `F 1 1`: `{1} ∪ {1, 1} ∪ {1}·{1} = {1}`. -/
theorem F_one_one_singleton : F (1 : ℕ) 1 ({1} : Set ℕ) = {1} := by
  unfold F
  simp_all


-- @@ L146-154 verbatim
/-- **Exercise 4.17 (Scott 1981, PRG-19).** The fixed point need **not** be
unique: over `S = ℕ`
(under `·`) with `a = b = 1`, both `{1}` (the least solution) and `Set.univ` solve
the equation, and
they are distinct. -/
theorem fixedPoint_not_unique :
    ∃ x y : Set ℕ, F 1 1 x = x ∧ F 1 1 y = y ∧ x ≠ y := by
  refine ⟨{1}, Set.univ, F_one_one_singleton, F_univ 1 1, ?_⟩
  simp_all


-- @@ L156-156 verbatim
end Domain.Neighborhood.Exercise417
