/-
Copyright (c) 2026 Arthur Freitas Ramos, David Hulak, Ruy de Queiroz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arthur Freitas Ramos, David Hulak, Ruy de Queiroz
-/
module


public import Mathlib.AlgebraicTopology.FundamentalGroupoid.FundamentalGroup
public import LeanPool.FiniteGraphFundamentalGroup.Proof
import Mathlib.Topology.WithTopology


-- @@ L13-17 verbatim
/-!
# Geometric realization of a finite quiver

This module realizes vertices discretely and every directed edge as a separate interval cell.
-/


-- @@ L19-19 verbatim
@[expose] public section


-- @@ L21-21 verbatim
open Set Function

-- @@ L22-22 verbatim
open CategoryTheory CategoryTheory.SingleObj Quiver

-- @@ L23-23 verbatim
open unitInterval


-- @@ L25-25 verbatim
noncomputable section


-- @@ L27-27 verbatim
universe u


-- @@ L29-29 verbatim
namespace FiniteGraphFreeGroup


-- @@ L31-44 verbatim
/-!
# A geometric realization of a finite quiver

The combinatorial development works with a quiver and its free groupoid.  The
construction in this file supplies the missing topological object: every
directed edge gets a copy of the unit interval, and its two endpoints are
identified with the source and target vertices.  Parallel edges and loops are
kept as distinct interval cells.

The quotient topology is the standard weak topology on this finite one-
dimensional cell complex.  The fundamental-group comparison is developed in
the later lemmas; the definitions here are intentionally independent of any
choice of spanning tree.
-/


-- @@ L46-49 verbatim
/-- The disjoint union of discrete vertices and one interval for each edge. -/
abbrev graphRealizationPre (V : Type u) [Quiver.{u} V] :=
  WithDiscreteTopology V ⊕
    Σ _e : WithDiscreteTopology (Quiver.Total V), I


-- @@ L51-53 verbatim
/-- A graph vertex regarded as a point of the discrete vertex space. -/
abbrev graphDiscreteVertex {V : Type u} (v : V) : WithDiscreteTopology V :=
  WithTopology.toTopology (⊥ : TopologicalSpace V) v


-- @@ L55-58 verbatim
/-- A graph edge regarded as a point of the discrete total-edge space. -/
abbrev graphDiscreteEdge {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    WithDiscreteTopology (Quiver.Total V) :=
  WithTopology.toTopology (⊥ : TopologicalSpace (Quiver.Total V)) e


-- @@ L60-62 verbatim
/-- Forgets the discrete topology from a graph vertex. -/
abbrev graphVertexUnderlying {V : Type u} (v : WithDiscreteTopology V) : V :=
  WithTopology.ofTopology v


-- @@ L64-67 verbatim
/-- Forgets the discrete topology from a total graph edge. -/
abbrev graphEdgeUnderlying {V : Type u} [Quiver.{u} V]
    (e : WithDiscreteTopology (Quiver.Total V)) : Quiver.Total V :=
  WithTopology.ofTopology e


-- @@ L69-77 verbatim
/-- The endpoint identifications used to form the geometric realization. -/
inductive graphRealizationGenerator {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealizationPre V → Prop
  | source (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 0⟩) (Sum.inl (graphDiscreteVertex e.left))
  | target (e : Quiver.Total V) :
      graphRealizationGenerator
        (Sum.inr ⟨graphDiscreteEdge e, 1⟩) (Sum.inl (graphDiscreteVertex e.right))


-- @@ L79-82 verbatim
/-- The equivalence relation generated by the two endpoint identifications. -/
instance graphRealizationSetoid {V : Type u} [Quiver.{u} V] :
    Setoid (graphRealizationPre V) :=
  Relation.EqvGen.setoid (graphRealizationGenerator (V := V))


-- @@ L84-86 verbatim
/-! The endpoint label is an invariant of the quotient relation.  Besides
    separating vertices, this records why no edge cell is accidentally glued
    to a vertex away from its two prescribed endpoints. -/


-- @@ L88-95 verbatim
/-- Labels the two endpoints of an edge interval and leaves interior points unlabeled. -/
def graphRealizationEndpointLabel {V : Type u} [Quiver.{u} V]
    : graphRealizationPre V → Option V
  | Sum.inl v => some (graphVertexUnderlying v)
  | Sum.inr ⟨e, t⟩ =>
      if t = 0 then some (graphEdgeUnderlying e).left
      else if t = 1 then some (graphEdgeUnderlying e).right
      else none


-- @@ L97-102 verbatim
lemma graphRealizationGenerator_endpointLabel {V : Type u} [Quiver.{u} V]
    {x y : graphRealizationPre V}
    (h : graphRealizationGenerator x y) :
  graphRealizationEndpointLabel x = graphRealizationEndpointLabel y := by
  cases h <;> simp [graphRealizationEndpointLabel, graphVertexUnderlying,
    graphEdgeUnderlying]


-- @@ L104-112 verbatim
lemma graphRealization_eqvGen_endpointLabel {V : Type u} [Quiver.{u} V]
    {x y : graphRealizationPre V}
    (h : Relation.EqvGen (graphRealizationGenerator (V := V)) x y) :
    graphRealizationEndpointLabel x = graphRealizationEndpointLabel y := by
  induction h with
  | rel x y h => exact graphRealizationGenerator_endpointLabel h
  | refl x => rfl
  | symm x y h ih => exact ih.symm
  | trans x y z hxy hyz ihxy ihyz => exact ihxy.trans ihyz


-- @@ L114-116 verbatim
/-- The geometric realization of a finite directed multigraph. -/
abbrev graphRealization (V : Type u) [Quiver.{u} V] :=
  Quotient (graphRealizationSetoid (V := V))


-- @@ L118-121 verbatim
/-- The quotient map from the disjoint union of cells. -/
abbrev graphRealizationQuotient {V : Type u} [Quiver.{u} V] :
    graphRealizationPre V → graphRealization V :=
  Quotient.mk'


-- @@ L123-125 verbatim
/-- The point of the realization corresponding to a vertex. -/
def graphVertex {V : Type u} [Quiver.{u} V] (v : V) : graphRealization V :=
  graphRealizationQuotient (Sum.inl (graphDiscreteVertex v))


-- @@ L127-131 verbatim
/-- The endpoint label descends to the quotient as a set-theoretic invariant. -/
def graphRealizationEndpointLabelQuotient {V : Type u} [Quiver.{u} V] :
    graphRealization V → Option V :=
  Quotient.lift graphRealizationEndpointLabel
    (fun _ _ h => graphRealization_eqvGen_endpointLabel h)


-- @@ L133-137 verbatim
@[simp]
theorem graphRealizationEndpointLabelQuotient_mk {V : Type u} [Quiver.{u} V]
    (x : graphRealizationPre V) :
    graphRealizationEndpointLabelQuotient (graphRealizationQuotient x) =
      graphRealizationEndpointLabel x := rfl


-- @@ L139-143 verbatim
@[simp]
theorem graphRealizationEndpointLabelQuotient_vertex {V : Type u} [Quiver.{u} V]
    (v : V) :
    graphRealizationEndpointLabelQuotient (graphVertex v) = some v := by
  rfl


-- @@ L145-148 verbatim
theorem graphRealization_isOpen_iff {V : Type u} [Quiver.{u} V]
    {s : Set (graphRealization V)} :
    IsOpen s ↔ IsOpen (graphRealizationQuotient ⁻¹' s) := by
  exact isOpen_coinduced


-- @@ L150-161 verbatim
theorem graphRealization_image_preimage_eq_of_saturated
    {V : Type u} [Quiver.{u} V] {s : Set (graphRealizationPre V)}
    (hs : ∀ {x y : graphRealizationPre V},
      Relation.EqvGen (graphRealizationGenerator (V := V)) x y →
        (x ∈ s ↔ y ∈ s)) :
    graphRealizationQuotient ⁻¹' (graphRealizationQuotient '' s) = s := by
  ext x
  constructor
  · rintro ⟨y, hy, hxy⟩
    exact (hs (Quotient.exact hxy)).mp hy
  · intro hx
    exact ⟨x, hx, rfl⟩


-- @@ L163-172 verbatim
theorem graphRealization_image_isOpen_of_saturated
    {V : Type u} [Quiver.{u} V] {s : Set (graphRealizationPre V)}
    (hs : ∀ {x y : graphRealizationPre V},
      Relation.EqvGen (graphRealizationGenerator (V := V)) x y →
        (x ∈ s ↔ y ∈ s))
    (hopen : IsOpen s) :
    IsOpen (graphRealizationQuotient '' s) := by
  rw [graphRealization_isOpen_iff,
    graphRealization_image_preimage_eq_of_saturated hs]
  exact hopen


-- @@ L174-181 verbatim
/-- The characteristic path of the interval cell associated to an edge. -/
def graphEdgePath {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    C(I, graphRealization V) where
  toFun t := graphRealizationQuotient (Sum.inr ⟨graphDiscreteEdge e, t⟩)
  continuous_toFun :=
    continuous_quotient_mk'.comp <|
      continuous_inr.comp
        (continuous_sigmaMk (i := graphDiscreteEdge e))


-- @@ L183-185 verbatim
@[simp]
theorem graphRealizationQuotient_vertex {V : Type u} [Quiver.{u} V] (v : V) :
    graphRealizationQuotient (Sum.inl (graphDiscreteVertex v)) = graphVertex v := rfl


-- @@ L187-190 verbatim
@[simp]
theorem graphEdgePath_zero {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    graphEdgePath e 0 = graphVertex e.left := by
  exact Quotient.sound (Relation.EqvGen.rel _ _ (graphRealizationGenerator.source e))


-- @@ L192-195 verbatim
@[simp]
theorem graphEdgePath_one {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    graphEdgePath e 1 = graphVertex e.right := by
  exact Quotient.sound (Relation.EqvGen.rel _ _ (graphRealizationGenerator.target e))


-- @@ L197-203 verbatim
theorem graphRealization_edge_interior_ne_vertex {V : Type u} [Quiver.{u} V]
    (e : Quiver.Total V) {t : I} (ht0 : t ≠ 0) (ht1 : t ≠ 1) (v : V) :
    graphRealizationQuotient (Sum.inr ⟨graphDiscreteEdge e, t⟩) ≠ graphVertex v := by
  intro h
  have hlabel := congrArg graphRealizationEndpointLabelQuotient h
  simp [graphRealizationEndpointLabelQuotient_mk,
    graphRealizationEndpointLabel, ht0, ht1] at hlabel


-- @@ L205-207 verbatim
theorem continuous_graphEdgePath {V : Type u} [Quiver.{u} V] (e : Quiver.Total V) :
    Continuous (graphEdgePath e) :=
  (graphEdgePath e).continuous


-- @@ L209-215 verbatim
/-- The interval cell, regarded as a path from the source to the target. -/
def graphRealizationForwardPath {V : Type u} [Quiver.{u} V]
    {a b : V} (e : a ⟶ b) :
    Path (graphVertex a) (graphVertex b) where
  toContinuousMap := graphEdgePath ⟨a, b, e⟩
  source' := graphEdgePath_zero ⟨a, b, e⟩
  target' := graphEdgePath_one ⟨a, b, e⟩


-- @@ L217-224 verbatim
/-- A continuous parametrisation of the part of an interval cell from `t` to
    its source endpoint. -/
def graphEdgeRetraction (t : I) : C(I, I) where
  toFun s :=
    ⟨(1 - (s : ℝ)) * (t : ℝ),
      unitInterval.mul_mem
        ⟨unitInterval.one_minus_nonneg s, unitInterval.one_minus_le_one s⟩ t.2⟩
  continuous_toFun := by fun_prop


-- @@ L226-229 verbatim
@[simp]
theorem graphEdgeRetraction_zero (t : I) : graphEdgeRetraction t 0 = t := by
  apply Subtype.ext
  simp [graphEdgeRetraction]


-- @@ L231-234 verbatim
@[simp]
theorem graphEdgeRetraction_one (t : I) : graphEdgeRetraction t 1 = 0 := by
  apply Subtype.ext
  simp [graphEdgeRetraction]


-- @@ L236-242 verbatim
/-- The homotopy moving points of an edge interval toward its source. -/
def graphEdgePathToSource {V : Type u} [Quiver.{u} V]
    (e : Quiver.Total V) (t : I) :
    Path (graphEdgePath e t) (graphVertex e.left) where
  toContinuousMap := (graphEdgePath e).comp (graphEdgeRetraction t)
  source' := by simp
  target' := by simp


-- @@ L244-256 verbatim
theorem graphRealizationPre_join_vertex {V : Type u} [Quiver.{u} V]
    (x : graphRealizationPre V) :
    ∃ v : V, Joined (graphRealizationQuotient x) (graphVertex v) := by
  cases x with
  | inl v =>
      refine ⟨graphVertexUnderlying v, ?_⟩
      exact ⟨Path.refl _⟩
  | inr z =>
      rcases z with ⟨e, t⟩
      refine ⟨(graphEdgeUnderlying e).left, ?_⟩
      refine ⟨?path⟩
      simpa [graphEdgePath, graphEdgeUnderlying, graphDiscreteEdge] using
        (graphEdgePathToSource (graphEdgeUnderlying e) t)


-- @@ L258-261 verbatim
/-! The symmetrified quiver is the combinatorial source used by the free
    groupoid.  Its positive arrows use the characteristic interval in the
    forward direction, while its negative arrows use the same interval in
    reverse. -/


-- @@ L263-269 verbatim
/-- The realization path of a symmetric edge, reversing the interval when necessary. -/
def graphRealizationSymmetricEdgePath {V : Type u} [Quiver.{u} V]
    {a b : V} (e : (Quiver.symmetrifyQuiver V).Hom a b) :
    Path (graphVertex (V := V) a) (graphVertex (V := V) b) :=
  match e with
  | Sum.inl e => graphRealizationForwardPath e
  | Sum.inr e => (graphRealizationForwardPath e).symm


-- @@ L271-279 verbatim
/-- Concatenates realized edge paths along a quiver path. -/
def graphRealizationQuiverPath {V : Type u} [Quiver.{u} V]
    {a b : V}
    (p : @Quiver.Path (Quiver.Symmetrify V)
      (Quiver.symmetrifyQuiver V) a b) :
    Path (graphVertex (V := V) a) (graphVertex (V := V) b) := by
  induction p with
  | nil => exact Path.refl _
  | cons p e ih => exact ih.trans (graphRealizationSymmetricEdgePath e)


-- @@ L281-285 verbatim
theorem graphRealizationQuiverPath_nil {V : Type u} [Quiver.{u} V]
    (a : V) :
    graphRealizationQuiverPath
      (Quiver.Path.nil : @Quiver.Path (Quiver.Symmetrify V)
        (Quiver.symmetrifyQuiver V) a a) = Path.refl (graphVertex a) := rfl


-- @@ L287-297 verbatim
theorem graphRealization_pathConnected {V : Type u} [Quiver.{u} V]
    [WeaklyConnected V] (root : V) :
    PathConnectedSpace (graphRealization V) where
  nonempty := ⟨graphVertex root⟩
  joined x y := by
    refine Quotient.inductionOn₂ x y ?_
    intro x y
    rcases graphRealizationPre_join_vertex x with ⟨a, hxa⟩
    rcases graphRealizationPre_join_vertex y with ⟨b, hyb⟩
    rcases WeaklyConnected.path a b with ⟨p⟩
    exact ⟨hxa.somePath.trans ((graphRealizationQuiverPath p).trans hyb.somePath.symm)⟩


-- @@ L299-306 verbatim
theorem graphRealization_compact {V : Type u} [Quiver.{u} V]
    [Finite V] [FiniteQuiver V] : CompactSpace (graphRealization V) := by
  let _ : Fintype V := Fintype.ofFinite V
  let _ : Finite (Quiver.Total V) := Finite.of_injective
    (fun e : Quiver.Total V ↦ (⟨e.left, e.right, e.hom⟩ : Σ a b : V, a ⟶ b))
    (by intro a b h; cases a; cases b; cases h; rfl)
  let _ : CompactSpace (graphRealizationPre V) := by infer_instance
  infer_instance


-- @@ L308-313 verbatim
/-- The prefunctor sending graph vertices and edges to their realization paths. -/
def graphRealizationQuiverMap {V : Type u} [Quiver.{u} V] :
    V ⥤q FundamentalGroupoid (graphRealization V) where
  obj v := FundamentalGroupoid.mk (graphVertex v)
  map e := FundamentalGroupoid.fromPath
    (Path.Homotopic.Quotient.mk (graphRealizationForwardPath e))


-- @@ L315-317 verbatim
/-! The universal property of Mathlib's free groupoid produces the canonical
    functor from the combinatorial graph groupoid into the topological
    fundamental groupoid of the realization. -/


-- @@ L319-322 verbatim
/-- The functor from the free graph groupoid to the realization's fundamental groupoid. -/
def graphFreeGroupoidToTopological {V : Type u} [Quiver.{u} V] :
    Quiver.FreeGroupoid V ⥤ FundamentalGroupoid (graphRealization V) :=
  Quiver.FreeGroupoid.lift (graphRealizationQuiverMap (V := V))


-- @@ L324-328 verbatim
theorem graphFreeGroupoidToTopological_restrict {V : Type u} [Quiver.{u} V] :
    (Quiver.FreeGroupoid.of V ⋙q
      (graphFreeGroupoidToTopological (V := V)).toPrefunctor) =
      graphRealizationQuiverMap (V := V) := by
  exact Quiver.FreeGroupoid.lift_spec (graphRealizationQuiverMap (V := V))


-- @@ L330-331 verbatim
/-! A quiver map acts on the realization cell by cell.  This is the map used
    below for the realization of the path-lifting cover. -/


-- @@ L333-340 verbatim
/-- The map on vertex and edge-interval representatives induced by a quiver prefunctor. -/
def graphRealizationPreMap {V W : Type u} [Quiver.{u} V] [Quiver.{u} W]
    (F : V ⥤q W) : graphRealizationPre V → graphRealizationPre W :=
  Sum.elim
    (fun v => Sum.inl (graphDiscreteVertex (F.obj (graphVertexUnderlying v))))
    (fun z =>
      let e := graphEdgeUnderlying z.1
      Sum.inr ⟨graphDiscreteEdge ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩, z.2⟩)


-- @@ L342-353 verbatim
theorem graphRealizationPreMap_generator {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) {x y : graphRealizationPre V}
    (h : graphRealizationGenerator x y) :
    graphRealizationGenerator (graphRealizationPreMap F x)
      (graphRealizationPreMap F y) := by
  cases h with
  | source e =>
      exact graphRealizationGenerator.source
        ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩
  | target e =>
      exact graphRealizationGenerator.target
        ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩


-- @@ L355-364 verbatim
theorem graphRealizationPreMap_eqvGen {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) {x y : graphRealizationPre V}
    (h : Relation.EqvGen (graphRealizationGenerator (V := V)) x y) :
    Relation.EqvGen (graphRealizationGenerator (V := W))
      (graphRealizationPreMap F x) (graphRealizationPreMap F y) := by
  induction h with
  | rel x y h => exact Relation.EqvGen.rel _ _ (graphRealizationPreMap_generator F h)
  | refl x => exact Relation.EqvGen.refl _
  | symm x y h ih => exact Relation.EqvGen.symm _ _ ih
  | trans x y z hxy hyz ihxy ihyz => exact Relation.EqvGen.trans _ _ _ ihxy ihyz


-- @@ L366-372 verbatim
/-- The continuous map of graph realizations induced by a quiver prefunctor. -/
def graphRealizationMap {V W : Type u} [Quiver.{u} V] [Quiver.{u} W]
    (F : V ⥤q W) : graphRealization V → graphRealization W := by
  let f : graphRealizationPre V → graphRealization W :=
    fun x => graphRealizationQuotient (graphRealizationPreMap F x)
  refine Quotient.lift f (fun x y h => ?_)
  exact Quotient.sound (graphRealizationPreMap_eqvGen F h)


-- @@ L374-398 verbatim
theorem continuous_graphRealizationMap {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) :
    Continuous (graphRealizationMap F) := by
  let f : graphRealizationPre V → graphRealization W :=
    fun x => graphRealizationQuotient (graphRealizationPreMap F x)
  have hcont : Continuous (graphRealizationPreMap F) := by
    apply continuous_sumElim.2
    constructor
    · exact continuous_inl.comp continuous_of_discreteTopology
    · apply continuous_inr.comp
      apply continuous_sigma
      intro e
      change Continuous (fun t : I =>
        (⟨graphDiscreteEdge
            ⟨F.obj (graphEdgeUnderlying e).left,
              F.obj (graphEdgeUnderlying e).right,
              F.map (graphEdgeUnderlying e).hom⟩, t⟩ :
          Σ _e : WithDiscreteTopology (Quiver.Total W), I))
      exact (continuous_sigmaMk (i := graphDiscreteEdge
        ⟨F.obj (graphEdgeUnderlying e).left,
          F.obj (graphEdgeUnderlying e).right,
          F.map (graphEdgeUnderlying e).hom⟩)).comp continuous_id
  have hf : Continuous f := continuous_quotient_mk'.comp hcont
  change Continuous (Quotient.lift f _)
  apply hf.quotient_lift


-- @@ L400-404 verbatim
@[simp]
theorem graphRealizationMap_vertex {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) (v : V) :
    graphRealizationMap F (graphVertex v) = graphVertex (F.obj v) := by
  rfl


-- @@ L406-411 verbatim
@[simp]
theorem graphRealizationMap_edgePath {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) (e : Quiver.Total V) (t : I) :
    graphRealizationMap F (graphEdgePath e t) =
      graphEdgePath ⟨F.obj e.left, F.obj e.right, F.map e.hom⟩ t := by
  rfl


-- @@ L413-418 verbatim
theorem graphRealizationMap_forwardPath {V W : Type u} [Quiver.{u} V]
    [Quiver.{u} W] (F : V ⥤q W) {a b : V} (e : a ⟶ b) :
    (graphRealizationMap F) ∘ (graphRealizationForwardPath e) =
      graphRealizationForwardPath (F.map e) := by
  ext t
  rfl


-- @@ L420-424 verbatim
/-! Taking the endomorphism group at a chosen vertex gives the canonical
    comparison homomorphism on fundamental groups.  The present file proves
    its construction and its behavior on edge generators; an isomorphism
    theorem requires the separate topological normal-form argument for paths
    in a finite one-dimensional cell complex. -/


-- @@ L426-431 verbatim
/-- The homomorphism from combinatorial loops to loops in the topological realization. -/
def graphCombinatorialToTopological {V : Type u} [Quiver.{u} V]
    (root : V) :
    graphFundamentalGroup root →*
      FundamentalGroup (graphRealization V) (graphVertex root) :=
  (graphFreeGroupoidToTopological (V := V)).mapEnd _


-- @@ L433-434 verbatim
/-! The geometric basepoint change is available independently of the still
    open comparison-isomorphism theorem. -/


-- @@ L436-444 verbatim
/-- Changes the basepoint of the topological fundamental group along a chosen graph path. -/
noncomputable def graphTopologicalRootEquiv {V : Type u} [Quiver.{u} V]
    [WeaklyConnected V] (root₁ root₂ : V) :
    FundamentalGroup (graphRealization V) (graphVertex root₁) ≃*
      FundamentalGroup (graphRealization V) (graphVertex root₂) := by
  letI : PathConnectedSpace (graphRealization V) :=
    graphRealization_pathConnected root₁
  exact FundamentalGroup.fundamentalGroupMulEquivOfPathConnected
    (graphVertex root₁) (graphVertex root₂)


-- @@ L446-450 verbatim
theorem graphVertex_injective {V : Type u} [Quiver.{u} V]
    {v w : V} (h : graphVertex v = graphVertex w) : v = w := by
  have h' := Quotient.exact h
  exact Option.some.inj <|
    graphRealization_eqvGen_endpointLabel h'


-- @@ L452-454 verbatim
theorem graphVertex_injective_iff {V : Type u} [Quiver.{u} V]
    {v w : V} : graphVertex v = graphVertex w ↔ v = w := by
  exact ⟨graphVertex_injective, congrArg graphVertex⟩


-- @@ L456-456 verbatim
end FiniteGraphFreeGroup
