/-
Copyright (c) 2026 Jue Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jue Xu
-/

module

public import LeanPool.LowWeightPauliDynamics.Pauli.TrotterTruncate


-- @@ L11-37 verbatim
/-!
# A two-qubit witness with a nonzero discarded component

A concrete non-vacuity witness for `apd:eq:step_component` and `apd:thm:triangle`. The input
`P = ZI` has weight one. A rotation generated by `G = XX` through conjugation angle `π / 2` turns
it into `Q = YX`, of weight two and Pauli norm one. A second rotation, generated by `Q`, leaves
this component unchanged. A weight-one cutoff at the end of this two-rotation step therefore
removes a nonzero observable. So the statements about discarded operators in `Pauli/Discard` and
`Pauli/TrotterTruncate` are not vacuous: they are exercised on a step whose high-weight sector is
nonempty and whose retained set is not `univ`.

The angle `π / 2` tests a nonzero discard and the placement of the cutoff at the step boundary,
not small-angle damping.

All statements use the library's rotation `rot` and its entrywise Pauli model `toMatrix`. That
these are the matrix exponential and a phase times the Kronecker product of Pauli matrices is
proved separately, in `RotationExp` and `Pauli/Tensor`.

## Main results

* `first_rotation`, `second_rotation`: the two conjugations, `P ↦ Q` and `Q ↦ Q`.
* `traj_two`: the untruncated two-rotation trajectory ends at `Q`.
* `interior_highNorm`, `boundary_eq_zero`: the truncated trajectory carries high-weight norm one
  inside the step and is zero at the step boundary.
* `discardedStep_zero`, `discardedStep_ne_zero`, `discardedStep_pauliNorm`: the first discarded
  operator is `Q`, it is nonzero, and its Pauli norm is one.
-/


-- @@ L39-39 verbatim
@[expose] public section


-- @@ L41-41 verbatim
namespace Lean4LPD.DiscardWitness


-- @@ L43-43 verbatim
open Finset PauliString


-- @@ L45-46 verbatim
/-- The Hermitian two-qubit generator `XX`, defined in the entrywise Pauli model. -/
def G : PauliString 2 := ⟨![1, 1], ![0, 0], 0⟩


-- @@ L48-49 verbatim
/-- The nonzero weight-one input `ZI`. -/
def P : PauliString 2 := ⟨![0, 0], ![1, 0], 0⟩


-- @@ L51-52 verbatim
/-- The weight-two partner `YX` that the first rotation creates. -/
def Q : PauliString 2 := ⟨![1, 1], ![1, 0], 1⟩


-- @@ L54-55 verbatim
/-- Concrete regression data for `apd:eq:step_component`: `G` is Hermitian. -/
theorem isSelfAdjoint_G : IsSelfAdjoint G := isSelfAdjoint_iff_phase.2 (by decide)


-- @@ L57-58 verbatim
/-- Concrete regression data for `apd:eq:step_component`: the input is Hermitian. -/
theorem isSelfAdjoint_P : IsSelfAdjoint P := isSelfAdjoint_iff_phase.2 (by decide)


-- @@ L60-61 verbatim
/-- Concrete regression data for `apd:eq:step_component`: the new component is Hermitian. -/
theorem isSelfAdjoint_Q : IsSelfAdjoint Q := isSelfAdjoint_iff_phase.2 (by decide)


-- @@ L63-65 verbatim
/-- Concrete regression data for `apd:eq:step_component`: `n = k_h = 2`, so the generator
is not one-local. -/
theorem weight_G : weight G = 2 := by decide


-- @@ L67-68 verbatim
/-- Concrete regression data for `apd:eq:step_component`: `k_o = 1 < n = 2`. -/
theorem weight_P : weight P = 1 := by decide


-- @@ L70-72 verbatim
/-- Concrete regression data for `apd:eq:step_component`: the created Pauli lies strictly
above `w* = 1`. -/
theorem weight_Q : weight Q = 2 := by decide


-- @@ L74-76 verbatim
/-- Concrete regression helper for `apd:eq:step_component`: the input uses the canonical
Hermitian representative. -/
theorem herm_P : herm (cls P) = P := by decide


-- @@ L78-80 verbatim
/-- Concrete regression helper for `apd:eq:step_component`: the created Pauli uses the canonical
Hermitian representative. -/
theorem herm_Q : herm (cls Q) = Q := by decide


-- @@ L82-84 verbatim
/-- Concrete regression helper for `apd:eq:step_component`: the first generator anticommutes
with the input. -/
theorem sympForm_G_P : sympForm G P = 1 := by decide


-- @@ L86-88 verbatim
/-- Concrete regression helper for `apd:eq:step_component`: the first rotation's Hermitian
partner is exactly `Q`. -/
theorem phaseMul_G_P : phaseMul 1 (G * P) = Q := by decide


-- @@ L90-91 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the input is nonzero. -/
theorem input_ne_zero : toMatrix P ≠ 0 := toMatrix_ne_zero P


-- @@ L93-97 verbatim
/-- Concrete regression example for `apd:eq:step_component`: input locality is genuinely
`k_o = 1`, not `k_o = n`. -/
theorem input_local (p : PauliIndex 2) (hp : 1 < wt p) : coeff (toMatrix P) p = 0 := by
  rw [← herm_P]
  exact coeff_toMatrix_herm_eq_zero (by simpa [weight_P] using hp)


-- @@ L99-101 verbatim
/-- Concrete regression example for `apd:eq:step_component`: no high-weight mass is present
initially; the later discarded mass must be produced by the rotation. -/
theorem input_highNorm : highNorm 1 (toMatrix P) = 0 := highNorm_eq_zero 1 input_local


-- @@ L103-110 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the first rotation creates
exactly one unit-amplitude weight-two Pauli, not a merely reachable branch. -/
theorem first_rotation :
    rot (toMatrix G) (Real.pi / 2) * toMatrix P * rot (toMatrix G) (-(Real.pi / 2))
      = toMatrix Q := by
  rw [pauli_rotation_branch_anticommute_hermitian isSelfAdjoint_G sympForm_G_P,
    Real.cos_pi_div_two, Real.sin_pi_div_two, phaseMul_G_P]
  simp


-- @@ L112-116 verbatim
/-- Concrete regression example for `apd:eq:step_component`: a genuine second rotation
preserves the high-weight component until the step boundary. -/
theorem second_rotation (θ : ℝ) :
    rot (toMatrix Q) θ * toMatrix Q * rot (toMatrix Q) (-θ) = toMatrix Q :=
  pauli_rotation_branch_commute isSelfAdjoint_Q (by decide) θ


-- @@ L118-121 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the high-weight sector at the
chosen cutoff is nonempty. -/
theorem highSet_nonempty : (highSet 2 1).Nonempty :=
  ⟨cls Q, mem_highSet.2 (by simp [weight_Q])⟩


-- @@ L123-129 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the retained set is a proper
subset of all Pauli classes, since it excludes the class of `Q`. -/
theorem cutoff_ne_univ : (highSet 2 1)ᶜ ≠ univ := by
  intro h
  have hmem : cls Q ∈ (highSet 2 1)ᶜ := by rw [h]; exact mem_univ _
  have hhigh : cls Q ∈ highSet 2 1 := mem_highSet.2 (by simp [weight_Q])
  exact (Finset.mem_compl.1 hmem) hhigh


-- @@ L131-140 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the cutoff removes the whole
new component, by its coefficients, not by an assumed operator identity. -/
theorem cutoff_Q : truncOp (highSet 2 1)ᶜ (toMatrix Q) = 0 := by
  rw [truncOp]
  refine Finset.sum_eq_zero fun p hp => ?_
  have hpq : p ≠ cls Q := by
    intro h
    subst p
    exact (Finset.mem_compl.1 hp) (mem_highSet.2 (by simp [weight_Q]))
  rw [← herm_Q, coeff_toMatrix_herm, ite_eq_right hpq, zero_smul]


-- @@ L142-146 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the discarded operator is `Q`.
This is the subtraction defining the paper's `Õ^{(d)}_{≥w*+1}`, specialized to the evolved
witness. -/
theorem discarded_eq_Q : toMatrix Q - truncOp (highSet 2 1)ᶜ (toMatrix Q) = toMatrix Q := by
  rw [cutoff_Q, sub_zero]


-- @@ L148-152 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the discarded operator is
provably nonzero. -/
theorem discarded_ne_zero : toMatrix Q - truncOp (highSet 2 1)ᶜ (toMatrix Q) ≠ 0 := by
  rw [discarded_eq_Q]
  exact toMatrix_ne_zero Q


-- @@ L154-158 verbatim
/-- Concrete regression helper for `apd:thm:triangle`: the normalized Pauli norm of the input
is exactly one. -/
theorem input_pauliNorm : pauliNorm (toMatrix P) = 1 := by
  rw [pauliNorm, ← sum_norm_coeff_sq, ← herm_P]
  simp [coeff_toMatrix_herm, apply_ite]


-- @@ L160-164 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the produced Pauli has exact
normalized norm one. -/
theorem Q_pauliNorm : pauliNorm (toMatrix Q) = 1 := by
  rw [pauliNorm, ← sum_norm_coeff_sq, ← herm_Q]
  simp [coeff_toMatrix_herm, apply_ite]


-- @@ L166-170 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the discarded norm, the scalar used
in the triangle bound's summand, is exactly one. -/
theorem discarded_pauliNorm :
    pauliNorm (toMatrix Q - truncOp (highSet 2 1)ᶜ (toMatrix Q)) = 1 := by
  rw [discarded_eq_Q, Q_pauliNorm]


-- @@ L172-178 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the high-weight scalar before
the cutoff is also exactly one. -/
theorem Q_highNorm : highNorm 1 (toMatrix Q) = 1 := by
  have hsq : highNorm 1 (toMatrix Q) ^ 2 = 1 := by
    rw [highNorm, norm_restr_sq, ← herm_Q]
    simp [coeff_toMatrix_herm, apply_ite, weight_Q]
  nlinarith [highNorm_nonneg 1 (toMatrix Q)]


-- @@ L180-182 verbatim
/-- The two-generator period: first `XX`, then `YX`. Both are genuine weight-two Hermitian
strings. `YX` commutes with the evolved observable `Q`, not with the first generator `XX`. -/
def Gs (g : ℕ) : PauliString 2 := if g % 2 = 0 then G else Q


-- @@ L184-185 verbatim
/-- Both rotations use conjugation angle `π / 2`; no zero-angle padding is used. -/
noncomputable def angles (_ : ℕ) : ℝ := Real.pi / 2


-- @@ L187-192 verbatim
/-- Concrete regression data for `apd:eq:step_component`: every generator is Hermitian. -/
theorem generators_selfAdjoint (g : ℕ) : IsSelfAdjoint (Gs g) := by
  unfold Gs
  split
  · exact isSelfAdjoint_G
  · exact isSelfAdjoint_Q


-- @@ L194-200 verbatim
/-- Concrete regression data for `apd:eq:step_component`: every generator has exactly
`k_h = 2`, rather than only a degenerate upper bound. -/
theorem generators_weight (g : ℕ) : weight (Gs g) = 2 := by
  unfold Gs
  split
  · exact weight_G
  · exact weight_Q


-- @@ L202-206 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the first rotation creates
weight-two mass in the actual recursive, untruncated trajectory. -/
theorem traj_one : traj Gs angles (toMatrix P) 1 = toMatrix Q := by
  rw [traj_succ, traj_zero]
  simpa [Gs, angles] using first_rotation


-- @@ L208-212 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the two-rotation evolution
still contains exactly `Q` immediately before its end-of-step cutoff. -/
theorem traj_two : traj Gs angles (toMatrix P) 2 = toMatrix Q := by
  rw [traj_succ, traj_one]
  simpa [Gs, angles] using second_rotation (Real.pi / 2)


-- @@ L214-217 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the first rotation of the length-two
step is not followed by a cutoff. -/
theorem schedule_zero : trotterSchedule (n := 2) 2 1 0 = univ := by
  simp [trotterSchedule]


-- @@ L219-222 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the second rotation is followed by
the genuine weight-one cutoff, at the end of the step. -/
theorem schedule_one : trotterSchedule (n := 2) 2 1 1 = (highSet 2 1)ᶜ := by
  simp [trotterSchedule]


-- @@ L224-227 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the independent full-step
recurrence removes the newly generated weight-two observable at the first step boundary. -/
theorem step_one : trotterStepTraj Gs angles 2 1 (toMatrix P) 1 = 0 := by
  rw [trotterStepTraj_succ, trotterStepTraj_zero, traj_two, cutoff_Q]


-- @@ L229-234 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the rotation-indexed trajectory still
contains `Q` inside the step, because the cutoff acts at the step boundary and not after every
rotation. -/
theorem interior_eq_Q : trotterTraj Gs angles 2 1 (toMatrix P) 1 = toMatrix Q := by
  simpa only [Nat.zero_mul, Nat.zero_add, trotterTraj_zero, traj_one] using
    trotterTraj_within_step Gs angles 2 1 (toMatrix P) 0 1 (by norm_num)


-- @@ L236-239 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the interior high-weight mass is
exactly one. This excludes a vacuous zero-sector witness. -/
theorem interior_highNorm : highNorm 1 (trotterTraj Gs angles 2 1 (toMatrix P) 1) = 1 := by
  rw [interior_eq_Q, Q_highNorm]


-- @@ L241-245 verbatim
/-- Concrete regression example for `apd:eq:step_component`: after the second rotation,
the rotation-indexed execution agrees with the independently computed step cutoff. -/
theorem boundary_eq_zero : trotterTraj Gs angles 2 1 (toMatrix P) 2 = 0 := by
  simpa only [Nat.one_mul, step_one] using
    trotterTraj_at_boundary Gs angles 2 1 (toMatrix P) 1 (by norm_num)


-- @@ L247-253 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the kept high-weight mass is
zero at the boundary, in contrast to the positive mass discarded at that same boundary. -/
theorem boundary_highNorm : highNorm 1 (trotterTraj Gs angles 2 1 (toMatrix P) 2) = 0 := by
  have hb := trotterTraj_at_boundary Gs angles 2 1 (toMatrix P) 1 (by norm_num)
  rw [Nat.one_mul] at hb
  rw [hb]
  exact highNorm_trotterStepTraj_succ Gs angles 2 1 (toMatrix P) 0


-- @@ L255-258 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the named discarded-step
operator `X₁`, not only an independently written difference, is exactly `Q`. -/
theorem discardedStep_zero : discardedStep Gs angles 2 1 (toMatrix P) 0 = toMatrix Q := by
  rw [discardedStep, trotterStepTraj_zero, step_one, traj_two, sub_zero]


-- @@ L260-264 verbatim
/-- Concrete regression example for `apd:eq:step_component`: the algorithm's first discarded
operator is provably nonzero. -/
theorem discardedStep_ne_zero : discardedStep Gs angles 2 1 (toMatrix P) 0 ≠ 0 := by
  rw [discardedStep_zero]
  exact toMatrix_ne_zero Q


-- @@ L266-269 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the generic discarded-operator norm
bridge computes the first error summand as exactly one. -/
theorem discardedStep_pauliNorm : pauliNorm (discardedStep Gs angles 2 1 (toMatrix P) 0) = 1 := by
  rw [pauliNorm_discardedStep, trotterStepTraj_zero, traj_two, Q_highNorm]


-- @@ L271-276 verbatim
/-- Concrete regression example for `apd:thm:triangle`: the first discarded norm is strictly
positive, unlike the high-weight norm of the retained boundary state. -/
theorem discardedStep_pauliNorm_pos :
    0 < pauliNorm (discardedStep Gs angles 2 1 (toMatrix P) 0) := by
  rw [discardedStep_pauliNorm]
  norm_num


-- @@ L278-278 verbatim
end Lean4LPD.DiscardWitness
