/-
Copyright (c) 2025 Yuyang Zhao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yuyang Zhao
-/
module

public import LeanPool.MisereGames.Player
public import Mathlib.Logic.Small.Defs


-- @@ L11-13 verbatim
/-!
Misere combinatorial games.
-/


-- @@ L15-15 verbatim
namespace MisereGames


-- @@ L17-17 verbatim
public section


-- @@ L19-19 verbatim
universe u


-- @@ L21-29 verbatim
/--
Type class for the `ofSets` operation. Used to implement the `!{st}` and `!{s |
t}` syntax.
-/
class OfSets (α : Type (u + 1)) (Valid : outParam ((Player → Set α) → Prop)) where
  /--
  Construct a combinatorial game from its Left and Right option sets.
  -/
  ofSets (st : Player → Set α) (h : Valid st) [Small.{u} (st .left)] [Small.{u} (st .right)] : α

-- @@ L30-30 verbatim
export OfSets (ofSets)


-- @@ L32-33 verbatim
@[inherit_doc OfSets.ofSets]
macro "!{" st:term "}'" h:term:max : term => `(OfSets.ofSets $st $h)


-- @@ L35-36 expanded
@[inherit_doc OfSets.ofSets] macro "!{" s:term " | " t:term "}'" h:term:max : term =>
  `(OfSets.ofSets (Player.cases $s $t) $h)


-- @@ L38-47 verbatim
/-- Discharge validity side conditions generated by the `!{...}` notation. -/
macro (name := ofSetsTactic) "of_sets_tactic" : tactic =>
  `(tactic| first
    | done
    | trivial
    | assumption
    | aesop
    | fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
where `h` is a proof that sets are valid"
   )


-- @@ L49-50 expanded
@[inherit_doc OfSets.ofSets] macro:max "!{" st:term "}" : term =>
  `(OfSets.ofSets $st
      (by
        first
        | done
        | trivial
        | assumption
        | aesop
        |
          fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
            where `h` is a proof that sets are valid"))


-- @@ L52-53 expanded
@[inherit_doc OfSets.ofSets] macro:max "!{" s:term " | " t:term "}" : term =>
  `(OfSets.ofSets (Player.cases $s $t)
      (by
        first
        | done
        | trivial
        | assumption
        | aesop
        |
          fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
            where `h` is a proof that sets are valid"))


-- @@ L55-55 verbatim
recommended_spelling "ofSets" for "!{st}'h" in [ofSets, «term!{_}'_»]

-- @@ L56-56 verbatim
recommended_spelling "ofSets" for "!{s | t}'h" in [ofSets, «term!{_|_}'_»]

-- @@ L57-57 verbatim
recommended_spelling "ofSets" for "!{st}" in [ofSets, «term!{_}»]

-- @@ L58-58 verbatim
recommended_spelling "ofSets" for "!{s | t}" in [ofSets, «term!{_|_}»]


-- @@ L60-60 verbatim
open Lean PrettyPrinter Delaborator SubExpr


-- @@ L62-75 expanded
/-- Delaborator for the `!{st}` and `!{s | t}` notation. -/
@[app_delab OfSets.ofSets]
meta def delabOfSets : Delab := do
  let e ← getExpr
  guard <| e.isAppOfArity' ``OfSets.ofSets 7
  withNaryArg 3 do
      let e ← getExpr
      if e.isAppOfArity' ``Player.cases 3 then 
        let s ← withNaryArg 1 delab
        let t ← withNaryArg 2 delab
        `(OfSets.ofSets (Player.cases $s $t)
              (by
                first
                | done
                | trivial
                | assumption
                | aesop
                |
                  fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                    where `h` is a proof that sets are valid"))
      else
        let st ← delab
        `(OfSets.ofSets $st
              (by
                first
                | done
                | trivial
                | assumption
                | aesop
                |
                  fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
                    where `h` is a proof that sets are valid"))


-- @@ L77-80 expanded
theorem ofSets_eq_ofSets_cases {α} {Valid : (Player → Set α) → Prop} [OfSets α Valid]
    (st : Player → Set α) (h : Valid st) [Small (st .left)] [Small (st .right)] :
    OfSets.ofSets st
        (by
          first
          | done
          | trivial
          | assumption
          | aesop
          |
            fail "failed to prove sets are valid, try to use `!{st}'h` notation instead, \
              where `h` is a proof that sets are valid") =
      OfSets.ofSets (Player.cases (st .left) (st .right)) (by convert h; aesop) :=
  by congr; ext1 p; cases p <;> rfl


-- @@ L82-82 verbatim
end


-- @@ L84-84 verbatim
end MisereGames
