/-
Copyright (c) 2026 Kalle Kytölä. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kalle Kytölä
-/
module

public import Mathlib.LinearAlgebra.Quotient.Basic
public import Mathlib.RingTheory.Ideal.Quotient.Defs
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.NormNum.Abs
import Mathlib.Tactic.NormNum.DivMod
import Mathlib.Tactic.NormNum.OfScientific
import Mathlib.Tactic.NormNum.Pow


-- @@ L17-53 verbatim
/-!
# Verma modules over algebras

This file defines a generalization of the notion of Verma modules used in Lie algebra
representation theory.

## Main definitions

* `vermaIdeal`: The left ideal in a `𝕜`-algebra `A` generated by elemements of the form `aᵢ - ηᵢ`,
  for some `aᵢ ∈ A` and `ηᵢ ∈ 𝕜`.
* `VermaModule`: The generalized Verma module for a `𝕜`-algebra `A`, defined as the quotient
  `A / vermaIdeal η`.
* `VermaModule.hwVec`: The "highest weight vector" of the Verma module.
* `VermaModule.universalMap`: The universal property of the Verma module:
  Given another module `M` over `A` and a "target" vector `hwv ∈ M` satisfying `aᵢ • hwv = ηᵢ • hwv`
  for all `i`, one obtains an `A`-module map from the Verma module to `M` uniquely specified by the
  requirement `hwVec η ↦ hwv`.

## Main statements

* `VermaModule.hwVec_cyclic`: The Verma module is generated by its highest weight vector.
* `VermaModule.range_universalMap_eq_span`: The map guaranteed by the universal property
  of the Verma module is surjective onto the submodule generated by the "target" vector.

## Implementation notes

The generalized Verma module for a `𝕜`-algebra `A` is defined as a quotient of `A` by a left ideal
generated by elemements of the form `aᵢ - ηᵢ`, for some `aᵢ ∈ A` and `ηᵢ ∈ 𝕜`. In the file
`LieVerma.lean` this is specialized to the most common case of Verma modules of Lie algebras
with a triangular decomposition. The generalized version applies beyond that case, e.g., with
Clifford algebras, it allows to construct fermionic Fock spaces.

## Tags

Verma module

-/


-- @@ L55-55 verbatim
@[expose] public section


-- @@ L57-57 verbatim
namespace VirasoroProject




-- @@ L61-61 verbatim
section canonical_map_from_a_ring_to_a_submodule_generated_by_a_vector


-- @@ L63-63 verbatim
variable (R : Type*) [Ring R] {M : Type*} [AddCommGroup M] [Module R M]


-- @@ L65-70 verbatim
/-- A surjective module map from a ring to the submodule generated by a given vector. -/
def _root_.VirasoroProject.Ring.smulVectorₗ (m : M) :
    R →ₗ[R] M where
  toFun a := a • m
  map_add' a₁ a₂ := by simp [add_smul]
  map_smul' a₁ a₂ := by simp [mul_smul]


-- @@ L72-74 verbatim
@[simp] lemma _root_.VirasoroProject.Ring.smulVectorₗ_one (m : M) :
    Ring.smulVectorₗ R m 1 = m := by
  simp [Ring.smulVectorₗ]


-- @@ L76-82 verbatim
lemma _root_.VirasoroProject.Ring.range_smulVectorₗ_eq_span (m : M) :
    LinearMap.range (Ring.smulVectorₗ R m) = Submodule.span R {m} := by
  ext v
  rw [show v ∈ Submodule.span R {m} ↔ v ∈ (Submodule.span R {m} : Set M) from Eq.to_iff rfl,
    Submodule.span_singleton_eq_range R m]
  simp only [LinearMap.mem_range, Set.mem_range]
  rfl


-- @@ L84-84 verbatim
end canonical_map_from_a_ring_to_a_submodule_generated_by_a_vector




-- @@ L88-88 verbatim
section cyclic_vectors


-- @@ L90-93 verbatim
/-- The submodule spanned by the unit `1` of a ring is the whole ring. -/
lemma _root_.VirasoroProject.one_cyclic {R : Type*} [Semiring R] :
    Submodule.span R {(1 : R)} = ⊤ :=
  (Submodule.span_singleton_eq_top_iff R 1).mpr fun a ↦ ⟨a, by simp⟩


-- @@ L95-106 verbatim
/-- A surjective linear map maps any cyclic vector (a vector which generates the whole
module) to a cyclic vector. -/
lemma _root_.VirasoroProject.LinearMap.apply_cyclic_of_cyclic_of_surjective {R : Type*} [Semiring R]
    {M₁ M₂ : Type*} [AddCommGroup M₁] [AddCommGroup M₂] [Module R M₁] [Module R M₂]
    {f : M₁ →ₗ[R] M₂} (f_surj : LinearMap.range f = ⊤)
    (m : M₁) (cyclic : Submodule.span R {m} = ⊤) :
    Submodule.span R {f m} = ⊤ := by
  rw [Submodule.span_singleton_eq_top_iff] at *
  intro m₂
  obtain ⟨m₁, hm⟩ : ∃ m₁, f m₁ = m₂ := LinearMap.range_eq_top.mp f_surj m₂
  obtain ⟨a, ha⟩ := cyclic m₁
  refine ⟨a, by rw [← map_smul, ha, hm]⟩


-- @@ L108-108 verbatim
end cyclic_vectors




-- @@ L112-112 verbatim
section generalized_Verma_module


-- @@ L114-114 verbatim
variable {𝕜 A : Type*} [CommRing 𝕜] [Ring A] [Algebra 𝕜 A]

-- @@ L115-115 verbatim
variable {ι : Type*}


-- @@ L117-122 verbatim
/-- The left ideal used in the construction of a (generalized) Verma module for an algebra `A`:
`η : ι → A × 𝕜` is an indexed collection of algebra elements and scalars by which they should act
on the "highest weight vector". -/
def _root_.VirasoroProject.vermaIdeal (η : ι → A × 𝕜) :
    Submodule A A :=
  Submodule.span A (Set.range <| fun (i : ι) ↦ (η i).1 - algebraMap 𝕜 A (η i).2)


-- @@ L124-128 verbatim
/-- The (generalied) Verma module of an algebra `A`:
`η : ι → A × 𝕜` is an indexed collection of algebra elements and scalars by which they should act
on the "highest weight vector". -/
def _root_.VirasoroProject.VermaModule (η : ι → A × 𝕜) :=
  A ⧸ vermaIdeal η


-- @@ L130-133 verbatim
/-- The highest weight vector in a (generalized) Verma module. -/
def _root_.VirasoroProject.VermaModule.hwVec (η : ι → A × 𝕜) :
    VermaModule η :=
  Submodule.Quotient.mk 1


-- @@ L135-137 verbatim
instance (η : ι → A × 𝕜) :
    AddCommGroup (VermaModule η) :=
  Submodule.Quotient.addCommGroup _


-- @@ L139-141 verbatim
instance (η : ι → A × 𝕜) :
    Module A (VermaModule η) :=
  Submodule.Quotient.module _


-- @@ L143-146 verbatim
/-- The highest weight vector in a Verma module is cyclic. -/
lemma _root_.VirasoroProject.VermaModule.hwVec_cyclic (η : ι → A × 𝕜) :
    Submodule.span A {VermaModule.hwVec η} = ⊤ :=
  LinearMap.apply_cyclic_of_cyclic_of_surjective (Submodule.range_mkQ _) 1 one_cyclic


-- @@ L148-155 verbatim
/-- The defining property of the highest weight vector in a Verma module. -/
lemma _root_.VirasoroProject.VermaModule.apply_hwVec_eq (η : ι → A × 𝕜) (i : ι) :
    (η i).1 • VermaModule.hwVec η = (algebraMap 𝕜 A (η i).2) • VermaModule.hwVec η := by
  change Submodule.Quotient.mk ((η i).1 • (1 : A)) =
    Submodule.Quotient.mk ((algebraMap 𝕜 A (η i).2) • (1 : A))
  rw [← sub_eq_zero, ← Submodule.Quotient.mk_sub]
  apply (Submodule.Quotient.mk_eq_zero ..).mpr
  exact Submodule.mem_span_of_mem (by simp)


-- @@ L157-157 verbatim
variable {M : Type*} [AddCommGroup M] [Module A M]


-- @@ L159-165 verbatim
lemma _root_.VirasoroProject.vermaIdeal_le_ker_smulVectorₗ (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    vermaIdeal η ≤ LinearMap.ker (Ring.smulVectorₗ A hwv) := by
  simp only [vermaIdeal, Submodule.span_le]
  intro a ⟨i, a_eq⟩
  simp only [← a_eq, SetLike.mem_coe, LinearMap.mem_ker, map_sub, sub_eq_zero]
  exact hwv_prop i


-- @@ L167-171 verbatim
/-- The map guaranteed by the universal property of a Verma module. -/
def _root_.VirasoroProject.VermaModule.universalMap (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    VermaModule η →ₗ[A] M :=
  Submodule.liftQ (vermaIdeal η) (Ring.smulVectorₗ A hwv) (vermaIdeal_le_ker_smulVectorₗ _ hwv_prop)


-- @@ L173-180 verbatim
/-- The image of the highest weight vector of a Verma module under the map guaranteed by the
universal property is the assigned highest weight vector in the image module. -/
@[simp] lemma _root_.VirasoroProject.VermaModule.universalMap_hwVec (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    VermaModule.universalMap η hwv_prop (VermaModule.hwVec η) = hwv := by
  rw [show VermaModule.universalMap η hwv_prop (VermaModule.hwVec η)
        = Ring.smulVectorₗ A hwv 1 from
      Submodule.liftQ_apply (vermaIdeal η) (Ring.smulVectorₗ A hwv) 1, Ring.smulVectorₗ_one]


-- @@ L182-189 verbatim
/-- The range of the map guaranteed by the universal property of a Verma module is the submodule
generated by the assigned highest weight vector in the image module. -/
lemma _root_.VirasoroProject.VermaModule.range_universalMap_eq_span (η : ι → A × 𝕜)
    {hwv : M} (hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv) :
    LinearMap.range (VermaModule.universalMap η hwv_prop) = Submodule.span A {hwv} := by
  have key := VermaModule.hwVec_cyclic η ▸
    Submodule.map_top (VermaModule.universalMap η hwv_prop)
  simp [← key, Submodule.map_span]


-- @@ L191-191 verbatim
end generalized_Verma_module



-- @@ L194-194 verbatim
section IsVerma


-- @@ L196-196 verbatim
variable {𝕜 A : Type*} [CommRing 𝕜] [Ring A] [Algebra 𝕜 A]

-- @@ L197-197 verbatim
variable {ι : Type*}


-- @@ L199-199 verbatim
universe u


-- @@ L201-207 verbatim
/-- The characteristic predicate of a Verma module. -/
structure _root_.VirasoroProject.IsVermaModule
    (η : ι → A × 𝕜) (M : Type u) (hwv : M) [AddCommGroup M] [Module A M] where
  hwv_prop : ∀ i, (η i).1 • hwv = algebraMap 𝕜 A (η i).2 • hwv
  universal : ∀ (V : Type u) [AddCommGroup V] [Module A V] (v : V)
                (_ : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v),
                ∃! (φ : M →ₗ[A] V), φ hwv = v


-- @@ L209-216 verbatim
/-- The universal map from a module satisfying the characteristic predicate of a Verma module. -/
noncomputable def _root_.VirasoroProject.IsVermaModule.universalMap
    {η : ι → A × 𝕜} {M : Type u} {hwv : M}
    [AddCommGroup M] [Module A M] (h : IsVermaModule η M hwv)
    {V : Type u} [AddCommGroup V] [Module A V] {v : V}
    (hv : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v) :
    M →ₗ[A] V :=
  (h.universal V v hv).choose


-- @@ L218-225 verbatim
/-- The defining property of a universal map from a module satisfying the characteristic predicate
of a Verma module. -/
@[simp] lemma _root_.VirasoroProject.IsVermaModule.universalMap_hwv
    {η : ι → A × 𝕜} {M : Type u} {hwv : M}
    [AddCommGroup M] [Module A M] (h : IsVermaModule η M hwv) {V : Type u}
    [AddCommGroup V] [Module A V] {v : V} (hv : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v) :
    h.universalMap hv hwv = v :=
  (h.universal V v hv).choose_spec.1


-- @@ L227-236 verbatim
/-- The uniqueness of the universal map from a module satisfying the characteristic predicate of
a Verma module. -/
lemma _root_.VirasoroProject.IsVermaModule.universalMap_unique
    {η : ι → A × 𝕜} {M : Type u} {hwv : M}
    [AddCommGroup M] [Module A M] (h : IsVermaModule η M hwv) {V : Type u}
    [AddCommGroup V] [Module A V] {v : V}
    (hv : ∀ i, (η i).1 • v = algebraMap 𝕜 A (η i).2 • v)
    {ψ : M →ₗ[A] V} (hψ : ψ hwv = v) :
    ψ = h.universalMap hv :=
  (h.universal V v hv).choose_spec.2 ψ hψ


-- @@ L238-249 verbatim
lemma _root_.VirasoroProject.VermaModule.isVermaModule (η : ι → A × 𝕜) :
    IsVermaModule η (VermaModule η) (VermaModule.hwVec η) := by
  refine ⟨fun i ↦ VermaModule.apply_hwVec_eq η i, ?_⟩
  intro V _ _ v hv
  use VermaModule.universalMap η hv
  refine ⟨VermaModule.universalMap_hwVec η hv, ?_⟩
  intro ψ hψ
  ext u
  obtain ⟨a, hau⟩ : ∃ (a : A), a • VermaModule.hwVec η = u := by
    have key := VermaModule.hwVec_cyclic η ▸ Submodule.mem_top (R := A) (x := u)
    rwa [Submodule.mem_span_singleton] at key
  simp [← hau, hψ]


-- @@ L251-272 verbatim
/-- Uniqueness up to isomorphism of a Verma module, phrased as the construction of an
isomorphism between two modules that satisfy the characteristic predicate `IsVermaModule`. -/
noncomputable def _root_.VirasoroProject.IsVermaModule.equivOfIsVermaModule
    (η : ι → A × 𝕜) (M₁ M₂ : Type u)
    (hwv₁ : M₁) (hwv₂ : M₂)
    [AddCommGroup M₁] [Module A M₁] [AddCommGroup M₂] [Module A M₂]
    (h₁ : IsVermaModule η M₁ hwv₁) (h₂ : IsVermaModule η M₂ hwv₂) :
    M₁ ≃ₗ[A] M₂ where
  toFun := h₁.universalMap h₂.hwv_prop
  map_add' := LinearMap.map_add (h₁.universalMap h₂.hwv_prop)
  map_smul' := LinearMap.CompatibleSMul.map_smul (h₁.universalMap h₂.hwv_prop)
  invFun := h₂.universalMap h₁.hwv_prop
  left_inv := by
    have obs := h₁.universalMap_unique h₁.hwv_prop
                (ψ := h₂.universalMap h₁.hwv_prop ∘ₗ (h₁.universalMap h₂.hwv_prop)) (by simp)
    have obs' := h₁.universalMap_unique h₁.hwv_prop (ψ := LinearMap.id) rfl
    exact LinearMap.congr_fun (obs'.symm ▸ obs)
  right_inv := by
    have obs := h₂.universalMap_unique h₂.hwv_prop
                (ψ := h₁.universalMap h₂.hwv_prop ∘ₗ (h₂.universalMap h₁.hwv_prop)) (by simp)
    have obs' := h₂.universalMap_unique h₂.hwv_prop (ψ := LinearMap.id) rfl
    exact LinearMap.congr_fun (obs'.symm ▸ obs)


-- @@ L274-274 verbatim
end IsVerma



-- @@ L277-277 verbatim
end VirasoroProject
