/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/
module

public import LeanPool.Wallace.LocalEnumeration
public import LeanPool.Wallace.LocalFusion
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Combinatorics.Matroid.Init


-- @@ L13-19 verbatim
/-!
# The unconditional concrete local fusion

For each nonzero vector this module instantiates the generic scheduling recursion with the
prepared local blocks.  It then converts the bounded deletion at every stage into a
block-density certificate for every relevant code.  No marker sequence is used.
-/


-- @@ L21-21 verbatim
@[expose] public section


-- @@ L23-23 verbatim
open Filter Set Topology


-- @@ L25-25 verbatim
namespace Wallace

-- @@ L26-26 verbatim
namespace ConcreteFusionRun


-- @@ L28-28 verbatim
noncomputable section


-- @@ L30-30 verbatim
open TriangularPreprocess

-- @@ L31-31 verbatim
open BlockData

-- @@ L32-32 verbatim
open ConcreteData

-- @@ L33-33 verbatim
open ConcreteClosure

-- @@ L34-34 verbatim
open ConcreteLocalSetup

-- @@ L35-35 verbatim
open FiniteCombinatorics

-- @@ L36-36 verbatim
open LocalFusion


-- @@ L38-38 verbatim
/-! ## Specialization of the numerical schedule -/


-- @@ L40-41 verbatim
/-- The finite-block size schedule used by the concrete integer construction. -/
abbrev blockSize : ℕ → ℕ := FusionSchedule.blockSize


-- @@ L43-44 verbatim
theorem blockSize_pos (l : ℕ) : 0 < blockSize l :=
  FusionSchedule.blockSize_pos l


-- @@ L46-47 verbatim
/-- The bounded-independence threshold at each fusion stage. -/
abbrev independenceBound : ℕ → ℕ := FusionSchedule.stageIndependenceBound


-- @@ L49-51 verbatim
/-- The countable coordinate closure generated by `x`. -/
abbrev localCarrier (x : ContinuumFreeGroup) : Set ContinuumIndex :=
  closure blockSize blockSize_pos independenceBound x


-- @@ L53-54 verbatim
/-- The free Abelian group supported on the local coordinate closure of `x`. -/
abbrev LocalGroup (x : ContinuumFreeGroup) := localCarrier x →₀ ℤ


-- @@ L56-58 verbatim
/-- The bounded-independent block presented to each local fusion stage. -/
abbrev fresh (x : ContinuumFreeGroup) : ℕ → Finset (LocalGroup x) :=
  localActiveBlock blockSize blockSize_pos independenceBound x


-- @@ L60-63 verbatim
/-- A fixed enumeration of the countable local group. -/
abbrev enumeration (x : ContinuumFreeGroup) : ℕ → LocalGroup x :=
  countableFinsuppEnumeration (localCarrier x)
    (closure_countable blockSize blockSize_pos independenceBound x)


-- @@ L65-68 verbatim
/-- The restriction of `x` to its local coordinate closure. -/
def distinguished (x : ContinuumFreeGroup) : LocalGroup x := by
  classical
  exact Finsupp.subtypeDomain (localCarrier x) x


-- @@ L70-76 verbatim
theorem distinguished_ne_zero {x : ContinuumFreeGroup} (hx : x ≠ 0) :
    distinguished x ≠ 0 := by
  classical
  intro hzero
  apply hx
  exact (Finsupp.subtypeDomain_eq_zero_iff
    (support_subset_closure blockSize blockSize_pos independenceBound x)).mp hzero


-- @@ L78-78 verbatim
/-! ## The scheduled run -/


-- @@ L80-89 verbatim
/-- The generic recursion, instantiated with the concrete local blocks. -/
def scheduledCertificate (x : {x : ContinuumFreeGroup // x ≠ 0}) :
    ScheduledRunCertificate (fresh x.1) (distinguished x.1) :=
  Classical.choice <| exists_scheduledRunCertificate
    (fresh x.1) (enumeration x.1) (distinguished x.1)
    (distinguished_ne_zero x.2)
    (localActiveBlock_card_le blockSize blockSize_pos independenceBound x.1)
    (localActiveBlock_boundedIndependent blockSize blockSize_pos independenceBound x.1)
    (countableFinsuppEnumeration_surjective (localCarrier x.1)
      (closure_countable blockSize blockSize_pos independenceBound x.1))


-- @@ L91-94 verbatim
/-- The certified fusion run attached to a nonzero vector. -/
abbrev run (x : {x : ContinuumFreeGroup // x ≠ 0}) :
    FusionRun (LocalGroup x.1) :=
  (scheduledCertificate x).run


-- @@ L96-96 verbatim
/-! ## Deleted positions and their density estimate -/


-- @@ L98-105 verbatim
/-- Positions discarded from the block of a relevant code.  Away from that code's refined
label this definition is harmless; only labelled stages enter its density certificate. -/
def deletedPositions (x : {x : ContinuumFreeGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) (l : ℕ) :
    Finset ℕ :=
  (blockPositions blockSize blockSize_pos l).filter fun n ↦
    localDifference blockSize blockSize_pos independenceBound x.1 a n ∉
      (run x).retained l


-- @@ L107-126 verbatim
private theorem image_deletedPositions (x : {x : ContinuumFreeGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) (l : ℕ) :
    (deletedPositions x a l).image
        (localDifference blockSize blockSize_pos independenceBound x.1 a) =
      localDifferenceBlock blockSize blockSize_pos independenceBound x.1 a l \
        (run x).retained l := by
  classical
  ext g
  constructor
  · intro hg
    obtain ⟨n, hn, rfl⟩ := Finset.mem_image.mp hg
    have hn' := Finset.mem_filter.mp hn
    exact Finset.mem_sdiff.mpr
      ⟨Finset.mem_image_of_mem _ hn'.1, hn'.2⟩
  · intro hg
    have hg' := Finset.mem_sdiff.mp hg
    obtain ⟨n, hn, hng⟩ := Finset.mem_image.mp hg'.1
    subst g
    exact Finset.mem_image.mpr
      ⟨n, Finset.mem_filter.mpr ⟨hn, hg'.2⟩, rfl⟩


-- @@ L128-153 verbatim
theorem deletedPositions_card_le (x : {x : ContinuumFreeGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1)
    (l : ℕ)
    (hl : l ∈ refinedLabel blockSize blockSize_pos independenceBound x.1 a) :
    (deletedPositions x a l).card ≤ FusionSchedule.protectedBound l := by
  classical
  let f := localDifference blockSize blockSize_pos independenceBound x.1 a
  have hinj : Function.Injective f :=
    localDifference_injective blockSize blockSize_pos independenceBound x.1 a
  calc
    (deletedPositions x a l).card =
        ((deletedPositions x a l).image f).card := by
          exact (Finset.card_image_of_injective _ hinj).symm
    _ = (localDifferenceBlock blockSize blockSize_pos independenceBound x.1 a l \
          (run x).retained l).card := by
          rw [image_deletedPositions]
    _ = (fresh x.1 l \ (run x).retained l).card := by
          change (localDifferenceBlock blockSize blockSize_pos independenceBound x.1 a l \
              (run x).retained l).card =
            (localActiveBlock blockSize blockSize_pos independenceBound x.1 l \
              (run x).retained l).card
          rw [localActiveBlock_eq_of_mem blockSize blockSize_pos independenceBound x.1 l a hl]
    _ ≤ ((run x).guardSet l).card :=
      (scheduledCertificate x).deleted_card_le l
    _ ≤ FusionSchedule.protectedBound l :=
      (scheduledCertificate x).guard_card_le l


-- @@ L155-169 verbatim
theorem retainedPositions_mem_ultrafilter
    (x : {x : ContinuumFreeGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) :
    (BlockSystem.ofBlockPositions blockSize blockSize_pos).retainedBlocks
        (refinedLabel blockSize blockSize_pos independenceBound x.1 a)
        (deletedPositions x a) ∈
      ultrafilter blockSize blockSize_pos a.1 := by
  apply ultrafilter_le_density blockSize blockSize_pos a.1
  apply BlockSystem.retainedBlocks_mem_densityFilter_ofBlockPositions
      blockSize blockSize_pos (deletedPositions x a)
      FusionSchedule.protectedBound
  · exact label_diff_refinedLabel_finite
      blockSize blockSize_pos independenceBound x.1 a
  · exact deletedPositions_card_le x a
  · exact FusionSchedule.tendsto_protectedBound_div_blockSize


-- @@ L171-171 verbatim
/-! ## Concrete block certificates and the local output -/


-- @@ L173-195 verbatim
/-- The retained-block certificate associated with one relevant sequence code. -/
def codeBlocks (x : {x : ContinuumFreeGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) :
    ConcreteCodeBlocks blockSize blockSize_pos independenceBound x.1 (run x) a where
  blocks := {
    p := ultrafilter blockSize blockSize_pos a.1
    block := blockPositions blockSize blockSize_pos
    labels := refinedLabel blockSize blockSize_pos independenceBound x.1 a
    deletions := deletedPositions x a
    difference := localDifference blockSize blockSize_pos independenceBound x.1 a
    retained_mem := by
      simpa only [BlockSystem.retainedBlocks,
        BlockSystem.ofBlockPositions_block] using
        retainedPositions_mem_ultrafilter x a
    retained_in_stage := by
      intro l n hl hn
      have hnparts := Finset.mem_sdiff.mp hn
      by_contra hnot
      exact hnparts.2 (Finset.mem_filter.mpr ⟨hnparts.1, hnot⟩)
  }
  p_eq := rfl
  block_eq := fun _ ↦ rfl
  difference_eq := fun _ ↦ rfl


-- @@ L197-205 verbatim
/-- A complete local fusion certificate for a fixed nonzero vector. -/
def localRunCertificate (x : {x : ContinuumFreeGroup // x ≠ 0}) :
    LocalRunCertificate blockSize blockSize_pos independenceBound x where
  run := run x
  self_ne_zero := by
    apply (run x).limitCharacter_ne_zero_of_initial_half
    · exact (scheduledCertificate x).initial_half
    · exact (scheduledCertificate x).distinguished_protected
  codeBlocks := codeBlocks x


-- @@ L207-210 verbatim
theorem exists_localRunCertificate
    (x : {x : ContinuumFreeGroup // x ≠ 0}) :
    Nonempty (LocalRunCertificate blockSize blockSize_pos independenceBound x) :=
  ⟨localRunCertificate x⟩


-- @@ L212-217 verbatim
/-- The local character required by the transfinite extension exists for every nonzero vector. -/
theorem hasLocalSeparatingCharacters :
    GlobalAssembly.HasLocalSeparatingCharacters
      blockSize blockSize_pos independenceBound :=
  hasLocalSeparatingCharacters_of_certificates
    blockSize blockSize_pos independenceBound exists_localRunCertificate


-- @@ L219-219 verbatim
end


-- @@ L221-221 verbatim
end ConcreteFusionRun

-- @@ L222-222 verbatim
end Wallace
