/-
Copyright (c) 2026 Arnaud Mayeux. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Arnaud Mayeux
-/
module

public import LeanPool.Dilatations.Centers


-- @@ L10-16 verbatim
/-!
# Codilatations and ordinary localizations

From Arnaud Mayeux, *Dilatations of categories, via their Lean formalization*,
https://arxiv.org/abs/2608.09305, and `rndmx/DilCat` at commit
`604559654c948566675da3f7709b8ad3126bd487` (Apache-2.0).
-/


-- @@ L18-18 verbatim
@[expose] public section


-- @@ L20-20 verbatim
noncomputable section


-- @@ L22-22 verbatim
open CategoryTheory Finset

-- @@ L23-23 verbatim
open CategoryTheory.Localization.Construction


-- @@ L25-25 verbatim
universe v u v' pu pv u₁ v₁ u₂ v₂ u₃ v₃


-- @@ L27-27 verbatim
namespace CategoryTheory.Dilatations


-- @@ L29-29 verbatim
variable {C : Type u} [Category.{v} C]

-- @@ L30-30 verbatim
variable (Z : Center C)

-- @@ L31-31 verbatim
variable {D : Type u} [Category.{v'} D]

-- @@ L32-32 verbatim
variable (F : C ⥤ D)


-- @@ L34-36 verbatim
/-! ### Section 4 : Codilatations of categories

Codilatations are defined via dilatations and opposite categories, exactly as in the paper. -/

-- @@ L37-43 verbatim
/-- **Definition 2.1 (dual notion).** A cosieve from `X`: a collection of morphisms out of `X`,
stable under postcomposition. -/
structure Cosieve {C : Type u₁} [Category.{v₁} C] (X : C) where
  /-- the underlying collection of morphisms out of `X` -/
  arrows : ∀ ⦃Y⦄, (X ⟶ Y) → Prop
  /-- stability by postcomposition -/
  upward_closed : ∀ {Y Z} {f : X ⟶ Y} (_ : arrows f) (g : Y ⟶ Z), arrows (f ≫ g)


-- @@ L45-52 verbatim
/-- **Definition 2.1.** The cosieve generated by a collection `E` of morphisms out of `X`
(denoted `CoSC_E` in the paper): `f` is generated iff `f = e ≫ h` for some `e ∈ E`. -/
def Cosieve.generate {C : Type u₁} [Category.{v₁} C] {X : C} (E : ∀ ⦃Y⦄, (X ⟶ Y) → Prop) :
    Cosieve X where
  arrows Z f := ∃ (Y : C) (e : X ⟶ Y) (h : Y ⟶ Z), E e ∧ e ≫ h = f
  upward_closed := by
    rintro Y Z _ ⟨W, e, h, he, rfl⟩ k
    exact ⟨W, e, h ≫ k, he, by simp⟩


-- @@ L54-58 verbatim
/-- **Fact 4.2.** A cosieve from `X` is *the same data* as a sieve over `op X` in `Cᵒᵖ`. -/
def Cosieve.toSieveOp {C : Type u₁} [Category.{v₁} C] {X : C} (V : Cosieve X) :
    Sieve (Opposite.op X : Cᵒᵖ) where
  arrows {_} f := V.arrows f.unop
  downward_closed {_ _ _} hf g := V.upward_closed hf g.unop


-- @@ L60-64 verbatim
/-- **Fact 4.2**, converse direction. -/
def Sieve.toCosieveUnop {C : Type u₁} [Category.{v₁} C] {X : C}
    (S : Sieve (Opposite.op X : Cᵒᵖ)) : Cosieve X where
  arrows {_} f := S.arrows f.op
  upward_closed {_ _ _} hf g := S.downward_closed hf g.op


-- @@ L66-72 verbatim
/-- **Fact 4.2**, as an explicit equivalence : a cosieve from `X` *is* a sieve over `op X`. -/
def Cosieve.equivSieveOp {C : Type u₁} [Category.{v₁} C] (X : C) :
    Cosieve X ≃ Sieve (Opposite.op X : Cᵒᵖ) where
  toFun := Cosieve.toSieveOp
  invFun := Sieve.toCosieveUnop
  left_inv _ := rfl
  right_inv _ := rfl


-- @@ L74-90 verbatim
/-- **Fact 4.4.** `CoSC_E = SCᵒᵖ_E`: the cosieve generated by `E` equals (under Fact 4.2's
identification) the sieve generated by `E`'s image under `.op` in `Cᵒᵖ`. -/
theorem Cosieve.generate_toSieveOp {C : Type u₁} [Category.{v₁} C] {X : C}
    (E : ∀ ⦃Y⦄, (X ⟶ Y) → Prop) :
    (Cosieve.generate E).toSieveOp =
      Sieve.generate (fun {Y'} (g : Y' ⟶ (Opposite.op X : Cᵒᵖ)) => E g.unop) := by
  apply Sieve.ext
  intro Y f
  constructor
  · rintro ⟨W, e, h, he, heq⟩
    refine ⟨Opposite.op W, h.op, e.op, he, ?_⟩
    change h.op ≫ e.op = f
    rw [← CategoryTheory.op_comp, heq, Quiver.Hom.op_unop]
  · rintro ⟨W, h, e, he, heq⟩
    refine ⟨W.unop, e.unop, h.unop, he, ?_⟩
    change e.unop ≫ h.unop = f.unop
    rw [← CategoryTheory.unop_comp, heq]


-- @@ L92-106 verbatim
/-- A cocenter `{[Vᵢ,dᵢ]}_{i∈I}` in `C` (Definition 4.1): `dᵢ` a morphism, `Vᵢ` a cosieve from
`dom(dᵢ)`. Following Fact 4.2 (a cosieve from `X` is *the same data* as a sieve over `op X` in
`Cᵒᵖ`), `Vᵢ` is recorded directly as a `Sieve` in `Cᵒᵖ` over `op (dom dᵢ)`. -/
structure Cocenter (C : Type u) [Category.{v} C] where
  /-- Indices of the denominator morphisms and their numerator cosieves. -/
  I : Type u
  nonempty : Nonempty I
  /-- Domain of each denominator morphism. -/
  dom : I → C
  /-- Codomain of each denominator morphism. -/
  cod : I → C
  /-- Morphisms used as denominators in the dual construction. -/
  mor : ∀ i : I, dom i ⟶ cod i
  /-- Permitted numerators, stable under postcomposition. -/
  V : ∀ i : I, Sieve (C := Cᵒᵖ) (Opposite.op (dom i))


-- @@ L108-116 verbatim
/-- The center on `Cᵒᵖ` obtained by regarding `{[Vᵢ,dᵢ]}_{i∈I}` as `{[Vᵢ,(dᵢ)ᵒᵖ]}_{i∈I}`
(Fact 4.2). -/
def Cocenter.toCenterOp (co : Cocenter C) : Center Cᵒᵖ where
  I := co.I
  nonempty := co.nonempty
  dom := fun i => Opposite.op (co.cod i)
  cod := fun i => Opposite.op (co.dom i)
  mor := fun i => (co.mor i).op
  N := co.V


-- @@ L118-127 verbatim
/-- The underlying `{dᵢ}`-only center on `C`. `IsSigmaRegular`/`ImageCenterMorphismProperty` only
depend on `I`/`dom`/`cod`/`mor` (never on the sieve component), so any placeholder sieve works
here. -/
def Cocenter.toCenter (co : Cocenter C) : Center C where
  I := co.I
  nonempty := co.nonempty
  dom := co.dom
  cod := co.cod
  mor := co.mor
  N := fun _ => ⊤


-- @@ L129-131 verbatim
/-- **Definition 4.3.** The codilatation of `C` with cocenter `{[Vᵢ,dᵢ]}_{i∈I}`:
`C[{Vᵢ∘(dᵢ)⁻¹}_{i∈I}] := (Cᵒᵖ[{(dᵢ)⁻¹∘Vᵢ}_{i∈I}])ᵒᵖ`. -/
def Codila (co : Cocenter C) : Type u := (Dila (co.toCenterOp))ᵒᵖ


-- @@ L133-134 verbatim
instance instCategoryCodila (co : Cocenter C) : Category (Codila co) := by
  unfold Codila; infer_instance


-- @@ L136-152 verbatim
/-- General fact used to transport faithfulness of `.Q` across `Cᵒᵖ`: if `W.Q` is faithful, so is
`(W.op).Q`. Proved via the universal property of `(W.op).Localization` (`Prop 2.8` /
`Localization.Construction.lift`), *not* via raw combinatorics — `(W.Q).op` is faithful for free
(`.op` preserves faithfulness), it inverts `W.op` (since `.op` preserves isomorphisms), so it
factors uniquely through `(W.op).Q`, and `faithful_of_comp_faithful` finishes it. -/
lemma MorphismProperty.op_Q_faithful {D : Type u} [Category.{v} D] (W : MorphismProperty D)
    (hW : W.Q.Faithful) : W.op.Q.Faithful := by
  have := hW
  apply faithful_of_comp_faithful_gen
    W.op.Q
    (Localization.Construction.lift (W := W.op) W.Q.op
      (fun X Y f hf => by
        change IsIso (W.Q.map f.unop).op
        have : IsIso (W.Q.map f.unop) := CategoryTheory.MorphismProperty.Q_inverts W f.unop hf
        infer_instance))
  erw [Localization.Construction.fac]
  infer_instance


-- @@ L154-157 verbatim
/-- **Proposition 4.5 (i).** The canonical functor `Υ : C ⥤ Codila co`, obtained by taking the
`rightOp` of `Θ : Cᵒᵖ ⥤ Dila (co.toCenterOp)` (Proposition 3.1). -/
def Cocenter.Upsilon (co : Cocenter C) : C ⥤ Codila co :=
  (CatToDila (co.toCenterOp)).rightOp


-- @@ L159-166 verbatim
/-- **Proposition 4.5 (ii).** The canonical faithful functor
`Codila co ⥤ (Cᵒᵖ[{(dᵢ)⁻¹}])ᵒᵖ` (which identifies with `C[{dᵢ}⁻¹]`, e.g. via the explicit
description of fractions — Fact 4.4 — matching the paper's own aside). -/
instance Codila.faithful_to_loc_op (co : Cocenter C) :
    ((DilaToLoc (co.toCenterOp)).op :
      Codila co ⥤ ((CenterMorphismProperty (co.toCenterOp)).Localization)ᵒᵖ).Faithful := by
  have := Fact_2_14 (co.toCenterOp)
  infer_instance


-- @@ L168-202 verbatim
/-- `Cocenter.Upsilon`'s `ImageCenterMorphismProperty` (relative to `co.toCenter`) is exactly the
`.op` of `Θ`'s (relative to `co.toCenterOp`), matching how `Upsilon = (CatToDila
(co.toCenterOp)).rightOp` is built. -/
lemma ImageCenterMorphismProperty_toCenter_Upsilon (co : Cocenter C) :
    ImageCenterMorphismProperty co.toCenter co.Upsilon =
      (ImageCenterMorphismProperty (co.toCenterOp) (CatToDila (co.toCenterOp))).op := by
  funext X Y f
  apply propext
  constructor
  · rintro ⟨i, hi⟩
    have hX : X = co.Upsilon.obj (co.dom i) := congrArg Sigma.fst hi
    have hY : Y = co.Upsilon.obj (co.cod i) := congrArg (fun s => s.2.1) hi
    subst hX
    subst hY
    have hf : f = co.Upsilon.map (co.mor i) := by cases hi; rfl
    subst hf
    exact ⟨i, rfl⟩
  · rintro ⟨i, hi⟩
    have hX : Opposite.unop Y = (CatToDila co.toCenterOp).obj (co.toCenterOp.dom i) :=
      congrArg Sigma.fst hi
    have hY : Opposite.unop X = (CatToDila co.toCenterOp).obj (co.toCenterOp.cod i) :=
      congrArg (fun s => s.2.1) hi
    refine ⟨i, ?_⟩
    have hXeq : X = Opposite.op ((CatToDila co.toCenterOp).obj (co.toCenterOp.cod i)) := by
      rw [← hY]; exact (Opposite.op_unop X).symm
    have hYeq : Y = Opposite.op ((CatToDila co.toCenterOp).obj (co.toCenterOp.dom i)) := by
      rw [← hX]; exact (Opposite.op_unop Y).symm
    subst hXeq
    subst hYeq
    injection hi with h1 h2
    injection h2 with h3 hf
    have hfeq : f = ((CatToDila co.toCenterOp).map (co.toCenterOp.mor i)).op := by
      rw [← hf]; exact (Quiver.Hom.op_unop f).symm
    subst hfeq
    rfl


-- @@ L204-209 verbatim
/-- **Proposition 4.5 (iii).** `Υ` belongs to `Cat ^ {{dᵢ}-reg}_C` (i.e. is `{dᵢ}`-regular). -/
theorem Cocenter.Upsilon_isSigmaRegular (co : Cocenter C) :
    IsSigmaRegular co.toCenter co.Upsilon := by
  change (ImageCenterMorphismProperty co.toCenter co.Upsilon).Q.Faithful
  rw [ImageCenterMorphismProperty_toCenter_Upsilon]
  exact MorphismProperty.op_Q_faithful _ (CatToDila_isSigmaRegular (co.toCenterOp))


-- @@ L211-215 verbatim
/-- `Cocenter.Upsilon` post-composed with any `G` corresponds, on the nose after taking `.op`, to
`Θ` post-composed with `G.rightOp`. This is the key bridge letting factorizations through
`Codila co` be transported to (and from) factorizations through `Dila (co.toCenterOp)`. -/
lemma Cocenter.comp_Upsilon_op (co : Cocenter C) (G : Codila co ⥤ D) :
    (co.Upsilon ⋙ G).op = CatToDila (co.toCenterOp) ⋙ G.rightOp := rfl


-- @@ L217-247 verbatim
/-- `ImageCenterMorphismProperty` for `(co.toCenterOp, F.op)` is exactly the `.op` of
`ImageCenterMorphismProperty` for `(co.toCenter, F)`. -/
lemma ImageCenterMorphismProperty_toCenterOp_op (co : Cocenter C) (F : C ⥤ D) :
    ImageCenterMorphismProperty (co.toCenterOp) F.op =
      (ImageCenterMorphismProperty co.toCenter F).op := by
  funext X Y f
  apply propext
  constructor
  · rintro ⟨i, hi⟩
    have hX : X = Opposite.op (F.obj (co.cod i)) := congrArg Sigma.fst hi
    have hY : Y = Opposite.op (F.obj (co.dom i)) := congrArg (fun s => s.2.1) hi
    subst hX
    subst hY
    have hf : f = (F.map (co.mor i)).op := by cases hi; rfl
    subst hf
    exact ⟨i, rfl⟩
  · rintro ⟨i, hi⟩
    have hX : Opposite.unop Y = F.obj (co.dom i) := congrArg Sigma.fst hi
    have hY : Opposite.unop X = F.obj (co.cod i) := congrArg (fun s => s.2.1) hi
    refine ⟨i, ?_⟩
    have hXeq : X = Opposite.op (F.obj (co.cod i)) := by rw [← hY]
    have hYeq : Y = Opposite.op (F.obj (co.dom i)) := by rw [← hX]
    subst hXeq
    subst hYeq
    injection hi with h1 h2
    injection h2 with h3 hf
    have hf' : f.unop = F.map (co.mor i) := hf
    have hfeq : f = (F.map (co.mor i)).op := by
      rw [← hf']; exact (Quiver.Hom.op_unop f).symm
    subst hfeq
    rfl


-- @@ L249-254 verbatim
/-- If `F : C ⥤ D` is `{dᵢ}`-regular, so is `F.op : Cᵒᵖ ⥤ Dᵒᵖ` (relative to `co.toCenterOp`). -/
lemma IsSigmaRegular_toCenterOp_op (co : Cocenter C) (F : C ⥤ D)
    (hF : IsSigmaRegular co.toCenter F) : IsSigmaRegular (co.toCenterOp) F.op := by
  change (ImageCenterMorphismProperty (co.toCenterOp) F.op).Q.Faithful
  rw [ImageCenterMorphismProperty_toCenterOp_op]
  exact MorphismProperty.op_Q_faithful _ hF


-- @@ L256-293 verbatim
/-- **Proposition 4.5 (iv).** `Υ` represents the covariant functor `Cat ^ {{dᵢ}-reg}_C → Set`,
`(C --F--> D) ↦ {∗}` if `CoS ^ D_{F(Vᵢ)} ⊂ CoS ^ D_{F(dᵢ)}` for all `i`, else `∅`. -/
theorem Cocenter.represents (co : Cocenter C) (F : C ⥤ D) (hfaith : IsSigmaRegular co.toCenter F) :
    (∃! G : Codila co ⥤ D, co.Upsilon ⋙ G = F) ↔
      ∀ i : co.I, Sieve.functorPushforward F.op (co.V i) ≤
        Sieve.generate (Presieve.singleton (F.op.map (co.toCenterOp.mor i))) := by
  change (∃! G : Codila co ⥤ D, co.Upsilon ⋙ G = F) ↔
      ∀ i : co.toCenterOp.I, Sieve.functorPushforward F.op (co.toCenterOp.N i) ≤
        Sieve.generate (Presieve.singleton (F.op.map (co.toCenterOp.mor i)))
  rw [← CatToDila_represents (co.toCenterOp) F.op (IsSigmaRegular_toCenterOp_op co F hfaith)]
  constructor
  · rintro ⟨G, hG, hU⟩
    refine ⟨G.rightOp, by
      change CatToDila co.toCenterOp ⋙ G.rightOp = F.op
      rw [← Cocenter.comp_Upsilon_op, hG], ?_⟩
    intro G'' hG''
    have hop : (co.Upsilon ⋙ G''.leftOp).op = F.op := by
      erw [Cocenter.comp_Upsilon_op]
      simpa only using! hG''
    have heq : co.Upsilon ⋙ G''.leftOp = F := by
      have := congrArg Functor.unop hop
      simpa only using! this
    have := hU G''.leftOp heq
    have := congrArg Functor.rightOp this
    simpa only using! this
  · rintro ⟨G', hG', hU'⟩
    refine ⟨G'.leftOp, ?_, ?_⟩
    · have hop : (co.Upsilon ⋙ G'.leftOp).op = F.op := by
        erw [Cocenter.comp_Upsilon_op]
        simpa only using! hG'
      have := congrArg Functor.unop hop
      simpa only using! this
    · intro G'' hG''
      have hop : CatToDila (co.toCenterOp) ⋙ G''.rightOp = F.op := by
        rw [← Cocenter.comp_Upsilon_op, hG'']
      have := hU' G''.rightOp hop
      have := congrArg Functor.leftOp this
      simpa only using! this


-- @@ L295-302 verbatim
/-! ### §5.1 : Universal property of localizations, recovered from the universal property of
dilatations

By Fact 2.15, the dilatation for a center whose sieves are all the trivial one
`Nᵢ = S ^ C_{Idcod(dᵢ)} = ⊤` is the plain localization `C[{dᵢ}⁻¹]`. Given that identification, this
section shows `Dila_universal_property` (Theorem 3.10) recovers `Proposition 2.8` (the universal
property of plain localizations) as a special case : a functor inverting every `dᵢ` factors
uniquely through this dilatation. -/

-- @@ L303-307 verbatim
/-- The sieve generated by a single isomorphism is the top sieve. -/
lemma Sieve.generate_singleton_eq_top_of_isIso {D : Type*} [Category D] {X Y : D} (g : X ⟶ Y)
    [IsIso g] : Sieve.generate (Presieve.singleton g) = ⊤ := by
  refine le_antisymm le_top (fun Z f _ => ?_)
  exact ⟨X, f ≫ inv g, g, Presieve.singleton_self _, by simp⟩


-- @@ L309-318 verbatim
/-- The center built from an arbitrary indexed family of morphisms `{dᵢ}_{i∈I}`, using the
trivial choice of sieves `Nᵢ = S ^ C_{Idcod(dᵢ)} = ⊤` — matching the hypothesis of Fact 2.15. -/
def Center.ofMorphisms {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) : Center C where
  I := I
  nonempty := hI
  dom := dom
  cod := cod
  mor := mor
  N := fun _ => ⊤


-- @@ L320-345 verbatim
/-- **§5.1.** The universal property of dilatations recovers the universal property of
localizations (Proposition 2.8, matching `Fact 2.15`'s identification of this dilatation with
`C[{dᵢ}⁻¹]`): any `F : C ⥤ D` inverting every generator `dᵢ = mor i` factors uniquely through
`Dila (Center.ofMorphisms hI dom cod mor)`. -/
theorem Center.ofMorphisms_universal_property {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) (F : C ⥤ D) (hF : ∀ i, IsIso (F.map (mor i))) :
    ∃! G : Dila (Center.ofMorphisms hI dom cod mor) ⥤ D,
      CatToDila (Center.ofMorphisms hI dom cod mor) ⋙ G = F := by
  set Z := Center.ofMorphisms hI dom cod mor with hZ
  apply Dila_universal_property Z F
  · change (ImageCenterMorphismProperty Z F).Q.Faithful
    apply isoMorphismProperty_Q_faithful
    rintro X Y f ⟨i, hi⟩
    have hX : X = F.obj (Z.dom i) := congrArg Sigma.fst hi
    have hY : Y = F.obj (Z.cod i) := congrArg (fun s => s.2.1) hi
    subst hX
    subst hY
    have hf : f = F.map (Z.mor i) := by cases hi; rfl
    subst hf
    exact hF i
  · intro i
    change Sieve.functorPushforward F (⊤ : Sieve (Z.cod i)) ≤
      Sieve.generate (Presieve.singleton (F.map (Z.mor i)))
    have : IsIso (F.map (Z.mor i)) := hF i
    rw [Sieve.generate_singleton_eq_top_of_isIso (F.map (Z.mor i))]
    exact le_top


-- @@ L347-363 verbatim
/-- **Fact 2.15, isomorphism-witness.** With all sieves trivial, `Θ(dᵢ)` already has an explicit
inverse fraction inside the dilatation : `n/dᵢ` at `n := 𝟙 (cod i)` (valid since `N i = ⊤`), with
`Prop_3_3`'s epi-ness closing the other triangle identity. -/
theorem CatToDila_ofMorphisms_isIso {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) (i : I) :
    IsIso ((CatToDila (Center.ofMorphisms hI dom cod mor)).map (mor i)) := by
  set Z := Center.ofMorphisms hI dom cod mor with hZ
  set inv := fractionInDilatation Z ⟨i, ⟨cod i, ⟨𝟙 (cod i), trivial⟩⟩⟩ with hinv
  have hri : inv ≫ (CatToDila Z).map (mor i) = 𝟙 _ := by
    have h := fraction_in_dila_comp_mor Z i (cod i) (𝟙 (cod i)) trivial
    erw [Functor.map_id] at h
    exact h
  have : Mono ((CatToDila Z).map (mor i)) := (Prop_3_3 Z i).1
  have hli : (CatToDila Z).map (mor i) ≫ inv = 𝟙 _ :=
    (cancel_mono ((CatToDila Z).map (mor i))).mp (by
      erw [Category.assoc, hri, Category.comp_id])
  exact ⟨inv, hli, hri⟩


-- @@ L365-376 verbatim
theorem CatToDila_ofMorphisms_isInvertedBy {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) :
    (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).IsInvertedBy
      (CatToDila (Center.ofMorphisms hI dom cod mor)) := by
  intro X Y f hf
  rcases hf with ⟨i, hi⟩
  have hX : X = (Center.ofMorphisms hI dom cod mor).dom i := congrArg Sigma.fst hi
  have hY : Y = (Center.ofMorphisms hI dom cod mor).cod i := congrArg (fun s => s.2.1) hi
  subst hX; subst hY
  have hf' : f = (Center.ofMorphisms hI dom cod mor).mor i := by cases hi; rfl
  rw [hf']
  exact CatToDila_ofMorphisms_isIso hI dom cod mor i


-- @@ L378-386 verbatim
/-- The inverse to `DilaToLoc (Center.ofMorphisms ...)`, built via the raw localization's own
universal property (`Localization.Construction.lift`), now that `CatToDila` inverts every
generator (`CatToDila_ofMorphisms_isInvertedBy`). -/
noncomputable def Fact215Inv {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) :
    (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Localization ⥤
      Dila (Center.ofMorphisms hI dom cod mor) :=
  Localization.Construction.lift (CatToDila (Center.ofMorphisms hI dom cod mor))
    (CatToDila_ofMorphisms_isInvertedBy hI dom cod mor)


-- @@ L388-392 verbatim
theorem Fact215Inv_fac {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) :
    (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Q ⋙
        Fact215Inv hI dom cod mor = CatToDila (Center.ofMorphisms hI dom cod mor) :=
  Localization.Construction.fac _ _


-- @@ L394-426 verbatim
/-- **Fact 2.15.** `Dila (Center.ofMorphisms hI dom cod mor)` (dilatation with all sieves
trivial) is isomorphic to the plain localization `C[{morᵢ}⁻¹]`. -/
noncomputable def localizationIso {I : Type u} (hI : Nonempty I) (dom cod : I → C)
    (mor : ∀ i, dom i ⟶ cod i) :
    Cat.of (Dila (Center.ofMorphisms hI dom cod mor)) ≅
      Cat.of (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Localization where
  hom := (DilaToLoc (Center.ofMorphisms hI dom cod mor)).toCatHom
  inv := (Fact215Inv hI dom cod mor).toCatHom
  hom_inv_id := by
    apply Cat.ext
    apply Dila_factor_unique (Center.ofMorphisms hI dom cod mor)
      (CatToDila (Center.ofMorphisms hI dom cod mor))
    · change CatToDila (Center.ofMorphisms hI dom cod mor) ⋙
          DilaToLoc (Center.ofMorphisms hI dom cod mor) ⋙ Fact215Inv hI dom cod mor =
        CatToDila (Center.ofMorphisms hI dom cod mor)
      rw [← Functor.assoc, CatToDila_comp_DilaToLoc]
      change (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Q ⋙
          Fact215Inv hI dom cod mor = CatToDila (Center.ofMorphisms hI dom cod mor)
      exact Fact215Inv_fac hI dom cod mor
    · exact Functor.comp_id _
    · exact CatToDila_isSigmaRegular (Center.ofMorphisms hI dom cod mor)
  inv_hom_id := by
    apply Cat.ext
    apply Localization.Construction.uniq
    change (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Q ⋙
        Fact215Inv hI dom cod mor ⋙ DilaToLoc (Center.ofMorphisms hI dom cod mor) =
      (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Q ⋙ 𝟭 _
    rw [← Functor.assoc, Fact215Inv_fac]
    show CatToDila (Center.ofMorphisms hI dom cod mor) ⋙
        DilaToLoc (Center.ofMorphisms hI dom cod mor) =
      (CenterMorphismProperty (Center.ofMorphisms hI dom cod mor)).Q ⋙ 𝟭 _
    rw [CatToDila_comp_DilaToLoc, Functor.comp_id]
    rfl


-- @@ L428-428 verbatim
end CategoryTheory.Dilatations
