/-
Copyright (c) 2026 Hyeon Seung-Hyeon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hyeon Seung-Hyeon
-/

-- Adapted for Lean Pool from 0stellensatz/MassFormula at 7fa41a621f724f110183904d3fd19c6730a932ad.
module

public import LeanPool.MassFormula.Defs
public import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import Mathlib.Algebra.GroupWithZero.Submonoid.CancelMulZero
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral
import Mathlib.RingTheory.Valuation.Integral


-- @@ L18-37 verbatim
/-!
# Auxiliary file: Eisenstein monogenicity—`integers L` is generated by `x`

For a root `x` of an Eisenstein polynomial over `𝒪[K]` in `SeparableClosure K`, the integral closure
of `𝒪[K]` in `K⟮x⟯` is generated by `x` itself ([Serre 1979, Chap. I, §6, Prop. 17][Serre1979]). The
proof is the classical two-step denominator chase, powered by two Mathlib lemmas:
`Algebra.discr_mul_isIntegral_mem_adjoin` clears an integral element into the adjoin after
multiplication by the discriminant of the power basis—nonzero by separability, which is free inside
`SeparableClosure K`—and `mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt` strips prime
powers, the discriminant being a unit times a power of the uniformizer in the discrete valuation
ring `𝒪[K]`. This file sits below `First.lean` and `Discriminant.lean` in the import graph: the
total-ramifiedness of `K⟮x⟯` (`isTotallyRamified_adjoin`, below) and the discriminant bound
`n - 1 ≤ d L` (`sub_one_le_d_adjoin`) are computations inside `𝒪[K][x]` made possible by this
identification.

## References

* [Serre1979] J-P. Serre, *Local fields*, Graduate Texts in Mathematics **67**, Springer, 1979.
  (The English translation of *Corps locaux*, whose numbering it keeps.)
-/


-- @@ L39-39 verbatim
@[expose] public section


-- @@ L41-41 verbatim
open ValuativeRel IntermediateField


-- @@ L43-43 verbatim
namespace MassFormula


-- @@ L45-46 verbatim
variable {K : Type*} [Field K] [ValuativeRel K] [UniformSpace K] [IsUniformAddGroup K]
  [IsNonarchimedeanLocalField K]


-- @@ L48-54 verbatim
/-! ## Instances Mathlib does not reach

Two links of the tower `𝒪[K] → L → SeparableClosure K` that instance search no longer finds on its
own: `IntermediateField.isScalarTower` wants the base to act on `K`, and `FaithfulSMul` over
`SeparableClosure K` is only reachable through `IsFractionRing 𝒪[K] K`, which is not a global
instance. Both are needed by `minpoly` and `isIntegral_algebraMap_iff` throughout this file.
-/


-- @@ L56-58 verbatim
instance instIsScalarTowerIntermediateField (L : IntermediateField K (SeparableClosure K)) :
    IsScalarTower 𝒪[K] ↥L (SeparableClosure K) :=
  IsScalarTower.of_algebraMap_eq fun _ => rfl


-- @@ L60-65 verbatim
instance : FaithfulSMul 𝒪[K] (SeparableClosure K) := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  rw [faithfulSMul_iff_algebraMap_injective,
    IsScalarTower.algebraMap_eq 𝒪[K] K (SeparableClosure K)]
  exact (algebraMap K (SeparableClosure K)).injective.comp (IsFractionRing.injective 𝒪[K] K)


-- @@ L67-90 verbatim
omit [IsUniformAddGroup K] in
/-- The constant coefficient of the Eisenstein minimal polynomial is an associate of the
uniformizer. -/
lemma associated_pi_coeff_zero {π : 𝒪[K]} {x : SeparableClosure K} (hπ : Irreducible π)
    (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Associated π ((minpoly 𝒪[K] x).coeff 0) := by
  have hn : 0 < (minpoly 𝒪[K] x).natDegree := minpoly.natDegree_pos hint
  have hdvd : π ∣ (minpoly 𝒪[K] x).coeff 0 := by
    have h1 := hei.mem hn
    rwa [Ideal.submodule_span_eq, Ideal.mem_span_singleton] at h1
  obtain ⟨c, hc⟩ := hdvd
  have hcunit : IsUnit c := by
    by_contra hcu
    apply hei.notMem
    have hcmem : c ∈ Ideal.span {π} := by
      have h1 : c ∈ IsLocalRing.maximalIdeal 𝒪[K] :=
        (IsLocalRing.mem_maximalIdeal _).mpr (mem_nonunits_iff.mpr hcu)
      rwa [hπ.maximalIdeal_eq] at h1
    rw [Ideal.mem_span_singleton] at hcmem
    obtain ⟨d, hd⟩ := hcmem
    rw [Ideal.submodule_span_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
    exact ⟨d, by rw [hc, hd]; ring⟩
  exact ⟨hcunit.unit, by rw [IsUnit.unit_spec]; exact hc.symm⟩



-- @@ L93-152 verbatim
omit [IsUniformAddGroup K] in
/-- A root of an Eisenstein polynomial is monogenic: the integral closure of `𝒪[K]` in
`K⟮x⟯` is generated by `x` itself. -/
theorem integers_eq_adjoin {π : 𝒪[K]} (hπ : Irreducible π) {x : SeparableClosure K}
    (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    integers (IntermediateField.adjoin K {x}) =
      Algebra.adjoin 𝒪[K] {IntermediateField.AdjoinSimple.gen K x} := by
  classical
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  have hKint : IsIntegral K x := hint.tower_top
  set B : PowerBasis K ↥(IntermediateField.adjoin K {x}) :=
    IntermediateField.adjoin.powerBasis hKint with hB
  have hgen : B.gen = IntermediateField.AdjoinSimple.gen K x := rfl
  have hval : algebraMap ↥(IntermediateField.adjoin K {x}) (SeparableClosure K) B.gen = x := rfl
  have hint' : IsIntegral 𝒪[K] B.gen :=
    (isIntegral_algebraMap_iff (B := SeparableClosure K)).mp hint
  have hminmap : minpoly 𝒪[K] B.gen = minpoly 𝒪[K] x :=
    (minpoly.algebraMap_eq
      (algebraMap ↥(IntermediateField.adjoin K {x}) (SeparableClosure K)).injective B.gen).symm
  refine le_antisymm (fun z hz => ?_) ?_
  · -- the integral closure is contained in the adjoin
    have : Module.Finite K ↥(IntermediateField.adjoin K {x}) := B.finite
    have hzint : IsIntegral 𝒪[K] z := hz
    have hbasis_int : ∀ i, IsIntegral 𝒪[K] (B.basis i) := by
      intro i
      rw [B.basis_eq_pow i]
      exact hint'.pow _
    have hdisc_int : IsIntegral 𝒪[K] (Algebra.discr K B.basis) :=
      Algebra.discr_isIntegral K hbasis_int
    obtain ⟨D, hD⟩ := IsIntegrallyClosed.isIntegral_iff.mp hdisc_int
    have hdiscne : Algebra.discr K B.basis ≠ 0 := Algebra.discr_not_zero_of_basis K B.basis
    have hDne : D ≠ 0 := by
      intro h0
      exact hdiscne (by rw [← hD, h0, map_zero])
    obtain ⟨m, hm⟩ := IsDiscreteValuationRing.associated_pow_irreducible hDne hπ
    obtain ⟨v, hv⟩ := hm.symm
    -- hv : π ^ m * v = D
    have h1 : Algebra.discr K B.basis • z ∈ Algebra.adjoin 𝒪[K] {B.gen} :=
      Algebra.discr_mul_isIntegral_mem_adjoin K hint' hzint
    have h2 : D • z ∈ Algebra.adjoin 𝒪[K] {B.gen} := by
      rwa [← hD, algebraMap_smul] at h1
    have h3 : π ^ m • ((v : 𝒪[K]) • z) ∈ Algebra.adjoin 𝒪[K] {B.gen} := by
      rwa [← hv, mul_smul] at h2
    have h4 : (v : 𝒪[K]) • z ∈ Algebra.adjoin 𝒪[K] {B.gen} :=
      mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
        (UniqueFactorizationMonoid.irreducible_iff_prime.mp hπ) hint'
        (hzint.smul _) h3 (by rw [hminmap]; exact hei)
    have h5 : ((v⁻¹ : 𝒪[K]ˣ) : 𝒪[K]) • ((v : 𝒪[K]) • z) ∈ Algebra.adjoin 𝒪[K] {B.gen} :=
      Subalgebra.smul_mem _ h4 _
    rw [smul_smul, ← Units.val_mul, inv_mul_cancel, Units.val_one, one_smul] at h5
    rwa [hgen] at h5
  · -- the adjoin is contained in the integral closure
    rw [Algebra.adjoin_le_iff]
    intro y hy
    rw [Set.mem_singleton_iff] at hy
    subst hy
    change IsIntegral 𝒪[K] _
    exact (isIntegral_algebraMap_iff (B := SeparableClosure K)).mp hint


-- @@ L154-163 verbatim
/-! ## Total ramifiedness of the adjoined root field

Three abstract commutative-algebra lemmas—kept over opaque rings so that unification stays
structural—followed by the concrete theorem. The route avoids constructing any valuation on
`L = K⟮x⟯`: from the Eisenstein relation, the constant coefficient satisfies `a₀ * u = -ξ ^ n` for a
unit `u = 1 + ξ * t`, so the extended maximal ideal is exactly the `n`-th power of `(ξ)`; the ideal
`(ξ)` is maximal as the kernel of the constant-coefficient-then-residue map through the monogenic
presentation of `integers L` as `𝒪[K][X]` modulo `(g)` from `integers_eq_adjoin`; and
`Ideal.ramificationIdx'_spec` turns the two power bounds into `e = n`, which is the degree.
-/


-- @@ L165-178 verbatim
/-- In any commutative ring, `1 + z * t` is a unit whenever `c * (1 + z * t) = -z ^ n`:
a maximal ideal containing it would contain `z ^ n`, hence `z`, hence `1`. -/
private lemma isUnit_one_add_of_mul_eq_neg_pow {A : Type*} [CommRing A]
    {c z t : A} {n : ℕ} (h : c * (1 + z * t) = -z ^ n) : IsUnit (1 + z * t) := by
  by_contra hu0
  obtain ⟨M, hM, huM⟩ := exists_max_ideal_of_mem_nonunits (mem_nonunits_iff.mpr hu0)
  have hzM : z ∈ M := by
    have h1 : c * (1 + z * t) ∈ M := Ideal.mul_mem_left M _ huM
    rw [h] at h1
    exact hM.isPrime.mem_of_pow_mem _ ((Ideal.neg_mem_iff M).mp h1)
  have h1 : (1 : A) ∈ M := by
    have h2 : (1 + z * t) - z * t ∈ M := Ideal.sub_mem M huM (Ideal.mul_mem_right _ M hzM)
    rwa [add_sub_cancel_right] at h2
  exact hM.ne_top ((Ideal.eq_top_iff_one M).mpr h1)


-- @@ L180-257 verbatim
/-- If evaluation at `z` is a surjection `R[X] → A` with kernel `(g)`, where the maximal
ideal of the local ring `R` is generated by the constant coefficient of `g`, whose image lies in
`(z)`, then `(z)` is maximal: it is the kernel of the induced map onto the residue field of `R`.
(Not `private`: `RootLifting.lean` reuses it to make the integral closure local.) -/
lemma isMaximal_span_of_aeval_surjective {R A : Type*} [CommRing R] [IsLocalRing R]
    [CommRing A] [Algebra R A] {z : A} {g : Polynomial R}
    (hsurj : Function.Surjective (Polynomial.aeval z : Polynomial R →ₐ[R] A))
    (hker : RingHom.ker (Polynomial.aeval z : Polynomial R →ₐ[R] A).toRingHom =
      Ideal.span {g})
    (hg₀ : IsLocalRing.maximalIdeal R = Ideal.span {g.coeff 0})
    (hb₀ : algebraMap R A (g.coeff 0) ∈ Ideal.span {z}) :
    (Ideal.span {z}).IsMaximal := by
  classical
  set φ₀ : Polynomial R →ₐ[R] IsLocalRing.ResidueField R :=
    Polynomial.aeval (0 : IsLocalRing.ResidueField R) with hφ₀
  have hφ₀eval : ∀ P : Polynomial R,
      φ₀ P = algebraMap R (IsLocalRing.ResidueField R) (P.coeff 0) := by
    intro P
    rw [hφ₀]
    simp [Polynomial.aeval_def, Polynomial.eval₂_at_zero]
  have hres0 : ∀ r : R, r ∈ IsLocalRing.maximalIdeal R →
      algebraMap R (IsLocalRing.ResidueField R) r = 0 := by
    intro r hr
    rw [IsLocalRing.ResidueField.algebraMap_eq]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr hr
  have hle : RingHom.ker (Polynomial.aeval z : Polynomial R →ₐ[R] A).toRingHom ≤
      RingHom.ker φ₀.toRingHom := by
    rw [hker]
    intro P hP
    rw [Ideal.mem_span_singleton] at hP
    obtain ⟨Q, rfl⟩ := hP
    rw [RingHom.mem_ker]
    change φ₀ (g * Q) = 0
    rw [map_mul, hφ₀eval g, hres0 _ (hg₀ ▸ Ideal.mem_span_singleton_self _), zero_mul]
  set φ : A →ₐ[R] IsLocalRing.ResidueField R :=
    AlgHom.liftOfSurjective _ hsurj φ₀ hle with hφ
  have hφmk : ∀ P : Polynomial R, φ (Polynomial.aeval z P) = φ₀ P := fun P =>
    AlgHom.liftOfSurjective_apply _ hsurj φ₀ hle P
  have hφsurj : Function.Surjective φ := by
    intro κ
    obtain ⟨r, hr⟩ := Ideal.Quotient.mk_surjective κ
    refine ⟨Polynomial.aeval z (Polynomial.C r), ?_⟩
    rw [hφmk, hφ₀eval, Polynomial.coeff_C_zero]
    rw [IsLocalRing.ResidueField.algebraMap_eq]
    exact hr
  have hkerφ : RingHom.ker φ.toRingHom = Ideal.span {z} := by
    apply le_antisymm
    · intro w hw
      obtain ⟨P, rfl⟩ := hsurj w
      rw [RingHom.mem_ker] at hw
      have hw' : φ₀ P = 0 := by rw [← hφmk]; exact hw
      rw [hφ₀eval] at hw'
      have hP0 : P.coeff 0 ∈ IsLocalRing.maximalIdeal R := by
        rw [IsLocalRing.ResidueField.algebraMap_eq] at hw'
        exact Ideal.Quotient.eq_zero_iff_mem.mp hw'
      rw [hg₀, Ideal.mem_span_singleton] at hP0
      obtain ⟨d, hd⟩ := hP0
      have hdecomp : Polynomial.aeval z P =
          z * Polynomial.aeval z P.divX + algebraMap R A (P.coeff 0) := by
        conv_lhs => rw [← Polynomial.X_mul_divX_add P]
        rw [map_add, map_mul, Polynomial.aeval_X, Polynomial.aeval_C]
      rw [hdecomp]
      refine Ideal.add_mem _
        (Ideal.mul_mem_right _ _ (Ideal.mem_span_singleton_self z)) ?_
      rw [hd, map_mul]
      exact Ideal.mul_mem_right _ _ hb₀
    · rw [Ideal.span_le]
      intro w hw
      rw [Set.mem_singleton_iff] at hw
      rw [hw]
      rw [SetLike.mem_coe, RingHom.mem_ker,
        show z = Polynomial.aeval z (Polynomial.X : Polynomial R) from
          (Polynomial.aeval_X (R := R) z).symm]
      rw [show φ.toRingHom (Polynomial.aeval z (Polynomial.X : Polynomial R)) =
        φ (Polynomial.aeval z (Polynomial.X : Polynomial R)) from rfl, hφmk, hφ₀eval,
        Polynomial.coeff_X_zero, map_zero]
  rw [← hkerφ]
  exact RingHom.ker_isMaximal_of_surjective _ hφsurj


-- @@ L259-289 verbatim
/-- The ramification index of `p = (g₀)` in `A` is `n` when `g₀` maps to a unit multiple of
`z ^ n` with `(z)` maximal. -/
private lemma ramificationIdx_eq_of_span {R A : Type*} [CommRing R] [CommRing A]
    [IsDomain A] [Algebra R A] {p : Ideal R} {g₀ : R} {z u : A} {n : ℕ} (hn : 0 < n)
    (hp : p = Ideal.span {g₀}) (hbu : algebraMap R A g₀ * u = -z ^ n) (hu : IsUnit u)
    (hzne : z ≠ 0) (hmax : (Ideal.span {z}).IsMaximal) :
    Ideal.ramificationIdx' p (Ideal.map (algebraMap R A) p).radical = n := by
  have hassoc : Associated (algebraMap R A g₀) (z ^ n) := by
    obtain ⟨w, hw⟩ := hu
    have h2 : Associated (algebraMap R A g₀) (-z ^ n) := ⟨w, by rw [hw]; exact hbu⟩
    exact h2.trans ⟨-1, by simp⟩
  have hspan : Ideal.span {algebraMap R A g₀} = Ideal.span {z} ^ n := by
    rw [Ideal.span_singleton_pow]
    exact Ideal.span_singleton_eq_span_singleton.mpr hassoc
  have hmapp : Ideal.map (algebraMap R A) p = Ideal.span {z} ^ n := by
    rw [hp, Ideal.map_span, Set.image_singleton, hspan]
  have hzu : ¬IsUnit z := by
    intro hz
    exact hmax.ne_top (Ideal.span_singleton_eq_top.mpr hz)
  have hrad : (Ideal.map (algebraMap R A) p).radical = Ideal.span {z} := by
    rw [hmapp, (Ideal.span {z}).radical_pow hn.ne']
    exact hmax.isPrime.radical
  rw [hrad]
  refine Ideal.ramificationIdx'_spec ?_ ?_
  · rw [hmapp]
  · rw [hmapp]
    intro hle
    have h1 : z ^ n ∈ Ideal.span {z} ^ (n + 1) :=
      hle (by rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton])
    rw [Ideal.span_singleton_pow, Ideal.mem_span_singleton] at h1
    exact absurd ((pow_dvd_pow_iff hzne hzu).mp h1) (by omega)


-- @@ L291-291 verbatim
/-! ## Total ramifiedness of the adjoined root field -/


-- @@ L293-339 verbatim
private lemma exists_unit_relation_of_coeff_dvd {R A : Type*} [CommRing R] [CommRing A]
    [Algebra R A] {g : Polynomial R} {ξ : A} (hgmonic : g.Monic)
    (hn : 0 < g.natDegree) (hdvd : ∀ i, i < g.natDegree → g.coeff 0 ∣ g.coeff i)
    (haev : Polynomial.aeval ξ g = 0) :
    ∃ u : A, IsUnit u ∧ algebraMap R A (g.coeff 0) * u = -ξ ^ g.natDegree := by
  classical
  let n := g.natDegree
  -- the Eisenstein relation, rearranged around the constant coefficient
  obtain ⟨m, hm⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  set b : ℕ → A := fun i => algebraMap R A (g.coeff i) with hb
  have hrel : ξ ^ n + ∑ i ∈ Finset.range n, b i * ξ ^ i = 0 := by
    calc ξ ^ n + ∑ i ∈ Finset.range n, b i * ξ ^ i
        = ∑ i ∈ Finset.range (n + 1), g.coeff i • ξ ^ i := by
          rw [Finset.sum_range_succ, hgmonic.coeff_natDegree, one_smul, add_comm]
          congr 1
          exact Finset.sum_congr rfl fun i _ => (Algebra.smul_def _ _).symm
      _ = Polynomial.aeval ξ g := (Polynomial.aeval_eq_sum_range _).symm
      _ = 0 := haev
  have hex : ∀ i : ℕ, ∃ d : R, i + 1 < n → g.coeff (i + 1) = g.coeff 0 * d := by
    intro i
    by_cases h : i + 1 < n
    · obtain ⟨d, hd⟩ := hdvd (i + 1) h
      exact ⟨d, fun _ => hd⟩
    · exact ⟨0, fun hh => absurd hh h⟩
  choose c hc using hex
  obtain ⟨t, ht⟩ : ∃ t : A, t = ∑ i ∈ Finset.range m,
      algebraMap R A (c i) * ξ ^ i := ⟨_, rfl⟩
  obtain ⟨u, hu'⟩ : ∃ u : A, u = 1 + ξ * t := ⟨_, rfl⟩
  have hbu : b 0 * u = -ξ ^ n := by
    have h2 : ∑ i ∈ Finset.range n, b i * ξ ^ i = b 0 * u := by
      rw [hu', ht, hm, Finset.sum_range_succ']
      have h3 : ∀ i ∈ Finset.range m, b (i + 1) * ξ ^ (i + 1) =
          b 0 * (algebraMap R A (c i) * ξ ^ i * ξ) := by
        intro i hi
        rw [Finset.mem_range] at hi
        rw [hb]
        dsimp only
        rw [hc i (by omega), map_mul, pow_succ]
        ac_rfl
      rw [Finset.sum_congr rfl h3, ← Finset.mul_sum, ← Finset.sum_mul]
      simp only [pow_zero, mul_one, mul_add, mul_comm ξ, add_comm]
    rw [h2] at hrel
    exact eq_neg_of_add_eq_zero_right hrel
  have hu : IsUnit u := by
    rw [hu']
    exact isUnit_one_add_of_mul_eq_neg_pow (c := b 0) (n := n) (by rw [← hu']; exact hbu)
  exact ⟨u, hu, hbu⟩


-- @@ L341-382 verbatim
omit [IsUniformAddGroup K] in
/-- The unit relation behind total ramifiedness, exposed for the discriminant bound of
`sub_one_le_d_adjoin`: the constant coefficient of the minimal polynomial becomes a unit multiple of
`-ξ ^ n` inside the integral closure. -/
theorem exists_unit_relation {π : 𝒪[K]} (hπ : Irreducible π) {x : SeparableClosure K}
    (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    ∃ ξ u : ↥(integers (IntermediateField.adjoin K {x})),
      (ξ : ↥(IntermediateField.adjoin K {x})) = IntermediateField.AdjoinSimple.gen K x ∧
      IsUnit u ∧
      algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))
          ((minpoly 𝒪[K] x).coeff 0) * u =
        -ξ ^ (minpoly 𝒪[K] x).natDegree := by
  classical
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  set L' := IntermediateField.adjoin K {x} with hL'
  set x' : ↥L' := IntermediateField.AdjoinSimple.gen K x with hx'
  have hx'mem : x' ∈ integers L' :=
    (isIntegral_algebraMap_iff (B := SeparableClosure K)).mp hint
  set ξ : ↥(integers L') := ⟨x', hx'mem⟩ with hξ
  set g : Polynomial 𝒪[K] := minpoly 𝒪[K] x with hg
  set n : ℕ := g.natDegree with hn'
  have hn : 0 < n := minpoly.natDegree_pos hint
  have hgmonic : g.Monic := minpoly.monic hint
  have haev : Polynomial.aeval ξ g = 0 := by
    apply Subtype.val_injective
    change algebraMap ↥(integers L') ↥L' (Polynomial.aeval ξ g) = 0
    rw [← Polynomial.aeval_algebraMap_apply]
    apply (algebraMap ↥L' (SeparableClosure K)).injective
    rw [← Polynomial.aeval_algebraMap_apply, map_zero]
    exact minpoly.aeval 𝒪[K] x
  -- the coefficient structure
  have hπg₀ : Associated π (g.coeff 0) := associated_pi_coeff_zero hπ hint hei
  have hdvd : ∀ i, i < n → g.coeff 0 ∣ g.coeff i := by
    intro i hi
    have h1 : π ∣ g.coeff i := by
      have := hei.mem hi
      rwa [Ideal.submodule_span_eq, Ideal.mem_span_singleton] at this
    exact (hπg₀.symm.dvd).trans h1
  obtain ⟨u, hu, hbu⟩ := exists_unit_relation_of_coeff_dvd hgmonic hn hdvd haev
  exact ⟨ξ, u, rfl, hu, hbu⟩


-- @@ L384-531 verbatim
omit [IsUniformAddGroup K] in
theorem isTotallyRamified_adjoin {π : 𝒪[K]} (hπ : Irreducible π) {x : SeparableClosure K}
    (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    IsTotallyRamified (IntermediateField.adjoin K {x}) := by
  classical
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  set L' := IntermediateField.adjoin K {x} with hL'
  set x' : ↥L' := IntermediateField.AdjoinSimple.gen K x with hx'
  have hx'mem : x' ∈ integers L' :=
    (isIntegral_algebraMap_iff (B := SeparableClosure K)).mp hint
  set ξ : ↥(integers L') := ⟨x', hx'mem⟩ with hξ
  set g : Polynomial 𝒪[K] := minpoly 𝒪[K] x with hg
  set n : ℕ := g.natDegree with hn'
  have hn : 0 < n := minpoly.natDegree_pos hint
  have hgmonic : g.Monic := minpoly.monic hint
  -- the evaluation identities
  have hvalinj : Function.Injective (Subtype.val : ↥(integers L') → ↥L') :=
    Subtype.val_injective
  have haevx' : ∀ P : Polynomial 𝒪[K],
      (Polynomial.aeval x' P : ↥L') = 0 ↔ Polynomial.aeval x P = 0 := by
    intro P
    have h2 : Polynomial.aeval x P =
        algebraMap ↥L' (SeparableClosure K) (Polynomial.aeval x' P) := by
      rw [← Polynomial.aeval_algebraMap_apply]
      rfl
    constructor
    · intro h
      rw [h2, h, map_zero]
    · intro h
      exact (algebraMap ↥L' (SeparableClosure K)).injective
        (by rw [← h2, h, map_zero])
  have haevξ : ∀ P : Polynomial 𝒪[K],
      Polynomial.aeval ξ P = 0 ↔ Polynomial.aeval x P = 0 := by
    intro P
    rw [← haevx' P]
    have h2 : Polynomial.aeval x' P =
        algebraMap ↥(integers L') ↥L' (Polynomial.aeval ξ P) := by
      rw [← Polynomial.aeval_algebraMap_apply]
      rfl
    constructor
    · intro h
      rw [h2, h, map_zero]
    · intro h
      refine hvalinj ?_
      rw [show ((0 : ↥(integers L')) : ↥L') = 0 from rfl,
        show ((Polynomial.aeval ξ P : ↥(integers L')) : ↥L') =
          algebraMap ↥(integers L') ↥L' (Polynomial.aeval ξ P) from rfl,
        ← h2, h]
  have haev : Polynomial.aeval ξ g = 0 := (haevξ g).mpr (minpoly.aeval 𝒪[K] x)
  have hvalaev : ∀ P : Polynomial 𝒪[K],
      (↑(Polynomial.aeval ξ P) : ↥L') = Polynomial.aeval x' P := by
    intro P
    have h2 : Polynomial.aeval x' P =
        algebraMap ↥(integers L') ↥L' (Polynomial.aeval ξ P) := by
      rw [← Polynomial.aeval_algebraMap_apply]
      rfl
    calc (↑(Polynomial.aeval ξ P) : ↥L')
        = algebraMap ↥(integers L') ↥L' (Polynomial.aeval ξ P) := rfl
      _ = Polynomial.aeval x' P := h2.symm
  -- the coefficient structure
  have hg₀ne : g.coeff 0 ≠ 0 := by
    intro h0
    exact hei.notMem (h0 ▸ zero_mem _)
  have hπg₀ : Associated π (g.coeff 0) := associated_pi_coeff_zero hπ hint hei
  obtain ⟨m, hm⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  set b : ℕ → ↥(integers L') := fun i => algebraMap 𝒪[K] ↥(integers L') (g.coeff i)
  obtain ⟨ξ₀, u, hξ₀, hu, hbu₀⟩ := exists_unit_relation hπ hint hei
  have hξ₀ξ : ξ₀ = ξ := Subtype.ext hξ₀
  have hbu : b 0 * u = -ξ ^ n := by
    simpa only [hξ₀ξ] using hbu₀
  have hg₀span : IsLocalRing.maximalIdeal 𝒪[K] = Ideal.span {g.coeff 0} := by
    rw [hπ.maximalIdeal_eq]
    exact Ideal.span_singleton_eq_span_singleton.mpr hπg₀
  have hχsurj : Function.Surjective
      (Polynomial.aeval ξ : Polynomial 𝒪[K] →ₐ[𝒪[K]] ↥(integers L')) := by
    intro z
    have h1 : (z : ↥L') ∈ Algebra.adjoin 𝒪[K] {x'} :=
      (integers_eq_adjoin hπ hint hei).le z.2
    have h1' : (z : ↥L') ∈ (Polynomial.aeval x' : Polynomial 𝒪[K] →ₐ[𝒪[K]] ↥L').range := by
      rw [← Algebra.adjoin_singleton_eq_range_aeval]
      exact h1
    obtain ⟨P, hP⟩ := (AlgHom.mem_range (Polynomial.aeval x')).mp h1'
    refine ⟨P, hvalinj ?_⟩
    rw [hvalaev P]
    exact hP
  have hker : RingHom.ker
      (Polynomial.aeval ξ : Polynomial 𝒪[K] →ₐ[𝒪[K]] ↥(integers L')).toRingHom =
      Ideal.span {g} := by
    apply le_antisymm
    · intro P hP
      rw [Ideal.mem_span_singleton]
      exact minpoly.isIntegrallyClosed_dvd hint
        ((haevξ P).mp (RingHom.mem_ker.mp hP))
    · rw [Ideal.span_le]
      intro P hP
      rw [Set.mem_singleton_iff] at hP
      subst hP
      rw [SetLike.mem_coe]
      refine RingHom.mem_ker.mpr ?_
      change Polynomial.aeval ξ g = 0
      exact haev
  have hb₀ξ : algebraMap 𝒪[K] ↥(integers L') (g.coeff 0) ∈ Ideal.span {ξ} := by
    change b 0 ∈ Ideal.span {ξ}
    rw [Ideal.mem_span_singleton]
    obtain ⟨w, hw⟩ := hu
    refine ⟨-(ξ ^ m * ↑w⁻¹), ?_⟩
    have h1 : b 0 = -ξ ^ n * ↑w⁻¹ := by
      calc b 0 = b 0 * ↑w * ↑w⁻¹ := by
            rw [mul_assoc, ← Units.val_mul, mul_inv_cancel, Units.val_one, mul_one]
        _ = -ξ ^ n * ↑w⁻¹ := by rw [hw, hbu]
    rw [h1, hm]
    ring
  have hmax : (Ideal.span {ξ}).IsMaximal :=
    isMaximal_span_of_aeval_surjective hχsurj hker hg₀span hb₀ξ
  have hξne : ξ ≠ 0 := by
    intro h0
    have hx'0 : x' = 0 := congrArg Subtype.val h0
    have hx0 : x = 0 := by
      calc x = algebraMap ↥L' (SeparableClosure K) x' := rfl
        _ = algebraMap ↥L' (SeparableClosure K) 0 := by rw [hx'0]
        _ = 0 := map_zero _
    apply hg₀ne
    have h1 := minpoly.aeval 𝒪[K] x
    rw [← hg, hx0] at h1
    have h2 : algebraMap 𝒪[K] (SeparableClosure K) (g.coeff 0) = 0 := by
      rw [← h1, Polynomial.aeval_def, Polynomial.eval₂_at_zero]
    have hinj : Function.Injective (algebraMap 𝒪[K] (SeparableClosure K)) := by
      rw [IsScalarTower.algebraMap_eq 𝒪[K] K (SeparableClosure K)]
      exact (algebraMap K (SeparableClosure K)).injective.comp
        (IsFractionRing.injective 𝒪[K] K)
    exact hinj (by rw [h2, map_zero])
  have hramfin : Ideal.ramificationIdx' (IsLocalRing.maximalIdeal 𝒪[K])
      ((Ideal.map (algebraMap 𝒪[K] ↥(integers L'))
        (IsLocalRing.maximalIdeal 𝒪[K])).radical) = n :=
    ramificationIdx_eq_of_span hn hg₀span (show b 0 * u = -ξ ^ n from hbu) hu hξne hmax
  -- conclude: the ramification index equals the degree
  have hfr : Module.finrank K ↥L' = n := by
    change Module.finrank K ↥(IntermediateField.adjoin K {x}) = n
    rw [IntermediateField.adjoin.finrank hint.tower_top,
      show minpoly K x = (minpoly 𝒪[K] x).map (algebraMap 𝒪[K] K) from
        minpoly.isIntegrallyClosed_eq_field_fractions' K hint,
      (minpoly.monic hint).natDegree_map]
  change ramificationIdx L' = Module.finrank K ↥L'
  rw [hfr]
  unfold ramificationIdx maximalIdealAbove
  exact hramfin


-- @@ L533-533 verbatim
end MassFormula
