/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.Methods.WellOrdering.GapWitness
import LeanPool.InfinitaryLogic.Methods.SymbSublangExpansion
import LeanPool.InfinitaryLogic.Methods.WellOrdering.ModelExtraction

-- @@ L11-27 verbatim
/-!
# Removing symbol countability (issue #12, the sublanguage wrapper)

The step-5/6 theorems assumed `[Countable (Σ l, L.Relations l)]` for the fair enumeration.
This wrapper removes it by the two-sorted symbol-generated sublanguage
(`symbSublang φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)` — both sorts countable,
**proved** from the sentence's own symbol supply, with `lt` inserted so the distinguished
relation survives the restriction):

* the well-ordered-chains hypothesis transfers to the sublanguage along reducts;
* the sublanguage endpoint produces the model and rational map;
* `expandSymbStructureBase` expands the model back to `L`, preserving the root
  (`realize_restrictSymbols_expandSymbStructureBase`) and the relation (`dif_pos`).

`[L.IsRelational]` remains — it is consumed by the quotient term model, and its removal is
the separate arbitrary-function-language graph translation, not this wrapper.
-/


-- @@ L29-29 verbatim
@[expose] public section


-- @@ L31-31 verbatim
namespace FirstOrder.Language


-- @@ L33-33 verbatim
open FirstOrder Structure


-- @@ L35-35 verbatim
variable {L : Language.{0, 0}}


-- @@ L37-91 verbatim
/-- **Step-5 endpoint, no symbol countability** (relational): the countable-relational-core
hypothesis of `exists_model_relPreserving_relational` removed via the two-sorted sublanguage
generated by the sentence's own symbols together with `lt`. -/
theorem exists_model_relPreserving_isRelational [L.IsRelational]
    (φ : L.Sentenceω) (lt : L.Relations 2) (h : HasWellOrderedChains φ lt) :
    ∃ (M : Type) (_ : L.Structure M) (_ : Nonempty M) (f : ℚ → M),
      Sentenceω.Realize φ M ∧ RelPreserving lt f := by
  classical
  have : (symbSublang (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn)).IsRelational := symbSublang_isRelational _ _
  have : Countable (Σ n, (symbSublang (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn)).Functions n) :=
    symbSublang_fun_countable φ.functionsIn_countable _
  have : Countable (Σ l, (symbSublang (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn)).Relations l) :=
    symbSublang_rel_countable _ (φ.relationsIn_countable.insert _)
  -- the restricted root and the surviving distinguished relation
  have hchains₀ : HasWellOrderedChains
      (φ.restrictSymbols (subset_refl _) (Set.subset_insert _ _))
      (⟨lt, Set.mem_insert _ _⟩ : (symbSublang (L := L) φ.functionsIn
        (insert ⟨2, lt⟩ φ.relationsIn)).Relations 2) := by
    intro α hα
    obtain ⟨M, instM, ne, hreal, w, hchain⟩ := h α hα
    let instM₀ := (symbSublangIncl φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)).reduct M
    have : (symbSublangIncl φ.functionsIn
        (insert ⟨2, lt⟩ φ.relationsIn)).IsExpansionOn M := LHom.isExpansionOn_reduct _ _
    refine ⟨M, instM₀, ne, ?_, w, fun x y hxy => hchain x y hxy⟩
    have hmap := BoundedFormulaω.realize_mapLanguage
      (symbSublangIncl φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn))
      (φ.restrictSymbols (subset_refl _) (Set.subset_insert _ _))
      (Empty.elim : Empty → M) Fin.elim0
    rw [BoundedFormulaω.mapLanguage_restrictSymbols] at hmap
    exact hmap.mp hreal
  obtain ⟨N, instN₀, neN, f, hreal₀, hf₀⟩ :=
    exists_model_relPreserving_relational _ _ hchains₀
  let := instN₀
  have := neN
  let instN : L.Structure N :=
    expandSymbStructureBase φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)
  have : (symbSublangIncl φ.functionsIn (insert ⟨2, lt⟩ φ.relationsIn)).IsExpansionOn N := by
    have hred := reduct_expandSymbStructureBase (L := L) φ.functionsIn
      (insert ⟨2, lt⟩ φ.relationsIn) (M := N)
    rw [← hred]
    exact LHom.isExpansionOn_reduct _ _
  refine ⟨N, instN, neN, f, ?_, fun q r hqr => ?_⟩
  · exact (realize_restrictSymbols_expandSymbStructureBase _ _ φ (subset_refl _)
      (Set.subset_insert _ _) Empty.elim Fin.elim0).mp hreal₀
  · have hpres := hf₀ q r hqr
    -- The relation and carrier are supplied explicitly: with `?R` open, `rw` must assign the
    -- subtype element `⟨lt, _⟩` to `?R : (symbSublang ..).Relations 2`, which fails at `implicit`
    -- transparency.
    exact Eq.mp (LHom.map_onRelation (M := N) (n := 2)
      (symbSublangIncl φ.functionsIn
        (insert (⟨2, lt⟩ : Σ n, L.Relations n) φ.relationsIn))
      ⟨lt, Set.mem_insert _ _⟩ ![f q, f r]).symm hpres


-- @@ L93-93 verbatim
end FirstOrder.Language
