/-
Copyright (c) 2026 Hyeon Seung-Hyeon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hyeon Seung-Hyeon
-/

-- Adapted for Lean Pool from 0stellensatz/MassFormula at 7fa41a621f724f110183904d3fd19c6730a932ad.
module

public import LeanPool.MassFormula.Defs
public import Mathlib.RingTheory.Polynomial.Eisenstein.Basic
import LeanPool.MassFormula.Discriminant
public import LeanPool.MassFormula.EisensteinMonogenic
import Mathlib.Algebra.GroupWithZero.Submonoid.CancelMulZero
import Mathlib.NumberTheory.ArithmeticFunction.Misc
import Mathlib.RingTheory.DedekindDomain.IntegralClosure
import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.Valuation.Integral


-- @@ L22-68 verbatim
/-!
# Auxiliary file: quantitative root-lifting

The analytic engine behind equation (3) and Lemma 1 of §3: a simple root of a monic integral
polynomial lifts to a root of every coefficientwise-close monic integral polynomial, inside any `L`
in `sigma K n` ([Serre 1978, Lemma 1, pp.1032–1033][Serre1978]). The concluding theorem
`card_aroots_eq` states the consequence used downstream: for a separable monic `f` over `𝒪[K]`,
there is a threshold `T` such that every monic `g` with `g.coeff i - f.coeff i` in the `T`-th power
of `𝓂[K]` for all `i` has exactly as many roots in `L` as `f` does—the local constancy of the root
count, which `First.lean` restates on the Eisenstein region and which the measurability,
countability, and change-of-variables arguments downstream consume.

The route is Newton–Hensel over the complete ring `integers L`, organized in four layers:

- **The `proof_wanted` of Mathlib.** `isAdicComplete_integer` proves
  `IsAdicComplete 𝓂[K] 𝒪[K]`—stated as `proof_wanted isAdicComplete` in
  `Mathlib/NumberTheory/LocalField/Basic.lean`—with `IsHausdorff` from the Krull intersection
  theorem and `IsPrecomplete` from Cantor's intersection of the nested closed balls around the
  partial terms, inside the compact unit ball of `K`.
- **The structure of `integers L` at an Eisenstein generator.** Through the monogenic presentation
  of `integers_eq_adjoin`, `integers L` is `𝒪[K][X]` modulo `(G)`: free of rank `n` over `𝒪[K]`
  (`basisOfEisenstein`), local with maximal ideal generated by the root
  (`isMaximal_span_integralGen`, `isLocalRing_integers`), a discrete valuation ring
  (`isDiscreteValuationRing_integers`), and adically complete
  (`isAdicComplete_span_integralGen`)—completeness transfers coefficientwise along the basis, and
  the interleaving of `(ξ) ^ n` with `π` times `integers L` converts `𝓂[K]`-adic limits into
  `(ξ)`-adic ones.
- **Newton iteration.** `exists_isRoot` is the quantitative Hensel lemma over an abstract complete
  discrete valuation ring: if the order of `F` at `y₀` exceeds twice that of its derivative, the
  iteration sending `y` to `y - F y / F' y` converges to a root `z` whose distance to `y₀` has
  order at least the difference of the two.
- **The count comparison.** A Bézout certificate `U * f + V * f' = β` over `𝒪[K]` (from separability
  over `K`, denominators cleared by `IsLocalization.integerNormalization`) bounds the order of the
  derivative of `f` at every near-root by the order `Γ` of `β`, uniformly; with threshold
  `T = 2 * Γ + 1`, Newton lifts each root of either polynomial to a root of the other at distance of
  order greater than `Γ`, while distinct roots stay at distance of order at most `Γ`—so the two
  lifting maps are injective, every root in `L` is simple, and the counts agree.

No topology on `L` enters anywhere: the completeness of `integers L` is the algebraic
`IsAdicComplete`, and all estimates use the `ℕ∞`-valued `IsDiscreteValuationRing.addVal` of
`integers L`.

## References

* [Serre1978] J-P. Serre, *Une «formule de masse» pour les extensions totalement ramifiées de
  degré donné d'un corps local*, C. R. Acad. Sci. Paris **286** (1978), Série A, 1031–1036.
-/


-- @@ L70-70 verbatim
@[expose] public section


-- @@ L72-72 verbatim
open ValuativeRel IntermediateField IsDiscreteValuationRing


-- @@ L74-74 verbatim
namespace MassFormula


-- @@ L76-77 verbatim
variable {K : Type*} [Field K] [ValuativeRel K] [UniformSpace K] [IsUniformAddGroup K]
  [IsNonarchimedeanLocalField K]


-- @@ L79-79 verbatim
/-! ## The `proof_wanted` of Mathlib: `𝒪[K]` is `𝓂[K]`-adically complete -/


-- @@ L81-177 verbatim
variable (K) in
/-- The ring of integers of a nonarchimedean local field is complete for its maximal-adic
topology—the statement `proof_wanted isAdicComplete` of
`Mathlib/NumberTheory/LocalField/Basic.lean`. `IsHausdorff` is the Krull intersection theorem in the
Noetherian local ring `𝒪[K]`; for `IsPrecomplete`, the closed balls around the partial terms of a
coherent sequence, of radius the `j`-th power of the valuation of `π`, are nested nonempty closed
subsets of the compact unit ball of `K`, so Cantor's intersection theorem provides the limit. -/
theorem isAdicComplete_integer : IsAdicComplete 𝓂[K] 𝒪[K] := by
  obtain ⟨π, hπ⟩ := IsDiscreteValuationRing.exists_irreducible 𝒪[K]
  have hmem_iff : ∀ (j : ℕ) (z : 𝒪[K]), z ∈ 𝓂[K] ^ j ↔ π ^ j ∣ z := fun j z => by
    rw [hπ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton]
  rw [isAdicComplete_iff]
  constructor
  · -- `IsHausdorff`: the Krull intersection theorem
    constructor
    intro z hz
    have h1 : z ∈ ⨅ j : ℕ, 𝓂[K] ^ j := Submodule.mem_iInf _ |>.mpr fun j => by
      have h2 := hz j
      rwa [SModEq.zero, ← Ideal.one_eq_top, smul_eq_mul, mul_one] at h2
    rwa [Ideal.iInf_pow_eq_bot_of_isLocalRing 𝓂[K]
      (IsLocalRing.maximalIdeal.isMaximal 𝒪[K]).ne_top, Submodule.mem_bot] at h1
  · -- `IsPrecomplete`: Cantor intersection of the nested closed balls around the terms
    constructor
    intro s hs
    have hdvd : ∀ {m j : ℕ}, m ≤ j → π ^ m ∣ (s j - s m) := by
      intro m j hmj
      have h1 := hs hmj
      rw [← Ideal.one_eq_top, smul_eq_mul, mul_one, SModEq.sub_mem] at h1
      exact dvd_sub_comm.mp ((hmem_iff m _).mp h1)
    -- the ball around the `j`-th term, of radius the `j`-th power of the valuation of `π`
    set C : ℕ → Set K := fun j =>
      {z : K | valuation K (z - (s j : K)) ≤ valuation K ((π : K) ^ j)} with hC
    have hdist : ∀ {m j : ℕ}, m ≤ j →
        valuation K ((s j : K) - (s m : K)) ≤ valuation K ((π : K) ^ m) := by
      intro m j hmj
      have h1 : ((s j - s m : 𝒪[K]) : K) = (s j : K) - (s m : K) := by push_cast; ring
      rw [← h1]
      exact Valuation.Integers.le_of_dvd (Valuation.integer.integers (valuation K)) (hdvd hmj)
    have hmono : ∀ j, C (j + 1) ⊆ C j := by
      intro j z hz
      have h1 : valuation K (z - (s j : K)) ≤
          max (valuation K (z - (s (j + 1) : K))) (valuation K ((s (j + 1) : K) - (s j : K))) := by
        have h2 : (z - (s (j + 1) : K)) + ((s (j + 1) : K) - (s j : K)) = z - (s j : K) := by ring
        simpa [h2] using (valuation K).map_add (z - (s (j + 1) : K)) ((s (j + 1) : K) - (s j : K))
      have h3 : valuation K ((π : K) ^ (j + 1)) ≤ valuation K ((π : K) ^ j) := by
        rw [map_pow, map_pow, pow_succ]
        exact mul_le_of_le_one_right' (((valuation K).mem_integer_iff _).mp π.2)
      exact h1.trans (max_le (le_trans hz h3) (hdist (Nat.le_succ j)))
    have hne : ∀ j, (C j).Nonempty := fun j => ⟨(s j : K), by simp [hC]⟩
    have hclosed : ∀ j, IsClosed (C j) := by
      intro j
      -- `Valued.isClosed_closedBall` states its ball over `Valued.v.restrict`, the valuation
      -- corestricted to its own value group, so the radius has to be moved across
      -- `Valuation.restrict_le_iff` first; `Valued.v` is `valuation K` definitionally.
      have h1 : C j = (fun z : K => z - (s j : K)) ⁻¹'
          {w : K | Valued.v.restrict w ≤ Valued.v.restrict ((π : K) ^ j)} := by
        ext z
        simp only [hC, Set.mem_ofPred_eq, Set.mem_preimage, Valuation.restrict_le_iff]
        exact Iff.rfl
      rw [h1]
      exact (Valued.isClosed_closedBall K _).preimage (continuous_sub_right _)
    have hcompact : IsCompact (C 0) := by
      have h1 : C 0 = (fun w : K => (s 0 : K) + w) '' {w : K | valuation K w ≤ 1} := by
        ext z
        constructor
        · intro hz
          refine ⟨z - (s 0 : K), ?_, by ring⟩
          simpa [hC] using hz
        · rintro ⟨w, hw, rfl⟩
          simpa [hC] using hw
      rw [h1]
      exact (IsNonarchimedeanLocalField.isCompact_closedBall K 1).image (continuous_const_add _)
    obtain ⟨ℓ, hℓ⟩ := IsCompact.nonempty_iInter_of_sequence_nonempty_isCompact_isClosed
      C hmono hne hcompact hclosed
    simp only [Set.mem_iInter] at hℓ
    have hℓO : ℓ ∈ 𝒪[K] := by
      have h0 : valuation K (ℓ - (s 0 : K)) ≤ 1 := by simpa [hC] using hℓ 0
      have h1 : valuation K ℓ ≤
          max (valuation K (ℓ - (s 0 : K))) (valuation K ((s 0 : K))) := by
        have h2 : (ℓ - (s 0 : K)) + (s 0 : K) = ℓ := by ring
        simpa [h2] using (valuation K).map_add (ℓ - (s 0 : K)) ((s 0 : K))
      exact ((valuation K).mem_integer_iff ℓ).mpr
        (h1.trans (max_le h0 (((valuation K).mem_integer_iff _).mp (s 0).2)))
    refine ⟨⟨ℓ, hℓO⟩, fun j => ?_⟩
    rw [← Ideal.one_eq_top, smul_eq_mul, mul_one, SModEq.sub_mem, hmem_iff]
    refine Valuation.Integers.dvd_of_le (Valuation.integer.integers (valuation K)) ?_
    have h1 : ((s j - ⟨ℓ, hℓO⟩ : 𝒪[K]) : K) = (s j : K) - ℓ := by push_cast; ring
    have h2 : valuation K ((s j : K) - ℓ) = valuation K (ℓ - (s j : K)) :=
      Valuation.map_sub_swap _ _ _
    have h3 : valuation K (ℓ - (s j : K)) ≤ valuation K ((π : K) ^ j) := by
      simpa [hC] using hℓ j
    calc valuation K (algebraMap 𝒪[K] K (s j - ⟨ℓ, hℓO⟩))
        = valuation K (ℓ - (s j : K)) := by
          rw [show algebraMap 𝒪[K] K (s j - ⟨ℓ, hℓO⟩) = ((s j - ⟨ℓ, hℓO⟩ : 𝒪[K]) : K) from rfl,
            h1, h2]
      _ ≤ valuation K ((π : K) ^ j) := h3
      _ = valuation K (algebraMap 𝒪[K] K (π ^ j)) := by push_cast; rfl


-- @@ L179-179 verbatim
/-! ## Adic completeness of finite free modules, coefficientwise -/


-- @@ L181-197 verbatim
/-- Membership in `J • ⊤` reads coefficientwise in any basis. -/
private theorem mem_smul_top_iff_of_basis {R M : Type*} [CommRing R] [AddCommGroup M]
    [Module R M] {ι : Type*} [Finite ι] (J : Ideal R) (b : Module.Basis ι R M) (z : M) :
    z ∈ (J • ⊤ : Submodule R M) ↔ ∀ i, b.repr z i ∈ J := by
  let := Fintype.ofFinite ι
  constructor
  · intro hz
    refine Submodule.smul_induction_on hz (fun r hr m _ => fun i => ?_)
      (fun y₁ y₂ h₁ h₂ => fun i => ?_)
    · rw [map_smul, Finsupp.smul_apply, smul_eq_mul]
      exact Ideal.mul_mem_right _ _ hr
    · rw [map_add, Finsupp.add_apply]
      exact J.add_mem (h₁ i) (h₂ i)
  · intro hz
    have h1 : z = ∑ i, b.repr z i • b i := (b.sum_repr z).symm
    rw [h1]
    exact Submodule.sum_mem _ fun i _ => Submodule.smul_mem_smul (hz i) Submodule.mem_top


-- @@ L199-237 verbatim
/-- `IsPrecomplete` passes from the base ring to any module with a finite basis: a coherent sequence
is coherent coefficientwise, each coefficient sequence has a limit, and the vector of limits is the
limit. -/
private theorem isPrecomplete_of_basis {R M : Type*} [CommRing R] [AddCommGroup M]
    [Module R M] {ι : Type*} [Finite ι] (I : Ideal R) (b : Module.Basis ι R M)
    (hR : IsPrecomplete I R) : IsPrecomplete I M := by
  let := Fintype.ofFinite ι
  constructor
  intro s hs
  have hcoord : ∀ i : ι, ∃ ℓ : R, ∀ j,
      b.repr (s j) i ≡ ℓ [SMOD (I ^ j • ⊤ : Submodule R R)] := by
    intro i
    refine hR.prec ?_
    intro m j hmj
    have h1 := hs hmj
    rw [SModEq.sub_mem] at h1 ⊢
    rw [← Ideal.one_eq_top, smul_eq_mul, mul_one]
    have h2 := (mem_smul_top_iff_of_basis (I ^ m) b _).mp h1 i
    rwa [map_sub, Finsupp.sub_apply] at h2
  choose ℓ hℓ using hcoord
  refine ⟨∑ i, ℓ i • b i, fun j => ?_⟩
  rw [SModEq.sub_mem, mem_smul_top_iff_of_basis _ b]
  intro i
  rw [map_sub, Finsupp.sub_apply]
  have h3 := hℓ i j
  rw [SModEq.sub_mem, ← Ideal.one_eq_top, smul_eq_mul, mul_one] at h3
  have h4 : b.repr (∑ i', ℓ i' • b i') i = ℓ i := by
    rw [map_sum]
    rw [Finsupp.finsetSum_apply]
    rw [Finset.sum_eq_single i]
    · rw [map_smul, Finsupp.smul_apply, Module.Basis.repr_self, Finsupp.single_eq_same,
        smul_eq_mul, mul_one]
    · intro i' _ hne
      rw [map_smul, Finsupp.smul_apply, Module.Basis.repr_self]
      simp [hne]
    · intro h
      exact absurd (Finset.mem_univ i) h
  rw [h4]
  exact h3


-- @@ L239-243 verbatim
/-- The congruences of the adic filtration read as ideal membership; isolating the rewrite keeps the
instance search away from subtype-heavy contexts. -/
private lemma smodEq_iff_sub_mem {A : Type*} [CommRing A] (J : Ideal A) (a b : A) :
    a ≡ b [SMOD (J • ⊤ : Submodule A A)] ↔ a - b ∈ J := by
  rw [SModEq.sub_mem, ← Ideal.one_eq_top, smul_eq_mul, mul_one]


-- @@ L245-252 verbatim
/-! ## The structure of the integral closure at an Eisenstein generator

Everything below is relative to a root `x` of an Eisenstein polynomial over `𝒪[K]`, through the
monogenic presentation of `integers_eq_adjoin`: writing `G` for `minpoly 𝒪[K] x` and `n` for its
degree, the integral closure of `𝒪[K]` in `K⟮x⟯` is `𝒪[K][ξ]`, presented as `𝒪[K][X]` modulo `(G)`,
a complete discrete valuation ring with maximal ideal `(ξ)` and `(ξ) ^ n` equal to `π` times that
closure.
-/


-- @@ L254-254 verbatim
variable {π : 𝒪[K]} {x : SeparableClosure K}


-- @@ L256-263 verbatim
/-- The generator `x` of `K⟮x⟯`, seen inside the integral closure—the canonical lift of
`IntermediateField.AdjoinSimple.gen K x`. -/
noncomputable def integralGen (hint : IsIntegral 𝒪[K] x) :
    ↥(integers (IntermediateField.adjoin K {x})) := by
  have : IsScalarTower ↥𝒪[K] ↥(IntermediateField.adjoin K {x}) (SeparableClosure K) :=
    IsScalarTower.of_algebraMap_eq' rfl
  exact ⟨IntermediateField.AdjoinSimple.gen K x,
    (isIntegral_algebraMap_iff (B := SeparableClosure K)).mp hint⟩


-- @@ L265-290 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- Evaluation at `integralGen` vanishes exactly when evaluation at `x` does: the two sit under the
injections of `integers L` into `K⟮x⟯` into `SeparableClosure K`. -/
private lemma aeval_integralGen_eq_zero_iff (hint : IsIntegral 𝒪[K] x)
    (P : Polynomial 𝒪[K]) :
    Polynomial.aeval (integralGen hint) P = 0 ↔ Polynomial.aeval x P = 0 := by
  set L' := IntermediateField.adjoin K {x} with hL'
  set x' : ↥L' := IntermediateField.AdjoinSimple.gen K x with hx'
  have h1 : Polynomial.aeval x' P =
      algebraMap ↥(integers L') ↥L' (Polynomial.aeval (integralGen hint) P) := by
    rw [← Polynomial.aeval_algebraMap_apply]
    rfl
  have h2 : Polynomial.aeval x P = algebraMap ↥L' (SeparableClosure K) (Polynomial.aeval x' P) := by
    rw [← Polynomial.aeval_algebraMap_apply]
    rfl
  constructor
  · intro h
    rw [h2, h1, h, map_zero, map_zero]
  · intro h
    have h3 : Polynomial.aeval x' P = 0 :=
      (algebraMap ↥L' (SeparableClosure K)).injective (by rw [← h2, h, map_zero])
    exact Subtype.val_injective (by
      rw [show ((Polynomial.aeval (integralGen hint) P : ↥(integers L')) : ↥L') =
            algebraMap ↥(integers L') ↥L' (Polynomial.aeval (integralGen hint) P) from rfl,
        ← h1, h3]
      rfl)


-- @@ L292-296 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- `integralGen` is a root of the minimal polynomial of `x` over `𝒪[K]`. -/
private lemma aeval_integralGen (hint : IsIntegral 𝒪[K] x) :
    Polynomial.aeval (integralGen hint) (minpoly 𝒪[K] x) = 0 :=
  (aeval_integralGen_eq_zero_iff hint _).mpr (minpoly.aeval 𝒪[K] x)


-- @@ L298-321 verbatim
omit [IsUniformAddGroup K] in
/-- Through the monogenicity of `integers_eq_adjoin`, evaluation at
`integralGen` is onto the integral closure. -/
private lemma aeval_integralGen_surjective (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Function.Surjective (Polynomial.aeval (integralGen hint) :
      Polynomial 𝒪[K] →ₐ[𝒪[K]] ↥(integers (IntermediateField.adjoin K {x}))) := by
  set L' := IntermediateField.adjoin K {x} with hL'
  set x' : ↥L' := IntermediateField.AdjoinSimple.gen K x with hx'
  intro z
  have h1 : (z : ↥L') ∈ Algebra.adjoin 𝒪[K] {x'} :=
    (integers_eq_adjoin hπ hint hei).le z.2
  have h1' : (z : ↥L') ∈ (Polynomial.aeval x' : Polynomial 𝒪[K] →ₐ[𝒪[K]] ↥L').range := by
    rw [← Algebra.adjoin_singleton_eq_range_aeval]
    exact h1
  obtain ⟨P, hP⟩ := (AlgHom.mem_range (Polynomial.aeval x')).mp h1'
  refine ⟨P, Subtype.val_injective ?_⟩
  have h2 : Polynomial.aeval x' P =
      algebraMap ↥(integers L') ↥L' (Polynomial.aeval (integralGen hint) P) := by
    rw [← Polynomial.aeval_algebraMap_apply]
    rfl
  rw [show ((Polynomial.aeval (integralGen hint) P : ↥(integers L')) : ↥L') =
    algebraMap ↥(integers L') ↥L' (Polynomial.aeval (integralGen hint) P) from rfl, ← h2]
  exact hP


-- @@ L323-342 verbatim
omit [IsUniformAddGroup K] in
/-- The kernel of evaluation at `integralGen` is generated by the minimal polynomial—`𝒪[K]` being
integrally closed. -/
private lemma ker_aeval_integralGen (hint : IsIntegral 𝒪[K] x) :
    RingHom.ker (Polynomial.aeval (integralGen hint) :
        Polynomial 𝒪[K] →ₐ[𝒪[K]] ↥(integers (IntermediateField.adjoin K {x}))).toRingHom =
      Ideal.span {minpoly 𝒪[K] x} := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  apply le_antisymm
  · intro P hP
    rw [Ideal.mem_span_singleton]
    exact minpoly.isIntegrallyClosed_dvd hint
      ((aeval_integralGen_eq_zero_iff hint P).mp (RingHom.mem_ker.mp hP))
  · rw [Ideal.span_le]
    intro P hP
    rw [Set.mem_singleton_iff] at hP
    subst hP
    rw [SetLike.mem_coe]
    exact RingHom.mem_ker.mpr (aeval_integralGen hint)


-- @@ L344-351 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- The minimal polynomial vanishes at `integralGen`, in the `eval₂` form `AdjoinRoot.liftAlgHom`
demands. -/
lemma eval₂_integralGen (hint : IsIntegral 𝒪[K] x) :
    (minpoly 𝒪[K] x).eval₂ (Algebra.ofId 𝒪[K]
      ↥(integers (IntermediateField.adjoin K {x}))) (integralGen hint) = 0 := by
  have h1 := aeval_integralGen hint
  rwa [Polynomial.aeval_def] at h1


-- @@ L353-359 verbatim
/-- The monogenic presentation read as an algebra map out of `AdjoinRoot`: substitution of
`integralGen` for the root. -/
noncomputable def adjoinRootLift (hint : IsIntegral 𝒪[K] x) :
    AdjoinRoot (minpoly 𝒪[K] x) →ₐ[𝒪[K]] ↥(integers (IntermediateField.adjoin K {x})) :=
  AdjoinRoot.liftAlgHom (minpoly 𝒪[K] x)
    (Algebra.ofId 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})))
    (integralGen hint) (eval₂_integralGen hint)


-- @@ L361-365 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
private lemma adjoinRootLift_mk (hint : IsIntegral 𝒪[K] x) (P : Polynomial 𝒪[K]) :
    adjoinRootLift hint (AdjoinRoot.mk _ P) = Polynomial.aeval (integralGen hint) P := by
  rw [adjoinRootLift, AdjoinRoot.liftAlgHom_mk]
  rfl


-- @@ L367-387 verbatim
omit [IsUniformAddGroup K] in
/-- The presentation is bijective: injective because the kernel of evaluation is exactly `(G)`,
surjective by the monogenicity of `integers_eq_adjoin`. -/
lemma bijective_adjoinRootLift (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Function.Bijective (adjoinRootLift hint) := by
  constructor
  · intro a b hab
    obtain ⟨P, rfl⟩ := AdjoinRoot.mk_surjective a
    obtain ⟨Q, rfl⟩ := AdjoinRoot.mk_surjective b
    rw [adjoinRootLift_mk, adjoinRootLift_mk] at hab
    have h1 : Polynomial.aeval (integralGen hint) (P - Q) = 0 := by
      rw [map_sub, hab, sub_self]
    have h2 : P - Q ∈ RingHom.ker (Polynomial.aeval (integralGen hint) :
        Polynomial 𝒪[K] →ₐ[𝒪[K]] _).toRingHom := RingHom.mem_ker.mpr h1
    rw [ker_aeval_integralGen hint, Ideal.mem_span_singleton] at h2
    rw [← sub_eq_zero, ← map_sub, AdjoinRoot.mk_eq_zero]
    exact h2
  · intro z
    obtain ⟨P, hP⟩ := aeval_integralGen_surjective hπ hint hei z
    exact ⟨AdjoinRoot.mk _ P, by rw [adjoinRootLift_mk]; exact hP⟩


-- @@ L389-394 verbatim
/-- The monogenic presentation, identifying `𝒪[K][X]` modulo `(G)` with `integers L`, as an algebra
equivalence. -/
noncomputable def adjoinRootEquiv (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    AdjoinRoot (minpoly 𝒪[K] x) ≃ₐ[𝒪[K]] ↥(integers (IntermediateField.adjoin K {x})) :=
  AlgEquiv.ofBijective (adjoinRootLift hint) (bijective_adjoinRootLift hπ hint hei)


-- @@ L396-402 verbatim
omit [IsUniformAddGroup K] in
/-- The presentation carries the root of `AdjoinRoot` to the Eisenstein generator. -/
lemma adjoinRootEquiv_root (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    adjoinRootEquiv hπ hint hei (AdjoinRoot.root (minpoly 𝒪[K] x)) = integralGen hint := by
  rw [adjoinRootEquiv, AlgEquiv.coe_ofBijective, AdjoinRoot.root,
    adjoinRootLift_mk hint Polynomial.X, Polynomial.aeval_X]


-- @@ L404-410 verbatim
/-- The integral closure as a power basis over `𝒪[K]`, generated by the Eisenstein generator: the
presentation of `integers L` as `𝒪[K][X]` modulo `(G)` carries the power basis of `AdjoinRoot`
across. -/
noncomputable def powerBasisOfEisenstein (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    PowerBasis 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) :=
  (AdjoinRoot.powerBasis' (minpoly.monic hint)).map (adjoinRootEquiv hπ hint hei)


-- @@ L412-417 verbatim
omit [IsUniformAddGroup K] in
lemma powerBasisOfEisenstein_gen (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    (powerBasisOfEisenstein hπ hint hei).gen = integralGen hint := by
  rw [powerBasisOfEisenstein, PowerBasis.map_gen, AdjoinRoot.powerBasis'_gen,
    adjoinRootEquiv_root]


-- @@ L419-422 verbatim
omit [IsUniformAddGroup K] in
lemma powerBasisOfEisenstein_dim (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    (powerBasisOfEisenstein hπ hint hei).dim = (minpoly 𝒪[K] x).natDegree := rfl


-- @@ L424-431 verbatim
/-- The power basis of the integral closure over `𝒪[K]`, on the index type `Fin n` of the minimal
polynomial's degree. Its `i`-th element is `ξ ^ i` (`basisOfEisenstein_apply`);
`UniformizerParam.lean` reads the coordinates of `integers L` off it. -/
noncomputable def basisOfEisenstein (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Module.Basis (Fin (minpoly 𝒪[K] x).natDegree) 𝒪[K]
      ↥(integers (IntermediateField.adjoin K {x})) :=
  (powerBasisOfEisenstein hπ hint hei).basis


-- @@ L433-441 verbatim
omit [IsUniformAddGroup K] in
/-- The power basis is the basis of the powers of the Eisenstein generator. -/
lemma basisOfEisenstein_apply (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    (i : Fin (minpoly 𝒪[K] x).natDegree) :
    basisOfEisenstein hπ hint hei i = integralGen hint ^ (i : ℕ) := by
  have h1 := (powerBasisOfEisenstein hπ hint hei).basis_eq_pow i
  rw [powerBasisOfEisenstein_gen] at h1
  exact h1



-- @@ L444-473 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- `integralGen` is nonzero: were it zero, the constant coefficient of the Eisenstein polynomial
would vanish. -/
private lemma integralGen_ne_zero (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    integralGen hint ≠ 0 := by
  intro h0
  set G : Polynomial 𝒪[K] := minpoly 𝒪[K] x with hG
  have hc0ne : G.coeff 0 ≠ 0 := fun h =>
    hei.notMem (h ▸ zero_mem _)
  have hx0 : x = 0 := by
    have h1 : (integralGen hint : ↥(IntermediateField.adjoin K {x})) = 0 :=
      congrArg Subtype.val h0
    calc x = algebraMap ↥(IntermediateField.adjoin K {x}) (SeparableClosure K)
          (IntermediateField.AdjoinSimple.gen K x) := rfl
      _ = 0 := by
          rw [show IntermediateField.AdjoinSimple.gen K x =
                (integralGen hint : ↥(IntermediateField.adjoin K {x})) from rfl,
            h1, map_zero]
  apply hc0ne
  have h1 : Polynomial.aeval x G = 0 := minpoly.aeval 𝒪[K] x
  rw [hx0] at h1
  have h2 : algebraMap 𝒪[K] (SeparableClosure K) (G.coeff 0) = 0 := by
    rw [← h1, Polynomial.aeval_def, Polynomial.eval₂_at_zero]
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  have hinj : Function.Injective (algebraMap 𝒪[K] (SeparableClosure K)) := by
    rw [IsScalarTower.algebraMap_eq 𝒪[K] K (SeparableClosure K)]
    exact (algebraMap K (SeparableClosure K)).injective.comp (IsFractionRing.injective 𝒪[K] K)
  exact hinj (by rw [h2, map_zero])


-- @@ L475-500 verbatim
omit [IsUniformAddGroup K] in
/-- The ideal generated by `integralGen` is maximal—via the presentation of `integers L` as
`𝒪[K][X]` modulo `(G)` and the residue map at the constant coefficient. -/
theorem isMaximal_span_integralGen (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    (Ideal.span {integralGen hint}).IsMaximal := by
  obtain ⟨ξ₀, u, hξ₀val, hu, hbu⟩ := exists_unit_relation hπ hint hei
  have hξ₀ : ξ₀ = integralGen hint := Subtype.ext hξ₀val
  subst hξ₀
  refine isMaximal_span_of_aeval_surjective (g := minpoly 𝒪[K] x)
    (aeval_integralGen_surjective hπ hint hei) (ker_aeval_integralGen hint) ?_ ?_
  · rw [hπ.maximalIdeal_eq]
    exact Ideal.span_singleton_eq_span_singleton.mpr (associated_pi_coeff_zero hπ hint hei)
  · rw [Ideal.mem_span_singleton]
    obtain ⟨w, hw⟩ := hu
    obtain ⟨m, hm⟩ : ∃ m, (minpoly 𝒪[K] x).natDegree = m + 1 :=
      ⟨(minpoly 𝒪[K] x).natDegree - 1, by have := minpoly.natDegree_pos hint; omega⟩
    refine ⟨-(integralGen hint ^ m * ↑w⁻¹), ?_⟩
    have h1 : algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))
        ((minpoly 𝒪[K] x).coeff 0) = -(integralGen hint) ^ (minpoly 𝒪[K] x).natDegree * ↑w⁻¹ := by
      calc algebraMap 𝒪[K] _ ((minpoly 𝒪[K] x).coeff 0)
          = algebraMap 𝒪[K] _ ((minpoly 𝒪[K] x).coeff 0) * ↑w * ↑w⁻¹ := by
            rw [mul_assoc, ← Units.val_mul, mul_inv_cancel, Units.val_one, mul_one]
        _ = -(integralGen hint) ^ (minpoly 𝒪[K] x).natDegree * ↑w⁻¹ := by rw [hw, hbu]
    rw [h1, hm]
    ring


-- @@ L502-543 verbatim
omit [IsUniformAddGroup K] in
/-- Every maximal ideal of the integral closure is `(integralGen)`: it lies over `𝓂[K]`, hence
contains the constant coefficient, hence—by the Eisenstein unit relation—the generator. -/
theorem eq_span_integralGen_of_isMaximal (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    {Q : Ideal ↥(integers (IntermediateField.adjoin K {x}))} (hQ : Q.IsMaximal) :
    Q = Ideal.span {integralGen hint} := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  have : FiniteDimensional K ↥(IntermediateField.adjoin K {x}) :=
    (IntermediateField.adjoin.powerBasis hint.tower_top).finite
  have hIC : IsIntegralClosure ↥(integers (IntermediateField.adjoin K {x})) ↥𝒪[K]
      ↥(IntermediateField.adjoin K {x}) :=
    inferInstanceAs (IsIntegralClosure
      ↥(integralClosure ↥𝒪[K] ↥(IntermediateField.adjoin K {x})) ↥𝒪[K]
      ↥(IntermediateField.adjoin K {x}))
  have hInt : Algebra.IsIntegral ↥𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) :=
    IsIntegralClosure.isIntegral_algebra ↥𝒪[K] (A := ↥(integers (IntermediateField.adjoin K {x})))
      ↥(IntermediateField.adjoin K {x})
  have := hQ
  have hcom : Ideal.comap (algebraMap ↥𝒪[K]
      ↥(integers (IntermediateField.adjoin K {x}))) Q = 𝓂[K] :=
    IsLocalRing.eq_maximalIdeal (Ideal.isMaximal_under_of_isIntegral_of_isMaximal Q)
  have hc0m : (minpoly 𝒪[K] x).coeff 0 ∈ 𝓂[K] := by
    have h1 := hei.mem (minpoly.natDegree_pos hint)
    rw [Ideal.submodule_span_eq] at h1
    rwa [hπ.maximalIdeal_eq]
  have hc0Q : algebraMap ↥𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))
      ((minpoly 𝒪[K] x).coeff 0) ∈ Q := by
    rw [← hcom] at hc0m
    exact hc0m
  obtain ⟨ξ₀, u, hξ₀val, hu, hbu⟩ := exists_unit_relation hπ hint hei
  have hξ₀ : ξ₀ = integralGen hint := Subtype.ext hξ₀val
  subst hξ₀
  have hpow : integralGen hint ^ (minpoly 𝒪[K] x).natDegree ∈ Q := by
    have h1 : -(integralGen hint ^ (minpoly 𝒪[K] x).natDegree) ∈ Q := by
      rw [← hbu]
      exact Ideal.mul_mem_right _ _ hc0Q
    exact (Ideal.neg_mem_iff Q).mp h1
  have hξQ : integralGen hint ∈ Q := hQ.isPrime.mem_of_pow_mem _ hpow
  exact ((isMaximal_span_integralGen hπ hint hei).eq_of_le hQ.ne_top
    ((Ideal.span_singleton_le_iff_mem _).mpr hξQ)).symm


-- @@ L545-552 verbatim
omit [IsUniformAddGroup K] in
/-- The integral closure is local: `(integralGen)` is its unique maximal ideal. -/
theorem isLocalRing_integers (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    IsLocalRing ↥(integers (IntermediateField.adjoin K {x})) :=
  IsLocalRing.of_unique_max_ideal ⟨Ideal.span {integralGen hint},
    isMaximal_span_integralGen hπ hint hei,
    fun _ hQ => eq_span_integralGen_of_isMaximal hπ hint hei hQ⟩


-- @@ L554-575 verbatim
omit [IsUniformAddGroup K] in
/-- The interleaving identity equating `(ξ) ^ n` with `π` times the integral closure, from the
Eisenstein unit relation `c₀ * u = -ξ ^ n` and the association of `c₀` with `π`. -/
theorem span_integralGen_pow_eq (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Ideal.span {integralGen hint} ^ (minpoly 𝒪[K] x).natDegree =
      Ideal.span {algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) π} := by
  obtain ⟨ξ₀, u, hξ₀val, hu, hbu⟩ := exists_unit_relation hπ hint hei
  have hξ₀ : ξ₀ = integralGen hint := Subtype.ext hξ₀val
  subst hξ₀
  have h1 : Associated (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))
      ((minpoly 𝒪[K] x).coeff 0)) (integralGen hint ^ (minpoly 𝒪[K] x).natDegree) := by
    obtain ⟨w, hw⟩ := hu
    have h2 : Associated (algebraMap 𝒪[K] _ ((minpoly 𝒪[K] x).coeff 0))
        (-(integralGen hint ^ (minpoly 𝒪[K] x).natDegree)) := ⟨w, by rw [hw]; exact hbu⟩
    exact h2.trans ⟨-1, by simp⟩
  have h2 : Associated (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) π)
      (algebraMap 𝒪[K] _ ((minpoly 𝒪[K] x).coeff 0)) :=
    (associated_pi_coeff_zero hπ hint hei).map
      (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})))
  rw [Ideal.span_singleton_pow]
  exact (Ideal.span_singleton_eq_span_singleton.mpr ((h2.trans h1).symm))


-- @@ L577-604 verbatim
omit [IsUniformAddGroup K] in
/-- The integral closure is a discrete valuation ring: local by `isLocalRing_integers`, Dedekind by
Krull–Akizuki, not a field since `integralGen ≠ 0` generates the maximal ideal. -/
theorem isDiscreteValuationRing_integers (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x})) := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  have : FiniteDimensional K ↥(IntermediateField.adjoin K {x}) :=
    (IntermediateField.adjoin.powerBasis hint.tower_top).finite
  have hIC : IsIntegralClosure ↥(integers (IntermediateField.adjoin K {x})) ↥𝒪[K]
      ↥(IntermediateField.adjoin K {x}) :=
    inferInstanceAs (IsIntegralClosure
      ↥(integralClosure ↥𝒪[K] ↥(IntermediateField.adjoin K {x})) ↥𝒪[K]
      ↥(IntermediateField.adjoin K {x}))
  have hDed : IsDedekindDomain ↥(integers (IntermediateField.adjoin K {x})) :=
    IsIntegralClosure.isDedekindDomain ↥𝒪[K] K ↥(IntermediateField.adjoin K {x})
      ↥(integers (IntermediateField.adjoin K {x}))
  have hLoc : IsLocalRing ↥(integers (IntermediateField.adjoin K {x})) :=
    isLocalRing_integers hπ hint hei
  have hmax : IsLocalRing.maximalIdeal ↥(integers (IntermediateField.adjoin K {x})) =
      Ideal.span {integralGen hint} :=
    (IsLocalRing.eq_maximalIdeal (isMaximal_span_integralGen hπ hint hei)).symm
  have hnf : ¬ IsField ↥(integers (IntermediateField.adjoin K {x})) := by
    rw [IsLocalRing.isField_iff_maximalIdeal_eq, hmax, Ideal.span_singleton_eq_bot]
    exact integralGen_ne_zero hint hei
  exact ((IsDiscreteValuationRing.TFAE ↥(integers (IntermediateField.adjoin K {x}))
    hnf).out 1 3).mpr hDed


-- @@ L606-674 verbatim
/-- The integral closure is complete for its maximal-adic topology.
`IsHausdorff` is Krull intersection; for `IsPrecomplete`, a coherent sequence for the powers of
`(integralGen)` is, along the subsequence of indices `n * m`, coherent for the powers of `𝓂[K]`—by
the interleaving of `(ξ) ^ n` with `π` times the integral closure—and the free module `𝒪[K]`-basis
of `basisOfEisenstein` produces the limit coefficientwise from `isAdicComplete_integer`. -/
theorem isAdicComplete_span_integralGen (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    IsAdicComplete (Ideal.span {integralGen hint})
      ↥(integers (IntermediateField.adjoin K {x})) := by
  classical
  set N := (minpoly 𝒪[K] x).natDegree with hN
  have hNpos : 0 < N := minpoly.natDegree_pos hint
  -- the two adic filtrations interleave
  have hEQ : ∀ m : ℕ, Ideal.map (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})))
      (𝓂[K] ^ m) = Ideal.span {integralGen hint} ^ (N * m) := by
    intro m
    rw [Ideal.map_pow, hπ.maximalIdeal_eq, Ideal.map_span, Set.image_singleton,
      ← span_integralGen_pow_eq hπ hint hei, ← pow_mul]
  rw [isAdicComplete_iff]
  constructor
  · -- `IsHausdorff`
    have := isLocalRing_integers hπ hint hei
    have : IsFractionRing 𝒪[K] K :=
      inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
    have : FiniteDimensional K ↥(IntermediateField.adjoin K {x}) :=
      (IntermediateField.adjoin.powerBasis hint.tower_top).finite
    have hIC : IsIntegralClosure ↥(integers (IntermediateField.adjoin K {x})) ↥𝒪[K]
        ↥(IntermediateField.adjoin K {x}) :=
      inferInstanceAs (IsIntegralClosure
        ↥(integralClosure ↥𝒪[K] ↥(IntermediateField.adjoin K {x})) ↥𝒪[K]
        ↥(IntermediateField.adjoin K {x}))
    have hDed : IsDedekindDomain ↥(integers (IntermediateField.adjoin K {x})) :=
      IsIntegralClosure.isDedekindDomain ↥𝒪[K] K ↥(IntermediateField.adjoin K {x})
        ↥(integers (IntermediateField.adjoin K {x}))
    constructor
    intro z hz
    have h1 : z ∈ ⨅ j : ℕ, Ideal.span {integralGen hint} ^ j :=
      Submodule.mem_iInf _ |>.mpr fun j => by
        have h2 := (smodEq_iff_sub_mem _ _ _).mp (hz j)
        rwa [sub_zero] at h2
    rwa [Ideal.iInf_pow_eq_bot_of_isLocalRing _
      (isMaximal_span_integralGen hπ hint hei).ne_top, Submodule.mem_bot] at h1
  · -- `IsPrecomplete`
    constructor
    intro s hs
    have hpreM : IsPrecomplete 𝓂[K] ↥(integers (IntermediateField.adjoin K {x})) :=
      isPrecomplete_of_basis _ (basisOfEisenstein hπ hint hei)
        (isAdicComplete_integer K).toIsPrecomplete
    have hmem_iff : ∀ (m : ℕ) (z : ↥(integers (IntermediateField.adjoin K {x}))),
        z ∈ (𝓂[K] ^ m • ⊤ : Submodule 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))) ↔
          z ∈ Ideal.span {integralGen hint} ^ (N * m) := by
      intro m z
      rw [Ideal.smul_top_eq_map, Submodule.restrictScalars_mem, hEQ m]
    have hconsis : ∀ {m j : ℕ}, m ≤ j → s (N * m) ≡ s (N * j)
        [SMOD (𝓂[K] ^ m • ⊤ : Submodule 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})))] := by
      intro m j hmj
      rw [SModEq.sub_mem, hmem_iff]
      exact (smodEq_iff_sub_mem _ _ _).mp (hs (Nat.mul_le_mul_left N hmj))
    obtain ⟨z, hz⟩ := hpreM.prec fun {m j} hmj => hconsis hmj
    refine ⟨z, fun j => ?_⟩
    rw [smodEq_iff_sub_mem]
    have h1 : s j - s (N * j) ∈ Ideal.span {integralGen hint} ^ j :=
      (smodEq_iff_sub_mem _ _ _).mp (hs (Nat.le_mul_of_pos_left j hNpos))
    have h2 : s (N * j) - z ∈ Ideal.span {integralGen hint} ^ j := by
      have h3 := hz j
      rw [SModEq.sub_mem, hmem_iff] at h3
      exact Ideal.pow_le_pow_right (Nat.le_mul_of_pos_left j hNpos) h3
    have h4 := add_mem h1 h2
    rwa [sub_add_sub_cancel] at h4


-- @@ L676-676 verbatim
/-! ## Quantitative Newton iteration over a complete discrete valuation ring -/


-- @@ L678-678 verbatim
section Newton


-- @@ L680-680 verbatim
open IsDiscreteValuationRing


-- @@ L682-682 verbatim
variable {A : Type*} [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]


-- @@ L684-689 verbatim
/-- Membership in a power of the maximal ideal of a DVR reads on the additive valuation. -/
private lemma mem_maximalIdeal_pow_iff_le_addVal (m : ℕ) (z : A) :
    z ∈ IsLocalRing.maximalIdeal A ^ m ↔ (m : ℕ∞) ≤ addVal A z := by
  obtain ⟨ϖ, hϖ⟩ := IsDiscreteValuationRing.exists_irreducible A
  rw [hϖ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton,
    ← hϖ.addVal_pow, addVal_le_iff_dvd]


-- @@ L691-695 verbatim
/-- The additive valuation is insensitive to sign. -/
private lemma addVal_neg (z : A) : addVal A (-z) = addVal A z := by
  have h1 : addVal A (-z) = addVal A (-1) + addVal A z := by
    rw [← addVal_mul, neg_one_mul]
  rw [h1, addVal_eq_zero_iff.mpr isUnit_one.neg, zero_add]


-- @@ L697-699 verbatim
/-- The additive valuation is insensitive to the order of a difference. -/
private lemma addVal_sub_swap (a b : A) : addVal A (a - b) = addVal A (b - a) := by
  rw [← neg_sub, addVal_neg]


-- @@ L701-703 verbatim
/-- Divisibility bounds the additive valuation from below. -/
private lemma le_addVal_of_dvd {a b : A} (h : a ∣ b) : addVal A a ≤ addVal A b :=
  addVal_le_iff_dvd.mpr h


-- @@ L705-712 verbatim
/-- An `ℕ∞` value that dominates every natural number is `⊤`. -/
private lemma eq_top_of_forall_le {w : ℕ∞} (h : ∀ j : ℕ, (j : ℕ∞) ≤ w) : w = ⊤ := by
  cases w with
  | top => rfl
  | coe w =>
    have h1 := h (w + 1)
    rw [Nat.cast_le] at h1
    omega


-- @@ L714-722 verbatim
/-- Cancellation in `ℕ∞`: from `b ≤ a + w` with naturals `a ≤ b`, conclude `b - a ≤ w`. -/
private lemma sub_le_of_le_add {a b : ℕ} (w : ℕ∞) (h : (b : ℕ∞) ≤ (a : ℕ∞) + w) :
    ((b - a : ℕ) : ℕ∞) ≤ w := by
  cases w with
  | top => exact le_top
  | coe w =>
    rw [← Nat.cast_add, Nat.cast_le] at h
    rw [Nat.cast_le]
    omega


-- @@ L724-914 verbatim
/-- Quantitative Newton–Hensel over a complete discrete valuation ring: a point where `F` vanishes
to order more than twice that of its derivative converges under the Newton iteration to an exact
root, at distance of order the difference of the two. The conclusion is stated additively—the order
of `F` at `y₀` is at most that of its derivative plus that of `z - y₀`—to stay subtraction-free in
`ℕ∞`. -/
theorem exists_isRoot (hc : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (F : Polynomial A) (y₀ : A)
    (hlt : addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) +
        addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) <
      addVal A (Polynomial.eval y₀ F)) :
    ∃ z : A, F.IsRoot z ∧
      addVal A (Polynomial.eval y₀ F) ≤
        addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) + addVal A (z - y₀) := by
  classical
  -- the finite order `γ` of the derivative
  have hγtop : addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) ≠ ⊤ := by
    intro h
    rw [h, top_add] at hlt
    exact absurd hlt not_top_lt
  obtain ⟨γ, hγ⟩ : ∃ γ : ℕ, addVal A (Polynomial.eval y₀ (Polynomial.derivative F)) = γ := by
    obtain ⟨γ, hγ⟩ := WithTop.ne_top_iff_exists.mp hγtop
    exact ⟨γ, hγ.symm⟩
  by_cases h0 : Polynomial.eval y₀ F = 0
  · refine ⟨y₀, h0, ?_⟩
    rw [sub_self, addVal_zero]
    exact le_top.trans_eq (add_top _).symm
  -- the finite order `h₀` of the value, with the gap `2γ + 1 ≤ h₀`
  obtain ⟨h₀, hh₀⟩ : ∃ m : ℕ, addVal A (Polynomial.eval y₀ F) = m := by
    obtain ⟨m, hm⟩ := WithTop.ne_top_iff_exists.mp (addVal_eq_top_iff.not.mpr h0)
    exact ⟨m, hm.symm⟩
  have hgap : 2 * γ + 1 ≤ h₀ := by
    rw [hγ, hh₀, ← Nat.cast_add, Nat.cast_lt] at hlt
    omega
  -- the Newton step: subtract the exact quotient `F y / F' y` when it exists
  set step : A → A := fun y =>
    if h : Polynomial.eval y (Polynomial.derivative F) ∣ Polynomial.eval y F then y - h.choose
    else y with hstepdef
  set c : ℕ → A := fun j => step^[j] y₀ with hcdef
  have hc0 : c 0 = y₀ := rfl
  have hcsucc : ∀ j, c (j + 1) = step (c j) := fun j => Function.iterate_succ_apply' step j y₀
  -- one Newton step from a point of derivative order `≤ γ` and value order `≥ m ≥ 2γ + 1`
  have hstep : ∀ (y : A) (m : ℕ), addVal A (Polynomial.eval y (Polynomial.derivative F)) ≤ γ →
      (m : ℕ∞) ≤ addVal A (Polynomial.eval y F) → 2 * γ + 1 ≤ m →
      addVal A (Polynomial.eval (step y) (Polynomial.derivative F)) ≤ γ ∧
        (((m - γ) + (m - γ) : ℕ) : ℕ∞) ≤ addVal A (Polynomial.eval (step y) F) ∧
        (((m - γ) : ℕ) : ℕ∞) ≤ addVal A (step y - y) := by
    intro y m hder hval hm
    have hFne : Polynomial.eval y (Polynomial.derivative F) ≠ 0 := by
      intro h
      rw [h, addVal_zero] at hder
      simp at hder
    have hdvd : Polynomial.eval y (Polynomial.derivative F) ∣ Polynomial.eval y F := by
      rw [← addVal_le_iff_dvd]
      refine hder.trans (le_trans ?_ hval)
      rw [Nat.cast_le]
      omega
    obtain ⟨t, ht⟩ := id hdvd
    have hteq : hdvd.choose = t :=
      mul_left_cancel₀ hFne (hdvd.choose_spec.symm.trans ht)
    have hstepy : step y = y - t := by
      have h1 : step y = y - hdvd.choose := by
        simp only [hstepdef]
        rw [dite_eq_left hdvd]
      rw [h1, hteq]
    -- the order of the quotient
    have hvt : (((m - γ) : ℕ) : ℕ∞) ≤ addVal A t := by
      refine sub_le_of_le_add _ ?_
      calc (m : ℕ∞) ≤ addVal A (Polynomial.eval y F) := hval
        _ = addVal A (Polynomial.eval y (Polynomial.derivative F)) + addVal A t := by
            rw [ht, addVal_mul]
        _ ≤ (γ : ℕ∞) + addVal A t := add_le_add hder le_rfl
    have hincr : (((m - γ) : ℕ) : ℕ∞) ≤ addVal A (step y - y) := by
      rw [hstepy, sub_sub_cancel_left, addVal_neg]
      exact hvt
    -- Taylor expansion around `y` with increment `-t`
    obtain ⟨k, hk⟩ := F.binomExpansion y (-t)
    have heval : Polynomial.eval (step y) F = k * (t * t) := by
      rw [hstepy, sub_eq_add_neg, hk, ht]
      ring
    refine ⟨?_, ?_, hincr⟩
    · -- the derivative order survives the step
      by_contra hgt
      rw [not_le] at hgt
      have h1 : step y - y ∣ Polynomial.eval (step y) (Polynomial.derivative F) -
          Polynomial.eval y (Polynomial.derivative F) :=
        Polynomial.sub_dvd_eval_sub _ _ _
      have h2 : (γ : ℕ∞) < addVal A (Polynomial.eval (step y) (Polynomial.derivative F) -
          Polynomial.eval y (Polynomial.derivative F)) := by
        refine lt_of_lt_of_le ?_ ((le_addVal_of_dvd h1).trans' hincr)
        rw [Nat.cast_lt]
        omega
      have h3 : (γ : ℕ∞) < addVal A (Polynomial.eval y (Polynomial.derivative F)) := by
        have h4 : Polynomial.eval y (Polynomial.derivative F) =
            Polynomial.eval (step y) (Polynomial.derivative F) -
              (Polynomial.eval (step y) (Polynomial.derivative F) -
                Polynomial.eval y (Polynomial.derivative F)) := by ring
        rw [h4, sub_eq_add_neg]
        refine lt_of_lt_of_le (lt_min hgt ?_) (addVal_add)
        rwa [addVal_neg]
      exact absurd (h3.trans_le hder) (lt_irrefl _)
    · -- the value order doubles
      rw [heval]
      calc (((m - γ) + (m - γ) : ℕ) : ℕ∞)
          = ((m - γ : ℕ) : ℕ∞) + ((m - γ : ℕ) : ℕ∞) := by rw [← Nat.cast_add]
        _ ≤ addVal A t + addVal A t := add_le_add hvt hvt
        _ = addVal A (t * t) := (addVal_mul).symm
        _ ≤ addVal A k + addVal A (t * t) := le_add_self
        _ = addVal A (k * (t * t)) := (addVal_mul).symm
  -- the invariant along the iteration
  have hinv : ∀ j : ℕ, addVal A (Polynomial.eval (c j) (Polynomial.derivative F)) ≤ γ ∧
      ((h₀ + j : ℕ) : ℕ∞) ≤ addVal A (Polynomial.eval (c j) F) := by
    intro j
    induction j with
    | zero => exact ⟨by rw [hc0, hγ], by rw [hc0, hh₀]; exact_mod_cast le_rfl⟩
    | succ j ih =>
      obtain ⟨ih1, ih2⟩ := ih
      obtain ⟨h1, h2, _⟩ := hstep (c j) (h₀ + j) ih1 ih2 (by omega)
      rw [← hcsucc j] at h1 h2
      refine ⟨h1, le_trans ?_ h2⟩
      rw [Nat.cast_le]
      omega
  have hincr : ∀ j : ℕ, ((h₀ - γ + j : ℕ) : ℕ∞) ≤ addVal A (c (j + 1) - c j) := by
    intro j
    obtain ⟨h1, h2⟩ := hinv j
    obtain ⟨_, _, h3⟩ := hstep (c j) (h₀ + j) h1 h2 (by omega)
    rw [← hcsucc j] at h3
    refine le_trans ?_ h3
    rw [Nat.cast_le]
    omega
  -- the telescoped Cauchy estimate
  have hcauchy : ∀ {m j : ℕ}, m ≤ j → ((h₀ - γ + m : ℕ) : ℕ∞) ≤ addVal A (c j - c m) := by
    intro m j hmj
    induction j, hmj using Nat.le_induction with
    | base => rw [sub_self, addVal_zero]; exact le_top
    | succ j hmj ih =>
      have h1 : c (j + 1) - c m = (c (j + 1) - c j) + (c j - c m) := by ring
      have h2 : ((h₀ - γ + m : ℕ) : ℕ∞) ≤ addVal A (c (j + 1) - c j) := by
        refine le_trans ?_ (hincr j)
        rw [Nat.cast_le]
        omega
      rw [h1]
      exact le_trans (le_min h2 ih) (addVal_add)
  -- the limit through `IsPrecomplete`
  have hcons : ∀ {m j : ℕ}, m ≤ j →
      c m ≡ c j [SMOD (IsLocalRing.maximalIdeal A ^ m • ⊤ : Ideal A)] := by
    intro m j hmj
    rw [← Ideal.one_eq_top, smul_eq_mul, mul_one, SModEq.sub_mem,
      mem_maximalIdeal_pow_iff_le_addVal, addVal_sub_swap]
    refine le_trans ?_ (hcauchy hmj)
    rw [Nat.cast_le]
    omega
  obtain ⟨z, hz⟩ := hc.toIsPrecomplete.prec fun {m j} hmj => hcons hmj
  have hzdist : ∀ j : ℕ, (j : ℕ∞) ≤ addVal A (z - c j) := by
    intro j
    have h1 := hz j
    rw [← Ideal.one_eq_top, smul_eq_mul, mul_one, SModEq.sub_mem,
      mem_maximalIdeal_pow_iff_le_addVal] at h1
    rwa [addVal_sub_swap]
  -- the limit is a root
  have hroot : F.IsRoot z := by
    rw [Polynomial.IsRoot, ← addVal_eq_top_iff]
    refine eq_top_of_forall_le fun j => ?_
    have h1 : Polynomial.eval z F =
        (Polynomial.eval z F - Polynomial.eval (c j) F) + Polynomial.eval (c j) F := by ring
    have h2 : (j : ℕ∞) ≤ addVal A (Polynomial.eval z F - Polynomial.eval (c j) F) :=
      le_trans (hzdist j) (le_addVal_of_dvd (Polynomial.sub_dvd_eval_sub _ _ _))
    have h3 : (j : ℕ∞) ≤ addVal A (Polynomial.eval (c j) F) := by
      refine le_trans ?_ (hinv j).2
      rw [Nat.cast_le]
      omega
    rw [h1]
    exact le_trans (le_min h2 h3) (addVal_add)
  -- the distance to the starting point
  have hdist : ((h₀ - γ : ℕ) : ℕ∞) ≤ addVal A (z - y₀) := by
    have h1 : z - y₀ = (z - c h₀) + (c h₀ - c 0) := by rw [hc0]; ring
    have h2 : ((h₀ - γ : ℕ) : ℕ∞) ≤ addVal A (z - c h₀) := by
      refine le_trans ?_ (hzdist h₀)
      rw [Nat.cast_le]
      omega
    have h3 : ((h₀ - γ : ℕ) : ℕ∞) ≤ addVal A (c h₀ - c 0) := by
      refine le_trans ?_ (hcauchy (Nat.zero_le h₀))
      rw [Nat.cast_le]
      omega
    rw [h1]
    exact le_trans (le_min h2 h3) (addVal_add)
  refine ⟨z, hroot, ?_⟩
  rw [hh₀, hγ]
  calc (h₀ : ℕ∞) ≤ (γ : ℕ∞) + ((h₀ - γ : ℕ) : ℕ∞) := by
        rw [← Nat.cast_add, Nat.cast_le]
        omega
    _ ≤ (γ : ℕ∞) + addVal A (z - y₀) := add_le_add le_rfl hdist


-- @@ L916-934 verbatim
/-- The form of the Newton lemma used by the count comparison: at a point where `F` vanishes to
order at least `2 * Γ + 1` while its derivative has order at most `Γ`, there is a root at distance
of order at least `Γ + 1`. -/
theorem exists_isRoot_near (hc : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    {F : Polynomial A} {w : A} {Γ : ℕ}
    (hval : ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ addVal A (Polynomial.eval w F))
    (hder : addVal A (Polynomial.eval w (Polynomial.derivative F)) ≤ (Γ : ℕ∞)) :
    ∃ z : A, F.IsRoot z ∧ ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal A (z - w) := by
  obtain ⟨z, hz, hd⟩ := exists_isRoot hc F w (by
    refine lt_of_le_of_lt (add_le_add hder hder) (lt_of_lt_of_le ?_ hval)
    rw [← Nat.cast_add, Nat.cast_lt]
    omega)
  refine ⟨z, hz, ?_⟩
  have h1 : ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ (Γ : ℕ∞) + addVal A (z - w) :=
    hval.trans (hd.trans (add_le_add hder le_rfl))
  have h2 := sub_le_of_le_add (a := Γ) (b := 2 * Γ + 1) (addVal A (z - w)) h1
  refine le_trans ?_ h2
  rw [Nat.cast_le]
  omega


-- @@ L936-960 verbatim
/-- Root separation: two distinct roots of a polynomial lie no closer than the order of the
derivative at either—from the factorization `F = (X - y) * q`, the identity giving the derivative
at `y` as `q` evaluated at `y`, and the divisibility of `q y - q y'` by `y - y'`. -/
theorem addVal_sub_le_of_isRoot {F : Polynomial A} {y y' : A}
    (hy : F.IsRoot y) (hy' : F.IsRoot y') (hne : y ≠ y') :
    addVal A (y - y') ≤ addVal A (Polynomial.eval y (Polynomial.derivative F)) := by
  obtain ⟨q, hq⟩ := Polynomial.dvd_iff_isRoot.mpr hy
  have hq' : Polynomial.eval y' q = 0 := by
    have h1 : (y' - y) * Polynomial.eval y' q = 0 := by
      have h2 := hy'
      rw [Polynomial.IsRoot, hq, Polynomial.eval_mul, Polynomial.eval_sub,
        Polynomial.eval_X, Polynomial.eval_C] at h2
      exact h2
    rcases mul_eq_zero.mp h1 with h | h
    · exact absurd (sub_eq_zero.mp h).symm hne
    · exact h
  have hd : Polynomial.eval y (Polynomial.derivative F) = Polynomial.eval y q := by
    rw [hq, Polynomial.derivative_mul, Polynomial.eval_add, Polynomial.eval_mul,
      Polynomial.eval_mul]
    simp
  rw [hd]
  have h1 : y - y' ∣ Polynomial.eval y q := by
    have h2 := Polynomial.sub_dvd_eval_sub y y' q
    rwa [hq', sub_zero] at h2
  exact le_addVal_of_dvd h1


-- @@ L962-970 verbatim
/-- Elements of `(ϖa ^ T)` have order at least `T`, once `ϖa` has positive order. -/
theorem le_addVal_of_mem_span_pow {ϖa : A} (h1 : (1 : ℕ∞) ≤ addVal A ϖa) {T : ℕ} {z : A}
    (hz : z ∈ Ideal.span {ϖa ^ T}) : (T : ℕ∞) ≤ addVal A z := by
  rw [Ideal.mem_span_singleton] at hz
  obtain ⟨w, rfl⟩ := hz
  rw [addVal_mul, addVal_pow, nsmul_eq_mul]
  refine le_trans ?_ le_self_add
  calc (T : ℕ∞) = (T : ℕ∞) * 1 := (mul_one _).symm
    _ ≤ (T : ℕ∞) * addVal A ϖa := mul_le_mul_right h1 _


-- @@ L972-978 verbatim
omit [IsDomain A] [IsDiscreteValuationRing A] in
/-- A polynomial with all coefficients in `(ϖa ^ T)` evaluates into `(ϖa ^ T)`. -/
theorem eval_mem_span_pow {ϖa : A} {T : ℕ} {P : Polynomial A}
    (hP : ∀ i, P.coeff i ∈ Ideal.span {ϖa ^ T}) (w : A) :
    Polynomial.eval w P ∈ Ideal.span {ϖa ^ T} := by
  rw [Polynomial.eval_eq_sum, Polynomial.sum_def]
  exact Ideal.sum_mem _ fun i _ => Ideal.mul_mem_right _ _ (hP i)


-- @@ L980-980 verbatim
end Newton


-- @@ L982-982 verbatim
/-! ## The Bézout certificate of separability and the count comparison -/


-- @@ L984-996 verbatim
/-- A root where the derivative does not vanish is simple. -/
private lemma rootMultiplicity_le_one_of_derivative {R : Type*} [CommRing R]
    {p : Polynomial R} (hp : p ≠ 0) {y : R}
    (hd : Polynomial.eval y (Polynomial.derivative p) ≠ 0) :
    p.rootMultiplicity y ≤ 1 := by
  rw [Polynomial.rootMultiplicity_le_iff hp]
  intro hdvd
  obtain ⟨q, hq⟩ := hdvd
  apply hd
  rw [hq]
  simp [Polynomial.derivative_mul, Polynomial.derivative_pow, Polynomial.eval_mul,
    Polynomial.eval_add, Polynomial.eval_pow, Polynomial.eval_sub, Polynomial.eval_X,
    Polynomial.eval_C, sub_self]


-- @@ L998-1024 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- A polynomial separable over the fraction field `K` admits a Bézout certificate over `𝒪[K]`
itself: `U * f + V * f' = β` with `β ≠ 0`, by clearing the denominators of a coprimality witness. -/
theorem exists_bezout {f : Polynomial 𝒪[K]}
    (hfsep : (f.map (algebraMap 𝒪[K] K)).Separable) :
    ∃ (U V : Polynomial 𝒪[K]) (β : 𝒪[K]), β ≠ 0 ∧
      U * f + V * Polynomial.derivative f = Polynomial.C β := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  obtain ⟨u, v, huv⟩ := hfsep
  obtain ⟨bu, hbu0, hbu⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors 𝒪[K]) u
  obtain ⟨bv, hbv0, hbv⟩ := IsLocalization.integerNormalization_spec (nonZeroDivisors 𝒪[K]) v
  refine ⟨Polynomial.C (bv : 𝒪[K]) *
      IsLocalization.integerNormalization (nonZeroDivisors 𝒪[K]) u,
    Polynomial.C (bu : 𝒪[K]) *
      IsLocalization.integerNormalization (nonZeroDivisors 𝒪[K]) v,
    (bu : 𝒪[K]) * (bv : 𝒪[K]),
    mul_ne_zero (nonZeroDivisors.ne_zero hbu0) (nonZeroDivisors.ne_zero hbv0), ?_⟩
  apply Polynomial.map_injective (algebraMap 𝒪[K] K) (IsFractionRing.injective 𝒪[K] K)
  have hsmul : ∀ (b : 𝒪[K]) (p : Polynomial K),
      b • p = Polynomial.C (algebraMap 𝒪[K] K b) * p := by
    intro b p
    rw [← Polynomial.smul_eq_C_mul, algebraMap_smul]
  simp only [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_C]
  rw [hbu, hbv, ← Polynomial.derivative_map, hsmul, hsmul, map_mul, Polynomial.C_mul]
  linear_combination (Polynomial.C (algebraMap 𝒪[K] K (bu : 𝒪[K])) *
    Polynomial.C (algebraMap 𝒪[K] K (bv : 𝒪[K]))) * huv


-- @@ L1026-1040 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- Evaluating (the base changes of) an `𝒪[K]`-polynomial at an integral element of `L`: the value
inside the integral closure maps to the value inside `L`. -/
private lemma algebraMap_eval_map {L : IntermediateField K (SeparableClosure K)}
    (p : Polynomial 𝒪[K]) {y : ↥L} (hy : y ∈ integers L) :
    algebraMap ↥(integers L) ↥L
        (Polynomial.eval (⟨y, hy⟩ : ↥(integers L))
          (p.map (algebraMap 𝒪[K] ↥(integers L)))) =
      Polynomial.aeval y (p.map (algebraMap 𝒪[K] K)) := by
  have h2 : Polynomial.aeval y p =
      algebraMap ↥(integers L) ↥L (Polynomial.aeval (⟨y, hy⟩ : ↥(integers L)) p) := by
    rw [← Polynomial.aeval_algebraMap_apply]
    rfl
  rw [Polynomial.eval_map, ← Polynomial.aeval_def, Polynomial.aeval_map_algebraMap]
  exact h2.symm


-- @@ L1042-1080 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- A nearby assignment between finite sets is injective when its sources are separated. -/
private theorem card_le_card_of_nearby (L : IntermediateField K (SeparableClosure K))
    [IsDiscreteValuationRing ↥(integers L)] (Γ : ℕ) :
    ∀ s t : Finset ↥L,
    (∀ y ∈ s, ∃ z ∈ t, ∃ (hy : y ∈ integers L)
      (hz : z ∈ integers L),
      ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
        ((⟨z, hz⟩ : ↥(integers L)) - ⟨y, hy⟩)) →
    (∀ y₁ ∈ s, ∀ y₂ ∈ s, y₁ ≠ y₂ →
      ∀ (h₁ : y₁ ∈ integers L)
        (h₂ : y₂ ∈ integers L),
      addVal _ ((⟨y₁, h₁⟩ : ↥(integers L)) - ⟨y₂, h₂⟩) ≤
        (Γ : ℕ∞)) →
    s.card ≤ t.card := by
  classical
  intro s t hex hsep
  choose! zf hzt hzd using hex
  refine Finset.card_le_card_of_injOn zf hzt ?_
  intro y₁ h₁ y₂ h₂ heq
  by_contra hne
  obtain ⟨hy₁, hz₁, hd₁⟩ := hzd y₁ h₁
  obtain ⟨hy₂, hz₂, hd₂⟩ := hzd y₂ h₂
  have h5 : (⟨zf y₁, hz₁⟩ : ↥(integers L)) = ⟨zf y₂, hz₂⟩ :=
    Subtype.ext heq
  have h3 : ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
      ((⟨y₁, hy₁⟩ : ↥(integers L)) - ⟨y₂, hy₂⟩) := by
    have h4 : (⟨y₁, hy₁⟩ : ↥(integers L)) - ⟨y₂, hy₂⟩ =
        -((⟨zf y₁, hz₁⟩ : ↥(integers L)) - ⟨y₁, hy₁⟩) +
          ((⟨zf y₂, hz₂⟩ : ↥(integers L)) - ⟨y₂, hy₂⟩) := by
      rw [h5]
      ring
    rw [h4]
    refine le_trans (le_min ?_ hd₂) addVal_add
    rw [addVal_neg]
    exact hd₁
  have h6 := (h3.trans (hsep y₁ h₁ y₂ h₂ hne hy₁ hy₂))
  rw [Nat.cast_le] at h6
  omega


-- @@ L1082-1280 verbatim
omit [UniformSpace K] [IsUniformAddGroup K] [IsNonarchimedeanLocalField K] in
/-- Mutual Hensel lifts preserve the root count under uniform derivative bounds. -/
private theorem card_aroots_eq_of_bounds (L : IntermediateField K (SeparableClosure K))
    [IsDiscreteValuationRing ↥(integers L)]
    (hAC : IsAdicComplete (IsLocalRing.maximalIdeal ↥(integers L)) ↥(integers L))
    {f g : Polynomial 𝒪[K]} (hfm : f.Monic) (hgm : g.Monic)
    (hfsep : (f.map (algebraMap 𝒪[K] K)).Separable) (Γ : ℕ)
    (hediff : ∀ w : ↥(integers L),
      ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
        (Polynomial.eval w (g.map (algebraMap 𝒪[K] _)) -
          Polynomial.eval w (f.map (algebraMap 𝒪[K] _))))
    (hbound : ∀ w : ↥(integers L),
      ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _ (Polynomial.eval w (f.map (algebraMap 𝒪[K] _))) →
      addVal _ (Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) ≤ (Γ : ℕ∞) ∧
        addVal _ (Polynomial.eval w (Polynomial.derivative (g.map (algebraMap 𝒪[K] _)))) ≤
          (Γ : ℕ∞)) :
    ((g.map (algebraMap 𝒪[K] K)).aroots ↥L).card =
      ((f.map (algebraMap 𝒪[K] K)).aroots ↥L).card := by
  classical
  have hinjL : Function.Injective (algebraMap ↥(integers L) ↥L) := Subtype.val_injective
  -- integrality of roots, and the evaluation bridge
  have hint_of_root : ∀ {p : Polynomial 𝒪[K]}, p.Monic →
      ∀ {y : ↥L},
      Polynomial.aeval y (p.map (algebraMap 𝒪[K] K)) = 0 →
      y ∈ integers L := by
    intro p hpm y hy
    rw [Polynomial.aeval_map_algebraMap] at hy
    exact ⟨p, hpm, hy⟩
  have hzero_iff : ∀ {y : ↥L}
      (hy : y ∈ integers L) (p : Polynomial 𝒪[K]),
      Polynomial.eval (⟨y, hy⟩ : ↥(integers L))
        (p.map (algebraMap 𝒪[K] _)) = 0 ↔
      Polynomial.aeval y (p.map (algebraMap 𝒪[K] K)) = 0 := by
    intro y hy p
    rw [← algebraMap_eval_map p hy]
    constructor
    · intro h
      rw [h, map_zero]
    · intro h
      exact hinjL (by rw [h, map_zero])
  -- the root Finsets in `L`
  have hfK0 : f.map (algebraMap 𝒪[K] K) ≠ 0 := (hfm.map _).ne_zero
  have hgK0 : g.map (algebraMap 𝒪[K] K) ≠ 0 := (hgm.map _).ne_zero
  have hmemF : ∀ y : ↥L,
      y ∈ ((f.map (algebraMap 𝒪[K] K)).aroots ↥L).toFinset ↔
      Polynomial.aeval y (f.map (algebraMap 𝒪[K] K)) = 0 := by
    intro y
    rw [Multiset.mem_toFinset, Polynomial.mem_aroots]
    exact ⟨fun h => h.2, fun h => ⟨hfK0, h⟩⟩
  have hmemG : ∀ y : ↥L,
      y ∈ ((g.map (algebraMap 𝒪[K] K)).aroots ↥L).toFinset ↔
      Polynomial.aeval y (g.map (algebraMap 𝒪[K] K)) = 0 := by
    intro y
    rw [Multiset.mem_toFinset, Polynomial.mem_aroots]
    exact ⟨fun h => h.2, fun h => ⟨hgK0, h⟩⟩
  -- the lifting: from the roots of `f` to the roots of `g`
  have hexFG : ∀ y ∈ ((f.map (algebraMap 𝒪[K] K)).aroots
      ↥L).toFinset,
      ∃ z ∈ ((g.map (algebraMap 𝒪[K] K)).aroots ↥L).toFinset,
      ∃ (hy : y ∈ integers L)
        (hz : z ∈ integers L),
        ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
          ((⟨z, hz⟩ : ↥(integers L)) - ⟨y, hy⟩) := by
    intro y hy
    have hyroot := (hmemF y).mp hy
    have hyint := hint_of_root hfm hyroot
    have hY0 : Polynomial.eval (⟨y, hyint⟩ : ↥(integers L))
        (f.map (algebraMap 𝒪[K] _)) = 0 := (hzero_iff hyint f).mpr hyroot
    have hgval : ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ addVal _ (Polynomial.eval
        (⟨y, hyint⟩ : ↥(integers L))
        (g.map (algebraMap 𝒪[K] _))) := by
      have h1 := hediff ⟨y, hyint⟩
      rwa [hY0, sub_zero] at h1
    have hders := hbound ⟨y, hyint⟩ (by rw [hY0, addVal_zero]; exact le_top)
    obtain ⟨Z, hZroot, hZdist⟩ := exists_isRoot_near hAC hgval hders.2
    refine ⟨(Z : ↥L), ?_, hyint, Z.2, ?_⟩
    · rw [hmemG]
      have h1 : Polynomial.eval Z (g.map (algebraMap 𝒪[K] _)) = 0 := hZroot
      rw [← hzero_iff Z.2 g]
      exact h1
    · exact hZdist
  -- the lifting: from the roots of `g` to the roots of `f`
  have hexGF : ∀ y ∈ ((g.map (algebraMap 𝒪[K] K)).aroots
      ↥L).toFinset,
      ∃ z ∈ ((f.map (algebraMap 𝒪[K] K)).aroots ↥L).toFinset,
      ∃ (hy : y ∈ integers L)
        (hz : z ∈ integers L),
        ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
          ((⟨z, hz⟩ : ↥(integers L)) - ⟨y, hy⟩) := by
    intro y hy
    have hyroot := (hmemG y).mp hy
    have hyint := hint_of_root hgm hyroot
    have hY0 : Polynomial.eval (⟨y, hyint⟩ : ↥(integers L))
        (g.map (algebraMap 𝒪[K] _)) = 0 := (hzero_iff hyint g).mpr hyroot
    have hfval : ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ addVal _ (Polynomial.eval
        (⟨y, hyint⟩ : ↥(integers L))
        (f.map (algebraMap 𝒪[K] _))) := by
      have h1 := hediff ⟨y, hyint⟩
      rw [hY0, zero_sub, addVal_neg] at h1
      exact h1
    have hders := hbound ⟨y, hyint⟩ (le_trans (by rw [Nat.cast_le]; omega) hfval)
    obtain ⟨Z, hZroot, hZdist⟩ := exists_isRoot_near hAC hfval hders.1
    refine ⟨(Z : ↥L), ?_, hyint, Z.2, ?_⟩
    · rw [hmemF]
      have h1 : Polynomial.eval Z (f.map (algebraMap 𝒪[K] _)) = 0 := hZroot
      rw [← hzero_iff Z.2 f]
      exact h1
    · exact hZdist
  -- the separations
  have hsepF : ∀ y₁ ∈ ((f.map (algebraMap 𝒪[K] K)).aroots
      ↥L).toFinset,
      ∀ y₂ ∈ ((f.map (algebraMap 𝒪[K] K)).aroots ↥L).toFinset,
      y₁ ≠ y₂ → ∀ (h₁ : y₁ ∈ integers L)
        (h₂ : y₂ ∈ integers L),
      addVal _ ((⟨y₁, h₁⟩ : ↥(integers L)) - ⟨y₂, h₂⟩) ≤
        (Γ : ℕ∞) := by
    intro y₁ hy₁ y₂ hy₂ hne h₁ h₂
    have hr₁ : Polynomial.IsRoot (f.map (algebraMap 𝒪[K] _))
        (⟨y₁, h₁⟩ : ↥(integers L)) :=
      (hzero_iff h₁ f).mpr ((hmemF y₁).mp hy₁)
    have hr₂ : Polynomial.IsRoot (f.map (algebraMap 𝒪[K] _))
        (⟨y₂, h₂⟩ : ↥(integers L)) :=
      (hzero_iff h₂ f).mpr ((hmemF y₂).mp hy₂)
    have hne' : (⟨y₁, h₁⟩ : ↥(integers L)) ≠ ⟨y₂, h₂⟩ :=
      fun h => hne (congrArg Subtype.val h)
    have hders := hbound ⟨y₁, h₁⟩ (by rw [hr₁.eq_zero, addVal_zero]; exact le_top)
    exact le_trans (addVal_sub_le_of_isRoot hr₁ hr₂ hne') hders.1
  have hsepG : ∀ y₁ ∈ ((g.map (algebraMap 𝒪[K] K)).aroots
      ↥L).toFinset,
      ∀ y₂ ∈ ((g.map (algebraMap 𝒪[K] K)).aroots ↥L).toFinset,
      y₁ ≠ y₂ → ∀ (h₁ : y₁ ∈ integers L)
        (h₂ : y₂ ∈ integers L),
      addVal _ ((⟨y₁, h₁⟩ : ↥(integers L)) - ⟨y₂, h₂⟩) ≤
        (Γ : ℕ∞) := by
    intro y₁ hy₁ y₂ hy₂ hne h₁ h₂
    have hr₁ : Polynomial.IsRoot (g.map (algebraMap 𝒪[K] _))
        (⟨y₁, h₁⟩ : ↥(integers L)) :=
      (hzero_iff h₁ g).mpr ((hmemG y₁).mp hy₁)
    have hr₂ : Polynomial.IsRoot (g.map (algebraMap 𝒪[K] _))
        (⟨y₂, h₂⟩ : ↥(integers L)) :=
      (hzero_iff h₂ g).mpr ((hmemG y₂).mp hy₂)
    have hne' : (⟨y₁, h₁⟩ : ↥(integers L)) ≠ ⟨y₂, h₂⟩ :=
      fun h => hne (congrArg Subtype.val h)
    have hfval : ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _ (Polynomial.eval
        (⟨y₁, h₁⟩ : ↥(integers L))
        (f.map (algebraMap 𝒪[K] _))) := by
      have h3 := hediff ⟨y₁, h₁⟩
      rw [hr₁.eq_zero, zero_sub, addVal_neg] at h3
      refine le_trans ?_ h3
      rw [Nat.cast_le]
      omega
    have hders := hbound ⟨y₁, h₁⟩ hfval
    exact le_trans (addVal_sub_le_of_isRoot hr₁ hr₂ hne') hders.2
  -- both root multisets are duplicate-free
  have hnodupF : ((f.map (algebraMap 𝒪[K] K)).aroots
      ↥L).Nodup :=
    Polynomial.nodup_roots hfsep.map
  have hnodupG : ((g.map (algebraMap 𝒪[K] K)).aroots
      ↥L).Nodup := by
    rw [Multiset.nodup_iff_count_le_one]
    intro y
    rw [Polynomial.aroots_def, Polynomial.count_roots]
    by_cases hy : Polynomial.IsRoot ((g.map (algebraMap 𝒪[K] K)).map
      (algebraMap K ↥L)) y
    · have hy' : Polynomial.aeval y (g.map (algebraMap 𝒪[K] K)) = 0 := by
        rwa [Polynomial.IsRoot, Polynomial.eval_map, ← Polynomial.aeval_def] at hy
      have hyint := hint_of_root hgm hy'
      have hY0 : Polynomial.eval (⟨y, hyint⟩ : ↥(integers L))
          (g.map (algebraMap 𝒪[K] _)) = 0 := (hzero_iff hyint g).mpr hy'
      have hfval : ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _ (Polynomial.eval
          (⟨y, hyint⟩ : ↥(integers L))
          (f.map (algebraMap 𝒪[K] _))) := by
        have h3 := hediff ⟨y, hyint⟩
        rw [hY0, zero_sub, addVal_neg] at h3
        refine le_trans ?_ h3
        rw [Nat.cast_le]
        omega
      have hders := hbound ⟨y, hyint⟩ hfval
      have hgne : Polynomial.eval (⟨y, hyint⟩ : ↥(integers L))
          (Polynomial.derivative (g.map (algebraMap 𝒪[K] _))) ≠ 0 := by
        intro h
        rw [h, addVal_zero] at hders
        exact absurd (top_le_iff.mp (le_top.trans hders.2)) (by simp)
      have hd : Polynomial.eval y (Polynomial.derivative ((g.map (algebraMap 𝒪[K] K)).map
          (algebraMap K ↥L))) ≠ 0 := by
        rw [Polynomial.derivative_map, Polynomial.derivative_map,
          Polynomial.eval_map, ← Polynomial.aeval_def, ← algebraMap_eval_map _ hyint,
          ← Polynomial.derivative_map]
        intro h
        exact hgne (hinjL (by rw [h, map_zero]))
      exact rootMultiplicity_le_one_of_derivative
        ((Polynomial.Monic.map (algebraMap K ↥L)
          (hgm.map _)).ne_zero) hd
    · rw [Polynomial.rootMultiplicity_eq_zero hy]
      omega
  -- conclude
  rw [← Multiset.toFinset_card_of_nodup hnodupG, ← Multiset.toFinset_card_of_nodup hnodupF]
  exact le_antisymm (card_le_card_of_nearby L Γ _ _ hexGF hsepG)
    (card_le_card_of_nearby L Γ _ _ hexFG hsepF)


-- @@ L1282-1433 verbatim
/-- Quantitative root-lifting, the analytic engine behind equation (3) and Lemma 1 of §3: for `L`
in `sigma K n` and a monic `f` over `𝒪[K]` separable over `K`, there is a threshold `0 < T` such
that every monic `g` with all coefficients congruent to those of `f` modulo the `T`-th power of
`𝓂[K]` has exactly as many roots in `L`, with multiplicity, as `f`
([Serre 1978, Lemma 1, pp.1032–1033][Serre1978]). With `Γ` the valuation in `integers L` of the
Bézout constant of `f` and `T = 2 * Γ + 1`: at any root of either polynomial the Bézout identity
pins the derivative order at at most `Γ`, so Newton (`exists_isRoot_near`) lifts each root of either
polynomial to a root of the other at distance of order greater than `Γ`, while distinct roots of one
polynomial stay at distance of order at most `Γ` (`addVal_sub_le_of_isRoot`); the liftings are
therefore injective both ways, and every root in `L` is simple, so the counts agree. -/
theorem card_aroots_eq (n : ℕ) (hn : 0 < n) (L : IntermediateField K (SeparableClosure K))
    (hL : L ∈ sigma K n) {f : Polynomial 𝒪[K]} (hfm : f.Monic)
    (hfsep : (f.map (algebraMap 𝒪[K] K)).Separable) :
    ∃ T : ℕ, 0 < T ∧ ∀ g : Polynomial 𝒪[K], g.Monic →
      (∀ i, g.coeff i - f.coeff i ∈ 𝓂[K] ^ T) →
      ((g.map (algebraMap 𝒪[K] K)).aroots ↥L).card =
        ((f.map (algebraMap 𝒪[K] K)).aroots ↥L).card := by
  classical
  obtain ⟨x, π, hπ, hint, hei, hadj, hdeg⟩ := exists_eisenstein_generator K n hn L hL
  subst hadj
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  -- the structural instances on the integral closure
  have hLoc : IsLocalRing ↥(integers (IntermediateField.adjoin K {x})) :=
    isLocalRing_integers hπ hint hei
  have hDVR : IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x})) :=
    isDiscreteValuationRing_integers hπ hint hei
  have hAC : IsAdicComplete
      (IsLocalRing.maximalIdeal ↥(integers (IntermediateField.adjoin K {x})))
      ↥(integers (IntermediateField.adjoin K {x})) := by
    rw [← IsLocalRing.eq_maximalIdeal (isMaximal_span_integralGen hπ hint hei)]
    exact isAdicComplete_span_integralGen hπ hint hei
  have hinjL : Function.Injective
      (algebraMap ↥(integers (IntermediateField.adjoin K {x}))
        ↥(IntermediateField.adjoin K {x})) := Subtype.val_injective
  have hinjA : Function.Injective
      (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))) := by
    intro a b hab
    have h1 : Function.Injective (algebraMap 𝒪[K] ↥(IntermediateField.adjoin K {x})) := by
      rw [IsScalarTower.algebraMap_eq 𝒪[K] K ↥(IntermediateField.adjoin K {x})]
      exact (algebraMap K ↥(IntermediateField.adjoin K {x})).injective.comp
        (IsFractionRing.injective 𝒪[K] K)
    apply h1
    rw [IsScalarTower.algebraMap_apply 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))
      ↥(IntermediateField.adjoin K {x}), hab, ← IsScalarTower.algebraMap_apply]
  -- the Bézout constant and its order `Γ`
  obtain ⟨U, V, β, hβ0, hUV⟩ := exists_bezout hfsep
  have hβA : algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) β ≠ 0 := fun h =>
    hβ0 (hinjA (by rw [h, map_zero]))
  obtain ⟨Γ, hΓ⟩ : ∃ Γ : ℕ, addVal ↥(integers (IntermediateField.adjoin K {x}))
      (algebraMap 𝒪[K] _ β) = (Γ : ℕ∞) := by
    obtain ⟨Γ, hΓ⟩ := WithTop.ne_top_iff_exists.mp (addVal_eq_top_iff.not.mpr hβA)
    exact ⟨Γ, hΓ.symm⟩
  refine ⟨2 * Γ + 1, by omega, fun g hgm hclose => ?_⟩
  -- the uniformizer has positive order upstairs
  have hϖa1 : (1 : ℕ∞) ≤ addVal _
      (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) π) := by
    rw [Order.one_le_iff_ne_zero, Ne, addVal_eq_zero_iff]
    intro hu
    have h1 : Ideal.span {integralGen hint} ^ (minpoly 𝒪[K] x).natDegree = ⊤ := by
      rw [span_integralGen_pow_eq hπ hint hei, Ideal.span_singleton_eq_top.mpr hu]
    have h2 : Ideal.span {integralGen hint} = ⊤ :=
      eq_top_iff.mpr (h1 ▸ Ideal.pow_le_self (minpoly.natDegree_pos hint).ne')
    exact (isMaximal_span_integralGen hπ hint hei).ne_top h2
  -- coefficientwise closeness, base changed to the integral closure
  have hcoeff : ∀ i, ((g - f).map
      (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})))).coeff i ∈
      Ideal.span
        {algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) π ^ (2 * Γ + 1)} := by
    intro i
    have h1 := hclose i
    rw [hπ.maximalIdeal_eq, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at h1
    obtain ⟨d, hd⟩ := h1
    rw [Polynomial.coeff_map, Polynomial.coeff_sub, hd, map_mul, map_pow]
    exact Ideal.mem_span_singleton.mpr ⟨algebraMap _ _ d, rfl⟩
  have hcoeffD : ∀ i, (Polynomial.derivative ((g - f).map
      (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x}))))).coeff i ∈
      Ideal.span
        {algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) π ^ (2 * Γ + 1)} := by
    intro i
    rw [Polynomial.coeff_derivative]
    exact Ideal.mul_mem_right _ _ (hcoeff (i + 1))
  -- evaluation estimates for the difference and its derivative
  have hediff : ∀ w : ↥(integers (IntermediateField.adjoin K {x})),
      ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
        (Polynomial.eval w (g.map (algebraMap 𝒪[K] _)) -
          Polynomial.eval w (f.map (algebraMap 𝒪[K] _))) := by
    intro w
    have h1 := le_addVal_of_mem_span_pow hϖa1 (eval_mem_span_pow hcoeff w)
    rwa [Polynomial.map_sub, Polynomial.eval_sub] at h1
  have hediffD : ∀ w : ↥(integers (IntermediateField.adjoin K {x})),
      ((2 * Γ + 1 : ℕ) : ℕ∞) ≤ addVal _
        (Polynomial.eval w (Polynomial.derivative (g.map (algebraMap 𝒪[K] _))) -
          Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) := by
    intro w
    have h1 := le_addVal_of_mem_span_pow hϖa1 (eval_mem_span_pow hcoeffD w)
    rwa [Polynomial.map_sub, Polynomial.derivative_sub, Polynomial.eval_sub] at h1
  -- the uniform derivative bound at any near-root of `f`
  have hbound : ∀ w : ↥(integers (IntermediateField.adjoin K {x})),
      ((Γ + 1 : ℕ) : ℕ∞) ≤ addVal _ (Polynomial.eval w (f.map (algebraMap 𝒪[K] _))) →
      addVal _ (Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) ≤ (Γ : ℕ∞) ∧
        addVal _ (Polynomial.eval w (Polynomial.derivative (g.map (algebraMap 𝒪[K] _)))) ≤
          (Γ : ℕ∞) := by
    intro w hw
    have hkey : Polynomial.eval w (U.map (algebraMap 𝒪[K] _)) *
        Polynomial.eval w (f.map (algebraMap 𝒪[K] _)) +
        Polynomial.eval w (V.map (algebraMap 𝒪[K] _)) *
        Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _))) =
        algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) β := by
      have h1 := congrArg (fun p : Polynomial 𝒪[K] =>
        Polynomial.eval w (p.map (algebraMap 𝒪[K]
          ↥(integers (IntermediateField.adjoin K {x}))))) hUV
      simp only [Polynomial.map_add, Polynomial.map_mul, Polynomial.map_C, Polynomial.eval_add,
        Polynomial.eval_mul, Polynomial.eval_C] at h1
      rwa [← Polynomial.derivative_map] at h1
    have hf' : addVal _ (Polynomial.eval w
        (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) ≤ (Γ : ℕ∞) := by
      by_contra hgt
      rw [not_le] at hgt
      have h2 : (Γ : ℕ∞) < addVal _ (Polynomial.eval w (U.map (algebraMap 𝒪[K] _)) *
          Polynomial.eval w (f.map (algebraMap 𝒪[K] _))) := by
        rw [addVal_mul]
        refine lt_of_lt_of_le (lt_of_lt_of_le ?_ hw) le_add_self
        rw [Nat.cast_lt]
        omega
      have h3 : (Γ : ℕ∞) < addVal _ (Polynomial.eval w (V.map (algebraMap 𝒪[K] _)) *
          Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) := by
        rw [addVal_mul]
        exact lt_of_lt_of_le hgt le_add_self
      have h4 : (Γ : ℕ∞) < addVal _
          (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) β) := by
        rw [← hkey]
        exact lt_of_lt_of_le (lt_min h2 h3) addVal_add
      rw [hΓ] at h4
      exact absurd h4 (lt_irrefl _)
    refine ⟨hf', ?_⟩
    by_contra hgt
    rw [not_le] at hgt
    have h5 : Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _))) =
        Polynomial.eval w (Polynomial.derivative (g.map (algebraMap 𝒪[K] _))) +
          -(Polynomial.eval w (Polynomial.derivative (g.map (algebraMap 𝒪[K] _))) -
            Polynomial.eval w (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) := by ring
    have h6 : (Γ : ℕ∞) < addVal _ (Polynomial.eval w
        (Polynomial.derivative (f.map (algebraMap 𝒪[K] _)))) := by
      rw [h5]
      refine lt_of_lt_of_le (lt_min hgt ?_) addVal_add
      rw [addVal_neg]
      refine lt_of_lt_of_le ?_ (hediffD w)
      rw [Nat.cast_lt]
      omega
    exact absurd (h6.trans_le hf') (lt_irrefl _)
  exact card_aroots_eq_of_bounds _ hAC hfm hgm hfsep Γ hediff hbound


-- @@ L1435-1435 verbatim
end MassFormula
