/-
Copyright (c) 2026 Tom Adamczewski and Epoch AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: GPT-6 Astra, Tom Adamczewski
-/
module

public import Mathlib.Algebra.Algebra.NonUnitalSubalgebra
public import LeanPool.Koethe.Linearization.Basic
import LeanPool.Koethe.Linearization.Pencil
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Tactic.NormNum.Abs
import Mathlib.Tactic.NormNum.DivMod
import Mathlib.Tactic.NormNum.OfScientific
import Mathlib.Tactic.NormNum.Pow


-- @@ L17-29 verbatim
/-!
# Nilness of the positive algebra from nilness of all root-row pencils

Every element of the nonunital algebra generated by three elements admits a
finite homogeneous-linear system. Its root-row pencil belongs to the exact
shared `Pencil` type, and nilpotence of that pencil implies nilpotence of the
element.

The strengthened adjoin induction below proves multiplication closure without
adding scalar/identity edges: besides linearizing `x`, it proves that left
multiplication by `x` preserves linearizability. At a generator this is the
`prepend` construction; the multiplication step is then composition.
-/


-- @@ L31-31 verbatim
@[expose] public section


-- @@ L33-33 verbatim
noncomputable section


-- @@ L35-35 verbatim
namespace KoetheCounterexample


-- @@ L37-37 verbatim
universe u v


-- @@ L39-39 verbatim
variable {k : Type u} [Field k] {R : Type v} [Ring R] [Algebra k R]


-- @@ L41-41 verbatim
namespace Linearization


-- @@ L43-74 verbatim
/-- Every positive algebra expression admits a finite homogeneous-linear
system. No dimension, cardinality, commutativity, or nilness hypothesis on the
ambient algebra is needed. -/
theorem linearizable_of_mem_adjoin (a : Fin 3 → R) {x : R}
    (hx : x ∈ NonUnitalAlgebra.adjoin k (Set.range a)) :
    Linearizable (k := k) a x := by
  have h : ∀ z, z ∈ NonUnitalAlgebra.adjoin k (Set.range a) →
      Linearizable (k := k) a z ∧
        ∀ y, Linearizable (k := k) a y → Linearizable (k := k) a (z * y) := by
    intro z hz
    induction hz using NonUnitalAlgebra.adjoin_induction with
    | mem z hz =>
        obtain ⟨i, rfl⟩ := hz
        exact ⟨linearizable_letter a i, fun y hy => linearizable_prepend hy i⟩
    | zero =>
        exact ⟨linearizable_zero a, fun y _ => by simpa using linearizable_zero (k := k) a⟩
    | add z w _ _ ihz ihw =>
        refine ⟨linearizable_add ihz.1 ihw.1, ?_⟩
        intro y hy
        rw [add_mul]
        exact linearizable_add (ihz.2 y hy) (ihw.2 y hy)
    | mul z w _ _ ihz ihw =>
        refine ⟨ihz.2 w ihw.1, ?_⟩
        intro y hy
        rw [mul_assoc]
        exact ihz.2 (w * y) (ihw.2 y hy)
    | smul r z _ ihz =>
        refine ⟨linearizable_smul ihz.1 r, ?_⟩
        intro y hy
        rw [smul_mul_assoc]
        exact linearizable_smul (ihz.2 y hy) r
  exact (h x hx).1


-- @@ L76-76 verbatim
end Linearization


-- @@ L78-85 verbatim
/-- A per-element root-row pencil certificate for any element of the generated
positive algebra. Its entries are homogeneous-linear in the generators, and
its parameter occurs solely in the distinguished row. -/
theorem exists_pencil_nil_imp_of_mem_adjoin (a : Fin 3 → R) {x : R}
    (hx : x ∈ NonUnitalAlgebra.adjoin k (Set.range a)) :
    ∃ (d : ℕ) (P : Pencil k d), IsNilpotent (P.lift a) → IsNilpotent x := by
  obtain ⟨S, hS⟩ := Linearization.linearizable_of_mem_adjoin a hx
  exact ⟨Fintype.card S.State, S.pencil, hS.nil_of_pencil_nil⟩


-- @@ L87-94 verbatim
/-- If all homogeneous-linear, single-root-row pencils in the three generators
are nilpotent, then their generated nonunital algebra is nil. -/
theorem nil_of_all_pencils_nil (a : Fin 3 → R)
    (hall : ∀ (d : ℕ) (P : Pencil k d), IsNilpotent (P.lift a)) :
    ∀ x ∈ NonUnitalAlgebra.adjoin k (Set.range a), IsNilpotent x := by
  intro x hx
  obtain ⟨d, P, hP⟩ := exists_pencil_nil_imp_of_mem_adjoin a hx
  exact hP (hall d P)


-- @@ L96-96 verbatim
end KoetheCounterexample


-- @@ L98-98 verbatim
end
