/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.Lomega1omega.Entailment
public import LeanPool.InfinitaryLogic.Lomega1omega.Polarity
public import LeanPool.InfinitaryLogic.Methods.GeneratedSublanguage
import LeanPool.InfinitaryLogic.Methods.Interpolation.CraigSublanguage
import LeanPool.InfinitaryLogic.Methods.Interpolation.LyndonRelational
import LeanPool.InfinitaryLogic.Methods.PolarityCalculus
import LeanPool.InfinitaryLogic.Methods.SymbSublangExpansion

-- @@ L15-39 verbatim
/-!
# Lyndon interpolation, ambient relational theorem (issue #14, Unit 5, commit 3)

The public relational endpoint, with **no global countability hypothesis**: pass to the
sublanguage generated by the two roots' (countably many) symbols, apply the countable core there,
and map the interpolant back along the inclusion — transporting the two *signed* occurrence bounds
by the exact image law `relationsInSigned_mapLanguage`.

```
lyndon_interpolation_relational [L.IsRelational] (r₁ r₂ : L.Sentenceω) :
  Sentenceω.Entails r₁ r₂ →
    ∃ θ, θ.functionsIn ⊆ r₁.functionsIn ∩ r₂.functionsIn ∧
         θ.positiveRelationsIn ⊆ r₁.positiveRelationsIn ∩ r₂.positiveRelationsIn ∧
         θ.negativeRelationsIn ⊆ r₁.negativeRelationsIn ∩ r₂.negativeRelationsIn ∧
         Sentenceω.Entails r₁ θ ∧ Sentenceω.Entails θ r₂
```

This is the **relation-polarity / logical-equality form** of López–Escobar 1965, Theorem 4.1: its
clause (.4) in full, with clause (.3)'s equality-occurrence condition deliberately not claimed
(equality is logical here, and unconstrained in the interpolant).

`lyndon_interpolant_is_craig` recovers the unsigned Craig bound from the two signed ones through
`relationsIn = positive ∪ negative`; it is a *consumer* lemma, so Craig interpolation is visibly
recoverable without duplicating the existing `craig_interpolation_relational`.
-/


-- @@ L41-41 verbatim
@[expose] public section


-- @@ L43-43 verbatim
namespace FirstOrder.Language


-- @@ L45-45 verbatim
open FirstOrder Structure BoundedFormulaω


-- @@ L47-47 verbatim
variable {L : Language.{0, 0}}


-- @@ L49-57 verbatim
/-- Signed occurrence transport along the sublanguage inclusion, by the exact image law. -/
private theorem relationsInSigned_mapLanguage_incl_subset (F : Set (Σ n, L.Functions n))
    (R : Set (Σ n, L.Relations n)) (r : L.Sentenceω) (hF : r.functionsIn ⊆ F)
    (hR : r.relationsIn ⊆ R) (θ' : (symbSublang (L := L) F R).Sentenceω) (s : Bool)
    (hsub : relationsInSigned s θ' ⊆ relationsInSigned s (r.restrictSymbols hF hR)) :
    relationsInSigned s (θ'.mapLanguage (symbSublangIncl F R)) ⊆ relationsInSigned s r := by
  rw [relationsInSigned_mapLanguage, ← BoundedFormulaω.mapLanguage_restrictSymbols r hF hR,
    relationsInSigned_mapLanguage]
  exact Set.image_mono hsub


-- @@ L59-106 verbatim
/-- **Lyndon interpolation for `L_ω₁ω` — relational, no global countability hypothesis.**

Over a purely relational language (of arbitrarily many symbols), an `L_ω₁ω`-entailment `r₁ ⊨ r₂`
has a base-`L` interpolant whose function symbols lie in the intersection of the roots' function
occurrences, whose **positively** occurring relation symbols lie in the intersection of the roots'
**positive** occurrences, and whose **negatively** occurring ones lie in the intersection of the
roots' **negative** occurrences.

The relation-polarity / logical-equality form of López–Escobar 1965, Theorem 4.1 — clause (.4) in
full; clause (.3)'s equality-occurrence condition is not claimed. -/
theorem lyndon_interpolation_relational [L.IsRelational] (r₁ r₂ : L.Sentenceω)
    (h : Sentenceω.Entails r₁ r₂) :
    ∃ θ : L.Sentenceω,
      θ.functionsIn ⊆ r₁.functionsIn ∩ r₂.functionsIn ∧
      θ.positiveRelationsIn ⊆ r₁.positiveRelationsIn ∩ r₂.positiveRelationsIn ∧
      θ.negativeRelationsIn ⊆ r₁.negativeRelationsIn ∩ r₂.negativeRelationsIn ∧
      Sentenceω.Entails r₁ θ ∧ Sentenceω.Entails θ r₂ := by
  -- The sublanguage generated by the two roots' (countable) combined symbol sets.
  set F : Set (Σ n, L.Functions n) := r₁.functionsIn ∪ r₂.functionsIn with hF
  set R : Set (Σ n, L.Relations n) := r₁.relationsIn ∪ r₂.relationsIn with hR
  have hRc : R.Countable := (r₁.relationsIn_countable).union (r₂.relationsIn_countable)
  have hr₁F : r₁.functionsIn ⊆ F := Set.subset_union_left
  have hr₁R : r₁.relationsIn ⊆ R := Set.subset_union_left
  have hr₂F : r₂.functionsIn ⊆ F := Set.subset_union_right
  have hr₂R : r₂.relationsIn ⊆ R := Set.subset_union_right
  have hE' : Sentenceω.Entails (r₁.restrictSymbols hr₁F hr₁R) (r₂.restrictSymbols hr₂F hr₂R) :=
    entails_restrictSymbols_singleton F R r₁ r₂ hr₁F hr₁R hr₂F hr₂R h
  have : Countable (Σ n, (symbSublang (L := L) F R).Relations n) :=
    symbSublang_rel_countable F hRc
  obtain ⟨θ', hθ'F, hθ'P, hθ'N, hE1', hE2'⟩ :=
    lyndon_interpolation_relational_countable (r₁.restrictSymbols hr₁F hr₁R)
      (r₂.restrictSymbols hr₂F hr₂R) hE'
  refine ⟨θ'.mapLanguage (symbSublangIncl F R), ?_, ?_, ?_, ?_, ?_⟩
  · exact Set.subset_inter
      (functionsIn_mapLanguage_incl_subset F R r₁ hr₁F hr₁R θ' (hθ'F.trans Set.inter_subset_left))
      (functionsIn_mapLanguage_incl_subset F R r₂ hr₂F hr₂R θ' (hθ'F.trans Set.inter_subset_right))
  · exact Set.subset_inter
      (relationsInSigned_mapLanguage_incl_subset F R r₁ hr₁F hr₁R θ' true
        (hθ'P.trans Set.inter_subset_left))
      (relationsInSigned_mapLanguage_incl_subset F R r₂ hr₂F hr₂R θ' true
        (hθ'P.trans Set.inter_subset_right))
  · exact Set.subset_inter
      (relationsInSigned_mapLanguage_incl_subset F R r₁ hr₁F hr₁R θ' false
        (hθ'N.trans Set.inter_subset_left))
      (relationsInSigned_mapLanguage_incl_subset F R r₂ hr₂F hr₂R θ' false
        (hθ'N.trans Set.inter_subset_right))
  · exact entails_mapLanguage_restrictSymbols_left F R r₁ hr₁F hr₁R θ' hE1'
  · exact entails_mapLanguage_restrictSymbols_right F R r₂ hr₂F hr₂R θ' hE2'


-- @@ L108-123 verbatim
/-- **Craig from Lyndon, at the occurrence level.** The unsigned shared-vocabulary bound follows
from the two signed bounds through `relationsIn = positive ∪ negative`.  Stated as a consumer
lemma so that the recovery of Craig interpolation is explicit, without duplicating the existing
`craig_interpolation_relational`. -/
theorem lyndon_interpolant_is_craig {θ r₁ r₂ : L.Sentenceω}
    (hp : θ.positiveRelationsIn ⊆ r₁.positiveRelationsIn ∩ r₂.positiveRelationsIn)
    (hn : θ.negativeRelationsIn ⊆ r₁.negativeRelationsIn ∩ r₂.negativeRelationsIn) :
    θ.relationsIn ⊆ r₁.relationsIn ∩ r₂.relationsIn := by
  rw [relationsIn_eq_signed_union θ]
  refine Set.union_subset (fun p hp' => ?_) (fun p hn' => ?_)
  · obtain ⟨h1, h2⟩ := hp hp'
    exact ⟨by rw [relationsIn_eq_signed_union r₁]; exact Set.mem_union_left _ h1,
      by rw [relationsIn_eq_signed_union r₂]; exact Set.mem_union_left _ h2⟩
  · obtain ⟨h1, h2⟩ := hn hn'
    exact ⟨by rw [relationsIn_eq_signed_union r₁]; exact Set.mem_union_right _ h1,
      by rw [relationsIn_eq_signed_union r₂]; exact Set.mem_union_right _ h2⟩


-- @@ L125-125 verbatim
end FirstOrder.Language
