/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import LeanPool.DomainTheory.Neighborhood.Basic
import Mathlib.Data.Set.Basic
import Mathlib.Tactic.Tauto


-- @@ L12-40 verbatim
/-!
# Exercise 1.20 (Scott 1981, PRG-19, §1) — the power system `𝒟' = {↑X}`

For any neighbourhood system `𝒟` over `Δ`, Scott takes `Δ' = 𝒟` and
`𝒟' = {↑X ∣ X ∈ 𝒟}` where `↑X = {Y ∈ 𝒟 ∣ Y ⊆ X}` (the *up-set* of `X` inside `𝒟` —
**not**
the principal filter of Definition 1.7, which is the *down*-set `{Y ∈ 𝒟 ∣ X ⊆
Y}`). The
exercise asks to show `𝒟'` is **positive** and that `|𝒟| ≅ |𝒟'|`, with finite
elements and
tokens of `𝒟'` in one-one correspondence.

This file (named `upSet` to avoid the `principal`/`↑X` collision):

* `upSet`, `upSet_inter` (`↑X ∩ ↑Y = ↑(X∩Y)`), `upSet_subset_iff` (`↑X ⊆ ↑Y ↔ X ⊆
Y`),
  `upSet_injective`;
* `powerSystem : NeighborhoodSystem (Set α)` and `powerSystem_isPositive`;
* the mutually-inverse `toPower`/`ofPower` and the order-iso `powerIso : |𝒟| ≃o
|𝒟'|`, hence
  `isomorphic_powerSystem : V ≅ᴰ V.powerSystem`;
* `toPower_principal`: the iso carries the finite element `↑X` to the finite
element of `𝒟'`
  generated by the token `↑X`, i.e. tokens of `𝒟'` ↔ finite elements one-one.

Note the variance: `X ↦ ↑X` is inclusion-**preserving** (`upSet_subset_iff`),
unlike Def 1.7's
`principal`. Everything is `[propext, Quot.sound]`.
-/


-- @@ L42-42 verbatim
@[expose] public section


-- @@ L44-44 verbatim
namespace Domain.Neighborhood


-- @@ L46-46 verbatim
namespace NeighborhoodSystem


-- @@ L48-48 verbatim
variable {α : Type*} (V : NeighborhoodSystem α)


-- @@ L50-51 verbatim
/-- Exercise 1.20's `↑X = {Y ∈ 𝒟 ∣ Y ⊆ X}` (the up-set of `X` *inside* `𝒟`). -/
def upSet (X : Set α) : Set (Set α) := {Y | V.mem Y ∧ Y ⊆ X}


-- @@ L53-53 verbatim
@[simp] theorem mem_upSet {X Y : Set α} : Y ∈ V.upSet X ↔ V.mem Y ∧ Y ⊆ X := Iff.rfl


-- @@ L55-59 verbatim
/-- `↑X ∩ ↑Y = ↑(X ∩ Y)` — a set identity (no membership hypotheses). -/
theorem upSet_inter (X Y : Set α) : V.upSet X ∩ V.upSet Y = V.upSet (X ∩ Y) := by
  ext Z
  simp only [Set.mem_inter_iff, mem_upSet, Set.subset_inter_iff]
  tauto


-- @@ L61-68 verbatim
/-- `X ↦ ↑X` is inclusion-**preserving**: `↑X ⊆ ↑Y ↔ X ⊆ Y` (for `X ∈ 𝒟`).
`→` tests at `X ∈ ↑X`; `←` is transitivity of `⊆`. -/
theorem upSet_subset_iff {X Y : Set α} (hX : V.mem X) : V.upSet X ⊆ V.upSet Y ↔ X ⊆ Y := by
  constructor
  · intro h
    exact (h ⟨hX, subset_rfl⟩).2
  · intro hXY Z hZ
    exact ⟨hZ.1, hZ.2.trans hXY⟩


-- @@ L70-74 verbatim
/-- `X ↦ ↑X` is one-one on `𝒟`. -/
theorem upSet_injective {X Y : Set α} (hX : V.mem X) (hY : V.mem Y)
    (h : V.upSet X = V.upSet Y) : X = Y :=
  Set.Subset.antisymm ((V.upSet_subset_iff hX).mp h.subset)
    ((V.upSet_subset_iff hY).mp h.superset)


-- @@ L76-94 verbatim
/-- **Exercise 1.20 — the power system `𝒟' = {↑X ∣ X ∈ 𝒟}`** over the tokens `Δ' =
𝒟`. The
master is `↑Δ`; the intersection law uses the consistency witness `Z ∈ ↑Z ⊆ ↑X ∩
↑Y` to get
`Z ⊆ X ∩ Y`, hence `X ∩ Y ∈ 𝒟` and `↑X ∩ ↑Y = ↑(X∩Y)`. -/
def powerSystem : NeighborhoodSystem (Set α) where
  mem S := ∃ X, V.mem X ∧ S = V.upSet X
  master := V.upSet V.master
  master_mem := ⟨V.master, V.master_mem, rfl⟩
  inter_mem := by
    rintro S T W ⟨X, hX, rfl⟩ ⟨Y, hY, rfl⟩ ⟨Z, hZ, rfl⟩ hWsub
    have hZin : Z ∈ V.upSet X ∩ V.upSet Y := hWsub ⟨hZ, subset_rfl⟩
    obtain ⟨⟨_, hZX⟩, _, hZY⟩ := hZin
    have hXY : V.mem (X ∩ Y) := V.inter_mem hX hY hZ (Set.subset_inter hZX hZY)
    exact ⟨X ∩ Y, hXY, V.upSet_inter X Y⟩
  sub_master := by
    intro S hS
    obtain ⟨X, hX, rfl⟩ := hS
    exact (V.upSet_subset_iff hX).mpr (V.sub_master hX)


-- @@ L96-97 verbatim
@[simp] theorem powerSystem_mem {S : Set (Set α)} :
    V.powerSystem.mem S ↔ ∃ X, V.mem X ∧ S = V.upSet X := Iff.rfl


-- @@ L99-111 verbatim
/-- **Exercise 1.20 — `𝒟'` is positive.** `↑X ∩ ↑Y = ↑(X∩Y)` is a neighbourhood
iff it is
non-empty: a witness `Z ⊆ X ∩ Y` gives `X ∩ Y ∈ 𝒟`; conversely `↑W` always
contains `W`. -/
theorem powerSystem_isPositive : V.powerSystem.IsPositive := by
  rintro S T ⟨X, hX, rfl⟩ ⟨Y, hY, rfl⟩
  rw [V.upSet_inter]
  constructor
  · rintro ⟨W, hW, hWeq⟩
    rw [hWeq]
    exact ⟨W, hW, subset_rfl⟩
  · rintro ⟨Z, hZmem, hZsub⟩
    exact ⟨X ∩ Y, V.inter_mem hX hY hZmem hZsub, rfl⟩


-- @@ L113-113 verbatim
/-! ### The isomorphism `|𝒟| ≃o |𝒟'|`. -/


-- @@ L115-126 verbatim
/-- The element of `|𝒟'|` corresponding to `x ∈ |𝒟|`: the filter `{↑W ∣ W ∈ x}`. -/
def toPower (x : V.Element) : V.powerSystem.Element where
  mem S := ∃ W, x.mem W ∧ S = V.upSet W
  sub := by rintro S ⟨W, hW, rfl⟩; exact ⟨W, x.sub hW, rfl⟩
  master_mem := ⟨V.master, x.master_mem, rfl⟩
  inter_mem := by
    rintro S T ⟨W1, hW1, rfl⟩ ⟨W2, hW2, rfl⟩
    exact ⟨W1 ∩ W2, x.inter_mem hW1 hW2, V.upSet_inter W1 W2⟩
  up_mem := by
    rintro S T ⟨W, hW, rfl⟩ hT hsub
    obtain ⟨W', hW', rfl⟩ := hT
    exact ⟨W', x.up_mem hW hW' ((V.upSet_subset_iff (x.sub hW)).mp hsub), rfl⟩


-- @@ L128-142 verbatim
/-- The element of `|𝒟|` corresponding to `y ∈ |𝒟'|`: the filter `{W ∣ ↑W ∈ y}`. -/
def ofPower (y : V.powerSystem.Element) : V.Element where
  mem W := V.mem W ∧ y.mem (V.upSet W)
  sub h := h.1
  master_mem := ⟨V.master_mem, y.master_mem⟩
  inter_mem := by
    rintro X Y ⟨hX, hyX⟩ ⟨hY, hyY⟩
    have hyInter : y.mem (V.upSet X ∩ V.upSet Y) := y.inter_mem hyX hyY
    rw [V.upSet_inter] at hyInter
    obtain ⟨W, hW, hWeq⟩ := y.sub hyInter
    have hWin : W ∈ V.upSet (X ∩ Y) := by rw [hWeq]; exact ⟨hW, subset_rfl⟩
    exact ⟨V.inter_mem hX hY hW hWin.2, hyInter⟩
  up_mem := by
    rintro X Y ⟨hX, hyX⟩ hY hXY
    exact ⟨hY, y.up_mem hyX ⟨Y, hY, rfl⟩ ((V.upSet_subset_iff hX).mpr hXY)⟩


-- @@ L144-178 verbatim
/-- **Exercise 1.20 (the isomorphism).** `toPower`/`ofPower` are mutually inverse
and
preserve/reflect `⊑`, giving `|𝒟| ≃o |𝒟'|`. -/
def powerIso : V.Element ≃o V.powerSystem.Element where
  toFun := V.toPower
  invFun := V.ofPower
  left_inv := by
    intro x
    apply Element.ext
    intro W
    constructor
    · rintro ⟨hW, W', hW', heq⟩
      rw [V.upSet_injective hW (x.sub hW') heq]; exact hW'
    · intro hx
      exact ⟨x.sub hx, W, hx, rfl⟩
  right_inv := by
    intro y
    apply Element.ext
    intro S
    constructor
    · rintro ⟨W, ⟨_, hyW⟩, rfl⟩
      exact hyW
    · intro hyS
      obtain ⟨W, hW, rfl⟩ := y.sub hyS
      exact ⟨W, ⟨hW, hyS⟩, rfl⟩
  map_rel_iff' := by
    intro x x'
    constructor
    · intro h W hx
      have hmem : (V.toPower x).mem (V.upSet W) := ⟨W, hx, rfl⟩
      obtain ⟨W', hW', heq⟩ := h (V.upSet W) hmem
      rw [V.upSet_injective (x.sub hx) (x'.sub hW') heq]; exact hW'
    · intro h S hS
      obtain ⟨W, hW, rfl⟩ := hS
      exact ⟨W, h W hW, rfl⟩


-- @@ L180-181 expanded
/-- **Exercise 1.20 (statement).** `𝒟` and its power system `𝒟'` are isomorphic. -/
theorem isomorphic_powerSystem : Isomorphic V V.powerSystem :=
  ⟨V.powerIso⟩


-- @@ L183-198 verbatim
/-- **Exercise 1.20 — tokens ↔ finite elements.** The iso carries the finite
element `↑X` of
`|𝒟|` (Def 1.7) to the finite element of `|𝒟'|` generated by the token `↑X`, i.e.
the principal
filter of `↑X` in `𝒟'`. Since `X ↦ ↑X` is one-one (`upSet_injective`), tokens of
`𝒟'` and its
finite elements are in one-one correspondence. -/
theorem toPower_principal {X : Set α} (hX : V.mem X) :
    V.toPower (V.principal hX) = V.powerSystem.principal ⟨X, hX, rfl⟩ := by
  apply Element.ext
  intro S
  constructor
  · rintro ⟨W, ⟨hWmem, hXW⟩, rfl⟩
    exact ⟨⟨W, hWmem, rfl⟩, (V.upSet_subset_iff hX).mpr hXW⟩
  · rintro ⟨⟨W, hWmem, rfl⟩, hsub⟩
    exact ⟨W, ⟨hWmem, (V.upSet_subset_iff hX).mp hsub⟩, rfl⟩


-- @@ L200-200 verbatim
end NeighborhoodSystem


-- @@ L202-202 verbatim
end Domain.Neighborhood
