/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/
module

public import Mathlib.Data.Finsupp.Defs
public import Mathlib.Data.Set.Countable


-- @@ L11-17 verbatim
/-!
# Countable closure under triangular dependencies

For a code `c`, `dependency c` is the countable set of basis coordinates occurring in its
prepared sequence.  Because code indices are injective, closing a countable set under all codes
whose indices it contains still takes only countably many new coordinates at each finite stage.
-/


-- @@ L19-19 verbatim
@[expose] public section


-- @@ L21-21 verbatim
open Set


-- @@ L23-23 verbatim
universe u v w


-- @@ L25-25 verbatim
namespace Wallace


-- @@ L27-27 verbatim
noncomputable section


-- @@ L29-29 verbatim
variable {I : Type u} {Code : Type v}


-- @@ L31-34 verbatim
/-- One closure step under a family of countable dependencies. -/
def dependencyClosureStep (index : Code ↪ I) (dependency : Code → Set I)
    (D : Set I) : Set I :=
  D ∪ ⋃ c, ⋃ (_h : index c ∈ D), dependency c


-- @@ L36-40 verbatim
/-- Finite stages of the dependency closure. -/
def dependencyClosureStages (index : Code ↪ I) (dependency : Code → Set I)
    (D₀ : Set I) : ℕ → Set I
  | 0 => D₀
  | n + 1 => dependencyClosureStep index dependency (dependencyClosureStages index dependency D₀ n)


-- @@ L42-45 verbatim
/-- Closure after all finite stages. -/
def dependencyClosure (index : Code ↪ I) (dependency : Code → Set I)
    (D₀ : Set I) : Set I :=
  ⋃ n, dependencyClosureStages index dependency D₀ n


-- @@ L47-50 verbatim
theorem subset_dependencyClosure (index : Code ↪ I) (dependency : Code → Set I)
    (D₀ : Set I) : D₀ ⊆ dependencyClosure index dependency D₀ := by
  intro x hx
  exact Set.mem_iUnion.mpr ⟨0, hx⟩


-- @@ L52-60 verbatim
/-- The closure is closed under every dependency whose code index it contains. -/
theorem dependency_subset_closure_of_index_mem
    (index : Code ↪ I) (dependency : Code → Set I) (D₀ : Set I)
    {c : Code} (hc : index c ∈ dependencyClosure index dependency D₀) :
    dependency c ⊆ dependencyClosure index dependency D₀ := by
  obtain ⟨n, hcn⟩ := Set.mem_iUnion.mp hc
  intro x hx
  refine Set.mem_iUnion.mpr ⟨n + 1, ?_⟩
  exact Or.inr (Set.mem_iUnion.mpr ⟨c, Set.mem_iUnion.mpr ⟨hcn, hx⟩⟩)


-- @@ L62-65 verbatim
theorem countable_preimage_of_injective
    (index : Code ↪ I) {D : Set I} (hD : D.Countable) :
    {c : Code | index c ∈ D}.Countable := by
  exact hD.preimage index.injective


-- @@ L67-76 verbatim
/-- A countable set remains countable after one dependency-closure step. -/
theorem countable_dependencyClosureStep
    (index : Code ↪ I) (dependency : Code → Set I)
    (hdep : ∀ c, (dependency c).Countable)
    {D : Set I} (hD : D.Countable) :
    (dependencyClosureStep index dependency D).Countable := by
  apply hD.union
  have hcodes : {c : Code | index c ∈ D}.Countable :=
    countable_preimage_of_injective index hD
  exact hcodes.biUnion fun c _hc ↦ hdep c


-- @@ L78-88 verbatim
/-- Closing a countable set under countable triangular dependencies is countable. -/
theorem countable_dependencyClosure
    (index : Code ↪ I) (dependency : Code → Set I)
    (hdep : ∀ c, (dependency c).Countable)
    {D₀ : Set I} (hD₀ : D₀.Countable) :
    (dependencyClosure index dependency D₀).Countable := by
  apply Set.countable_iUnion
  intro n
  induction n with
  | zero => exact hD₀
  | succ n ih => exact countable_dependencyClosureStep index dependency hdep ih


-- @@ L90-90 verbatim
/-! ## Prepared-support specialization -/


-- @@ L92-92 verbatim
variable {R : Type w} [Zero R]


-- @@ L94-96 verbatim
/-- All coordinates occurring in the prepared sequence attached to a code. -/
def preparedDependency (prepared : Code → ℕ → I →₀ R) (c : Code) : Set I :=
  ⋃ n, ↑(prepared c n).support


-- @@ L98-102 verbatim
theorem preparedDependency_countable (prepared : Code → ℕ → I →₀ R) (c : Code) :
    (preparedDependency prepared c).Countable := by
  apply Set.countable_iUnion
  intro n
  exact (prepared c n).support.finite_toSet.countable


-- @@ L104-107 verbatim
/-- The dependency closure generated by the support of a finitely supported vector. -/
def preparedClosure (index : Code ↪ I) (prepared : Code → ℕ → I →₀ R)
    (x : I →₀ R) : Set I :=
  dependencyClosure index (preparedDependency prepared) ↑x.support


-- @@ L109-112 verbatim
theorem support_subset_preparedClosure (index : Code ↪ I)
    (prepared : Code → ℕ → I →₀ R) (x : I →₀ R) :
    ↑x.support ⊆ preparedClosure index prepared x :=
  subset_dependencyClosure index (preparedDependency prepared) ↑x.support


-- @@ L114-118 verbatim
theorem preparedClosure_countable (index : Code ↪ I)
    (prepared : Code → ℕ → I →₀ R) (x : I →₀ R) :
    (preparedClosure index prepared x).Countable :=
  countable_dependencyClosure index (preparedDependency prepared)
    (preparedDependency_countable prepared) x.support.finite_toSet.countable


-- @@ L120-127 verbatim
/-- The closure contains every coordinate in a prepared sequence whose code index it contains. -/
theorem preparedSupport_subset_preparedClosure (index : Code ↪ I)
    (prepared : Code → ℕ → I →₀ R) (x : I →₀ R) (c : Code)
    (hc : index c ∈ preparedClosure index prepared x) (n : ℕ) :
    ↑(prepared c n).support ⊆ preparedClosure index prepared x := by
  intro i hi
  exact dependency_subset_closure_of_index_mem
    index (preparedDependency prepared) ↑x.support hc (Set.mem_iUnion_of_mem n hi)


-- @@ L129-129 verbatim
end


-- @@ L131-131 verbatim
end Wallace
