/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/
module

public import Mathlib.Analysis.Fourier.AddCircleMulti
import Mathlib.Algebra.Module.CharacterModule
import Mathlib.Topology.ContinuousMap.Bounded.ArzelaAscoli
import Mathlib.Topology.MetricSpace.UniformConvergence


-- @@ L13-18 verbatim
/-!
# Algebraic foundations for the uniform Kronecker lemma

This file isolates the exact (non-quantitative) character-extension argument used in the paper.
The remaining quantitative statement is developed on top of these declarations.
-/


-- @@ L20-20 verbatim
@[expose] public section


-- @@ L22-22 verbatim
open scoped BigOperators


-- @@ L24-24 verbatim
noncomputable section


-- @@ L26-26 verbatim
universe u


-- @@ L28-28 verbatim
namespace Wallace


-- @@ L30-30 verbatim
open Filter Set TopologicalSpace Topology


-- @@ L32-39 verbatim
/-- The homomorphism which evaluates an integer relation on a finite tuple. -/
def relationMap {G : Type u} [AddCommGroup G] {m : ℕ} (z : Fin m → G) :
    (Fin m → ℤ) →+ G where
  toFun a := ∑ i, a i • z i
  map_zero' := by simp
  map_add' a b := by
    simp only [Pi.add_apply, add_zsmul]
    exact Finset.sum_add_distrib


-- @@ L41-46 verbatim
@[simp]
theorem relationMap_single {G : Type u} [AddCommGroup G] {m : ℕ}
    (z : Fin m → G) (i : Fin m) :
    relationMap z (Pi.single i 1) = z i := by
  classical
  simp [relationMap]


-- @@ L48-51 verbatim
/-- Evaluation of an integer vector on a tuple in the unit additive torus. -/
def torusRelationMap {m : ℕ} (t : Fin m → UnitAddCircle) :
    (Fin m → ℤ) →+ UnitAddCircle :=
  relationMap t


-- @@ L53-56 verbatim
@[simp]
theorem torusRelationMap_single {m : ℕ} (t : Fin m → UnitAddCircle) (i : Fin m) :
    torusRelationMap t (Pi.single i 1) = t i :=
  relationMap_single t i


-- @@ L58-61 verbatim
/-- The subgroup of integer relations on a tuple. -/
abbrev relationGroup {G : Type u} [AddCommGroup G] {m : ℕ} (z : Fin m → G) :
    AddSubgroup (Fin m → ℤ) :=
  (relationMap z).ker


-- @@ L63-66 verbatim
/-- A target tuple respects every relation of `z`. -/
def RespectsRelations {G : Type u} [AddCommGroup G] {m : ℕ}
    (z : Fin m → G) (t : Fin m → UnitAddCircle) : Prop :=
  (relationMap z).ker ≤ (torusRelationMap t).ker


-- @@ L68-72 verbatim
theorem respectsRelations_iff {G : Type u} [AddCommGroup G] {m : ℕ}
    (z : Fin m → G) (t : Fin m → UnitAddCircle) :
    RespectsRelations z t ↔
      ∀ a : Fin m → ℤ, (∑ i, a i • z i = 0) → (∑ i, a i • t i = 0) := by
  rfl


-- @@ L74-76 verbatim
/-- Supremum norm (height) of an integer vector with finite index type. -/
def intVectorHeight {m : ℕ} (a : Fin m → ℤ) : ℕ :=
  Finset.univ.sup fun i => (a i).natAbs


-- @@ L78-80 verbatim
theorem natAbs_le_intVectorHeight {m : ℕ} (a : Fin m → ℤ) (i : Fin m) :
    (a i).natAbs ≤ intVectorHeight a := by
  exact Finset.le_sup (f := fun j => (a j).natAbs) (Finset.mem_univ i)


-- @@ L82-86 verbatim
/-- A target tuple respects all relations of height at most `q`. -/
def RespectsRelationsUpTo {G : Type u} [AddCommGroup G] {m : ℕ}
    (q : ℕ) (z : Fin m → G) (t : Fin m → UnitAddCircle) : Prop :=
  ∀ a : Fin m → ℤ, intVectorHeight a ≤ q →
    relationMap z a = 0 → torusRelationMap t a = 0


-- @@ L88-92 verbatim
/-- `q` is a uniform Kronecker bound for tuples of length `m` and error `ε`. -/
def IsUniformKroneckerBound (m : ℕ) (ε : ℝ) (q : ℕ) : Prop :=
  ∀ {G : Type u} [AddCommGroup G] (z : Fin m → G) (t : Fin m → UnitAddCircle),
    RespectsRelationsUpTo q z t →
      ∃ χ : G →+ UnitAddCircle, ∀ i, ‖χ (z i) - t i‖ < ε


-- @@ L94-104 verbatim
/-- A target which respects all relations defines a homomorphism on the range generated by the
tuple. -/
def homOnTupleRange {G : Type u} [AddCommGroup G] {m : ℕ}
    (z : Fin m → G) (t : Fin m → UnitAddCircle)
    (h : RespectsRelations z t) : (relationMap z).range →+ UnitAddCircle := by
  let inv : (relationMap z).range → (Fin m → ℤ) :=
    Function.surjInv (relationMap z).rangeRestrict_surjective
  exact (relationMap z).rangeRestrict.liftOfRightInverse inv
    (Function.rightInverse_surjInv (relationMap z).rangeRestrict_surjective)
    ⟨torusRelationMap t, by
      simpa only [AddMonoidHom.ker_rangeRestrict, RespectsRelations] using h⟩


-- @@ L106-115 verbatim
theorem homOnTupleRange_comp {G : Type u} [AddCommGroup G] {m : ℕ}
    (z : Fin m → G) (t : Fin m → UnitAddCircle)
    (h : RespectsRelations z t) :
    (homOnTupleRange z t h).comp (relationMap z).rangeRestrict = torusRelationMap t := by
  let inv : (relationMap z).range → (Fin m → ℤ) :=
    Function.surjInv (relationMap z).rangeRestrict_surjective
  exact (relationMap z).rangeRestrict.liftOfRightInverse_comp inv
    (Function.rightInverse_surjInv (relationMap z).rangeRestrict_surjective)
    ⟨torusRelationMap t, by
      simpa only [AddMonoidHom.ker_rangeRestrict, RespectsRelations] using h⟩


-- @@ L117-133 verbatim
/-- Exact finite Kronecker extension: a target tuple which respects all integer relations is the
restriction of a character of the ambient Abelian group. -/
theorem exists_character_of_respectsRelations
    {G : Type u} [AddCommGroup G] {m : ℕ}
    (z : Fin m → G) (t : Fin m → UnitAddCircle)
    (h : RespectsRelations z t) :
    ∃ χ : G →+ UnitAddCircle, ∀ i, χ (z i) = t i := by
  obtain ⟨χ, hχ⟩ := (Module.Baer.of_divisible UnitAddCircle).extension_property_addMonoidHom
    (relationMap z).range.subtype (relationMap z).range.subtype_injective
    (homOnTupleRange z t h)
  refine ⟨χ, fun i => ?_⟩
  have hcomp : χ.comp (relationMap z).range.subtype = homOnTupleRange z t h := hχ
  have hrange := DFunLike.congr_fun hcomp ((relationMap z).rangeRestrict (Pi.single i 1))
  have htuple := DFunLike.congr_fun (homOnTupleRange_comp z t h) (Pi.single i 1)
  simpa only [AddMonoidHom.comp_apply, AddSubgroup.coe_subtype,
    AddMonoidHom.coe_rangeRestrict, relationMap_single, torusRelationMap_single] using
      hrange.trans htuple


-- @@ L135-135 verbatim
/-! ## Algebraic separation into the real unit circle -/


-- @@ L137-145 verbatim
/-- The embedding of the rational additive circle into the real additive circle. -/
noncomputable def rationalCircleToUnit : AddCircle (1 : ℚ) →+ UnitAddCircle :=
  QuotientAddGroup.map (AddSubgroup.zmultiples (1 : ℚ))
    (AddSubgroup.zmultiples (1 : ℝ)) (Rat.castHom ℝ).toAddMonoidHom (by
      rintro x hx
      rw [AddSubgroup.mem_comap]
      rw [AddSubgroup.mem_zmultiples_iff] at hx ⊢
      obtain ⟨n, rfl⟩ := hx
      exact ⟨n, by simp⟩)


-- @@ L147-156 verbatim
private theorem rationalCircleToUnit_eq_zero
    (x : AddCircle (1 : ℚ)) (hx : rationalCircleToUnit x = 0) : x = 0 := by
  induction x using QuotientAddGroup.induction_on
  rename_i q
  change (((q : ℝ) : UnitAddCircle) = 0) at hx
  rw [AddCircle.coe_eq_zero_iff] at hx ⊢
  obtain ⟨n, hn⟩ := hx
  refine ⟨n, ?_⟩
  norm_num at hn ⊢
  exact_mod_cast hn


-- @@ L158-162 verbatim
theorem rationalCircleToUnit_injective : Function.Injective rationalCircleToUnit := by
  intro x y hxy
  rw [← sub_eq_zero]
  apply rationalCircleToUnit_eq_zero
  simpa using sub_eq_zero.mpr hxy


-- @@ L164-176 verbatim
/-- Characters into the real unit circle separate points of every Abelian group.  The
`CharacterModule` theorem supplies a rational-circle character and the preceding embedding changes
the codomain without losing its nonzero value. -/
theorem exists_unit_character_apply_ne_zero
    {A : Type u} [AddCommGroup A] {a : A} (ha : a ≠ 0) :
    ∃ c : A →+ UnitAddCircle, c a ≠ 0 := by
  obtain ⟨c, hc⟩ := CharacterModule.exists_character_apply_ne_zero_of_ne_zero ha
  refine ⟨rationalCircleToUnit.comp c, ?_⟩
  intro hz
  apply hc
  apply rationalCircleToUnit_injective
  change rationalCircleToUnit (c a) = 0 at hz
  simpa only [map_zero] using hz


-- @@ L178-178 verbatim
/-! ## Relation annihilators and their distance functions -/


-- @@ L180-195 verbatim
/-- The annihilator in the finite torus of a subgroup of integer relations. -/
def integerAnnihilator {m : ℕ} (R : AddSubgroup (Fin m → ℤ)) :
    AddSubgroup (UnitAddTorus (Fin m)) where
  carrier := {x | ∀ a ∈ R, torusRelationMap x a = 0}
  zero_mem' := by
    intro a _ha
    simp [torusRelationMap, relationMap]
  add_mem' {x y} hx hy a ha := by
    change (∀ a ∈ R, ∑ i, a i • x i = 0) at hx
    change (∀ a ∈ R, ∑ i, a i • y i = 0) at hy
    change ∑ i, a i • (x i + y i) = 0
    simp_rw [smul_add, Finset.sum_add_distrib, hx a ha, hy a ha, add_zero]
  neg_mem' {x} hx a ha := by
    change (∀ a ∈ R, ∑ i, a i • x i = 0) at hx
    change ∑ i, a i • (-x i) = 0
    simp_rw [smul_neg, Finset.sum_neg_distrib, hx a ha, neg_zero]


-- @@ L197-205 verbatim
theorem isClosed_integerAnnihilator {m : ℕ} (R : AddSubgroup (Fin m → ℤ)) :
    IsClosed (integerAnnihilator R : Set (UnitAddTorus (Fin m))) := by
  rw [show (integerAnnihilator R : Set (UnitAddTorus (Fin m))) =
      ⋂ a : Fin m → ℤ, ⋂ (_ha : a ∈ R), {x | torusRelationMap x a = 0} by
    ext x
    simp [integerAnnihilator]]
  refine isClosed_biInter fun a _ha ↦ ?_
  change IsClosed {x : UnitAddTorus (Fin m) | (∑ i, a i • x i) = 0}
  exact isClosed_singleton.preimage (by fun_prop)


-- @@ L207-212 verbatim
/-- Distance to the relation annihilator, as a bounded continuous real-valued function. -/
def annihilatorDistance {m : ℕ} (R : AddSubgroup (Fin m → ℤ)) :
    BoundedContinuousFunction (UnitAddTorus (Fin m)) ℝ :=
  BoundedContinuousFunction.mkOfCompact
    (⟨fun x ↦ Metric.infDist x (integerAnnihilator R),
      Metric.continuous_infDist_pt _⟩ : C(UnitAddTorus (Fin m), ℝ))


-- @@ L214-218 verbatim
@[simp]
theorem annihilatorDistance_apply {m : ℕ} (R : AddSubgroup (Fin m → ℤ))
    (x : UnitAddTorus (Fin m)) :
    annihilatorDistance R x = Metric.infDist x (integerAnnihilator R) :=
  rfl


-- @@ L220-222 verbatim
theorem annihilatorDistance_lipschitz {m : ℕ} (R : AddSubgroup (Fin m → ℤ)) :
    LipschitzWith 1 (annihilatorDistance R) :=
  Metric.lipschitz_infDist_pt _


-- @@ L224-227 verbatim
private theorem intTuple_eq_sum_single {m : ℕ} (a : Fin m → ℤ) :
    (∑ i, a i • Pi.single i 1) = a := by
  classical
  exact (pi_eq_sum_univ' a).symm


-- @@ L229-263 verbatim
/-- The algebraic double-annihilator direction needed below: if an integer vector is not in
`R`, some point of `R⁺` detects it. -/
theorem exists_mem_integerAnnihilator_not_annihilate {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) {a : Fin m → ℤ} (ha : a ∉ R) :
    ∃ x ∈ integerAnnihilator R, torusRelationMap x a ≠ 0 := by
  have hqa : QuotientAddGroup.mk' R a ≠ 0 := by
    intro hzero
    exact ha ((QuotientAddGroup.eq_zero_iff a).mp hzero)
  obtain ⟨c, hc⟩ := exists_unit_character_apply_ne_zero hqa
  let z : Fin m → (Fin m → ℤ) ⧸ R :=
    fun i ↦ QuotientAddGroup.mk' R (Pi.single i 1)
  have hz (b : Fin m → ℤ) : relationMap z b = QuotientAddGroup.mk' R b := by
    change (∑ i, b i • QuotientAddGroup.mk' R (Pi.single i 1)) =
      QuotientAddGroup.mk' R b
    calc
      _ = QuotientAddGroup.mk' R (∑ i, b i • Pi.single i 1) := by
        rw [map_sum]
        simp
      _ = QuotientAddGroup.mk' R b := congrArg _ (intTuple_eq_sum_single b)
  let x : UnitAddTorus (Fin m) := fun i ↦ c (z i)
  have heval (b : Fin m → ℤ) : torusRelationMap x b = c (QuotientAddGroup.mk' R b) := by
    change (∑ i, b i • c (z i)) = c (QuotientAddGroup.mk' R b)
    calc
      _ = c (∑ i, b i • z i) := by
        rw [map_sum]
        simp
      _ = c (relationMap z b) := rfl
      _ = c (QuotientAddGroup.mk' R b) := congrArg c (hz b)
  refine ⟨x, ?_, ?_⟩
  · intro b hb
    rw [heval]
    have hb0 : QuotientAddGroup.mk' R b = 0 :=
      (QuotientAddGroup.eq_zero_iff b).mpr hb
    rw [hb0, map_zero]
  · simpa only [heval] using hc


-- @@ L265-280 verbatim
theorem mFourier_eq_toCircle_relation {m : ℕ} (a : Fin m → ℤ)
    (x : UnitAddTorus (Fin m)) :
    UnitAddTorus.mFourier a x = (AddCircle.toCircle (torusRelationMap x a) : ℂ) := by
  simp only [UnitAddTorus.mFourier, ContinuousMap.coe_mk, fourier_apply,
    torusRelationMap, relationMap]
  have hprod (s : Finset (Fin m)) :
      (∏ i ∈ s, (AddCircle.toCircle (a i • x i) : ℂ)) =
        (AddCircle.toCircle (∑ i ∈ s, a i • x i) : ℂ) := by
    induction s using Finset.induction_on with
    | empty => simp
    | @insert i s hi ih =>
        rw [Finset.prod_insert hi, Finset.sum_insert hi, AddCircle.toCircle_add, ih]
        simp only [Circle.coe_mul]
  change (∏ i, (AddCircle.toCircle (a i • x i) : ℂ)) =
    (AddCircle.toCircle (∑ i, a i • x i) : ℂ)
  simpa only [Finset.prod_const_one, Finset.sum_const_zero] using hprod Finset.univ


-- @@ L282-287 verbatim
/-- Regard a bounded real-valued continuous function on the compact torus as a complex-valued
continuous function. -/
def complexifyDistanceFunction {m : ℕ}
    (f : BoundedContinuousFunction (UnitAddTorus (Fin m)) ℝ) :
    C(UnitAddTorus (Fin m), ℂ) :=
  ⟨fun x ↦ (f x : ℂ), Complex.continuous_ofReal.comp f.continuous⟩


-- @@ L289-293 verbatim
/-- The family occurring in the paper's uniform-frequency-set lemma: real-valued functions on
the finite torus which are `1`-Lipschitz and take their values in `[0, 1 / 2]`. -/
def oneLipschitzHalfRangeFamily (m : ℕ) :
    Set (BoundedContinuousFunction (UnitAddTorus (Fin m)) ℝ) :=
  {f | LipschitzWith 1 f ∧ ∀ x, f x ∈ Set.Icc (0 : ℝ) (1 / 2)}


-- @@ L295-306 verbatim
/-- Arzelà--Ascoli compactness for the family in the uniform-frequency-set lemma.  We retain
the closure in the statement because that is exactly the form supplied by Mathlib's version of
Arzelà--Ascoli; membership of the original family is enough for every application below. -/
theorem isCompact_closure_oneLipschitzHalfRangeFamily (m : ℕ) :
    IsCompact (closure (oneLipschitzHalfRangeFamily m)) := by
  apply BoundedContinuousFunction.arzela_ascoli (Set.Icc (0 : ℝ) (1 / 2)) isCompact_Icc
  · intro f x hf
    exact hf.2 x
  · apply UniformEquicontinuous.equicontinuous
    apply LipschitzWith.uniformEquicontinuous _ 1
    rintro ⟨f, hf⟩
    exact hf.1


-- @@ L308-369 verbatim
/-- A compact family of real-valued continuous functions on a finite torus admits one finite
Fourier support which works, with error `2 * δ`, for every member of the family. -/
private theorem exists_finite_frequency_approximation_of_compact
    (m : ℕ) (A : Set (BoundedContinuousFunction (UnitAddTorus (Fin m)) ℝ))
    (hA : IsCompact A) {δ : ℝ} (hδ : 0 < δ) :
    ∃ S : Finset (Fin m → ℤ), ∀ f ∈ A,
      ∃ c : (Fin m → ℤ) →₀ ℂ, c.support ⊆ S ∧
        ∀ x : UnitAddTorus (Fin m),
          ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) x - (f x : ℂ)‖ < 2 * δ := by
  classical
  obtain ⟨T, hTA, hTfin, hcover⟩ := hA.finite_cover_balls hδ
  have hpoly (g : A) : ∃ c : (Fin m → ℤ) →₀ ℂ,
      ∀ x : UnitAddTorus (Fin m),
        ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) x -
          (complexifyDistanceFunction g.1) x‖ < δ := by
    let V : Submodule ℂ C(UnitAddTorus (Fin m), ℂ) :=
      Submodule.span ℂ (Set.range UnitAddTorus.mFourier)
    have hg_top : complexifyDistanceFunction g.1 ∈ V.topologicalClosure := by
      rw [show V.topologicalClosure = ⊤ from UnitAddTorus.span_mFourier_closure_eq_top]
      exact Submodule.mem_top
    have hg_closure : complexifyDistanceFunction g.1 ∈ closure (V : Set _) :=
      (Submodule.mem_closure_iff).mpr hg_top
    obtain ⟨P, hPV, hgP⟩ := (Metric.mem_closure_iff.mp hg_closure) δ hδ
    obtain ⟨c, rfl⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp hPV
    refine ⟨c, fun x ↦ ?_⟩
    calc
      ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) x -
          (complexifyDistanceFunction g.1) x‖ =
          ‖((c.sum fun a z ↦ z • UnitAddTorus.mFourier a) -
            complexifyDistanceFunction g.1) x‖ := rfl
      _ ≤ ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) -
            complexifyDistanceFunction g.1‖ :=
        ContinuousMap.norm_coe_le_norm _ x
      _ = dist (c.sum fun a z ↦ z • UnitAddTorus.mFourier a)
            (complexifyDistanceFunction g.1) := by rw [dist_eq_norm]
      _ < δ := by simpa only [dist_comm] using hgP
  let : Fintype T := hTfin.fintype
  choose coeff hcoeff using fun g : T ↦ hpoly ⟨g.1, hTA g.2⟩
  let S : Finset (Fin m → ℤ) := Finset.univ.biUnion fun g : T ↦ (coeff g).support
  refine ⟨S, fun f hfA ↦ ?_⟩
  obtain ⟨g, hgT, hfg⟩ := Set.mem_iUnion₂.mp (hcover hfA)
  let gT : T := ⟨g, hgT⟩
  refine ⟨coeff gT, ?_, fun x ↦ ?_⟩
  · intro a ha
    exact Finset.mem_biUnion.mpr ⟨gT, Finset.mem_univ _, ha⟩
  · calc
      ‖((coeff gT).sum (fun a z ↦ z • UnitAddTorus.mFourier a)) x - (f x : ℂ)‖ ≤
          ‖((coeff gT).sum (fun a z ↦ z • UnitAddTorus.mFourier a)) x -
            (g x : ℂ)‖ + ‖(g x : ℂ) - (f x : ℂ)‖ := by
        rw [show
          ((coeff gT).sum (fun a z ↦ z • UnitAddTorus.mFourier a)) x - (f x : ℂ) =
            (((coeff gT).sum (fun a z ↦ z • UnitAddTorus.mFourier a)) x -
              (g x : ℂ)) + ((g x : ℂ) - (f x : ℂ)) by ring]
        exact norm_add_le _ _
      _ < δ + δ := add_lt_add (hcoeff gT x) (by
        calc
          ‖(g x : ℂ) - (f x : ℂ)‖ = |g x - f x| := by
            rw [← Complex.ofReal_sub, Complex.norm_real, Real.norm_eq_abs]
          _ < δ := by
            simpa only [abs_sub_comm, Real.dist_eq] using lt_of_le_of_lt
              (BoundedContinuousFunction.dist_coe_le_dist x) hfg)
      _ = 2 * δ := by ring


-- @@ L371-399 verbatim
/-- **Uniform finite frequency set (paper, Lemma `uniform-frequency-set`).**

For every dimension and every positive error there is a finite set of integer frequencies such
that every real-valued `1`-Lipschitz function with values in `[0, 1 / 2]` is uniformly approximated
by a trigonometric polynomial supported on that same set.  The paper assumes `1 ≤ m`; the
formal statement is slightly stronger, since it also holds for `m = 0`. -/
theorem exists_uniform_frequency_set (m : ℕ) {η : ℝ} (hη : 0 < η) :
    ∃ S : Finset (Fin m → ℤ),
      ∀ f : BoundedContinuousFunction (UnitAddTorus (Fin m)) ℝ,
        LipschitzWith 1 f →
        (∀ x, f x ∈ Set.Icc (0 : ℝ) (1 / 2)) →
        ∃ c : (Fin m → ℤ) →₀ ℂ, c.support ⊆ S ∧
          ∀ x : UnitAddTorus (Fin m),
            ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) x - (f x : ℂ)‖ < η := by
  let δ : ℝ := η / 2
  have hδ : 0 < δ := by
    dsimp [δ]
    positivity
  let A := closure (oneLipschitzHalfRangeFamily m)
  have hA : IsCompact A := isCompact_closure_oneLipschitzHalfRangeFamily m
  obtain ⟨S, hS⟩ := exists_finite_frequency_approximation_of_compact m A hA hδ
  refine ⟨S, fun f hfLip hfRange ↦ ?_⟩
  have hfA : f ∈ A := subset_closure ⟨hfLip, hfRange⟩
  obtain ⟨c, hcS, hc⟩ := hS f hfA
  refine ⟨c, hcS, fun x ↦ ?_⟩
  have htwo : 2 * δ = η := by
    dsimp [δ]
    ring
  simpa only [htwo] using hc x


-- @@ L401-421 verbatim
/-- Uniform finite Fourier approximation for all annihilator-distance functions of a fixed
dimension.  Compactness is used only here: it turns the frequency support, initially depending on
the subgroup, into one finite set. -/
theorem exists_finite_frequency_approximation (m : ℕ) {δ : ℝ} (hδ : 0 < δ) :
    ∃ S : Finset (Fin m → ℤ), ∀ R : AddSubgroup (Fin m → ℤ),
      ∃ c : (Fin m → ℤ) →₀ ℂ, c.support ⊆ S ∧
        ∀ x : UnitAddTorus (Fin m),
          ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) x -
            (annihilatorDistance R x : ℂ)‖ < 2 * δ := by
  have htwoδ : 0 < 2 * δ := by positivity
  obtain ⟨S, hS⟩ := exists_uniform_frequency_set m htwoδ
  refine ⟨S, fun R ↦ hS (annihilatorDistance R) (annihilatorDistance_lipschitz R) ?_⟩
  intro x
  refine ⟨Metric.infDist_nonneg, ?_⟩
  calc
    Metric.infDist x (integerAnnihilator R) ≤ dist x 0 :=
      Metric.infDist_le_dist_of_mem (integerAnnihilator R).zero_mem
    _ ≤ 1 / 2 := by
      refine (dist_pi_le_iff (by positivity)).2 fun i ↦ ?_
      simpa only [Pi.zero_apply, dist_zero_right, abs_one] using
        (AddCircle.norm_le_half_period (p := (1 : ℝ)) (x := x i) one_ne_zero)


-- @@ L423-423 verbatim
/-! ## Averaging over a relation annihilator -/


-- @@ L425-429 verbatim
private noncomputable def annihilatorHaarMeasure {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) : MeasureTheory.Measure (integerAnnihilator R) :=
  letI : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  MeasureTheory.Measure.addHaarMeasure ⊤


-- @@ L431-440 verbatim
private instance annihilatorHaar_isProbability {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) :
    MeasureTheory.IsProbabilityMeasure (annihilatorHaarMeasure R) := by
  let : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  constructor
  change MeasureTheory.Measure.addHaarMeasure (⊤ : PositiveCompacts (integerAnnihilator R))
      Set.univ = 1
  rw [← PositiveCompacts.coe_top]
  exact MeasureTheory.Measure.addHaarMeasure_self


-- @@ L442-458 verbatim
private theorem integral_mFourier_translate {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) (a : Fin m → ℤ)
    (x : UnitAddTorus (Fin m)) :
    (∫ h : integerAnnihilator R, UnitAddTorus.mFourier a (x + h.1)
        ∂(annihilatorHaarMeasure R)) =
      UnitAddTorus.mFourier a x *
        ∫ h : integerAnnihilator R, UnitAddTorus.mFourier a h.1
          ∂(annihilatorHaarMeasure R) := by
  let : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  rw [← MeasureTheory.integral_const_mul]
  apply MeasureTheory.integral_congr_ae
  filter_upwards [] with h
  change (∏ i, fourier (a i) (x i + h.1 i)) =
    (∏ i, fourier (a i) (x i)) * ∏ i, fourier (a i) (h.1 i)
  simp only [fourier_apply, zsmul_add, AddCircle.toCircle_add,
    Circle.coe_mul, Finset.prod_mul_distrib]


-- @@ L460-494 verbatim
private theorem integral_mFourier_eq_zero_of_not_mem {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) {a : Fin m → ℤ} (ha : a ∉ R) :
    (∫ h : integerAnnihilator R, UnitAddTorus.mFourier a h.1
        ∂(annihilatorHaarMeasure R)) = 0 := by
  let : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  obtain ⟨x, hxR, hxa⟩ := exists_mem_integerAnnihilator_not_annihilate R ha
  let xR : integerAnnihilator R := ⟨x, hxR⟩
  let I : ℂ := ∫ h : integerAnnihilator R, UnitAddTorus.mFourier a h.1
      ∂(annihilatorHaarMeasure R)
  let K : PositiveCompacts (integerAnnihilator R) := ⊤
  have hmeasure : annihilatorHaarMeasure R =
      MeasureTheory.Measure.addHaarMeasure K := rfl
  let : (annihilatorHaarMeasure R).IsAddLeftInvariant := by
    rw [hmeasure]
    infer_instance
  have hinv : (∫ h : integerAnnihilator R,
      UnitAddTorus.mFourier a (xR.1 + h.1) ∂(annihilatorHaarMeasure R)) = I := by
    have htranslate := MeasureTheory.integral_add_left_eq_self
      (fun h : integerAnnihilator R ↦ UnitAddTorus.mFourier a h.1) xR
      (μ := annihilatorHaarMeasure R)
    simpa only [I, AddSubgroup.coe_add] using htranslate
  have hscalar : UnitAddTorus.mFourier a x * I = I := by
    rw [← integral_mFourier_translate R a x]
    exact hinv
  have hfactor : UnitAddTorus.mFourier a x ≠ 1 := by
    intro hone
    have hcirc : AddCircle.toCircle (torusRelationMap x a) = 1 := by
      apply Subtype.ext
      simpa [mFourier_eq_toCircle_relation] using hone
    exact hxa <| AddCircle.injective_toCircle one_ne_zero <| by
      simpa using hcirc
  by_contra hI
  apply hfactor
  exact mul_right_cancel₀ hI (by simpa only [one_mul] using hscalar)


-- @@ L496-507 verbatim
private theorem integral_mFourier_eq_one_of_mem {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) {a : Fin m → ℤ} (ha : a ∈ R) :
    (∫ h : integerAnnihilator R, UnitAddTorus.mFourier a h.1
        ∂(annihilatorHaarMeasure R)) = 1 := by
  let : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  have hone : ∀ h : integerAnnihilator R, UnitAddTorus.mFourier a h.1 = 1 := by
    intro h
    rw [mFourier_eq_toCircle_relation, h.2 a ha, AddCircle.toCircle_zero]
    rfl
  simp_rw [hone]
  simp


-- @@ L509-515 verbatim
/-- Averaging a finite Fourier polynomial over a translated annihilator deletes exactly the
frequencies which are not relations. -/
private noncomputable def filteredFourierTerm {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) (a : Fin m → ℤ) (z : ℂ)
    (x : UnitAddTorus (Fin m)) : ℂ := by
  classical
  exact if a ∈ R then z * UnitAddTorus.mFourier a x else 0


-- @@ L517-549 verbatim
private theorem integral_fourierPolynomial_translate {m : ℕ}
    (R : AddSubgroup (Fin m → ℤ)) (c : (Fin m → ℤ) →₀ ℂ)
    (x : UnitAddTorus (Fin m)) :
    (∫ h : integerAnnihilator R,
        (c.sum fun a z ↦ z • UnitAddTorus.mFourier a) (x + h.1)
        ∂(annihilatorHaarMeasure R)) =
      c.sum fun a z ↦ filteredFourierTerm R a z x := by
  classical
  let : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  rw [Finsupp.sum_of_support_subset c (s := c.support) Subset.rfl _ (by
    intro a _ha
    exact zero_smul ℂ (UnitAddTorus.mFourier a))]
  simp_rw [ContinuousMap.sum_apply]
  rw [Finsupp.sum_of_support_subset c (s := c.support) Subset.rfl _ (by
    intro a _ha
    simp [filteredFourierTerm])]
  rw [MeasureTheory.integral_finsetSum c.support]
  · apply Finset.sum_congr rfl
    intro a ha
    simp_rw [ContinuousMap.smul_apply, smul_eq_mul]
    rw [MeasureTheory.integral_const_mul, integral_mFourier_translate R a x]
    by_cases haR : a ∈ R
    · rw [filteredFourierTerm, ite_eq_left haR,
        integral_mFourier_eq_one_of_mem R haR, mul_one]
    · rw [filteredFourierTerm, ite_eq_right haR,
        integral_mFourier_eq_zero_of_not_mem R haR, mul_zero, mul_zero]
  · intro a _ha
    apply MeasureTheory.Integrable.const_mul
    exact (UnitAddTorus.mFourier a).continuous.comp
      (continuous_const.add continuous_subtype_val)
      |>.continuousOn.integrableOn_compact isCompact_univ |>
        MeasureTheory.integrableOn_univ.mp


-- @@ L551-646 verbatim
/-- A target satisfying all frequencies in `c.support` is close to the corresponding annihilator.
This is the quantitative conclusion extracted from the averaged finite Fourier approximation. -/
theorem infDist_integerAnnihilator_lt_of_finite_relations {m : ℕ} {δ : ℝ}
    {S : Finset (Fin m → ℤ)}
    (hS : ∀ R : AddSubgroup (Fin m → ℤ),
      ∃ c : (Fin m → ℤ) →₀ ℂ, c.support ⊆ S ∧
        ∀ x : UnitAddTorus (Fin m),
          ‖(c.sum fun a z ↦ z • UnitAddTorus.mFourier a) x -
            (annihilatorDistance R x : ℂ)‖ < 2 * δ)
    (R : AddSubgroup (Fin m → ℤ)) (t : UnitAddTorus (Fin m))
    (ht : ∀ a ∈ S, a ∈ R → torusRelationMap t a = 0) :
    Metric.infDist t (integerAnnihilator R) ≤ 4 * δ := by
  classical
  let : CompactSpace (integerAnnihilator R) :=
    isCompact_iff_compactSpace.mp (isClosed_integerAnnihilator R).isCompact
  obtain ⟨c, hcS, hc⟩ := hS R
  let P : C(UnitAddTorus (Fin m), ℂ) := c.sum fun a z ↦ z • UnitAddTorus.mFourier a
  have haverage :
      (∫ h : integerAnnihilator R, P (t + h.1) ∂(annihilatorHaarMeasure R)) =
        ∫ h : integerAnnihilator R, P h.1 ∂(annihilatorHaarMeasure R) := by
    rw [integral_fourierPolynomial_translate]
    have hzero := integral_fourierPolynomial_translate R c 0
    simp only [zero_add] at hzero
    rw [hzero]
    apply Finsupp.sum_congr
    intro a ha
    have haS : a ∈ S := hcS ha
    by_cases haR : a ∈ R
    · simp only [filteredFourierTerm, ite_eq_left haR]
      have hat : torusRelationMap t a = 0 := ht a haS haR
      rw [mFourier_eq_toCircle_relation, hat, AddCircle.toCircle_zero]
      simp [UnitAddTorus.mFourier]
    · simp only [filteredFourierTerm, ite_eq_right haR]
  have hdistInvariant : ∀ h : integerAnnihilator R,
      annihilatorDistance R (t + h.1) = annihilatorDistance R t := by
    intro h
    simp only [annihilatorDistance_apply]
    rw [← QuotientAddGroup.norm_mk (S := integerAnnihilator R),
      ← QuotientAddGroup.norm_mk (S := integerAnnihilator R)]
    congr 1
    exact (QuotientAddGroup.eq_iff_sub_mem).mpr (by simp [h.2])
  have hdistZero : ∀ h : integerAnnihilator R,
      annihilatorDistance R h.1 = 0 := by
    intro h
    rw [annihilatorDistance_apply]
    exact Metric.infDist_zero_of_mem h.2
  let It : ℂ := ∫ h : integerAnnihilator R, P (t + h.1)
      ∂(annihilatorHaarMeasure R)
  let I0 : ℂ := ∫ h : integerAnnihilator R, P h.1
      ∂(annihilatorHaarMeasure R)
  have hIt : ‖It - (annihilatorDistance R t : ℂ)‖ ≤ 2 * δ := by
    have hPint : MeasureTheory.Integrable
        (fun h : integerAnnihilator R ↦ P (t + h.1))
        (annihilatorHaarMeasure R) :=
      (P.continuous.comp (continuous_const.add continuous_subtype_val)).continuousOn
        |>.integrableOn_compact isCompact_univ |>
          (MeasureTheory.integrableOn_univ.mp)
    have hconstint : MeasureTheory.Integrable
        (fun _ : integerAnnihilator R ↦ (annihilatorDistance R t : ℂ))
        (annihilatorHaarMeasure R) := MeasureTheory.integrable_const _
    have hconst :
        (∫ _ : integerAnnihilator R, (annihilatorDistance R t : ℂ)
            ∂(annihilatorHaarMeasure R)) = (annihilatorDistance R t : ℂ) := by
      simp
    have hsub :
        (∫ h : integerAnnihilator R,
            (P (t + h.1) - (annihilatorDistance R t : ℂ))
              ∂(annihilatorHaarMeasure R)) =
          It - (annihilatorDistance R t : ℂ) := by
      rw [MeasureTheory.integral_sub hPint hconstint, hconst]
    rw [← hsub]
    simpa using MeasureTheory.norm_integral_le_of_norm_le_const
      (μ := annihilatorHaarMeasure R) (Eventually.of_forall fun h ↦
        (by simpa [hdistInvariant h] using (hc (t + h.1)).le))
  have hI0 : ‖I0‖ ≤ 2 * δ := by
    rw [show I0 = ∫ h : integerAnnihilator R, P h.1 - 0
        ∂(annihilatorHaarMeasure R) by simp [I0]]
    simpa using MeasureTheory.norm_integral_le_of_norm_le_const
      (μ := annihilatorHaarMeasure R) (Eventually.of_forall fun h ↦ by
        simpa [hdistZero h] using (hc h.1).le)
  have hII : It = I0 := haverage
  have hnorm : ‖(annihilatorDistance R t : ℂ)‖ ≤ 4 * δ := by
    calc
      ‖(annihilatorDistance R t : ℂ)‖ ≤
          ‖It - (annihilatorDistance R t : ℂ)‖ + ‖It‖ := by
        calc
          ‖(annihilatorDistance R t : ℂ)‖ =
              ‖((annihilatorDistance R t : ℂ) - It) + It‖ := by ring_nf
          _ ≤ ‖(annihilatorDistance R t : ℂ) - It‖ + ‖It‖ := norm_add_le _ _
          _ = ‖It - (annihilatorDistance R t : ℂ)‖ + ‖It‖ := by
            rw [norm_sub_rev]
      _ ≤ 2 * δ + 2 * δ := by
        exact add_le_add hIt (by simpa [hII] using hI0)
      _ = 4 * δ := by ring
  simpa [annihilatorDistance_apply, Complex.norm_real, Real.norm_eq_abs,
    abs_of_nonneg Metric.infDist_nonneg] using hnorm


-- @@ L648-655 verbatim
/-- A uniform Kronecker bound remains valid when the permitted relation height is increased. -/
theorem IsUniformKroneckerBound.mono {m q q' : ℕ} {ε : ℝ}
    (h : IsUniformKroneckerBound.{u} m ε q) (hqq' : q ≤ q') :
    IsUniformKroneckerBound.{u} m ε q' := by
  intro G _ z t ht
  apply h (G := G) z t
  intro a ha haz
  exact ht a (ha.trans hqq') haz


-- @@ L657-693 verbatim
/-- Unconditional uniform finite-dimensional Kronecker theorem.

For every tuple length and every positive error, a single finite height bound detects enough
integer relations to guarantee approximation by a character of every Abelian group. -/
theorem exists_uniform_kronecker_bound (m : ℕ) {ε : ℝ} (hε : 0 < ε) :
    ∃ q : ℕ, IsUniformKroneckerBound.{u} m ε q := by
  classical
  let δ : ℝ := ε / 8
  have hδ : 0 < δ := by
    dsimp [δ]
    positivity
  obtain ⟨S, hS⟩ := exists_finite_frequency_approximation m hδ
  let q : ℕ := max 1 (S.sup intVectorHeight)
  refine ⟨q, ?_⟩
  intro G _ z t ht
  let R : AddSubgroup (Fin m → ℤ) := relationGroup z
  have hfinite : ∀ a ∈ S, a ∈ R → torusRelationMap t a = 0 := by
    intro a haS haR
    apply ht a
    · exact (Finset.le_sup haS).trans (Nat.le_max_right 1 _)
    · exact haR
  have hdist : Metric.infDist t (integerAnnihilator R) ≤ 4 * δ :=
    infDist_integerAnnihilator_lt_of_finite_relations hS R t hfinite
  have hdistlt : Metric.infDist t (integerAnnihilator R) < ε := by
    apply hdist.trans_lt
    dsimp [δ]
    linarith
  have hnonempty : (integerAnnihilator R : Set (UnitAddTorus (Fin m))).Nonempty :=
    ⟨0, (integerAnnihilator R).zero_mem⟩
  obtain ⟨x, hx, htx⟩ := (Metric.infDist_lt_iff hnonempty).mp hdistlt
  have hrelations : RespectsRelations z x := by
    intro a ha
    exact hx a ha
  obtain ⟨χ, hχ⟩ := exists_character_of_respectsRelations z x hrelations
  refine ⟨χ, fun i ↦ ?_⟩
  have hi : dist (t i) (x i) < ε := (dist_pi_lt_iff hε).mp htx i
  simpa only [hχ i, ← dist_eq_norm, dist_comm] using hi


-- @@ L695-698 verbatim
/-- Camel-case compatibility spelling for downstream modules. -/
theorem exists_uniformKroneckerBound (m : ℕ) {ε : ℝ} (hε : 0 < ε) :
    ∃ q : ℕ, IsUniformKroneckerBound.{u} m ε q :=
  exists_uniform_kronecker_bound m hε


-- @@ L700-700 verbatim
end Wallace
