/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import LeanPool.DomainTheory.ContinuousLattice.Specialization


-- @@ L10-42 verbatim
/-!
# March 1972 correction (Scott, pp. 135–136)

Robin Milner observed that Scott's remark before Proposition 2.5 was wrong: a
`T₀`-topology
on a complete lattice need not have every open set Scott-open. The two extreme
`T₀`-topologies
inducing the same partial order are generated by

* `{x | not x <= y}` (the *lower* subbasic sets), and
* `{x | y ⊑ x}` (principal up-sets).

The corrected proofs of Propositions **2.9**, **2.10**, and **3.3** assume the
given
topology is *contained in* the Scott (lattice) topology: every open set of the
given
topology is Scott-open.

For Proposition **2.10**, Scott distinguishes ambient joins in `D'` from subspace
joins in
a retract `D ⊆ D'`: the prime in `⊔S′` marks the *index* (join taken in `D'`), not
a
"primed join" operator. The retraction identity used in the corrected argument is
`j(⊔S′) = ⊔S` for directed `S ⊆ D` (see
`IsContinuousLatticeRetraction.retr_ambientSSup_eq_sSup`
in `FunctionSpaces.lean`).

Page **136** adds that function spaces pose no subspace/sup mismatch: lubs are
computed
pointwise, so the product (relativized) topology is contained in the Scott
topology once
the Milner hypothesis is in place.
-/


-- @@ L44-44 verbatim
@[expose] public section


-- @@ L46-46 verbatim
namespace Domain.ContinuousLattice


-- @@ L48-48 verbatim
open Set Topology


-- @@ L50-50 verbatim
variable {D D' : Type*} [CompleteLattice D] [CompleteLattice D']


-- @@ L52-52 verbatim
/-! ### Extreme `T₀`-topologies inducing the order -/


-- @@ L54-56 verbatim
/-- Lower subbasic set `{x | not x <= y}` from Scott's March 1972 correction. -/
def scottLowerSubbasisSet (y : D) : Set D :=
  { x | ¬ x ≤ y }


-- @@ L58-60 verbatim
/-- Upper subbasic set `{x | y ⊑ x}` (principal up-set) from the correction. -/
def scottPrincipalUpSet (y : D) : Set D :=
  Set.Ici y


-- @@ L62-62 verbatim
/-! ### Milner hypothesis for 2.9, 2.10, 3.3 -/


-- @@ L64-70 verbatim
/-- **March 1972 correction.** The given topology `τ` is coarser than (or equal
to) the Scott
topology: every set open in `τ` is Scott-open. Equivalently `Opens(τ) ⊆
Opens(Scott)`,
i.e. `scottTopologicalSpace ≤ τ` in mathlib's order on topologies. -/
def CoarserThanScottTopology (τ : TopologicalSpace D) : Prop :=
  scottTopologicalSpace ≤ τ


-- @@ L72-74 verbatim
theorem scottOpen_of_coarserThanScott {τ : TopologicalSpace D} (hτ : CoarserThanScottTopology τ)
    {U : Set D} (hU : @IsOpen D τ U) : ScottOpen U :=
  isOpen_iff_scottOpen.mp (hτ U hU)


-- @@ L76-76 verbatim
end Domain.ContinuousLattice
