/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import LeanPool.DomainTheory.Neighborhood.Basic
public import Mathlib.Basic.Finite.Defs
public import Mathlib.Data.Set.Basic
import Mathlib.Data.Set.Finite.Basic


-- @@ L13-41 verbatim
/-!
# Exercise 1.16 (Scott 1981, PRG-19, §1) — cofinite subsets of `ℕ`

`Δ = ℕ`, `𝒟 =` the *cofinite* subsets (`Xᶜ` finite). This is a neighbourhood
system
(`cofiniteSystem`), closed under all finite intersections. Scott asks to show
`|𝒟| ≅ (𝒫(ℕ), ⊆)`.

The order-isomorphism `cofiniteIso : |𝒟| ≃o Set ℕ` sends a filter `x` to its set
of
**excluded points** `toExcluded x = {n ∣ {n}ᶜ ∈ x}`, with inverse
`ofExcluded E = {Y cofinite ∣ Yᶜ ⊆ E}` (a filter for *every* `E ⊆ ℕ`). The key
reconstruction
lemma is `mem_compl_of_finite`: `⋂_{n∈F} {n}ᶜ = Fᶜ ∈ x` for finite `F` of points
whose
single-point deletions are in `x`.

We also record `ofExcluded_univ_isTotal` / `le_ofExcluded_univ` — the unique total
element is the
`⊑`-top `ofExcluded ℕ` (= all of `𝒟`), matching the greatest element `ℕ ∈ 𝒫(ℕ)` —
and
`fullSystem`, a second system (all subsets) closed under finite intersection.

`mem_compl_of_finite` uses `Set.Finite.induction_on` (and `Set.Finite` is
classical), so the
classification lemmas are not choice-free; the *constructions* (`ofExcluded`,
`cofiniteSystem`)
are `[propext, Quot.sound]`.
-/


-- @@ L43-43 verbatim
@[expose] public section


-- @@ L45-45 verbatim
namespace Domain.Neighborhood


-- @@ L47-47 verbatim
namespace Cofinite


-- @@ L49-49 verbatim
open NeighborhoodSystem


-- @@ L51-62 verbatim
/-- **Exercise 1.16 — the cofinite neighbourhood system on `ℕ`.** `X ∈ 𝒟 iff Xᶜ`
finite;
closed under finite intersection since `(X∩Y)ᶜ = Xᶜ ∪ Yᶜ`. -/
def cofiniteSystem : NeighborhoodSystem ℕ where
  mem X := Xᶜ.Finite
  master := Set.univ
  master_mem := by rw [Set.compl_univ]; exact Set.finite_empty
  inter_mem := by
    intro X Y _ hX hY _ _
    rw [Set.compl_inter]
    exact hX.union hY
  sub_master := fun _ => Set.subset_univ _


-- @@ L64-64 verbatim
@[simp] theorem cofiniteSystem_mem {X : Set ℕ} : cofiniteSystem.mem X ↔ Xᶜ.Finite := Iff.rfl


-- @@ L66-80 verbatim
/-- The filter generated by an arbitrary set `E ⊆ ℕ` of "excluded points":
`ofExcluded E = {Y cofinite ∣ Yᶜ ⊆ E}`. This is a filter for *every* `E`. -/
def ofExcluded (E : Set ℕ) : cofiniteSystem.Element where
  mem Y := Yᶜ.Finite ∧ Yᶜ ⊆ E
  sub h := h.1
  master_mem := by
    change (Set.univ : Set ℕ)ᶜ.Finite ∧ (Set.univ : Set ℕ)ᶜ ⊆ E
    simp_all
  inter_mem := by
    rintro Y1 Y2 ⟨hf1, hs1⟩ ⟨hf2, hs2⟩
    rw [Set.compl_inter]
    exact ⟨hf1.union hf2, Set.union_subset hs1 hs2⟩
  up_mem := by
    rintro Y1 Y2 ⟨_, hs1⟩ hY2 hsub
    exact ⟨hY2, (Set.compl_subset_compl.mpr hsub).trans hs1⟩


-- @@ L82-83 verbatim
@[simp] theorem mem_ofExcluded {E Y : Set ℕ} :
    (ofExcluded E).mem Y ↔ Yᶜ.Finite ∧ Yᶜ ⊆ E := Iff.rfl


-- @@ L85-86 verbatim
/-- The set of points *excluded* by a filter `x`: `toExcluded x = {n ∣ {n}ᶜ ∈ x}`. -/
def toExcluded (x : cofiniteSystem.Element) : Set ℕ := {n | x.mem ({n}ᶜ)}


-- @@ L88-89 verbatim
@[simp] theorem mem_toExcluded {x : cofiniteSystem.Element} {n : ℕ} :
    n ∈ toExcluded x ↔ x.mem ({n}ᶜ) := Iff.rfl


-- @@ L91-93 verbatim
/-- Each `{n}ᶜ` is a neighbourhood (its complement `{n}` is finite). -/
theorem mem_compl_singleton (n : ℕ) : cofiniteSystem.mem (({n} : Set ℕ)ᶜ) := by
  simp_all


-- @@ L95-106 verbatim
/-- **Reconstruction lemma.** For finite `F` of points each of whose
single-deletion `{n}ᶜ`
is in the filter `x`, the intersection `⋂_{n∈F} {n}ᶜ = Fᶜ` is also in `x`. -/
theorem mem_compl_of_finite (x : cofiniteSystem.Element) {F : Set ℕ} (hF : F.Finite) :
    (∀ n ∈ F, x.mem ({n}ᶜ)) → x.mem (Fᶜ) := by
  induction F, hF using Set.Finite.induction_on with
  | empty => intro _; rw [Set.compl_empty]; exact x.master_mem
  | @insert a s _ _ ih =>
    intro h
    rw [Set.insert_eq, Set.compl_union]
    exact x.inter_mem (h a (Set.mem_insert a s))
      (ih (fun n hn => h n (Set.mem_insert_of_mem a hn)))


-- @@ L108-110 verbatim
/-- For `n ∉ Y`, the neighbourhood `Y` is contained in `{n}ᶜ`. -/
theorem subset_compl_singleton {Y : Set ℕ} {n : ℕ} (hn : n ∈ Yᶜ) : Y ⊆ ({n} : Set ℕ)ᶜ := by
  simp_all


-- @@ L112-114 verbatim
theorem toExcluded_ofExcluded (E : Set ℕ) : toExcluded (ofExcluded E) = E := by
  ext n
  simp_all


-- @@ L116-129 verbatim
theorem ofExcluded_toExcluded (x : cofiniteSystem.Element) :
    ofExcluded (toExcluded x) = x := by
  apply Element.ext
  intro Y
  rw [mem_ofExcluded]
  constructor
  · rintro ⟨hfin, hsub⟩
    have h := mem_compl_of_finite x hfin (fun n hn => mem_toExcluded.mp (hsub hn))
    rwa [compl_compl] at h
  · intro hxY
    refine ⟨x.sub hxY, ?_⟩
    intro n hn
    rw [mem_toExcluded]
    exact x.up_mem hxY (mem_compl_singleton n) (subset_compl_singleton hn)


-- @@ L131-152 verbatim
/-- **Exercise 1.16 — `|𝒟| ≅ (𝒫(ℕ), ⊆)`.** The filter `x` corresponds to its
excluded-point
set `toExcluded x`; inclusion of filters matches inclusion of excluded sets. -/
def cofiniteIso : cofiniteSystem.Element ≃o Set ℕ where
  toFun := toExcluded
  invFun := ofExcluded
  left_inv := ofExcluded_toExcluded
  right_inv := toExcluded_ofExcluded
  map_rel_iff' := by
    intro x x'
    constructor
    · intro h Y hY
      have hfin : Yᶜ.Finite := x.sub hY
      have hsub : Yᶜ ⊆ toExcluded x' := by
        intro n hn
        have hx : x.mem (({n} : Set ℕ)ᶜ) :=
          x.up_mem hY (mem_compl_singleton n) (subset_compl_singleton hn)
        exact h (mem_toExcluded.mpr hx)
      have h2 := mem_compl_of_finite x' hfin (fun n hn => mem_toExcluded.mp (hsub hn))
      rwa [compl_compl] at h2
    · intro h n hn
      exact mem_toExcluded.mpr (h _ (mem_toExcluded.mp hn))


-- @@ L154-154 verbatim
/-! ### Total elements. -/


-- @@ L156-161 verbatim
/-- Every filter is `⊑ ofExcluded ℕ` (the whole family `𝒟`; every cofinite `Y` has
`Yᶜ ⊆ ℕ`). -/
theorem le_ofExcluded_univ (x : cofiniteSystem.Element) :
    x ≤ ofExcluded Set.univ := by
  intro Y hY
  exact ⟨x.sub hY, Set.subset_univ _⟩


-- @@ L163-167 verbatim
/-- **Exercise 1.16 — the unique total element.** `ofExcluded ℕ` (matching the
greatest
element `ℕ ∈ 𝒫(ℕ)`) is total: it is `⊑`-maximal. -/
theorem ofExcluded_univ_isTotal : cofiniteSystem.IsTotal (ofExcluded Set.univ) :=
  fun y _ => le_ofExcluded_univ y


-- @@ L169-169 verbatim
/-! ### A second `∩`-closed system: all subsets. -/


-- @@ L171-183 verbatim
/-- **Exercise 1.16 (second example).** All subsets of `ℕ` form a neighbourhood
system, trivially
closed under *all* finite intersections. Unlike `cofiniteSystem` it is **not**
positive (`∅` is a
neighbourhood). Every neighbourhood is a finite element via `principal`; its total
elements are
the principal filters of singletons (the system is "flat"). -/
def fullSystem : NeighborhoodSystem ℕ where
  mem _ := True
  master := Set.univ
  master_mem := trivial
  inter_mem := fun _ _ _ _ => trivial
  sub_master := fun _ => Set.subset_univ _


-- @@ L185-185 verbatim
end Cofinite


-- @@ L187-187 verbatim
end Domain.Neighborhood
