/-
Copyright (c) 2026 Matevz Miščič, Maša Žaucer, Job Petrovčič. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matevz Miščič, Maša Žaucer, Job Petrovčič
-/
module

public import LeanPool.ArtinWedderburn.IdealProd
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.NoncommRing
import Mathlib.Tactic.NormNum.Abs
import Mathlib.Tactic.NormNum.DivMod
import Mathlib.Tactic.NormNum.OfScientific


-- @@ L16-22 verbatim
/-!
# Left and right multiplication sets

Provides `leftMul a = Ra`, `rightMul a = aR`, the `leftIdealOfElement` constructor, and
the consequence that `aRb = 0` collapses these auxiliary sets to zero. Used by the prime ring
characterisation.
-/


-- @@ L24-24 verbatim
@[expose] public section


-- @@ L26-26 verbatim
namespace LeanPool.ArtinWedderburn


-- @@ L28-30 verbatim
variable {R : Type*} [Ring R] (a b : R)

-- leftMul a is the set Ra

-- @@ L31-34 verbatim
/-- The set `Ra = {r * a | r : R}` of left multiples of `a`. -/
def leftMul (a : R) : Set R := {x | ∃ r : R, x = r * a}

-- rightMul a is the set aR

-- @@ L35-36 verbatim
/-- The set `aR = {a * r | r : R}` of right multiples of `a`. -/
def rightMul (a : R) : Set R := {x | ∃ r : R, x = a * r}


-- @@ L38-41 verbatim
theorem left_mul_zero_impl_mul_zero : bothMul a b = {0} → a * b = 0 := by
  intro h
  have k : a * b ∈ bothMul a b := by use 1; simp
  simp_all


-- @@ L43-46 verbatim
theorem in_particular (a c b : R) : bothMul a b = {0} → a * c * b = 0 := by
  intro h
  have k : a * c * b ∈ bothMul a b := by use c
  simp_all


-- @@ L48-50 verbatim
open Pointwise Set

-- aRb = 0 implies Ra = 0 or Rb = 0

-- @@ L51-68 verbatim
theorem both_mul_zero_one_left_zero :
    bothMul a b = {0} → (leftMul a) * (leftMul b) = {0} := by
  intro h
  apply Set.ext_iff.mpr
  intro x
  constructor
  · rintro ⟨y, ⟨r, hr⟩, z, ⟨s, hs⟩, hx⟩
    simp only at hx
    calc
      x = y * z := by rw [← hx]
      _ = (r * a) * (s * b) := by rw [hr, hs]
      _ = r * (a * s * b) := by noncomm_ring
      _ = r * 0 := by rw [in_particular a s b h]
      _ = 0 := by noncomm_ring
  · intro hx
    rw [Set.mem_singleton_iff] at hx
    refine ⟨0, ⟨0, by noncomm_ring⟩, 0, ⟨0, by noncomm_ring⟩, ?_⟩
    simp_all


-- @@ L70-83 verbatim
/-- The principal left ideal `Ra` generated by `a`, packaged as an `Ideal R`. -/
def leftIdealOfElement (a : R) : Ideal R :=
  { carrier := leftMul a,
    zero_mem' := by use 0; noncomm_ring,
    add_mem' := by
      rintro x y ⟨r, hr⟩ ⟨s, hs⟩
      use r + s
      rw [hr, hs]
      noncomm_ring,
    smul_mem' := by
      rintro x y ⟨r, hr⟩
      use x * r
      rw [hr]
      noncomm_ring }


-- @@ L85-86 verbatim
theorem carrier_of_left_ideal_of_element (a : R) :
    (leftIdealOfElement a).carrier = leftMul a := rfl


-- @@ L88-88 verbatim
end LeanPool.ArtinWedderburn
