/-
Copyright (c) 2026 Michael Stoll. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Michael Stoll
-/
module

public import Mathlib.Algebra.Algebra.Rat
public import Mathlib.Algebra.CharP.IntermediateField
public import Mathlib.FieldTheory.PolynomialGaloisGroup
public import Mathlib.GroupTheory.RegularWreathProduct
public import Mathlib.RingTheory.SimpleRing.Principal

public import LeanPool.QuadraticIterates.ArchMath1992.Sequences
public import LeanPool.QuadraticIterates.Mathlib.FieldTheory.Multiquadratic
public import Mathlib.Order.CompletePartialOrder
import LeanPool.QuadraticIterates.Mathlib.Algebra.BigOperators
import LeanPool.QuadraticIterates.Mathlib.Data.Nat
import LeanPool.QuadraticIterates.Mathlib.GroupTheory.Card
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Data.Int.ConditionallyCompleteOrder
import Mathlib.Data.Int.Star
import Mathlib.RingTheory.Radical.NatInt


-- @@ L25-41 verbatim
/-!
# The iterates of `X² + a`, their splitting fields and Galois groups

The iterates `f_n` of `f = X² + a`, the splitting field `K_n` of `f_n` over `ℚ` taken inside
`AlgebraicClosure ℚ`, the Galois group `Ω_n = Gal(f_n/ℚ)` and the iterated wreath product `[C₂]ⁿ`;
the integer sequences `c_n` and `b_n` and the rescaled polynomial `normPoly a`; 2-independence of
families of rationals. The main results here are Odoni's embedding `Ω_n ↪ [C₂]ⁿ`
(`odoni_embedding`), the Kummer tower `K_n ⊆ K_{n+1}` with `[K_{n+1} : K_n] ≤ 2^{2^n}`
(`kummer_degree_bound`), and Lemma 1.4 (`embed_equiv`).

Part of the formalization of M. Stoll, *Galois groups over ℚ of some iterated polynomials*,
Arch. Math. **59** (1992), 239-244; see `QuadraticIterates.ArchMath1992`.

## Notation

`fℚ[a, n]` is scoped notation for the iterate `f_n` viewed in `ℚ[X]`.
-/


-- @@ L43-43 verbatim
@[expose] public section


-- @@ L45-45 verbatim
open Polynomial


-- @@ L47-47 verbatim
namespace QuadraticIterates


-- @@ L49-53 verbatim
/-- The iterates `f_n` of `f = X² + a` over a commutative (semi)ring `R`: `f_0 = X`,
`f_{n+1} = f_n² + a`. Over `ℤ` (`R := ℤ`) this is the sequence of the paper. -/
noncomputable def iteratedPoly {R : Type*} [CommSemiring R] (a : R) : ℕ → R[X]
  | 0 => X
  | n + 1 => (iteratedPoly a n) ^ 2 + C a


-- @@ L55-55 verbatim
@[simp] lemma iteratedPoly_zero {R : Type*} [CommSemiring R] (a : R) : iteratedPoly a 0 = X := rfl


-- @@ L57-58 verbatim
lemma iteratedPoly_succ {R : Type*} [CommSemiring R] (a : R) (n : ℕ) :
    iteratedPoly a (n + 1) = iteratedPoly a n ^ 2 + C a := rfl


-- @@ L60-67 verbatim
/-- Iterating commutes with any ring homomorphism: the image of `f_n` under `φ` is the `n`-th
iterate over the codomain with parameter `φ a`. -/
lemma map_iteratedPoly {R S : Type*} [CommSemiring R] [CommSemiring S] (φ : R →+* S) (a : R)
    (n : ℕ) : (iteratedPoly a n).map φ = iteratedPoly (φ a) n := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [iteratedPoly_succ, Polynomial.map_add, Polynomial.map_pow, ih, map_C, iteratedPoly_succ]


-- @@ L69-77 verbatim
/-- `f_{n+1} = f_n ∘ (X² + a)`: the iterate can also grow on the right. -/
lemma iteratedPoly_succ_comp {R : Type*} [CommSemiring R] (a : R) (n : ℕ) :
    iteratedPoly a (n + 1) = (iteratedPoly a n).comp (X ^ 2 + C a) := by
  induction n with
  | zero => simp [iteratedPoly_succ]
  | succ k ih =>
    rw [iteratedPoly_succ a (k + 1)]
    nth_rw 1 [ih]
    rw [iteratedPoly_succ, add_comp, pow_comp, C_comp]


-- @@ L79-86 verbatim
/-- Iterates compose additively: `f_{m+n} = f_m ∘ f_n`. -/
lemma iteratedPoly_add {R : Type*} [CommSemiring R] (a : R) (m n : ℕ) :
    iteratedPoly a (m + n) = (iteratedPoly a m).comp (iteratedPoly a n) := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [show m + (k + 1) = (m + k) + 1 from rfl, iteratedPoly_succ_comp, ih, comp_assoc,
      ← iteratedPoly_succ_comp]


-- @@ L88-89 verbatim
/-- `fℚ[a, n]` denotes the `n`-th iterate `f_n = iteratedPoly a n`, viewed in `ℚ[X]`. -/
scoped notation "fℚ[" a ", " n "]" => map (Int.castRingHom ℚ) (iteratedPoly a n)


-- @@ L91-94 verbatim
/-- The splitting field `K_n` of `f_n` over `ℚ`, as the intermediate field of `AlgebraicClosure ℚ`
generated by the roots of `f_n`. -/
noncomputable abbrev splittingField (a : ℤ) (n : ℕ) : IntermediateField ℚ (AlgebraicClosure ℚ) :=
  IntermediateField.adjoin ℚ ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ))


-- @@ L96-98 verbatim
instance splittingField.instIsSplittingField (a : ℤ) (n : ℕ) :
    IsSplittingField ℚ ↥(splittingField a n) (fℚ[a, n]) :=
  IntermediateField.adjoin_rootSet_isSplittingField (IsAlgClosed.splits _)


-- @@ L100-102 verbatim
instance splittingField.instFiniteDimensional (a : ℤ) (n : ℕ) :
    FiniteDimensional ℚ ↥(splittingField a n) :=
  IsSplittingField.finiteDimensional _ (fℚ[a, n])


-- @@ L104-106 verbatim
instance splittingField.instIsGalois (a : ℤ) (n : ℕ) : IsGalois ℚ ↥(splittingField a n) :=
  have : Normal ℚ ↥(splittingField a n) := Normal.of_isSplittingField (fℚ[a, n])
  IsGalois.mk


-- @@ L108-109 verbatim
/-- The Galois group `Ω_n = Gal(f_n/ℚ)` of the `n`-th iterate, via Mathlib's `Polynomial.Gal`. -/
noncomputable abbrev GaloisGroup (a : ℤ) (n : ℕ) : Type := (fℚ[a, n]).Gal


-- @@ L111-113 verbatim
/-- The `n`-fold iterated regular wreath product `[C_2]^n` of `C_2 = Multiplicative (ZMod 2)`, via
Mathlib's `IteratedWreathProduct`. -/
abbrev WreathPower (n : ℕ) : Type := IteratedWreathProduct (Multiplicative (ZMod 2)) n

-- @@ L114-114 verbatim
/-! ### The sequences `c` and `b` over `ℤ` -/


-- @@ L116-118 verbatim
/-- `X² + a` is an even polynomial. -/
lemma evenPoly_X_sq_add_C {R : Type*} [CommSemiring R] (a : R) : EvenPoly (X ^ 2 + C a) :=
  ⟨X + C a, by rw [map_add, expand_X, expand_C]⟩


-- @@ L120-123 verbatim
/-- `b·X² + c` is an even polynomial. -/
lemma evenPoly_C_mul_X_sq_add_C {R : Type*} [CommSemiring R] (b c : R) :
    EvenPoly (C b * X ^ 2 + C c) :=
  ⟨C b * X + C c, by simp⟩


-- @@ L125-127 verbatim
/-- The integer sequence `c_n` (indexed from 1): `c_1 = -a`, `c_{n+1} = c_n² + a`; the value at
index `0` is `0`. It is the `γ`-sequence of `X² + a` with `ε = -1`. -/
noncomputable def cSeq (a : ℤ) : ℕ → ℤ := gammaSeq (X ^ 2 + C a) (-1)


-- @@ L129-130 verbatim
/-- `c_n = γ_n(X² + a, ε = -1)` (definitional). -/
lemma cSeq_eq_gammaSeq (a : ℤ) (n : ℕ) : cSeq a n = gammaSeq (X ^ 2 + C a) (-1) n := rfl


-- @@ L132-132 verbatim
@[simp] lemma cSeq_zero (a : ℤ) : cSeq a 0 = 0 := rfl


-- @@ L134-134 verbatim
@[simp] lemma cSeq_one (a : ℤ) : cSeq a 1 = -a := by simp [cSeq_eq_gammaSeq]


-- @@ L136-138 verbatim
/-- The recursion `c_{n+1} = c_n² + a`, valid for `n ≥ 1`. -/
theorem cSeq_succ (a : ℤ) {n : ℕ} (hn : 1 ≤ n) : cSeq a (n + 1) = cSeq a n ^ 2 + a := by
  simp only [cSeq_eq_gammaSeq, gammaSeq_succ _ _ hn, eval_add, eval_pow, eval_X, eval_C]


-- @@ L140-140 verbatim
lemma cSeq_two (a : ℤ) : cSeq a 2 = a ^ 2 + a := by rw [cSeq_succ a le_rfl, cSeq_one]; ring


-- @@ L142-144 verbatim
/-- **Strong divisibility** for the `c`-sequence: `gcd (c_m) (c_n) = |c_{gcd m n}|`. -/
theorem cSeq_gcd (a : ℤ) (m n : ℕ) : Int.gcd (cSeq a m) (cSeq a n) = (cSeq a (m.gcd n)).natAbs :=
  gammaSeq_gcd (evenPoly_X_sq_add_C a) (.inr rfl) m n


-- @@ L146-150 verbatim
/-- Strong divisibility of the `c`-sequence in the `Associated`-of-`gcd` form consumed by the
`moebiusFactorR` API. -/
theorem cSeq_associated_gcd (a : ℤ) (m n : ℕ) :
    Associated (gcd (cSeq a m) (cSeq a n)) (cSeq a (m.gcd n)) :=
  gammaSeq_associated_gcd (evenPoly_X_sq_add_C a) (by norm_num) m n


-- @@ L152-162 verbatim
/-- `c_{k+1} = (-1)^{2^k} · f_k(a)`; in particular `c_{k+1} = f_k(a)` for `k ≥ 1`. -/
theorem cSeq_succ_eq_neg_one_pow_mul_eval (a : ℤ) (k : ℕ) :
    cSeq a (k + 1) = (-1 : ℤ) ^ 2 ^ k * (iteratedPoly a k).eval a := by
  induction k with
  | zero => simp [cSeq_one]
  | succ i ih =>
    have hsq : ((-1 : ℤ) ^ 2 ^ i) ^ 2 = 1 := by rw [pow_right_comm, neg_one_sq, one_pow]
    have hone : (-1 : ℤ) ^ 2 ^ (i + 1) = 1 :=
      (Nat.even_pow.mpr ⟨even_two, i.succ_ne_zero⟩).neg_one_pow
    rw [cSeq_succ a (by lia), ih, hone, one_mul, mul_pow, hsq, one_mul]
    simp [iteratedPoly_succ]


-- @@ L164-167 verbatim
/-- The Möbius factors `b_n = ∏_{d ∣ n} c_d^{μ(n/d)} ∈ ℤ` of the `c`-sequence: the specialization
of the general `β`-sequence to `X² + a`, `ε = -1` (an integer by strong divisibility, see
`intCast_bSeq`). -/
noncomputable def bSeq (a : ℤ) (n : ℕ) : ℤ := betaSeq (X ^ 2 + C a) (-1) n


-- @@ L169-169 verbatim
lemma bSeq_eq_moebiusFactorR (a : ℤ) (n : ℕ) : bSeq a n = moebiusFactorR (cSeq a) n := rfl


-- @@ L171-172 verbatim
@[simp] lemma bSeq_one (a : ℤ) : bSeq a 1 = -a := by
  rw [bSeq_eq_moebiusFactorR, moebiusFactorR_one, cSeq_one]


-- @@ L174-178 verbatim
/-- The rescaling `|a|·X² + sign a` of `X² + a`. Substituting `x ↦ |a|·x` turns the recursion
`c_{n+1} = c_n² + a` into the `γ`-recursion of `normPoly a`, whose sequence is therefore
`|c_n| / |a|` (`abs_cSeq_eq_gammaSeq_mul_abs`) — in particular positive, which is what
Lemma 2.2 needs and `X² + a` itself does not provide. -/
noncomputable def normPoly (a : ℤ) : ℤ[X] := C |a| * X ^ 2 + C a.sign


-- @@ L180-181 verbatim
@[simp] lemma eval_normPoly (a x : ℤ) : (normPoly a).eval x = |a| * x ^ 2 + a.sign := by
  simp [normPoly]


-- @@ L183-183 verbatim
lemma evenPoly_normPoly (a : ℤ) : EvenPoly (normPoly a) := evenPoly_C_mul_X_sq_add_C |a| a.sign


-- @@ L185-185 verbatim
/-! ### 2-independence of families of rationals -/


-- @@ L187-191 verbatim
/-- Nonzero rationals `a_1, …, a_n` are *2-independent* if their classes in `ℚ*/(ℚ*)²` are
`𝔽₂`-linearly independent: no nonempty subfamily has product a square in `ℚ`. -/
def TwoIndependent {n : ℕ} (v : Fin n → ℚ) : Prop :=
  (∀ i, v i ≠ 0) ∧
    ∀ S : Finset (Fin n), S.Nonempty → ¬IsSquare (∏ i ∈ S, v i)


-- @@ L193-202 verbatim
/-- Square roots of 2-independent rationals in a `ℚ`-algebra are pairwise distinct. -/
theorem TwoIndependent.sqrt_injective {n : ℕ} {v : Fin n → ℚ} (hv : TwoIndependent v)
    {K : Type*} [Field K] [Algebra ℚ K] {x : Fin n → K}
    (hx : ∀ i, x i ^ 2 = algebraMap ℚ K (v i)) : Function.Injective x := by
  intro i j hij
  by_contra hne
  have h2 : v i = v j := (algebraMap ℚ K).injective (by rw [← hx i, ← hx j, hij])
  refine hv.2 {i, j} ⟨i, by simp⟩ ?_
  rw [Finset.prod_pair hne, ← h2]
  exact ⟨v i, rfl⟩


-- @@ L204-214 verbatim
/-- 2-independence of `Fin.snoc v c` restricts to the initial family `v`. -/
theorem TwoIndependent.of_snoc {n : ℕ} {v : Fin n → ℚ} {c : ℚ}
    (h : TwoIndependent (Fin.snoc v c)) : TwoIndependent v := by
  obtain ⟨hv0, hvsq⟩ := h
  refine ⟨fun i ↦ ?_, fun S hS ↦ ?_⟩
  · simpa [Fin.snoc_castSucc] using hv0 i.castSucc
  · have hSmap : (S.map Fin.castSuccEmb).Nonempty := by
      obtain ⟨x, hx⟩ := hS
      exact ⟨x.castSucc, Finset.mem_map.mpr ⟨x, hx, rfl⟩⟩
    simpa [Fin.snoc_castSucc, Finset.prod_map S Fin.castSuccEmb (Fin.snoc v c)] using
      hvsq (S.map Fin.castSuccEmb) hSmap


-- @@ L216-243 verbatim
/-- A family of rationals is 2-independent iff the family of its classes in `ℚˣ/(ℚˣ)²` is
`𝔽₂`-linearly independent. -/
theorem twoIndependent_iff_linearIndependent {n : ℕ} (v : Fin n → ℚ) :
    TwoIndependent v ↔ LinearIndependent (ZMod 2) (fun i ↦ sqClass (v i)) := by
  rw [Fintype.linearIndependent_iff]
  have h01 : ∀ x : ZMod 2, x = 0 ∨ x = 1 := by decide
  refine ⟨fun ⟨hv0, hsq⟩ g hg i ↦ ?_, fun H ↦ ?_⟩
  · by_contra hgi
    have hg1 : g i = 1 := (h01 (g i)).resolve_left hgi
    refine hsq (Finset.univ.filter fun j ↦ g j = 1)
      ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ i, hg1⟩⟩ ?_
    rw [isSquare_prod_iff_sum_sqClass_eq_zero (fun i _ ↦ hv0 i),
      ← sum_zmod_two_smul_eq_sum_filter (fun i ↦ sqClass (v i)) g, hg]
  · have hne (i) : sqClass (v i) ≠ 0 := fun hi ↦ by
      have h := H (fun j ↦ if j = i then 1 else 0) ?_ i
      · simp at h
      · rw [Finset.sum_eq_single i (fun j _ hj ↦ by simp [hj])
          (fun h ↦ absurd (Finset.mem_univ i) h), ite_eq_left rfl, hi, smul_zero]
    have hv0 (i) : v i ≠ 0 := fun hvi ↦ hne i (by rw [hvi, sqClass_zero])
    refine ⟨hv0, fun S hS hsqS ↦ ?_⟩
    obtain ⟨i, hiS⟩ := hS
    have hfilt : Finset.univ.filter (fun j ↦ (if j ∈ S then (1 : ZMod 2) else 0) = 1) = S := by
      ext j
      by_cases hj : j ∈ S <;> simp [hj, zero_ne_one (α := ZMod 2)]
    have hg : ∑ j, (if j ∈ S then (1 : ZMod 2) else 0) • sqClass (v j) = 0 := by
      rw [sum_zmod_two_smul_eq_sum_filter (fun j ↦ sqClass (v j)), hfilt]
      exact (isSquare_prod_iff_sum_sqClass_eq_zero (fun i _ ↦ hv0 i)).mp hsqS
    exact absurd (H _ hg i) (by simp [hiS])



-- @@ L246-246 verbatim
section


-- @@ L248-248 verbatim
variable (a : ℤ)


-- @@ L250-250 verbatim
/-! ### Degrees, roots and the Galois group of the iterates over `ℚ` -/


-- @@ L252-256 verbatim
lemma natDegree_iteratedPoly (n : ℕ) : (iteratedPoly a n).natDegree = 2 ^ n := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [iteratedPoly_succ, natDegree_add_C, natDegree_pow, ih, pow_succ']


-- @@ L258-259 verbatim
lemma map_iteratedPoly_succ_eq_sq_add (k : ℕ) : fℚ[a, k + 1] = (fℚ[a, k]) ^ 2 + C (a : ℚ) := by
  simp [iteratedPoly_succ]


-- @@ L261-262 verbatim
lemma map_iteratedPoly_one : fℚ[a, 1] = X ^ 2 + C (a : ℚ) := by
  simp [map_iteratedPoly_succ_eq_sq_add]


-- @@ L264-265 verbatim
lemma map_iteratedPoly_succ (k : ℕ) : fℚ[a, k + 1] = (fℚ[a, k]).comp (X ^ 2 + C (a : ℚ)) := by
  rw [map_iteratedPoly, map_iteratedPoly, iteratedPoly_succ_comp]; rfl


-- @@ L267-276 verbatim
lemma monic_iteratedPoly (n : ℕ) : (iteratedPoly a n).Monic := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [iteratedPoly_succ]
    have hpow : (iteratedPoly a k ^ 2).Monic := ih.pow 2
    refine hpow.add_of_left <| degree_C_le.trans_lt ?_
    refine natDegree_pos_iff_degree_pos.mp ?_
    rw [natDegree_pow, natDegree_iteratedPoly]
    positivity


-- @@ L278-281 verbatim
lemma ncard_rootSet_iteratedPoly_le (n : ℕ) :
    (((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)).ncard) ≤ 2 ^ n :=
  (ncard_rootSet_le _ _).trans_eq
    (by rw [(monic_iteratedPoly a n).natDegree_map, natDegree_iteratedPoly])


-- @@ L283-291 verbatim
lemma mem_rootSet_iteratedPoly_succ (n : ℕ) (β : AlgebraicClosure ℚ) :
    β ∈ (fℚ[a, n + 1]).rootSet (AlgebraicClosure ℚ) ↔
    β ^ 2 + (a : AlgebraicClosure ℚ) ∈ (fℚ[a, n]).rootSet (AlgebraicClosure ℚ) := by
  apply (mem_rootSet_of_injective (x := β) (algebraMap ℚ (AlgebraicClosure ℚ)).injective
    ((monic_iteratedPoly a (n + 1)).map (Int.castRingHom ℚ)).ne_zero).trans
  simpa [map_iteratedPoly_succ a n, aeval_comp] using
    (mem_rootSet_of_injective (x := β ^ 2 + (a : AlgebraicClosure ℚ))
      (algebraMap ℚ (AlgebraicClosure ℚ)).injective
      ((monic_iteratedPoly a n).map (Int.castRingHom ℚ)).ne_zero).symm


-- @@ L293-315 verbatim
/-- Any `ℚ`-automorphism of its algebraic closure raised to the power `2 ^ m` fixes every
root of `f_m`. -/
theorem pow_two_pow_apply_root (ϕ : AlgebraicClosure ℚ ≃ₐ[ℚ] AlgebraicClosure ℚ)
    {m : ℕ} {γ : AlgebraicClosure ℚ} (hγ : γ ∈ (fℚ[a, m]).rootSet (AlgebraicClosure ℚ)) :
    (ϕ ^ (2 ^ m)) γ = γ := by
  induction m generalizing γ with
  | zero =>
    rw [iteratedPoly_zero, map_X,
      mem_rootSet_of_injective (algebraMap ℚ (AlgebraicClosure ℚ)).injective X_ne_zero] at hγ
    obtain rfl : γ = 0 := by simpa using hγ
    simp
  | succ k ih =>
    have hsq : ((ϕ ^ 2 ^ k) γ) ^ 2 = γ ^ 2 := by
      have hfix := ih ((mem_rootSet_iteratedPoly_succ a k γ).mp hγ)
      have hmap : (ϕ ^ 2 ^ k) (γ ^ 2 + (a : AlgebraicClosure ℚ))
          = ((ϕ ^ 2 ^ k) γ) ^ 2 + (a : AlgebraicClosure ℚ) := by
        simp [map_add, map_pow, map_intCast]
      rw [hmap] at hfix
      linear_combination hfix
    rw [show (2 : ℕ) ^ (k + 1) = 2 ^ k + 2 ^ k by ring, pow_add, AlgEquiv.mul_apply]
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h
    · rw [h, h]
    · rw [h, map_neg, h, neg_neg]


-- @@ L317-329 verbatim
/-- `Ω_n = Gal(f_n/ℚ)` is a 2-group. -/
theorem isPGroup_galoisGroup (n : ℕ) : IsPGroup 2 (GaloisGroup a n) := by
  set F := fℚ[a, n]
  have : Fact (F.map (algebraMap ℚ (AlgebraicClosure ℚ))).Splits := ⟨IsAlgClosed.splits _⟩
  have : IsAlgClosure ℚ (AlgebraicClosure ℚ) := AlgebraicClosure.instIsAlgClosure ℚ
  refine isPGroup_iff_pow_pow_eq_one.mpr fun σ ↦ ⟨n, ?_⟩
  obtain ⟨ϕ, rfl⟩ := Gal.restrict_surjective F (AlgebraicClosure ℚ) σ
  apply Gal.galActionHom_injective F (AlgebraicClosure ℚ)
  rw [map_pow, map_one, ← map_pow, ← map_pow]
  ext β
  simp only [Equiv.Perm.one_apply]
  exact (Gal.galActionHom_restrict F (AlgebraicClosure ℚ) (ϕ ^ 2 ^ n) β).trans
    (pow_two_pow_apply_root a ϕ β.2)


-- @@ L331-357 verbatim
/-- Odoni's embedding theorem: `Ω_n` embeds into `[C_2]^n`. -/
theorem odoni_embedding (n : ℕ) :
    ∃ φ : GaloisGroup a n →* WreathPower n, Function.Injective φ := by
  set F := fℚ[a, n]
  set E := AlgebraicClosure ℚ
  have : Fact (F.map (algebraMap ℚ E)).Splits := ⟨IsAlgClosed.splits _⟩
  have hcard_le : Fintype.card ↥(F.rootSet E)
      ≤ Fintype.card (Fin n → Multiplicative (ZMod 2)) := by
    rw [show Fintype.card (Fin n → Multiplicative (ZMod 2)) = 2 ^ n by
      rw [Fintype.card_fun, Fintype.card_multiplicative, ZMod.card, Fintype.card_fin]]
    calc Fintype.card ↥(F.rootSet E) = (F.rootSet E).ncard := by
          rw [Set.ncard_eq_toFinset_card', Set.toFinset_card]
      _ ≤ 2 ^ n := ncard_rootSet_iteratedPoly_le a n
  obtain ⟨emb⟩ := Function.Embedding.nonempty_of_card_le hcard_le
  set Θ := (Equiv.Perm.extendDomainHom (Equiv.ofInjective emb emb.injective)).comp
    (Gal.galActionHom F E)
  have hΘinj : Function.Injective ⇑Θ :=
    (Equiv.Perm.extendDomainHom_injective (Equiv.ofInjective emb emb.injective)).comp
      (Gal.galActionHom_injective F E)
  obtain ⟨Q, hQ⟩ := IsPGroup.exists_le_sylow
    ((isPGroup_galoisGroup a n).of_equiv (MonoidHom.ofInjective hΘinj))
  let e := Sylow.mulEquivIteratedWreathProduct 2 n (Fin n → Multiplicative (ZMod 2))
    (by simp [Nat.card_eq_fintype_card]) (Multiplicative (ZMod 2))
    (by simp [Nat.card_eq_fintype_card]) Q
  exact ⟨e.toMonoidHom.comp ((Subgroup.inclusion hQ).comp Θ.rangeRestrict),
    e.injective.comp ((Subgroup.inclusion_injective hQ).comp
      (Θ.rangeRestrict_injective_iff.mpr hΘinj))⟩


-- @@ L359-363 verbatim
/-- Every element of the algebraic closure of `ℚ` has a square root after subtracting `a`; the
square roots of the `α - a` for `α` a root of `f_n` generate `K_{n+1}` over `K_n`. -/
lemma exists_sq_eq_sub (α : AlgebraicClosure ℚ) :
    ∃ β : AlgebraicClosure ℚ, β ^ 2 = α - (a : AlgebraicClosure ℚ) :=
  IsAlgClosed.exists_pow_nat_eq _ two_pos


-- @@ L365-373 verbatim
lemma splittingField_le_succ (n : ℕ) : splittingField a n ≤ splittingField a (n + 1) := by
  refine IntermediateField.adjoin_le_iff.mpr fun α hα ↦ ?_
  obtain ⟨β, hβ⟩ := exists_sq_eq_sub a α
  have hβmem : β ∈ splittingField a (n + 1) :=
    IntermediateField.subset_adjoin ℚ _ ((mem_rootSet_iteratedPoly_succ a n β).mpr
      (by simpa [hβ, sub_add_cancel] using hα))
  have hα_eq : α = β ^ 2 + (a : AlgebraicClosure ℚ) := by rw [hβ]; ring
  rw [hα_eq]
  exact add_mem (pow_mem hβmem 2) (IntermediateField.intCast_mem _ a)


-- @@ L375-376 verbatim
lemma splittingField_mono {m n : ℕ} (hmn : m ≤ n) : splittingField a m ≤ splittingField a n :=
  Nat.le_induction le_rfl (fun k _ ih ↦ ih.trans (splittingField_le_succ a k)) n hmn


-- @@ L378-384 verbatim
/-- `K_0 = ℚ`: the only root of `f_0 = X` is `0`. -/
@[simp] lemma splittingField_zero_eq_bot : splittingField a 0 = ⊥ := by
  refine IntermediateField.adjoin_eq_bot_iff.mpr fun x hx ↦ ?_
  rw [iteratedPoly_zero, map_X, mem_rootSet_of_injective
    (algebraMap ℚ (AlgebraicClosure ℚ)).injective X_ne_zero] at hx
  rw [SetLike.mem_coe, show x = 0 by simpa using hx]
  exact zero_mem _


-- @@ L386-386 verbatim
end


-- @@ L388-388 verbatim
section


-- @@ L390-390 verbatim
variable (a : ℤ)


-- @@ L392-392 verbatim
/-! ### The Kummer tower `K_n ⊆ K_{n+1}` -/


-- @@ L394-429 verbatim
/-- `K_{n+1} = K_n(√(α - a) : α root of f_n)`: the relative degree `[K_{n+1} : K_n]` is the
degree of the multiquadratic extension of `K_n` generated by a choice of square roots of the
`α - a`. -/
theorem relfinrank_succ_eq_finrank_adjoin (n : ℕ) (g : AlgebraicClosure ℚ → AlgebraicClosure ℚ)
    (hg : ∀ α, g α ^ 2 = α - (a : AlgebraicClosure ℚ)) :
    (splittingField a n).relfinrank (splittingField a (n + 1))
      = Module.finrank ↥(splittingField a n)
          ↥(IntermediateField.adjoin ↥(splittingField a n)
            (g '' ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)))) := by
  set t : Set (AlgebraicClosure ℚ) := g '' ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ))
  set Kn := splittingField a n
  have hC : splittingField a (n + 1) = Kn ⊔ IntermediateField.adjoin ℚ t := by
    refine le_antisymm ?_ (sup_le (splittingField_le_succ a n) ?_)
    · refine IntermediateField.adjoin_le_iff.mpr fun β hβ ↦ ?_
      have hgmem : g (β ^ 2 + (a : AlgebraicClosure ℚ)) ∈ IntermediateField.adjoin ℚ t :=
        IntermediateField.subset_adjoin ℚ _
          ⟨β ^ 2 + (a : AlgebraicClosure ℚ), (mem_rootSet_iteratedPoly_succ a n β).mp hβ, rfl⟩
      have hsq : β ^ 2 = g (β ^ 2 + (a : AlgebraicClosure ℚ)) ^ 2 := by
        rw [hg (β ^ 2 + (a : AlgebraicClosure ℚ)), add_sub_cancel_right]
      rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h
      · rw [h]
        exact SetLike.le_def.mp le_sup_right hgmem
      · rw [h]
        exact neg_mem (SetLike.le_def.mp le_sup_right hgmem)
    · refine IntermediateField.adjoin_le_iff.mpr ?_
      rintro x ⟨α, hα, rfl⟩
      exact IntermediateField.subset_adjoin ℚ _
        ((mem_rootSet_iteratedPoly_succ a n (g α)).mpr (by rwa [hg α, sub_add_cancel]))
  have hsup : IntermediateField.restrictScalars ℚ (IntermediateField.adjoin (↥Kn) t)
      = Kn ⊔ IntermediateField.adjoin ℚ t :=
    IntermediateField.restrictScalars_adjoin_eq_sup ℚ Kn t
  have hle : Kn ≤ IntermediateField.restrictScalars ℚ (IntermediateField.adjoin (↥Kn) t) := by
    rw [hsup]
    exact le_sup_left
  rw [hC, ← hsup, IntermediateField.relfinrank_eq_finrank_of_le hle]
  congr 1


-- @@ L431-457 verbatim
lemma relfinrank_succ_le (n : ℕ) :
    (splittingField a n).relfinrank (splittingField a (n + 1)) ≤ 2 ^ 2 ^ n := by
  classical
  choose g hg using exists_sq_eq_sub a
  set s : Finset (AlgebraicClosure ℚ) :=
    ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)).toFinset.image g with hs
  have hcard : s.card ≤ 2 ^ n := by
    calc s.card
        ≤ ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)).toFinset.card := Finset.card_image_le
      _ = ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ)).ncard := (Set.ncard_eq_toFinset_card' _).symm
      _ ≤ 2 ^ n := ncard_rootSet_iteratedPoly_le a n
  have hsq : ∀ x ∈ s, ∃ c : ↥(splittingField a n), x ^ 2 = algebraMap _ (AlgebraicClosure ℚ) c := by
    intro x hx
    rw [hs, Finset.mem_image] at hx
    obtain ⟨α, hα, rfl⟩ := hx
    rw [Set.mem_toFinset] at hα
    exact ⟨⟨α - (a : AlgebraicClosure ℚ), sub_mem (IntermediateField.subset_adjoin ℚ _ hα)
      (IntermediateField.intCast_mem _ a)⟩, hg α⟩
  have hst : g '' ((fℚ[a, n]).rootSet (AlgebraicClosure ℚ))
      = (s : Set (AlgebraicClosure ℚ)) := by
    rw [hs, Finset.coe_image, Set.coe_toFinset]
  calc (splittingField a n).relfinrank (splittingField a (n + 1))
      = Module.finrank ↥(splittingField a n)
          (IntermediateField.adjoin ↥(splittingField a n) (s : Set (AlgebraicClosure ℚ))) := by
        rw [relfinrank_succ_eq_finrank_adjoin a n g hg, hst]
    _ ≤ 2 ^ s.card := finrank_adjoin_finset_sq_le hsq
    _ ≤ 2 ^ 2 ^ n := Nat.pow_le_pow_right (by norm_num) hcard


-- @@ L459-474 verbatim
/-- Facts 1.0 (Kummer tower): `K_n ⊆ K_{n+1}`, the extension `K_{n+1}` is generated over `K_n` by
roots of `f_{n+1}` whose squares lie in `K_n`, and `[K_{n+1} : K_n] ≤ 2^{2^n}`. -/
theorem kummer_degree_bound (n : ℕ) :
    splittingField a n ≤ splittingField a (n + 1) ∧
    (splittingField a (n + 1) = splittingField a n ⊔
      IntermediateField.adjoin ℚ
        ((fℚ[a, n + 1]).rootSet (AlgebraicClosure ℚ)) ∧
      ∀ β ∈ (fℚ[a, n + 1]).rootSet (AlgebraicClosure ℚ),
        β ^ 2 ∈ splittingField a n) ∧
    (splittingField a n).relfinrank (splittingField a (n + 1)) ≤ 2 ^ 2 ^ n := by
  have hmono := splittingField_le_succ a n
  refine ⟨hmono, ⟨(sup_eq_right.mpr hmono).symm, fun β hβ ↦ ?_⟩, relfinrank_succ_le a n⟩
  rw [← add_sub_cancel_right (β ^ 2) (a : AlgebraicClosure ℚ)]
  exact sub_mem
    (IntermediateField.subset_adjoin ℚ _ ((mem_rootSet_iteratedPoly_succ a n β).mp hβ))
    (IntermediateField.intCast_mem _ a)


-- @@ L476-480 verbatim
lemma card_wreathPower (n : ℕ) : Nat.card (WreathPower n) = 2 ^ (2 ^ n - 1) := by
  rw [IteratedWreathProduct.card,
    show Nat.card (Multiplicative (ZMod 2)) = 2 by simp [Nat.card_eq_fintype_card],
    Nat.geomSum_eq le_rfl]
  norm_num


-- @@ L482-489 verbatim
lemma card_galoisGroup_eq_finrank (n : ℕ) :
    Nat.card (GaloisGroup a n) = Module.finrank ℚ (splittingField a n) := by
  set F := fℚ[a, n]
  have e : ↥(splittingField a n) ≃ₐ[ℚ] F.SplittingField := IsSplittingField.algEquiv _ F
  have : Normal ℚ F.SplittingField := SplittingField.instNormal F
  have : IsGalois ℚ F.SplittingField := IsGalois.mk
  exact (IsGalois.card_aut_eq_finrank ℚ F.SplittingField).trans
    (LinearEquiv.finrank_eq e.toLinearEquiv).symm


-- @@ L491-521 verbatim
/-- Lemma 1.4: `Ω_n` embeds into `[C_2]^n`, and `Ω_{n+1} ≅ [C_2]^{n+1}` iff `Ω_n ≅ [C_2]^n` and
`[K_{n+1} : K_n] = 2^{2^n}`. -/
theorem embed_equiv (n : ℕ) :
    (∃ φ : GaloisGroup a n →* WreathPower n, Function.Injective φ) ∧
    (Nonempty (GaloisGroup a (n + 1) ≃* WreathPower (n + 1)) ↔
      Nonempty (GaloisGroup a n ≃* WreathPower n) ∧
        (splittingField a n).relfinrank (splittingField a (n + 1)) = 2 ^ 2 ^ n) := by
  obtain ⟨φn, hφn⟩ := odoni_embedding a n
  obtain ⟨φn1, hφn1⟩ := odoni_embedding a (n + 1)
  refine ⟨⟨φn, hφn⟩, ?_⟩
  have htower : Module.finrank ℚ ↥(splittingField a n)
        * (splittingField a n).relfinrank (splittingField a (n + 1))
      = Module.finrank ℚ ↥(splittingField a (n + 1)) :=
    IntermediateField.finrank_bot_mul_relfinrank (splittingField_le_succ a n)
  have hxle : Module.finrank ℚ ↥(splittingField a n) ≤ 2 ^ (2 ^ n - 1) := by
    refine Nat.le_of_dvd (by positivity) ?_
    have h := Subgroup.card_dvd_of_injective φn hφn
    rwa [card_galoisGroup_eq_finrank, card_wreathPower] at h
  have hrle := relfinrank_succ_le a n
  have hexp : 2 ^ (2 ^ (n + 1) - 1) = 2 ^ (2 ^ n - 1) * 2 ^ 2 ^ n := by
    rw [← pow_add]
    congr 1
    have := Nat.one_le_two_pow (n := n)
    rw [pow_succ]
    lia
  rw [φn1.nonempty_mulEquiv_iff_card_eq hφn1, φn.nonempty_mulEquiv_iff_card_eq hφn,
    card_galoisGroup_eq_finrank, card_galoisGroup_eq_finrank, card_wreathPower, card_wreathPower]
  refine ⟨fun hy ↦ ?_, fun ⟨hxeq, hreq⟩ ↦ ?_⟩
  · exact Nat.eq_and_eq_of_le_of_le_of_mul_eq_mul hxle hrle (by rw [htower, hy, hexp])
      (by positivity) (by positivity)
  · rw [← htower, hxeq, hreq, ← hexp]


-- @@ L523-523 verbatim
end


-- @@ L525-525 verbatim
end QuadraticIterates
