/-
Copyright (c) 2026 OpenAI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: OpenAI
-/
module

public import LeanPool.NavierStokesAndEuler.Euler.PacketBudgetTimeChange
public import LeanPool.NavierStokesAndEuler.Euler.PacketCylinderTermBudget
public import LeanPool.NavierStokesAndEuler.Euler.PacketMeanGradeBounds
public import LeanPool.NavierStokesAndEuler.Euler.PacketProfileBudget
public import LeanPool.NavierStokesAndEuler.Euler.PacketSourceProfiles
public import LeanPool.NavierStokesAndEuler.Euler.TransversePacketForwardGradeBounds
import LeanPool.NavierStokesAndEuler.Euler.PacketGevreyProfileChoice
import LeanPool.NavierStokesAndEuler.Euler.PacketProfileBudgetTransport
import LeanPool.NavierStokesAndEuler.Euler.PacketSourceRegularity
import LeanPool.NavierStokesAndEuler.Euler.PacketCylinderBoundTransfer
import LeanPool.NavierStokesAndEuler.Euler.PacketCylinderTimeUnique
import LeanPool.NavierStokesAndEuler.Euler.PacketCylinderWeightedLinear
import LeanPool.NavierStokesAndEuler.Euler.PacketForcingBounds
import LeanPool.NavierStokesAndEuler.Euler.ParameterSobolevScaling
import LeanPool.NavierStokesAndEuler.Euler.TransversePacketParity


-- @@ L24-26 verbatim
/-! One fixed radius bounds every grade generated by the actual mean and
zero-initial direct-forward solvers.  Only the genuine primary datum remains
as input; no later forcing or solution estimate is assumed. -/


-- @@ L28-28 verbatim
section


-- @@ L30-31 verbatim
/-! One complete quantitative recursion step, using the actual mean and zero-initial direct-forward
transverse solvers. -/


-- @@ L33-33 verbatim
section


-- @@ L35-36 verbatim
/-! Every forced direct-forward grade starts from zero and obeys the genuine
five-field grade budget at the common radius. -/


-- @@ L38-38 verbatim
@[expose] public section


-- @@ L40-40 verbatim
noncomputable section


-- @@ L42-42 verbatim
namespace EulerTransversePacketForward.Budget


-- @@ L44-47 verbatim
open Set EulerSmoothLimit EulerTransversePacketProvider EulerPacketCylinderField
  EulerPacketProfileRecursion EulerContinuousTimeWeight EulerParameterWordGevrey
  EulerGevrey EulerLiftedGradientSpace EulerLpCylinderTranslation EulerCylinderSobolev
  EulerPacketShiftArithmetic


-- @@ L49-57 verbatim
variable {P : ℝ} [Fact (0 < P)]
  {U : Type*} [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
  {D : Data U} (L : Budget D (Fin 4) 6)
  (N : EulerTransversePacketJoin.NormalBudget D 6 L.R)
  (W : GradeGuards (P := P) L N 1) {raw : VectorField}
  (G : Forcing P D raw) (F : Field P D.T raw) (c : ℝ) (hc : 0 < c)
  (p : ℕ) (hp : 2 ≤ p)
  (hforce : (F.normalized D.T_pos.le (c • L.g)
    (smul_profile_pos L.g L.positive c hc)).WordBound 6 L.R 1 (highForceShift p))


-- @@ L59-59 verbatim
include W hc hp hforce


-- @@ L61-81 verbatim
theorem forced_grade_bounds :
    ((G.vectorField (InitialData.zero P D)).normalized D.T_pos.le (c • L.g)
      (smul_profile_pos L.g L.positive c hc)).WordBound 6 L.R 1 (highShift p) ∧
    ((G.vectorDerivativeField (InitialData.zero P D)).normalized D.T_pos.le (c • L.g)
      (smul_profile_pos L.g L.positive c hc)).WordBound 6 L.R 1 (highShift p) ∧
    ((G.curlCorrectorField (InitialData.zero P D)).normalized D.T_pos.le (c • L.g)
      (smul_profile_pos L.g L.positive c hc)).WordBound 6 L.R 1 (highShift p) ∧
    ((G.correctorDerivativeField (InitialData.zero P D)).normalized D.T_pos.le (c • L.g)
      (smul_profile_pos L.g L.positive c hc)).WordBound 6 L.R 1 (highShift p) ∧
    ((G.scalarGradientField (InitialData.zero P D)).normalized D.T_pos.le (c • L.g)
      (smul_profile_pos L.g L.positive c hc)).WordBound 6 L.R 1 (highShift p) := by
  have hf : (G.forcingField.normalized D.T_pos.le L.g L.positive).WordBound
      6 L.R (c*1) (highForceShift p) :=
    (hforce.unscale_profile D.T_pos.le L.g L.positive c hc).transfer _
  have hi (n : ℕ) : block standardDirection 6
      (fun a => translate P a ((InitialData.zero P D).value : CylinderL2 P U)) n 0 ≤
        (c*1)*majorant L.R (highForceShift p) n := by
    simpa only [InitialData.zero,Submodule.coe_zero,map_zero,block_zero_function,mul_one] using
      mul_nonneg hc.le (majorant_nonneg L.R (zero_le_one.trans L.radius_one) (highForceShift p) n)
  exact L.grade_fields N 1 W G (InitialData.zero P D) c hc (highForceShift p) (highShift p)
    (by simp only [highForceShift,highShift]; omega) hf hi


-- @@ L83-83 verbatim
end EulerTransversePacketForward.Budget


-- @@ L85-85 verbatim
end

-- @@ L86-86 verbatim
end


-- @@ L88-88 verbatim
end


-- @@ L90-90 verbatim
@[expose] public section


-- @@ L92-92 verbatim
noncomputable section


-- @@ L94-94 verbatim
namespace EulerPacketCylinderField.ProfileBudget


-- @@ L96-97 verbatim
open Set EulerSmoothLimit EulerPacketPointJets EulerPacketProfileRecursion
  EulerPacketTimeProfile EulerPacketShiftArithmetic EulerParameterWordGevrey


-- @@ L99-230 verbatim
theorem forwardStep
    {P : ℝ} [Fact (0 < P)] (M : EulerMeanPacketProvider.Data)
    {U : Type*} [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
    (D : EulerTransversePacketProvider.Data U) (hTime : M.T = D.T)
    (L : EulerTransversePacketForward.Budget D (Fin 4) 6)
    (N : EulerTransversePacketJoin.NormalBudget D 6 L.R)
    (W : EulerTransversePacketForward.Budget.GradeGuards (P := P) L N 1)
    (LM : EulerMeanPacketProvider.Budget M 6 L.R)
    (WM : EulerMeanPacketProvider.Budget.GradeGuards LM)
    {O : Operators} (C : CoefficientData P M.T O) (BC : CoefficientBudget C)
    (hmean : O.meanSolve = EulerMeanPacketProvider.meanSolve M)
    (hhigh : O.highSolve = EulerTransversePacketProvider.highSolve P D
        (EulerTransversePacketProvider.InitialData.zero P D))
    (hcorrector : O.curlCorrector = D.curlCorrector P)
    (hRc : sobolevCoefficientRadius (Fin 4) BC.Rc ≤ L.R) (hcost : BC.termCost ≤ L.R)
    (S : Scales (Icc (0 : ℝ) M.T))
    {p : ℕ} {a : ℕ → Profile} (hp : 2 ≤ p)
    (G : ∀ i, i < p → ProfileRegularity P M.T M.T_pos.le D.support (a i))
    (hG : ∀ i (hi : i < p), 1 ≤ i → ProfileBudget (G i hi) S L.R i)
    (hc₀ : (a 0).corrector = 0) (hB₁ : (a 1).mean = 0)
    (hA : ∀ i, i < p → ∀ (t : Icc (0 : ℝ) M.T) x θ,
      inner ℝ (O.normal (t, (x, θ))) ((a i).high (t, (x, θ))) = 0)
    (c : ℝ) (hc : 0 < c)
    (hprofile : timeProfileChange (S.high p) hTime = c • L.g)
    (H : ProfileRegularity P M.T M.T_pos.le D.support (EulerPacketProfileRecursion.step O p a)) :
    ProfileBudget H S L.R p := by
  let I := EulerTransversePacketProvider.InitialData.zero P D
  let F := ProfileRegularity.prefixFields G
  let V := G (p-1) (by omega)
  have hV := hG (p-1) (by omega) (by omega)
  have BF : PrefixBound F M.T_pos.le S L.R := {
    high := fun i hi hi1 => (hG i hi hi1).high
    mean := fun i hi hi2 => (hG i hi (by omega)).mean
    corrector := fun i hi hi1 => (hG i hi hi1).corrector
  }
  have hB : ∀ i, i < p → ∀ (t : Icc (0 : ℝ) M.T) x θ,
      (a i).mean (t,(x,θ)) = (a i).mean (t,(x,0)) := fun i hi => (G i hi).mean_angle
  let MF := F.meanForce C (by omega) M.T_pos V.correctorDerivative V.corrector_time V.pressure
  have hMF : (MF.normalized M.T_pos.le (S.mean p) (S.mean_pos p)).WordBound
      6 L.R 1 (meanForceShift p) :=
    BF.meanForce_bound hp M.T_pos V.correctorDerivative V.corrector_time V.pressure BC
      hV.correctorDerivative hV.pressure L.radius_one hRc hcost hc₀ hB₁ hA hB
  let hm : Nonempty (EulerMeanPacketProvider.Forcing M (meanForce O p a)) :=
    ⟨F.meanForcing M C (by omega) V.correctorDerivative V.corrector_time V.pressure⟩
  let GM := Classical.choice hm
  have hMeanSolve : O.meanSolve (meanForce O p a) = (GM.vector,GM.scalar) := by
    rw [hmean,EulerMeanPacketProvider.meanSolve_of_admissible M _ hm]
  let newMean : Field P M.T (meanResult O p a).1 := (GM.vectorCylinderField P).congr
    (fun t x θ => by change (O.meanSolve (meanForce O p a)).1 _ = _; rw [hMeanSolve])
  have hmBounds := LM.grade_bounds WM S GM MF p hp hMF
  have hNew : (newMean.normalized M.T_pos.le (S.mean p) (S.mean_pos p)).WordBound
      6 L.R 1 (meanShift p) := hmBounds.1.of_path_eq _ rfl
  let HF := F.highForce C hp M.T_pos V.correctorDerivative V.corrector_time V.pressure newMean
  have hHF : (HF.normalized M.T_pos.le (S.high p) (S.high_pos p)).WordBound
      6 L.R 1 (highForceShift p) :=
    BF.highForce_bound hp M.T_pos V.correctorDerivative V.corrector_time V.pressure BC
      hV.correctorDerivative hV.pressure L.radius_one hRc hcost hc₀ hB₁ hA hB newMean hNew
  let hh : Nonempty (EulerTransversePacketProvider.Forcing P D (highForce O p a)) :=
    ⟨F.highForcing M D hTime C hp V.correctorDerivative V.corrector_time V.pressure hmean
      (ProfileRegularity.prefixLocality G) V.pressure_zero⟩
  let GH := Classical.choice hh
  let hg := smul_profile_pos L.g L.positive c hc
  have hHFD : ((HF.changeTime hTime).normalized D.T_pos.le (c • L.g) hg).WordBound
      6 L.R 1 (highForceShift p) :=
    hHF.normalized_changeTime M.T_pos.le (S.high p) (S.high_pos p) hTime D.T_pos.le
      (c • L.g) hg hprofile
  have hj := L.forced_grade_bounds N W GH (HF.changeTime hTime) c hc p hp hHFD
  have hback : timeProfileChange (c • L.g) hTime.symm = S.high p := by
    rw [← hprofile,timeProfileChange_roundtrip]
  have hv := hj.1.normalized_changeTime D.T_pos.le (c • L.g) hg
    hTime.symm M.T_pos.le (S.high p) (S.high_pos p) hback
  have hvt := hj.2.1.normalized_changeTime D.T_pos.le (c • L.g) hg
    hTime.symm M.T_pos.le (S.high p) (S.high_pos p) hback
  have hcv := hj.2.2.1.normalized_changeTime D.T_pos.le (c • L.g) hg
    hTime.symm M.T_pos.le (S.high p) (S.high_pos p) hback
  have hct := hj.2.2.2.1.normalized_changeTime D.T_pos.le (c • L.g) hg
    hTime.symm M.T_pos.le (S.high p) (S.high_pos p) hback
  have hpv := hj.2.2.2.2.normalized_changeTime D.T_pos.le (c • L.g) hg
    hTime.symm M.T_pos.le (S.high p) (S.high_pos p) hback
  have hHighSolve : O.highSolve (highForce O p a) =
      (GH.vector I,GH.scalar I) := by
    rw [hhigh]
    exact EulerTransversePacketProvider.highSolve_of_admissible D I _ hh
  have hHighVal : (EulerPacketProfileRecursion.step O p a).high =
      GH.vector I := congrArg Prod.fst hHighSolve
  have hMeanVal : (EulerPacketProfileRecursion.step O p a).mean = GM.vector := congrArg Prod.fst
      hMeanSolve
  have hCorrectorVal : (EulerPacketProfileRecursion.step O p a).corrector =
      D.curlCorrector P (GH.vector I) := by
    change O.curlCorrector (O.highSolve (highForce O p a)).1 = _
    rw [hcorrector,hHighSolve]
  have hPressureVal : pressureGradient (EulerPacketProfileRecursion.step O p a).highPressure =
      pressureGradient (GH.scalar I) :=
    congrArg pressureGradient (congrArg Prod.snd hHighSolve)
  let highBase : Field P M.T (EulerPacketProfileRecursion.step O p a).high :=
    ((GH.vectorField I).changeTime hTime.symm).congr
      (fun t x θ => congrFun hHighVal (t,(x,θ)))
  let meanBase : Field P M.T (EulerPacketProfileRecursion.step O p a).mean :=
    (GM.vectorCylinderField P).congr (fun t x θ => congrFun hMeanVal (t,(x,θ)))
  let correctorBase : Field P M.T (EulerPacketProfileRecursion.step O p a).corrector :=
    ((GH.curlCorrectorField I).changeTime hTime.symm).congr
      (fun t x θ => congrFun hCorrectorVal (t,(x,θ)))
  have hHighTime : TimeDerivative M.T_pos.le highBase
      ((GH.vectorDerivativeField I).changeTime hTime.symm) :=
    (GH.vectorField I).changeTime_derivative
      (GH.vectorDerivativeField I) hTime.symm D.T_pos.le M.T_pos.le
      (GH.vectorField_time I)
  have hMeanTime : TimeDerivative M.T_pos.le meanBase (GM.vectorDerivativeCylinderField P) :=
    GM.vectorCylinderField_time P
  have hCorrectorTime : TimeDerivative M.T_pos.le correctorBase
      ((GH.correctorDerivativeField I).changeTime hTime.symm) :=
    (GH.curlCorrectorField I).changeTime_derivative
      (GH.correctorDerivativeField I) hTime.symm D.T_pos.le M.T_pos.le
      (GH.curlCorrectorField_time I)
  exact {
    high := hv.normalized_of_raw_eq H.high M.T_pos.le (S.high p) (S.high_pos p)
      (fun t x θ => congrFun hHighVal (t,(x,θ)))
    highDerivative := hvt.normalized_of_raw_eq H.highDerivative M.T_pos.le (S.high p) (S.high_pos p)
      (TimeDerivative.raw_eq (hT := M.T_pos) H.high_time hHighTime)
    mean := hmBounds.1.normalized_of_raw_eq H.mean M.T_pos.le (S.mean p) (S.mean_pos p)
      (fun t x θ => congrFun hMeanVal (t,(x,θ)))
    meanDerivative := hmBounds.2.1.normalized_of_raw_eq H.meanDerivative M.T_pos.le (S.mean p)
        (S.mean_pos p)
      (TimeDerivative.raw_eq (hT := M.T_pos) H.mean_time hMeanTime)
    corrector := hcv.normalized_of_raw_eq H.corrector M.T_pos.le (S.high p) (S.high_pos p)
      (fun t x θ => congrFun hCorrectorVal (t,(x,θ)))
    correctorDerivative := hct.normalized_of_raw_eq H.correctorDerivative M.T_pos.le (S.high p)
        (S.high_pos p)
      (TimeDerivative.raw_eq (hT := M.T_pos) H.corrector_time hCorrectorTime)
    pressure := hpv.normalized_of_raw_eq H.pressure M.T_pos.le (S.high p) (S.high_pos p)
      (fun t x θ => congrFun hPressureVal (t,(x,θ)))
  }


-- @@ L232-232 verbatim
end EulerPacketCylinderField.ProfileBudget


-- @@ L234-234 verbatim
end

-- @@ L235-235 verbatim
end


-- @@ L237-237 verbatim
end


-- @@ L239-239 verbatim
@[expose] public section


-- @@ L241-241 verbatim
noncomputable section


-- @@ L243-243 verbatim
namespace EulerPacketCylinderField


-- @@ L245-246 verbatim
open Set EulerSmoothLimit EulerPacketPointJets EulerPacketProfileRecursion
  EulerPacketTimeProfile EulerParameterWordGevrey EulerTransversePacketProvider


-- @@ L248-250 verbatim
variable (P : ℝ) [Fact (0 < P)] (M : EulerMeanPacketProvider.Data)
  {U : Type*} [NormedAddCommGroup U] [InnerProductSpace ℝ U] [CompleteSpace U]
  (D : Data U) (hTime : M.T = D.T) (Y : InitialData P D)


-- @@ L252-258 verbatim
/-- Forward source primary witness, given by `(homogeneousPrimaryRegularity D Y (sourceOperators
P M D (InitialData.zero P D)) rfl).changeTime hTime.symm M.T_pos.le`. -/
def forwardSourcePrimaryWitness :
    ProfileRegularity P M.T M.T_pos.le D.support
      (homogeneousPrimary D Y (sourceOperators P M D (InitialData.zero P D))) :=
  (homogeneousPrimaryRegularity D Y (sourceOperators P M D (InitialData.zero P D)) rfl).changeTime
    hTime.symm M.T_pos.le


-- @@ L260-269 verbatim
variable (L : EulerTransversePacketForward.Budget D (Fin 4) 6)
  (N : EulerTransversePacketJoin.NormalBudget D 6 L.R)
  (W : EulerTransversePacketForward.Budget.GradeGuards (P := P) L N 1)
  (LM : EulerMeanPacketProvider.Budget M 6 L.R)
  (WM : EulerMeanPacketProvider.Budget.GradeGuards LM)
  (BC : CoefficientBudget (sourceCoefficientData P M D (InitialData.zero P D) hTime))
  (hRc : sobolevCoefficientRadius (Fin 4) BC.Rc ≤ L.R) (hcost : BC.termCost ≤ L.R)
  (S : Scales (Icc (0 : ℝ) M.T)) (α : ℝ) (hα : 0 < α)
  (hgrowth : timeProfileChange S.growth hTime = α • L.g)
  (hprimaryBudget : ProfileBudget (forwardSourcePrimaryWitness P M D hTime Y) S L.R 1)


-- @@ L271-271 verbatim
include N W LM WM BC hRc hcost hα hgrowth hprimaryBudget


-- @@ L273-304 verbatim
theorem forwardSource_profile_budgets (p : ℕ) : 1 ≤ p →
    ProfileBudget (sourceProfileWitness P M D hTime (InitialData.zero P D) Y p) S L.R p := by
  induction p using Nat.strong_induction_on with
  | h p ih =>
    intro hp
    by_cases hp1 : p = 1
    · subst p
      apply hprimaryBudget.of_profile_eq M.T_pos
      simp only [sourceProfiles,profiles_one]
    have hp2 : 2 ≤ p := by omega
    let I := InitialData.zero P D
    let a := sourceProfiles P M D I Y
    let O := sourceOperators P M D I
    let C := sourceCoefficientData P M D I hTime
    let G : ∀ i, i < p → ProfileRegularity P M.T M.T_pos.le D.support (a i) :=
      fun i _ => sourceProfileWitness P M D hTime I Y i
    have hG : ∀ i (hi : i < p), 1 ≤ i → ProfileBudget (G i hi) S L.R i :=
      fun i hi hi1 => ih i hi hi1
    have he : a p = EulerPacketProfileRecursion.step O p a :=
      profiles_step O (homogeneousPrimary D Y O) p hp2
    let H := (sourceProfileWitness P M D hTime I Y p).congr he
    have hc₀ : (a 0).corrector = 0 := by simp only [a,sourceProfiles,profiles_zero]; rfl
    have hB₁ : (a 1).mean = 0 := by
      simp only [a,sourceProfiles,profiles_one,homogeneousPrimary,primaryProfile]
    have hA : ∀ i, i < p → ∀ (t : Icc (0 : ℝ) M.T) x θ,
        inner ℝ (O.normal (t,(x,θ))) ((a i).high (t,(x,θ))) = 0 :=
      fun i _ t x θ => source_high_tangent P M D hTime I Y i t x θ
    have hStep : ProfileBudget H S L.R p :=
      ProfileBudget.forwardStep M D hTime L N W LM WM C BC rfl rfl rfl hRc hcost S
        hp2 G hG hc₀ hB₁ hA (α*meanScale S.H0 p) (S.gradeFactor_pos α hα p)
        (S.high_timeProfile_eq hTime L.g α hgrowth p) H
    exact hStep.of_profile_eq M.T_pos _ he.symm


-- @@ L306-306 verbatim
end EulerPacketCylinderField
