/-
Copyright (c) 2026 Kalle Kytölä. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kalle Kytölä
-/
module

public import Mathlib.Basic.Sign.Defs
public import LeanPool.VirasoroProject.LieAlgebraModuleUEA
public import LeanPool.VirasoroProject.ToMathlib.LinearAlgebra.Basis.FinsumRepr
public import LeanPool.VirasoroProject.VermaModule
public import Mathlib.Order.CompletePartialOrder


-- @@ L14-60 verbatim
/-!
# Verma modules for Lie algebras with triangular decomposition

This file defines Verma modules used in Lie algebra representation theory.

## Main definitions

* `TriangularDecomposition`: A triangular decomposition of a Lie algebra (typically to a
  commutative Cartan subalgebra and two nilpotent subalgebras, but these requirements are not
  bundled in the definition).
* `TriangularDecomposition.ofBasis`: The triangular decomposition of a Lie algebra `𝓰` associated
  with a tri-partition of a given basis of `𝓰`.
* `TriangularDecomposition.weight`: A weight of a Lie algebra `𝓰` with triangular decomposition is
  a linear functional on the Cartan subalgebra `𝓱 ⊆ 𝓰`.
* `TriangularDecomposition.VermaHW η`: The Verma module of highest weight `η` for a Lie algebra `𝓰`
  with a triangular decomposition.
* `TriangularDecomposition.VermaHW.hwVec`: The highest weight vector of the Verma module.
* `TriangularDecomposition.VermaHW.universalMap`: The universal property of the Verma module:
  Given another module `M` over `𝓤 𝕜 𝓰` and a "target" vector `hwv ∈ M` satisfying
  `E • hwv = 0` for all `E` in the positive part of the triangular decomposition and
  `H • hwv  = η(H) • hwv` for all `H` in the Cartan subalgebra, one obtains an `A`-module map from
  the Verma module to `M` uniquely specified by the requirement `hwVec η ↦ hwv`.

## Main statements

* `TriangularDecomposition.instModule𝓤VermaHW` and `TriangularDecomposition.instModuleVermaHW`:
  A Verma module of a Lie algebra `𝓰` is a module over the universal enveloping algebra `𝓤 𝕜 𝓰` and
  a vector space over `𝕜`.
* `TriangularDecomposition.VermaHW.hwVec_cyclic`: The Verma module is generated by its highest
  weight vector.
* `TriangularDecomposition.VermaHW.cartan_smul_hwVec`: The highest weight vector of a Verma module
  is an eigenvector of the Cartan subalgebra with the eigenvalues specified by the highest weight.
* `TriangularDecomposition.VermaHW.upper_smul_hwVec`: The highest weight vector of a Verma module
  is annihilated by the positive part of the triangular decomposition.
* `VermaModule.range_universalMap_eq_span`: The map guaranteed by the universal property
  of the Verma module is surjective onto the submodule generated by the "target" vector.

## Implementation notes

Verma modules over Lie algebras are defined as a special case of generalized Verma module for
algebras (see the file `VermaModule.lean`).

## Tags

Verma module, Lie algebra, representation

-/


-- @@ L62-62 verbatim
@[expose] public section


-- @@ L64-64 verbatim
namespace VirasoroProject


-- @@ L66-66 verbatim
section


-- @@ L68-68 verbatim
open Module


-- @@ L70-70 verbatim
variable (𝕜 : Type*) [CommRing 𝕜]

-- @@ L71-71 verbatim
variable (𝓰 : Type*) [LieRing 𝓰] [LieAlgebra 𝕜 𝓰]


-- @@ L73-79 verbatim
/-- A triangular decomposition of a Lie algebra (without assumptions of commutativity
of the Cartan subalgebra or nilpotency of the other parts bundled, yet). -/
structure TriangularDecomposition where
  /-- The submodule assigned to one of the three sign parts. -/
  part : SignType → Submodule 𝕜 𝓰
  /-- The three sign parts form an internal direct sum. -/
  directSum : DirectSum.IsInternal part


-- @@ L81-81 verbatim
namespace TriangularDecomposition


-- @@ L83-124 verbatim
variable {𝕜 𝓰} in
/-- The triangular decomposition induced by a basis and a partition of the basis indices. -/
def ofBasis {ι : Type*} [Nontrivial 𝕜] [IsCancelMulZero 𝕜] [Module.IsTorsionFree 𝕜 𝓰]
    (B : Basis ι 𝕜 𝓰) (Bp : SignType → Set ι)
    (Bp_disj : Pairwise (fun ε₁ ε₂ ↦ Disjoint (Bp ε₁) (Bp ε₂)))
    (Bp_cover : ⋃ ε, Bp ε = Set.univ) :
    TriangularDecomposition 𝕜 𝓰 where
  part ε := Submodule.span 𝕜 (B '' Bp ε)
  directSum := by
    rw [DirectSum.isInternal_submodule_iff_iSupIndep_and_iSup_eq_top]
    constructor
    · exact B.iSupIndep_submodule_span_of_pairwise_disjoint _ Bp_disj
    · rw [Submodule.eq_top_iff']
      intro X
      have Xpart_mem (ε) : ∑ᶠ i ∈ Bp ε, B.repr X i • B i ∈ Submodule.span 𝕜 (B '' Bp ε) :=
        finsum_mem_mem_span (fun i ↦ B i) (B.repr X) (Bp ε)
      have X_eq :
          X = ∑ᶠ i ∈ Bp 1, B.repr X i • B i + ∑ᶠ i ∈ Bp (-1), B.repr X i • B i
              + ∑ᶠ i ∈ Bp 0, B.repr X i • B i := by
        nth_rw 1 [← B.finsum_repr_smul_basis X]
        have supp_finite_aux : (Function.support (fun i ↦ B.repr X i • B i)).Finite := by
          apply (Finsupp.hasFiniteSupport (B.repr X)).subset
          simp_all
        have supp_finite (ε : SignType) := supp_finite_aux.inter_of_right (Bp ε)
        rw [← finsum_mem_union' (Bp_disj (by simp)) (supp_finite 1) (supp_finite (-1))]
        rw [← finsum_mem_union' ?_ ?_ (supp_finite 0)]
        · have Bp_cover' : Bp 1 ∪ Bp (-1) ∪ Bp 0 = Set.univ := by
            rw [← Bp_cover]
            refine subset_antisymm ?_ (Set.iUnion_subset fun ε ↦ ?_)
            · simp_all
            · match ε with
              | 1 => apply Set.subset_union_of_subset_left (by simp)
              | 0 => simp
              | -1 => apply Set.subset_union_of_subset_left (by simp)
          simp [Bp_cover']
        · exact Disjoint.union_left (Bp_disj (by simp)) (Bp_disj (by simp))
        · exact Set.Finite.inter_of_right supp_finite_aux (Bp 1 ∪ Bp (-1))
      rw [X_eq]
      apply Submodule.add_mem _ (Submodule.add_mem _ ?_ ?_)
      · exact Submodule.mem_iSup_of_mem 0 (Xpart_mem 0)
      · exact Submodule.mem_iSup_of_mem 1 (Xpart_mem 1)
      · exact Submodule.mem_iSup_of_mem (-1) (Xpart_mem (-1))


-- @@ L126-135 verbatim
variable {𝕜 𝓰} in
/-- The parts of a triangular decomposition determined by a basis have natural bases by
construction. -/
noncomputable def _root_.VirasoroProject.TriangularDecomposition.ofBasis.basisPart {ι : Type*}
    [Nontrivial 𝕜] [IsCancelMulZero 𝕜] [Module.IsTorsionFree 𝕜 𝓰]
    (B : Basis ι 𝕜 𝓰) (Bp : SignType → Set ι)
    (Bp_disj : Pairwise (fun ε₁ ε₂ ↦ Disjoint (Bp ε₁) (Bp ε₂)))
    (Bp_cover : ⋃ ε, Bp ε = Set.univ) (ε : SignType) :
    Basis (Bp ε) 𝕜 ((ofBasis B Bp Bp_disj Bp_cover).part ε) :=
  Basis.basisSubmoduleSpan B (Bp ε)


-- @@ L137-137 verbatim
variable {𝕜 𝓰}

-- @@ L138-138 verbatim
variable (tri : TriangularDecomposition 𝕜 𝓰)


-- @@ L140-141 verbatim
/-- The Cartan subalgebra of a given triangular decomposition of a Lie algebra. -/
abbrev cartan := tri.part 0


-- @@ L143-144 verbatim
/-- The positive part of a triangular decomposition. -/
abbrev upper := tri.part 1


-- @@ L146-147 verbatim
/-- The negative part of a triangular decomposition. -/
abbrev lower := tri.part (-1)


-- @@ L149-151 verbatim
/-- Weights of a Lie algebra with triangular decomposition are functionals on the
Cartan subalgebra. -/
abbrev weight := tri.cartan →ₗ[𝕜] 𝕜


-- @@ L153-153 verbatim
variable {tri}


-- @@ L155-160 verbatim
/-- The data associated to a weight for the purpose of constructing a highest weight
representation. -/
noncomputable def weightHW (η : weight tri) (i : tri.cartan ⊕ tri.upper) :
    𝓤 𝕜 𝓰 × 𝕜 := match i with
  | Sum.inl H => ⟨ιUEA 𝕜 H, η H⟩
  | Sum.inr E => ⟨ιUEA 𝕜 E, 0⟩


-- @@ L162-164 verbatim
/-- The Verma module of highest weight η. -/
def VermaHW (η : weight tri) :=
  VermaModule (weightHW η)


-- @@ L166-166 verbatim
variable (η : weight tri)


-- @@ L168-171 verbatim
/-- The highest weight vector of the Verma module of highest weight η. -/
noncomputable def _root_.VirasoroProject.TriangularDecomposition.VermaHW.hwVec
    (η : weight tri) : VermaHW η :=
  VermaModule.hwVec _


-- @@ L173-174 verbatim
noncomputable instance (η : weight tri) : AddCommGroup (VermaHW η) :=
  instAddCommGroupVermaModule _


-- @@ L176-178 verbatim
noncomputable instance (η : weight tri) :
    Module (𝓤 𝕜 𝓰) (VermaHW η) :=
  instModuleVermaModule _


-- @@ L180-182 verbatim
noncomputable instance (η : weight tri) :
    Module 𝕜 (VermaHW η) :=
  moduleScalarOfModule 𝕜 (𝓤 𝕜 𝓰) (VermaHW η)


-- @@ L184-186 verbatim
instance (η : weight tri) :
    IsScalarTower 𝕜 (𝓤 𝕜 𝓰) (VermaHW η) :=
  isScalarTowerModuleScalarOfModule 𝕜 (𝓤 𝕜 𝓰) (VermaHW η)


-- @@ L188-191 verbatim
lemma _root_.VirasoroProject.TriangularDecomposition.VermaHW.smul_eq_algebraHom_smul
    {η : weight tri} (r : 𝕜) (v : VermaHW η) :
    r • v = (algebraMap 𝕜 (𝓤 𝕜 𝓰) r) • v :=
  rfl


-- @@ L193-197 verbatim
instance (η : weight tri) :
    SMulCommClass 𝕜 (𝓤 𝕜 𝓰) (VermaHW η) where
  smul_comm r a v := by
    simp_rw [VermaHW.smul_eq_algebraHom_smul]
    simp only [← smul_assoc, smul_eq_mul, Algebra.commutes r a]


-- @@ L199-201 verbatim
lemma _root_.VirasoroProject.TriangularDecomposition.VermaHW.hwVec_cyclic (η : weight tri) :
    Submodule.span (𝓤 𝕜 𝓰) {VermaHW.hwVec η} = ⊤ :=
  VermaModule.hwVec_cyclic _


-- @@ L203-207 verbatim
lemma _root_.VirasoroProject.TriangularDecomposition.VermaHW.upper_smul_hwVec
    (η : weight tri) {E : 𝓰} (hE : E ∈ tri.upper) :
    ιUEA 𝕜 E • VermaHW.hwVec η = 0 := by
  change (ιUEA 𝕜 E : 𝓤 𝕜 𝓰) • VermaModule.hwVec (weightHW η) = 0
  simpa [weightHW] using VermaModule.apply_hwVec_eq (weightHW η) (Sum.inr ⟨E, hE⟩)


-- @@ L209-215 verbatim
lemma _root_.VirasoroProject.TriangularDecomposition.VermaHW.cartan_smul_hwVec
    (η : weight tri) {H : 𝓰} (hH : H ∈ tri.cartan) :
    ιUEA 𝕜 H • VermaHW.hwVec η = (η ⟨H, hH⟩) • VermaHW.hwVec η := by
  change
    (ιUEA 𝕜 H : 𝓤 𝕜 𝓰) • VermaModule.hwVec (weightHW η) =
      (algebraMap 𝕜 (𝓤 𝕜 𝓰) (η ⟨H, hH⟩)) • VermaModule.hwVec (weightHW η)
  simpa [weightHW] using VermaModule.apply_hwVec_eq (weightHW η) (Sum.inl ⟨H, hH⟩)


-- @@ L217-230 verbatim
/-- The universal map from a Verma module to any module with a vector of the given
highest weight. -/
noncomputable def _root_.VirasoroProject.TriangularDecomposition.VermaHW.universalMap
    (η : weight tri)
    (M : Type*) [AddCommGroup M] [Module (𝓤 𝕜 𝓰) M] {hwv : M}
    (hwv_cartan : ∀ {H} (hH : H ∈ tri.cartan),
      ιUEA 𝕜 H • hwv = (algebraMap 𝕜 (𝓤 𝕜 𝓰) (η ⟨H, hH⟩) • hwv))
    (hwv_upper : ∀ {E} (_ : E ∈ tri.upper), ιUEA 𝕜 E • hwv = 0) :
    VermaHW η →ₗ[𝓤 𝕜 𝓰] M :=
  VermaModule.universalMap (weightHW η) (hwv := hwv) <| by
    intro i
    match i with
    | Sum.inl H => simpa [weightHW] using hwv_cartan (Submodule.coe_mem H)
    | Sum.inr E => simpa [weightHW] using hwv_upper (Submodule.coe_mem E)


-- @@ L232-238 verbatim
lemma _root_.VirasoroProject.TriangularDecomposition.VermaHW.universalMap_hwVec (η : weight tri)
    (M : Type*) [AddCommGroup M] [Module (𝓤 𝕜 𝓰) M] {hwv : M}
    (hwv_cartan : ∀ {H} (hH : H ∈ tri.cartan),
      ιUEA 𝕜 H • hwv = (algebraMap 𝕜 (𝓤 𝕜 𝓰) (η ⟨H, hH⟩) • hwv))
    (hwv_upper : ∀ {E} (_ : E ∈ tri.upper), ιUEA 𝕜 E • hwv = 0) :
    VermaHW.universalMap η M hwv_cartan hwv_upper (VermaHW.hwVec η) = hwv :=
  VermaModule.universalMap_hwVec ..


-- @@ L240-240 verbatim
end TriangularDecomposition




-- @@ L244-244 verbatim
section HasCentralValue


-- @@ L246-246 verbatim
variable (M : Type*) [AddCommGroup M] [Module 𝕜 M] [Module (𝓤 𝕜 𝓰) M]


-- @@ L248-251 verbatim
/-- A type class for recording that a (central) element acts as a particular scalar on a
representation. -/
class HasCentralValue (C : 𝓰) (c : 𝕜) where
  central_smul' : ∀ (v : M), ιUEA 𝕜 C • v = c • v


-- @@ L253-256 verbatim
lemma _root_.VirasoroProject.HasCentralValue.central_smul
    {C : 𝓰} {c : 𝕜} [HasCentralValue 𝕜 𝓰 M C c] (v : M) :
    ιUEA 𝕜 C • v = c • v :=
  HasCentralValue.central_smul' v


-- @@ L258-258 verbatim
end HasCentralValue


-- @@ L260-260 verbatim
end




-- @@ L264-264 verbatim
end VirasoroProject
