/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.ModelTheory.AElementary
public import Mathlib.ModelTheory.Substructures
import LeanPool.InfinitaryLogic.ModelTheory.HanfSpectrum.CardinalBounds


-- @@ L12-36 verbatim
/-!
# Genuine downward Löwenheim–Skolem for fragments (issue #13 unit 5)

Per the frozen audit (`docs/fragments-audit.md` §5–§6): from an arbitrary `M` and `X ⊆ M`,
construct an A-elementary substructure containing `X` with the HONEST cardinal bound

  `|N| ≤ max(ℵ₀, |X|, |A|, |Σ n, L.Functions n|)`.

The construction is the semantic witness hull (Marker, Exercise 1.23, presented with choice
functions instead of a language expansion): interleave `Substructure.closure` (all language
functions — this is where `|Σ Functions|` honestly enters) with chosen witnesses for failures
of the fragment-controlled universals (`tvWitnessSet` — `|A|`-many witness suppliers), iterate
ω times, and close once more. The union is closed under both, so the Tarski–Vaught criterion
(`aElementary_of_tarskiVaught`) applies. Witnesses are extracted from existence proofs
(`Exists.choose`), so no `Nonempty M` hypothesis and no dummy elements are needed.

Marker's textbook bound `max(|A|,|X|)` (Theorem 1.22) is the special case
`|Σ Functions| ≤ max ℵ₀ |A|`; the countable corollary, which is what the consumers use, is
`exists_countable_aElementary_substructure`.

The language's two universes and the carrier's are independent. The three cardinals being
compared therefore start in three different universes, so every bound is stated with an explicit
`Cardinal.lift` into `max u v w`. `exists_aElementary_substructure_of_eq_univ` is the
same-universe form, where those lifts are identities.
-/


-- @@ L38-38 verbatim
@[expose] public section


-- @@ L40-40 verbatim
namespace FirstOrder


-- @@ L42-42 verbatim
namespace Language


-- @@ L44-44 verbatim
open Cardinal


-- @@ L46-46 verbatim
universe u v w


-- @@ L48-48 verbatim
variable {L : Language.{u, v}} {M : Type w} [L.Structure M] (A : Fragment L)


-- @@ L50-50 verbatim
/-! ## The witness sets and the hull -/


-- @@ L52-57 verbatim
/-- The chosen witnesses over a base set `Y`: for each fragment-controlled universal and each
tuple from `Y` admitting a counterexample in `M`, THE chosen counterexample. -/
private def tvWitnessSet (Y : Set M) : Set M :=
  {m | ∃ (n : ℕ) (φ : L.BoundedFormulaω Empty (n + 1)) (a : Fin n → M),
    ((⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet ∧ ∀ i, a i ∈ Y) ∧
    ∃ h : ∃ m' : M, ¬φ.Realize Empty.elim (Fin.snoc a m'), m = h.choose}


-- @@ L59-64 verbatim
/-- The Löwenheim–Skolem stages: alternately close under all language functions and add the
fragment witnesses. -/
private def lsStage (X : Set M) : ℕ → Set M
  | 0 => X
  | k + 1 => (Substructure.closure L (lsStage X k) : Set M)
      ∪ tvWitnessSet A ((Substructure.closure L (lsStage X k) : Set M))


-- @@ L66-67 verbatim
private theorem lsStage_mono (X : Set M) : ∀ k, lsStage A X k ⊆ lsStage A X (k + 1) := fun _ =>
  le_trans (Substructure.subset_closure (L := L)) Set.subset_union_left


-- @@ L69-70 verbatim
private theorem lsStage_mono_le (X : Set M) : Monotone (lsStage A X) :=
  monotone_nat_of_le_succ (lsStage_mono A X)


-- @@ L72-74 verbatim
/-- **The witness hull**: the substructure generated by all stages. -/
private def lsHull (X : Set M) : L.Substructure M :=
  Substructure.closure L (⋃ k, lsStage A X k)


-- @@ L76-77 verbatim
private theorem subset_lsHull (X : Set M) : X ⊆ (lsHull A X : Set M) :=
  le_trans (Set.subset_iUnion (lsStage A X) 0) (Substructure.subset_closure (L := L))


-- @@ L79-103 verbatim
/-- The hull's carrier is the union of the stage closures — directedness makes the last
closure redundant. -/
private theorem coe_lsHull (X : Set M) :
    (lsHull A X : Set M) = ⋃ k, (Substructure.closure L (lsStage A X k) : Set M) := by
  apply Set.Subset.antisymm
  · intro x hx
    rw [lsHull] at hx
    have hsub : (⋃ k, lsStage A X k)
        ⊆ ⋃ k, (Substructure.closure L (lsStage A X k) : Set M) :=
      Set.iUnion_mono fun k => Substructure.subset_closure (L := L)
    -- the union of the closures is itself (the carrier of) a substructure, by directedness
    have hdir : Directed (· ≤ ·) fun k => Substructure.closure L (lsStage A X k) := by
      intro i j
      exact ⟨max i j, Substructure.closure_mono (lsStage_mono_le A X (le_max_left i j)),
        Substructure.closure_mono (lsStage_mono_le A X (le_max_right i j))⟩
    have hmem := (Substructure.closure_le
      (S := ⨆ k, Substructure.closure L (lsStage A X k))).mpr
      (le_trans hsub (by
        intro y hy
        obtain ⟨k, hk⟩ := Set.mem_iUnion.mp hy
        exact (Substructure.mem_iSup_of_directed hdir).mpr ⟨k, hk⟩)) hx
    obtain ⟨k, hk⟩ := (Substructure.mem_iSup_of_directed hdir).mp hmem
    exact Set.mem_iUnion.mpr ⟨k, hk⟩
  · refine Set.iUnion_subset fun k => ?_
    exact Substructure.closure_mono (Set.subset_iUnion (lsStage A X) k)


-- @@ L105-117 verbatim
/-- Finitely many hull elements lie in a common stage closure. -/
private theorem exists_stage_of_tuple {X : Set M} {n : ℕ} (a : Fin n → lsHull A X) :
    ∃ K, ∀ i, (a i : M) ∈ (Substructure.closure L (lsStage A X K) : Set M) := by
  have hmem : ∀ i, ∃ k, (a i : M) ∈ (Substructure.closure L (lsStage A X k) : Set M) := by
    intro i
    have h := (a i).2
    have h2 : (a i : M) ∈ (lsHull A X : Set M) := h
    rw [coe_lsHull A X] at h2
    exact Set.mem_iUnion.mp h2
  choose ks hks using hmem
  refine ⟨Finset.univ.sup ks, fun i => ?_⟩
  exact Substructure.closure_mono
    (lsStage_mono_le A X (Finset.le_sup (Finset.mem_univ i))) (hks i)


-- @@ L119-131 verbatim
/-- **The hull is A-elementary** — the Tarski–Vaught criterion holds by construction. -/
private theorem aElementary_lsHull (X : Set M) :
    AElementary A ((lsHull A X).subtype) := by
  refine aElementary_of_tarskiVaught _ ?_
  intro n φ hφ a hex
  obtain ⟨K, hK⟩ := exists_stage_of_tuple A a
  have hwmem : hex.choose ∈ (lsHull A X : Set M) := by
    have h1 : hex.choose ∈ tvWitnessSet A
        ((Substructure.closure L (lsStage A X K) : Set M)) :=
      ⟨n, φ, _, ⟨hφ, hK⟩, hex, rfl⟩
    have h2 : hex.choose ∈ lsStage A X (K + 1) := Set.mem_union_right _ h1
    exact Substructure.subset_closure (L := L) (Set.mem_iUnion.mpr ⟨K + 1, h2⟩)
  exact ⟨⟨hex.choose, hwmem⟩, hex.choose_spec⟩


-- @@ L133-133 verbatim
/-! ## The cardinal bound -/


-- @@ L135-138 verbatim
/-- The per-arity witness suppliers: fragment-controlled bodies paired with tuples from `Y`. -/
private def tvSlice (Y : Set M) (n : ℕ) : Type (max u v w) :=
  {q : L.BoundedFormulaω Empty (n + 1) × (Fin n → M) //
    (⟨n, q.1.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet ∧ ∀ i, q.2 i ∈ Y}


-- @@ L140-143 verbatim
open Classical in
/-- The choice map from a slice: the chosen counterexample, when one exists. -/
private noncomputable def tvSliceWitness (Y : Set M) (n : ℕ) : tvSlice A Y n → Option M := fun q =>
  if h : ∃ m' : M, ¬q.1.1.Realize Empty.elim (Fin.snoc q.1.2 m') then some h.choose else none


-- @@ L145-150 verbatim
private theorem tvWitnessSet_subset_iUnion (Y : Set M) :
    tvWitnessSet A Y ⊆ ⋃ n : ℕ, Option.some ⁻¹' Set.range (tvSliceWitness A Y n) := by
  rintro m ⟨n, φ, a, ⟨hφ, ha⟩, hex, rfl⟩
  refine Set.mem_iUnion.mpr ⟨n, ⟨⟨(φ, a), hφ, ha⟩, ?_⟩⟩
  show tvSliceWitness A Y n ⟨(φ, a), hφ, ha⟩ = some hex.choose
  exact dite_eq_left hex


-- @@ L152-155 verbatim
/-! Mathlib's heterogeneous-universe lemmas produce the *complementary* lift level: for a set
in `M` they give `lift.{max u v}`, and for language-side data `lift.{w}`. Both land in
`Cardinal.{max u v w}`, but Lean keeps the level expressions distinct, so every bound below is
stated with the uniform `lift.{max u v w}` and converted once through these. -/


-- @@ L157-157 verbatim
section


-- @@ L159-159 verbatim
universe x y


-- @@ L161-167 verbatim
/-- Absorb a `max` into the lift level: `lift.{max y x} #α` and `lift.{y} #α` are the same map
on `Cardinal.{x}`, but Lean does not identify the level expressions. Both directions of the
mismatch below are this one lemma — set-of-`M` data lifted by `max u v`, and language data
lifted by `w`. -/
private theorem lift_mk_umax {α : Type x} :
    Cardinal.lift.{max y x} (Cardinal.mk α) = Cardinal.lift.{y} (Cardinal.mk α) :=
  congrFun Cardinal.lift_umax _


-- @@ L169-169 verbatim
end


-- @@ L171-226 verbatim
omit [L.Structure M] in
private theorem mk_tvSlice_le (Y : Set M) (n : ℕ) :
    Cardinal.mk (tvSlice A Y n)
      ≤ max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk Y)))
          (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet)) := by
  set κ := max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk Y)))
    (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet)) with hκ
  have hκinf : Cardinal.aleph0 ≤ κ := le_trans (le_max_left _ _) (le_max_left _ _)
  -- `mk_prod` produces the complementary lift levels; these are the same maps, since
  -- `max (max u v) w` and `max w (max u v)` are the same universe.
  have hAlift : Cardinal.lift.{max u v w} (Cardinal.mk A.toSet)
      = Cardinal.lift.{w} (Cardinal.mk A.toSet) := lift_mk_umax
  have hYlift : Cardinal.lift.{max u v w} (Cardinal.mk Y)
      = Cardinal.lift.{max u v} (Cardinal.mk Y) := lift_mk_umax
  have hinj : Function.Injective (fun q : tvSlice A Y n =>
      ((⟨q.1.1, q.2.1⟩, fun i => ⟨q.1.2 i, q.2.2 i⟩) :
        {φ : L.BoundedFormulaω Empty (n + 1) //
          (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} × (Fin n → Y))) := by
    intro q r h
    have h1 : q.1.1 = r.1.1 := congrArg (fun p => (p.1 : L.BoundedFormulaω Empty (n + 1))) h
    have h2 : q.1.2 = r.1.2 := funext fun i =>
      congrArg (fun p => (p.2 i : M)) h
    exact Subtype.ext (Prod.ext h1 h2)
  have hφle : Cardinal.mk {φ : L.BoundedFormulaω Empty (n + 1) //
      (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} ≤ Cardinal.mk A.toSet := by
    refine Cardinal.mk_le_of_injective (f := fun φ => (⟨⟨n, φ.1.all⟩, φ.2⟩ : A.toSet)) ?_
    intro φ ψ h
    have h1 : (⟨n, φ.1.all⟩ : Σ n, L.BoundedFormulaω Empty n) = ⟨n, ψ.1.all⟩ :=
      congrArg Subtype.val h
    have h2 : φ.1.all = ψ.1.all := eq_of_heq (Sigma.mk.injEq .. ▸ h1).2
    exact Subtype.ext (by injection h2)
  have hYle : Cardinal.mk (Fin n → Y) ≤ max Cardinal.aleph0 (Cardinal.mk Y) := by
    have hpow : Cardinal.mk (Fin n → Y) = Cardinal.mk Y ^ (n : Cardinal) := by
      rw [Cardinal.mk_arrow, Cardinal.mk_fin, Cardinal.lift_natCast, Cardinal.lift_uzero]
    rw [hpow]
    calc Cardinal.mk Y ^ (n : Cardinal)
        ≤ (max Cardinal.aleph0 (Cardinal.mk Y)) ^ (n : Cardinal) :=
          Cardinal.power_le_power_right (le_max_right _ _)
      _ ≤ max Cardinal.aleph0 (Cardinal.mk Y) :=
          Cardinal.pow_le (le_max_left _ _) Cardinal.natCast_lt_aleph0
  calc Cardinal.mk (tvSlice A Y n)
      ≤ Cardinal.mk ({φ : L.BoundedFormulaω Empty (n + 1) //
          (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet} × (Fin n → Y)) :=
        Cardinal.mk_le_of_injective hinj
    _ = Cardinal.lift.{w} (Cardinal.mk {φ : L.BoundedFormulaω Empty (n + 1) //
          (⟨n, φ.all⟩ : Σ n, L.BoundedFormulaω Empty n) ∈ A.toSet})
            * Cardinal.lift.{max u v} (Cardinal.mk (Fin n → Y)) := Cardinal.mk_prod _ _
    _ ≤ κ * κ := by
        refine mul_le_mul' ?_ ?_
        · refine le_trans (Cardinal.lift_le.mpr hφle) ?_
          rw [← hAlift]
          exact le_max_right _ _
        · refine le_trans (Cardinal.lift_le.mpr hYle) ?_
          rw [Cardinal.lift_max, Cardinal.lift_aleph0, ← hYlift]
          exact le_max_left _ _
    _ = κ := Cardinal.mul_eq_self hκinf


-- @@ L228-244 verbatim
private theorem mk_tvWitnessSet_le (Y : Set M) :
    Cardinal.lift.{max u v w} (Cardinal.mk (tvWitnessSet A Y))
      ≤ max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk Y)))
          (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet)) := by
  rw [lift_mk_umax.{w, max u v}]
  refine le_trans (Cardinal.lift_le.mpr
    (Cardinal.mk_le_mk_of_subset (tvWitnessSet_subset_iUnion A Y))) ?_
  refine FirstOrder.HanfLadder.lift_mk_iUnion_le_of_countable (ι := ℕ)
    (le_trans (le_max_left _ _) (le_max_left _ _)) fun n => ?_
  refine le_trans (Cardinal.lift_le.mpr
    (Cardinal.mk_preimage_of_injective _ _ (Option.some_injective _))) ?_
  refine le_trans ?_ (mk_tvSlice_le A Y n)
  calc Cardinal.lift.{max u v} (Cardinal.mk (Set.range (tvSliceWitness A Y n)))
      = Cardinal.lift.{max u v w} (Cardinal.mk (Set.range (tvSliceWitness A Y n))) :=
        lift_mk_umax.{w, max u v}.symm
    _ ≤ Cardinal.mk (tvSlice A Y n) :=
        (Cardinal.mk_range_le_lift (f := tvSliceWitness A Y n)).trans_eq (Cardinal.lift_id' _)


-- @@ L246-260 verbatim
/-- The substructure-closure bound is lifted into the common universe `max u v w`. Mathlib's
own statement lives in `Cardinal.{max u w}`, so it needs one further lift, and the
function-symbol summand arrives with the complementary level. -/
private theorem lift_mk_closure_le (S : Set M) {κ : Cardinal.{max u v w}} (hκ : Cardinal.aleph0 ≤ κ)
    (hS : Cardinal.lift.{max u v w} (Cardinal.mk S) ≤ κ)
    (hF : Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)) ≤ κ) :
    Cardinal.lift.{max u v w} (Cardinal.mk (Substructure.closure L S : Set M)) ≤ κ := by
  have h := Cardinal.lift_le.{v}.mpr (Substructure.lift_card_closure_le (L := L) (s := S))
  rw [Cardinal.lift_lift, Cardinal.lift_max, Cardinal.lift_aleph0, Cardinal.lift_add,
    Cardinal.lift_lift, Cardinal.lift_lift] at h
  rw [lift_mk_umax.{w, max u v}]
  refine le_trans h (max_le hκ ?_)
  refine le_trans (add_le_add ?_ ?_) (le_of_eq (Cardinal.add_eq_self hκ))
  · rwa [← lift_mk_umax.{w, max u v}]
  · rwa [← lift_mk_umax.{u, max v w}]


-- @@ L262-288 verbatim
/-- The honest per-stage bound. -/
private theorem mk_lsStage_le (X : Set M) (k : ℕ) :
    Cardinal.lift.{max u v w} (Cardinal.mk (lsStage A X k))
      ≤ max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk X)))
          (max (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet))
            (Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)))) := by
  set κ := max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk X)))
    (max (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet))
      (Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)))) with hκ
  have hκinf : Cardinal.aleph0 ≤ κ := le_trans (le_max_left _ _) (le_max_left _ _)
  have hF : Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)) ≤ κ :=
    le_trans (le_max_right _ _) (le_max_right _ _)
  induction k with
  | zero => exact le_trans (le_max_right _ _) (le_max_left _ _)
  | succ k ih =>
    have hclk := lift_mk_closure_le (L := L) (lsStage A X k) hκinf ih hF
    refine le_trans (Cardinal.lift_le.mpr (Cardinal.mk_union_le _ _)) ?_
    have hW : Cardinal.lift.{max u v w} (Cardinal.mk (tvWitnessSet A
        ((Substructure.closure L (lsStage A X k) : Set M)))) ≤ κ := by
      refine le_trans (mk_tvWitnessSet_le A _) (max_le (max_le hκinf hclk) ?_)
      exact le_trans (le_max_left _ _) (le_max_right _ _)
    rw [Cardinal.lift_add]
    calc Cardinal.lift.{max u v w} (Cardinal.mk (Substructure.closure L (lsStage A X k) : Set M))
          + Cardinal.lift.{max u v w}
            (Cardinal.mk (tvWitnessSet A ((Substructure.closure L (lsStage A X k) : Set M))))
        ≤ κ + κ := add_le_add hclk hW
      _ = κ := Cardinal.add_eq_self hκinf


-- @@ L290-304 verbatim
/-- **The honest hull bound**: `|N| ≤ max(ℵ₀, |X|, |A|, |Σ Functions|)`. -/
private theorem mk_lsHull_le (X : Set M) :
    Cardinal.lift.{max u v w} (Cardinal.mk (lsHull A X))
      ≤ max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk X)))
          (max (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet))
            (Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)))) := by
  set κ := max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk X)))
    (max (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet))
      (Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)))) with hκ
  have hκinf : Cardinal.aleph0 ≤ κ := le_trans (le_max_left _ _) (le_max_left _ _)
  have hF : Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)) ≤ κ :=
    le_trans (le_max_right _ _) (le_max_right _ _)
  have hunion : Cardinal.lift.{max u v w} (Cardinal.mk (⋃ k, lsStage A X k)) ≤ κ :=
    FirstOrder.HanfLadder.lift_mk_iUnion_le_of_countable (ι := ℕ) hκinf (mk_lsStage_le A X)
  exact lift_mk_closure_le (L := L) _ hκinf hunion hF


-- @@ L306-315 verbatim
/-- **Genuine downward Löwenheim–Skolem for fragments** (issue #13 unit 5): every `X ⊆ M` is
contained in an A-elementary substructure of size at most `max(ℵ₀, |X|, |A|, |Σ Functions|)` —
the honest bound; only function symbols enlarge the hull beyond the fragment's witnesses. -/
private theorem exists_aElementary_substructure (A : Fragment L) (X : Set M) :
    ∃ N : L.Substructure M, X ⊆ (N : Set M) ∧ AElementary A N.subtype ∧
      Cardinal.lift.{max u v w} (Cardinal.mk N)
        ≤ max (max Cardinal.aleph0 (Cardinal.lift.{max u v w} (Cardinal.mk X)))
            (max (Cardinal.lift.{max u v w} (Cardinal.mk A.toSet))
              (Cardinal.lift.{max u v w} (Cardinal.mk (Σ n, L.Functions n)))) :=
  ⟨lsHull A X, subset_lsHull A X, aElementary_lsHull A X, mk_lsHull_le A X⟩


-- @@ L317-325 verbatim
/-- The same-universe form, for a language and a structure that already share one universe: the
lifts are then all identities, so this is the statement without the universe bookkeeping. -/
private theorem exists_aElementary_substructure_of_eq_univ {L : Language.{u, u}} {M : Type u}
    [L.Structure M] (A : Fragment L) (X : Set M) :
    ∃ N : L.Substructure M, X ⊆ (N : Set M) ∧ AElementary A N.subtype ∧
      Cardinal.mk N ≤ max (max Cardinal.aleph0 (Cardinal.mk X))
        (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L.Functions n))) := by
  obtain ⟨N, hXN, hAe, hcard⟩ := exists_aElementary_substructure A X
  exact ⟨N, hXN, hAe, by simpa using hcard⟩


-- @@ L327-342 verbatim
/-- **The countable corollary** (Marker, Theorem 1.22 second half — what #17 consumes):
countable data yields a countable A-elementary substructure. -/
theorem exists_countable_aElementary_substructure (A : Fragment L) {X : Set M}
    (hX : X.Countable) (hA : A.toSet.Countable)
    [hF : Countable (Σ n, L.Functions n)] :
    ∃ N : L.Substructure M, X ⊆ (N : Set M) ∧ AElementary A N.subtype ∧ Countable N := by
  obtain ⟨N, hXN, hAe, hcard⟩ := exists_aElementary_substructure A X
  refine ⟨N, hXN, hAe, ?_⟩
  rw [← Cardinal.mk_le_aleph0_iff]
  refine Cardinal.lift_le_aleph0.{w, max u v w}.mp
    (le_trans hcard (max_le (max_le le_rfl ?_) (max_le ?_ ?_)))
  · have := hX.to_subtype
    exact Cardinal.lift_le_aleph0.mpr Cardinal.mk_le_aleph0
  · have := hA.to_subtype
    exact Cardinal.lift_le_aleph0.mpr Cardinal.mk_le_aleph0
  · exact Cardinal.lift_le_aleph0.mpr Cardinal.mk_le_aleph0


-- @@ L344-350 verbatim
/-! ## Universe regression

These instantiate the hull construction and its cardinal bound where the language's two universes
and the structure's universe are pairwise distinct, and at the same-universe specialization.
They are compiled, so they fail if the file is ever reconstrained;
the `variable` block alone would not catch that, since a `Language.{u, v}` binder can still be
silently pinned by a downstream lemma. -/


-- @@ L352-358 verbatim
example {L' : Language.{1, 2}} {M' : Type 3} [L'.Structure M'] (A : Fragment L') (X : Set M') :
    ∃ N : L'.Substructure M', X ⊆ (N : Set M') ∧ AElementary A N.subtype ∧
      Cardinal.lift.{3} (Cardinal.mk N)
        ≤ max (max Cardinal.aleph0 (Cardinal.lift.{3} (Cardinal.mk X)))
            (max (Cardinal.lift.{3} (Cardinal.mk A.toSet))
              (Cardinal.lift.{3} (Cardinal.mk (Σ n, L'.Functions n)))) :=
  exists_aElementary_substructure A X


-- @@ L360-364 verbatim
example {L' : Language.{0, 0}} {M' : Type} [L'.Structure M'] (A : Fragment L') (X : Set M') :
    ∃ N : L'.Substructure M', X ⊆ (N : Set M') ∧ AElementary A N.subtype ∧
      Cardinal.mk N ≤ max (max Cardinal.aleph0 (Cardinal.mk X))
        (max (Cardinal.mk A.toSet) (Cardinal.mk (Σ n, L'.Functions n))) :=
  exists_aElementary_substructure_of_eq_univ A X


-- @@ L366-366 verbatim
end Language


-- @@ L368-368 verbatim
end FirstOrder
