/-
Copyright (c) 2026 Hyeon Seung-Hyeon. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hyeon Seung-Hyeon
-/

-- Adapted for Lean Pool from 0stellensatz/MassFormula at 7fa41a621f724f110183904d3fd19c6730a932ad.
module

public import LeanPool.MassFormula.HaarScaling
public import LeanPool.MassFormula.RootLifting
import LeanPool.MassFormula.Discriminant
import Mathlib.NumberTheory.ArithmeticFunction.Misc
import Mathlib.RingTheory.DedekindDomain.IntegralClosure
import Mathlib.RingTheory.Henselian
import Mathlib.RingTheory.Localization.NormTrace
import Mathlib.RingTheory.Valuation.Integral
import Mathlib.Topology.UniformSpace.Uniformizable


-- @@ L20-72 verbatim
/-!
# Auxiliary file: the uniformizer parametrization

The algebraic layer of the §3 change of variables (equations (5)–(13)), stated in the *coordinates*
of the monogenic basis of `integers L` ([Serre 1978, §3, pp.1032–1033][Serre1978]). `L` carries no
topology in this project (see the header of `RootLifting.lean`), so the paper's map from the
uniformizers of `L` to the Eisenstein coefficients cannot be integrated over directly: the source of
the parametrization is the coefficient space `Fin n → K` of the power basis of an Eisenstein
generator (monogenicity and Newton lifting), and both source and target are the same measured space.
This file supplies the dictionary between the two pictures; the measure-theoretic assembly lives in
`First.lean`, on top of the scaling law of `HaarScaling.lean`.

The file has four layers:

- **Orthogonality of a power basis.** In `integers L`, generated over `𝒪[K]` by an Eisenstein
  generator `ξ`, the terms of a combination of the `c i * ξ ^ i` for `i < n` have *pairwise
  distinct* valuations—the `i`-th term has valuation `n * v (c i) + i`, and the exponents are
  distinct modulo `n` because `i < n`. So no cancellation is possible and the valuation of the sum
  is the minimum of the terms' (`le_addVal_sum_iff`). A ball of `integers L` is therefore a *box* in
  coordinates, and at a radius that is a multiple of `n` it is the *cube* of radius `π ^ ρ`
  (`le_addVal_mul_iff`)—which is what keeps the volume bookkeeping of eq. (13) free of ceilings.
  Orthogonality also gives the power basis at *every* uniformizer, not just at the Eisenstein
  generator (`powersBasis`): the transition matrix between two such bases is triangular with unit
  diagonal modulo `𝓂[K]`, so its determinant is a unit.
- **The matrix of a multiplication.** A ball of `integers L` of *arbitrary* radius is the ideal
  generated by a suitable `z`, and in coordinates that ideal is the image lattice of the matrix of
  multiplication by `z` (`toCoeff_equivFun_mem_imageLattice_iff`), whose determinant is the norm of
  `z` (`det_leftMulMatrix`). So `measure_integerBox_eq_pow_mul` gives its volume as `1 / q` to the
  order of that norm—and it is this, not a Jacobian, that carries the factor `1 / q ^ d L` of
  equations (11)–(13).
- **The order of the norm of the derivative.** That order, for `z` the derivative of `g` at `ξ`, is
  `d L` (`associated_norm_derivative`): that norm is the discriminant of the power basis up to sign,
  hence *generates* `discIdeal` (`discIdeal_eq_span`), whose multiplicity at `𝓂[K]` is `d L` by
  definition. This is Serre's Lemma 2 and equation (11) with no conjugates, no Vandermonde, and no
  square roots. Since for a totally ramified extension the norm computes the valuation
  (`addVal_norm`), the same `d L` is also the valuation of that derivative in `integers L`
  (`addVal_derivative_eq_d`)—which is the exponent the fiber count below is stated with.
- **The local fiber count.** The cube around `ξ` of radius `π ^ ρ` contains *exactly one* root of a
  monic `F` of degree `n` precisely when the valuation of `F` at `ξ` is at least `n * ρ + δ`
  (`existsUnique_isRoot_iff`)—Newton (`exists_isRoot`) in one direction, the factorization of `F` at
  `ξ` as `(ξ - y) * h ξ` in the other. So the image of a cube under the minimal-polynomial map is
  the *exact* level set of the valuation of `f` at `ξ`, an affine condition on the coefficients of
  `f` and hence a lattice translate, which is what replaces Lemmas 1 and 3 of the paper.

Everything except the specializations is stated for an abstract pair of discrete valuation rings in
which `π` is associated to `ξ ^ n`, since nothing about local fields, integral closures, or
Eisenstein polynomials enters it.

## References

* [Serre1978] J-P. Serre, *Une «formule de masse» pour les extensions totalement ramifiées de
  degré donné d'un corps local*, C. R. Acad. Sci. Paris **286** (1978), Série A, 1031–1036.
-/


-- @@ L74-74 verbatim
@[expose] public section


-- @@ L76-76 verbatim
open ValuativeRel IsDiscreteValuationRing MeasureTheory

-- @@ L77-77 verbatim
open scoped ENNReal


-- @@ L79-79 verbatim
namespace MassFormula


-- @@ L81-87 verbatim
/-! ## Orthogonality of a power basis over a discrete valuation ring

`R` and `A` are discrete valuation rings, `A` an `R`-algebra in which the uniformizer `π` of `R` is
an associate of `ξ ^ n` for a uniformizer `ξ` of `A`—the interleaving equating `(ξ) ^ n` with `π`
times `integers L` that a totally ramified extension of degree `n` produces
(`span_integralGen_pow_eq`).
-/


-- @@ L89-93 verbatim
/-- Associated elements of a discrete valuation ring have equal additive valuation. -/
theorem addVal_eq_of_associated {A : Type*} [CommRing A] [IsDomain A]
    [IsDiscreteValuationRing A] {a b : A} (h : Associated a b) :
    addVal A a = addVal A b :=
  le_antisymm (addVal_le_iff_dvd.mpr h.dvd) (addVal_le_iff_dvd.mpr h.symm.dvd)


-- @@ L95-95 verbatim
section Orthogonality


-- @@ L97-99 verbatim
variable {R A : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] [Algebra R A]
  {π : R} {ξ : A} {n : ℕ}


-- @@ L101-110 verbatim
/-- A sum one of whose terms has strictly the smallest valuation has that valuation: the ultrametric
inequality is an equality when there is nothing to cancel against. -/
private lemma addVal_sum_eq_of_isMin {ι : Type*} {s : Finset ι} {f : ι → A}
    {i₀ : ι} (hi₀ : i₀ ∈ s) (hfin : addVal A (f i₀) ≠ ⊤)
    (hlt : ∀ j ∈ s, j ≠ i₀ → addVal A (f i₀) < addVal A (f j)) :
    addVal A (∑ j ∈ s, f j) = addVal A (f i₀) := by
  classical
  rw [← Finset.add_sum_erase _ _ hi₀]
  exact (addVal A).map_add_eq_of_lt_left ((addVal A).map_lt_sum hfin fun j hj =>
    hlt j (Finset.mem_of_mem_erase hj) (Finset.ne_of_mem_erase hj))


-- @@ L112-118 verbatim
/-- The exponents `n * a + i` with `i < n` determine `i`: they are pairwise distinct modulo `n`.
This is the whole reason the power basis is orthogonal. -/
private lemma fin_eq_of_mul_add_eq {a b : ℕ} {i j : Fin n}
    (h : n * a + (i : ℕ) = n * b + (j : ℕ)) : i = j := by
  have h1 : (i : ℕ) % n = (j : ℕ) % n := by
    rw [← Nat.mul_add_mod n a (i : ℕ), ← Nat.mul_add_mod n b (j : ℕ), h]
  rwa [Nat.mod_eq_of_lt i.isLt, Nat.mod_eq_of_lt j.isLt, Fin.val_inj] at h1


-- @@ L120-130 verbatim
/-- At a radius that is a multiple of `n`, the coordinatewise condition collapses: the offset
`i < n` cannot bridge a gap of `n`. -/
private lemma mul_le_mul_add_iff {ρ a i : ℕ} (hi : i < n) :
    n * ρ ≤ n * a + i ↔ ρ ≤ a := by
  refine ⟨fun h => ?_, fun h => (Nat.mul_le_mul_left n h).trans (Nat.le_add_right _ _)⟩
  by_contra hlt
  rw [not_le] at hlt
  have h1 : n * a + i < n * (a + 1) := by
    rw [Nat.mul_succ]
    exact Nat.add_lt_add_left hi _
  exact absurd h (not_le.mpr (h1.trans_le (Nat.mul_le_mul_left n hlt)))


-- @@ L132-143 verbatim
/-- Through the interleaving associating `π` with `ξ ^ n`, the valuation of an element of `R` is
multiplied by `n` upstairs—the totally ramified normalization of the valuation on `R`. -/
theorem addVal_algebraMap (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (z : R) :
    addVal A (algebraMap R A z) = (n : ℕ∞) * addVal R z := by
  have hn0 : (n : ℕ∞) ≠ 0 := by exact_mod_cast hn.ne'
  by_cases hz : z = 0
  · rw [hz, map_zero, addVal_zero, addVal_zero, ENat.mul_top hn0]
  · obtain ⟨m, u, hu⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hz hπ
    rw [hu, map_mul, map_pow, addVal_mul, addVal_eq_zero_iff.mpr (u.isUnit.map (algebraMap R A)),
      zero_add, addVal_pow, addVal_eq_of_associated hass, hξ.addVal_pow, addVal_def' u hπ m,
      nsmul_eq_mul, mul_comm]


-- @@ L145-149 verbatim
/-- The valuation of one term of a power-basis combination. -/
theorem addVal_term (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (z : R) (i : ℕ) :
    addVal A (algebraMap R A z * ξ ^ i) = (n : ℕ∞) * addVal R z + i := by
  rw [addVal_mul, addVal_algebraMap hπ hξ hn hass, hξ.addVal_pow]


-- @@ L151-190 verbatim
/-- Orthogonality of a power basis: a combination of the `c i * ξ ^ i` for `i < n` has valuation at
least `m` exactly when each of its terms does. One direction is the ultrametric inequality; the
other is the absence of cancellation, the terms having pairwise distinct valuations
`n * v (c i) + i` by `fin_eq_of_mul_add_eq`, so that the smallest one survives in the sum. -/
theorem le_addVal_sum_iff (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (c : Fin n → R) (m : ℕ∞) :
    m ≤ addVal A (∑ i : Fin n, algebraMap R A (c i) * ξ ^ (i : ℕ)) ↔
      ∀ i : Fin n, m ≤ (n : ℕ∞) * addVal R (c i) + (i : ℕ) := by
  classical
  have hn0 : (n : ℕ∞) ≠ 0 := by exact_mod_cast hn.ne'
  refine ⟨fun hle i => ?_, fun h => (addVal A).map_le_sum fun i _ => ?_⟩
  · by_contra hlt
    rw [not_le] at hlt
    -- the least of the term valuations, and its uniqueness
    obtain ⟨i₀, -, hi₀⟩ := Finset.exists_min_image Finset.univ
      (fun j : Fin n => (n : ℕ∞) * addVal R (c j) + (j : ℕ)) ⟨i, Finset.mem_univ i⟩
    have hlt₀ : (n : ℕ∞) * addVal R (c i₀) + (i₀ : ℕ) < m :=
      lt_of_le_of_lt (hi₀ i (Finset.mem_univ i)) hlt
    have hcfin : ∀ j : Fin n, (n : ℕ∞) * addVal R (c j) + (j : ℕ) ≠ ⊤ →
        addVal R (c j) ≠ ⊤ := by
      intro j hj hv
      rw [hv, ENat.mul_top hn0, top_add] at hj
      exact hj rfl
    have hinj : ∀ j : Fin n, (n : ℕ∞) * addVal R (c j) + (j : ℕ) =
        (n : ℕ∞) * addVal R (c i₀) + (i₀ : ℕ) → j = i₀ := by
      intro j hj
      obtain ⟨a, ha⟩ := ENat.ne_top_iff_exists.mp (hcfin j (by rw [hj]; exact hlt₀.ne_top))
      obtain ⟨b, hb⟩ := ENat.ne_top_iff_exists.mp (hcfin i₀ hlt₀.ne_top)
      rw [← ha, ← hb] at hj
      exact fin_eq_of_mul_add_eq (a := a) (b := b) (by exact_mod_cast hj)
    -- the sum has the least term's valuation, which is below `m`
    have hsum := addVal_sum_eq_of_isMin (f := fun j : Fin n => algebraMap R A (c j) * ξ ^ (j : ℕ))
      (Finset.mem_univ i₀) (by rw [addVal_term hπ hξ hn hass]; exact hlt₀.ne_top)
      (fun j _ hne => by
        rw [addVal_term hπ hξ hn hass, addVal_term hπ hξ hn hass]
        exact lt_of_le_of_ne (hi₀ j (Finset.mem_univ j)) fun heq => hne (hinj j heq.symm))
    rw [hsum, addVal_term hπ hξ hn hass] at hle
    exact absurd hle (not_le.mpr hlt₀)
  · rw [addVal_term hπ hξ hn hass]
    exact h i


-- @@ L192-201 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
/-- Every element is the combination of the powers of `ξ` given by its coordinates in a power
basis. -/
theorem sum_repr (b : Module.Basis (Fin n) R A) (hb : ∀ i, b i = ξ ^ (i : ℕ)) (y : A) :
    ∑ i : Fin n, algebraMap R A (b.repr y i) * ξ ^ (i : ℕ) = y := by
  have h1 : ∀ i : Fin n, algebraMap R A (b.repr y i) * ξ ^ (i : ℕ) = b.repr y i • b i := by
    intro i
    rw [Algebra.smul_def, hb i]
  rw [Finset.sum_congr rfl fun i (_ : i ∈ Finset.univ) => h1 i]
  exact b.sum_repr y


-- @@ L203-211 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
/-- Conversely, the coordinates of a combination of the powers are its coefficients. -/
theorem equivFun_sum (b : Module.Basis (Fin n) R A) (hb : ∀ i, b i = ξ ^ (i : ℕ))
    (c : Fin n → R) :
    b.equivFun (∑ i : Fin n, algebraMap R A (c i) * ξ ^ (i : ℕ)) = c := by
  have h1 : b.equivFun.symm c = ∑ i : Fin n, algebraMap R A (c i) * ξ ^ (i : ℕ) := by
    rw [Module.Basis.equivFun_symm_apply]
    exact Finset.sum_congr rfl fun i _ => by rw [Algebra.smul_def, hb i]
  rw [← h1, LinearEquiv.apply_symm_apply]


-- @@ L213-218 verbatim
/-! ### The matrix of a multiplication

The image of the ideal `z A` in coordinates is the lattice of the matrix of multiplication by `z`,
whose determinant is the norm of `z`—the pair of facts that lets the scaling law of
`HaarScaling.lean` compute the volume of a ball of `integers L`.
-/


-- @@ L220-236 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
/-- The lattice of a multiplication matrix: the coordinate vector of `y` lies in the range of the
matrix of multiplication by `z` exactly when `z` divides `y`, the matrix acting on coordinates as
the multiplication does on elements. -/
theorem mem_range_leftMulMatrix_iff (b : Module.Basis (Fin n) R A) (z y : A) :
    b.equivFun y ∈ LinearMap.range (Matrix.mulVecLin (Algebra.leftMulMatrix b z)) ↔ z ∣ y := by
  have hkey : ∀ w : A, Matrix.mulVecLin (Algebra.leftMulMatrix b z) (b.equivFun w)
      = b.equivFun (z * w) := by
    intro w
    rw [Matrix.mulVecLin_apply]
    exact Algebra.leftMulMatrix_mulVec_repr b z w
  refine ⟨fun ⟨c, hc⟩ => ⟨b.equivFun.symm c, b.equivFun.injective ?_⟩,
    fun ⟨w, hw⟩ => ⟨b.equivFun w, by rw [hkey w, hw]⟩⟩
  have h2 := hkey (b.equivFun.symm c)
  rw [LinearEquiv.apply_symm_apply] at h2
  rw [← h2]
  exact hc.symm


-- @@ L238-243 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
/-- The determinant of the matrix of a multiplication is the norm—the classical definition of the
norm, read backwards. -/
theorem det_leftMulMatrix (b : Module.Basis (Fin n) R A) (z : A) :
    (Algebra.leftMulMatrix b z).det = Algebra.norm R z :=
  (Algebra.norm_eq_matrix_det b z).symm


-- @@ L245-252 verbatim
/-- A ball of `A` is a box in power-basis coordinates: the orthogonality relation, read on the
coordinates of an element rather than on a given combination. -/
theorem le_addVal_iff (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) (y : A) (m : ℕ∞) :
    m ≤ addVal A y ↔ ∀ i : Fin n, m ≤ (n : ℕ∞) * addVal R (b.repr y i) + (i : ℕ) := by
  have h1 := le_addVal_sum_iff hπ hξ hn hass (fun i => b.repr y i) m
  rwa [sum_repr b hb y] at h1


-- @@ L254-273 verbatim
/-- A ball of radius a multiple of `n` is a cube: an element lies in `π ^ ρ * A` exactly when every
one of its power-basis coordinates lies in `π ^ ρ * R`—the offset `i < n` of the `i`-th coordinate
cannot bridge a gap of `n`, so the `n` coordinatewise conditions all read `ρ ≤ v (c i)`. This is the
form the volume computation of equation (13) uses: on such radii no ceiling ever appears. -/
theorem le_addVal_mul_iff (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) (ρ : ℕ) (y : A) :
    ((n * ρ : ℕ) : ℕ∞) ≤ addVal A y ↔ ∀ i : Fin n, (ρ : ℕ∞) ≤ addVal R (b.repr y i) := by
  have hn0 : (n : ℕ∞) ≠ 0 := by exact_mod_cast hn.ne'
  rw [le_addVal_iff hπ hξ hn hass b hb]
  refine forall_congr' fun i => ?_
  set v := addVal R (b.repr y i) with hvdef
  clear_value v
  rcases eq_or_ne v ⊤ with hv | hv
  · rw [hv, ENat.mul_top hn0, top_add]
    simp
  · lift v to ℕ using hv with a
    rw [show (n : ℕ∞) * (a : ℕ∞) + ((i : ℕ) : ℕ∞) = ((n * a + (i : ℕ) : ℕ) : ℕ∞) from by
      push_cast; ring, Nat.cast_le, Nat.cast_le]
    exact mul_le_mul_add_iff i.isLt


-- @@ L275-284 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
/-- The value at `ξ` of the base change of a polynomial of degree `< n`, as a combination of the
powers—the shape the orthogonality relation consumes. -/
lemma eval_map_eq_sum {P : Polynomial R} (hdeg : P.natDegree < n) :
    Polynomial.eval ξ (P.map (algebraMap R A)) =
      ∑ i : Fin n, algebraMap R A (P.coeff i) * ξ ^ (i : ℕ) := by
  rw [Polynomial.eval_eq_sum_range'
      (lt_of_le_of_lt (Polynomial.natDegree_map_le) hdeg) ξ,
    ← Fin.sum_univ_eq_sum_range fun k => (P.map (algebraMap R A)).coeff k * ξ ^ k]
  exact Finset.sum_congr rfl fun i _ => by rw [Polynomial.coeff_map]


-- @@ L286-295 verbatim
/-! ### The power basis at an arbitrary uniformizer

The cubes decomposing the set of uniformizers in the change of variables are centered at arbitrary
uniformizers of `integers L`, and each carries its own affine chart—the coordinates of the powers of
*its* center. So the power basis is needed not only at the Eisenstein generator of
`integers_eq_adjoin` but at every uniformizer. Orthogonality supplies it: since `η ^ j` has
valuation exactly `j`, the `j`-th coordinate of `η ^ j` in the basis of the powers of `ξ` is a unit
while the earlier ones lie in the maximal ideal of `R`, so the transition matrix is triangular with
unit diagonal modulo that ideal and its determinant is a unit.
-/


-- @@ L297-300 verbatim
/-- The coordinates, in a power basis, of the powers of another uniformizer. -/
noncomputable def transition (b : Module.Basis (Fin n) R A) (η : A) :
    Matrix (Fin n) (Fin n) R :=
  Matrix.of fun i j => b.repr (η ^ (j : ℕ)) i


-- @@ L302-351 verbatim
/-- The transition matrix is triangular with unit diagonal modulo the maximal ideal of `R`: the
valuation `j` of `η ^ j` is carried by the `j`-th coordinate alone, the exponents `n * v (c i) + i`
being distinct modulo `n`. -/
private lemma transition_entries (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) {η : A} (hη : Irreducible η) (j : Fin n) :
    (∀ i : Fin n, i < j → transition b η i j ∈ IsLocalRing.maximalIdeal R) ∧
      IsUnit (transition b η j j) := by
  have hpow : addVal A (η ^ (j : ℕ)) = ((j : ℕ) : ℕ∞) := hη.addVal_pow _
  have hge : ∀ i : Fin n, ((j : ℕ) : ℕ∞) ≤
      (n : ℕ∞) * addVal R (b.repr (η ^ (j : ℕ)) i) + (i : ℕ) :=
    (le_addVal_iff hπ hξ hn hass b hb _ _).mp (le_of_eq hpow.symm)
  have hentry : ∀ i : Fin n, transition b η i j = b.repr (η ^ (j : ℕ)) i := fun i => rfl
  refine ⟨fun i hij => ?_, ?_⟩
  · -- an earlier coordinate cannot be a unit, since `n · 0 + i = i < j`
    rw [IsLocalRing.mem_maximalIdeal, mem_nonunits_iff, hentry, ← addVal_eq_zero_iff]
    intro h0
    have h1 := hge i
    rw [h0, mul_zero, zero_add, Nat.cast_le] at h1
    omega
  · -- the `j`-th coordinate is a unit, else every exponent would exceed `j`
    rw [hentry, ← addVal_eq_zero_iff]
    by_contra h0
    have hnot : ¬ ((((j : ℕ) + 1 : ℕ)) : ℕ∞) ≤ addVal A (η ^ (j : ℕ)) := by
      rw [hpow, Nat.cast_le]
      omega
    refine hnot ((le_addVal_iff hπ hξ hn hass b hb _ _).mpr fun i => ?_)
    rcases eq_or_ne i j with rfl | hij
    · -- at the `j`-th coordinate the valuation is at least `1`, so the exponent is at least `n + j`
      refine le_trans ?_ (add_le_add
        (mul_le_mul_right (Order.one_le_iff_ne_zero.mpr h0) (n : ℕ∞))
        (le_refl (((i : ℕ)) : ℕ∞)))
      rw [mul_one, ← Nat.cast_add, Nat.cast_le]
      omega
    · -- elsewhere the exponent differs from `j` modulo `n`, so it strictly exceeds `j`
      have h2 := hge i
      rcases eq_or_ne (addVal R (b.repr (η ^ (j : ℕ)) i)) ⊤ with hv | hv
      · rw [hv, ENat.mul_top (by exact_mod_cast hn.ne'), top_add]
        exact le_top
      · lift addVal R (b.repr (η ^ (j : ℕ)) i) to ℕ using hv with c
        have hcast : (n : ℕ∞) * (c : ℕ∞) = ((n * c : ℕ) : ℕ∞) := by push_cast; ring
        have hne : (j : ℕ) ≠ n * c + (i : ℕ) := by
          intro heq
          refine hij (fin_eq_of_mul_add_eq (a := c) (b := 0) ?_)
          rw [Nat.mul_zero, Nat.zero_add]
          exact heq.symm
        have hle : (j : ℕ) ≤ n * c + (i : ℕ) := by
          rwa [hcast, ← Nat.cast_add, Nat.cast_le] at h2
        rw [hcast, ← Nat.cast_add, Nat.cast_le]
        exact Nat.succ_le_of_lt (lt_of_le_of_ne hle hne)


-- @@ L353-377 verbatim
/-- The transition matrix has unit determinant: modulo the maximal ideal of `R` it is triangular
with unit diagonal, so its determinant is nonzero in the residue field, hence a unit in the local
ring `R`. -/
lemma isUnit_det_transition (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) {η : A} (hη : Irreducible η) :
    IsUnit (transition b η).det := by
  classical
  have htri : ((transition b η).map (IsLocalRing.residue R)).BlockTriangular
      OrderDual.toDual := by
    intro i j hij
    rw [Matrix.map_apply]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr ((transition_entries hπ hξ hn hass b hb hη j).1 i
      (OrderDual.toDual_lt_toDual.mp hij))
  have hne : ((transition b η).map (IsLocalRing.residue R)).det ≠ 0 := by
    rw [Matrix.det_of_isLowerTriangular _ htri]
    refine Finset.prod_ne_zero_iff.mpr fun i _ => ?_
    rw [Matrix.map_apply]
    exact ((transition_entries hπ hξ hn hass b hb hη i).2.map (IsLocalRing.residue R)).ne_zero
  have hdetmap : IsLocalRing.residue R ((transition b η).det) =
      ((transition b η).map (IsLocalRing.residue R)).det := by
    rw [RingHom.map_det, RingHom.mapMatrix_apply]
  by_contra hu
  exact hne (hdetmap.symm.trans (Ideal.Quotient.eq_zero_iff_mem.mpr
    ((IsLocalRing.mem_maximalIdeal _).mpr (mem_nonunits_iff.mpr hu))))


-- @@ L379-387 verbatim
/-- The power basis at an arbitrary uniformizer: once the powers of one uniformizer form an
`R`-basis of `A`, so do the powers of every uniformizer, the transition matrix between the two
families having unit determinant. -/
noncomputable def powersBasis (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) {η : A} (hη : Irreducible η) :
    Module.Basis (Fin n) R A :=
  b.map (Matrix.toLinearEquiv b (transition b η)
    (isUnit_det_transition hπ hξ hn hass b hb hη))


-- @@ L389-397 verbatim
lemma powersBasis_apply (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) {η : A} (hη : Irreducible η) (i : Fin n) :
    powersBasis hπ hξ hn hass b hb hη i = η ^ (i : ℕ) := by
  have h1 : Matrix.toLin b b (transition b η) (b i) = η ^ (i : ℕ) := by
    rw [Matrix.toLin_self]
    exact b.sum_repr _
  rw [powersBasis, Module.Basis.map_apply]
  exact h1


-- @@ L399-399 verbatim
end Orthogonality


-- @@ L401-413 verbatim
/-! ## The order of the derivative is an invariant of `A`

The exponent `δ` of the fiber count below is the valuation of the derivative of `G` at `ξ`, for `G`
the monic degree-`n` annihilator of a uniformizer `ξ`. The change of variables sums over cubes
centered at *different* uniformizers, so it needs `δ` to be the same for all of them—classically,
`δ` is the valuation of the different, an invariant of `integers L` over `𝒪[K]`. The proof here is
elementary and stays inside `A`: writing `η = P ξ` and `ξ = Q η` with `P` and `Q` over `R` (possible
since the powers of either uniformizer form a basis), the chain rule turns each of the identities
presenting `G` at `η` composed with `P`, and `G` at `ξ` composed with `Q`, as multiples of the other
annihilator, into a divisibility between the two derivatives, while the divisibility of
`Q.comp P - X` by `G` at `ξ` makes the product of the two expansion derivatives congruent to `1`—so
both are units and the two divisibilities are equalities.
-/


-- @@ L415-415 verbatim
section Different


-- @@ L417-419 verbatim
variable {R A : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] [Algebra R A]
  {π : R} {ξ : A} {n : ℕ}


-- @@ L421-423 verbatim
/-- The polynomial expanding `y` in a power basis. -/
noncomputable def expand (b : Module.Basis (Fin n) R A) (y : A) : Polynomial R :=
  ∑ i : Fin n, Polynomial.C (b.repr y i) * Polynomial.X ^ (i : ℕ)


-- @@ L425-432 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
lemma eval_map_expand (b : Module.Basis (Fin n) R A) (hb : ∀ i, b i = ξ ^ (i : ℕ)) (y : A) :
    Polynomial.eval ξ ((expand b y).map (algebraMap R A)) = y := by
  rw [expand, Polynomial.map_sum]
  simp only [Polynomial.map_mul, Polynomial.map_C, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.eval_finsetSum, Polynomial.eval_mul, Polynomial.eval_C, Polynomial.eval_pow,
    Polynomial.eval_X]
  exact sum_repr b hb y


-- @@ L434-442 verbatim
omit [IsDomain A] [IsDiscreteValuationRing A] in
/-- The expansion has degree below `n`. -/
private lemma degree_expand_lt (b : Module.Basis (Fin n) R A) (y : A) :
    (expand b y).degree < (Polynomial.X ^ n : Polynomial R).degree := by
  rw [Polynomial.degree_X_pow]
  refine lt_of_le_of_lt (Polynomial.degree_sum_le _ _) ?_
  rw [Finset.sup_lt_iff (by exact_mod_cast WithBot.bot_lt_coe n)]
  intro i _
  exact lt_of_le_of_lt (Polynomial.degree_C_mul_X_pow_le _ _) (by exact_mod_cast i.isLt)


-- @@ L444-447 verbatim
/-- The monic degree-`n` annihilator of `y` read off a power basis at `y`: `y ^ n` minus its
expansion in the lower powers. -/
noncomputable def annih (b : Module.Basis (Fin n) R A) (y : A) : Polynomial R :=
  Polynomial.X ^ n - expand b (y ^ n)


-- @@ L449-453 verbatim
omit [IsDomain A] [IsDiscreteValuationRing A] in
lemma annih_monic (b : Module.Basis (Fin n) R A) (y : A) : (annih b y).Monic := by
  rw [annih, sub_eq_add_neg]
  exact (Polynomial.monic_X_pow n).add_of_left
    (by rw [Polynomial.degree_neg]; exact degree_expand_lt b (y ^ n))


-- @@ L455-463 verbatim
omit [IsDomain A] [IsDiscreteValuationRing A] in
lemma annih_natDegree (b : Module.Basis (Fin n) R A) (y : A) :
    (annih b y).natDegree = n := by
  have h := Polynomial.degree_add_eq_left_of_degree_lt
    (p := (Polynomial.X ^ n : Polynomial R)) (q := -expand b (y ^ n))
    (by rw [Polynomial.degree_neg]; exact degree_expand_lt b (y ^ n))
  rw [Polynomial.degree_X_pow] at h
  rw [annih, sub_eq_add_neg]
  exact Polynomial.natDegree_eq_of_degree_eq_some h


-- @@ L465-469 verbatim
omit [IsDomain R] [IsDiscreteValuationRing R] [IsDomain A] [IsDiscreteValuationRing A] in
lemma eval_map_annih (b : Module.Basis (Fin n) R A) (hb : ∀ i, b i = ξ ^ (i : ℕ)) :
    Polynomial.eval ξ ((annih b ξ).map (algebraMap R A)) = 0 := by
  rw [annih, Polynomial.map_sub, Polynomial.eval_sub, Polynomial.map_pow, Polynomial.map_X,
    Polynomial.eval_pow, Polynomial.eval_X, eval_map_expand b hb, sub_self]


-- @@ L471-508 verbatim
omit [IsDomain A] [IsDiscreteValuationRing A] in
/-- A monic annihilator of a power-basis generator divides every polynomial vanishing there: the
remainder has degree below `n` and vanishes at `ξ`, so all of its coefficients vanish. -/
private lemma dvd_of_eval_map_eq_zero (hn : 0 < n) (b : Module.Basis (Fin n) R A)
    (hb : ∀ i, b i = ξ ^ (i : ℕ)) {G : Polynomial R} (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0) {P : Polynomial R}
    (hP : Polynomial.eval ξ (P.map (algebraMap R A)) = 0) : G ∣ P := by
  classical
  rw [← Polynomial.modByMonic_eq_zero_iff_dvd hGm]
  set S := P %ₘ G with hS
  -- the remainder vanishes at `ξ`
  have hdec := Polynomial.modByMonic_add_div P G
  have hSroot : Polynomial.eval ξ (S.map (algebraMap R A)) = 0 := by
    have h1 := congrArg (fun p : Polynomial R =>
      Polynomial.eval ξ (p.map (algebraMap R A))) hdec
    simp only [Polynomial.map_add, Polynomial.map_mul, Polynomial.eval_add,
      Polynomial.eval_mul, hGroot, zero_mul, add_zero] at h1
    rw [h1, hP]
  -- its degree is below `n`, so orthogonality kills every coefficient
  have hSdeg : S.natDegree < n := by
    by_cases h0 : S = 0
    · rw [h0, Polynomial.natDegree_zero]
      omega
    · rw [← hGdeg]
      exact Polynomial.natDegree_lt_natDegree h0
        (by rw [hS]; exact Polynomial.degree_modByMonic_lt P hGm)
  have hcoeff : ∀ i : Fin n, S.coeff i = 0 := by
    have h2 : b.equivFun (∑ i : Fin n, algebraMap R A (S.coeff (i : ℕ)) * ξ ^ (i : ℕ)) =
        (fun i : Fin n => S.coeff (i : ℕ)) :=
      equivFun_sum b hb (fun i : Fin n => S.coeff (i : ℕ))
    rw [← eval_map_eq_sum hSdeg, hSroot, map_zero] at h2
    intro i
    exact (congrFun h2 i).symm
  refine Polynomial.ext fun i => ?_
  rw [Polynomial.coeff_zero]
  rcases Nat.lt_or_ge i n with hi | hi
  · exact hcoeff ⟨i, hi⟩
  · exact Polynomial.coeff_eq_zero_of_natDegree_lt (lt_of_lt_of_le hSdeg hi)


-- @@ L510-510 verbatim
variable {ξ₁ ξ₂ : A}


-- @@ L512-551 verbatim
/-- One half of the invariance: writing `ξ₂ = P ξ₁`, the identity presenting `G₂.comp P` as
`G₁ * W` differentiates to an identity between the derivative of `P` at `ξ₁` times that of `G₂` at
`ξ₂` and the derivative of `G₁` at `ξ₁` times `W` at `ξ₁`, so once the first is a unit the order of
the derivative of `G₁` at `ξ₁` is at most that of `G₂` at `ξ₂`. -/
private lemma le_addVal_eval_derivative (hn : 0 < n) (b₁ : Module.Basis (Fin n) R A)
    (hb₁ : ∀ i, b₁ i = ξ₁ ^ (i : ℕ)) {G₁ G₂ : Polynomial R}
    (hG₁m : G₁.Monic) (hG₁deg : G₁.natDegree = n)
    (hG₁root : Polynomial.eval ξ₁ (G₁.map (algebraMap R A)) = 0)
    (hG₂root : Polynomial.eval ξ₂ (G₂.map (algebraMap R A)) = 0)
    (hunit : IsUnit (Polynomial.eval ξ₁
      (Polynomial.derivative ((expand b₁ ξ₂).map (algebraMap R A))))) :
    addVal A (Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A)))) ≤
      addVal A (Polynomial.eval ξ₂ (Polynomial.derivative (G₂.map (algebraMap R A)))) := by
  set P := expand b₁ ξ₂ with hP
  have hPval : Polynomial.eval ξ₁ (P.map (algebraMap R A)) = ξ₂ := eval_map_expand b₁ hb₁ ξ₂
  -- `G₂ ∘ P` vanishes at `ξ₁`, hence is divisible by `G₁`
  have hcomp : Polynomial.eval ξ₁ ((G₂.comp P).map (algebraMap R A)) = 0 := by
    rw [Polynomial.map_comp, Polynomial.eval_comp, hPval, hG₂root]
  obtain ⟨W, hW⟩ := dvd_of_eval_map_eq_zero hn b₁ hb₁ hG₁m hG₁deg hG₁root hcomp
  -- differentiate and evaluate at `ξ₁`
  have hkey : Polynomial.eval ξ₁ (Polynomial.derivative (P.map (algebraMap R A))) *
      Polynomial.eval ξ₂ (Polynomial.derivative (G₂.map (algebraMap R A))) =
      Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A))) *
        Polynomial.eval ξ₁ (W.map (algebraMap R A)) := by
    have h1 := congrArg (fun p : Polynomial R =>
      Polynomial.eval ξ₁ ((Polynomial.derivative p).map (algebraMap R A))) hW
    simp only [Polynomial.derivative_comp, Polynomial.derivative_mul, Polynomial.map_add,
      Polynomial.map_mul, Polynomial.map_comp, Polynomial.eval_add, Polynomial.eval_mul,
      Polynomial.eval_comp, hPval, hG₁root, zero_mul, add_zero] at h1
    simpa only [Polynomial.derivative_map] using h1
  -- read the orders off
  have h2 : addVal A (Polynomial.eval ξ₂
      (Polynomial.derivative (G₂.map (algebraMap R A)))) =
      addVal A (Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A)))) +
        addVal A (Polynomial.eval ξ₁ (W.map (algebraMap R A))) := by
    have h3 := congrArg (addVal A) hkey
    rw [addVal_mul, addVal_mul, addVal_eq_zero_iff.mpr hunit, zero_add] at h3
    exact h3
  rw [h2]
  exact le_self_add


-- @@ L553-601 verbatim
/-- The two expansion derivatives are units: `Q.comp P - X` is divisible by `G₁`, so the product of
the derivative of `P` at `ξ₁` and that of `Q` at `ξ₂` is congruent to `1` modulo the derivative of
`G₁` at `ξ₁`, which has positive order. -/
private lemma isUnit_eval_derivative_expand (hn : 0 < n) (b₁ b₂ : Module.Basis (Fin n) R A)
    (hb₁ : ∀ i, b₁ i = ξ₁ ^ (i : ℕ)) (hb₂ : ∀ i, b₂ i = ξ₂ ^ (i : ℕ)) {G₁ : Polynomial R}
    (hG₁m : G₁.Monic) (hG₁deg : G₁.natDegree = n)
    (hG₁root : Polynomial.eval ξ₁ (G₁.map (algebraMap R A)) = 0)
    (hδ : 1 ≤ addVal A (Polynomial.eval ξ₁
      (Polynomial.derivative (G₁.map (algebraMap R A))))) :
    IsUnit (Polynomial.eval ξ₁
        (Polynomial.derivative ((expand b₁ ξ₂).map (algebraMap R A)))) ∧
      IsUnit (Polynomial.eval ξ₂
        (Polynomial.derivative ((expand b₂ ξ₁).map (algebraMap R A)))) := by
  set P := expand b₁ ξ₂ with hP
  set Q := expand b₂ ξ₁ with hQ
  have hPval : Polynomial.eval ξ₁ (P.map (algebraMap R A)) = ξ₂ := eval_map_expand b₁ hb₁ ξ₂
  have hQval : Polynomial.eval ξ₂ (Q.map (algebraMap R A)) = ξ₁ := eval_map_expand b₂ hb₂ ξ₁
  -- `Q ∘ P - X` vanishes at `ξ₁`
  have hcomp : Polynomial.eval ξ₁ ((Q.comp P - Polynomial.X).map (algebraMap R A)) = 0 := by
    rw [Polynomial.map_sub, Polynomial.eval_sub, Polynomial.map_comp, Polynomial.eval_comp,
      hPval, hQval, Polynomial.map_X, Polynomial.eval_X, sub_self]
  obtain ⟨S, hS⟩ := dvd_of_eval_map_eq_zero hn b₁ hb₁ hG₁m hG₁deg hG₁root hcomp
  -- differentiate: the product of the two derivatives is `1` plus something deep
  have hkey : Polynomial.eval ξ₁ (Polynomial.derivative (P.map (algebraMap R A))) *
      Polynomial.eval ξ₂ (Polynomial.derivative (Q.map (algebraMap R A))) =
      1 + Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A))) *
        Polynomial.eval ξ₁ (S.map (algebraMap R A)) := by
    have h1 := congrArg (fun p : Polynomial R =>
      Polynomial.eval ξ₁ ((Polynomial.derivative p).map (algebraMap R A))) hS
    simp only [Polynomial.derivative_sub, Polynomial.derivative_X, Polynomial.derivative_comp,
      Polynomial.derivative_mul, Polynomial.map_add, Polynomial.map_sub, Polynomial.map_mul,
      Polynomial.map_one, Polynomial.map_comp, Polynomial.eval_add, Polynomial.eval_sub,
      Polynomial.eval_mul, Polynomial.eval_one, Polynomial.eval_comp, hPval, hG₁root,
      zero_mul, add_zero] at h1
    have h2 : Polynomial.eval ξ₁ (Polynomial.derivative (P.map (algebraMap R A))) *
        Polynomial.eval ξ₂ (Polynomial.derivative (Q.map (algebraMap R A))) - 1 =
        Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A))) *
          Polynomial.eval ξ₁ (S.map (algebraMap R A)) := by
      simpa only [Polynomial.derivative_map] using h1
    linear_combination h2
  have hlt : addVal A (1 : A) < addVal A
      (Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A))) *
        Polynomial.eval ξ₁ (S.map (algebraMap R A))) := by
    rw [addVal_one, addVal_mul]
    exact lt_of_lt_of_le zero_lt_one (hδ.trans le_self_add)
  have hprod : IsUnit (Polynomial.eval ξ₁ (Polynomial.derivative (P.map (algebraMap R A))) *
      Polynomial.eval ξ₂ (Polynomial.derivative (Q.map (algebraMap R A)))) := by
    rw [← addVal_eq_zero_iff, hkey, (addVal A).map_add_eq_of_lt_left hlt, addVal_one]
  exact ⟨isUnit_of_mul_isUnit_left hprod, isUnit_of_mul_isUnit_right hprod⟩


-- @@ L603-620 verbatim
/-- The order of the derivative of a monic annihilator is an invariant of `A`, not of the
uniformizer used to present it—classically, the valuation of the different. This is what lets the
change of variables use one exponent for all of its cubes. -/
theorem addVal_eval_derivative_eq_of_powersBasis (hn : 0 < n)
    (b₁ b₂ : Module.Basis (Fin n) R A)
    (hb₁ : ∀ i, b₁ i = ξ₁ ^ (i : ℕ)) (hb₂ : ∀ i, b₂ i = ξ₂ ^ (i : ℕ)) {G₁ G₂ : Polynomial R}
    (hG₁m : G₁.Monic) (hG₁deg : G₁.natDegree = n)
    (hG₁root : Polynomial.eval ξ₁ (G₁.map (algebraMap R A)) = 0)
    (hG₂m : G₂.Monic) (hG₂deg : G₂.natDegree = n)
    (hG₂root : Polynomial.eval ξ₂ (G₂.map (algebraMap R A)) = 0)
    (hδ : 1 ≤ addVal A (Polynomial.eval ξ₁
      (Polynomial.derivative (G₁.map (algebraMap R A))))) :
    addVal A (Polynomial.eval ξ₂ (Polynomial.derivative (G₂.map (algebraMap R A)))) =
      addVal A (Polynomial.eval ξ₁ (Polynomial.derivative (G₁.map (algebraMap R A)))) := by
  obtain ⟨hu₁, hu₂⟩ :=
    isUnit_eval_derivative_expand hn b₁ b₂ hb₁ hb₂ hG₁m hG₁deg hG₁root hδ
  refine le_antisymm ?_ (le_addVal_eval_derivative hn b₁ hb₁ hG₁m hG₁deg hG₁root hG₂root hu₁)
  exact le_addVal_eval_derivative hn b₂ hb₂ hG₂m hG₂deg hG₂root hG₁root hu₂


-- @@ L622-622 verbatim
end Different


-- @@ L624-639 verbatim
/-! ## The local fiber count of the minimal-polynomial map

The analytic heart of the change of variables, still over an abstract pair of discrete valuation
rings. For a uniformizer `ξ` of `A` annihilated by a monic `G` of degree `n` over `R`, and `δ` the
valuation of the derivative of `G` at `ξ`, the cube around `ξ` of radius `π ^ ρ` contains *exactly
one* root of a monic `F` of degree `n` when the valuation of `F` at `ξ` is at least `n * ρ + δ`, and
none otherwise.

The paper gets this from the étaleness of the parametrization (Lemma 1) and the change-of-variables
formula (Lemma 3). Here one direction is Newton's method (`exists_isRoot`) and the other the
factorization of `F` at `ξ` as `(ξ - y) * h ξ` at a root `y`, with the orthogonality above
converting "the value at `ξ` is small" into "the coefficients are close" (`coeff_mem_span_pow`).
That conversion is what makes the image of the cube the *exact* level set of the valuation of `f` at
`ξ`—an affine condition on the coefficients of `f`, hence a lattice—rather than a linear image up to
higher order.
-/


-- @@ L641-641 verbatim
section Fibers


-- @@ L643-645 verbatim
variable {R A : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
  [CommRing A] [IsDomain A] [IsDiscreteValuationRing A] [Algebra R A]
  {π : R} {ξ : A} {n : ℕ} {F G : Polynomial R} {δ ρ : ℕ}


-- @@ L647-650 verbatim
/-- Membership in a power of the maximal ideal, read on the valuation. -/
private lemma mem_span_pow_iff_le_addVal (hξ : Irreducible ξ) (T : ℕ) (z : A) :
    z ∈ Ideal.span {ξ ^ T} ↔ (T : ℕ∞) ≤ addVal A z := by
  rw [Ideal.mem_span_singleton, ← addVal_le_iff_dvd, hξ.addVal_pow]


-- @@ L652-680 verbatim
/-- Orthogonality, read on a polynomial: if a polynomial of degree `< n` over `R` takes at `ξ` a
value of valuation at least `m` with `n ≤ m`, then all of its coefficients lie in the ideal
generated by `ξ ^ (m - n + 1)`—the value pins each coefficient to within `n` of `m`, and the worst
offset is `n - 1`. -/
private lemma coeff_mem_span_pow (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) {P : Polynomial R} (hdeg : P.natDegree < n)
    {m : ℕ} (hmn : n ≤ m)
    (hval : (m : ℕ∞) ≤ addVal A (Polynomial.eval ξ (P.map (algebraMap R A)))) (i : ℕ) :
    (P.map (algebraMap R A)).coeff i ∈ Ideal.span {ξ ^ (m - n + 1)} := by
  rw [Polynomial.coeff_map, mem_span_pow_iff_le_addVal hξ]
  rcases Nat.lt_or_ge i n with hi | hi
  · have h1 : (m : ℕ∞) ≤ (n : ℕ∞) * addVal R (P.coeff i) + (i : ℕ∞) := by
      rw [eval_map_eq_sum hdeg] at hval
      exact (le_addVal_sum_iff hπ hξ hn hass (fun j : Fin n => P.coeff j) (m : ℕ∞)).mp hval
        ⟨i, hi⟩
    rw [addVal_algebraMap hπ hξ hn hass]
    set v := addVal R (P.coeff i) with hvdef
    clear_value v
    rcases eq_or_ne v ⊤ with hv | hv
    · rw [hv, ENat.mul_top (by exact_mod_cast hn.ne')]
      exact le_top
    · lift v to ℕ using hv with b
      rw [show (n : ℕ∞) * (b : ℕ∞) = ((n * b : ℕ) : ℕ∞) from by push_cast; ring] at h1 ⊢
      rw [← Nat.cast_add, Nat.cast_le] at h1
      rw [Nat.cast_le]
      have key : ∀ c : ℕ, m ≤ c + i → m - n + 1 ≤ c := by intro c hc; omega
      exact key _ h1
  · rw [Polynomial.coeff_eq_zero_of_natDegree_lt (lt_of_lt_of_le hdeg hi), map_zero, addVal_zero]
    exact le_top


-- @@ L682-691 verbatim
/-- The coefficients of the derivative lie in the same ideal, being multiples of the
coefficients. -/
private lemma coeff_derivative_mem_span_pow (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n)) {P : Polynomial R} (hdeg : P.natDegree < n)
    {m : ℕ} (hmn : n ≤ m)
    (hval : (m : ℕ∞) ≤ addVal A (Polynomial.eval ξ (P.map (algebraMap R A)))) (i : ℕ) :
    (Polynomial.derivative (P.map (algebraMap R A))).coeff i ∈
      Ideal.span {ξ ^ (m - n + 1)} := by
  rw [Polynomial.coeff_derivative]
  exact Ideal.mul_mem_right _ _ (coeff_mem_span_pow hπ hξ hn hass hdeg hmn hval (i + 1))


-- @@ L693-706 verbatim
/-- Two monic polynomials of the same positive degree differ in degree `< n`. -/
lemma natDegree_sub_lt (hn : 0 < n) (hFm : F.Monic) (hFdeg : F.natDegree = n)
    (hGm : G.Monic) (hGdeg : G.natDegree = n) : (F - G).natDegree < n := by
  by_cases h0 : F - G = 0
  · rw [h0, Polynomial.natDegree_zero]
    exact hn
  · rw [Polynomial.natDegree_lt_iff_degree_lt h0]
    have hFdeg' : F.degree = (n : ℕ) := by
      rw [Polynomial.degree_eq_natDegree hFm.ne_zero, hFdeg]
    have hGdeg' : G.degree = (n : ℕ) := by
      rw [Polynomial.degree_eq_natDegree hGm.ne_zero, hGdeg]
    refine lt_of_lt_of_le (Polynomial.degree_sub_lt_left ?_ hFm.ne_zero ?_) hFdeg'.le
    · rw [hFdeg', hGdeg']
    · rw [hFm.leadingCoeff, hGm.leadingCoeff]


-- @@ L708-741 verbatim
/-- The derivative at `ξ` is insensitive to a small perturbation of the coefficients: a monic `F` of
degree `n` whose value at `ξ` has valuation at least `δ + n` has derivative at `ξ` of valuation `δ`,
the same as `G`—the difference `F - G` has small coefficients by orthogonality, so its derivative
contributes strictly more than `δ`. -/
private lemma addVal_eval_derivative_eq (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n))
    (hFm : F.Monic) (hFdeg : F.natDegree = n) (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0)
    (hδ : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (G.map (algebraMap R A)))) = δ)
    {m : ℕ} (hmδ : δ + n ≤ m)
    (hval : (m : ℕ∞) ≤ addVal A (Polynomial.eval ξ (F.map (algebraMap R A)))) :
    addVal A (Polynomial.eval ξ (Polynomial.derivative (F.map (algebraMap R A)))) = δ := by
  have hPdeg : (F - G).natDegree < n := natDegree_sub_lt hn hFm hFdeg hGm hGdeg
  have hmap : (F - G).map (algebraMap R A) =
      F.map (algebraMap R A) - G.map (algebraMap R A) := by simp
  have hPval : (m : ℕ∞) ≤ addVal A (Polynomial.eval ξ ((F - G).map (algebraMap R A))) := by
    rwa [hmap, Polynomial.eval_sub, hGroot, sub_zero]
  -- the perturbation's derivative is strictly deeper than `δ`
  have hξ1 : (1 : ℕ∞) ≤ addVal A ξ := by rw [addVal_uniformizer hξ]
  have hdeep : ((m - n + 1 : ℕ) : ℕ∞) ≤ addVal A (Polynomial.eval ξ
      (Polynomial.derivative ((F - G).map (algebraMap R A)))) :=
    le_addVal_of_mem_span_pow hξ1 (eval_mem_span_pow
      (coeff_derivative_mem_span_pow hπ hξ hn hass hPdeg (by omega) hPval) ξ)
  have hlt : (δ : ℕ∞) < ((m - n + 1 : ℕ) : ℕ∞) := by
    rw [Nat.cast_lt]
    omega
  have hsplit : Polynomial.derivative (F.map (algebraMap R A)) =
      Polynomial.derivative (G.map (algebraMap R A)) +
        Polynomial.derivative ((F - G).map (algebraMap R A)) := by
    rw [hmap, Polynomial.derivative_sub]
    abel
  rw [hsplit, Polynomial.eval_add,
    (addVal A).map_add_eq_of_lt_left (by rw [hδ]; exact lt_of_lt_of_le hlt hdeep), hδ]


-- @@ L743-790 verbatim
/-- The fiber, the forward direction: a root of `F` in the cube around `ξ` forces the value of `F`
at `ξ` to have valuation at least `n * ρ + δ`. The factorization `F = (X - y) * h` gives that value
as `(ξ - y) * h ξ`, and `h ξ` has valuation at least `δ` because it agrees with the derivative of
`F` at `ξ` modulo `ξ - y`. -/
theorem le_addVal_eval_of_isRoot (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n))
    (hFm : F.Monic) (hFdeg : F.natDegree = n) (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0)
    (hδ : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (G.map (algebraMap R A)))) = δ)
    (hρ : δ + n ≤ n * ρ) {y : A}
    (hy : Polynomial.eval y (F.map (algebraMap R A)) = 0)
    (hdist : ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y - ξ)) :
    ((n * ρ + δ : ℕ) : ℕ∞) ≤ addVal A (Polynomial.eval ξ (F.map (algebraMap R A))) := by
  obtain ⟨h, hh⟩ := Polynomial.dvd_iff_isRoot.mpr hy
  have hdistξ : ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (ξ - y) := by
    rwa [(addVal A).map_sub_swap]
  have hev : Polynomial.eval ξ (F.map (algebraMap R A)) = (ξ - y) * Polynomial.eval ξ h := by
    rw [hh]
    simp
  -- the crude bound suffices to pin the derivative
  have hcrude : ((n * ρ : ℕ) : ℕ∞) ≤
      addVal A (Polynomial.eval ξ (F.map (algebraMap R A))) := by
    rw [hev, addVal_mul]
    exact hdistξ.trans le_self_add
  have hFder : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (F.map (algebraMap R A)))) = δ :=
    addVal_eval_derivative_eq hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hcrude
  -- `h (ξ)` agrees with `F' (ξ)` modulo `ξ - y`
  have hderiv : Polynomial.derivative (F.map (algebraMap R A)) =
      h + (Polynomial.X - Polynomial.C y) * Polynomial.derivative h := by
    rw [hh, Polynomial.derivative_mul, Polynomial.derivative_sub, Polynomial.derivative_X,
      Polynomial.derivative_C, sub_zero, one_mul]
  have hhval : (δ : ℕ∞) ≤ addVal A (Polynomial.eval ξ h) := by
    have h1 : Polynomial.eval ξ h =
        Polynomial.eval ξ (Polynomial.derivative (F.map (algebraMap R A))) -
          (ξ - y) * Polynomial.eval ξ (Polynomial.derivative h) := by
      rw [hderiv]
      simp
    rw [h1]
    refine (addVal A).map_le_sub (le_of_eq hFder.symm) ?_
    rw [addVal_mul]
    refine le_trans ?_ le_self_add
    refine le_trans ?_ hdistξ
    rw [Nat.cast_le]
    omega
  rw [hev, addVal_mul, Nat.cast_add]
  exact add_le_add hdistξ hhval


-- @@ L792-828 verbatim
/-- The fiber, the backward direction: if the value of `F` at `ξ` has valuation at least
`n * ρ + δ`, then `F` has a root in the cube around `ξ`. Newton's method (`exists_isRoot`) applies
because that valuation exceeds twice `δ`, which is the valuation of the derivative of `F` at `ξ`,
and it lands the root at distance of order at least `n * ρ`. -/
theorem exists_isRoot_of_le_addVal_eval (hc : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n))
    (hFm : F.Monic) (hFdeg : F.natDegree = n) (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0)
    (hδ : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (G.map (algebraMap R A)))) = δ)
    (hρ : δ + n ≤ n * ρ)
    (hval : ((n * ρ + δ : ℕ) : ℕ∞) ≤
      addVal A (Polynomial.eval ξ (F.map (algebraMap R A)))) :
    ∃ y : A, Polynomial.eval y (F.map (algebraMap R A)) = 0 ∧
      ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y - ξ) := by
  have hcrude : ((n * ρ : ℕ) : ℕ∞) ≤
      addVal A (Polynomial.eval ξ (F.map (algebraMap R A))) :=
    le_trans (by rw [Nat.cast_le]; omega) hval
  have hFder : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (F.map (algebraMap R A)))) = δ :=
    addVal_eval_derivative_eq hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hcrude
  obtain ⟨z, hz, hd⟩ := exists_isRoot hc (F.map (algebraMap R A)) ξ (by
    rw [hFder]
    refine lt_of_lt_of_le ?_ hval
    rw [← Nat.cast_add, Nat.cast_lt]
    omega)
  refine ⟨z, hz, ?_⟩
  have h2 : ((n * ρ + δ : ℕ) : ℕ∞) ≤ (δ : ℕ∞) + addVal A (z - ξ) :=
    hval.trans (hd.trans_eq (by rw [hFder]))
  rcases eq_or_ne (addVal A (z - ξ)) ⊤ with hv | hv
  · rw [hv]
    exact le_top
  · lift addVal A (z - ξ) to ℕ using hv with c hc'
    rw [← Nat.cast_add, Nat.cast_le] at h2
    rw [Nat.cast_le]
    omega


-- @@ L830-865 verbatim
/-- The order of the derivative at a nearby root: if a monic `F` of degree `n` has a root `y` in the
cube around `ξ`, then the derivative of `F` at `y` has valuation `δ`. Applied to the minimal
polynomial of *another* uniformizer of the same cube, this says that `δ` depends only on the cube
and not on the generator used to describe it—which is what lets the volume bookkeeping of the change
of variables use a single exponent for every cube. -/
theorem addVal_eval_derivative_eq_of_isRoot (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n))
    (hFm : F.Monic) (hFdeg : F.natDegree = n) (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0)
    (hδ : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (G.map (algebraMap R A)))) = δ)
    (hρ : δ + n ≤ n * ρ) {y : A}
    (hy : Polynomial.eval y (F.map (algebraMap R A)) = 0)
    (hdist : ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y - ξ)) :
    addVal A (Polynomial.eval y (Polynomial.derivative (F.map (algebraMap R A)))) = δ := by
  have hcrude : ((n * ρ : ℕ) : ℕ∞) ≤
      addVal A (Polynomial.eval ξ (F.map (algebraMap R A))) :=
    le_trans (by rw [Nat.cast_le]; omega)
      (le_addVal_eval_of_isRoot hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hy hdist)
  have hFder : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (F.map (algebraMap R A)))) = δ :=
    addVal_eval_derivative_eq hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hcrude
  have h1 : Polynomial.eval y (Polynomial.derivative (F.map (algebraMap R A))) =
      Polynomial.eval ξ (Polynomial.derivative (F.map (algebraMap R A))) +
        (Polynomial.eval y (Polynomial.derivative (F.map (algebraMap R A))) -
          Polynomial.eval ξ (Polynomial.derivative (F.map (algebraMap R A)))) := by
    abel
  have h2 : (δ : ℕ∞) < addVal A
      (Polynomial.eval y (Polynomial.derivative (F.map (algebraMap R A))) -
        Polynomial.eval ξ (Polynomial.derivative (F.map (algebraMap R A)))) := by
    refine lt_of_lt_of_le ?_ (addVal_le_iff_dvd.mpr
      (Polynomial.sub_dvd_eval_sub y ξ (Polynomial.derivative (F.map (algebraMap R A)))))
    refine lt_of_lt_of_le ?_ hdist
    rw [Nat.cast_lt]
    omega
  rw [h1, (addVal A).map_add_eq_of_lt_left (by rw [hFder]; exact h2), hFder]


-- @@ L867-894 verbatim
/-- **The fiber is at most a singleton**: two roots of `F` in the same cube coincide.
Distinct roots are no farther apart than the order of the derivative (`addVal_sub_le_of_isRoot`),
which is `δ` at either of them, and `δ < n * ρ`. -/
theorem eq_of_isRoot_of_dist (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n))
    (hFm : F.Monic) (hFdeg : F.natDegree = n) (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0)
    (hδ : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (G.map (algebraMap R A)))) = δ)
    (hρ : δ + n ≤ n * ρ) {y y' : A}
    (hy : Polynomial.eval y (F.map (algebraMap R A)) = 0)
    (hy' : Polynomial.eval y' (F.map (algebraMap R A)) = 0)
    (hdist : ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y - ξ))
    (hdist' : ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y' - ξ)) : y = y' := by
  by_contra hne
  have hyder : addVal A (Polynomial.eval y
      (Polynomial.derivative (F.map (algebraMap R A)))) = δ :=
    addVal_eval_derivative_eq_of_isRoot hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hy hdist
  -- distinct roots are at distance at most `δ`, but both are `n ρ`-close to `ξ`
  have h3 : ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y - y') := by
    have h4 : y - y' = (y - ξ) - (y' - ξ) := by abel
    rw [h4]
    exact (addVal A).map_le_sub hdist hdist'
  have h5 := addVal_sub_le_of_isRoot hy hy' hne
  rw [hyder] at h5
  have h6 : ((n * ρ : ℕ) : ℕ∞) ≤ (δ : ℕ∞) := h3.trans h5
  rw [Nat.cast_le] at h6
  omega


-- @@ L896-921 verbatim
/-- The local fiber count behind the change of variables, the quantitative form of Lemma 1 and the
surjectivity of the parametrization: the cube around `ξ` of radius `π ^ ρ` contains exactly one root
of `F` precisely when the value of `F` at `ξ` has valuation at least `n * ρ + δ`. So the image of
the cube under the minimal-polynomial map is the *exact* level set of that condition, an affine
condition on the coefficients of `F` and hence a translate of a lattice
([Serre 1978, Lemma 1, p.1033][Serre1978]). -/
theorem existsUnique_isRoot_iff (hc : IsAdicComplete (IsLocalRing.maximalIdeal A) A)
    (hπ : Irreducible π) (hξ : Irreducible ξ) (hn : 0 < n)
    (hass : Associated (algebraMap R A π) (ξ ^ n))
    (hFm : F.Monic) (hFdeg : F.natDegree = n) (hGm : G.Monic) (hGdeg : G.natDegree = n)
    (hGroot : Polynomial.eval ξ (G.map (algebraMap R A)) = 0)
    (hδ : addVal A (Polynomial.eval ξ
      (Polynomial.derivative (G.map (algebraMap R A)))) = δ)
    (hρ : δ + n ≤ n * ρ) :
    (∃! y : A, Polynomial.eval y (F.map (algebraMap R A)) = 0 ∧
        ((n * ρ : ℕ) : ℕ∞) ≤ addVal A (y - ξ)) ↔
      ((n * ρ + δ : ℕ) : ℕ∞) ≤
        addVal A (Polynomial.eval ξ (F.map (algebraMap R A))) := by
  constructor
  · rintro ⟨y, ⟨hy, hdist⟩, -⟩
    exact le_addVal_eval_of_isRoot hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hy hdist
  · intro hval
    obtain ⟨y, hy, hdist⟩ := exists_isRoot_of_le_addVal_eval hc hπ hξ hn hass hFm hFdeg hGm hGdeg
      hGroot hδ hρ hval
    exact ⟨y, ⟨hy, hdist⟩, fun y' ⟨hy', hdist'⟩ =>
      eq_of_isRoot_of_dist hπ hξ hn hass hFm hFdeg hGm hGdeg hGroot hδ hρ hy' hy hdist' hdist⟩


-- @@ L923-923 verbatim
end Fibers


-- @@ L925-929 verbatim
/-! ## The coordinate dictionary at an Eisenstein generator

The specialization of the layer above to `integers L` at an Eisenstein generator, through the
monogenic power basis `basisOfEisenstein`.
-/


-- @@ L931-931 verbatim
section Integers


-- @@ L933-934 verbatim
variable {K : Type*} [Field K] [ValuativeRel K] [UniformSpace K] [IsUniformAddGroup K]
  [IsNonarchimedeanLocalField K] {π : 𝒪[K]} {x : SeparableClosure K}


-- @@ L936-944 verbatim
omit [IsUniformAddGroup K] in
/-- The Eisenstein generator is a uniformizer of `integers L`: it generates the maximal ideal
(`isMaximal_span_integralGen`). -/
theorem irreducible_integralGen (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))] :
    Irreducible (integralGen hint) :=
  (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr
    (IsLocalRing.eq_maximalIdeal (isMaximal_span_integralGen hπ hint hei)).symm


-- @@ L946-955 verbatim
omit [IsUniformAddGroup K] in
/-- The interleaving equating `(ξ) ^ n` with `π` times `integers L`, from
`span_integralGen_pow_eq`, in the associate form the orthogonality layer consumes. -/
theorem associated_algebraMap_pow (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Associated (algebraMap 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) π)
      (integralGen hint ^ (minpoly 𝒪[K] x).natDegree) := by
  have h := span_integralGen_pow_eq hπ hint hei
  rw [Ideal.span_singleton_pow] at h
  exact (Ideal.span_singleton_eq_span_singleton.mp h).symm


-- @@ L957-972 verbatim
omit [IsUniformAddGroup K] in
/-- The coordinate dictionary at an Eisenstein generator: an element of `integers L` lies in
`π ^ ρ` times `integers L` exactly when all of its coordinates in the monogenic basis
(`basisOfEisenstein`) lie in `π ^ ρ` times `𝒪[K]`, so a ball of `integers L` whose radius is a
multiple of `n` is a *cube* in coordinates. This is the dictionary that turns the source side of the
paper's parametrization (equations (6)–(7)) into a subset of the same measured coefficient space as
its target. -/
theorem le_addVal_mul_iff_coords (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    (ρ : ℕ) (y : ↥(integers (IntermediateField.adjoin K {x}))) :
    (((minpoly 𝒪[K] x).natDegree * ρ : ℕ) : ℕ∞) ≤
        addVal ↥(integers (IntermediateField.adjoin K {x})) y ↔
      ∀ i, (ρ : ℕ∞) ≤ addVal 𝒪[K] ((basisOfEisenstein hπ hint hei).repr y i) :=
  le_addVal_mul_iff hπ (irreducible_integralGen hπ hint hei) (minpoly.natDegree_pos hint)
    (associated_algebraMap_pow hπ hint hei) _ (basisOfEisenstein_apply hπ hint hei) ρ y


-- @@ L974-984 verbatim
/-- The power basis of `integers L` at an arbitrary uniformizer—the affine chart that each cube of
the decomposition of the set of uniformizers carries, being centered at a uniformizer of its own. -/
noncomputable def powersBasisIntegers (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    {η : ↥(integers (IntermediateField.adjoin K {x}))} (hη : Irreducible η) :
    Module.Basis (Fin (minpoly 𝒪[K] x).natDegree) 𝒪[K]
      ↥(integers (IntermediateField.adjoin K {x})) :=
  powersBasis hπ (irreducible_integralGen hπ hint hei) (minpoly.natDegree_pos hint)
    (associated_algebraMap_pow hπ hint hei) (basisOfEisenstein hπ hint hei)
    (basisOfEisenstein_apply hπ hint hei) hη


-- @@ L986-995 verbatim
omit [IsUniformAddGroup K] in
lemma powersBasisIntegers_apply (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    {η : ↥(integers (IntermediateField.adjoin K {x}))} (hη : Irreducible η)
    (i : Fin (minpoly 𝒪[K] x).natDegree) :
    powersBasisIntegers hπ hint hei hη i = η ^ (i : ℕ) :=
  powersBasis_apply hπ (irreducible_integralGen hπ hint hei) (minpoly.natDegree_pos hint)
    (associated_algebraMap_pow hπ hint hei) (basisOfEisenstein hπ hint hei)
    (basisOfEisenstein_apply hπ hint hei) hη i


-- @@ L997-1014 verbatim
omit [IsUniformAddGroup K] in
/-- A ball of `integers L` is the coordinate lattice of a multiplication matrix: the coordinate
vector of `y` lies in the lattice of the matrix of multiplication by `z` exactly when the valuation
of `z` is at most that of `y`—in the discrete valuation ring `integers L` divisibility *is* the
valuation inequality, and the ball of radius the valuation of `z` is the ideal generated by `z`.
With `det_leftMulMatrix` and `measure_integerBox_eq_pow_mul` this computes the volume of such a ball
in coordinates as `1 / q` to the order of the norm of `z`—the step that replaces the paper's
Jacobian ([Serre 1978, Lemma 2, p.1033][Serre1978]). -/
theorem toCoeff_equivFun_mem_imageLattice_iff (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    (z y : ↥(integers (IntermediateField.adjoin K {x}))) :
    toCoeff ((basisOfEisenstein hπ hint hei).equivFun y) ∈
        imageLattice
          (Algebra.leftMulMatrix (basisOfEisenstein hπ hint hei) z) ↔
      addVal ↥(integers (IntermediateField.adjoin K {x})) z ≤
        addVal ↥(integers (IntermediateField.adjoin K {x})) y := by
  rw [toCoeff_mem_imageLattice_iff, mem_range_leftMulMatrix_iff, addVal_le_iff_dvd]


-- @@ L1016-1023 verbatim
/-- The coordinate embedding of `integers L` into the coefficient space, in the monogenic basis
(`basisOfEisenstein`): the chart in which the balls of `integers L` become the lattices of
`HaarScaling.lean`. -/
noncomputable def coord (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    (y : ↥(integers (IntermediateField.adjoin K {x}))) :
    Fin (minpoly 𝒪[K] x).natDegree → K :=
  toCoeff ((basisOfEisenstein hπ hint hei).equivFun y)


-- @@ L1025-1029 verbatim
omit [IsUniformAddGroup K] in
lemma coord_injective (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Function.Injective (coord hπ hint hei) := fun _ _ hyy' =>
  (basisOfEisenstein hπ hint hei).equivFun.injective (toCoeff_injective hyy')


-- @@ L1031-1054 verbatim
omit [IsUniformAddGroup K] in
/-- A ball of `integers L` is a lattice in coordinates: the image under the chart of the ball of
radius the valuation of `z`—that is, of the ideal generated by `z`—is the image lattice of the
matrix of multiplication by `z`. -/
theorem image_coord_eq_imageLattice (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    (z : ↥(integers (IntermediateField.adjoin K {x}))) :
    coord hπ hint hei '' {y | addVal ↥(integers (IntermediateField.adjoin K {x})) z ≤
        addVal ↥(integers (IntermediateField.adjoin K {x})) y} =
      imageLattice (Algebra.leftMulMatrix (basisOfEisenstein hπ hint hei) z) := by
  ext a
  constructor
  · rintro ⟨y, hy, rfl⟩
    exact (toCoeff_equivFun_mem_imageLattice_iff hπ hint hei z y).mpr hy
  · intro ha
    -- the lattice sits in the integer box, so `a` is the chart image of some element
    rw [imageLattice_eq_image_range] at ha
    obtain ⟨c, hcmem, hc⟩ := ha
    refine ⟨(basisOfEisenstein hπ hint hei).equivFun.symm c, ?_, ?_⟩
    · refine (toCoeff_equivFun_mem_imageLattice_iff hπ hint hei z _).mp ?_
      rw [LinearEquiv.apply_symm_apply]
      exact (toCoeff_mem_imageLattice_iff _ c).mpr hcmem
    · rw [coord, LinearEquiv.apply_symm_apply, hc]


-- @@ L1056-1065 verbatim
/-! ### The order of the norm of the derivative

Lemma 2 of the paper computes the Jacobian of the parametrization as a Vandermonde times the
determinant of the embeddings on a basis, and equation (11) reads off that its valuation is `d L`
from the fact that the square of each factor generates the discriminant. In the route of this file
no Jacobian occurs: what carries the factor `1 / q ^ d L` is the lattice of multiplication by the
derivative of `g` at `ξ`, whose index is the order of the norm of that derivative—and that norm *is*
the discriminant of the power basis up to sign, so its order is `d L` by the definition of
`discIdeal`. Neither conjugates nor square roots enter.
-/


-- @@ L1067-1093 verbatim
omit [IsUniformAddGroup K] in
/-- The norm over `𝒪[K]`, computed after base change: the norm over `𝒪[K]` of an element of
`integers L` maps to its norm over `K`—the two are determinants of the same multiplication, on an
`𝒪[K]`-basis and on its base change, and `L` is the localization of `integers L` at the
nonzerodivisors of `𝒪[K]`. -/
theorem algebraMap_norm (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    (z : ↥(integers (IntermediateField.adjoin K {x}))) :
    algebraMap 𝒪[K] K (Algebra.norm 𝒪[K] z) =
      Algebra.norm K (algebraMap ↥(integers (IntermediateField.adjoin K {x}))
        ↥(IntermediateField.adjoin K {x}) z) := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  have : FiniteDimensional K ↥(IntermediateField.adjoin K {x}) :=
    (IntermediateField.adjoin.powerBasis hint.tower_top).finite
  have hIC : IsIntegralClosure ↥(integers (IntermediateField.adjoin K {x})) ↥𝒪[K]
      ↥(IntermediateField.adjoin K {x}) :=
    inferInstanceAs (IsIntegralClosure
      ↥(integralClosure ↥𝒪[K] ↥(IntermediateField.adjoin K {x})) ↥𝒪[K]
      ↥(IntermediateField.adjoin K {x}))
  have := IsIntegralClosure.isLocalization 𝒪[K] K ↥(IntermediateField.adjoin K {x})
    ↥(integers (IntermediateField.adjoin K {x}))
  have : Module.Free 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) :=
    Module.Free.of_basis (basisOfEisenstein hπ hint hei)
  have : Module.Finite 𝒪[K] ↥(integers (IntermediateField.adjoin K {x})) :=
    Module.Finite.of_basis (basisOfEisenstein hπ hint hei)
  exact (Algebra.norm_localization 𝒪[K] (nonZeroDivisors 𝒪[K]) z).symm


-- @@ L1095-1132 verbatim
omit [IsUniformAddGroup K] in
/-- Lemma 2 in elementary form: the norm of the derivative of `g` at `ξ` is an associate of
`π ^ d L`. That norm is the discriminant of the power basis up to sign, so it *generates*
`discIdeal` (`discIdeal_eq_span`), whose multiplicity at `𝓂[K]` is `d L` by definition
(`associated_pow_d`) ([Serre 1978, Lemma 2, eq. (11), p.1033][Serre1978]). -/
theorem associated_norm_derivative (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Associated (Algebra.norm 𝒪[K] (Polynomial.aeval (integralGen hint)
        (Polynomial.derivative (minpoly 𝒪[K] x))))
      (π ^ d (IntermediateField.adjoin K {x})) := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  obtain ⟨N₀, hN₀ne, -, hN₀val, hspan⟩ := discIdeal_eq_span K hπ hint hei
  -- evaluation at `integralGen` agrees with evaluation at the generator of `L`
  have hcoe : ∀ P : Polynomial 𝒪[K],
      algebraMap ↥(integers (IntermediateField.adjoin K {x}))
          ↥(IntermediateField.adjoin K {x}) (Polynomial.aeval (integralGen hint) P) =
        Polynomial.aeval (IntermediateField.AdjoinSimple.gen K x) P := fun P => by
    rw [← Polynomial.aeval_algebraMap_apply]
    rfl
  have hminx' : minpoly K (IntermediateField.AdjoinSimple.gen K x) =
      (minpoly 𝒪[K] x).map (algebraMap 𝒪[K] K) := by
    rw [show minpoly K (IntermediateField.AdjoinSimple.gen K x) = minpoly K x from
      (minpoly.algebraMap_eq
        (algebraMap ↥(IntermediateField.adjoin K {x}) (SeparableClosure K)).injective _).symm]
    exact minpoly.isIntegrallyClosed_eq_field_fractions' K hint
  have hderiv : Polynomial.aeval (IntermediateField.AdjoinSimple.gen K x)
      (Polynomial.derivative (minpoly K (IntermediateField.AdjoinSimple.gen K x))) =
      algebraMap ↥(integers (IntermediateField.adjoin K {x}))
        ↥(IntermediateField.adjoin K {x}) (Polynomial.aeval (integralGen hint)
          (Polynomial.derivative (minpoly 𝒪[K] x))) := by
    rw [hminx', Polynomial.derivative_map, Polynomial.aeval_map_algebraMap, hcoe]
  have heq : Algebra.norm 𝒪[K] (Polynomial.aeval (integralGen hint)
      (Polynomial.derivative (minpoly 𝒪[K] x))) = N₀ := by
    refine IsFractionRing.injective 𝒪[K] K ?_
    rw [algebraMap_norm hπ hint hei, hN₀val, hderiv]
  rw [heq]
  exact associated_pow_d K hπ hN₀ne hspan


-- @@ L1134-1167 verbatim
omit [IsUniformAddGroup K] in
/-- The norm of the Eisenstein generator is an associate of the uniformizer: it is the constant
coefficient of the minimal polynomial up to sign (`PowerBasis.norm_gen_eq_coeff_zero_minpoly`), and
that coefficient is an associate of `π` (`associated_pi_coeff_zero`). -/
theorem associated_norm_integralGen (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) :
    Associated (Algebra.norm 𝒪[K] (integralGen hint)) π := by
  have : IsFractionRing 𝒪[K] K :=
    inferInstanceAs (IsFractionRing (valuation K).valuationSubring K)
  have : FiniteDimensional K ↥(IntermediateField.adjoin K {x}) :=
    (IntermediateField.adjoin.powerBasis hint.tower_top).finite
  set pb : PowerBasis K ↥(IntermediateField.adjoin K {x}) :=
    IntermediateField.adjoin.powerBasis hint.tower_top with hpb
  have hminx' : minpoly K (IntermediateField.AdjoinSimple.gen K x) =
      (minpoly 𝒪[K] x).map (algebraMap 𝒪[K] K) := by
    rw [show minpoly K (IntermediateField.AdjoinSimple.gen K x) = minpoly K x from
      (minpoly.algebraMap_eq
        (algebraMap ↥(IntermediateField.adjoin K {x}) (SeparableClosure K)).injective _).symm]
    exact minpoly.isIntegrallyClosed_eq_field_fractions' K hint
  have hnorm : Algebra.norm 𝒪[K] (integralGen hint) =
      (-1 : 𝒪[K]) ^ pb.dim * (minpoly 𝒪[K] x).coeff 0 := by
    refine IsFractionRing.injective 𝒪[K] K ?_
    have h1 := Algebra.PowerBasis.norm_gen_eq_coeff_zero_minpoly pb
    rw [show pb.gen = IntermediateField.AdjoinSimple.gen K x from rfl, hminx',
      Polynomial.coeff_map] at h1
    rw [algebraMap_norm hπ hint hei,
      show algebraMap ↥(integers (IntermediateField.adjoin K {x}))
          ↥(IntermediateField.adjoin K {x}) (integralGen hint) =
        IntermediateField.AdjoinSimple.gen K x from rfl, h1]
    simp only [map_mul, map_pow, map_neg, map_one]
  rw [hnorm]
  exact (Ideal.span_singleton_eq_span_singleton.mp
    (Ideal.span_singleton_mul_left_unit (isUnit_one.neg.pow pb.dim) _)).trans
      (associated_pi_coeff_zero hπ hint hei).symm


-- @@ L1169-1175 verbatim
omit [IsUniformAddGroup K] in
/-- The norm of a power of the Eisenstein generator is an associate of the same power of `π`. -/
theorem associated_norm_integralGen_pow (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π})) (k : ℕ) :
    Associated (Algebra.norm 𝒪[K] (integralGen hint ^ k)) (π ^ k) := by
  rw [map_pow]
  exact Associated.pow_pow (associated_norm_integralGen hπ hint hei)


-- @@ L1177-1189 verbatim
/-- A multiplicative norm carrying a uniformizer to valuation one preserves valuations. -/
private theorem addVal_norm_of_uniformizer {R A : Type*} [CommRing R] [IsDomain R]
    [IsDiscreteValuationRing R] [CommRing A] [IsDomain A] [IsDiscreteValuationRing A]
    [Algebra R A] {n : ℕ} (b : Module.Basis (Fin n) R A) {ξ : A}
    (hξ : Irreducible ξ) (hnξ : addVal R (Algebra.norm R ξ) = 1) (z : A) :
    addVal R (Algebra.norm R z) = addVal A z := by
  by_cases hz : z = 0
  · subst hz
    rw [addVal_zero, (Algebra.norm_eq_zero_iff_of_basis b).mpr rfl, addVal_zero]
  · obtain ⟨k, u, hu⟩ := IsDiscreteValuationRing.eq_unit_mul_pow_irreducible hz hξ
    rw [hu, map_mul, map_pow, addVal_mul,
      addVal_eq_zero_iff.mpr (u.isUnit.map (Algebra.norm R)), zero_add, addVal_pow, hnξ,
      addVal_def' u hξ k, nsmul_eq_mul, mul_one]


-- @@ L1191-1210 verbatim
omit [IsUniformAddGroup K] in
/-- The norm computes the valuation: for the totally ramified `integers L` over `𝒪[K]`, the
`π`-adic order of the norm of `z` is the valuation of `z` in `integers L`—every `z` is a unit times
a power of the generator, the norm of a unit is a unit, and the norm of the generator is an
associate of `π`. This is the classical statement that the valuation of `K` composed with the norm
is the valuation of `L`, for a totally ramified extension (cf. the header of
`Discriminant.lean`). -/
theorem addVal_norm (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    (z : ↥(integers (IntermediateField.adjoin K {x}))) :
    addVal 𝒪[K] (Algebra.norm 𝒪[K] z) =
      addVal ↥(integers (IntermediateField.adjoin K {x})) z := by
  have hnξ : addVal 𝒪[K] (Algebra.norm 𝒪[K] (integralGen hint)) = 1 := by
    rw [addVal_eq_of_associated (associated_norm_integralGen hπ hint hei),
      addVal_uniformizer hπ]
  exact addVal_norm_of_uniformizer (R := ↥𝒪[K])
    (A := ↥(integers (IntermediateField.adjoin K {x})))
    (n := (minpoly 𝒪[K] x).natDegree) (basisOfEisenstein hπ hint hei)
    (irreducible_integralGen hπ hint hei) hnξ z


-- @@ L1212-1225 verbatim
omit [IsUniformAddGroup K] in
/-- The fiber exponent is the discriminant exponent: the valuation in `integers L` of the derivative
of `g` at `ξ` is `d L`. The fiber condition of `existsUnique_isRoot_iff` is stated with that
valuation, while the volume of the corresponding lattice is governed by the order of its *norm*
(`associated_norm_derivative`)—and `addVal_norm` identifies the two. -/
theorem addVal_derivative_eq_d (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))] :
    addVal ↥(integers (IntermediateField.adjoin K {x}))
        (Polynomial.aeval (integralGen hint)
          (Polynomial.derivative (minpoly 𝒪[K] x))) =
      (d (IntermediateField.adjoin K {x}) : ℕ∞) := by
  rw [← addVal_norm hπ hint hei,
    addVal_eq_of_associated (associated_norm_derivative hπ hint hei), hπ.addVal_pow]


-- @@ L1227-1233 verbatim
/-! ### Equation (5): the volume of the uniformizers

The one volume of the set of uniformizers that the assembly of equation (13) needs. In the chart,
that set is the ideal generated by `ξ` minus the ideal generated by `ξ ^ 2`, the difference of two
lattices of determinant orders `1` and `2`—the norms of `ξ` and `ξ ^ 2`—so their volumes are `1 / q`
and `1 / q ^ 2`.
-/


-- @@ L1235-1247 verbatim
/-- The lattice of multiplication by an element has volume prescribed by its norm. -/
theorem measure_imageLattice_leftMul {A : Type*} [CommRing A]
    [Algebra 𝒪[K] A] {n : ℕ} (b : Module.Basis (Fin n) 𝒪[K] A)
    [MeasurableSpace (Fin n → K)] [BorelSpace (Fin n → K)]
    (μ : Measure (Fin n → K)) [μ.IsAddLeftInvariant]
    (hnorm : μ (integerBox K n) = 1) {π : 𝒪[K]} (hπ : Irreducible π)
    (z : A) {k : ℕ} (hz : Associated (Algebra.norm 𝒪[K] z) (π ^ k)) :
    μ (imageLattice (Algebra.leftMulMatrix b z)) = (q K : ℝ≥0∞)⁻¹ ^ k := by
  have hdet := det_leftMulMatrix (R := ↥𝒪[K]) (A := A) (n := n) b z
  refine measure_imageLattice_eq_inv_pow μ hnorm _ ?_ hπ ?_
  · rw [hdet]
    exact hz.ne_zero_iff.mpr (pow_ne_zero k hπ.ne_zero)
  · rwa [hdet]


-- @@ L1249-1263 verbatim
/-- The volume of the ball of radius `k` of `integers L` in the chart is `1 / q ^ k`: it is the
lattice of multiplication by `ξ ^ k`, whose determinant, the norm of `ξ ^ k`, has order `k`. -/
theorem measure_image_coord_ball (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    [MeasurableSpace (Fin (minpoly 𝒪[K] x).natDegree → K)]
    [BorelSpace (Fin (minpoly 𝒪[K] x).natDegree → K)]
    (μ : Measure (Fin (minpoly 𝒪[K] x).natDegree → K)) [μ.IsAddLeftInvariant]
    (hnorm : μ (integerBox K (minpoly 𝒪[K] x).natDegree) = 1) (k : ℕ) :
    μ (coord hπ hint hei '' {y | addVal ↥(integers (IntermediateField.adjoin K {x}))
        (integralGen hint ^ k) ≤ addVal ↥(integers (IntermediateField.adjoin K {x})) y}) =
      (q K : ℝ≥0∞)⁻¹ ^ k := by
  rw [image_coord_eq_imageLattice hπ hint hei]
  exact measure_imageLattice_leftMul (A := ↥(integers (IntermediateField.adjoin K {x})))
    (basisOfEisenstein hπ hint hei) μ hnorm hπ _ (associated_norm_integralGen_pow hπ hint hei k)


-- @@ L1265-1325 verbatim
/-- The uniformizers of `integers L` have volume `(1 / q) * (1 - 1 / q)` in the chart of the
monogenic basis. The set of uniformizers is the difference of the balls of radii `1` and `2`, whose
volumes `measure_image_coord_ball` computes as `1 / q` and `1 / q ^ 2`
([Serre 1978, eq. (5), p.1032][Serre1978]). -/
theorem measure_image_coord_uniformizers (hπ : Irreducible π) (hint : IsIntegral 𝒪[K] x)
    (hei : (minpoly 𝒪[K] x).IsEisensteinAt (Submodule.span 𝒪[K] {π}))
    [IsDiscreteValuationRing ↥(integers (IntermediateField.adjoin K {x}))]
    [MeasurableSpace (Fin (minpoly 𝒪[K] x).natDegree → K)]
    [BorelSpace (Fin (minpoly 𝒪[K] x).natDegree → K)]
    (μ : Measure (Fin (minpoly 𝒪[K] x).natDegree → K)) [μ.IsAddLeftInvariant]
    (hnorm : μ (integerBox K (minpoly 𝒪[K] x).natDegree) = 1) :
    μ (coord hπ hint hei ''
        {y | addVal ↥(integers (IntermediateField.adjoin K {x})) y = 1}) =
      (q K : ℝ≥0∞)⁻¹ * (1 - (q K : ℝ≥0∞)⁻¹) := by
  classical
  have hξ : Irreducible (integralGen hint) := irreducible_integralGen hπ hint hei
  have hq1 : (q K : ℝ≥0∞)⁻¹ ≤ 1 :=
    ENNReal.inv_le_one.mpr (by exact_mod_cast (one_lt_q K).le)
  -- the uniformizers are the difference of the balls of radii `1` and `2`
  have hset : {y : ↥(integers (IntermediateField.adjoin K {x})) |
        addVal ↥(integers (IntermediateField.adjoin K {x})) y = 1} =
      {y | addVal _ (integralGen hint ^ 1) ≤ addVal _ y} \
        {y | addVal _ (integralGen hint ^ 2) ≤ addVal _ y} := by
    ext y
    rw [Set.mem_sdiff, Set.mem_ofPred_eq, Set.mem_ofPred_eq, Set.mem_ofPred_eq, hξ.addVal_pow,
      hξ.addVal_pow]
    constructor
    · intro h
      rw [h]
      exact ⟨by norm_num, by norm_num⟩
    · rintro ⟨h1, h2⟩
      rcases eq_or_ne (addVal _ y) ⊤ with hv | hv
      · exact absurd (hv ▸ le_top) h2
      · lift addVal ↥(integers (IntermediateField.adjoin K {x})) y to ℕ using hv with m
        have h1' : 1 ≤ m := by exact_mod_cast h1
        have h2' : ¬ (2 ≤ m) := fun h => h2 (by exact_mod_cast h)
        rw [show m = 1 from by omega]
        norm_num
  have hsub : coord hπ hint hei '' {y | addVal _ (integralGen hint ^ 2) ≤ addVal _ y} ⊆
      coord hπ hint hei '' {y | addVal _ (integralGen hint ^ 1) ≤ addVal _ y} := by
    refine Set.image_mono fun y hy => ?_
    rw [Set.mem_ofPred_eq] at hy ⊢
    refine le_trans ?_ hy
    rw [hξ.addVal_pow, hξ.addVal_pow, Nat.cast_le]
    omega
  have hmeas2 : MeasurableSet (coord hπ hint hei ''
      {y | addVal _ (integralGen hint ^ 2) ≤ addVal _ y}) := by
    rw [image_coord_eq_imageLattice hπ hint hei]
    exact (isCompact_imageLattice _).isClosed.measurableSet
  have hfin2 : μ (coord hπ hint hei ''
      {y | addVal _ (integralGen hint ^ 2) ≤ addVal _ y}) ≠ ⊤ := by
    rw [measure_image_coord_ball hπ hint hei μ hnorm 2]
    exact ENNReal.pow_ne_top (ENNReal.inv_ne_top.mpr
      (Nat.cast_ne_zero.mpr (by have := one_lt_q K; omega)))
  rw [hset, Set.image_sdiff (coord_injective hπ hint hei),
    measure_sdiff hsub hmeas2.nullMeasurableSet hfin2,
    measure_image_coord_ball hπ hint hei μ hnorm 1,
    measure_image_coord_ball hπ hint hei μ hnorm 2]
  refine ENNReal.sub_eq_of_eq_add (ENNReal.pow_ne_top (ENNReal.inv_ne_top.mpr
    (Nat.cast_ne_zero.mpr (by have := one_lt_q K; omega)))) ?_
  rw [pow_one, pow_two, ← mul_add, tsub_add_cancel_of_le hq1, mul_one]


-- @@ L1327-1327 verbatim
end Integers


-- @@ L1329-1329 verbatim
end MassFormula
