/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.Descriptive.StructureSpace
public import Mathlib.MeasureTheory.MeasurableSpace.Constructions
import Mathlib.Algebra.Order.Module.Field
import Mathlib.Data.EReal.Inv
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded


-- @@ L15-26 verbatim
/-!
# Measurable Structure on the Structure Space

This file equips `StructureSpace L` with a `MeasurableSpace` structure, derived from
the product measurable space on `RelQuery L → Bool`. The key result is that cylinder
sets (sets determined by a single relation query) are measurable.

## Main Results

- `StructureSpace.instMeasurableSpace`: `MeasurableSpace` instance on `StructureSpace L`.
- `measurableSet_relHolds`: The set of codes where a given relation query holds is measurable.
-/


-- @@ L28-28 verbatim
@[expose] public section


-- @@ L30-30 verbatim
universe u v


-- @@ L32-32 verbatim
namespace FirstOrder


-- @@ L34-34 verbatim
namespace Language


-- @@ L36-36 verbatim
open MeasureTheory


-- @@ L38-44 verbatim
/-- The set of codes where a given relation query returns `true` is measurable (generic). -/
theorem measurableSet_relHoldsOn {α : Type*} (q : RelQueryOn L α) :
    MeasurableSet {c : StructureSpaceOn L α | c q = true} := by
  have : {c : StructureSpaceOn L α | c q = true} = (fun c => c q) ⁻¹' {true} := by
    ext c; simp
  rw [this]
  exact (measurable_pi_apply q) (measurableSet_singleton true)


-- @@ L46-50 verbatim
/-- `StructureSpace L` inherits the product measurable space from `RelQuery L → Bool`.
Since `Bool` has `MeasurableSpace Bool := ⊤` (all sets measurable), this is the
σ-algebra generated by cylinder sets. -/
instance : MeasurableSpace (StructureSpace L) :=
  MeasurableSpace.pi


-- @@ L52-59 verbatim
/-- The set of codes where a given relation query returns `true` is measurable.
These are the basic cylinder sets generating the σ-algebra. -/
theorem measurableSet_relHolds (q : RelQuery L) :
    MeasurableSet {c : StructureSpace L | c q = true} := by
  have : {c : StructureSpace L | c q = true} = (fun c => c q) ⁻¹' {true} := by
    ext c; simp
  rw [this]
  exact (measurable_pi_apply q) (measurableSet_singleton true)


-- @@ L61-61 verbatim
end Language


-- @@ L63-63 verbatim
end FirstOrder
