/-
Copyright (c) 2026 Cameron Freer. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Cameron Freer
-/
module

public import LeanPool.InfinitaryLogic.Methods.LopezEscobar.CodeClass
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.Data.EReal.Inv
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded

-- @@ L13-33 verbatim
/-!
# The shared-symbol decoder (issue #10, Unit 5a)

Craig separation returns a sentence over the **shared vocabulary** of the two PC
presentations, namely `symbSublang` of the intersections of their occurrence sets.  Unit 2b's
`pcSentence_relationsIn_inter` already proves that this intersection contains only graph
images of base relation symbols, so the separator can be decoded straight back into `L` —
no detour through `KLang L` or `backTranslateFormula` is needed.

Contents:

* `sharedLang` — the Craig shared language, exactly as `craig_pcSeparation_relational`
  returns it for the two side sentences;
* `exists_base_of_mem_relSym` — under `L.IsRelational`, every symbol of
  `relSym (KLang L) (baseFuns L) (baseRels L)` is `GraphRelation.base (Sum.inl R)` for a base
  relation `R` of the same arity (the `baseFuns` branch is vacuous);
* `sharedToBase : sharedLang L T₀ T₁ →ᴸ L` — the decoder, with
  `sharedToBase_onRelation_spec` recovering the shared symbol from its base preimage;
* `realize_sharedToBase` — **the semantic square**: for every graph code `d`, a shared
  sentence holds in the sublanguage reduct of `d` iff its decoding holds in `codeReduct d`.
-/


-- @@ L35-35 verbatim
@[expose] public section


-- @@ L37-37 verbatim
namespace FirstOrder.Language


-- @@ L39-39 verbatim
open FirstOrder Structure Set


-- @@ L41-41 verbatim
variable {L : Language.{0, 0}} [L.IsRelational] [Countable (Σ l, L.Relations l)]


-- @@ L43-43 verbatim
/-! ## The shared language -/


-- @@ L45-52 verbatim
variable (L) in
/-- **The Craig shared language** of the two PC presentations: the two-sorted sublanguage of
`graphLanguage (KLang L)` generated by the intersections of their occurrence sets — exactly
the language over which `craig_pcSeparation_relational` produces its separator. -/
noncomputable abbrev sharedLang (T₀ T₁ : (n : ℕ) → Set ((Fin n → Bool) × (Fin n → ℕ))) :
    Language.{0, 0} :=
  symbSublang ((pcSentence L .left T₀).functionsIn ∩ (pcSentence L .right T₁).functionsIn)
    ((pcSentence L .left T₀).relationsIn ∩ (pcSentence L .right T₁).relationsIn)


-- @@ L54-54 verbatim
/-! ## Decoding a shared relation symbol -/


-- @@ L56-70 verbatim
omit [Countable (Σ l, L.Relations l)] in
/-- Under `L.IsRelational` the base-generated graph symbols are exactly the base images: the
`graphRelSym '' baseFuns` branch of `relSym` is empty, so every member is
`GraphRelation.base (Sum.inl R)` at the same arity. -/
private theorem exists_base_of_mem_relSym {n : ℕ} {r : (graphLanguage (KLang L)).Relations n}
    (h : (⟨n, r⟩ : Σ k, (graphLanguage (KLang L)).Relations k) ∈
      relSym (KLang L) (baseFuns L) (baseRels L)) :
    ∃ R : L.Relations n, r = GraphRelation.base (Sum.inl R) := by
  rcases h with ⟨p, hp, hpe⟩ | ⟨q, hq, -⟩
  · obtain ⟨⟨k, R⟩, rfl⟩ := hp
    obtain ⟨rfl, h2⟩ := Sigma.mk.inj_iff.mp hpe
    rw [heq_eq_eq] at h2
    exact ⟨R, h2.symm⟩
  · obtain ⟨⟨k, f⟩, -⟩ := hq
    exact ((‹L.IsRelational› k).false f).elim


-- @@ L72-81 verbatim
variable (L) in
/-- **The shared-symbol decoder** `sharedLang L T₀ T₁ →ᴸ L`: the shared language has no
function symbols (the graph language is relational), and each shared relation symbol is the
graph image of a unique base relation symbol, which the decoder returns. -/
noncomputable def sharedToBase (T₀ T₁ : (n : ℕ) → Set ((Fin n → Bool) × (Fin n → ℕ))) :
    sharedLang L T₀ T₁ →ᴸ L where
  onFunction {_} f := f.1.elim
  onRelation {_} r :=
    Classical.choose (private_decl%
      (exists_base_of_mem_relSym (pcSentence_relationsIn_inter T₀ T₁ r.2)))


-- @@ L83-89 verbatim
/-- The decoder recovers the shared symbol: its base image is the symbol itself. -/
private theorem sharedToBase_onRelation_spec
    (T₀ T₁ : (n : ℕ) → Set ((Fin n → Bool) × (Fin n → ℕ)))
    {n : ℕ} (r : (sharedLang L T₀ T₁).Relations n) :
    (r.1 : (graphLanguage (KLang L)).Relations n) =
      GraphRelation.base (Sum.inl ((sharedToBase L T₀ T₁).onRelation r)) :=
  Classical.choose_spec (exists_base_of_mem_relSym (pcSentence_relationsIn_inter T₀ T₁ r.2))


-- @@ L91-91 verbatim
/-! ## The semantic square -/


-- @@ L93-110 verbatim
/-- The decoder is an expansion from the sublanguage reduct of a graph code onto its base
code reduct: shared relations are read the same way on both sides. -/
private theorem sharedToBase_isExpansionOn
    (T₀ T₁ : (n : ℕ) → Set ((Fin n → Bool) × (Fin n → ℕ)))
    (d : StructureSpace (graphLanguage (KLang L))) :
    @LHom.IsExpansionOn (sharedLang L T₀ T₁) L (sharedToBase L T₀ T₁) ℕ
      (@LHom.reduct (sharedLang L T₀ T₁) (graphLanguage (KLang L))
        (symbSublangIncl _ _) ℕ d.toStructure)
      (codeReduct d).toStructure := by
  let : (graphLanguage (KLang L)).Structure ℕ := d.toStructure
  let : (sharedLang L T₀ T₁).Structure ℕ :=
    @LHom.reduct (sharedLang L T₀ T₁) (graphLanguage (KLang L))
      (symbSublangIncl _ _) ℕ d.toStructure
  let : L.Structure ℕ := (codeReduct d).toStructure
  refine ⟨fun {_} f _ => f.1.elim, fun {n} r x => propext ?_⟩
  refine (codeReduct_toStructure ((sharedToBase L T₀ T₁).onRelation r) x).trans ?_
  rw [← sharedToBase_onRelation_spec T₀ T₁ r]
  exact Iff.rfl


-- @@ L112-129 verbatim
/-- **The semantic square** (the Unit-5a gate): a shared sentence holds in the sublanguage
reduct of a graph code exactly when its decoding along `sharedToBase` holds in the code
reduct.  This is what lets the Craig separator be read as an `L`-sentence about base codes. -/
theorem realize_sharedToBase (T₀ T₁ : (n : ℕ) → Set ((Fin n → Bool) × (Fin n → ℕ)))
    (θ₀ : (sharedLang L T₀ T₁).Sentenceω)
    (d : StructureSpace (graphLanguage (KLang L))) :
    @Sentenceω.Realize (sharedLang L T₀ T₁) θ₀ ℕ
        (@LHom.reduct (sharedLang L T₀ T₁) (graphLanguage (KLang L))
          (symbSublangIncl _ _) ℕ d.toStructure) ↔
      @Sentenceω.Realize L (θ₀.mapLanguage (sharedToBase L T₀ T₁)) ℕ
        (codeReduct d).toStructure := by
  let : (sharedLang L T₀ T₁).Structure ℕ :=
    @LHom.reduct (sharedLang L T₀ T₁) (graphLanguage (KLang L))
      (symbSublangIncl _ _) ℕ d.toStructure
  let : L.Structure ℕ := (codeReduct d).toStructure
  have := sharedToBase_isExpansionOn T₀ T₁ d
  exact (BoundedFormulaω.realize_mapLanguage (sharedToBase L T₀ T₁) θ₀
    (Empty.elim : Empty → ℕ) Fin.elim0).symm


-- @@ L131-131 verbatim
end FirstOrder.Language
