/-
Copyright (c) 2026 Siddhartha Gadgil, Anand Rao. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Siddhartha Gadgil, Anand Rao
-/
module

public import Mathlib.Algebra.Group.Basic
public import Mathlib.Algebra.Ring.Defs
public import Mathlib.Data.Quot
public import Mathlib.Tactic.ToDual
import Mathlib.Logic.Equiv.Defs


-- @@ L14-30 verbatim
/-!
# Free modules

We construct the free module over a ring `R` generated by a set `X`. It is assumed that both
`R` and `X` have decidable equality. This is to obtain decidable equality for the elements of
the module, which we do (`FreeModule.decEq`).
We choose our definition to allow both such computations and to prove results.

The definition is as a quotient of *Formal Sums* (`FormalSum`),
which are simply lists of pairs `(a, x)` where `a` is a coefficient in `R` and `x` is a term in `X`.
We associate to such a formal sum a coordinate function `X → R` (`FormalSum.coords`).
We see that having the same coordinate functions gives an equivalence relation on the formal sums.
The free module (`FreeModule`) is then defined as the corresponding quotient of such formal sums.

We also give an alternative description via moves, which is more convenient for universal
properties.
-/


-- @@ L32-32 verbatim
@[expose] public section


-- @@ L34-34 verbatim
namespace LeanPool.Polylean



-- @@ L37-37 verbatim
variable {R : Type _} [Ring R] [DecidableEq R]


-- @@ L39-39 verbatim
variable {X : Type _} [DecidableEq X]


-- @@ L41-44 verbatim
/-!

## Formal sums
-/




-- @@ L48-53 verbatim
/-- A *formal sum* represents an `R`-linear combination of finitely many elements of `X`.
  This is implemented as a list `R × X`, which associates to each element `X` of the list a
  coefficient from `R`. -/
abbrev FormalSum (R X : Type _) [Ring R] :=
  let _ringR : Ring R := inferInstance
  List (R × X)


-- @@ L55-62 verbatim
/-!
## Coordinate functions and Supports

* We define coordinate functions X → R for formal sums.
* We define (weak) support, relate non-zero coordinates.
* We prove decidable equality on a list (easy fact).

-/


-- @@ L64-70 verbatim
/-!
### Coordinate functions

The definition of coordinate functions is in two steps. We first define the coordinate for a pair
`(a, x)`, and then define the coordinate function for a formal sum by summing over such terms.

-/


-- @@ L72-76 verbatim
/-- Coordinates for a formal sum with one term. -/
def monomCoeff (R X : Type _) [Ring R] [DecidableEq X] (x₀ : X) (nx : R × X) : R :=
  match (nx.2 == x₀) with
  | true => nx.1
  | false => 0


-- @@ L78-84 verbatim
omit [DecidableEq R] in
/-- Homomorphism property for coordinates for a formal sum with one term. -/
theorem monom_coords_hom (x₀ x : X) (a b : R) :
    monomCoeff R X x₀ (a + b, x) =
      monomCoeff R X x₀ (a, x) + monomCoeff R X x₀ (b, x) := by
  simp only [monomCoeff]
  cases x == x₀ <;> simp


-- @@ L86-91 verbatim
omit [DecidableEq R] in
/-- Associativity of scalar multiplication coordinates for a formal sum with one term. -/
theorem monom_coords_mul (x₀ : X) (a b : R) :
    monomCoeff R X x₀ (a * b, x) = a * monomCoeff R X x₀ (b, x) := by
  simp only [monomCoeff]
  cases x == x₀ <;> simp


-- @@ L93-98 verbatim
omit [DecidableEq R] in
/-- Coordinates for a formal sum with one term with scalar `0`.
-/
theorem monom_coords_at_zero (x₀ x : X) : monomCoeff R X x₀ (0, x) = 0 := by
  rw [monomCoeff]
  cases x == x₀ <;> rfl


-- @@ L100-103 verbatim
/-- The coordinates for a formal sum. -/
def _root_.LeanPool.Polylean.FormalSum.coords : FormalSum R X → X → R
  | [], _ => 0
  | h :: t, x₀ => monomCoeff R X x₀ h + coords t x₀


-- @@ L105-111 verbatim
/-!

### Support of a formal sum

We next define the support of a formal sum and prove the property that coordinates vanish outside
the support.
-/


-- @@ L113-115 verbatim
/-- Support for a formal sum in a weak sense (coordinates may vanish on this). -/
def _root_.LeanPool.Polylean.FormalSum.support (s : FormalSum R X) : List X :=
  s.map <| fun (_, x) => x


-- @@ L117-117 verbatim
open FormalSum


-- @@ L119-140 verbatim
omit [DecidableEq R] in
/-- Support contains elements `x : X` where the coordinate is not `0`. -/
theorem nonzero_coord_in_support (s : FormalSum R X) :
    ∀ x : X, 0 ≠ s.coords x → x ∈ s.support :=
  match s with
  | [] => fun x hyp => by
    have d : coords [] x = (0 : R) := by
      rfl
    simp_all
  | h :: t => by
    intro x hyp
    let (a₀, x₀) := h
    have d : support ((a₀, x₀) :: t) = x₀ :: (support t) := by
      rfl
    rw [d]
    match p : x₀ == x with
    | true =>
      simp_all
    | false =>
      rw [coords, monomCoeff, p, zero_add] at hyp
      let step := nonzero_coord_in_support t x hyp
      simp_all


-- @@ L142-147 verbatim
/-!
### Equality of coordinates on a list

We define equality of coordinates on a list and prove that it is decidable and implied by equality
of formal sums.
-/


-- @@ L149-153 verbatim
/-- The condition of being equal on all elements is a given list -/
def equalOnList (l : List X) (f g : X → R) : Prop :=
  match l with
  | [] => true
  | h :: t => (f h = g h) ∧ (equalOnList t f g)


-- @@ L155-165 verbatim
omit [Ring R] [DecidableEq R] [DecidableEq X] in
/-- Equal functions are equal on arbitrary supports. -/
theorem equalOnList_of_equal (l : List X) (f g : X → R) :
    f = g → equalOnList l f g := by
  intro hyp
  induction l with
  | nil =>
    rw [equalOnList]
  | cons h t step =>
    rw [equalOnList]
    simp_all


-- @@ L167-182 verbatim
omit [Ring R] [DecidableEq R] [DecidableEq X] in
/-- Functions equal on support `l` are equal on each `x ∈ l`. -/
theorem eq_mem_of_equalOnList (l : List X) (f g : X → R) (x : X) (mhyp : x ∈ l) :
    equalOnList l f g → f x = g x :=
  match l with
  | [] => by
    contradiction
  | h :: t => by
    intro hyp
    simp only [equalOnList] at hyp
    cases mhyp
    · exact hyp.left
    · have inTail : x ∈ t := by
        assumption
      have step := eq_mem_of_equalOnList t f g x inTail hyp.right
      exact step


-- @@ L184-203 verbatim
/-- Decidability of equality on list. -/
@[reducible, instance] def decidableEqualOnList (l : List X) (f g : X → R) :
    Decidable (equalOnList l f g) :=
  match l with
  | [] =>
    Decidable.isTrue
      (by
        simp only [equalOnList])
  | h :: t => by
    simp only [equalOnList]
    cases (decidableEqualOnList t f g) with
    | isTrue hs =>
      exact
        (if c : f h = g h then (Decidable.isTrue ⟨c, hs⟩)
        else by
          apply Decidable.isFalse
          simp_all)
    | isFalse hs =>
      apply Decidable.isFalse
      simp_all



-- @@ L206-206 verbatim
/-! ### Combining coefficients -/


-- @@ L208-208 verbatim
namespace FormalSum


-- @@ L210-216 verbatim
/-- Add a monomial, combining its coefficient with the first matching basis term. -/
def addMonomial (term : R × X) : FormalSum R X → FormalSum R X
  | [] => if term.1 = 0 then [] else [term]
  | head :: tail =>
      if head.2 = term.2 then
        if head.1 + term.1 = 0 then tail else (head.1 + term.1, head.2) :: tail
      else head :: addMonomial term tail


-- @@ L218-240 verbatim
/-- Combining a monomial preserves its contribution to every coordinate. -/
theorem coords_addMonomial (term : R × X) (sum : FormalSum R X) (x : X) :
    (addMonomial term sum).coords x = monomCoeff R X x term + sum.coords x := by
  induction sum with
  | nil =>
      by_cases hzero : term.1 = 0
      · cases h : term.2 == x <;> simp [addMonomial, hzero, coords, monomCoeff, h]
      · simp [addMonomial, hzero, coords]
  | cons head tail ih =>
      by_cases hsame : head.2 = term.2
      · simp only [addMonomial, hsame, ite_true]
        by_cases hzero : head.1 + term.1 = 0
        · rw [ite_eq_left hzero]
          by_cases hx : term.2 = x
          · simp only [coords, monomCoeff, hsame, hx, beq_self_eq_true]
            rw [← add_assoc, add_comm term.1 head.1, hzero, zero_add]
          · simp [coords, monomCoeff, hsame, beq_false_of_ne hx]
        · rw [ite_eq_right hzero]
          by_cases hx : term.2 = x
          · simp only [coords, monomCoeff, hsame, hx, beq_self_eq_true]
            rw [add_comm head.1 term.1, add_assoc]
          · simp [coords, monomCoeff, hsame, beq_false_of_ne hx]
      · simp [addMonomial, hsame, coords, ih, add_left_comm]


-- @@ L242-245 verbatim
/-- Combine repeated basis terms and discard terms whose coefficients cancel. -/
def combineCoefficients : FormalSum R X → FormalSum R X
  | [] => []
  | term :: tail => addMonomial term (combineCoefficients tail)


-- @@ L247-252 verbatim
/-- Combining coefficients preserves every coordinate of a formal sum. -/
theorem coords_combineCoefficients (sum : FormalSum R X) (x : X) :
    sum.combineCoefficients.coords x = sum.coords x := by
  induction sum with
  | nil => rfl
  | cons term tail ih => simp [combineCoefficients, coords_addMonomial, ih, coords]


-- @@ L254-254 verbatim
end FormalSum


-- @@ L256-262 verbatim
/-!
## Quotient Free Module


* We define relation by having equal coordinates
* We show this is an equivalence relation and define the quotient
-/

-- @@ L263-265 verbatim
/-- Relation by equal coordinates. -/
def eqlCoords (R X : Type) [Ring R] [DecidableEq X] (s₁ s₂ : FormalSum R X) : Prop :=
  s₁.coords = s₂.coords


-- @@ L267-267 verbatim
namespace eqlCoords


-- @@ L269-273 verbatim
omit [DecidableEq R] in
/-- Relation by equal coordinates is reflexive. -/
theorem refl (s : FormalSum R X) : eqlCoords R X s s :=
  by
  rfl


-- @@ L275-277 verbatim
omit [DecidableEq R] in
/-- Relation by equal coordinates is  symmetric. -/
theorem symm {s₁ s₂ : FormalSum R X} : eqlCoords R X s₁ s₂ → eqlCoords R X s₂ s₁ := Eq.symm


-- @@ L279-282 verbatim
omit [DecidableEq R] in
/-- Relation by equal coordinates is transitive. -/
theorem trans {s₁ s₂ s₃ : FormalSum R X} :
    eqlCoords R X s₁ s₂ → eqlCoords R X s₂ s₃ → eqlCoords R X s₁ s₃ := Eq.trans


-- @@ L284-287 verbatim
omit [DecidableEq R] in
/-- Relation by equal coordinates is an equivalence relation. -/
theorem is_equivalence : Equivalence (eqlCoords R X) :=
  { refl := refl, symm := symm, trans := trans }


-- @@ L289-289 verbatim
end eqlCoords


-- @@ L291-295 verbatim
/-- Setoid based on equal coordinates. -/
instance formalSumSetoid (R X : Type) [Ring R] [DecidableEq X] [DecidableEq R] :
    Setoid (FormalSum R X) :=
  let _decidableEqR : DecidableEq R := inferInstance
  ⟨eqlCoords R X, eqlCoords.is_equivalence⟩


-- @@ L297-299 verbatim
/-- Quotient free module. -/
abbrev FreeModule (R X : Type) [Ring R] [DecidableEq X] [DecidableEq R] :=
  Quotient (formalSumSetoid R X)


-- @@ L301-302 verbatim
/-- Notation for the quotient free module over `R` generated by `G`. -/
notation R"["G"]" => FreeModule R G


-- @@ L304-312 verbatim
/-!
## Decidable equality on quotient free modules

We show that the free module `F[X]` has decidable equality. This has two steps:

* show decidable equality for images of formal sums.
* lift to quotient (by relating to formal sums).

We also show that the coordinate functions are defined on the quotient. -/




-- @@ L316-316 verbatim
namespace FreeModule


-- @@ L318-325 verbatim
/-- Equal combined formal sums represent equal free-module elements. -/
theorem quotient_eq_of_combineCoefficients_eq (left right : FormalSum R X)
    (h : left.combineCoefficients = right.combineCoefficients) :
    (⟦left⟧ : FreeModule R X) = ⟦right⟧ := by
  apply Quotient.sound
  funext x
  rw [← FormalSum.coords_combineCoefficients left x,
    ← FormalSum.coords_combineCoefficients right x, h]


-- @@ L327-347 expanded
/-- Equality on both supports gives equal quotients. -/
theorem eqlquot_of_equalOnList (s₁ s₂ : FormalSum R X)
    (ch₁ : equalOnList s₁.support s₁.coords s₂.coords)
    (ch₂ : equalOnList s₂.support s₁.coords s₂.coords) : @Eq (R[X]) ⟦s₁⟧ ⟦s₂⟧ :=
  by
  apply Quotient.sound
  apply funext
  intro x
  exact
    if h₁ : (0 = s₁.coords x) then
      if h₂ : (0 = s₂.coords x) then by rw [← h₁, h₂]
      else
        by
        have lem : x ∈ s₂.support := by
          apply nonzero_coord_in_support
          assumption
        exact eq_mem_of_equalOnList s₂.support s₁.coords s₂.coords x lem ch₂
    else
      by
      have lem : x ∈ s₁.support := by
        apply nonzero_coord_in_support
        assumption
      exact eq_mem_of_equalOnList s₁.support s₁.coords s₂.coords x lem ch₁


-- @@ L349-369 expanded
/-- Decidable equality for quotient elements in the free module -/
@[reducible, instance]
def decideEqualQuotient (s₁ s₂ : FormalSum R X) : Decidable (@Eq (R[X]) ⟦s₁⟧ ⟦s₂⟧) :=
  if ch₁ : equalOnList s₁.support s₁.coords s₂.coords then
    if ch₂ : equalOnList s₂.support s₁.coords s₂.coords then
      Decidable.isTrue (eqlquot_of_equalOnList s₁ s₂ ch₁ ch₂)
    else
      Decidable.isFalse
        (by
          intro contra
          let lem := equalOnList_of_equal s₂.support s₁.coords s₂.coords (Quotient.exact contra)
          contradiction)
  else
    Decidable.isFalse
      (by
        intro contra
        let lem := equalOnList_of_equal s₁.support s₁.coords s₂.coords (Quotient.exact contra)
        contradiction)


-- @@ L371-373 verbatim
/-!
### Lift to quotient
-/


-- @@ L375-377 verbatim
/-- Boolean equality on support. -/
def beqOnSupport (l : List X) (f g : X → R) : Bool :=
  l.all <| fun x => decide (f x = g x)


-- @@ L379-391 verbatim
omit [Ring R] [DecidableEq X] in
/-- Equality on support from boolean equality. -/
theorem eql_on_support_of_true {l : List X} {f g : X → R} :
    beqOnSupport l f g = true → equalOnList l f g := by
  intro hyp
  induction l with
  | nil =>
    simp only [equalOnList]
  | cons h t step =>
    simp only [equalOnList]
    simp only [beqOnSupport, List.all, Bool.and_eq_true, decide_eq_true_eq, List.all_eq_true] at hyp
    simp only [beqOnSupport, List.all_eq_true, decide_eq_true_eq] at step
    simp_all


-- @@ L393-397 expanded
/-- Boolean equality on support gives equal quotients. -/
theorem eqlquot_of_beq_support (s₁ s₂ : FormalSum R X)
    (c₁ : beqOnSupport s₁.support s₁.coords s₂.coords)
    (c₂ : beqOnSupport s₂.support s₁.coords s₂.coords) : @Eq (R[X]) ⟦s₁⟧ ⟦s₂⟧ :=
  eqlquot_of_equalOnList s₁ s₂ (eql_on_support_of_true c₁) (eql_on_support_of_true c₂)


-- @@ L400-409 expanded
/-- Boolean equality for the quotient via lifting
-/
def beqQuot : (x₁ x₂ : R[X]) → Bool :=
  by
  apply Quotient.lift₂ (fun (s₁ s₂ : FormalSum R X) => decide (@Eq (R[X]) ⟦s₁⟧ ⟦s₂⟧))
  intro a₁ b₁ a₂ b₂ eqv₁ eqv₂
  let eq₁ : Eq (α := R[X]) ⟦a₁⟧ ⟦a₂⟧ := Quot.sound eqv₁
  let eq₂ : Eq (α := R[X]) ⟦b₁⟧ ⟦b₂⟧ := Quot.sound eqv₂
  conv => lhs; congr; rw [eq₁, eq₂]


-- @@ L411-419 expanded
/-- Boolean equality for the quotient is equality.
-/
lemma eq_of_beq_true : ∀ x₁ x₂ : R[X], x₁.beqQuot x₂ = true → x₁ = x₂ :=
  by
  apply Quotient.ind₂ (motive := fun (x₁ x₂ : R[X]) => x₁.beqQuot x₂ = true → x₁ = x₂)
  intro s₁ s₂ eqv
  let eql := of_decide_eq_true eqv
  assumption


-- @@ L421-430 expanded
/-- Boolean inequality for the quotient is inequality.
-/
lemma neq_of_beq_false : ∀ x₁ x₂ : R[X], x₁.beqQuot x₂ = false → Not (x₁ = x₂) :=
  by
  apply Quotient.ind₂ (motive := fun (x₁ x₂ : R[X]) => x₁.beqQuot x₂ = false → Not (x₁ = x₂))
  intro s₁ s₂ neqv
  let neql := of_decide_eq_false neqv
  assumption


-- @@ L432-444 unexpanded
/--
Decidable equality for the free module.
-/
@[reducible, instance] def decEq (x₁ x₂ : R[X]) : Decidable (x₁ = x₂) := by
  match p : x₁.beqQuot x₂ with
  | true =>
    apply Decidable.isTrue
    apply FreeModule.eq_of_beq_true
    assumption
  | false =>
    apply Decidable.isFalse
    apply FreeModule.neq_of_beq_false
    assumption


-- @@ L446-448 verbatim
/-!
### Induced coordinates on the quotient.
-/


-- @@ L450-453 verbatim
/-- Coordinates are well defined on the quotient. -/
theorem equal_coords_of_approx (s₁ s₂ : FormalSum R X) :
    s₁ ≈ s₂ → s₁.coords = s₂.coords :=
  fun hyp => funext fun x₀ => congrFun hyp x₀


-- @@ L455-460 expanded
/-- coordinates for the quotient -/
def coordinates (x₀ : X) : R[X] → R :=
  by
  apply Quotient.lift (fun s : FormalSum R X => s.coords x₀)
  intro a b hyp
  let l := equal_coords_of_approx _ _ hyp
  exact congrFun l x₀


-- @@ L462-462 verbatim
end FreeModule


-- @@ L464-472 verbatim
/-!
## Module structure

We define the module structure on the quotient of the free module by the equivalence relation.

* We define scalar multiplication and addition on formal sums.
* We show that we have induced operations on the quotient.
* We show that the induced operations give a module structure on the quotient.
-/

-- @@ L473-473 verbatim
open FormalSum

-- @@ L474-474 verbatim
namespace FormalSum

-- @@ L475-477 verbatim
/-!
### Scalar multiplication: on formal sums and on the quotient.
-/


-- @@ L479-484 verbatim
/-- Scalar multiplication on formal sums. -/
def scmul : R → FormalSum R X → FormalSum R X
  | _, [] => []
  | r, (h :: t) =>
    let (a₀, x₀) := h
    (r * a₀, x₀) :: (scmul r t)


-- @@ L486-494 verbatim
omit [DecidableEq R] in
/-- Coordinates after scalar multiplication. -/
theorem scmul_coords (r : R) (s : FormalSum R X) (x₀ : X) :
    (r * s.coords x₀) = (s.scmul r).coords x₀ := by
  induction s with
  | nil =>
    simp only [coords, mul_zero, scmul]
  | cons h t ih =>
    simp only [coords, left_distrib, ih, scmul, monom_coords_mul]


-- @@ L496-510 expanded
/-- Scalar multiplication on the Free Module. -/
def _root_.LeanPool.Polylean.FreeModule.scmul : R → R[X] → R[X] :=
  by
  intro r
  let f : FormalSum R X → R[X] := fun s => ⟦s.scmul r⟧
  apply Quotient.lift f
  intro s₁ s₂
  simp only [f]
  intro hypeq
  apply Quotient.sound
  apply funext
  intro x₀
  have l₁ := scmul_coords r s₁ x₀
  have l₂ := scmul_coords r s₂ x₀
  rw [← l₁, ← l₂]
  rw [hypeq]


-- @@ L512-514 verbatim
/-!
### Addition: on formal sums and on the quotient.
-/


-- @@ L516-524 verbatim
omit [DecidableEq R] in
/-- Coordinates add when appending. -/
theorem append_coords (s₁ s₂ : FormalSum R X) (x₀ : X) :
    (s₁.coords x₀) + (s₂.coords x₀) = (s₁ ++ s₂).coords x₀ := by
  induction s₁ with
  | nil =>
    simp only [coords, zero_add, List.nil_append]
  | cons h t ih =>
    simp only [coords, add_assoc, List.cons_append, ← ih]


-- @@ L526-538 verbatim
/-- Coordinates well-defined up to equivalence. -/
theorem append_equiv (s₁ s₂ t₁ t₂ : FormalSum R X) :
    (s₁ ≈ s₂) → (t₁ ≈ t₂) → s₁ ++ t₁ ≈ s₂ ++ t₂ := by
    intro eqv₁ eqv₂
    apply funext
    intro x₀
    rw [← append_coords]
    rw [← append_coords]
    have ls : coords s₁ x₀ = coords s₂ x₀ := by
      apply congrFun eqv₁
    have lt : coords t₁ x₀ = coords t₂ x₀ := by
      apply congrFun eqv₂
    rw [← ls, ← lt]


-- @@ L540-540 verbatim
end FormalSum


-- @@ L542-555 expanded
/-- Addition of elements in the free module. -/
def _root_.LeanPool.Polylean.FreeModule.add : R[X] → R[X] → R[X] :=
  by
  let f : FormalSum R X → FormalSum R X → R[X] := fun s₁ s₂ => ⟦s₁ ++ s₂⟧
  apply Quotient.lift₂ f
  intro a₁ b₁ a₂ b₂
  simp only [f]
  intro eq₁ eq₂
  apply Quotient.sound
  apply funext
  intro x₀
  have l₁ := append_coords a₁ b₁ x₀
  have l₂ := append_coords a₂ b₂ x₀
  rw [← l₁, ← l₂]
  rw [eq₁, eq₂]


-- @@ L557-558 expanded
instance : Add (R[X]) :=
  ⟨FreeModule.add⟩


-- @@ L560-561 expanded
instance : HSMul R (R[X]) (R[X]) :=
  ⟨FreeModule.scmul⟩


-- @@ L562-562 verbatim
namespace FormalSum


-- @@ L564-566 verbatim
/-!
### Properties of operations on formal sums.
-/


-- @@ L568-575 verbatim
omit [DecidableEq R] [DecidableEq X] in
/-- Associativity for scalar multiplication for formal sums. -/
theorem action (a b : R) (s : FormalSum R X) : (s.scmul b).scmul a = s.scmul (a * b) := by
  induction s with
  | nil =>
    simp only [scmul]
  | cons h t ih =>
    simp only [scmul, ih, mul_assoc]


-- @@ L577-600 verbatim
/-- Distributivity for the module operations. -/
theorem act_sum (a b : R) (s : FormalSum R X) : (s.scmul a) ++ (s.scmul b) ≈ s.scmul (a + b) := by
  induction s with
  | nil =>
    simp only [scmul, List.append_nil]
    apply eqlCoords.refl
  | cons h t ih =>
    apply funext; intro x₀
    let il₁ := congrFun ih x₀
    rw [← append_coords]
    simp only [scmul, coords, right_distrib, monom_coords_hom]
    rw [← append_coords] at il₁
    rw [← il₁]
    conv =>
      lhs
      rw [add_assoc]
      arg 2
      rw [← add_assoc]
      arg 1
      rw [add_comm]
    conv =>
      lhs
      rw [add_assoc]
      rw [← add_assoc]



-- @@ L603-603 verbatim
end FormalSum


-- @@ L605-605 verbatim
namespace FreeModule


-- @@ L607-609 verbatim
/-!
### Module properties for the free module.
-/


-- @@ L611-617 unexpanded
/-- Associativity for scalar and ring products. -/
theorem module_action (a b : R) (x : R[X]) : a • (b • x) = (a * b) • x := by
  apply @Quotient.ind (motive := fun x : R[X] => a • (b • x) = (a * b) • x)
  intro s
  apply Quotient.sound
  rw [FormalSum.action]
  apply eqlCoords.refl


-- @@ L619-629 unexpanded
/-- Commutativity of addition. -/
theorem addn_comm (x₁ x₂ : R[X]) : x₁ + x₂ = x₂ + x₁ := by
  apply @Quotient.ind₂ (motive := fun x₁ x₂ : R[X] => x₁ + x₂ = x₂ + x₁)
  intro s₁ s₂
  apply Quotient.sound
  apply funext
  intro x₀
  let lm₁ := append_coords s₁ s₂ x₀
  let lm₂ := append_coords s₂ s₁ x₀
  rw [← lm₁, ← lm₂]
  simp only [add_comm]


-- @@ L631-638 unexpanded
theorem add_assoc_aux (s₁ : FormalSum R X) (x₂ x₃ : R[X]) :
    (⟦s₁⟧ + x₂) + x₃ = ⟦s₁⟧ + (x₂ + x₃) := by
  apply @Quotient.ind₂
    (motive := fun x₂ x₃ : R[X] => (⟦s₁⟧ + x₂) + x₃ = ⟦s₁⟧ + (x₂ + x₃))
  intro x₂ x₃
  apply Quotient.sound
  apply funext
  simp_all


-- @@ L640-644 unexpanded
/-- Associativity of addition. -/
theorem addn_assoc (x₁ x₂ x₃ : R[X]) : (x₁ + x₂) + x₃ = x₁ + (x₂ + x₃) := by
  apply @Quotient.ind (motive := fun x₁ : R[X] => (x₁ + x₂) + x₃ = x₁ + (x₂ + x₃))
  intro x₁
  apply add_assoc_aux


-- @@ L646-647 expanded
/-- The zero element of the free module. -/
def zero : R[X] :=
  ⟦[]⟧


-- @@ L649-655 unexpanded
/-- adding zero -/
theorem addn_zero (x : R[X]) : x + zero = x := by
  apply @Quotient.ind (motive := fun x : R[X] => x + zero = x)
  intro x
  apply Quotient.sound
  apply funext
  simp_all


-- @@ L657-663 unexpanded
/-- adding zero -/
theorem zero_addn (x : R[X]) : zero + x = x := by
  apply @Quotient.ind (motive := fun x : R[X] => zero + x = x)
  intro x
  apply Quotient.sound
  apply funext
  simp_all


-- @@ L665-679 unexpanded
/-- Distributivity for addition of module elements. -/
theorem elem_distrib (a : R) (x₁ x₂ : R[X]) :
    a • (x₁ + x₂) = a • x₁ + a • x₂ := by
  apply @Quotient.ind₂
    (motive := fun x₁ x₂ : R[X] => a • (x₁ + x₂) = a • x₁ + a • x₂)
  intro s₁ s₂
  apply Quotient.sound
  apply funext
  intro x₀
  rw [← scmul_coords]
  rw [← append_coords]
  rw [← append_coords]
  rw [← scmul_coords]
  rw [← scmul_coords]
  simp only [left_distrib]


-- @@ L681-691 unexpanded
/-- Distributivity with respect to scalars. -/
theorem coeffs_distrib (a b : R) (x : R[X]) : a • x + b • x = (a + b) • x := by
  apply @Quotient.ind (motive := fun x : R[X] =>
    a • x + b • x = (a + b) • x)
  intro s
  apply Quotient.sound
  apply funext
  intro x₀
  let l := act_sum a b s
  let l'' := congrFun l x₀
  exact l''


-- @@ L693-703 unexpanded
/-- Multiplication by `1 : R`. -/
theorem unit_coeffs (x : R[X]) : (1 : R) • x = x := by
  apply @Quotient.ind (motive := fun x : R[X] =>
    (1 : R) • x = x)
  intro s
  apply Quotient.sound
  apply funext
  intro x₀
  let l := scmul_coords 1 s x₀
  rw [← l]
  simp only [one_mul]


-- @@ L705-715 unexpanded
/-- Multiplication by `0 : R`. -/
theorem zero_coeffs (x : R[X]) : (0 : R) • x = ⟦ [] ⟧ := by
  apply @Quotient.ind (motive := fun x : R[X] =>
    (0 : R) • x = ⟦ [] ⟧)
  intro s
  apply Quotient.sound
  apply funext
  intro x₀
  let l := scmul_coords 0 s x₀
  rw [← l]
  simp only [zero_mul, coords]


-- @@ L717-718 expanded
instance : Zero (R[X]) :=
  ⟨FreeModule.zero⟩


-- @@ L720-721 expanded
instance : Neg (R[X]) :=
  ⟨fun x => (-1 : R) • x⟩


-- @@ L723-746 expanded
/-- The module is an additive commutative group, mainly proved as a check -/
instance : AddCommGroup (R[X]) :=
  { zero := _
    add := FreeModule.add
    add_assoc := FreeModule.addn_assoc
    add_zero := FreeModule.addn_zero
    zero_add := FreeModule.zero_addn
    neg := fun x => (-1 : R) • x
    nsmul := nsmulRec
    zsmul := zsmulRec
    sub_eq_add_neg := by intros; rfl
    neg_add_cancel := by
      intro x
      let l := FreeModule.coeffs_distrib (-1 : R) (1 : R) x
      simp only [neg_add_cancel] at l
      rw [FreeModule.unit_coeffs] at l
      rw [FreeModule.zero_coeffs] at l
      exact l
    add_comm := FreeModule.addn_comm }


-- @@ L748-748 verbatim
end FreeModule


-- @@ L750-760 verbatim
/-!
## Equivalent definition of the relation via moves

For conceptual results such as the universal property (needed for the group ring structure) it is
useful to define the relation on the free module in terms of moves. We do this, and show that
this is the same as the relation defined by equality of coordinates.

* We define elementary moves on formal sums
* We show coordinates equal if and only if related by elementary moves
* Hence can define map on Free Module when invariant under elementary moves
  -/


-- @@ L762-762 verbatim
open FormalSum

-- @@ L763-773 verbatim
/-- Elementary moves for formal sums. -/
inductive ElementaryMove (R X : Type) [Ring R] [DecidableEq R] [DecidableEq X] :
    FormalSum R X → FormalSum R X → Prop where
  | zeroCoeff (tail : FormalSum R X) (x : X) (a : R) (h : a = 0) :
    ElementaryMove R X ((a, x) :: tail) tail
  | addCoeffs (a b : R) (x : X) (tail : FormalSum R X) :
    ElementaryMove R X ((a, x) :: (b, x) :: tail) ((a + b, x) :: tail)
  | cons (a : R) (x : X) (s₁ s₂ : FormalSum R X) :
    ElementaryMove R X s₁ s₂ → ElementaryMove R X ((a, x) :: s₁) ((a, x) :: s₂)
  | swap (a₁ a₂ : R) (x₁ x₂ : X) (tail : FormalSum R X) :
    ElementaryMove R X ((a₁, x₁) :: (a₂, x₂) :: tail) ((a₂, x₂) :: (a₁, x₁) :: tail)


-- @@ L775-777 verbatim
/-- Free module quotient using elementary moves on formal sums. -/
def FreeModuleAux (R X : Type) [Ring R] [DecidableEq R] [DecidableEq X] :=
  Quot (ElementaryMove R X)


-- @@ L779-779 verbatim
namespace FormalSum


-- @@ L781-783 verbatim
/-- Image in the quotient (i.e., actual, not formal, sum). -/
def sum (s : FormalSum R X) : FreeModuleAux R X :=
  Quot.mk (ElementaryMove R X) s


-- @@ L785-787 verbatim
/-- Equivalence by having the same image. -/
def equiv (s₁ s₂ : FormalSum R X) : Prop :=
  s₁.sum = s₂.sum


-- @@ L789-790 verbatim
/-- Infix notation for equivalence by elementary moves. -/
infix: 65 " ≃ " => FormalSum.equiv


-- @@ L792-794 verbatim
/-!
### Invariance of coordinates under elementary moves
-/


-- @@ L796-807 verbatim
/-- Coordinates are invariant under moves. -/
theorem coords_move_invariant (x₀ : X) (s₁ s₂ : FormalSum R X)
    (h : ElementaryMove R X s₁ s₂) : coords s₁ x₀ = coords s₂ x₀ := by
  induction h with
  | zeroCoeff tail x a hyp =>
    simp only [coords, hyp, monom_coords_at_zero, zero_add]
  | addCoeffs a b x tail =>
    simp only [coords, ← add_assoc, monom_coords_hom]
  | cons a x s₁ s₂ _ step =>
    simp only [coords, step]
  | swap a₁ a₂ x₁ x₂ tail =>
    simp only [coords, ← add_assoc, add_comm]


-- @@ L809-809 verbatim
end FormalSum


-- @@ L811-813 verbatim
/-- Coordinates on the quotients. -/
def _root_.LeanPool.Polylean.FreeModuleAux.coeff (x₀ : X) : FreeModuleAux R X → R :=
  Quot.lift (fun s => s.coords x₀) (coords_move_invariant x₀)


-- @@ L815-815 verbatim
namespace FormalSum


-- @@ L817-821 verbatim
/-- Commutative diagram for coordinates. -/
theorem coeff_factors (x : X) (s : FormalSum R X) : FreeModuleAux.coeff x (sum s) = s.coords x := by
  simp only [FreeModuleAux.coeff]
  apply @Quot.liftBeta (r := ElementaryMove R X) (f := fun s => s.coords x)
  apply coords_move_invariant


-- @@ L823-827 expanded
/-- Coordinates well-defined under the equivalence generated by moves. -/
theorem coords_well_defined (x : X) (s₁ s₂ : FormalSum R X) : s₁ ≃ s₂ → s₁.coords x = s₂.coords x :=
  by
  intro hyp
  rw [← coeff_factors x s₂, ← coeff_factors x s₁, hyp]


-- @@ L829-831 verbatim
/-!
### Equal coordinates implies related by elementary moves.
-/


-- @@ L833-848 expanded
/-- Cons respects equivalence. -/
theorem cons_equiv_of_equiv (s₁ s₂ : FormalSum R X) (a : R) (x : X) :
    s₁ ≃ s₂ → (a, x) :: s₁ ≃ (a, x) :: s₂ := by
  intro h
  let f : FormalSum R X → FreeModuleAux R X := fun s => sum <| (a, x) :: s
  let wit : (s₁ s₂ : FormalSum R X) → (ElementaryMove R X s₁ s₂) → f s₁ = f s₂ :=
    by
    intro s₁ s₂ hyp
    apply Quot.sound
    apply ElementaryMove.cons
    assumption
  let g := Quot.lift f wit
  let factorizes : (s : FormalSum R X) → g (s.sum) = sum ((a, x) :: s) := Quot.liftBeta f wit
  rw [equiv]
  rw [← factorizes]
  rw [← factorizes]
  rw [h]


-- @@ L850-913 expanded
/-- If a coordinate `x` for a formal sum `s` is non-zero, `s` is related by moves to a formal sum
with first term `x` with coefficient its coordinates, and the rest shorter than `s`. -/
theorem nonzero_coeff_has_complement (x₀ : X) (s : FormalSum R X) :
    0 ≠ s.coords x₀ →
      (∃ ys : FormalSum R X, (((s.coords x₀, x₀) :: ys) ≃ s) ∧ (List.length ys < s.length)) :=
  by
  induction s with
  | nil =>
    intro contra
    contradiction
  | cons head tail hyp =>
    let (a, x) := head
    intro pos
    cases c : x == x₀ with
    | true =>
      let k := FormalSum.coords tail x₀
      have lem : a + k = coords ((a, x) :: tail) x₀ := by rw [coords, monomCoeff, c]
      have c'' : x = x₀ := of_decide_eq_true c
      rw [c'']
      rw [c''] at lem
      exact
        if c' : (0 = k) then
          by
          have lIneq : tail.length < List.length ((a, x) :: tail) := by
            simp only [List.length_cons, Nat.lt_add_one]
          rw [← c', add_zero] at lem
          rw [← lem]
          exact ⟨tail, rfl, lIneq⟩
        else by
          let ⟨ys, eqnStep, lIneqStep⟩ := hyp c'
          have eqn₁ : (a, x₀) :: (k, x₀) :: ys ≃ (a + k, x₀) :: ys :=
            by
            apply Quot.sound
            apply ElementaryMove.addCoeffs
          have eqn₂ : (a, x₀) :: (k, x₀) :: ys ≃ (a, x₀) :: tail :=
            by
            apply cons_equiv_of_equiv
            assumption
          have eqn : (a + k, x₀) :: ys ≃ (a, x₀) :: tail := Eq.trans (Eq.symm eqn₁) eqn₂
          rw [← lem]
          have lIneq : ys.length < List.length ((a, x₀) :: tail) :=
            by
            apply Nat.le_trans lIneqStep
            simp only [List.length_cons, Nat.le_succ]
          exact ⟨ys, eqn, lIneq⟩
    | false =>
      let k := coords tail x₀
      have lem : k = coords ((a, x) :: tail) x₀ := by simp only [coords, monomCoeff, c, zero_add, k]
      rw [← lem] at pos
      let ⟨ys', eqnStep, lIneqStep⟩ := hyp pos
      rw [← lem]
      let ys := (a, x) :: ys'
      have lIneq : ys.length < ((a, x) :: tail).length :=
        by
        simp only [List.length_cons]
        apply Nat.succ_lt_succ
        exact lIneqStep
      have eqn₁ : (k, x₀) :: ys ≃ (a, x) :: (k, x₀) :: ys' :=
        by
        apply Quot.sound
        apply ElementaryMove.swap
      have eqn₂ : (a, x) :: (k, x₀) :: ys' ≃ (a, x) :: tail :=
        by
        apply cons_equiv_of_equiv
        assumption
      have eqn : (k, x₀) :: ys ≃ (a, x) :: tail := by exact Eq.trans eqn₁ eqn₂
      exact ⟨ys, eqn, lIneq⟩


-- @@ L915-994 expanded
/-- If all coordinates are zero, then moves relate to the empty sum. -/
theorem equiv_e_of_zero_coeffs (s : FormalSum R X) (hyp : ∀ x : X, s.coords x = 0) : s ≃ [] :=
  match mt : s with
  | [] => rfl
  | h :: t => by
    let (a₀, x₀) := h
    let hyp₀ := hyp x₀
    rw [coords] at hyp₀
    have c₀ : monomCoeff R X x₀ (a₀, x₀) = a₀ := by simp only [monomCoeff, BEq.rfl]
    rw [c₀] at hyp₀
    exact
      if hz : a₀ = 0 then by
        rw [hz] at hyp₀
        rw [zero_add] at hyp₀
        have tail_coeffs : ∀ x : X, coords t x = 0 :=
          by
          intro x
          exact
            if c : (x₀ = x) then by simp_all
            else by
              let hx := hyp x
              simp only [coords, monomCoeff] at hx
              have lf : (x₀ == x) = false := decide_eq_false c
              rw [lf] at hx
              simp_all
        have _ : t.length < (h :: t).length := by simp only [List.length_cons, Nat.lt_add_one]
        let step : t ≃ [] := by
          apply equiv_e_of_zero_coeffs
          exact tail_coeffs
        rw [hz]
        have ls : (0, x₀) :: t ≃ t := by
          apply Quot.sound
          apply ElementaryMove.zeroCoeff
          rfl
        exact Eq.trans ls step
      else
        by
        have non_zero : 0 ≠ coords t x₀ := by
          intro contra'
          simp_all
        let ⟨ys, eqnStep, lIneqStep⟩ := nonzero_coeff_has_complement x₀ t non_zero
        have tail_coeffs : ∀ x : X, coords ys x = 0 :=
          by
          intro x
          exact
            if c : (x₀ = x) then by
              rw [← c]
              let ceq := coords_well_defined x₀ _ _ eqnStep
              simp only [coords, monomCoeff, BEq.rfl, add_eq_left] at ceq
              assumption
            else by
              let hx := hyp x
              simp only [coords, monomCoeff] at hx
              have lf : (x₀ == x) = false := decide_eq_false c
              rw [lf] at hx
              simp only [zero_add] at hx
              let ceq := coords_well_defined x _ _ eqnStep
              simp only [coords, monomCoeff, lf, zero_add] at ceq
              simp_all
        have _ : ys.length < (h :: t).length :=
          by
          simp only [List.length_cons]
          apply Nat.le_trans lIneqStep
          apply Nat.le_succ
        let step : ys ≃ [] := by
          apply equiv_e_of_zero_coeffs
          exact tail_coeffs
        let eqn₁ := cons_equiv_of_equiv _ _ (coords t x₀) x₀ step
        let eqn₂ : t ≃ (coords t x₀, x₀) :: [] := Eq.trans (Eq.symm eqnStep) eqn₁
        let eqn₃ := cons_equiv_of_equiv _ _ a₀ x₀ eqn₂
        apply Eq.trans eqn₃
        have eqn₄ : sum [(a₀, x₀), (coords t x₀, x₀)] = sum [(a₀ + coords t x₀, x₀)] :=
          by
          apply Quot.sound
          apply ElementaryMove.addCoeffs
        apply Eq.trans eqn₄
        rw [hyp₀]
        apply Quot.sound
        apply ElementaryMove.zeroCoeff
        rfl
termination_by s.length


-- @@ L996-1068 expanded
/-- If coordinates are equal, the sums are related by moves. -/
theorem equiv_of_equal_coeffs (s₁ s₂ : FormalSum R X) (hyp : ∀ x : X, s₁.coords x = s₂.coords x) :
    s₁ ≃ s₂ :=
  match s₁ with
  | [] =>
    have coeffs : ∀ x : X, s₂.coords x = 0 := by
      intro x
      let h := hyp x
      rw [← h]
      rfl
    let zl := equiv_e_of_zero_coeffs s₂ coeffs
    Eq.symm zl
  | (a₀, x₀) :: t => by
    exact
      if p : 0 = a₀ then
        by
        have eq₁ : (a₀, x₀) :: t ≃ t := by
          apply Quot.sound
          apply ElementaryMove.zeroCoeff
          simp_all
        have _ : t.length < ((a₀, x₀) :: t).length := by
          simp only [List.length_cons, Nat.lt_add_one]
        have eq₂ : t ≃ s₂ := by
          apply equiv_of_equal_coeffs t s₂
          intro x
          let ceq := coords_well_defined x ((a₀, x₀) :: t) t eq₁
          simp only [← ceq, hyp]
        exact Eq.trans eq₁ eq₂
      else by
        let a₁ := coords t x₀
        exact
          if p₁ : 0 = a₁ then
            by
            have cf₂ : s₂.coords x₀ = a₀ := by
              rw [← hyp]
              simpa only [coords, monomCoeff, BEq.rfl, add_eq_left] using Eq.symm p₁
            let ⟨ys, eqn, _⟩ := nonzero_coeff_has_complement x₀ s₂ (by simp_all)
            let cfs := fun x => coords_well_defined x _ _ eqn
            rw [cf₂] at cfs
            let cfs' := fun (x : X) => Eq.trans (hyp x) (Eq.symm (cfs x))
            simp only [coords, add_right_inj] at cfs'
            have _ : t.length < ((a₀, x₀) :: t).length := by
              simp only [List.length_cons, Nat.lt_add_one]
            let step := equiv_of_equal_coeffs t ys cfs'
            let _step' := cons_equiv_of_equiv t ys a₀ x₀ step
            rw [cf₂] at eqn
            exact Eq.trans _step' eqn
          else by
            let ⟨ys, eqn, ineqn⟩ := nonzero_coeff_has_complement x₀ t p₁
            let s₃ := (a₀ + a₁, x₀) :: ys
            have eq₁ : (a₀, x₀) :: (a₁, x₀) :: ys ≃ s₃ :=
              by
              apply Quot.sound
              let lem := ElementaryMove.addCoeffs a₀ a₁ x₀ ys
              exact lem
            have eq₂ : (a₀, x₀) :: (a₁, x₀) :: ys ≃ (a₀, x₀) :: t :=
              by
              apply cons_equiv_of_equiv
              assumption
            have eq₃ : s₃ ≃ s₂ :=
              by
              have _ : ys.length + 1 < t.length + 1 := by simp_all
              apply equiv_of_equal_coeffs
              intro x
              rw [← hyp x]
              simp only [coords, s₃]
              let d := coords_well_defined x _ _ eqn
              rw [coords] at d
              rw [← d]
              simp only [monom_coords_hom]
              rw [add_assoc]
            apply Eq.trans (Eq.trans (Eq.symm eq₂) eq₁) eq₃
termination_by s₁.length


-- @@ L1069-1071 verbatim
/-!
## Functions invariant under moves pass to the quotient.
-/

-- @@ L1072-1088 verbatim
/-- Lifting functions to the move induced quotient. -/
theorem func_eql_of_move_equiv {β : Sort u} (f : FormalSum R X → β) :
    (∀ s₁ s₂ : FormalSum R X, ElementaryMove R X s₁ s₂ → f s₁ = f s₂) →
      (∀ s₁ s₂ : FormalSum R X, s₁ ≈ s₂ → f s₁ = f s₂) :=
  by
  intro hyp
  let fbar : FreeModuleAux R X → β := Quot.lift f hyp
  let fct : ∀ s : FormalSum R X, f s = fbar (sum s) := by
    apply Quot.liftBeta
    apply hyp
  intro s₁ s₂ sim
  have ec : eqlCoords R X s₁ s₂ := sim
  rw [eqlCoords] at ec
  have pullback : sum s₁ = sum s₂ := by
    apply equiv_of_equal_coeffs
    simp_all
  simp only [fct, pullback]


-- @@ L1090-1090 verbatim
end FormalSum


-- @@ L1092-1102 verbatim
/-!
## Injectivity of inclusions

We show that, under appropriate hypotheses, two inclusions into Free Modules are injective.

* If `a : R` is nonzero, then `x : X ↦ ⟦[(a, x)]⟧` is injective.
* If `x: X`, then `a : R ↦ ⟦[(a, x)]⟧` is injective.

These are used in proving injectivity results for related functions on group rings, which act as a
check on the correctness of the definitions.
-/

-- @@ L1103-1103 verbatim
open FormalSum


-- @@ L1105-1122 expanded
omit [DecidableEq R] in
/-- For `a : R` and `a ≠ 0`, injectivity of the function `x : X ↦ [(a, x)]` up to
equivalence. -/
theorem monom_elem_eq_of_coord_eq_nonzero (a : R) (non_zero : a ≠ 0) (x₀ x₁ : X) :
    coords [(a, x₀)] = coords [(a, x₁)] → x₀ = x₁ :=
  by
  intro hyp
  have sup₀ : support [(a, x₀)] = [x₀] := by rfl
  have c₁ : coords [(a, x₁)] x₁ = a := by simp only [coords, monomCoeff, BEq.rfl, add_zero]
  rw [← c₁] at non_zero
  symm at non_zero
  rw [← hyp] at non_zero
  let lem := nonzero_coord_in_support [(a, x₀)] x₁ non_zero
  have lem' : x₁ = x₀ := by
    simpa only [support, List.map_cons, List.map_nil, List.mem_cons, List.not_mem_nil,
      or_false] using lem
  exact Eq.symm lem'


-- @@ L1124-1131 expanded
omit [DecidableEq R] in
/-- For `x : X`, injectivity of the function `a : R ↦ [(a, x)]` up to equivalence. -/
theorem monom_coeff_eq_of_coord_eq (x : X) (a₀ a₁ : R) :
    coords [(a₀, x)] = coords [(a₁, x)] → a₀ = a₁ :=
  by
  intro hyp
  let h₁ := congrFun hyp x
  simp only [coords, monomCoeff, BEq.rfl, add_zero] at h₁
  assumption


-- @@ L1134-1136 expanded
/-- For `x: X`, the functions `a : R ↦ ⟦[(a, x)]⟧` -/
def coeffInclusion (x₀ : X) : R → R[X] := fun a₀ => ⟦[(a₀, x₀)]⟧


-- @@ L1138-1145 verbatim
/-- Injectivity of `coeffInclusion` -/
theorem coeffInclusion_injective (x₀ : X)
 (a₀ a₁ : R) : coeffInclusion x₀ a₀ =
                coeffInclusion x₀ a₁ → a₀ = a₁ := by
  intro hyp
  simp only [coeffInclusion] at hyp
  rw [Quotient.eq] at hyp
  exact monom_coeff_eq_of_coord_eq x₀ a₀ a₁ hyp


-- @@ L1147-1149 expanded
/-- For `a: A`, the function `x: X ↦ ⟦[(a, x)]⟧` -/
def baseInclusion (a₀ : R) : X → R[X] := fun x₀ => ⟦[(a₀, x₀)]⟧


-- @@ L1151-1158 verbatim
/-- Injectivity of `baseInclusion a` give `a ≠0` -/
theorem baseInclusion_injective (a₀ : R) (non_zero : a₀ ≠ 0)
 (x₀ x₁ : X) : baseInclusion a₀ x₀ =
                baseInclusion a₀ x₁ → x₀ = x₁ := by
  intro hyp
  simp only [baseInclusion] at hyp
  rw [Quotient.eq] at hyp
  exact monom_elem_eq_of_coord_eq_nonzero a₀ non_zero x₀ x₁ hyp

-- @@ L1159-1165 verbatim
/-!
## Basic `Repr`

An instance of `Repr` on Free Modules, mainly for debugging (fairly crude). This is implemented
by constructing a norm ball containing all the non-zero coordinates, and then making a list of
non-zero coordinates.
-/


-- @@ L1167-1167 verbatim
theorem fst_le_max (a b : Nat) : a ≤ max a b := Nat.le_max_left a b



-- @@ L1170-1170 verbatim
theorem snd_le_max (a b : Nat) : b ≤ max a b := Nat.le_max_right a b



-- @@ L1173-1173 verbatim
theorem eq_fst_or_snd_of_max (a b : Nat) : (max a b = a) ∨ (max a b = b) := by omega


-- @@ L1175-1183 verbatim
/-- The successor of the largest norm with nonzero coordinate on a support list. -/
def maxNormSuccOnSupp (norm : X → Nat) (crds : X → R) (s : List X) : Nat :=
  match s with
  | [] => 0
  | head :: tail =>
      if crds head ≠ 0 then
        max (norm head + 1) (maxNormSuccOnSupp norm crds tail)
      else
        maxNormSuccOnSupp norm crds tail


-- @@ L1185-1209 verbatim
omit [DecidableEq X] in
theorem max_in_support (norm : X → Nat) (crds : X → R) (s : List X) :
    maxNormSuccOnSupp norm crds s > 0 →
      ∃ x : X, crds x ≠ 0 ∧ maxNormSuccOnSupp norm crds s = norm x + 1 := by
  intro h
  induction s with
  | nil =>
    simp only [maxNormSuccOnSupp, gt_iff_lt, Nat.lt_irrefl] at h
  | cons head tail ih =>
    exact if c : crds head = 0 then
      by
        simp only [ne_eq, maxNormSuccOnSupp, c, not_true_eq_false, ↓reduceIte]
        simp only [maxNormSuccOnSupp, c, ne_eq, not_true_eq_false, ↓reduceIte, gt_iff_lt] at h
        exact ih h
    else by
        simp only [ne_eq, maxNormSuccOnSupp, c, not_false_eq_true, ↓reduceIte]
        simp only [maxNormSuccOnSupp, ne_eq, c, not_false_eq_true, ↓reduceIte, gt_iff_lt] at h
        let sl := eq_fst_or_snd_of_max (norm head + 1) (maxNormSuccOnSupp norm crds tail)
        cases sl
        case inr p =>
            simp_all
        case inl p =>
            rw [p]
            rw [p] at h
            exact ⟨head, And.intro c rfl⟩


-- @@ L1211-1230 verbatim
omit [DecidableEq X] in
theorem supp_below_max (norm : X → Nat) (crds : X → R) (s : List X) :
    (x : X) → x ∈ s → crds x ≠ 0 → norm x + 1 ≤ maxNormSuccOnSupp norm crds s := by
    intro x h₁ h₂
    cases h₁
    case head as =>
      rw [maxNormSuccOnSupp]
      simp only [ne_eq, h₂, not_false_eq_true, ↓reduceIte]
      apply fst_le_max
    case tail a as th =>
      rw [maxNormSuccOnSupp]
      let l := supp_below_max norm crds as x th h₂
      exact if c : crds a ≠ 0 then
        by
        simp only [ne_eq, c, not_false_eq_true, ↓reduceIte, ge_iff_le]
        apply Nat.le_trans l
        apply snd_le_max
      else
        by
        simpa only [c, ↓reduceIte, ge_iff_le] using l


-- @@ L1232-1240 verbatim
omit [DecidableEq X] in
theorem supp_zero_of_max_zero (norm : X → Nat) (crds : X → R) (s : List X) :
    maxNormSuccOnSupp norm crds s = 0 →
      (x : X) → x ∈ s → crds x = 0 := fun hyp x hm =>
      if c : crds x = 0 then c
      else by
        let l := supp_below_max norm crds s x hm c
        rw [hyp] at l
        contradiction


-- @@ L1242-1244 verbatim
/-- The successor of the largest norm with nonzero coefficient in a formal sum. -/
def _root_.LeanPool.Polylean.FormalSum.normSucc (norm : X → Nat) (s : FormalSum R X) : Nat :=
      maxNormSuccOnSupp norm s.coords (s.support)


-- @@ L1246-1246 verbatim
open FormalSum

-- @@ L1247-1264 verbatim
theorem normsucc_le (norm : X → Nat) (s₁ s₂ : FormalSum R X) (eql : s₁ ≈ s₂) :
    s₁.normSucc norm ≤ s₂.normSucc norm :=
      if c : s₁.normSucc norm = 0 then
      by
        simp_all
      else by
        simp only [normSucc]
        simp only [normSucc] at c
        let c' : maxNormSuccOnSupp norm (coords s₁) (support s₁) > 0 := Nat.pos_of_ne_zero c
        let l := max_in_support norm s₁.coords s₁.support c'
        let ⟨x₀, p⟩ := l
        let nonzr' := p.left
        let l := congrFun eql x₀
        rw [l] at nonzr'
        let nonzr : 0 ≠ s₂.coords x₀ := Ne.symm nonzr'
        let in_supp := nonzero_coord_in_support s₂ x₀ nonzr
        rw [p.right]
        apply supp_below_max norm s₂.coords s₂.support x₀ in_supp nonzr'


-- @@ L1266-1273 verbatim
theorem norm_succ_eq (norm : X → Nat) (s₁ s₂ : FormalSum R X) (eql : s₁ ≈ s₂) :
    s₁.normSucc norm = s₂.normSucc norm := by
      apply Nat.le_antisymm
      · apply normsucc_le
        assumption
      · apply normsucc_le
        apply eqlCoords.symm
        assumption


-- @@ L1275-1280 verbatim
/-- Finite exhaustive approximations to a type, organized by a norm. -/
class NormCube (α : Type) where
  /-- A size function on elements. -/
  norm : α → Nat
  /-- Elements whose norm is bounded by a given natural number. -/
  cube : Nat → List α


-- @@ L1282-1283 verbatim
/-- The finite cube at radius `k`. -/
def normCube (α : Type) [nc : NormCube α] (k : Nat) := nc.cube k


-- @@ L1285-1285 verbatim
instance natCube : NormCube Nat := ⟨id, fun n => (List.range n).reverse⟩


-- @@ L1287-1292 verbatim
instance finCube {k : Nat} : NormCube (Fin (Nat.succ k)) :=
    let i : Nat → Fin (Nat.succ k) := fun n => ⟨n % (Nat.succ k), by
          apply Nat.mod_lt
          apply Nat.zero_lt_succ
          ⟩
    ⟨fun j => j.val, fun n => (List.range (min (k + 1) n)).reverse.map i⟩



-- @@ L1295-1299 verbatim
instance intCube : NormCube ℤ where
  norm := Int.natAbs
  cube : Nat → List ℤ := fun n =>
      (List.range (n)).reverse.map (Int.ofNat) ++
      (List.range (n - 1)).map (Int.negSucc)


-- @@ L1301-1308 verbatim
instance prodCube {α β : Type} [na : NormCube α] [nb : NormCube β] : NormCube (α × β) where
  norm : (α × β) → Nat :=
    fun ⟨a, b⟩ => max (na.norm a) (nb.norm b)
  cube : Nat → List (α × β) :=
    fun n =>
      (na.cube n).flatMap (fun a =>
        (nb.cube n).map (fun b =>
          (a, b)))


-- @@ L1310-1313 unexpanded
/-- A norm bound for the support of a quotient free-module element. -/
def _root_.LeanPool.Polylean.FreeModule.normBound (x : R[X]) [nx : NormCube X] : Nat :=
  Quotient.lift (fun s : FormalSum R X => s.normSucc nx.norm)
    (fun s₁ s₂ eql => norm_succ_eq nx.norm s₁ s₂ eql) x


-- @@ L1315-1322 unexpanded
/-- The nonzero coefficients of a quotient free-module element in a bounded cube. -/
def _root_.LeanPool.Polylean.FreeModule.coeffList (x : R[X]) [nx : NormCube X] :
    List (R × X) :=
   (nx.cube (x.normBound)).filterMap fun x₀ =>
      let a := x.coordinates x₀
      if a = 0 then none else some (a, x₀)

-- basic repr

-- @@ L1323-1324 expanded
instance basicRepr [NormCube X] [Repr X] [Repr R] : Repr (R[X]) :=
  ⟨fun x _ => reprStr (x.coeffList)⟩


-- @@ L1326-1326 verbatim
end LeanPool.Polylean
