/-
Copyright (c) 2026 Matevz Miščič, Maša Žaucer, Job Petrovčič. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Matevz Miščič, Maša Žaucer, Job Petrovčič
-/
module

public import LeanPool.ArtinWedderburn.CornerCornerLemma
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Rat.Cast.Order
import Mathlib.Tactic.ContinuousFunctionalCalculus
import Mathlib.Tactic.NormNum.Abs
import Mathlib.Tactic.NormNum.DivMod
import Mathlib.Tactic.NormNum.OfScientific


-- @@ L16-21 verbatim
/-!
# Nice ideals and the induction step in Artin–Wedderburn

A *nice ideal* is an idempotent ideal whose corner ring is `OrtIdemDiv`. We
prove that in a prime artinian ring, every ideal is nice.
-/


-- @@ L23-23 verbatim
@[expose] public section


-- @@ L25-25 verbatim
namespace LeanPool.ArtinWedderburn


-- @@ L27-27 verbatim
variable {R : Type*} [Ring R]

-- @@ L28-28 verbatim
universe u


-- @@ L30-32 verbatim
/-- An ideal is *idempotent-generated* when it is the (left) span of a single idempotent. -/
def IdemIdeal (I : Ideal R) : Prop :=
  ∃ (e : R), IsIdempotentElem e ∧ I = Ideal.span {e}


-- @@ L34-38 verbatim
/-- An ideal is *nice* when, whenever it is generated by an idempotent `e`, the corner
ring `eRe` admits an `OrtIdemDiv` decomposition. -/
def NiceIdeal (I : Ideal R) :=
  IdemIdeal I → ∀ (e : R) (idem : IsIdempotentElem e),
    I = Ideal.span {e} → OrtIdemDiv (CornerSubring idem)


-- @@ L40-44 verbatim
lemma idem_lift_is_idem {e : R} {idem_e : IsIdempotentElem e}
    (f : CornerSubring idem_e) (hf : IsIdempotentElem f) : IsIdempotentElem (f : R) := by
  unfold IsIdempotentElem at *
  nth_rewrite 3 [← hf]
  rfl


-- @@ L46-63 verbatim
/-- The zero ideal is a nice ideal. -/
def zeroIdealNice : NiceIdeal (⊥ : Ideal R) := by
  intro _ e idem_e h
  have e_zero : e = 0 := by
    rw [← Ideal.span_singleton_eq_bot]
    exact Eq.symm h
  have zero_e := Eq.symm e_zero
  exact
    { n := 0,
      f := fun _ => 0,
      h := fun _ => IsIdempotentElem.zero,
      sum_one := by
        calc (0 : CornerSubring idem_e) =
            (⟨e, e_in_corner_ring idem_e⟩ : CornerSubring idem_e) :=
              Subtype.ext_iff.2 zero_e
          _ = (1 : CornerSubring idem_e) := rfl
      orthogonal := by simp only [IsEmpty.forall_iff]
      div := by simp only [IsEmpty.forall_iff] }


-- @@ L65-68 verbatim
/-- Extend a list of `n` elements with an extra entry `x` in front, yielding `n + 1`
elements. -/
def idempotents {α : Type*} {n : ℕ} (x : α) (h : Fin n → α) : Fin (n + 1) → α :=
  Fin.cases x h


-- @@ L70-71 verbatim
lemma idempotents_first {α : Type*} {n : ℕ} (x : α) (h : Fin n → α) :
    idempotents x h 0 = x := rfl


-- @@ L73-74 verbatim
lemma idempotents_rest {α : Type*} {n : ℕ} (x : α) (h : Fin n → α) (i : Fin n) :
    idempotents x h (Fin.succ i) = h i := rfl


-- @@ L76-79 verbatim
theorem extend_idempotents {n : ℕ} (f : R) (idem_f : IsIdempotentElem f) (es : Fin n → R)
    (h : (i : Fin n) → IsIdempotentElem (es i)) :
    (i : Fin (n + 1)) → (IsIdempotentElem ((idempotents f es) i)) :=
  Fin.cases idem_f h


-- @@ L81-82 verbatim
lemma i_nonzero_succ {n : ℕ} (i : Fin (n + 1)) (i_nonzero : i ≠ 0) :
    ∃ (k : Fin n), i = k.succ := Fin.eq_succ_of_ne_zero i_nonzero


-- @@ L84-88 verbatim
lemma bot_eq_span_zero (I : Ideal R) (e : R) (h_bot : I ≠ ⊥) (h_span : I = Ideal.span {e}) :
    e ≠ 0 := by
  simp_all

-- If e is idempotent and (1-e)R(1-e) is OrtIdem then R is OrtIdemDiv

-- @@ L89-140 verbatim
/-- Prepend the idempotent `e` to an `OrtIdem` system on the corner ring of `1 - e`
to obtain an `OrtIdem R`. -/
def extensionOfOrtIdem (e : R) (idem_e : IsIdempotentElem e)
    (oi : OrtIdem (CornerSubring (IsIdempotentElem.one_sub idem_e))) : OrtIdem R :=
  { n := oi.n + 1,
    f := idempotents e (fun (i : Fin oi.n) => oi.f i),
    h := extend_idempotents e idem_e (fun (i : Fin oi.n) => oi.f i)
      (fun (i : Fin oi.n) => by
        apply e_idem_to_e_val_idem
        exact oi.h i),
    sum_one := by
      rw [Fin.sum_univ_succ]
      rw [idempotents_first]
      apply add_eq_of_eq_sub'
      have one_sub_e_unit : 1 - e = (1 : CornerSubring (IsIdempotentElem.one_sub idem_e)) := rfl
      simp only [one_sub_e_unit]
      rw [← oi.sum_one]
      calc
        ∑ i : Fin oi.n, idempotents e (fun i ↦ ↑(oi.f i)) i.succ =
            ∑ i : Fin oi.n, (fun i ↦ ↑(oi.f i)) i := rfl
        _ = ↑(∑ i : Fin oi.n, oi.f i) := Eq.symm (AddSubmonoidClass.coe_finsetSum oi.f Finset.univ)
    orthogonal := by
      intro i j i_neq_j
      have h1 : idempotents e (fun i ↦ ↑(oi.f i)) 0 = e := rfl
      by_cases hi : i = 0
      · rw [hi]
        let ⟨k, hk⟩ := i_nonzero_succ j (Ne.symm (ne_of_eq_of_ne (Eq.symm hi) i_neq_j))
        have h2 : idempotents e (fun i ↦ ↑(oi.f i)) j = oi.f k := by rw [hk]; rfl
        rw [h1, h2]
        apply f_in_corner_othogonal
        · exact idem_e
        · exact Subtype.coe_prop (oi.f k)
      · let ⟨k, hk⟩ := i_nonzero_succ i hi
        have h1' : (idempotents e (fun i ↦ ↑(oi.f i)) i) = oi.f k := by rw [hk]; rfl
        rw [h1']
        by_cases hj : j = 0
        · rw [hj, h1]
          apply ort_comm
          apply f_in_corner_othogonal
          · exact idem_e
          · exact Subtype.coe_prop (oi.f k)
        · let ⟨l, hl⟩ := i_nonzero_succ j hj
          have h2' : (idempotents e (fun i ↦ ↑(oi.f i)) j) = oi.f l := by rw [hl]; rfl
          rw [h2']
          have k_neq_l : k ≠ l := by
            simp_all
          let ort := oi.orthogonal k l k_neq_l
          apply orth_coercion
          exact ort }

-- If e is idempotent such that eRe is a division ring and (1-e)R(1-e) is OrtIdemDiv,
-- then R is OrtIdemDiv

-- @@ L141-175 verbatim
/-- Combine the idempotent `e` (with division corner) with an `OrtIdemDiv` system on the
corner ring of `1 - e` to obtain an `OrtIdemDiv R`. -/
def extensionOfOrtIdemDiv (e : R) (idem_e : IsIdempotentElem e)
    (div_e : IsDivisionRing (CornerSubring idem_e))
    (oid : OrtIdemDiv (CornerSubring (IsIdempotentElem.one_sub idem_e))) : OrtIdemDiv R :=
  { toOrtIdem := extensionOfOrtIdem e idem_e oid.toOrtIdem,
    div := by
      have hn : (extensionOfOrtIdem e idem_e oid.toOrtIdem).n = oid.n + 1 := rfl
      intro i
      change Fin (oid.n + 1) at i
      by_cases hi : i = 0
      · rw [hi]
        exact div_e
      · have ⟨k, hk⟩ := i_nonzero_succ i hi
        have h1 : oid.f k = (extensionOfOrtIdem e idem_e oid.toOrtIdem).f i := by rw [hk]; rfl
        apply @isomorphic_ring_div (CornerSubring (oid.h k)) _
          (CornerSubring ((extensionOfOrtIdem e idem_e oid.toOrtIdem).h i)) _
        · symm
          have eq_el : (extensionOfOrtIdem e idem_e oid.toOrtIdem).f i = oid.f k :=
            Eq.symm h1
          have hc1 : CornerSubring ((extensionOfOrtIdem e idem_e oid.toOrtIdem).h i) ≃+*
              (CornerSubring (e_idem_to_e_val_idem (oid.h k))) :=
            (eqElIsoCorner ((extensionOfOrtIdem e idem_e oid.toOrtIdem).f i)
              (oid.f k)
              ((extensionOfOrtIdem e idem_e oid.toOrtIdem).h i)
              (e_idem_to_e_val_idem (oid.h k)) eq_el)
          have hc2 : (CornerSubring (e_idem_to_e_val_idem (oid.h k))) ≃+*
              CornerSubring (oid.h k) := by
            symm
            apply @cornerRingUnitalEq R _
          exact RingEquiv.trans hc1 hc2
        · exact oid.div k }

-- if all ideals under I are nice then I is nice
-- induction step in the proof of Artin Wedderburn

-- @@ L176-250 verbatim
/-- Induction step of Artin–Wedderburn: if every proper subideal of `I` is nice, then `I`
itself is nice. -/
noncomputable
def subidealsNiceIdealNice (h_prime : IsPrimeRing R) (h_art : IsArtinian R R)
    (I : Ideal R) (hi : ∀ J, J < I → NiceIdeal J) : NiceIdeal I := by
  by_cases h_zero : I = ⊥
  · rw [h_zero]
    exact zeroIdealNice
  · intro _ e idem_e I_span_e
    have e_nonzero : e ≠ 0 := bot_eq_span_zero I e h_zero I_span_e
    have corner_nontriv : Nontrivial (CornerSubring idem_e) :=
      e_nonzero_corner_nontrivial R idem_e e_nonzero
    have corner_prime : IsPrimeRing (CornerSubring idem_e) := corner_ring_prime idem_e h_prime
    have corner_artinian : IsArtinian (CornerSubring idem_e) (CornerSubring idem_e) :=
      corner_ring_artinian idem_e
    obtain h := prime_and_artinian_esists_idem_corner_div corner_prime corner_artinian
    let f' := Classical.choose h
    have h_spec : f' ≠ 0 ∧ IsIdempotentElem f' ∧ IsDivisionSubring (CornerSubringNonUnital f') f' :=
      Classical.choose_spec h
    let fnz := h_spec.left
    let idem_f := h_spec.2.1
    let div_f := h_spec.2.2
    let f := f'.val
    let hf := f'.property
    have fnzR : f ≠ 0 := (nonzero idem_e f').mp fnz
    have idem_one_sub_e : IsIdempotentElem (1 - e) := IsIdempotentElem.one_sub idem_e
    have f_mem : f ∈ bothMul e e := hf
    have idem_f_val : IsIdempotentElem f := e_idem_to_e_val_idem idem_f
    have one_sub_e_f_orthogonal : IsOrthogonal (1 - e) f :=
      f_in_corner_othogonal (1 - e) f idem_one_sub_e (by simp only [sub_sub_cancel]; exact hf)
    have idem_e_sub_f : IsIdempotentElem (e - f) :=
      f_mem_corner_e_e_sub_f_idem e idem_e ⟨f, f_mem⟩ idem_f
    have e_sub_f_mem : (e - f) ∈ bothMul e e := by
      have e_mem : e ∈ bothMul e e := by
        refine ⟨1, ?_⟩
        rw [mul_one]
        exact (IsIdempotentElem.eq idem_e).symm
      apply both_mul_sub
      · exact e_mem
      · exact f_mem
    let J : Ideal R := Ideal.span {e - f}
    have J_sub_I : J < I := by
      rw [I_span_e]
      apply e_span_larger_e_sub_f e f ⟨idem_one_sub_e, idem_f_val, one_sub_e_f_orthogonal⟩ fnzR
    have J_nice := hi J J_sub_I
    have J_idem : IdemIdeal J := ⟨e - f, idem_e_sub_f, rfl⟩
    specialize J_nice J_idem (e - f) idem_e_sub_f rfl
    have f_div : IsDivisionRing (CornerSubring idem_f) := by
      apply div_subring_to_div_ring
      exact div_f
    apply extensionOfOrtIdemDiv
    · exact f_div
    have h : (CornerSubring (IsIdempotentElem.one_sub idem_f)) ≃+*
        ↥(CornerSubring idem_e_sub_f) := by
      have eq_el : (1 : CornerSubring idem_e) - f' =
          ⟨e, e_in_corner_ring idem_e⟩ - f' := by
        rw [Subtype.ext_iff, AddSubgroupClass.coe_sub, corner_ring_one]
        rfl
      have hc1 : (CornerSubring (IsIdempotentElem.one_sub idem_f)) ≃+*
          CornerSubring (e_idem_to_e_val_idem (IsIdempotentElem.one_sub idem_f)) := by
        apply cornerRingUnitalEq
      have hc2 : (CornerSubring idem_e_sub_f) ≃+*
          CornerSubring (e_idem_to_e_val_idem (IsIdempotentElem.one_sub idem_f)) := by
        apply eqElIsoCorner
        -- Goal: e - f = ↑(1 - f'). The `1 - f'` uses the `Sub` instance from
        -- the `Ring` structure on `CornerSubring idem_e`, which differs from
        -- `AddSubgroupClass.sub` only definitionally. Unfold subtraction on
        -- both sides via `sub_eq_add_neg`, then reduce coercions.
        rw [sub_eq_add_neg (1 : CornerSubring idem_e) f', AddMemClass.coe_add,
          NegMemClass.coe_neg, corner_ring_one, ← sub_eq_add_neg]
      exact RingEquiv.trans hc1 hc2.symm
    exact isomorphicOrtIdemDiv h.symm (hi J J_sub_I J_idem (e - f) idem_e_sub_f rfl)

-- In nontrivial prime artinian ring all ideal are nice
-- Induction using previous theorem

-- @@ L251-258 verbatim
/-- Well-founded induction along `<` lifting `subidealsNiceIdealNice`: every accessible
ideal in a prime artinian ring is nice. -/
noncomputable
def accIdealNice (h_prime : IsPrimeRing R) (h_art : IsArtinian R R)
    (I : Ideal R) (h_acc : Acc (fun x y => x < y) I) : NiceIdeal I := by
  induction h_acc with
  | intro J _ hJ =>
    exact subidealsNiceIdealNice h_prime h_art J hJ


-- @@ L260-260 verbatim
end LeanPool.ArtinWedderburn
