/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import LeanPool.DomainTheory.Neighborhood.Approximable
public import LeanPool.DomainTheory.Neighborhood.Exercise122
import LeanPool.DomainTheory.Neighborhood.Exercise213
import Mathlib.Topology.Continuous


-- @@ L13-62 verbatim
/-!
# Exercise 2.15 (Scott 1981, PRG-19, §2) — the one-token system `𝒪` (Sierpiński
space)

> **EXERCISE 2.15.** (For topologists.) Consider the one-token system with `𝒪 =
{{0}, ∅}`. We can
> regard `|𝒪|` as having just two finite elements `⊥` and `⊤`, where `⊥ ⊑ ⊤`. For
any system `𝒟`,
> show that the open subsets `U` of `|𝒟|` are in a one-one correspondence with the
approximable
> mappings `f : 𝒟 → 𝒪`, where the correspondence is given by `U = {x ∣ f(x) = ⊤}`.
What are the
> open subsets of `|𝒪|`? of `|𝕋|`? of `|𝔹|`?

We take the token type to be `Fin 1`, so the master neighbourhood `Δ = {0}` is
`Set.univ` and the
two neighbourhoods of `𝒪` are `Δ = univ` and `∅`. Then `|𝒪|` has exactly two
elements:
`⊥ = ↑Δ = {Δ}` and `⊤ = ↑∅`, with `⊥ ⊑ ⊤` (`botElt_le_topElt`, strict by
`botElt_ne_topElt`).
The space `|𝒪|` is **Sierpiński space**: its open sets are `∅`, `{⊤}` (`basicOpen
∅`), and the whole
space; `{⊥}` is *not* open (`⊥` is the generic point,
`not_isOpen_singleton_botElt`).

The main theorem (`openSetEquivMap`) is the Sierpiński-space adjunction "open
sets = continuous
maps to `𝒪`", here in the approximable-mapping guise:

* `openToMap U hU : ApproximableMap 𝒟 𝒪` — the map with `f(x) = ⊤ ↔ x ∈ U`, built
**choice-free**
  as the neighbourhood relation `X f Y ↔ X ∈ 𝒟 ∧ Y ∈ 𝒪 ∧ (Y = ∅ → ↑X ∈ U)`
  (monotone because `U`
  is open, i.e. an upper set);
* `mapToOpen f := {x ∣ f(x) = ⊤}` — open (`isOpen_mapToOpen`), being the preimage
of the open point
  `{⊤} = [∅]` under the continuous `x ↦ f(x)` (Exercise 2.13);
* `openSetEquivMap : {U // IsOpen U} ≃ ApproximableMap 𝒟 𝒪` — the two are
mutually inverse.

For the opens of `|𝕋|` and `|𝔹|`: `𝕋` (two incomparable totals `true`, `false`
above `⊥`) has opens
generated by the two open points `[{true}] = {true-total}` and `[{false}] =
{false-total}`; `|𝔹|`'s
opens are generated by the basic cones `[σΣ*]`. We record only `|𝒪|`'s opens in
Lean.

Choice-free (`#print axioms ⊆ {propext, Quot.sound}`) apart from the
`eq_of_toElementMap_principal`
uniqueness step inherited from Exercise 2.8. -/


-- @@ L64-64 verbatim
@[expose] public section


-- @@ L66-66 verbatim
namespace Domain.Neighborhood.Exercise215


-- @@ L68-68 verbatim
open Domain.Neighborhood NeighborhoodSystem


-- @@ L70-70 verbatim
/-! ### The one-token system `𝒪`. -/


-- @@ L72-73 verbatim
/-- Membership for `𝒪`: a neighbourhood is the master `Δ = univ` or the empty set. -/
def memO (X : Set (Fin 1)) : Prop := X = Set.univ ∨ X = ∅


-- @@ L75-76 verbatim
theorem univ_ne_empty : (Set.univ : Set (Fin 1)) ≠ ∅ := by
  simp_all


-- @@ L78-83 verbatim
theorem nestedOrDisjoint_O : NestedOrDisjoint memO := by
  rintro X Y (rfl | rfl) (rfl | rfl)
  · exact Or.inl subset_rfl
  · exact Or.inr (Or.inl (Set.empty_subset _))
  · exact Or.inl (Set.empty_subset _)
  · exact Or.inl subset_rfl


-- @@ L85-85 verbatim
theorem subMaster_O : ∀ {X : Set (Fin 1)}, memO X → X ⊆ Set.univ := fun _ => Set.subset_univ _


-- @@ L87-89 verbatim
/-- **Exercise 2.15 — the one-token system `𝒪 = {Δ, ∅}`.** -/
def O : NeighborhoodSystem (Fin 1) :=
  NeighborhoodSystem.ofNestedOrDisjoint memO Set.univ (Or.inl rfl) nestedOrDisjoint_O subMaster_O


-- @@ L91-91 verbatim
@[simp] theorem O_mem {X : Set (Fin 1)} : O.mem X ↔ memO X := Iff.rfl

-- @@ L92-92 verbatim
@[simp] theorem O_master : O.master = (Set.univ : Set (Fin 1)) := rfl


-- @@ L94-94 verbatim
theorem O_mem_empty : O.mem (∅ : Set (Fin 1)) := Or.inr rfl

-- @@ L95-95 verbatim
theorem O_mem_univ : O.mem (Set.univ : Set (Fin 1)) := Or.inl rfl


-- @@ L97-101 verbatim
/-- `𝒪` is closed under intersection (used to verify the relation of `openToMap`). -/
theorem O_inter_mem {Y Y' : Set (Fin 1)} (hY : O.mem Y) (hY' : O.mem Y') : O.mem (Y ∩ Y') := by
  rcases hY with rfl | rfl
  · rw [Set.univ_inter]; exact hY'
  · rw [Set.empty_inter]; exact O_mem_empty


-- @@ L103-103 verbatim
/-! ### The two elements `⊥ ⊑ ⊤` of `|𝒪|`. -/


-- @@ L105-106 verbatim
/-- The top element `⊤ = ↑∅` of `|𝒪|`. -/
def topElt : O.Element := O.principal O_mem_empty

-- @@ L107-108 verbatim
/-- The bottom element `⊥ = ↑Δ = {Δ}` of `|𝒪|`. -/
def botElt : O.Element := O.bot


-- @@ L110-112 verbatim
/-- `Y ∈ ⊥` iff `Y = Δ = univ`. -/
theorem mem_botElt {Y : Set (Fin 1)} : botElt.mem Y ↔ Y = (Set.univ : Set (Fin 1)) := by
  rw [botElt, O.mem_bot, O_master]


-- @@ L114-123 verbatim
/-- **The defining property of `⊤`.** An element `z` of `|𝒪|` is `⊤` iff it
contains `∅`: `∅` is
the sharpest neighbourhood, so `∅ ∈ z` forces `z` to be the principal filter `↑∅ =
⊤`. -/
theorem mem_empty_iff_eq_top (z : O.Element) : z.mem ∅ ↔ z = topElt := by
  constructor
  · intro hz
    exact O.eq_principal_of_isMin z hz (fun Y _ => Set.empty_subset Y)
  · rintro rfl
    exact ⟨O_mem_empty, subset_rfl⟩


-- @@ L125-139 verbatim
/-- **Two elements.** Every element of `|𝒪|` is `⊥` or `⊤`. -/
theorem element_eq_bot_or_top (z : O.Element) : z = botElt ∨ z = topElt := by
  by_cases hz : z.mem ∅
  · exact Or.inr ((mem_empty_iff_eq_top z).mp hz)
  · refine Or.inl ?_
    apply Element.ext
    intro Y
    constructor
    · intro hY
      rcases (O_mem.mp (z.sub hY)) with rfl | rfl
      · exact mem_botElt.mpr rfl
      · exact absurd hY hz
    · intro hY
      rw [mem_botElt.mp hY, ← O_master]
      exact z.master_mem


-- @@ L141-142 verbatim
/-- `⊥ ⊑ ⊤`. -/
theorem botElt_le_topElt : botElt ≤ topElt := O.bot_le _


-- @@ L144-149 verbatim
/-- `⊥ ≠ ⊤` (so `⊥ ⊏ ⊤`). -/
theorem botElt_ne_topElt : botElt ≠ topElt := by
  intro h
  have htop : topElt.mem ∅ := ⟨O_mem_empty, subset_rfl⟩
  rw [← h, mem_botElt] at htop
  exact univ_ne_empty htop.symm


-- @@ L151-162 verbatim
/-- **Extensionality for `|𝒪|`.** Two elements agreeing on membership of `∅` are
equal (it
distinguishes `⊥` from `⊤`). -/
theorem O_ext {z w : O.Element} (h : z.mem ∅ ↔ w.mem ∅) : z = w := by
  by_cases hz : z.mem ∅
  · rw [(mem_empty_iff_eq_top z).mp hz, (mem_empty_iff_eq_top w).mp (h.mp hz)]
  · have ez : z = botElt :=
      (element_eq_bot_or_top z).resolve_right (fun c => hz ((mem_empty_iff_eq_top z).mpr c))
    have ew : w = botElt :=
      (element_eq_bot_or_top w).resolve_right
        (fun c => (fun c' => hz (h.mpr c')) ((mem_empty_iff_eq_top w).mpr c))
    rw [ez, ew]


-- @@ L164-164 verbatim
/-! ### The opens of `|𝒪|`. -/


-- @@ L166-170 verbatim
/-- The open point `{⊤}` is the basic open `[∅]`. -/
theorem basicOpen_empty_eq_singleton_top : O.basicOpen ∅ = {topElt} := by
  ext x
  rw [mem_basicOpen, mem_empty_iff_eq_top]
  exact Set.mem_singleton_iff.symm


-- @@ L172-182 verbatim
/-- **The opens of `|𝒪|`.** `{⊥}` is not open: `⊥` is the generic point. (The
basic neighbourhood of
`⊥` is `[Δ] = |𝒪|`, which is not contained in `{⊥}` because it also contains `⊤`.) -/
theorem not_isOpen_singleton_botElt : ¬ IsOpen ({botElt} : Set O.Element) := by
  intro h
  obtain ⟨X, hX, hsub⟩ := h botElt rfl
  rw [mem_botElt] at hX
  subst hX
  have htop : topElt ∈ ({botElt} : Set O.Element) :=
    hsub (show topElt ∈ O.basicOpen Set.univ from (O_master ▸ topElt.master_mem))
  exact botElt_ne_topElt (Set.mem_singleton_iff.mp htop).symm


-- @@ L184-184 verbatim
/-! ### The correspondence between opens of `|𝒟|` and approximable maps `𝒟 → 𝒪`. -/


-- @@ L186-186 verbatim
variable {γ : Type*} (V : NeighborhoodSystem γ)


-- @@ L188-215 verbatim
/-- **Exercise 2.15 — the approximable map of an open set.** For open `U ⊆ |𝒟|`,
the relation
`X f Y ↔ X ∈ 𝒟 ∧ Y ∈ 𝒪 ∧ (Y = ∅ → ↑X ∈ U)`. The single nontrivial obligation is
monotonicity:
sharpening the input `X' ⊆ X` means `↑X ⊑ ↑X'`, and `U` open (an upper set)
carries `↑X ∈ U` up to
`↑X' ∈ U`. Choice-free. -/
def openToMap (U : Set V.Element) (hU : IsOpen U) : ApproximableMap V O where
  rel X Y := V.mem X ∧ O.mem Y ∧ (Y = ∅ → ∃ hX : V.mem X, V.principal hX ∈ U)
  rel_dom h := h.1
  rel_cod h := h.2.1
  master_rel := ⟨V.master_mem, O.master_mem, fun heq => (univ_ne_empty (O_master ▸ heq)).elim⟩
  inter_right := by
    rintro X Y Y' ⟨hX, hY, fY⟩ ⟨_, hY', fY'⟩
    refine ⟨hX, O_inter_mem hY hY', ?_⟩
    intro h
    rcases O_mem.mp hY with rfl | rfl
    · rw [Set.univ_inter] at h; exact fY' h
    · exact fY rfl
  mono := by
    rintro X X' Y Y' ⟨hX, _, fY⟩ hX'X hYY' hX' hY'
    refine ⟨hX', hY', ?_⟩
    intro hY'eq
    have hYeq : Y = ∅ := Set.subset_empty_iff.mp (hY'eq ▸ hYY')
    obtain ⟨hX0, hmem⟩ := fY hYeq
    have hmem' : V.principal hX ∈ U := hmem
    have hle : V.principal hX ≤ V.principal hX' := (V.principal_le_iff hX hX').mpr hX'X
    exact ⟨hX', V.isOpen_isUpperSet hU hmem' hle⟩


-- @@ L217-228 verbatim
/-- The value of `openToMap U hU` on the finite element `↑X` contains `∅` iff `↑X
∈ U`; i.e.
`(openToMap U hU)(↑X) = ⊤ ↔ ↑X ∈ U`. -/
theorem toElementMap_openToMap_principal_mem_empty (U : Set V.Element) (hU : IsOpen U)
    {X : Set γ} (hX : V.mem X) :
    ((openToMap V U hU).toElementMap (V.principal hX)).mem ∅ ↔ V.principal hX ∈ U := by
  rw [← (openToMap V U hU).rel_iff_mem_principal hX]
  constructor
  · rintro ⟨_, _, fimpl⟩
    simp_all
  · intro h
    exact ⟨hX, O_mem_empty, fun _ => ⟨hX, h⟩⟩


-- @@ L230-232 verbatim
/-- **Exercise 2.15 — the open set of an approximable map.** `mapToOpen f = {x ∣
f(x) = ⊤}`. -/
def mapToOpen (f : ApproximableMap V O) : Set V.Element := {x | f.toElementMap x = topElt}


-- @@ L234-243 verbatim
/-- `mapToOpen f` is open: it is the preimage of the open point `{⊤} = [∅]` under
the continuous
`x ↦ f(x)` (Exercise 2.13). -/
theorem isOpen_mapToOpen (f : ApproximableMap V O) : IsOpen (mapToOpen V f) := by
  have heq : mapToOpen V f = (fun x => f.toElementMap x) ⁻¹' O.basicOpen ∅ := by
    ext x
    simp only [mapToOpen, Set.mem_ofPred_eq, Set.mem_preimage, mem_basicOpen]
    exact (mem_empty_iff_eq_top (f.toElementMap x)).symm
  rw [heq]
  exact (O.isOpen_basicOpen ∅).preimage f.continuous_toElementMap


-- @@ L245-260 verbatim
/-- **Exercise 2.15 — round trip (open → map → open).** `mapToOpen (openToMap U
hU) = U`. -/
theorem mem_mapToOpen_openToMap (U : Set V.Element) (hU : IsOpen U) (x : V.Element) :
    x ∈ mapToOpen V (openToMap V U hU) ↔ x ∈ U := by
  rw [mapToOpen, Set.mem_ofPred_eq, ← mem_empty_iff_eq_top,
    ApproximableMap.toElementMap_mem_iff_principal]
  constructor
  · rintro ⟨X, hxX, hmem⟩
    rw [toElementMap_openToMap_principal_mem_empty] at hmem
    have hple : V.principal (x.sub hxX) ≤ x := fun Z hZ => x.up_mem hxX hZ.1 hZ.2
    exact V.isOpen_isUpperSet hU hmem hple
  · intro hxU
    obtain ⟨X, hxX, hXU⟩ := hU x hxU
    refine ⟨X, hxX, ?_⟩
    rw [toElementMap_openToMap_principal_mem_empty]
    exact hXU (show V.principal (x.sub hxX) ∈ V.basicOpen X from ⟨x.sub hxX, subset_rfl⟩)


-- @@ L262-270 verbatim
/-- **Exercise 2.15 — round trip (map → open → map).** `openToMap (mapToOpen f) =
f`. -/
theorem openToMap_mapToOpen (f : ApproximableMap V O) :
    openToMap V (mapToOpen V f) (isOpen_mapToOpen V f) = f := by
  apply ApproximableMap.eq_of_toElementMap_principal
  intro X hX
  apply O_ext
  rw [toElementMap_openToMap_principal_mem_empty, mapToOpen, Set.mem_ofPred_eq,
    ← mem_empty_iff_eq_top]


-- @@ L272-283 verbatim
/-- **Exercise 2.15 (main).** The open subsets of `|𝒟|` are in one-one
correspondence with the
approximable mappings `𝒟 → 𝒪`, via `U ↦ openToMap U` and `f ↦ {x ∣ f(x) = ⊤}`. -/
def openSetEquivMap : {U : Set V.Element // IsOpen U} ≃ ApproximableMap V O where
  toFun U := openToMap V U.1 U.2
  invFun f := ⟨mapToOpen V f, isOpen_mapToOpen V f⟩
  left_inv := by
    rintro ⟨U, hU⟩
    apply Subtype.ext
    ext x
    exact mem_mapToOpen_openToMap V U hU x
  right_inv f := openToMap_mapToOpen V f


-- @@ L285-285 verbatim
end Domain.Neighborhood.Exercise215
