/-
Copyright (c) 2026 Juliane Trianon Fraga and Vinicius de Oliveira Rodrigues. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Juliane Trianon Fraga, Vinicius de Oliveira Rodrigues
-/
module

public import LeanPool.Wallace.RationalLocalSetup
public import LeanPool.Wallace.LocalFusion
public import LeanPool.Wallace.LocalEnumeration
import Mathlib.CategoryTheory.Category.Init
import Mathlib.Combinatorics.Matroid.Init


-- @@ L14-20 verbatim
/-!
# The unconditional local fusion for the rational direct sum

For each nonzero rational vector this module instantiates the generic fusion recursion with the
prepared local blocks, proves the density bound for deleted positions, and packages the
resulting separating, locally admissible character.
-/


-- @@ L22-22 verbatim
@[expose] public section


-- @@ L24-24 verbatim
open Filter Set Topology


-- @@ L26-26 verbatim
namespace Wallace

-- @@ L27-27 verbatim
namespace RationalFusionRun


-- @@ L29-29 verbatim
noncomputable section


-- @@ L31-31 verbatim
open RationalTriangularPreprocess

-- @@ L32-32 verbatim
open BlockData

-- @@ L33-33 verbatim
open RationalData

-- @@ L34-34 verbatim
open RationalClosure

-- @@ L35-35 verbatim
open RationalLocalSetup

-- @@ L36-36 verbatim
open FiniteCombinatorics

-- @@ L37-37 verbatim
open LocalFusion


-- @@ L39-40 verbatim
/-- The finite-block size schedule used by the rational construction. -/
abbrev blockSize : ℕ → ℕ := FusionSchedule.blockSize

-- @@ L41-41 verbatim
theorem blockSize_pos (l : ℕ) : 0 < blockSize l := FusionSchedule.blockSize_pos l

-- @@ L42-43 verbatim
/-- The bounded-independence threshold at each fusion stage. -/
abbrev independenceBound : ℕ → ℕ := FusionSchedule.stageIndependenceBound


-- @@ L45-47 verbatim
/-- The countable coordinate closure generated by `x`. -/
abbrev localCarrier (x : ContinuumRationalGroup) : Set ContinuumIndex :=
  closure blockSize blockSize_pos independenceBound x


-- @@ L49-50 verbatim
/-- The rational direct sum supported on the local coordinate closure of `x`. -/
abbrev LocalGroup (x : ContinuumRationalGroup) := localCarrier x →₀ ℚ


-- @@ L52-54 verbatim
/-- The bounded-independent block presented to each local fusion stage. -/
abbrev fresh (x : ContinuumRationalGroup) : ℕ → Finset (LocalGroup x) :=
  localActiveBlock blockSize blockSize_pos independenceBound x


-- @@ L56-59 verbatim
/-- A fixed surjection used to make every local point eventually protected. -/
abbrev localEnumeration (x : ContinuumRationalGroup) : ℕ → LocalGroup x :=
  countableFinsuppEnumeration (localCarrier x)
    (closure_countable blockSize blockSize_pos independenceBound x)


-- @@ L61-64 verbatim
/-- The restriction of `x` to its local coordinate closure. -/
def distinguished (x : ContinuumRationalGroup) : LocalGroup x := by
  classical
  exact Finsupp.subtypeDomain (localCarrier x) x


-- @@ L66-72 verbatim
theorem distinguished_ne_zero {x : ContinuumRationalGroup} (hx : x ≠ 0) :
    distinguished x ≠ 0 := by
  classical
  intro hzero
  apply hx
  exact (Finsupp.subtypeDomain_eq_zero_iff
    (support_subset_closure blockSize blockSize_pos independenceBound x)).mp hzero


-- @@ L74-83 verbatim
/-- The generic scheduling recursion instantiated on the rational local group. -/
def scheduledCertificate (x : {x : ContinuumRationalGroup // x ≠ 0}) :
    ScheduledRunCertificate (fresh x.1) (distinguished x.1) :=
  Classical.choice <| exists_scheduledRunCertificate
    (fresh x.1) (localEnumeration x.1) (distinguished x.1)
    (distinguished_ne_zero x.2)
    (localActiveBlock_card_le blockSize blockSize_pos independenceBound x.1)
    (localActiveBlock_boundedIndependent blockSize blockSize_pos independenceBound x.1)
    (countableFinsuppEnumeration_surjective (localCarrier x.1)
      (closure_countable blockSize blockSize_pos independenceBound x.1))


-- @@ L85-87 verbatim
/-- The certified fusion run attached to a nonzero rational vector. -/
abbrev run (x : {x : ContinuumRationalGroup // x ≠ 0}) :
    FusionRun (LocalGroup x.1) := (scheduledCertificate x).run


-- @@ L89-94 verbatim
/-- Positions discarded from the block assigned to a relevant code. -/
def deletedPositions (x : {x : ContinuumRationalGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) (l : ℕ) :
    Finset ℕ :=
  (TriangularPreprocess.blockPositions blockSize blockSize_pos l).filter fun n ↦
    localDifference blockSize blockSize_pos independenceBound x.1 a n ∉ (run x).retained l


-- @@ L96-115 verbatim
private theorem image_deletedPositions
    (x : {x : ContinuumRationalGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) (l : ℕ) :
    (deletedPositions x a l).image
        (localDifference blockSize blockSize_pos independenceBound x.1 a) =
      localDifferenceBlock blockSize blockSize_pos independenceBound x.1 a l \
        (run x).retained l := by
  classical
  ext g
  constructor
  · intro hg
    obtain ⟨n, hn, rfl⟩ := Finset.mem_image.mp hg
    have hn' := Finset.mem_filter.mp hn
    exact Finset.mem_sdiff.mpr ⟨Finset.mem_image_of_mem _ hn'.1, hn'.2⟩
  · intro hg
    have hg' := Finset.mem_sdiff.mp hg
    obtain ⟨n, hn, hng⟩ := Finset.mem_image.mp hg'.1
    subst g
    exact Finset.mem_image.mpr
      ⟨n, Finset.mem_filter.mpr ⟨hn, hg'.2⟩, rfl⟩


-- @@ L117-138 verbatim
theorem deletedPositions_card_le
    (x : {x : ContinuumRationalGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) (l : ℕ)
    (hl : l ∈ refinedLabel blockSize blockSize_pos independenceBound x.1 a) :
    (deletedPositions x a l).card ≤ FusionSchedule.protectedBound l := by
  classical
  let f := localDifference blockSize blockSize_pos independenceBound x.1 a
  have hinj : Function.Injective f :=
    localDifference_injective blockSize blockSize_pos independenceBound x.1 a
  calc
    (deletedPositions x a l).card = ((deletedPositions x a l).image f).card := by
      exact (Finset.card_image_of_injective _ hinj).symm
    _ = (localDifferenceBlock blockSize blockSize_pos independenceBound x.1 a l \
          (run x).retained l).card := by rw [image_deletedPositions]
    _ = (fresh x.1 l \ (run x).retained l).card := by
      change (localDifferenceBlock blockSize blockSize_pos independenceBound x.1 a l \
          (run x).retained l).card =
        (localActiveBlock blockSize blockSize_pos independenceBound x.1 l \
          (run x).retained l).card
      rw [localActiveBlock_eq_of_mem blockSize blockSize_pos independenceBound x.1 l a hl]
    _ ≤ ((run x).guardSet l).card := (scheduledCertificate x).deleted_card_le l
    _ ≤ FusionSchedule.protectedBound l := (scheduledCertificate x).guard_card_le l


-- @@ L140-152 verbatim
theorem retainedPositions_mem_ultrafilter
    (x : {x : ContinuumRationalGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) :
    (BlockSystem.ofBlockPositions blockSize blockSize_pos).retainedBlocks
        (refinedLabel blockSize blockSize_pos independenceBound x.1 a)
        (deletedPositions x a) ∈ ultrafilter blockSize blockSize_pos a.1 := by
  apply ultrafilter_le_density blockSize blockSize_pos a.1
  apply BlockSystem.retainedBlocks_mem_densityFilter_ofBlockPositions
      blockSize blockSize_pos (deletedPositions x a) FusionSchedule.protectedBound
  · exact label_diff_refinedLabel_finite
      blockSize blockSize_pos independenceBound x.1 a
  · exact deletedPositions_card_le x a
  · exact FusionSchedule.tendsto_protectedBound_div_blockSize


-- @@ L154-154 verbatim
/-! ## Rational block and run certificates -/


-- @@ L156-162 verbatim
/-- Rational specialization of the shared prepared-block certificate. -/
abbrev RationalCodeBlocks
    (x : ContinuumRationalGroup) (R : FusionRun (LocalGroup x))
    (a : RelevantCode blockSize blockSize_pos independenceBound x) :=
  R.PreparedCodeBlocks (ultrafilter blockSize blockSize_pos a.1)
    (TriangularPreprocess.blockPositions blockSize blockSize_pos)
    (localDifference blockSize blockSize_pos independenceBound x a)


-- @@ L164-164 verbatim
namespace RationalCodeBlocks


-- @@ L166-193 verbatim
theorem tendsto_prepared
    {x : ContinuumRationalGroup} {R : FusionRun (LocalGroup x)}
    {a : RelevantCode blockSize blockSize_pos independenceBound x}
    (C : RationalCodeBlocks x R a) :
    Tendsto
      (fun n ↦ R.limitCharacter
        (Finsupp.subtypeDomain (localCarrier x)
          (prepared blockSize blockSize_pos independenceBound a.1 n)))
      (ultrafilter blockSize blockSize_pos a.1)
      (nhds (R.limitCharacter (Finsupp.single ⟨codeIndex a.1, a.2⟩ 1))) := by
  apply FusionRun.PreparedCodeBlocks.tendsto_prepared C blockSize blockSize_pos
  · exact ultrafilter_free blockSize blockSize_pos a.1
  · exact fun _ ↦ rfl
  · intro n
    simp only [localDifference]
    ext i
    change prepared blockSize blockSize_pos independenceBound a.1 n i.val -
        codeBasisVector a.1 i.val =
      prepared blockSize blockSize_pos independenceBound a.1 n i.val -
        Finsupp.single ⟨codeIndex a.1, a.2⟩ 1 i
    by_cases hi : i.val = codeIndex a.1
    · have hisub : i = ⟨codeIndex a.1, a.2⟩ := Subtype.ext hi
      subst i
      simp [codeBasisVector]
    · have hisub : i ≠ ⟨codeIndex a.1, a.2⟩ := by
        intro heq
        exact hi (congrArg Subtype.val heq)
      simp [codeBasisVector, hi, hisub]


-- @@ L195-195 verbatim
end RationalCodeBlocks


-- @@ L197-204 verbatim
/-- Complete local fusion output for one nonzero rational vector. -/
structure LocalRunCertificate (x : {x : ContinuumRationalGroup // x ≠ 0}) where
  /-- The fusion run on the countable local group generated by `x`. -/
  run : FusionRun (LocalGroup x.1)
  self_ne_zero : run.limitCharacter (Finsupp.subtypeDomain (localCarrier x.1) x.1) ≠ 0
  /-- A retained-block certificate for every locally relevant code. -/
  codeBlocks : ∀ a : RelevantCode blockSize blockSize_pos independenceBound x.1,
    RationalCodeBlocks x.1 run a


-- @@ L206-212 verbatim
theorem LocalRunCertificate.locallyAdmissible
    {x : {x : ContinuumRationalGroup // x ≠ 0}} (C : LocalRunCertificate x) :
    RationalTransfiniteExtension.LocallyAdmissible
      (transfiniteData blockSize blockSize_pos independenceBound)
      (localCarrier x.1) C.run.limitCharacter := by
  intro a ha
  exact (C.codeBlocks ⟨a, ha⟩).tendsto_prepared


-- @@ L214-235 verbatim
/-- The retained-block certificate associated with one relevant sequence code. -/
def codeBlocks (x : {x : ContinuumRationalGroup // x ≠ 0})
    (a : RelevantCode blockSize blockSize_pos independenceBound x.1) :
    RationalCodeBlocks x.1 (run x) a where
  blocks := {
    p := ultrafilter blockSize blockSize_pos a.1
    block := TriangularPreprocess.blockPositions blockSize blockSize_pos
    labels := refinedLabel blockSize blockSize_pos independenceBound x.1 a
    deletions := deletedPositions x a
    difference := localDifference blockSize blockSize_pos independenceBound x.1 a
    retained_mem := by
      simpa only [BlockSystem.retainedBlocks, BlockSystem.ofBlockPositions_block] using
        retainedPositions_mem_ultrafilter x a
    retained_in_stage := by
      intro l n hl hn
      have hnparts := Finset.mem_sdiff.mp hn
      by_contra hnot
      exact hnparts.2 (Finset.mem_filter.mpr ⟨hnparts.1, hnot⟩)
  }
  p_eq := rfl
  block_eq := fun _ ↦ rfl
  difference_eq := fun _ ↦ rfl


-- @@ L237-245 verbatim
/-- Complete local separating and admissibility certificate. -/
def localRunCertificate (x : {x : ContinuumRationalGroup // x ≠ 0}) :
    LocalRunCertificate x where
  run := run x
  self_ne_zero := by
    apply (run x).limitCharacter_ne_zero_of_initial_half
    · exact (scheduledCertificate x).initial_half
    · exact (scheduledCertificate x).distinguished_protected
  codeBlocks := codeBlocks x


-- @@ L247-247 verbatim
end

-- @@ L248-248 verbatim
end RationalFusionRun

-- @@ L249-249 verbatim
end Wallace
