/-
Copyright (c) 2026 Fernando Portela. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fernando Portela
-/

/-
Portions of this file were generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.28.0
Mathlib version: 8f9d9cff6bd728b17a24e163c9402775d9e6a365

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/
module

public import Mathlib.Data.Finset.Sort
public import Mathlib.Basic.Real.Basic
public import Mathlib.Data.ZMod.Basic
import Mathlib.Analysis.SpecialFunctions.Pow.Real
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt



-- @@ L27-36 verbatim
/-!
# Core Definitions for the Krafft Sieve

This module establishes the foundational definitions for the sieve:
- $\mathcal{P}_n$: The target set of primes.
- $q$: The primorial $q = \prod_{p \in \mathcal{P}_n} p$.
- $\mathcal{A}_n$: The target interval.
- $g_i, c$: Local and global hit counters.
- $sum1, sum2$: Weighted sums over the interval.
-/


-- @@ L38-38 verbatim
@[expose] public section


-- @@ L40-40 verbatim
namespace KrafftSieve


-- @@ L42-42 verbatim
open scoped BigOperators Real Nat Pointwise


-- @@ L44-44 verbatim
noncomputable section


-- @@ L46-49 verbatim
/-- Definition of the set of primes primeWindow.
Let $\mathcal{P}_n$ denote the set of primes $p$ such that $5 \le p < 6n+2$. -/
def primeWindow (n : ℕ) : Finset ℕ :=
  (Finset.range (6 * n + 2)).filter (fun p => 5 ≤ p ∧ p.Prime)


-- @@ L51-53 verbatim
/-- Definition of the primorial q.
Define the primorial $q = \prod_{p \in \mathcal{P}_n} p$. -/
def q (n : ℕ) : ℕ := (primeWindow n).prod (fun p => p)


-- @@ L55-57 verbatim
/-- Definition of w as the cardinality of primeWindow.
Let $w = |\mathcal{P}_n|$ be the number of distinct prime factors of $q$. -/
def w (n : ℕ) : ℕ := (primeWindow n).card


-- @@ L59-61 verbatim
/-- Definition of the sorted list of primes and the accessor function p_i.
Index the primes in $\mathcal{P}_n$ as $p_1, p_2, \dots, p_w$. -/
def primesList (n : ℕ) : List ℕ := (primeWindow n).sort (· ≤ ·)


-- @@ L63-67 verbatim
/-- Access the $i$-th prime $p_i$. Note that we use 0-based indexing for the implementation,
so $p_0$ corresponds to the user's $p_1$. -/
def p (n : ℕ) (i : Fin (w n)) : ℕ := (primesList n).get (i.cast (by
  unfold w primesList
  simp_all only [Finset.length_sort]))


-- @@ L69-72 verbatim
/-- Define r^K
Define the Krafft tuple r^K such that for each 1 <= i <= w,
r^K_i = floor((p_i+1)/6). -/
def krafftResidue (n : ℕ) (i : Fin (w n)) : ℕ := (p n i + 1) / 6


-- @@ L74-78 verbatim
/-- Define evalInterval
Define the target interval of indices:
evalInterval = {x in N | 6n^2 - 2n <= x <= 6n^2 + 10n + 3}. -/
def evalInterval (n : ℕ) : Finset ℕ :=
  Finset.Icc (6 * n ^ 2 - 2 * n) (6 * n ^ 2 + 10 * n + 3)


-- @@ L80-88 verbatim
/-- Define the local hit function g_i(x)
Define the local hit function $g_i : \mathbb{Z}/q\mathbb{Z} \to \mathbb{R}$
for each prime index $i \in \{1, \dots, w\}$.
- $g_i(x) = 1$ if $x \equiv r^K_i \pmod{p_i}$ or $x \equiv -r^K_i \pmod{p_i}$.
- Otherwise, $g_i(x) = 0$. -/
noncomputable def g (n : ℕ) (i : Fin (w n)) (x : ZMod (q n)) : ℝ :=
  if (x.cast : ZMod (p n i)) = (krafftResidue n i : ZMod (p n i))
    ∨ (x.cast : ZMod (p n i)) = -(krafftResidue n i : ZMod (p n i))
  then 1 else 0


-- @@ L90-95 verbatim
/-- Define the global additive hit counter c(x)
Define the global additive hit counter
$c : \mathbb{Z}/q\mathbb{Z} \to \mathbb{R}$ as the sum of all local hits:
$$ c(x) = \sum_{i=1}^w g_i(x) $$ -/
noncomputable def c (n : ℕ) (x : ZMod (q n)) : ℝ :=
  ∑ i : Fin (w n), g n i x


-- @@ L97-101 verbatim
/-- Define the total weighted mass of the interval sum1(n, W)
Define the total weighted mass of the interval $sum1(n, W)$:
$$ sum1(n, W) = \sum_{x \in \mathcal{A}_n} W(x) $$ -/
noncomputable def sum1 (n : ℕ) (W : ZMod (q n) → ℝ) : ℝ :=
  ∑ x ∈ evalInterval n, W (x : ZMod (q n))


-- @@ L103-107 verbatim
/-- Define the weighted hit count sum2(n, W)
Define the weighted hit count $sum2(n, W)$:
$$ sum2(n, W) = \sum_{x \in \mathcal{A}_n} W(x) c(x) $$ -/
noncomputable def sum2 (n : ℕ) (W : ZMod (q n) → ℝ) : ℝ :=
  ∑ x ∈ evalInterval n, W (x : ZMod (q n)) * c n (x : ZMod (q n))


-- @@ L109-109 verbatim
end


-- @@ L111-111 verbatim
end KrafftSieve
