/-
Copyright (c) 2026 Aurélien Eveil. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Eveil, Anthropic, OpenAI
-/

/-
The conditional-star completion and completed valuation of source Definition 79.

The carrier is represented by an optional generated world together with the
condition that `none` is admitted only when some variable is missing from every
generated world.  Thus this is definitionally a generated-world copy plus at
most one star, and the star exists exactly in the source's missing-variable
case.
-/
module

public import LeanPool.MatchingLogic.EntryIII.Generated


-- @@ L20-22 verbatim
/-!
# MatchingLogic.EntryIII.Completion
-/


-- @@ L24-24 verbatim
@[expose] public section


-- @@ L26-26 verbatim
namespace MatchingLogic


-- @@ L28-28 verbatim
open Set


-- @@ L30-30 verbatim
variable {S : Signature}


-- @@ L32-32 verbatim
noncomputable section


-- @@ L34-36 verbatim
/-- Local decidable equality used by the model-completion construction. -/
local instance instDecidableEqPatternNatCompletion : DecidableEq (Pattern S Nat) :=
  Classical.decEq _


-- @@ L38-41 verbatim
/-- Some element variable is absent from every world generated by `root`. -/
def Missing (root : CanonicalCarrier S) : Prop :=
  ∃ x : Nat, ∀ world : GeneratedCarrier root,
    Pattern.var x ∉ world.val.val


-- @@ L43-46 verbatim
/-- The source's conditional completion: all generated worlds are present,
while `none` is a legal point exactly when `Missing root` holds. -/
def CompletedCarrier (root : CanonicalCarrier S) :=
  {o : Option (GeneratedCarrier root) // o = none → Missing root}


-- @@ L48-48 verbatim
namespace CompletedCarrier


-- @@ L50-52 verbatim
/-- A completed point is the added star precisely when its option is `none`. -/
def isStar {root : CanonicalCarrier S} (point : CompletedCarrier root) : Prop :=
  point.val = none


-- @@ L54-54 verbatim
end CompletedCarrier


-- @@ L56-59 verbatim
/-- Embed a generated world into the completed carrier. -/
def completedEmbed (root : CanonicalCarrier S) (world : GeneratedCarrier root) :
    CompletedCarrier root :=
  ⟨some world, by simp⟩


-- @@ L61-64 verbatim
/-- Construct the star point from evidence that a variable is missing. -/
def completedStar {root : CanonicalCarrier S} (hmissing : Missing root) :
    CompletedCarrier root :=
  ⟨none, fun _ => hmissing⟩


-- @@ L66-71 verbatim
/-- The generated-world embedding is injective. -/
theorem completedEmbed_injective (root : CanonicalCarrier S) :
    Function.Injective (completedEmbed root) := by
  intro left right h
  have hval := congrArg Subtype.val h
  simpa [completedEmbed] using hval


-- @@ L73-79 verbatim
/-- The conditional star is distinct from every embedded generated world. -/
theorem completedStar_ne_embed {root : CanonicalCarrier S}
    (hmissing : Missing root) (world : GeneratedCarrier root) :
    completedStar hmissing ≠ completedEmbed root world := by
  intro h
  have hval := congrArg Subtype.val h
  simp [completedStar, completedEmbed] at hval


-- @@ L81-89 verbatim
/-- The representation has a star point exactly in the source's
missing-variable case. -/
theorem exists_completedStar_iff_missing (root : CanonicalCarrier S) :
    (∃ point : CompletedCarrier root, point.isStar) ↔ Missing root := by
  constructor
  · rintro ⟨point, hstar⟩
    exact point.property hstar
  · intro hmissing
    exact ⟨completedStar hmissing, rfl⟩


-- @@ L91-108 verbatim
/-- Every completed point is either an embedded generated world or the unique
conditional star. -/
theorem completedCarrier_cases {root : CanonicalCarrier S}
    (point : CompletedCarrier root) :
    (∃ world : GeneratedCarrier root, point = completedEmbed root world) ∨
      (∃ hmissing : Missing root, point = completedStar hmissing) := by
  cases hval : point.val with
  | none =>
      right
      let hmissing := point.property hval
      refine ⟨hmissing, ?_⟩
      apply Subtype.ext
      simpa [completedStar] using hval
  | some world =>
      left
      refine ⟨world, ?_⟩
      apply Subtype.ext
      simpa [completedEmbed] using hval


-- @@ L110-110 verbatim
/-! ### Completed interpretation -/


-- @@ L112-124 verbatim
/-- Source Definition 79's interpretation.  The existential tuple makes the
three cases exact: a star input admits no tuple; real outputs are the generated
interpretation; and star is an additional output exactly when some real input
is the generated root. -/
def completedInterp (root : CanonicalCarrier S) (sigma : S.Sym)
    (inputs : Fin (S.arity sigma) → CompletedCarrier root) :
    Set (CompletedCarrier root) :=
  {output | ∃ components : Fin (S.arity sigma) → GeneratedCarrier root,
    (∀ i, inputs i = completedEmbed root (components i)) ∧
      ((∃ world : GeneratedCarrier root,
          output = completedEmbed root world ∧
            world ∈ generatedInterp root sigma components) ∨
       (output.isStar ∧ ∃ i, components i = generatedRoot root))}


-- @@ L126-130 verbatim
/-- The completed one-sorted model. -/
abbrev completedModel (root : CanonicalCarrier S) : Model S where
  carrier := CompletedCarrier root
  nonempty := ⟨completedEmbed root (generatedRoot root)⟩
  interp := completedInterp root


-- @@ L132-142 verbatim
@[simp] theorem mem_completedInterp {root : CanonicalCarrier S} {sigma : S.Sym}
    {inputs : Fin (S.arity sigma) → CompletedCarrier root}
    {output : CompletedCarrier root} :
    output ∈ completedInterp root sigma inputs ↔
      ∃ components : Fin (S.arity sigma) → GeneratedCarrier root,
        (∀ i, inputs i = completedEmbed root (components i)) ∧
          ((∃ world : GeneratedCarrier root,
              output = completedEmbed root world ∧
                world ∈ generatedInterp root sigma components) ∨
           (output.isStar ∧ ∃ i, components i = generatedRoot root)) :=
  Iff.rfl


-- @@ L144-148 verbatim
@[simp] theorem completedModel_interp (root : CanonicalCarrier S)
    (sigma : S.Sym)
    (inputs : Fin (S.arity sigma) → CompletedCarrier root) :
    (completedModel root).interp sigma inputs = completedInterp root sigma inputs :=
  rfl


-- @@ L150-155 verbatim
theorem mem_completedModel_interp {root : CanonicalCarrier S}
    {sigma : S.Sym} {inputs : Fin (S.arity sigma) → CompletedCarrier root}
    {output : CompletedCarrier root} :
    output ∈ (completedModel root).interp sigma inputs ↔
      output ∈ completedInterp root sigma inputs :=
  Iff.rfl


-- @@ L157-168 verbatim
/-- Any star input forces the completed symbol interpretation to be empty. -/
theorem completedInterp_eq_empty_of_input_star {root : CanonicalCarrier S}
    {sigma : S.Sym} {inputs : Fin (S.arity sigma) → CompletedCarrier root}
    (i : Fin (S.arity sigma)) (hstar : (inputs i).isStar) :
    completedInterp root sigma inputs = ∅ := by
  ext output
  simp only [Set.mem_empty_iff_false, iff_false]
  intro houtput
  rcases houtput with ⟨components, hinputs, _⟩
  have hsome := congrArg Subtype.val (hinputs i)
  rw [hstar] at hsome
  simp [completedEmbed] at hsome


-- @@ L170-192 verbatim
/-- On all-real inputs, real output membership is exactly membership in the
generated interpretation. -/
theorem completedEmbed_mem_completedInterp_iff
    (root : CanonicalCarrier S) {sigma : S.Sym}
    (components : Fin (S.arity sigma) → GeneratedCarrier root)
    (world : GeneratedCarrier root) :
    completedEmbed root world ∈
        completedInterp root sigma (fun i => completedEmbed root (components i)) ↔
      world ∈ generatedInterp root sigma components := by
  constructor
  · rintro ⟨components', hinputs, hreal | hstar⟩
    · have hcomponents : components = components' := by
        funext i
        exact completedEmbed_injective root (hinputs i)
      subst components'
      rcases hreal with ⟨output, hout, houtput⟩
      have hw : world = output := completedEmbed_injective root hout
      simpa [hw] using houtput
    · have himpossible : (completedEmbed root world).val = none := hstar.1
      simp [completedEmbed] at himpossible
  · intro hworld
    refine ⟨components, fun _ => rfl, Or.inl ?_⟩
    exact ⟨world, rfl, hworld⟩


-- @@ L194-212 verbatim
/-- On all-real inputs, star is output exactly when one component is the
generated root. -/
theorem completedStar_mem_completedInterp_iff
    {root : CanonicalCarrier S} (hmissing : Missing root) {sigma : S.Sym}
    (components : Fin (S.arity sigma) → GeneratedCarrier root) :
    completedStar hmissing ∈
        completedInterp root sigma (fun i => completedEmbed root (components i)) ↔
      ∃ i, components i = generatedRoot root := by
  constructor
  · rintro ⟨components', hinputs, hreal | hstar⟩
    · rcases hreal with ⟨world, hout, _⟩
      exact False.elim (completedStar_ne_embed hmissing world hout)
    · have hcomponents : components = components' := by
        funext i
        exact completedEmbed_injective root (hinputs i)
      subst components'
      exact hstar.2
  · intro hroot
    exact ⟨components, fun _ => rfl, Or.inr ⟨rfl, hroot⟩⟩


-- @@ L214-214 verbatim
/-! ### Completed valuation -/


-- @@ L216-224 verbatim
/-- Select the unique generated world containing `var x`, when one exists;
otherwise select the conditional star justified by `x` itself. -/
def completedValuation (root : CanonicalCarrier S) (x : Nat) :
    CompletedCarrier root := by
  classical
  by_cases h : ∃ world : GeneratedCarrier root,
      Pattern.var x ∈ world.val.val
  · exact completedEmbed root (Classical.choose h)
  · exact ⟨none, fun _ => ⟨x, fun world hx => h ⟨world, hx⟩⟩⟩


-- @@ L226-250 verbatim
/-- The completed valuation is star exactly for variables missing from all
generated worlds. -/
theorem completedValuation_isStar_iff (root : CanonicalCarrier S) (x : Nat) :
    (completedValuation root x).isStar ↔
      ∀ world : GeneratedCarrier root, Pattern.var x ∉ world.val.val := by
  classical
  by_cases h : ∃ world : GeneratedCarrier root,
      Pattern.var x ∈ world.val.val
  · constructor
    · intro hstar
      change (completedValuation root x).val = none at hstar
      simp [completedValuation, h, completedEmbed] at hstar
    · intro hall
      obtain ⟨world, hworld⟩ := h
      exact False.elim (hall world hworld)
  · have hall : ∀ world : GeneratedCarrier root,
        Pattern.var x ∉ world.val.val := by
      intro world hworld
      exact h ⟨world, hworld⟩
    constructor
    · intro _
      exact hall
    · intro _
      change (completedValuation root x).val = none
      simp [completedValuation, h]


-- @@ L252-279 verbatim
/-- The selection is well-defined: it names an embedded world exactly when
that world contains the variable, with uniqueness supplied by Lemma 78. -/
theorem completedValuation_eq_embed_iff (root : CanonicalCarrier S) (x : Nat)
    (world : GeneratedCarrier root) :
    completedValuation root x = completedEmbed root world ↔
      Pattern.var x ∈ world.val.val := by
  classical
  by_cases h : ∃ candidate : GeneratedCarrier root,
      Pattern.var x ∈ candidate.val.val
  · let chosen := Classical.choose h
    have hchosen : Pattern.var x ∈ chosen.val.val := Classical.choose_spec h
    have hvalue : completedValuation root x = completedEmbed root chosen := by
      simp [completedValuation, h, chosen]
    constructor
    · intro heq
      have hchosenWorld : chosen = world :=
        completedEmbed_injective root (hvalue.symm.trans heq)
      simpa [hchosenWorld] using hchosen
    · intro hworld
      have hchosenWorld : chosen = world :=
        GeneratedCarrier.eq_of_var_mem chosen world hchosen hworld
      simp [hvalue, hchosenWorld]
  · constructor
    · intro heq
      have hval := congrArg Subtype.val heq
      simp [completedValuation, h, completedEmbed] at hval
    · intro hworld
      exact False.elim (h ⟨world, hworld⟩)


-- @@ L281-294 verbatim
/-- Every point of the completed carrier is named by some element variable. -/
theorem completedValuation_surjective (root : CanonicalCarrier S) :
    Function.Surjective (completedValuation root) := by
  intro point
  rcases completedCarrier_cases point with hreal | hstar
  · obtain ⟨world, rfl⟩ := hreal
    obtain ⟨x, hx⟩ := CanonicalCarrier.exists_var_mem world.val
    exact ⟨x, (completedValuation_eq_embed_iff root x world).mpr hx⟩
  · obtain ⟨hmissing, rfl⟩ := hstar
    obtain ⟨x, hx⟩ := hmissing
    refine ⟨x, ?_⟩
    apply Subtype.ext
    simpa [CompletedCarrier.isStar, completedStar] using
      (completedValuation_isStar_iff root x).mpr hx


-- @@ L296-296 verbatim
end


-- @@ L298-298 verbatim
end MatchingLogic
