/-
Copyright (c) 2026 QudeLeap. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: QudeLeap Team
-/

module

public import Mathlib.Algebra.Lie.OfAssociative
public import Mathlib.Basic.Complex.Basic
import Mathlib.Algebra.Order.Algebra
import Mathlib.Analysis.SpecialFunctions.Pow.NNReal
import Mathlib.Data.Sym.Sym2.Init
import Mathlib.Tactic.NormNum.GCD


-- @@ L16-42 verbatim
/-!
# The dynamical Lie algebra

The **dynamical Lie algebra** (DLA) of a parameterized quantum circuit with
generators `{H₁, …, H_K}` is the Lie closure `g = ⟨i H₁, …, i H_K⟩_Lie` — the
smallest Lie subalgebra (under the matrix commutator `⁅A, B⁆ = A B − B A`)
containing the (skew-Hermitian) generators. Its dimension governs circuit
expressibility, overparametrization, and barren-plateau trainability.

Here the ambient Lie algebra is `gl(N, ℂ) = Matrix (Fin N) (Fin N) ℂ` with its
commutator bracket (`LieAlgebra.ofAssociativeAlgebra`). The DLA is defined for an
arbitrary set of matrix generators via `LieSubalgebra.lieSpan`; the physical
generators `i • Hₖ` are skew-Hermitian, so the resulting algebra lies inside
`u(N)`.

Sources: Ragone et al. (2023), *A Lie Algebraic Theory of Barren Plateaus*
(definition Eq. (5)); Allcock et al. (2024), *On the dynamical Lie algebras of
QAOA*.

## Main definitions / results

- `LeanPool.LeanQuantumAlg.dynamicalLieAlgebra` — the Lie subalgebra generated by the
  generator set (the Lie closure).
- `LeanPool.LeanQuantumAlg.generators_subset_dynamicalLieAlgebra` — the generators lie in it.
- `LeanPool.LeanQuantumAlg.dynamicalLieAlgebra_le_iff` / `dynamicalLieAlgebra_minimal` — its
  universal property: it is the smallest Lie subalgebra containing the generators.
-/


-- @@ L44-44 verbatim
@[expose] public section


-- @@ L46-46 verbatim
attribute [local instance 100] LieRing.ofAssociativeRing


-- @@ L48-48 verbatim
namespace QuantumAlg


-- @@ L50-50 verbatim
noncomputable section


-- @@ L52-52 verbatim
variable {N : ℕ}


-- @@ L54-59 verbatim
/-- The dynamical Lie algebra generated by a set of matrix generators: the
smallest Lie subalgebra of `gl(N, ℂ)` (with the commutator bracket) containing
them — the Lie closure under nested commutators. -/
def dynamicalLieAlgebra (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ) :=
  LieSubalgebra.lieSpan ℂ (Matrix (Fin N) (Fin N) ℂ) gens


-- @@ L61-65 verbatim
/-- The generators belong to their dynamical Lie algebra. -/
theorem generators_subset_dynamicalLieAlgebra
    (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    gens ⊆ (dynamicalLieAlgebra gens : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  LieSubalgebra.subset_lieSpan


-- @@ L67-73 verbatim
/-- **Universal property.** The dynamical Lie algebra is contained in a Lie
subalgebra `K` exactly when all generators are. -/
theorem dynamicalLieAlgebra_le_iff (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    (K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)) :
    dynamicalLieAlgebra gens ≤ K
      ↔ gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  LieSubalgebra.lieSpan_le


-- @@ L75-81 verbatim
/-- **Minimality.** The dynamical Lie algebra is the smallest Lie subalgebra
containing the generators. -/
theorem dynamicalLieAlgebra_minimal (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    {K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)}
    (h : gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ))) :
    dynamicalLieAlgebra gens ≤ K :=
  LieSubalgebra.lieSpan_le.mpr h


-- @@ L83-83 verbatim
/-! ### Controllability -/


-- @@ L85-91 verbatim
/-- **Algebraic controllability criterion.** The system is controllable when its
dynamical Lie algebra is all of `gl(N, ℂ)`. For unitary dynamics the reachable set
is the connected Lie group `exp(g)`, which is the whole group exactly when `g` is
the full algebra; we record the Lie-algebraic criterion (`g = ⊤`). Identifying the
reachable set with `exp(g)` at the Lie-group level is left to future work. -/
def IsControllable (gens : Set (Matrix (Fin N) (Fin N) ℂ)) : Prop :=
  dynamicalLieAlgebra gens = ⊤


-- @@ L93-102 verbatim
/-- Controllability is equivalent to every matrix lying in the Lie closure of the
generators. -/
theorem isControllable_iff_forall_mem (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    IsControllable gens ↔ ∀ A, A ∈ dynamicalLieAlgebra gens := by
  constructor
  · intro h A
    rw [IsControllable] at h
    simp_all
  · intro h
    exact le_antisymm le_top fun a _ => h a


-- @@ L104-110 verbatim
/-- Enlarging the generator set preserves controllability. -/
theorem IsControllable.mono {gens gens' : Set (Matrix (Fin N) (Fin N) ℂ)}
    (hsub : gens ⊆ gens') (hc : IsControllable gens) : IsControllable gens' := by
  have hmono : dynamicalLieAlgebra gens ≤ dynamicalLieAlgebra gens' :=
    LieSubalgebra.lieSpan_le.mpr (hsub.trans LieSubalgebra.subset_lieSpan)
  rw [IsControllable] at hc ⊢
  simp_all


-- @@ L112-112 verbatim
/-! ### Classification: the abelian (mutually commuting) case -/


-- @@ L114-141 verbatim
/-- **Abelian case of the Pauli-Lie-algebra classification.** If the generators
pairwise commute, the dynamical Lie algebra is abelian: the commutator vanishes on
all of it. This is the free/trivial end of the structural classification of
Pauli-generated Lie algebras (Aguilar et al. 2024). -/
theorem dynamicalLieAlgebra_lie_eq_zero_of_comm
    {gens : Set (Matrix (Fin N) (Fin N) ℂ)}
    (hcomm : ∀ a ∈ gens, ∀ b ∈ gens, ⁅a, b⁆ = 0)
    {x y : Matrix (Fin N) (Fin N) ℂ}
    (hx : x ∈ dynamicalLieAlgebra gens) (hy : y ∈ dynamicalLieAlgebra gens) :
    ⁅x, y⁆ = 0 := by
  -- inner induction: for a generator `s`, `⁅s, ·⁆` vanishes on the whole DLA.
  have hgen : ∀ s ∈ gens, ∀ z ∈ dynamicalLieAlgebra gens, ⁅s, z⁆ = 0 := by
    intro s hs z hz
    refine LieSubalgebra.lieSpan_induction ℂ (p := fun t _ => ⁅s, t⁆ = 0)
      ?_ ?_ ?_ ?_ ?_ hz
    · intro b hb; exact hcomm s hs b hb
    · simp
    · intro t1 t2 ht1 ht2 h1 h2; simp [lie_add, h1, h2]
    · intro a t ht h; simp [lie_smul, h]
    · intro t1 t2 ht1 ht2 h1 h2; rw [leibniz_lie, h1, h2]; simp
  -- outer induction: `⁅·, y⁆` vanishes on the whole DLA.
  refine LieSubalgebra.lieSpan_induction ℂ (p := fun t _ => ⁅t, y⁆ = 0)
    ?_ ?_ ?_ ?_ ?_ hx
  · intro s hs; exact hgen s hs y hy
  · simp
  · intro t1 t2 ht1 ht2 h1 h2; simp [add_lie, h1, h2]
  · intro a t ht h; simp [smul_lie, h]
  · intro t1 t2 ht1 ht2 h1 h2; rw [lie_lie, h1, h2]; simp


-- @@ L143-143 verbatim
namespace DynamicalLieAlgebra


-- @@ L145-150 verbatim
/-- Main theorem: the DLA is the smallest Lie subalgebra containing the generators. -/
theorem main (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    {K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)}
    (h : gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ))) :
    dynamicalLieAlgebra gens ≤ K :=
  dynamicalLieAlgebra_minimal gens h


-- @@ L152-155 verbatim
/-- Public supporting theorem: generators belong to their DLA. -/
theorem main_generators_subset (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    gens ⊆ (dynamicalLieAlgebra gens : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  generators_subset_dynamicalLieAlgebra gens


-- @@ L157-162 verbatim
/-- Public supporting theorem: the universal property of the DLA. -/
theorem main_le_iff (gens : Set (Matrix (Fin N) (Fin N) ℂ))
    (K : LieSubalgebra ℂ (Matrix (Fin N) (Fin N) ℂ)) :
    dynamicalLieAlgebra gens ≤ K
      ↔ gens ⊆ (K : Set (Matrix (Fin N) (Fin N) ℂ)) :=
  dynamicalLieAlgebra_le_iff gens K


-- @@ L164-171 verbatim
/-- Public supporting theorem: commuting generators produce an abelian DLA. -/
theorem main_abelian_of_commuting_generators
    {gens : Set (Matrix (Fin N) (Fin N) ℂ)}
    (hcomm : ∀ a ∈ gens, ∀ b ∈ gens, ⁅a, b⁆ = 0)
    {x y : Matrix (Fin N) (Fin N) ℂ}
    (hx : x ∈ dynamicalLieAlgebra gens) (hy : y ∈ dynamicalLieAlgebra gens) :
    ⁅x, y⁆ = 0 :=
  dynamicalLieAlgebra_lie_eq_zero_of_comm hcomm hx hy


-- @@ L173-173 verbatim
end DynamicalLieAlgebra


-- @@ L175-175 verbatim
namespace DLAReachability


-- @@ L177-180 verbatim
/-- Main theorem: controllability is membership of every matrix in the DLA. -/
theorem main (gens : Set (Matrix (Fin N) (Fin N) ℂ)) :
    IsControllable gens ↔ ∀ A, A ∈ dynamicalLieAlgebra gens :=
  isControllable_iff_forall_mem gens


-- @@ L182-185 verbatim
/-- Public supporting theorem: enlarging generators preserves controllability. -/
theorem main_mono {gens gens' : Set (Matrix (Fin N) (Fin N) ℂ)}
    (hsub : gens ⊆ gens') (hc : IsControllable gens) : IsControllable gens' :=
  IsControllable.mono hsub hc


-- @@ L187-187 verbatim
end DLAReachability


-- @@ L189-189 verbatim
end


-- @@ L191-191 verbatim
end QuantumAlg
