/-
Copyright (c) 2026 Catskills Research Company. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Catskills Research Company
-/
module

public import LeanPool.DomainTheory.Neighborhood.Basic
import Mathlib.Data.Set.Basic


-- @@ L11-47 verbatim
/-!
# Exercise 1.23 (Scott 1981, PRG-19, §1) — the greedy total element of a countable
system

Scott: suppose `𝒟 = {X₀, X₁, …}` is countable and the consistency of finite
sequences of
neighbourhoods is *decidable*. Then the greedy sequence

```
Y₀     = X₀
Y_{n+1} = X_{n+1}  if X_{n+1} is consistent with Y₀, …, Yₙ;
        = Yₙ       otherwise.
```

is well defined, and `{Y₀, Y₁, …}` is a **total** element of `|𝒟|`. (Hint: first
show that
`Y₀, …, Y_{n-1}` is consistent for every `n`.)

This file formalizes the greedy construction over an enumeration `enum : ℕ → Set
α` of `𝒟`,
encoding "consistency of the prefix + candidate is decidable" as `[DecidablePred
V.mem]` (by
Theorem 1.1c, a prefix is consistent iff its running intersection is a
neighbourhood). We carry
the *state* `(Yₙ, ⋂_{i≤n} Yᵢ)`; the running intersection `acc n` is exactly
`interUpTo Y (n+1)`
and is always a neighbourhood, which is the hint `Y_prefix_consistent`.

* `greedyElement` — the filter `{X ∈ 𝒟 ∣ ⋂_{i<n} Yᵢ ⊆ X for some n}` generated by
`⟨Yₙ⟩`;
* `greedyElement_isTotal` — under surjectivity of `enum`, `greedyElement` is
maximal: any `W`
  in a larger filter `z` is some `enum k`; if greedy *skipped* it then `W` was
  inconsistent with
  the prefix, contradicting `z`'s closure under intersection.

The construction is `[propext, Quot.sound]` given the supplied `DecidablePred`. -/


-- @@ L49-49 verbatim
@[expose] public section


-- @@ L51-51 verbatim
namespace Domain.Neighborhood


-- @@ L53-53 verbatim
namespace NeighborhoodSystem


-- @@ L55-55 verbatim
variable {α : Type*} (V : NeighborhoodSystem α)


-- @@ L57-67 verbatim
/-- The finite intersection is antitone in its length: a longer prefix is
contained in a shorter
one. -/
theorem interUpTo_antitone (X : ℕ → Set α) {j k : ℕ} (h : j ≤ k) :
    V.interUpTo X k ⊆ V.interUpTo X j := by
  induction k with
  | zero => rw [Nat.le_zero.mp h]
  | succ k ih =>
    rcases Nat.eq_or_lt_of_le h with h' | h'
    · rw [h']
    · exact Set.inter_subset_left.trans (ih (Nat.lt_succ_iff.mp h'))


-- @@ L69-69 verbatim
end NeighborhoodSystem


-- @@ L71-71 verbatim
namespace Exercise123


-- @@ L73-73 verbatim
open NeighborhoodSystem


-- @@ L75-75 verbatim
variable {α : Type*} (V : NeighborhoodSystem α) (enum : ℕ → Set α) [DecidablePred V.mem]


-- @@ L77-89 verbatim
/-- Greedy *state*: `state n = (Yₙ, ⋂_{i≤n} Yᵢ)`. The running intersection in the
second
component lets the consistency test `V.mem (acc ∩ enum (n+1))` be self-contained
(Theorem 1.1c:
the prefix `Y₀,…,Yₙ,enum (n+1)` is consistent iff this intersection is a
neighbourhood). -/
def state : ℕ → Set α × Set α
  | 0 => (enum 0, V.master ∩ enum 0)
  | (n + 1) =>
      if V.mem ((state n).2 ∩ enum (n + 1)) then
        (enum (n + 1), (state n).2 ∩ enum (n + 1))
      else
        state n


-- @@ L91-92 verbatim
/-- The greedy sequence `Yₙ = (state n).1`. -/
def Y (n : ℕ) : Set α := (state V enum n).1


-- @@ L94-95 verbatim
/-- The running intersection `acc n = ⋂_{i≤n} Yᵢ = (state n).2`. -/
def acc (n : ℕ) : Set α := (state V enum n).2


-- @@ L97-100 verbatim
/-- The consistency test at stage `n+1`: is `enum (n+1)` consistent with the
prefix `Y₀,…,Yₙ`?
An `abbrev` so the `[DecidablePred V.mem]` instance is found through it. -/
abbrev cond (n : ℕ) : Prop := V.mem (acc V enum n ∩ enum (n + 1))


-- @@ L102-102 verbatim
@[simp] theorem Y_zero : Y V enum 0 = enum 0 := rfl


-- @@ L104-104 verbatim
@[simp] theorem acc_zero : acc V enum 0 = V.master ∩ enum 0 := rfl


-- @@ L106-111 verbatim
/-- The defining equation of `state` at a successor, written with the named
`cond`/`acc`. -/
theorem state_succ (n : ℕ) :
    state V enum (n + 1) =
      if cond V enum n then (enum (n + 1), acc V enum n ∩ enum (n + 1)) else state V enum n :=
  rfl


-- @@ L113-115 verbatim
theorem Y_succ_pos {n : ℕ} (h : cond V enum n) : Y V enum (n + 1) = enum (n + 1) := by
  change (state V enum (n + 1)).1 = enum (n + 1)
  rw [state_succ, ite_eq_left h]


-- @@ L117-119 verbatim
theorem Y_succ_neg {n : ℕ} (h : ¬ cond V enum n) : Y V enum (n + 1) = Y V enum n := by
  change (state V enum (n + 1)).1 = (state V enum n).1
  rw [state_succ, ite_eq_right h]


-- @@ L121-124 verbatim
theorem acc_succ_pos {n : ℕ} (h : cond V enum n) :
    acc V enum (n + 1) = acc V enum n ∩ enum (n + 1) := by
  change (state V enum (n + 1)).2 = acc V enum n ∩ enum (n + 1)
  rw [state_succ, ite_eq_left h]


-- @@ L126-129 verbatim
theorem acc_succ_neg {n : ℕ} (h : ¬ cond V enum n) :
    acc V enum (n + 1) = acc V enum n := by
  change (state V enum (n + 1)).2 = (state V enum n).2
  rw [state_succ, ite_eq_right h]


-- @@ L131-143 verbatim
/-- `acc n = ⋂_{i<n+1} Yᵢ`: the carried intersection is exactly the prefix
intersection. -/
theorem acc_eq_interUpTo : ∀ n, acc V enum n = V.interUpTo (Y V enum) (n + 1) := by
  intro n
  induction n with
  | zero =>
    rw [acc_zero, interUpTo_succ, interUpTo_zero, Y_zero]
  | succ n ih =>
    rw [interUpTo_succ, ← ih]
    by_cases h : cond V enum n
    · rw [acc_succ_pos V enum h, Y_succ_pos V enum h]
    · rw [acc_succ_neg V enum h, Y_succ_neg V enum h]
      simp_all


-- @@ L145-145 verbatim
variable (henum : ∀ n, V.mem (enum n))

-- @@ L146-146 verbatim
include henum


-- @@ L148-156 verbatim
/-- Each `Yₙ` is a neighbourhood. -/
theorem Y_mem : ∀ n, V.mem (Y V enum n) := by
  intro n
  induction n with
  | zero => rw [Y_zero]; exact henum 0
  | succ n ih =>
    by_cases h : cond V enum n
    · rw [Y_succ_pos V enum h]; exact henum (n + 1)
    · rw [Y_succ_neg V enum h]; exact ih


-- @@ L158-170 verbatim
/-- The running intersection `acc n` is always a neighbourhood — the greedy choice
guarantees it.
This is the content of Scott's hint (consistency of the prefix). -/
theorem acc_mem : ∀ n, V.mem (acc V enum n) := by
  intro n
  induction n with
  | zero =>
    rw [acc_zero, Set.inter_eq_right.mpr (V.sub_master (henum 0))]
    exact henum 0
  | succ n ih =>
    by_cases h : cond V enum n
    · rw [acc_succ_pos V enum h]; exact h
    · rw [acc_succ_neg V enum h]; exact ih


-- @@ L172-177 verbatim
/-- `⋂_{i<n} Yᵢ` is always a neighbourhood. -/
theorem mem_interUpTo_Y : ∀ n, V.mem (V.interUpTo (Y V enum) n) := by
  intro n
  cases n with
  | zero => rw [interUpTo_zero]; exact V.master_mem
  | succ n => rw [← acc_eq_interUpTo V enum]; exact acc_mem V enum henum n


-- @@ L179-184 verbatim
/-- **Exercise 1.23 — the hint.** For every `n`, the prefix `Y₀, …, Y_{n-1}` is
consistent in
`𝒟`: its finite intersection is a neighbourhood, so it is its own common lower
bound. -/
theorem Y_prefix_consistent (n : ℕ) : V.Consistent (Y V enum) n :=
  ⟨V.interUpTo (Y V enum) n, mem_interUpTo_Y V enum henum n, subset_rfl⟩


-- @@ L186-203 verbatim
/-- **Exercise 1.23 — the greedy element.** The filter generated by all `Yₙ`:
`{X ∈ 𝒟 ∣ ⋂_{i<n} Yᵢ ⊆ X for some n}`. The prefix intersections `⋂_{i<n} Yᵢ` are a
descending
chain of neighbourhoods, so this is a genuine filter. -/
def greedyElement : V.Element where
  mem X := V.mem X ∧ ∃ n, V.interUpTo (Y V enum) n ⊆ X
  sub h := h.1
  master_mem := ⟨V.master_mem, 0, by rw [interUpTo_zero]⟩
  inter_mem := by
    rintro X X' ⟨hX, n, hn⟩ ⟨hX', m, hm⟩
    have hsub : V.interUpTo (Y V enum) (max n m) ⊆ X ∩ X' :=
      Set.subset_inter
        ((V.interUpTo_antitone (Y V enum) (le_max_left n m)).trans hn)
        ((V.interUpTo_antitone (Y V enum) (le_max_right n m)).trans hm)
    exact ⟨V.inter_mem hX hX' (mem_interUpTo_Y V enum henum (max n m)) hsub, max n m, hsub⟩
  up_mem := by
    rintro X X' ⟨_, n, hn⟩ hX' hsub
    exact ⟨hX', n, hn.trans hsub⟩


-- @@ L205-207 verbatim
/-- Every `Yₙ` belongs to the greedy element. -/
theorem greedyElement_mem_Y (n : ℕ) : (greedyElement V enum henum).mem (Y V enum n) :=
  ⟨Y_mem V enum henum n, n + 1, V.interUpTo_subset (Y V enum) (Nat.lt_succ_self n)⟩


-- @@ L209-212 verbatim
/-- The running intersection `acc n` belongs to the greedy element. -/
theorem greedyElement_mem_acc (n : ℕ) : (greedyElement V enum henum).mem (acc V enum n) := by
  refine ⟨acc_mem V enum henum n, n + 1, ?_⟩
  rw [acc_eq_interUpTo V enum]


-- @@ L214-214 verbatim
variable (hsurj : ∀ {X : Set α}, V.mem X → ∃ n, enum n = X)

-- @@ L215-215 verbatim
include hsurj


-- @@ L217-243 verbatim
/-- **Exercise 1.23 — `{Yₙ}` is a total element.** Maximality: if `z` extends the
greedy element
and `W ∈ z`, write `W = enum k` (surjectivity). For `k = 0`, `W = Y₀` is already
in the greedy
element. For `k = m+1`: either the greedy step *accepted* `enum k` (then `W = Y_k`
is in the
element), or it *rejected* it — but then `acc m ∩ enum k ∉ 𝒟`, contradicting that
both `acc m`
(in the greedy element, hence in `z`) and `W` lie in the filter `z`. -/
theorem greedyElement_isTotal : V.IsTotal (greedyElement V enum henum) := by
  intro z hz W hW
  obtain ⟨k, rfl⟩ := hsurj (z.sub hW)
  cases k with
  | zero =>
    have : Y V enum 0 = enum 0 := Y_zero V enum
    rw [← this]
    exact greedyElement_mem_Y V enum henum 0
  | succ m =>
    by_cases h : cond V enum m
    · have hYk : Y V enum (m + 1) = enum (m + 1) := Y_succ_pos V enum h
      rw [← hYk]
      exact greedyElement_mem_Y V enum henum (m + 1)
    · exfalso
      apply h
      have hacc_z : z.mem (acc V enum m) := hz _ (greedyElement_mem_acc V enum henum m)
      have : z.mem (acc V enum m ∩ enum (m + 1)) := z.inter_mem hacc_z hW
      exact z.sub this


-- @@ L245-275 verbatim
omit [DecidablePred V.mem] in
/-- **Exercise 1.23 — "all filters can be determined by sequences".** In a
countable system, every
filter `x` is the *limit family* of a sequence of neighbourhoods: take `sₙ = enum
n` whenever
`enum n ∈ x` and `sₙ = Δ` otherwise. Every member of `x` is some `enum k`
(surjectivity), so it is
caught by `s`; conversely each `sₙ ∈ x`, so anything above some `sₙ` is in `x`.
(Classical: it
selects the sequence by deciding membership in `x`.) -/
theorem filters_sequence_determined (x : V.Element) :
    ∃ s : ℕ → Set α, (∀ n, V.mem (s n)) ∧ ∀ Z, x.mem Z ↔ (V.mem Z ∧ ∃ n, s n ⊆ Z) := by
  classical
  refine ⟨fun i => if x.mem (enum i) then enum i else V.master, ?_, ?_⟩
  · intro n
    by_cases h : x.mem (enum n)
    · simp only [ite_eq_left h]; exact henum n
    · simp only [ite_eq_right h]; exact V.master_mem
  · intro Z
    constructor
    · intro hZ
      obtain ⟨k, hk⟩ := hsurj (x.sub hZ)
      have hxk : x.mem (enum k) := by rw [hk]; exact hZ
      refine ⟨x.sub hZ, k, ?_⟩
      simp_all
    · rintro ⟨hZmem, n, hn⟩
      have hsx : x.mem (if x.mem (enum n) then enum n else V.master) := by
        by_cases h : x.mem (enum n)
        · simp only [ite_eq_left h]; exact h
        · simp only [ite_eq_right h]; exact x.master_mem
      exact x.up_mem hsx hZmem hn


-- @@ L277-277 verbatim
end Exercise123


-- @@ L279-279 verbatim
end Domain.Neighborhood
