/-
Copyright (c) 2026 Kalle Kytölä. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kalle Kytölä
-/
module

public import LeanPool.VirasoroProject.HeisenbergAlgebra
public import LeanPool.VirasoroProject.IndexTri
public import LeanPool.VirasoroProject.LieVerma
public import Mathlib.Data.Int.ConditionallyCompleteOrder
import Mathlib.Algebra.EuclideanDomain.Field
import Mathlib.Algebra.Order.Ring.Star
import Mathlib.Analysis.Normed.Group.Basic
import Mathlib.Data.EReal.Operations
import Mathlib.Data.Int.Star
import Mathlib.Topology.Algebra.InfiniteSum.Order
import Mathlib.Topology.MetricSpace.Bounded


-- @@ L20-67 verbatim
/-!
# Verma modules for the Virasoro algebra

This file defines Verma modules used in Lie algebra representation theory.

## Main definitions

* `HasCentralCharge`: A typeclass for Vierasoro modules where the central element acts by
  multiplication by a particular scalar (the scalar is called the *central charge*).
* `heisenbergTri`: The triangular decomposition of the Heisenberg algebra whose positive (resp.
  negative) part is spanned by `Jₖ` with `k` positive (resp. negative) and the Cartan subalgebra
  is spanned by `J₀` and the central element `K`.
* `HeisenbergAlgebra.hw α`: The (highest) weight of the Heisenberg algebra specified by the
  value `α` of the charge (`J₀`-eigenvalue); the central element `K` is by convention normalized to
  have value `1`.
* `ChargedFockSpace α`: The charged Fock space representation of the Heisenberg algebra with
  charge (`J₀`-eigenvalue) `α`.
* `ChargedFockSpace.vacuum`: The vacuum vector (highest weight vector) of the charged Fock space.
* `VirasoroVerma.universalMap`: The universal property of the Virasoro Verma module:
  Given another module `M` over `𝓤 𝕜 (VirasoroAlgebra 𝕜)` and a "target" vector `hwv ∈ M` satisfying
  `Lₙ • hwv = 0` for all `n > 0`, `L₀ • hwv = h • hwv`, and `C • hwv = c • hwv`,
  one obtains an `A`-module map from the Verma module to `M` uniquely specified by the requirement
  `hwVec c h ↦ hwv`.

## Main statements

* `ChargedFockSpace.vacuum_cyclic`: The charged Fock space is generated by its vacuum vector.
* `TriangularDecomposition.VermaHW.cartan_smul_hwVec`: The highest weight vector of a Verma module
  is an eigenvector of the Cartan subalgebra with the eigenvalues specified by the highest weight.
* `ChargedFockSpace.jgen_pos_vacuum`: The highest weight vector of a Virasoro Verma module
  is annihilated `Jₖ` for `k > 0`.
* `ChargedFockSpace.jgen_zero_smul`: The Heisenberg generator `J₀` acts as scalar `α` (the charge)
  on the charged Fock space.
* `ChargedFockSpace.kgen_smul`: The central element `K` acts as scalar `1` in the charged Fock
  space.
* `ChargedFockSpace.eventually_jgen_smul_eq_zero`: The charged Fock space satisfies the local
  truncation condition (which is needed, e.g., for the Sugawara construction).

## Implementation notes

The charged Fock space is defined as a Verma module for the Heisenberg Lie algebra (with an
appropriate triangular decomposition).

## Tags

Heisenberg algebra, Fock space

-/


-- @@ L69-69 verbatim
@[expose] public section




-- @@ L73-73 verbatim
namespace VirasoroProject


-- @@ L75-78 verbatim
open Module

-- `LieRing.ofAssociativeRing` is only a local instance in Mathlib; it provides the Lie ring
-- structure on the universal enveloping algebra, used for `LieHom.map_lie`.

-- @@ L79-79 verbatim
attribute [local instance 100] LieRing.ofAssociativeRing


-- @@ L81-81 verbatim
section HasCharge


-- @@ L83-83 verbatim
variable (𝕜 : Type*) [Field 𝕜] [CharZero 𝕜]

-- @@ L84-84 verbatim
variable (M : Type*) [AddCommGroup M] [Module 𝕜 M] [Module (𝓤 𝕜 (HeisenbergAlgebra 𝕜)) M]


-- @@ L86-87 verbatim
/-- A Heisenberg module where the central generator `K` acts by the scalar `1`. -/
abbrev HasUnitCentral := HasCentralValue 𝕜 (HeisenbergAlgebra 𝕜) M (.kgen _) 1


-- @@ L89-92 verbatim
lemma _root_.VirasoroProject.HasUnitCentral.kgen_smul [HasUnitCentral 𝕜 M] (v : M) :
    ιUEA 𝕜 (HeisenbergAlgebra.kgen 𝕜) • v = v := by
  nth_rw 2 [show v = (1 : 𝕜) • v by rw [one_smul]]
  exact HasCentralValue.central_smul ..


-- @@ L94-95 verbatim
/-- A Heisenberg module where `J₀` acts by the charge `α`. -/
abbrev HasCharge (α : 𝕜) := HasCentralValue 𝕜 (HeisenbergAlgebra 𝕜) M (.jgen _ 0) α


-- @@ L97-99 verbatim
lemma _root_.VirasoroProject.HasCharge.jgen_zero_smul {α : 𝕜} [HasCharge 𝕜 M α] (v : M) :
    ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 0) • v = α • v :=
  HasCentralValue.central_smul ..


-- @@ L101-101 verbatim
end HasCharge


-- @@ L103-103 verbatim
section ChargedFockSpace


-- @@ L105-105 verbatim
variable (𝕜 : Type*) [Field 𝕜] [CharZero 𝕜]


-- @@ L107-113 verbatim
open HeisenbergAlgebra in
/-- The triangular decomposition of the Heisenberg algebra with upper and lower (essentially
nilpotent) parts spanned by the `Jₖ` with positive and negative `k`, respectively, and the
Cartan subalgebra spanned by `J₀` and the central element `K`. -/
noncomputable def _root_.VirasoroProject.heisenbergTri :
    TriangularDecomposition 𝕜 (HeisenbergAlgebra 𝕜) :=
  TriangularDecomposition.ofBasis (basisJK 𝕜) indexTri pairwise_disjoint_indexTri iUnion_indexTri


-- @@ L115-120 verbatim
open HeisenbergAlgebra TriangularDecomposition in
lemma _root_.VirasoroProject.heisenbergTri_cartan :
    (heisenbergTri 𝕜).cartan = Submodule.span 𝕜 {.kgen 𝕜, .jgen 𝕜 0} := by
  simp only [heisenbergTri, indexTri, ofBasis, cartan]
  congr 1
  aesop


-- @@ L122-127 verbatim
open HeisenbergAlgebra TriangularDecomposition in
lemma _root_.VirasoroProject.heisenbergTri_upper :
    (heisenbergTri 𝕜).upper = Submodule.span 𝕜 ((fun n ↦ jgen 𝕜 n) '' {n | 0 < n}) := by
  simp only [heisenbergTri, indexTri, ofBasis, upper]
  congr 1
  aesop


-- @@ L129-134 verbatim
open HeisenbergAlgebra TriangularDecomposition in
lemma _root_.VirasoroProject.heisenbergTri_lower :
    (heisenbergTri 𝕜).lower = Submodule.span 𝕜 ((fun n ↦ jgen 𝕜 n) '' {n | n < 0}) := by
  simp only [heisenbergTri, indexTri, ofBasis, lower]
  congr 1
  aesop


-- @@ L136-141 verbatim
open HeisenbergAlgebra in
/-- The basis of the Cartan part of the Heisenberg triangular decomposition. -/
noncomputable def _root_.VirasoroProject.heisenbergTriCartanBasis :
    Basis ({none, some 0} : Set (Option ℤ)) 𝕜 (heisenbergTri 𝕜).cartan :=
  TriangularDecomposition.ofBasis.basisPart (HeisenbergAlgebra.basisJK 𝕜) indexTri
    pairwise_disjoint_indexTri iUnion_indexTri 0


-- @@ L143-147 verbatim
/-- The highest weight of Heisenberg algebra determined by charge `α` (`J₀`-eigenvalue).
The `K`-eigenvalue is by convention normalized to `1` by default. -/
noncomputable def _root_.VirasoroProject.HeisenbergAlgebra.hw (α : 𝕜) :
    (heisenbergTri 𝕜).cartan →ₗ[𝕜] 𝕜 :=
  (heisenbergTriCartanBasis 𝕜).constr (M' := 𝕜) 𝕜 (fun i ↦ if i.val = none then 1 else α)


-- @@ L149-151 verbatim
/-- The Heisenberg generator `K` as an element of the Cartan subalgebra. -/
noncomputable def _root_.VirasoroProject.heisenbergTriKgen : (heisenbergTri 𝕜).part 0 :=
  ⟨.kgen 𝕜, Submodule.mem_span_of_mem (by simp [indexTri])⟩


-- @@ L153-155 verbatim
/-- The Heisenberg generator `J₀` as an element of the Cartan subalgebra. -/
noncomputable def _root_.VirasoroProject.heisenbergTriJzero : (heisenbergTri 𝕜).part 0 :=
  ⟨.jgen 𝕜 0, Submodule.mem_span_of_mem (by simp [indexTri])⟩


-- @@ L157-158 verbatim
@[simp] lemma _root_.VirasoroProject.heisenbergTri_kgen_val
    : (heisenbergTriKgen 𝕜).val = .kgen 𝕜 := rfl

-- @@ L159-160 verbatim
@[simp] lemma _root_.VirasoroProject.heisenbergTri_jzero_val
    : (heisenbergTriJzero 𝕜).val = .jgen 𝕜 0 := rfl


-- @@ L162-172 verbatim
open HeisenbergAlgebra in
lemma _root_.VirasoroProject.heisenbergTri_cartan_basis_none_eq_kgen :
    (heisenbergTriCartanBasis 𝕜) ⟨none, Set.mem_insert none {some 0}⟩ = heisenbergTriKgen 𝕜 := by
  ext
  simp only [heisenbergTriCartanBasis, TriangularDecomposition.ofBasis.basisPart, indexTri,
             heisenbergTri_kgen_val]
  convert (basisJK 𝕜).basis_submodule_span_apply {none, some 0} ⟨none, Set.mem_insert none {some 0}⟩
  all_goals
    first
      | rfl
      | rw [HeisenbergAlgebra.basisJK_none]


-- @@ L174-186 verbatim
open HeisenbergAlgebra in
lemma _root_.VirasoroProject.heisenbergTri_cartan_basis_some_eq_jzero :
    (heisenbergTriCartanBasis 𝕜) ⟨some 0, by exact Set.mem_insert_of_mem none rfl⟩
      = heisenbergTriJzero 𝕜 := by
  ext
  simp only [heisenbergTriCartanBasis, TriangularDecomposition.ofBasis.basisPart, indexTri,
             heisenbergTri_jzero_val]
  convert (basisJK 𝕜).basis_submodule_span_apply {none, some 0}
          ⟨some 0, Set.mem_insert_of_mem none rfl⟩
  all_goals
    first
      | rfl
      | rw [HeisenbergAlgebra.basisJK_some]


-- @@ L188-190 verbatim
lemma _root_.VirasoroProject.heisenbergTri_kgen_mem_cartan :
    .kgen 𝕜 ∈ (heisenbergTri 𝕜).cartan := by
  simpa only [heisenbergTri_cartan] using Submodule.mem_span_of_mem (by simp)


-- @@ L192-194 verbatim
lemma _root_.VirasoroProject.heisenbergTri_jgen_zero_mem_cartan :
    .jgen 𝕜 0 ∈ (heisenbergTri 𝕜).cartan := by
  simpa only [heisenbergTri_cartan] using Submodule.mem_span_of_mem (by simp)


-- @@ L196-200 verbatim
lemma _root_.VirasoroProject.heisenbergTri_jgen_pos_mem_upper {n : ℤ} (n_pos : 0 < n) :
    .jgen 𝕜 n ∈ (heisenbergTri 𝕜).upper := by
  simp only [heisenbergTri_upper]
  apply Submodule.mem_span_of_mem
  exact (Set.mem_image ..).mpr ⟨n, ⟨n_pos, rfl⟩⟩


-- @@ L202-210 verbatim
lemma _root_.VirasoroProject.HeisenbergAlgebra.hw_apply_kgen (α : 𝕜) :
    HeisenbergAlgebra.hw 𝕜 α (heisenbergTriKgen 𝕜) = 1 := by
  rw [← heisenbergTri_cartan_basis_none_eq_kgen]
  simp only [HeisenbergAlgebra.hw, Basis.constr_apply_fintype]
  simp only [Basis.equivFun_self, smul_eq_mul, mul_ite, ite_mul, one_mul, zero_mul]
  rw [Finset.sum_eq_single ⟨none, Set.mem_insert none {some 0}⟩]
  · simp
  · simp_all
  · simp


-- @@ L212-220 verbatim
lemma _root_.VirasoroProject.HeisenbergAlgebra.hw_apply_jzero (α : 𝕜) :
    HeisenbergAlgebra.hw 𝕜 α (heisenbergTriJzero 𝕜) = α := by
  rw [← heisenbergTri_cartan_basis_some_eq_jzero]
  simp only [HeisenbergAlgebra.hw, Basis.constr_apply_fintype]
  simp only [Basis.equivFun_self, smul_eq_mul, mul_ite, ite_mul, one_mul, zero_mul]
  rw [Finset.sum_eq_single ⟨some 0, by exact Set.mem_insert_of_mem none rfl⟩]
  · simp
  · simp_all
  · simp


-- @@ L222-224 verbatim
/-- The charged Fock space with charge `α`. -/
abbrev _root_.VirasoroProject.ChargedFockSpace
    (α : 𝕜) := (heisenbergTri 𝕜).VermaHW (HeisenbergAlgebra.hw 𝕜 α)


-- @@ L226-228 verbatim
/-- The vacuum vector in the charged Fock space with charge `α`. -/
noncomputable abbrev _root_.VirasoroProject.ChargedFockSpace.vacuum (α : 𝕜) :=
   TriangularDecomposition.VermaHW.hwVec (HeisenbergAlgebra.hw 𝕜 α)


-- @@ L230-232 verbatim
lemma _root_.VirasoroProject.ChargedFockSpace.vacuum_cyclic (α : 𝕜) :
    Submodule.span (𝓤 𝕜 (HeisenbergAlgebra 𝕜)) {ChargedFockSpace.vacuum 𝕜 α} = ⊤ :=
  VermaModule.hwVec_cyclic ..


-- @@ L234-238 verbatim
/-- `Jₖ • vacuum(α) = 0` for `k > 0` -/
lemma _root_.VirasoroProject.ChargedFockSpace.jgen_pos_vacuum (α : 𝕜) {k : ℤ} (k_pos : 0 < k) :
    ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 k) • ChargedFockSpace.vacuum 𝕜 α = 0 :=
  TriangularDecomposition.VermaHW.upper_smul_hwVec
    (HeisenbergAlgebra.hw 𝕜 α) (E := .jgen 𝕜 k) (heisenbergTri_jgen_pos_mem_upper 𝕜 k_pos)


-- @@ L240-245 verbatim
lemma _root_.VirasoroProject.ChargedFockSpace.jgen_zero_vacuum (α : 𝕜) :
    ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 0) • ChargedFockSpace.vacuum 𝕜 α =
      α • ChargedFockSpace.vacuum 𝕜 α := by
  convert TriangularDecomposition.VermaHW.cartan_smul_hwVec
          (HeisenbergAlgebra.hw 𝕜 α) (H := .jgen 𝕜 0) (heisenbergTri_jgen_zero_mem_cartan 𝕜)
  exact (HeisenbergAlgebra.hw_apply_jzero 𝕜 α).symm


-- @@ L247-253 verbatim
lemma _root_.VirasoroProject.ChargedFockSpace.kgen_vacuum (α : 𝕜) :
    ιUEA 𝕜 (HeisenbergAlgebra.kgen 𝕜) • ChargedFockSpace.vacuum 𝕜 α =
      ChargedFockSpace.vacuum 𝕜 α := by
  have key := TriangularDecomposition.VermaHW.cartan_smul_hwVec
          (HeisenbergAlgebra.hw 𝕜 α) (H := .kgen 𝕜) (heisenbergTri_kgen_mem_cartan 𝕜)
  rw [← heisenbergTriKgen, HeisenbergAlgebra.hw_apply_kgen, one_smul] at key
  convert key


-- @@ L255-262 verbatim
/-- `J₀ • v = α • v` for all `v` in `ChargedFockSpace 𝕜 α` -/
lemma _root_.VirasoroProject.ChargedFockSpace.kgen_smul (α : 𝕜) (v : ChargedFockSpace 𝕜 α) :
    ιUEA 𝕜 (HeisenbergAlgebra.kgen 𝕜) • v = v := by
  have aux : ιUEA 𝕜 (HeisenbergAlgebra.kgen 𝕜) • ChargedFockSpace.vacuum 𝕜 α =
      (1 : 𝕜) • ChargedFockSpace.vacuum 𝕜 α := by
    rw [ChargedFockSpace.kgen_vacuum 𝕜 α, one_smul]
  simpa using UniversalEnvelopingAlgebra.smul_eq_of_cyclic_of_forall_lie_eq_zero
    _ _ (fun _ ↦ rfl) (ChargedFockSpace.vacuum_cyclic 𝕜 α) aux v


-- @@ L264-269 verbatim
/-- `J₀ • v = α • v` for all `v` in `ChargedFockSpace 𝕜 α` -/
lemma _root_.VirasoroProject.ChargedFockSpace.jgen_zero_smul (α : 𝕜) (v : ChargedFockSpace 𝕜 α) :
    (ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 0)) • v = α • v :=
  UniversalEnvelopingAlgebra.smul_eq_of_cyclic_of_forall_lie_eq_zero 𝕜
    (HeisenbergAlgebra 𝕜) (Z := .jgen 𝕜 0) (ζ := α) (HeisenbergAlgebra.lie_jgen_zero _)
    (ChargedFockSpace.vacuum_cyclic 𝕜 α) (ChargedFockSpace.jgen_zero_vacuum 𝕜 α) v


-- @@ L271-273 verbatim
/-- The charged Fock space with charge `α` has `K` action by unit scalar. -/
instance (α : 𝕜) : HasUnitCentral 𝕜 (ChargedFockSpace 𝕜 α) where
  central_smul' v := by rw [ChargedFockSpace.kgen_smul 𝕜 α v, one_smul]


-- @@ L275-277 verbatim
/-- The charged Fock space with charge `α` has charge `α`. -/
instance (α : 𝕜) : HasCharge 𝕜 (ChargedFockSpace 𝕜 α) α :=
  ⟨fun v ↦ ChargedFockSpace.jgen_zero_smul 𝕜 α v⟩


-- @@ L279-318 verbatim
open Filter in
lemma _root_.VirasoroProject.HeisenbergAlgebra.ueaEventually_commute_jgen
    (a : 𝓤 𝕜 (HeisenbergAlgebra 𝕜)) :
    ∀ᶠ k in atTop, Commute (ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 k)) a := by
  apply UniversalEnvelopingAlgebra.induction 𝕜 _
    (C := fun a' ↦ ∀ᶠ k in atTop, Commute (ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 k)) a')
  · intro r
    filter_upwards [Ioi_mem_atTop 0] with k k_pos
    exact (Algebra.commutes r _).symm
  · let whole := Submodule.span 𝕜 (Set.range (HeisenbergAlgebra.basisJK 𝕜))
    suffices ∀ X ∈ whole, ∀ᶠ k in atTop,
        Commute (ιUEA 𝕜 (HeisenbergAlgebra.jgen 𝕜 k)) (ιUEA 𝕜 X) from
      fun X ↦ this X (by simp [whole])
    apply Submodule.span_induction
    · intro Z ⟨i, hiZ⟩
      match i with
      | none =>
        simp only [← hiZ, HeisenbergAlgebra.basisJK_none]
        filter_upwards [Ioi_mem_atTop 0] with k k_pos
        exact (UniversalEnvelopingAlgebra.central_of_forall_lie_eq_zero 𝕜 (HeisenbergAlgebra 𝕜)
                (congrFun rfl) ((ιUEA 𝕜) (HeisenbergAlgebra.jgen 𝕜 k))).symm
      | some l =>
        simp only [← hiZ, HeisenbergAlgebra.basisJK_some]
        filter_upwards [Ioi_mem_atTop |l|] with k hk
        rw [commute_iff_lie_eq, ← LieHom.map_lie]
        have obs : ¬ k + l = 0 := by
          simp only [Set.mem_Ioi, abs_lt] at hk
          grind
        simp [HeisenbergAlgebra.lie_jgen, obs]
    · simp
    · intro a b a_mem b_mem ha hb
      filter_upwards [ha, hb] with k hka hkb
      simpa only [map_add] using Commute.add_right hka hkb
    · intro r a a_mem ha
      filter_upwards [ha] with k hka
      simpa only [map_smul] using Commute.smul_right hka _
  · intro a b ha hb
    filter_upwards [ha, hb] with k hka hkb using Commute.mul_right hka hkb
  · intro a b ha hb
    filter_upwards [ha, hb] with k hka hkb using Commute.add_right hka hkb


-- @@ L320-331 verbatim
open Filter HeisenbergAlgebra in
lemma _root_.VirasoroProject.ChargedFockSpace.eventually_jgen_smul_eq_zero
    (α : 𝕜) (v : ChargedFockSpace 𝕜 α) :
    ∀ᶠ k in atTop, (ιUEA 𝕜 (jgen 𝕜 k)) • v = 0 := by
  have aux : v ∈ Submodule.span (𝓤 𝕜 (HeisenbergAlgebra 𝕜))
      {ChargedFockSpace.vacuum 𝕜 α} := by
    simp [ChargedFockSpace.vacuum_cyclic 𝕜 α]
  obtain ⟨a, hav⟩ := Submodule.mem_span_singleton.mp aux
  filter_upwards [HeisenbergAlgebra.ueaEventually_commute_jgen _ a, Ioi_mem_atTop 0] with
    k hk k_pos
  rw [← hav, ← mul_smul, show _ * a = a * _ from hk, mul_smul,
      ChargedFockSpace.jgen_pos_vacuum _ _ k_pos, smul_zero]


-- @@ L333-333 verbatim
end ChargedFockSpace


-- @@ L335-335 verbatim
end VirasoroProject
