/-
Copyright (c) 2026 Shengtong Zhang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Shengtong Zhang
-/
module

public import LeanPool.BollobasNikiforov.CP.Basic
public import Mathlib.Topology.Instances.Matrix
public import Mathlib.Topology.Defs.Sequences
public import Mathlib.Topology.MetricSpace.Pseudo.Defs
import Mathlib.Analysis.Real.Sqrt
import Mathlib.LinearAlgebra.Matrix.FiniteDimensional
import Mathlib.Topology.Sequences


-- @@ L16-21 verbatim
/-!
# Compact generators and the closed CP cone

The rank-one generators of unit mass form a compact set `S` not containing `0`.
The completely positive cone is the cone generated by `S`, and is closed.
-/


-- @@ L23-23 verbatim
@[expose] public section


-- @@ L25-25 verbatim
open Matrix Set Filter

-- @@ L26-26 verbatim
open scoped Topology


-- @@ L28-28 verbatim
namespace BollobasNikiforov


-- @@ L30-30 verbatim
variable {n : Type*} [Fintype n] [DecidableEq n]



-- @@ L33-36 verbatim
omit [Fintype n] [DecidableEq n] in
variable [Finite n] in
instance : FirstCountableTopology (Matrix n n ℝ) :=
  inferInstanceAs (FirstCountableTopology (n → n → ℝ))


-- @@ L38-41 verbatim
omit [Fintype n] [DecidableEq n] in
variable [Finite n] in
instance : SequentialSpace (Matrix n n ℝ) :=
  inferInstanceAs (SequentialSpace (n → n → ℝ))


-- @@ L43-45 verbatim
/-- Nonnegative vectors of Euclidean mass `1`. -/
def nonnegativeUnitSphere : Set (n → ℝ) :=
  {p | 0 ≤ p ∧ ∑ i, p i ^ 2 = 1}


-- @@ L47-49 verbatim
/-- Rank-one CP generators of unit Frobenius mass. -/
def rankOneGenerators : Set (Matrix n n ℝ) :=
  (fun p : n → ℝ ↦ vecMulVec p p) '' nonnegativeUnitSphere


-- @@ L51-54 verbatim
omit [Fintype n] [DecidableEq n] in
lemma continuous_vecMulVec_self :
    Continuous fun p : n → ℝ ↦ vecMulVec p p :=
  continuous_id.matrix_vecMulVec continuous_id


-- @@ L56-66 verbatim
omit [DecidableEq n] in
lemma isClosed_nonnegativeUnitSphere : IsClosed (nonnegativeUnitSphere (n := n)) := by
  have hnn : IsClosed {p : n → ℝ | 0 ≤ p} := by
    have : {p : n → ℝ | 0 ≤ p} = univ.pi fun _ ↦ Ici (0 : ℝ) := by
      ext p
      simp [Pi.le_def]
    rw [this]
    exact isClosed_set_pi fun _ _ ↦ isClosed_Ici
  have hsph : IsClosed {p : n → ℝ | ∑ i, p i ^ 2 = 1} :=
    isClosed_eq (continuous_finsetSum _ fun i _ ↦ (continuous_apply i).pow 2) continuous_const
  exact hnn.inter hsph


-- @@ L68-77 verbatim
omit [DecidableEq n] in
lemma isCompact_nonnegativeUnitSphere : IsCompact (nonnegativeUnitSphere (n := n)) := by
  have hsub : nonnegativeUnitSphere ⊆ (univ.pi fun _ : n ↦ Icc (0 : ℝ) 1) := by
    intro p ⟨hp, hsq⟩ i _
    have hi : p i ^ 2 ≤ 1 := by
      have := Finset.single_le_sum (fun j _ ↦ sq_nonneg (p j)) (Finset.mem_univ i)
      exact this.trans_eq hsq
    exact ⟨hp i, (sq_le_one_iff₀ (hp i)).1 hi⟩
  exact (isCompact_univ_pi fun _ ↦ isCompact_Icc).of_isClosed_subset
    isClosed_nonnegativeUnitSphere hsub


-- @@ L79-82 verbatim
omit [DecidableEq n] in
/-- CP06: the unit-mass rank-one generators are compact. -/
lemma isCompact_rankOneGenerators : IsCompact (rankOneGenerators (n := n)) :=
  isCompact_nonnegativeUnitSphere.image continuous_vecMulVec_self


-- @@ L84-88 verbatim
omit [DecidableEq n] in
lemma trace_eq_one_of_mem_rankOneGenerators {C : Matrix n n ℝ}
    (hC : C ∈ rankOneGenerators) : C.trace = 1 := by
  obtain ⟨p, ⟨_, hsq⟩, rfl⟩ := hC
  simpa [trace_vecMulVec, dotProduct, sq] using hsq


-- @@ L90-95 verbatim
omit [DecidableEq n] in
/-- CP06: the unit-mass rank-one generators do not contain the zero matrix. -/
lemma zero_notMem_rankOneGenerators : (0 : Matrix n n ℝ) ∉ rankOneGenerators := by
  intro h
  have := trace_eq_one_of_mem_rankOneGenerators h
  simp at this


-- @@ L97-99 verbatim
omit [Fintype n] [DecidableEq n] in
lemma isCompletelyPositive_zero : IsCompletelyPositive (0 : Matrix n n ℝ) :=
  ⟨0, fun a ↦ isEmptyElim a, fun a ↦ isEmptyElim a, by simp⟩


-- @@ L101-104 verbatim
omit [DecidableEq n] in
lemma trace_sum_vecMulVec {q : ℕ} (p : Fin q → n → ℝ) :
    (∑ a, vecMulVec (p a) (p a)).trace = ∑ a, ∑ i, p a i ^ 2 := by
  simp [trace_sum, trace_vecMulVec, dotProduct, sq]


-- @@ L106-183 verbatim
omit [DecidableEq n] in
/-- Drop linearly dependent rank-one summands until at most `card n * card n` remain. -/
lemma exists_sum_vecMulVec_card_le (q : ℕ) (p : Fin q → n → ℝ) (hp : ∀ a i, 0 ≤ p a i) :
    ∃ q' ≤ Fintype.card n * Fintype.card n, ∃ p' : Fin q' → n → ℝ,
      (∀ a i, 0 ≤ p' a i) ∧
      ∑ a, vecMulVec (p a) (p a) = ∑ a, vecMulVec (p' a) (p' a) := by
  refine Nat.strongRecOn q (motive := fun q ↦ ∀ (p : Fin q → n → ℝ),
      (∀ a i, 0 ≤ p a i) →
      ∃ q' ≤ Fintype.card n * Fintype.card n, ∃ p' : Fin q' → n → ℝ,
        (∀ a i, 0 ≤ p' a i) ∧
        ∑ a, vecMulVec (p a) (p a) = ∑ a, vecMulVec (p' a) (p' a)) ?_ p hp
  intro q ih p hp
  by_cases hq : q ≤ Fintype.card n * Fintype.card n
  · exact ⟨q, hq, p, hp, rfl⟩
  · have hqpos : 0 < q := by
      have : 0 ≤ Fintype.card n * Fintype.card n := Nat.zero_le _
      omega
    obtain ⟨k, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hqpos.ne'
    have hfr : Module.finrank ℝ (Matrix n n ℝ) = Fintype.card n * Fintype.card n := by
      rw [Module.finrank_matrix, Module.finrank_self, mul_one]
    have hdep : ¬ LinearIndependent ℝ fun a : Fin (k + 1) ↦
        (vecMulVec (p a) (p a) : Matrix n n ℝ) := by
      intro hli
      have := hli.fintype_card_le_finrank
      simp only [Fintype.card_fin, hfr] at this
      exact hq this
    obtain ⟨g, hgsum, a_ne, hgne⟩ := Fintype.not_linearIndependent_iff.mp hdep
    let g' : Fin (k + 1) → ℝ := if ∃ a, 0 < g a then g else -g
    have hg'sum : ∑ a, g' a • vecMulVec (p a) (p a) = 0 := by
      dsimp [g']
      split_ifs
      · exact hgsum
      · simpa [neg_smul, Finset.sum_neg_distrib] using congrArg Neg.neg hgsum
    have hg'pos : ∃ a, 0 < g' a := by
      dsimp [g']
      split_ifs with h
      · exact h
      · push Not at h
        exact ⟨a_ne, neg_pos.mpr (lt_of_le_of_ne (h a_ne) hgne)⟩
    obtain ⟨a0, ha0max⟩ := Finite.exists_max g'
    obtain ⟨apos, hapos⟩ := hg'pos
    have ha0pos : 0 < g' a0 := lt_of_lt_of_le hapos (ha0max apos)
    let α : ℝ := (g' a0)⁻¹
    have hα : 0 ≤ α := inv_nonneg.mpr ha0pos.le
    have hcoeff (a : Fin (k + 1)) : 0 ≤ 1 - α * g' a := by
      rw [sub_nonneg]
      calc
        α * g' a ≤ α * g' a0 := mul_le_mul_of_nonneg_left (ha0max a) hα
        _ = 1 := inv_mul_cancel₀ ha0pos.ne'
    have ha00 : 1 - α * g' a0 = 0 := by
      rw [inv_mul_cancel₀ ha0pos.ne', sub_self]
    let p' : Fin k → n → ℝ := fun i ↦
      √(1 - α * g' (a0.succAbove i)) • p (a0.succAbove i)
    have hp' : ∀ a i, 0 ≤ p' a i := fun a i ↦
      mul_nonneg (Real.sqrt_nonneg _) (hp _ _)
    have hred : ∑ a, vecMulVec (p a) (p a) = ∑ a, vecMulVec (p' a) (p' a) := by
      have hscale : ∑ a, (1 - α * g' a) • vecMulVec (p a) (p a) =
          ∑ a, vecMulVec (p a) (p a) := by
        simp only [sub_smul, one_smul, Finset.sum_sub_distrib]
        have : ∑ a, (α * g' a) • vecMulVec (p a) (p a) =
            α • ∑ a, g' a • vecMulVec (p a) (p a) := by
          simp [mul_smul, Finset.smul_sum]
        rw [this, hg'sum, smul_zero, sub_zero]
      have hdrop : ∑ a, (1 - α * g' a) • vecMulVec (p a) (p a) =
          ∑ i : Fin k, (1 - α * g' (a0.succAbove i)) •
            vecMulVec (p (a0.succAbove i)) (p (a0.succAbove i)) := by
        rw [Fin.sum_univ_succAbove _ a0, ha00, zero_smul, zero_add]
      have hsqrt : ∀ i : Fin k,
          vecMulVec (p' i) (p' i) =
            (1 - α * g' (a0.succAbove i)) •
              vecMulVec (p (a0.succAbove i)) (p (a0.succAbove i)) := by
        intro i
        simp only [p', smul_vecMulVec, vecMulVec_smul, smul_smul]
        rw [Real.mul_self_sqrt (hcoeff _)]
      rw [← hscale, hdrop]
      exact Finset.sum_congr rfl fun i _ ↦ (hsqrt i).symm
    obtain ⟨q', hq', p'', hp'', hrec⟩ := ih k (Nat.lt_succ_self k) p' hp'
    exact ⟨q', hq', p'', hp'', hred.trans hrec⟩


-- @@ L185-192 verbatim
omit [DecidableEq n] in
lemma IsCompletelyPositive.exists_repr_card_le {C : Matrix n n ℝ}
    (hC : IsCompletelyPositive C) :
    ∃ q ≤ Fintype.card n * Fintype.card n, ∃ p : Fin q → n → ℝ,
      (∀ a i, 0 ≤ p a i) ∧ C = ∑ a, vecMulVec (p a) (p a) := by
  obtain ⟨q, p, hp, rfl⟩ := hC
  obtain ⟨q', hq', p', hp', heq⟩ := exists_sum_vecMulVec_card_le q p hp
  exact ⟨q', hq', p', hp', heq⟩


-- @@ L194-229 verbatim
omit [DecidableEq n] in
/-- A CP matrix is a sum of at most `card n * card n` nonnegative rank-ones, padded. -/
lemma IsCompletelyPositive.exists_repr_of_card {C : Matrix n n ℝ}
    (hC : IsCompletelyPositive C) :
    ∃ p : Fin (Fintype.card n * Fintype.card n) → n → ℝ,
      (∀ a i, 0 ≤ p a i) ∧ C = ∑ a, vecMulVec (p a) (p a) := by
  obtain ⟨q, hq, p, hp, rfl⟩ := hC.exists_repr_card_le
  set N := Fintype.card n * Fintype.card n
  let pPad : Fin N → n → ℝ := fun a ↦ if h : a.1 < q then p ⟨a.1, h⟩ else 0
  refine ⟨pPad, ?_, ?_⟩
  · intro a i
    dsimp [pPad]
    split_ifs
    · exact hp _ _
    · exact le_rfl
  · symm
    let e : Fin q ≃ { a : Fin N // a.1 < q } :=
      { toFun := fun i ↦ ⟨⟨i.1, Nat.lt_of_lt_of_le i.2 hq⟩, i.2⟩
        invFun := fun a ↦ ⟨a.1.1, a.2⟩
        left_inv := fun i ↦ by ext; rfl
        right_inv := fun a ↦ by ext; rfl }
    calc
      ∑ a, vecMulVec (pPad a) (pPad a)
          = ∑ a ∈ Finset.univ.filter fun a : Fin N ↦ a.1 < q,
              vecMulVec (pPad a) (pPad a) := by
            rw [← Finset.sum_filter_of_ne (p := fun a : Fin N ↦ a.1 < q)]
            intro a _ hne
            by_contra h
            exact hne (by simp [pPad, h])
      _ = ∑ a : { a : Fin N // a.1 < q }, vecMulVec (pPad a.1) (pPad a.1) :=
            Finset.sum_subtype _ (fun _ ↦ by simp) _
      _ = ∑ i, vecMulVec (p i) (p i) := by
            refine Fintype.sum_equiv e.symm _ _ ?_
            intro a
            have ha : a.1.1 < q := a.2
            simp [pPad, e, ha]


-- @@ L231-234 verbatim
omit [Fintype n] [DecidableEq n] in
lemma continuous_sum_vecMulVec {q : ℕ} :
    Continuous fun p : Fin q → n → ℝ ↦ ∑ a, vecMulVec (p a) (p a) :=
  continuous_finsetSum _ fun a _ ↦ (continuous_apply a).matrix_vecMulVec (continuous_apply a)


-- @@ L236-312 verbatim
omit [DecidableEq n] [Fintype n] in
variable [Finite n] in
/-- CP07: the completely positive cone is closed. -/
lemma isClosed_isCompletelyPositive :
    IsClosed {C : Matrix n n ℝ | IsCompletelyPositive C} := by
  cases nonempty_fintype n
  classical
  refine IsSeqClosed.isClosed ?_
  intro seq C hseq hlim
  set N := Fintype.card n * Fintype.card n
  choose p hp_heq using fun k : ℕ ↦ (hseq k).exists_repr_of_card
  have hp : ∀ k a i, 0 ≤ p k a i := fun k ↦ (hp_heq k).1
  have heq : ∀ k, seq k = ∑ a, vecMulVec (p k a) (p k a) := fun k ↦ (hp_heq k).2
  have htr : Tendsto (fun k ↦ (seq k).trace) atTop (𝓝 C.trace) :=
    ((continuous_id (X := Matrix n n ℝ)).matrix_trace.tendsto C).comp hlim
  obtain ⟨K, hK⟩ := Metric.tendsto_atTop.mp htr 1 one_pos
  let M : ℝ := |C.trace| + 1 + ∑ k ∈ Finset.range K, |(seq k).trace|
  have htr_le : ∀ k, (seq k).trace ≤ M := by
    intro k
    dsimp [M]
    have hnn : 0 ≤ (seq k).trace := by
      rw [heq, trace_sum_vecMulVec]
      exact Finset.sum_nonneg fun _ _ ↦ Finset.sum_nonneg fun _ _ ↦ sq_nonneg _
    by_cases hk : k < K
    · have hle : |(seq k).trace| ≤ ∑ i ∈ Finset.range K, |(seq i).trace| :=
        Finset.single_le_sum (fun i _ ↦ abs_nonneg (seq i).trace) (Finset.mem_range.mpr hk)
      calc
        (seq k).trace ≤ |(seq k).trace| := le_abs_self _
        _ ≤ ∑ i ∈ Finset.range K, |(seq i).trace| := hle
        _ ≤ |C.trace| + 1 + ∑ i ∈ Finset.range K, |(seq i).trace| := by
            linarith [abs_nonneg C.trace]
    · have hdist := hK k (le_of_not_gt hk)
      rw [Real.dist_eq] at hdist
      have hlt : (seq k).trace < |C.trace| + 1 := by
        have := (abs_lt.mp hdist).2
        linarith [le_abs_self C.trace]
      have hsum : 0 ≤ ∑ i ∈ Finset.range K, |(seq i).trace| :=
        Finset.sum_nonneg fun i _ ↦ abs_nonneg (seq i).trace
      linarith
  let R : ℝ := √(max M 0)
  have hp_box : ∀ k a i, p k a i ∈ Icc (0 : ℝ) R := by
    intro k a i
    refine ⟨hp k a i, ?_⟩
    have hsq : p k a i ^ 2 ≤ (seq k).trace := by
      rw [heq, trace_sum_vecMulVec]
      refine le_trans ?_ (Finset.single_le_sum
        (fun b _ ↦ Finset.sum_nonneg fun _ _ ↦ sq_nonneg _) (Finset.mem_univ a))
      exact Finset.single_le_sum (fun _ _ ↦ sq_nonneg _) (Finset.mem_univ i)
    have hle : p k a i ^ 2 ≤ max M 0 :=
      (hsq.trans (htr_le k)).trans (le_max_left _ _)
    refine (sq_le_sq₀ (hp k a i) (Real.sqrt_nonneg _)).1 ?_
    rwa [Real.sq_sqrt (le_max_right M 0)]
  let box : Set (Fin N → n → ℝ) :=
    univ.pi fun _ ↦ univ.pi fun _ ↦ Icc (0 : ℝ) R
  have hbox : IsCompact box :=
    isCompact_univ_pi fun _ ↦ isCompact_univ_pi fun _ ↦ isCompact_Icc
  have hp_mem : ∀ k, p k ∈ box := by
    intro k a _ i _
    exact hp_box k a i
  obtain ⟨plim, hplim, φ, hφ, hplim_tendsto⟩ := hbox.tendsto_subseq hp_mem
  have hplim_nonneg : ∀ a i, 0 ≤ plim a i := by
    intro a i
    have hmem : plim ∈ box := hplim
    simp only [box, Set.mem_pi, mem_univ, mem_Icc, forall_true_left] at hmem
    exact (hmem a i).1
  have hlimφ : Tendsto (seq ∘ φ) atTop (𝓝 C) :=
    hlim.comp hφ.tendsto_atTop
  have hsumlim : Tendsto (seq ∘ φ) atTop (𝓝 (∑ a, vecMulVec (plim a) (plim a))) := by
    have hfun : seq ∘ φ =
        (fun q : Fin N → n → ℝ ↦ ∑ a, vecMulVec (q a) (q a)) ∘ p ∘ φ := by
      funext k
      exact heq (φ k)
    rw [hfun]
    exact (continuous_sum_vecMulVec.tendsto plim).comp hplim_tendsto
  have hCeq : C = ∑ a, vecMulVec (plim a) (plim a) :=
    tendsto_nhds_unique hlimφ hsumlim
  exact ⟨N, plim, hplim_nonneg, hCeq⟩


-- @@ L314-314 verbatim
end BollobasNikiforov
